ui/src/app/shared/services/workflows-service.ts
Fixes #11419
- Make archived logs more human friendly
1. Fix the error message when we don't select a node.
2. Show `node.displayName` in logs.
I've checked regressions.
=> fix: make archived logs more human friendly in UI

server/workflow/workflow_server.go, server/workflowarchive/archived_workflow_server.go, workflow/controller/operator_test.go, workflow/creator/creator.go, workflow/creator/creator_test.go, workflow/util/util.go, workflow/util/util_test.go
Fixes #11414
There was a problem related to creator labels of a resubmitted Workflow.
When the creators of an existing Workflow and a new Workflow, created by resubmission, are different, incorrect creator labels are propagated to the new Workflow. A detailed illustration is in https://github.com/argoproj/argo-workflows/issues/11414.
I modified `FormulateResubmitWorkflow` to apply the creator labels for the actual user who resubmits a Workflow by adding a context argument to the `FormulateResubmitWorkflow` function.
1. Submit a Workflow and resubmit one based on the just-submitted Workflow.
```yaml
$ argo submit wf-whalesay.yaml --token ${FOO_TOKEN}
Name:                hello-world-p485h …
```
=> fix: Apply the creator labels about the user who resubmitted a Workflow

docs/lifecyclehook.md
There is a typo in the documentation https://argoproj.github.io/argo-workflows/lifecyclehook/ :
>  Put differently, an exit handler is like a workflow-level LifecycleHook with an expression of workflow.status == "Completed" or workflow.status == "Failed" or workflow.status == "Error".
It should be workflow.status == "Succeeded"  and not "Completed"
- We can see here what the `workflow.status` values may be for exit handler: https://argoproj.github.io/argo-workflows/variables/#exit-handler
```md
| Variable | Description|
|----------|------------|
| `workflow.status` | Workflow status. One of: `Succeeded`, `Failed`, `Error` |
```
- Additionally, tested on my environment with argo-workflows v3.4.7
Changed word from "Completed" -> "Succeeded"
=> docs: fix typo exit handler status to Succeeded

docs/lifecyclehook.md
- this doc was using absolute links everywhere, but the convention is to use a relative link when possible
- i.e. examples use absolute links, but docs links should be relative
- this ensure the links work both on the website and on GitHub
- consistently, website links go to website, GH links go to GH
- and when editing the repo locally, it will redirect within the local repo itself as well
- _most_ of the absolute links referenced the website, but _one_ referenced GH
- meaning if you were reading the docs on GH, you'd get sent to the website most of the time
- and if you were reading on the website, that one link would send you to GH, confusingly
Stumbled upon this while verifying #11416, which I also happened to stumble upon
- Convert all docs links on the Lifecycle Hook page to be …
=> docs: use relative links in Lifecycle Hook

Makefile
Make sure that there are no version inconsistencies due to NPM global deps installed in the `Makefile` (which is used locally as well as in CI)
- This has been a bit concerning to me ever since I noticed the installs are not pinned 😅 
- This also makes the "# update this in Nix" comments make more sense as there's a version specified now
- add `@<version>` for each `npm i -g`
- use the versions from [`dev/nix/node-packages.nix`](https://github.com/argoproj/argo-workflows/blob/7f22085d16316bdd77bdb1060455140d9d6e1664/dev/nix/node-packages.nix#L853) and [`dev/nix/package.json#dependencies`](https://github.com/argoproj/argo-workflows/blob/7f22085d16316bdd77bdb1060455140d9d6e1664/dev/nix/package.json#L5)
Ran in my devcontainer successfully:
```bash
npm i -g markdown-spellcheck@1.3.1
npm i -g …
```
=> build: pin versions of NPM global deps in `Makefile`

config/config.go, config/retention_policy.go, docs/workflow-controller-configmap.yaml
Several configurations were missing, and, as a result, entirely undocumented
- several of these can be very useful for different use-cases, lack of docs makes these settings hard to discover
- addresses https://github.com/argoproj/argo-workflows/pull/11293#issuecomment-1622162284 and https://github.com/argoproj/argo-workflows/issues/8539
- add namespace, columns, podSpecLogStrategy, podGCGracePeriodSeconds, podGCDeleteDelayDuration, initialDelay, and retentionPolicy
- add comments for all of the above, primarily copying from `config.go`: https://github.com/argoproj/argo-workflows/blob/30a916880ff21027ad1004c4ae176037f1a956da/config/config.go#L22
- a few comments from other places, like `info.go` for Column: https://github.com/argoproj/argo-workflows/blob/8ec5623093181cfb5ef7c34a5df8a8c9172 …
=> docs: add all remaining controller configurations

docs/memoization.md, docs/work-avoidance.md, workflow/controller/dag.go, workflow/controller/operator_test.go, workflow/controller/steps.go
Please note: I am not totally in favour of this change, it makes memoization work without outputs and I'm not conviced this is actually healthy, but it's what people seem to expect. See the linked issues in the fixes list below.
This change will cause memoization to work for all step and dag tasks even without outputs. Note: They were working semi-erroneously for some dag tasks due to implicit outputs before this change.
Fixes #11280 (raised to cover this desire)
Fixes #10769 (already closed by documentation)
Partially addresses #10426: Dags will memoize now, but retries still won't - manually tested.
=> feat: Allow memoization without outputs

util/logs/log-k8s-requests.go
Implemented logging of throttling.
when a delay of more than 5 seconds occurs.
Fixes #11387 #11402 
To make it faster for users to notice when client-side throttling is happening.
Implemented to output a warning if latency is greater than 5 seconds when qps, burst is set very low
=> feat: logging for client-side throttling

.devcontainer/devcontainer.json, .devcontainer/pre-build.sh
Fixes #11439 
A container created by Devcontainer keeps resetting /etc/hosts whenever I reboot or restart the container.
.devcontainer/devcontainer.json
.devcontainer/pre-build.sh
~~.devcontainer/post-start.sh~~
To ensure this issue is fixed, I manually tested by running devcontainer commands that after I made this change.
I also tested with VsCode devcontainer extension.
=> fix: Devcontainer resets /etc/hosts (#11439)

cmd/argo/commands/retry.go, docs/cli/argo_retry.md, workflow/util/util.go, workflow/util/util_test.go
Fixes #11020 
As described in #11020 - I want to be able to retry successful workflow, given I specify explicitly `retrySuccessful` and node selector.
I added a condition to only fail the `FormulateRetryWorkflow` method if the original workflow is not Error/Failed **AND either `restartSuccessful==False` or `nodeFieldSelector` is empty**.
I verified it with local deployment + added tests for both cases (retry should fail for a successful run without those extra flags, retry should work for a successful workflow with those flags).
- ~I'm not completely sure about the error message (_"To retry either: (1) workflow must be Failed/Error (2) Provide also restartSuccessful and nodeFieldSelector value"_). Too long? understandable?~ changed it according to @terrytangyuan 's advise 🙏 
- I think …
=> feat: cli allow retry successful workflow if nodeFieldSelector is set. Fixes #11020)

.spelling, docs/resource-template.md, mkdocs.yml
- previously, the Template Types section of the User Guide never mentioned Resource Templates
- the Walk Through section of Getting Started did have a page on this though
- so just link the two together as that one already documents it in detail
- I felt like something was missing in this section, finally realized what 😅
- Was trying to find this doc while answering a question [on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1690286713376469?thread_ts=1690276970.326629&cid=C01QW9QSSSK) and went to Template Types only to not see it 💭 
- create a new Resource Template page under Template Types of the User Guide
- just link to the existing docs in the Walk Through 
- also add a version as all the Template Type pages have one
- this was released in a 2.0 alpha as part of #622
- …
=> docs: add Resource Template page

cmd/workflow-controller/main.go, workflow/controller/controller.go, workflow/cron/controller.go
=> feat: Expose the Cron workflow workers as argument

docs/quick-start.md, docs/running-locally.md
I noticed that Running Locally could use various improvements (grammar, style, links, formatting, etc) when I first read it (it was confusing, to say the least), and after reviewing #11405 I was reminded of this again. So went through the whole first half and made modifications
- use a warning box for nicer looking formatting than unicode
- clarify that dev container does not necessarily need VSCode given that there is a CLI
- it said this before, but the ordering of the wording made it confusing and easy to miss or misunderstand
- also use code backticks for `devcontainer` CLI as that is the name of the command (see k8s style guide: https://kubernetes.io/docs/contribute/style/style-guide/#code-style-inline-code)
- use "Dev Container" as the proper noun when referring to the tool in …
=> docs: improve Quick Start and Running Locally

hack/what-to-cherry-pick.sh
This was brought up in https://github.com/argoproj/argo-workflows/pull/11276#issuecomment-1655545804 (thanks @cbuchli for reporting!).
We missed certain fixes in patch releases. Some examples:
```
137d5f8cc fix(controller): Enable dummy metrics server on non-leader workflow controller (#11295)
6f1cb4843 fix(windows): Propagate correct numerical exitCode under Windows (Fixes #11271) (#11276)
48097ea0b fix(controller): Drop Checking daemoned children without nodeID (Fixes #10960) (#10974)
10111724b fix(agent): no more requeue when the node succeeded (#10681)
f62472a69 fix(ui): reword Workflow `DELETED` error (#10689)
7d2a8c3d2 fix(docs): container-set-template workflow example (#10452)
2a0e91b44 fix(controller): Add locking for read operationin controller. Fixes #… (#9985)
```
=> chore: Commits with parenthesis after prefix should also be cherry-picked

dev/nix/README.md, docs/running-nix.md
There is already documentation for this, so just link to [the existing docs](https://argoproj.github.io/argo-workflows/running-nix/)
- just handy to have a back-link for those less familiar with Nix and who stumble upon it
- Similar to #10969
- add a README with a one-line link to `dev/nix/`
- also improve some grammar and formatting in the Nix docs
- use code backticks for all commands
- use markdown convention of using `1.` for all items of an ordered list and having the renderer determine the numbering
- use the name of the doc (Running Locally) instead of "this"
- more consistent with the rest of the docs, as well as k8s style guide: https://kubernetes.io/docs/contribute/style/style-guide/#links
- also merge 1 and 2 as they're both mentioned in Running Locally
- separate run-on …
=> docs: add a README to the Nixfiles, improve formatting

ui/src/app/workflows/components/workflow-filters/workflow-filters.scss, ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx
Fixes #11476 
The date filter is a crucial element when viewing the list of workflows. However, when clicking on the date-picker to change the date, the styles get messed up, resulting in a UI state where the filter functionality cannot be used properly. Moreover, the close button overlaps with the selected date, making it difficult to select the desired date.
This issue is more related to layout and styles rather than a major functional problem. Therefore, we plan to make the following two modifications:
1. Move the close button to the right so that it doesn't overlap with the date-picker.
2. Adjust the styles of the date-picker using the calendar to ensure proper functionality.
=> fix: Datepicker Style Malfunction Issue. Fixes #11476

ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx
Fixes #11494 
In workflowDrawer, which can be accessed by clicking 'SHOW' text in workflow row, there is an information link about resource duration as the screen capture below.
This information link should go to `https://github.com/argoproj/argo-workflows/blob/master/docs/resource-duration.md` when click this, but this is broken.
When click this, it just goes to workflow detail page which is same behavior of clicking the row.
I just add simple stop propagation in <a> tag. This will prevent 'i' icons from parent row clicking event propagation. 
Simply test this in workflow page UI.
=> fix: Fixed UI workflowDrawer information link broken. Fixes #11494

docs/access-token.md, docs/argo-server-sso.md, docs/walk-through/artifacts.md, docs/walk-through/hardwired-artifacts.md
Simplify some misc docs and use more consistent style & formatting
- Just stumbled upon these while making other changes or responding to questions on Slack and put a few small adjustments from different pages together into one PR
- per k8s style guide: https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language
- "almost certainly want to be able to" -> "likely want to"
- "getting list of" -> "listing"
- "from an existing namespace" -> "in a namespace" ("existing" is a necessary pre-req)
- by the same logic, remove some redundant words
- "With Argo" -> "" -- these are the Argo docs and they only reference Argo itself
- "we find" -> "" -- make the statement without prefacing it
- see also https://kubernetes.io/docs/contribute/style/style-guide/#avoid-using-we
- …
=> docs: improve directness and consistency of misc sentences

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go
Fixes #11512
Make `AzureArtifact.hasLocation` consistent with the other `hasLocation`s.
Added check for an endpoint to `hasLocation`. So an Azure Artifact is only considered to "have a location" if it has an endpoint, a container and a blob (key).
I ran `executor.TestWorkflowExecutor_LoadArtifacts`
=> fix: azure hasLocation incorporates endpoint. Fixes #11512

docs/fields.md, docs/intermediate-inputs.md, examples/Intermediate-parameters.yaml, examples/intermediate-parameters.yaml
- Modify examples for intermediate parameters
- Add example workflow.
- Fix docs to submit directly
- I submitted workflows by copy & paste
=> docs: Modify examples for intermediate parameters

.github/workflows/ci-build.yaml, test/e2e/testdata/workflow-templates/success-hook.yaml, test/e2e/workflow_template_test.go, workflow/util/merge.go, workflow/util/merge_test.go
Fixes #11521
- Ensure `target.spec.Hooks` in MergeTo is not nil when we should patch
- make(map) if  `target.spec.Hooks` is nil.
- Add corresponding tests.
- Create WorkflowTemplate  from #11521 and confirm submitted succesflly.
=> fix: Ensure target Workflow hooks not nil (#11521)

workflow/controller/operator.go, workflow/controller/operator_concurrency_test.go
Fixes #11219 
As it is described in issue #11219 , currently when using [Mutex](https://argoproj.github.io/argo-workflows/executor_swagger/#mutex) synchronization with [Memoization](https://argoproj.github.io/argo-workflows/fields/#memoize) cache, it seems working not correctly.
When running like the example in verification, two jobs related to same mutex and memozation works like this.
* job-1 runs first (acquire the key)
* when job-1 runs end, job-2 runs after that (no matter what memoization is)
**This means mutex synchronization is OK but memoization cache doesn't have an effect.**
However, the correct way I think how it works to be is,
* job-1 runs first, and write the memoization cache.
* when job-1 runs end, job-2 trys to run (acquire the key), but check the memoization.
* as …
=> fix: Fixed memoization is unchecked after mutex synchronization. Fixes #11219

test/e2e/hooks_test.go, test/e2e/workflow_configmap_substitution_test.go, test/e2e/workflow_inputs_orverridable_test.go
Relates #10807
- Fix flaky tests about lifecycle hooks
- Add sleep in main step to invoke `Running` lifecycle hook
- Same as #10898
- Wait after creating cm, since it fails several times.
- TestArgsValueFromParamsOverrideInputParamsValueFrom
- Wait 2 seconds for  `TestTemplateLevelHooksWaitForTriggeredHookAndRespectSynchronization`
- #11536
- https://github.com/argoproj/argo-workflows/actions/runs/5780166938/job/15663480943?pr=11536
Succeed 100% in 4x2+1=9 times
- https://github.com/argoproj/argo-workflows/actions/runs/5776394791/job/15655477551?pr=11534
- https://github.com/argoproj/argo-workflows/actions/runs/5776512356/job/15655733358?pr=11534
- https://github.com/argoproj/argo-workflows/actions/runs/5776793933/job/15656278721?pr=115 …
=> fix: Flaky test about lifecycle hooks

Dockerfile, go.mod, go.sum
We at LitmusChaos are using Argo-Workflows for orchestrating Chaos Experiments. We want to upgrade to latest version of Argo-Workflows & currently it's v3.4.9. On scanning via Twistlock, we found some vulnerabilities due to an old version of go - go1.20.4 & one due to an older version of go package - `https://github.com/emicklei/go-restful/v3`.
On checking, found that Dockerfile is using golang:1.20-alpine3.16, which is using go1.20.4. There are some vulnerabilities which were fixed in latest version i.e. `1.20.5`. Looks like golang:1.20-alpine3.16 is not getting build with latest version of go anymore.
```
+------------------+----------+------+-----------------------------------+---------+--------------------------+------------+------------+------------------------------------------------ …
```
=> fix: Added vulnerability fixes for gorestlful gopkg & OS vulnerabilities in golang:1.20-alpine3.16

manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/base/httpbin/httpbin-deploy.yaml
Fixes #10427
Run local development with httpbin on Mac M1 (ard64)
Replace out date image httpbin with ~~mccutchen/go-httpbin~~ kong/httpbin
Tested locally/manually + Run `make test`
=> fix: Switch to use kong/httpbin to support arm64. Fixes #10427

cmd/argoexec/commands/emissary_test.go, workflow/executor/os-specific/command.go, workflow/executor/os-specific/command_test.go
Fixes #11330
Outputs of the executed command are asynchronously read and copied to `cmd.Stdout`. `cmd.Stdout` must be closed after copies are done otherwise command outputs are gone. 
As described below, however, copies can never be end because sub-processes can keep running and can write to stdout indefinitely.
https://github.com/argoproj/argo-workflows/blob/6166464aa6961bcb375705753ed0b58707d68222/workflow/executor/os-specific/signal_darwin.go#L27-L38
`Wait()` is added to wait the copy.
`WaitDelay` is also added. It will close the pipes (stdout/stderr) of the executed command to stop sub-processes writing any more texts. 
Tests were added.
I also ran the following command for more than an hour.
```sh
$ docker run \
--rm -it \
--cpus 0.5 \
-e ARGO_CONTAINER_NAME=main \
-e …
```
=> fix: prevent stdout from disappearing in script templates. Fixes #11330

Dockerfile, go.mod, go.sum
Here from LitmusChaos Again!!
After our last PR - https://github.com/argoproj/argo-workflows/pull/11538 got merged, we scanned the latest images again, we found one more vulnerability in both workflow-controller and argoexec which may have been missed earlier - 
```
Scan results for: image [quay.io/argoproj/argoexec:latest] sha256:ee7f51a0169c160f6c04e4a85d3fddae14b5ff640d0b2202a8e8fb7ffc4ddef4
Vulnerabilities
+---------------+----------+------+--------------------------------+---------+-----------------------+-----------+------------+----------------------------------------------------+
|      CVE      | SEVERITY | CVSS |            PACKAGE             | VERSION |        STATUS         | PUBLISHED | DISCOVERED |                    DESCRIPTION                     | …
```
=> fix: Upgraded docker distribution go package to v2.8.2 for fixing a high vulnerability

docs/kubectl.md, docs/walk-through/argo-cli.md
- `kubectl` page referenced the CLI but did not link to it
- CLI page duplicated some of the content from the `kubectl` page instead of linking to it
- CLI page also did not link to the reference
- add link to CLI from `kubectl` page
- add link to `kubectl` page and CLI Reference from Argo CLI page
- remove duplicative `kubectl`
- split lines based on sentences instead of length as that is more maintainable
Checked that the links worked
=> docs: back-link the `kubectl` + Argo CLI pages

Makefile, dev/nix/flake.nix, sdks/java/Makefile, sdks/java/flake.lock, sdks/java/flake.nix, sdks/python/Makefile, sdks/python/flake.lock, sdks/python/flake.nix
Fixes #11443
Simple change that doesn't install some software is USE_NIX flag is set. 
Relies on the Nix installed software to perform it's tasks. 
This means that sudoless codegen, pre-commit can be trivially achieved. 
Also one further step in taking the Nix build process from bare-bones to production ready. 
Verified to be the same codegen output by running make codegen and comparing output.
=> feat: add support for codegen/pre-commit via Nix. Fixes #11443

server/apiserver/argoserver.go
Fixes https://github.com/argoproj/argo-helm/issues/2159, Fixes https://github.com/argoproj/argo-helm/issues/1624
- I root caused this in https://github.com/argoproj/argo-helm/issues/2159#issuecomment-1646988596
- the `ResourceCache` creates a `ServiceAccountLister` `informer`, but this is only used when RBAC is enabled
- if RBAC is not enabled, it is [not](https://github.com/argoproj/argo-workflows/blob/7f22085d16316bdd77bdb1060455140d9d6e1664/server/auth/gatekeeper.go#L300) [used](https://github.com/argoproj/argo-workflows/blob/7f22085d16316bdd77bdb1060455140d9d6e1664/server/auth/gatekeeper.go#L245), and so does not need to be created
- also, if RBAC is not enabled, the Server's `ClusterRole` should not require `serviceaccount` permissions
- without this change, whenever SSO is enabled, …
=> fix(server): don't grab SAs if SSO RBAC is not enabled

ui/src/app/webpack.config.js
Simplify the Webpack config a tiny bit after having to work with it for #11593 and #11585 
- makes it more similar to Argo CD's [current config](https://github.com/argoproj/argo-cd/blob/bfaac2b5ac4b96c8af8158902c1b086f7ced7389/ui/src/app/webpack.config.js#L10)
- using a `proxyConf` variable borrowed from there, though I thought that was a good simplification either way
- `console.log` statement is very similar now, though slightly modified wording ("in" -> "for")
- I was pretty confused by the `isProd= ` log before, thought it had some significance, and thought it might have an error (due to the space), but it was actually just a log statement. So make it more clear this way
- separate `from:` and `to:` to separate lines
- better readability and usually formatters have rules for this …
=> refactor(ui): simplify Webpack config a bit

ui/package.json
The Workflows UI and [`argo-ui`](https://github.com/argoproj/argo-ui) had the same name before, which made logs confusing and could potentially cause very wacky conflicts
- rename to `argo-workflows-ui` to match the current full name of the project (`argo-workflows` fka `argo`)
- also to match Argo CD's [UI name](https://github.com/argoproj/argo-cd/blob/e019b7fecba26d85dcf707dac0f0c76ca2025409/ui/package.json#L2)
- also alphabetize the `resolutions`
- normally deps are sorted alphabetically, so make `resolutions` the same for consistency
Install succeeds, build passes. Been working on my local, just split this out as a separate, independent PR
=> fix(ui): ensure `package.json#name` is not the same as `argo-ui`

cmd/argo/commands/delete.go
Reduces the complexity of code a tiny bit
- Noticed this while reviewing #11577 and #11557 
- invert the `if` conditional and `continue` early on it instead of having nesting with an `if` / `else`
No semantic changes, just stylistic changes. Unfortunately `delete` still does not have any tests though
"Ignore whitespace" makes [the diff](https://github.com/argoproj/argo-workflows/pull/11596/files?diff=unified&w=1) pretty easy to read and verify
=> refactor: remove nesting during dry-run of `argo delete`

cmd/argo/commands/delete.go, docs/cli/argo_delete.md
For https://github.com/argoproj/argo-workflows/issues/11555. @tooptoop4 wants to filter workflows more accurately and flexibly by status.
There are two supported flags associated with it: 
- `--field-selector`: `metadata.name=foo`, `metadata.namespace=bar`
- `--selector`: `workflows.argoproj.io/phase=Succeeded`
It is not feasible to use the `--field-selector` to filter workflows by status because of the [well-known reasons](https://github.com/kubernetes/kubernetes/issues/53459).
Using `-l(--selector)` would satisfy the need, but the labels are too long with a common prefix `workflows.argoproj.io/`. It is not convenient to use.
Luckily, `argo list` has a directly related flag `--status` to filter workflows by status like `argo list --status Running`. It is more convenient to use. I think …
=> feat(cli): Add a flag status to delete cmd like list cmd of argo cli

sdks/java/Makefile, sdks/python/Makefile
Due to docker running under root, it is necessary to modify the owner of the generated file.
Add --user with docker run
I've read [link](https://vsupalov.com/docker-shared-permissions/#set-the-docker-user-when-running-your-container)
bash and openapi-generator-cli works normally
=> build: run openapi-generator-cli in docker with current user.

go.mod, go.sum
Updates antonmedv/expr from v1.13 to v1.14 which has a [much richer language definition](https://expr.medv.io/docs/Language-Definition) and includes useful helpers such as `hasPrefix`, `max`
I think this will really help with simplifying workflows. I also think it will make the WorkflowEventBinding much more useful and reduce the need for argo-events webhook eventsource.
The other problem that this will solve is that our docs constantly refer to the expr project to see how to write expressions. But if we continue to use the old version, users will hit unexpected errors. e.g.:
```
Non-transient error: failed to evaluate workflow template expression: unable to evaluate expression 'hasPrefix(payload.Key, \"foo\") == true': reflect: call of reflect.Value.Call on zero Value (1:1)\n | …
```
=> feat: upgrade expr to v1.14 for richer language definition

ui/src/app/help/components/help.tsx
Fixes #11615 
I wanted to communicate when I wanted to ask questions or get help while using Argo workflow.
However, I accessed the contact field link on the help page, but was connected to the deleted argo workflow slack workspace. 😭
I think In order to smoothly maintain the Argo workflow ecosystem, a forum for active communication should be provided 💪
I simply modified the Contact link in the help.tsx source code among UI components.
Link (https://argoproj.slack.com/   ->  https://argoproj.github.io/community/join-slack/ (Changed))
=> fix: deprecated Link(Help-Contact) Issue

.devcontainer/devcontainer.json, .github/workflows/ci-build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, Dockerfile, Dockerfile.windows, go.mod, go.sum
Fixes #11556 
upgrade to go 1.21
I upgraded the go version by referring to the previous case PR #11027
=> fix: Upgrade Go to v1.21 Fixes #11556

workflow/util/util.go, workflow/util/util_test.go
Fixes #11631
- Override parameter when retrying workflow submitted from WorkflowTemplate
- Override `.Status.StoredWorkflowSpec.Arguments.Parameters` when overriding parameter.
Retry workflow submitted from WorkflowTemplate with parameter
```yaml
spec:
templates:
- name: argosay
inputs:
parameters:
- name: code
value: '{{workflow.parameters.code}}'
outputs: {}
metadata: {}
container:
name: main
image: argoproj/argosay:v2
command:
- sh
- '-c'
args:
- exit '{{workflow.parameters.code}}'
resources: {}
entrypoint: argosay
arguments:
parameters:
- name: code
```
```console
(⎈|k3d-k3s-default:argo)➜  argo-workflows git:(fix-11631) ./dist/argo retry exit-9xj9g --parameter code=0
INFO[2023-08-20T16:17:11.967Z] Deleting pod …
```
=> fix: override storedWorkflowSpec when override parameter (#11631)

ui/src/app/shared/services/workflows-service.ts, ui/src/app/shared/workflow-operations-map.tsx, ui/src/app/workflows/components/retry-workflow-panel.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/models/index.ts, ui/src/models/resubmit-opts.ts, ui/src/models/submit-opts.ts
Closes #10824
- Resubmit workflow with parameter in UI
- Pop up retry panel when we click retry buttom.
```yaml
spec:
templates:
- name: workflow
inputs:
parameters:
- name: flag
value: '{{workflow.parameters.flag}}'
outputs: {}
metadata: {}
steps:
- - name: success
arguments: {}
- name: fail
template: intentional-fail
arguments:
parameters:
- name: flag
value: '{{inputs.parameters.flag}}'
inputs: {}
outputs: {}
metadata: {}
container:
name: ''
command:
- sh
- '-c'
args:
- cowsay worl
resources: {}
- name: intentional-fail
inputs:
parameters:
- name: flag
outputs: {}
metadata: {}
container:
name: ''
command:
- sh
- '-c'
args:
- exit …
```
=> feat(ui): retry workflows with parameter (#10824)

dev/nix/flake.nix
Current `./dev/nix/flake.nix` is using go 1.19 for `pkgs.buildGoModule`, and the build fails.
Previously it worked well anyway, but after [this change](https://github.com/argoproj/argo-workflows/pull/11368/files#diff-b655785d3d88b4f926fa9bb629e20bee6b91d8f361832ba7942dfe266d0834beR21), the added `cmd.WaitDelay` makes the build completely fail on versions below go 1.20.
```sh
$ nix develop --extra-experimental-features nix-command --extra-experimental-features flakes ./dev/nix/ --impure
...
workflow/executor/os-specific/command.go:21:7: cmd.WaitDelay undefined (type *exec.Cmd has no field or method WaitDelay)
note: module requires Go 1.20
...
```
- Update `_module.args`, and add overlays for `go`, `buildGoModule` to use go 1.20.
- Update controller's `vendorSha256` hash
```sh
$ nix develop …
```
=> build: Fix nix build

workflow/controller/dag.go, workflow/controller/steps.go
Fixes #10173
Tested locally and verified to be correct.
=> fix: do not process withParams when task/step Skipped. Fixes #10173

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #11612 
Previous commit of #11456 PR makes some error as described in #11612.
When there is a memoization in template level, it seems memoization is not applied to child.
When running workflow like in Verification,
<< Correct - Before apply commit of #11456 >>
* First Run (without cache)
* Second Run (with cache)
<< Current >> 
* First Run (without cache) - Same
* Second Run (with cache) - **Broken**
It seems memoized template not escape the pending status.
So it is required for this to work as it works originally.
The reason why : I omitted the fulfilled condition of memoization in `executeTemplate`
BEFORE commiting #11456 , `executeTemplate` function In `operator.go` works like below.
(In aspect of working synchronization & memoization)
```go
// Original code before  #11456 …
```
=> fix: Fixed parent level memoization broken. Fixes #11612

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #11612 
This is cherry-pick of #11623 from master to release-3.4.11 branch
(Refer to #11648)
change woc.wf.Status.Nodes.Set(...) to woc.wf.Status.Nodes[...] to feat unsupported feature on release.
Same as #11623 
```go
kind: Workflow
metadata:
generateName: memoized-entrypoint-
spec:
entrypoint: entrypoint
templates:
- name: entrypoint
memoize:
key: "entrypoint-key-1"
cache:
configMap:
name: cache-top-entrypoint
outputs:
parameters:
- name: url
valueFrom:
expression: |
'https://argo-workflows.company.com/workflows/namepace/' + '{{workflow.name}}' + '?tab=workflow'
steps:
- - name: whalesay
container:
args: ["cowsay hello_world `date` > /tmp/hello_world.txt"]
outputs: …
```
=> fix: Fixed parent level memoization broken. Fixes #11612 (#11623)

docs/CONTRIBUTING.md
Fixes https://github.com/argoproj/argo-workflows/issues/11167.
=> docs: Add more links in contributor workshop

.spelling, docs/workflow-archive.md
See context in https://github.com/argoproj/argo-workflows/issues/3569#issuecomment-1688454810
=> docs: Add notes on IAM Auth for workflow persistence

.github/workflows/release.yaml
When I checked the log of release actions, I was initially puzzled to see that it was running actions/cache three times.
However, I found out that this is to use multiple caches, and I want to improve it so that it can be recognized right away in the log.
=> ci: Improved readability of log of release actions

cmd/argo/commands/stop.go, cmd/argo/commands/terminate.go, docs/cli/argo_stop.md, docs/cli/argo_terminate.md
Similar to #11625, this is another one of the most frequently asked questions by users and so could definitely use some clarification
- Following the same pattern as #11625, add a `Long` description to the CLI commands that details how `stop` and `terminate` work in more detail
- via `make codegen`, this resulted in a `### Synopsis` section in the generated docs as well, which is also helpful
Descriptions loosely follow the official issue response in https://github.com/argoproj/argo-workflows/issues/4454#issuecomment-721821469.
This is effectively a follow-up to #4653
- `make codegen` passes
- I wrote this as a "fix" commit so that it can be added as a patch to the CLI (and make it into any cherry-picks), but could make it a "docs" commit instead.
- Feel free to add more modifications to …
=> docs(cli): clarify `stop` v. `terminate` with `Long` descriptions

ui/package.json, ui/yarn.lock
- removing these has no impact on resolution, as can be seen in the `yarn.lock`
- any bumps in these deps will produce either the same minor or same major version (most are same minor version) -- i.e. no breaking changes
- basically, these are extraneous as of this time
Related to #11630, which removes unused deps; this removes unneeded `resolutions`
- remove resolutions for `@types/react`, `autolinker`, `fast-json-patch`, `lodash`, and `prismjs`
- did _not_ touch `semver` or `react-toastify`
- the `semver` resolution currently forces _all versions_ to the same as the resolution (including different majors, which can be seen [in the `yarn.lock`](https://github.com/argoproj/argo-workflows/blob/8a52da5e8ee6eeabffb6c7e5858702129b37b525/ui/yarn.lock#L8959))
- ~the `react-toastify` resolution …
=> chore(deps): remove unneeded Yarn resolutions

ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Potentially fix and surface the underlying issue in https://github.com/argoproj/argo-workflows/issues/11661.
=> fix(ui): Only redirect/reload to wf list page when wf deletion succeeds

dev/nix/flake.nix
Updates to mockery v2.26.0 (what is used in Makefile). 
Adds ldflags to ensure stdout is the same as official package when the command `mockery --version` is run.
=> feat: update nix version and build with ldflags

util/printer/workflow-printer.go, util/printer/workflow-printer_test.go
Fixes #10873.
Tools with `-o json` are expected to output to valid JSON. Same for YAML.
I kept the change minimal. Since `PrintWorkflows` fails fast at `len(workflows) == 0`, I stuck with that.
```
$ make dist/argo-linux-amd64
<...>
$ dist/argo-linux-amd64 -v list -o json
DEBU[2023-08-25T23:26:48.261Z] CLI version                                   version="{latest+9cc740c.dirty 2023-08-26T05:59:15Z 9cc740cc49a9ff91a955bd1356dbacb8dcf4fe50 untagged dirty go1.20.4 gc linux/amd64}"
DEBU[2023-08-25T23:26:48.261Z] Client options                                opts="(argoServerOpts=(url=,path=,secure=true,insecureSkipVerify=false,http=false),instanceID=)"
I0825 23:26:48.263036 1745777 loader.go:372] Config loaded from file:  /home/ag/.kube/config
I0825 23:26:48.264209 1745777 loader.go:372] …
```
=> fix: Print valid JSON/YAML when workflow list empty #10873

test/e2e/hooks_test.go, workflow/controller/dag.go
Fixes #11422 
- Change `node` in scope to `taskNode`
=> fix: Change node in paramScope to taskNode at executeDAG (#11422)

server/workflow/workflow_server.go, test/e2e/cli_test.go
This surfaces the underlying error. See https://github.com/argoproj/argo-workflows/issues/11661#issuecomment-1693722430
The new error message is: `workflows.argoproj.io "hello-world-2gs6g" not found rpc error: code = Internal desc = getting archived workflows not supported`
=> fix(server): Surface underlying error when getting a workflow

ui/src/app/cron-workflows/components/cron-workflow-spec-editior.tsx, ui/src/app/shared/components/checkbox-filter/checkbox-filter.tsx
Fixes #11685
Encountering some issues while using the Cron workflow feature.
1. When I enter the cron workflow, the lists are displayed, but all the filters are removed and set to default values. This can confuse users compared to having all the phases filters selected from the beginning. Therefore, the state of the cron workflow should start with all selections made.<img width="979" alt="스크린샷 2023-08-27 오전 2 14 12" src="https://github.com/argoproj/argo-workflows/assets/28799597/70122138-5bf9-484e-8a31-4e5860dce01f">
2. The second issue is related to modifying the cron in the cron workflow. The style of the Concurrency Policy is broken. The position and height of the Select box and Select arrow need to be adjusted.<img width="1177" alt="스크린샷 2023-08-27 오전 2 06 07" …
=> fix: cron workflow initial filter value. Fixes #11685

cmd/argo/commands/resubmit.go, cmd/argo/commands/retry.go, docs/cli/argo_resubmit.md, docs/cli/argo_retry.md
Fixes #10906
This is one of the most frequently asked questions by users and so could definitely use some clarification
- add a `Long` description to the CLI commands that details how `retry` and `resubmit` work in more detail
- via `make codegen`, this resulted in a `### Synopsis` section in the generated docs as well, which is also helpful
Descriptions loosely follow the official issue response in https://github.com/argoproj/argo-workflows/issues/2320#issuecomment-592060487 with some minor copy-edits, such as mentioning `resubmit`'s memoization functionality.
- `make codegen` passes
- I wrote this as a "fix" commit so that it can be added as a patch to the CLI (and make it into any cherry-picks), but could make it a "docs" commit instead.
- Feel free to add more modifications to the …
=> docs(cli): clarify the difference b/t `retry` and `resubmit`

ui/jest.config.js, ui/src/app/webpack.config.js
Consistent and correct formatting:
- `jest.config.js` had incorrect indentation, inconsistent keys, etc
- `webpack.config.js` had _mostly_ double quotes, but some single quotes and other inconsistencies
- use 2 space indentation, use unquoted keys
- consistently use double quotes as well
- convert most to double quotes for consistency
- the rest are converted in #11628 so as to not merge conflict
- alphabetize the `DefinePlugin` substitutions
- and consistently use double quoted keys for visual consistency -- this is a good bit easier on the eyes IMO
- also similar to [Argo CD config](https://github.com/argoproj/argo-cd/blob/6ca2e90b5094eba3878746fee5f2c357bfbc6cb8/ui/src/app/webpack.config.js#L66)
No semantic changes, just stylistic.
Build and tests continue to pass
To format config …
=> chore(ui): fix formatting errors in config

.github/workflows/ci-build.yaml, Makefile, ui/package.json, ui/yarn.lock
Use as few duplicates of dependencies as possible, reducing install size, memory usage, and bundle size
- See also https://github.com/atlassian/yarn-deduplicate#why-is-this-necessary and a PR from a repo I used to maintain: https://github.com/jaredpalmer/tsdx/pull/683
- Removes 700+ lines from the `yarn.lock` by condensing deps
- add a `deduplicate` script that uses `yarn-deduplicate`
- run `deduplicate` during `make lint` and UI CI
- I added this as another one-liner in `make lint` b/c that was honestly _much_ more readable than trying to do multi-line shell conditionals inside of a `Makefile` (which require `\` and `;` as they get interpreted [as a single line](https://stackoverflow.com/a/58602879/3431180))
- run `deduplicate` once and commit the results
- double-checked 50%+ of these …
=> ci(deps): dedupe `yarn.lock`, add check for dupes

docs/CONTRIBUTING.md, docs/running-locally.md
Fixes #11700
moved the policy regarding commits from when it was running locally to the contributor page and I have also improved some links related to commits
=> docs: moved the policy regarding commits from when it was running locally to the contributor page

workflow/executor/resource.go
May fix or alleviate issues like https://github.com/argoproj/argo-workflows/issues/11156 and https://github.com/argoproj/argo-workflows/issues/9934
We migrated to using `kubectl` as a package starting v3.4.7:
* v3.4.7: https://github.com/argoproj/argo-workflows/blob/v3.4.7/go.mod#L71
* v3.4.8: https://github.com/argoproj/argo-workflows/blob/v3.4.8/go.mod#L71
* master: https://github.com/argoproj/argo-workflows/blob/master/go.mod#L71
Before v3.4.7 we used `kubectl` binary ([ref1](https://github.com/argoproj/argo-workflows/blob/v3.4.6/Dockerfile#L82-L83), [ref2](https://github.com/argoproj/argo-workflows/blob/988706dd131cf98808f09fb7cc03780e2af94c73/workflow/executor/resource.go#L39))
`kubectl` binary uses uses higher values for discovery burst and QPS [since …
=> fix(workflow): match discovery burst and qps for `kubectl` with upstream kubectl binary

ui/src/app/shared/components/pagination-panel.tsx
Fixes #11702
Upon investigating the cause, it was found that when changing the pagination limit in the onChange function, the offset used as the pagination reference was not reset. Instead, the offset value received from the server was directly used.
As a solution, I have modified the onChange function to reset the offset during each change. This change ensures that when the pagination limit is modified, the search restarts from the beginning with the updated limit.
I just set offset '' in page limit onChange function.
1. Set the limit to 5 on the workflows page or workflow templates page from the frontend. and Click "Next Page."
2. While on the next page, change the limit to 10. they  appear.
=> fix: offset reset when pagination limit onchange

cmd/argo/commands/resume.go, cmd/argo/commands/suspend.go, docs/cli/argo.md, docs/cli/argo_resume.md, docs/cli/argo_suspend.md
Fixes #11511 
The CLI had incorrectly stated that `argo resume` could be used on a stopped workflow, resulting in confusion for some users, such as in #11511
- remove the "stopped" statement in `argo resume`
- specify that `resume` and `suspend` are opposites (and therefore unrelated to `stop` / `terminate`)
- `make codegen` passes
To make sure that `argo resume` does not affect stopped workflows, I looked through the source code:
- `stop` and `terminate` are two ["shutdown strategies"](https://github.com/argoproj/argo-workflows/blob/5eb50f42897e969995ad86eef764230e3a023641/pkg/apis/workflow/v1alpha1/workflow_types.go#L540) with minor differences
- the shutdown strategy is marked on a Workflow [via `spec.shutdown`](https://github.com/argoproj/argo-workflows/blob/524b4cb58672d07ce2ed9cff3dd …
=> docs(cli): a stopped workflow cannot be resumed

OWNERS
- to be in order of most to least privilege
- previously `reviewers` was in the middle, basically making it unordered
Stumbled upon this when looking at who had approver permissions (or CI retry permissions, to be specific) and was a bit disoriented by the (lack of) ordering. Thought I might as well fix it, especially after seeing that other Argo projects have a consistent order.
- move `reviewers` to the bottom. Order is now `owners` > `approvers` > `reviewers`
- matches [argoproj](https://github.com/argoproj/argoproj/blob/2f51907659dee1c11be2e69b0e36a6e2b7398c72/OWNERS) and [Argo CD](https://github.com/argoproj/argo-cd/blob/ef7f32eb844739d8ae5b5feb987f32fa63024226/OWNERS)
n/a. purely stylistic changes, no semantic changes
=> chore: reorder `OWNERS` file

ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Hopefully fixes #11661 
- Per my comments in https://github.com/argoproj/argo-workflows/pull/11676#discussion_r1306119462, workflow deletions happen asynchronously and were not waited on
- this meant that the error check could occur too early
- and that the page reload might occur too early, before the requests finished
- in particular, this scenario could happen on a higher latency connection (e.g. on a remote server, not running locally)
- I and others were not able to reproduce locally, but it was reliably reproduced in the issue (e.g. https://github.com/argoproj/argo-workflows/issues/11661#issuecomment-1691839976)
- if this were to happen, the UI would be dropping its connection and reconnecting during the reload
- if the connection were dropped while the request were in-flight, the …
=> fix(ui): don't reload the page until _after_ deletion

.spelling, docs/scaling.md
Fixes: https://github.com/argoproj/argo-workflows/issues/10566
Want to provide more information to those who are trying to scale Argo Workflows.
=> docs: Add some more info to the Scaling Doc

ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/shared/components/checkbox-filter/checkbox-filter.tsx
Fixes https://github.com/argoproj/argo-workflows/pull/11686#discussion_r1306692491
- Per my [review](https://github.com/argoproj/argo-workflows/pull/11686#discussion_r1306692491), #11686 used an anti-pattern of setting a prop based on another prop
- `CronWorkflowsList` now roughly matches how `WorkflowsList` [sets](https://github.com/argoproj/argo-workflows/blob/8e01696a9c63f25b3660ed479c6f7a57bb61d82d/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L120) its initial state (it _also_ uses `localStorage` & query params though)
- refactor `CheckboxFilter` to be a functional component
- this makes the anti-pattern more obvious (as it would be modifying arguments), as I mentioned in my [review comment](https://github.com/argoproj/argo-workflows/pull/11686#discussion_r13066924 …
=> fix(ui): don't use anti-pattern in CheckboxFilter

.github/workflows/ci-build.yaml
- it's timed out a [few](https://github.com/argoproj/argo-workflows/pull/11710#issuecomment-1698280827) [times](https://github.com/argoproj/argo-workflows/pull/11626#issuecomment-1685131400) on my PRs (as well as [others](https://github.com/argoproj/argo-workflows/pull/9805#issuecomment-1328566629))
- note that the `golangci-lint` is [set to `12m`](https://github.com/argoproj/argo-workflows/blame/c31132d6e123b95af7db2f7ddc1eaf5872513605/.golangci.yml#L3)
- `make lint` runs that and more, so it should always be _strictly greater than_ `golanci-lint`'s timeout
- and CI also runs `checkout` and `setup-go` on top of that as well
- Bump CI Lint timeout from 10 minutes to 15 minutes
- `golangci-lint`'s own timeout was already bumped recently as part of #11586
n/a, this is a pure CI change. CI …
=> ci: bump `lint` timeout to 15 minutes

workflow/controller/config.go
Fixes #11177
To simplify the workflow controller initDB function.
Reduced  `if else`, just return the `sqldb.NewMigrate(...)`.
After the code modification, tested the workflow-controller deployment in my environment with
multiple replicas (1, 5 and 10), all work ok.
10 for example:
```
workflow-controller-85bfb69457-292r6   1/1     Running   0          8s
workflow-controller-85bfb69457-5jc6l   1/1     Running   0          7s
workflow-controller-85bfb69457-b2fw2   1/1     Running   0          7s
workflow-controller-85bfb69457-kr4kv   1/1     Running   0          7s
workflow-controller-85bfb69457-lkz9r   1/1     Running   0          8s
workflow-controller-85bfb69457-ms5zf   1/1     Running   0          7s
workflow-controller-85bfb69457-qwcvx   1/1     Running   0          7s …
```
=> chore: Update workflow controller initDB func

ui/src/app/shared/pod-name.test.ts, ui/src/app/shared/pod-name.ts
Fixes #11764
- `Buffer` requires a polyfill in client-side JS
- #11628 upgraded to Webpack v5, which [no longer auto adds Node polyfills](https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed)
- which ended up breaking 2 year old code from #6925
- this seems to be the only one we use (as far as I can tell) -- and this code quite literally copies server-side Go code, so makes sense that it may use server-side libraries
- add comments in the code about where this is copied from so that it is easier to track (I had to go through the `blame` + commit history)
- use `charCodeAt` to extract an int from a character of a string instead of converting the string to a Buffer
- was inspired by looking at some JS FNV implementations and stumbled upon some lines like this: …
=> fix(ui): don't use `Buffer` for FNV hash

.github/workflows/ci-build.yaml, hack/recurl.sh, test/e2e/agent_test.go, test/e2e/signals_test.go
Partial fix for #10807
- signal_test.go was flaking quite a bit in CI
- examples (all same test, same error): [1](https://github.com/argoproj/argo-workflows/actions/runs/6090397163/job/16525212870?pr=11752), [2](https://github.com/argoproj/argo-workflows/actions/runs/6090397163/job/16525214144?pr=11752), [3](https://github.com/argoproj/argo-workflows/actions/runs/6057348108/job/16438451395?pr=11727), [4](https://github.com/argoproj/argo-workflows/actions/runs/6024154407/job/16342412510?pr=11716), [5](https://github.com/argoproj/argo-workflows/actions/runs/5910880044/job/16032931699?pr=11568), [6](https://github.com/argoproj/argo-workflows/actions/runs/5910880485/job/16032933770?pr=11567), [7](https://github.com/argoproj/argo-workflows/actions/runs/6066706542/job/16457612480), …
=> ci: reduce test & CI flakes with retries + longer waits & timeouts

workflow/controller/healthz.go
Fixes #11769
To fix the workflow controller crash on nil pointer.
Check if `wfc.wfInformer` is nil when calling healthz func.
After the code modification, tested the workflow-controller deployment in my environment with
multiple replicas (1, 5 and 10), all work ok.
10 for example:
```
workflow-controller-85bfb69457-2sgl8   1/1     Running   0          10m
workflow-controller-85bfb69457-8qdfq   1/1     Running   0          10m
workflow-controller-85bfb69457-95bc6   1/1     Running   0          10m
workflow-controller-85bfb69457-bmj2s   1/1     Running   0          10m
workflow-controller-85bfb69457-cmmkp   1/1     Running   0          10m
workflow-controller-85bfb69457-df4j6   1/1     Running   0          10m
workflow-controller-85bfb69457-fdng8   1/1     Running   0          10m …
```
=> fix: Workflow controller crash on nil pointer 

workflow/controller/taskresult.go
Potentially fixes #11607. This seems like a similar issue that we fixed in https://github.com/argoproj/argo-workflows/pull/11343.
=> fix: Correct limit in WorkflowTaskResultInformer List API calls. Fixes #11607

config/sso.go, server/auth/sso/sso.go
Fixes #10153 #9530
- Currently users logging in via SSO with lot of groups, exceed the 4KB Cookie limit
- This happens because we send the full set of claims as part of cookie
- Adding capability to filter sso groups matching a regex.
- This would eliminate all SSO groups which won't be used in SSO RBAC and reduce the number of groups in the authorization cookie
- Add a property `filterGroupsRegex ` in SSO config
- FIlter groups based on the property
- Tested locally with `filterGroupsRegex `
```
scopes:
- groups
- email
- profile
rbac:
enabled: true
filterGroupsRegex:
- ".*argowf.*"
```
=> feat: filter sso groups based on regex

.github/workflows/changelog.yaml, .github/workflows/ci-build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, .github/workflows/sdks.yaml, .github/workflows/snyk.yml
As nodejs v16 ends support on September 11th, we will upgrade checkout v3, which uses nodejs v16, to checkout v4, which uses nodejs v20.
https://endoflife.date/nodejs
checkout version from v3 to v4
=> ci: Bump checkout from v3 to v4

ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Another fix for #9696
- when date filters are removed, they are set to undefined
- the previous logic did not handle this correctly, comparing `undefined` with Dates    
- comparing to `undefined` _always_ returns `false`
- new logic only compares when Dates are set
- only compare the Dates when they are actually set, otherwise return `true`
Can see in the below screenshot (in React DevTools) that `minStartedAt` was set to `undefined` after I hit the "x" button on the date filter:
Made sure that `undefined` did in fact act weirdly, and here's results from browser console REPL:
```js
undefined < new Date()
// false
undefined > new Date()
// false
new Date() > undefined
// false
new Date() < undefined
// false
```
Tested manually in the UI and made sure it works as expected
=> fix(ui): handle `undefined` dates in Workflows List filter

test/e2e/cli_test.go, workflow/creator/creator.go, workflow/creator/creator_test.go, workflow/util/util.go, workflow/util/util_test.go
Relates #11148 
- Add resumer on suspended nodes message for auditing, and tracing purposes.
- Add message about resumed user to node status when resuming workflow.
- ![image](https://github.com/argoproj/argo-workflows/assets/83329336/5b9baa8a-2ebb-44a9-b4a4-33af7e59c8f8)
=> feat: Add user info to suspended node when resuming

test/e2e/workflow_configmap_substitution_test.go
See https://github.com/argoproj/argo-workflows/pull/11781#issuecomment-1712437382
```
=== RUN   TestConfigMapKeySelectorSubstitutionSuite/TestInvalidNameParameterSubstitution
Submitting workflow  workflow-template-configmapkeyselector-wf-
Waiting 1m0s for workflow metadata.name=workflow-template-configmapkeyselector-wf-m2hkg
✖ workflow-template-configmapkeyselector-wf-m2hkg Workflow 0s      invalid spec: templates.whalesay: failed to resolve {{ workflow.parameters.cm-name}","key":"msg"}}
workflow_configmap_substitution_test.go:141: condition never and cannot be met because the workflow is done
=== FAIL: WorkflowConfigMapSelectorSubstitutionSuite/TestInvalidNameParameterSubstitution
FAIL	github.com/argoproj/argo-workflows/v3/test/e2e	872.118s
```
=> test: Fix invalid parameter reference in TestInvalidNameParameterSubstitution

pkg/apis/workflow/v1alpha1/artifact_repository_types.go
Currently forward slash is appended regardless of whether it already presents in the repoURL.
=> fix: Only append slash when missing for Artifactory repoURL

docs/quick-start.md, docs/walk-through/argo-cli.md
Fixes #11750
Currently, when user want to install Argo CLI, it is quite hard to find.
This is not in [Argo CLI walk through](https://argoproj.github.io/argo-workflows/walk-through/argo-cli/), but in [Quick Start](https://argoproj.github.io/argo-workflows/quick-start/#install-the-argo-workflows-cli).
(You can find out that only some kind comments in Argo CLI walk through page are the only guide for the new users)
And still in Quick Start, it is just redirection to the [release note page](https://github.com/argoproj/argo-workflows/releases/tag/v3.3.10).
**I want to put this installation guides into documentation, in Argo CLI walk through page.**
In this way, the user who just pass quick guide and search with keyword 'Argo CLI' can find how to install this in walk through page.
I append the …
=> docs: Add more readable argo CLI installation guide. Fixes #11750

server/workflow/workflow_server_test.go
Fixes #11815
https://github.com/argoproj/argo-workflows/actions/runs/6166062084/job/16734921912
The mergeWithArchivedWorkflows test data was modified to match expected.
Since mergeWithArchivedWorkflows does not return sorted within the function, sort.Sort() was used for testing to match expected.
=> fix: fix mergeWithArchivedWorkflows test data to match expected

.spelling, docs/doc-changes.md
Update documentation guidelines to reference the much more detailed upstream k8s guidelines
- Stumbled upon this for the first time in a long while, during recent PR reviews for the Developer tab of the docs
- refer to the [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/), which is pretty highly quality with good examples
- and which I use often to guide my technical writing, including in many previous PRs to this repo
- remove duplicative content that is already mentioned in the k8s style guide, such as "avoid jargon"
- remove an example that contradicts the k8s style guide
- it actually should be "the Workflow" as it is an API object: https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects
- remove incorrect title-case …
=> docs: update style guidelines for documentation contributions

docs/public-api.md
- `manifests/README.md` just has a one-line link to the Installation docs
- instead of redirecting a contributor twice, just redirect once
- also follows existing pattern of the docs using relative links to other pages
Stumbled upon this for the first time recently during PR reviews for the Developer tab of the docs
Modify `public-api.md` to link to `installation.md` directly
- instead of `manifests/README.md` which [itself then links](https://github.com/argoproj/argo-workflows/blob/f00b6ff631bae954f749f52d2d94c5dbc6a0df53/manifests/README.md?plain=1#L3) to `installation.md`
`make docs` passes
=> docs: link to Installation instead of `manifests/README.md`

pkg/apiclient/http1/facade.go
Signed-off-by: Thearas <thearas850@gmail.com>
Close response body when request event-stream failed.
=> fix: close response body when request event-stream failed

ui/src/app/modals/new-version/new-version-modal.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Fixes #10821
Technically a follow-up to #8596
- Workflows being hidden behind a first-time user panel was confusing
- reported in #10821 with a few upvotes
- personally, I did not even realize that panel specified a new default, it just seemed like another unnecessary click when my cookies get cleared -- similar to the survey etc (i.e. #10826)
- Move the description of the new default instead to the New Version Modal
- and specify in **bold** that there is a new default
- unrelated: simplify some syntax in this file using optional chaining (from [investigating](https://github.com/argoproj/argo-workflows/issues/9696#issuecomment-1704688457) #9696)
1. Cleared cookies and loaded `/workflows`
1. Confirmed that New Version Modal has the new bullet point and has the new default in bold. 
1. …
=> fix(ui): merge WF List FTU Panel with New Version Modal

README.md, USERS.md
The latest survey result link is incorrect. Added the link to `USERS.md` as well.
=> docs: Fix links to community survey results

ui/src/app/workflows/components/resubmit-workflow-panel.tsx, ui/src/app/workflows/components/retry-workflow-panel.tsx, ui/src/app/workflows/components/submit-workflow-panel.tsx
Partial fix for https://github.com/argoproj/argo-workflows/issues/9810
Partial fix for https://github.com/argoproj/argo-workflows/issues/11740
- Use newer, modern functional components compatible with hooks instead of legacy class-based components
- `this.state` -> `useState`
- `this.props` -> `props`
- methods -> inner functions
- anonymous functions -> named functions
- chaining promise callbacks -> async/await & try/catch
- useMemo for optimization
- hoist up static variable out of component
- Mostly no real semantic changes
- manually tested in local environment
- submit panel
- resubmit panel
- retry panel
- https://github.com/argoproj/argo-workflows/pull/11800
=> refactor(ui): workflow panel components from class to functional

cmd/argo/commands/delete.go, cmd/argo/commands/list.go, cmd/argo/commands/list_test.go, ui/src/app/shared/utils.ts, ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Fixes #9696 (hopefully final fix for that -- this is not a partial fix, but a holistic fix), fixes #11671
Follow-up to #11792
Bring the UX of the CLI and the UI together and reduce a solid amount of user confusion about this
- UI should check against `metadata.creationTimestamp` and `status.finishedAt`, same as the CLI, not `status.startedAt`
- rename `minStartedAt` -> `createdAfter` and `maxStartedAt` -> `finishedBefore`
- modify `nullSafeTimeFilter` to use the same logic as the Go back-end
- remove the default 1 month filter on the UI
- it was different from the CLI, buggy, and caused confusion for users
- the date filter is also [entirely](https://github.com/argoproj/argo-workflows/pull/8596#discussion_r864319508) [client-side](https://github.com/argoproj/argo-workflows/blob/caedd0ff7ad …
=> fix: use same date filter in the UI and CLI

workflow/cron/operator.go, workflow/util/util.go, workflow/util/util_test.go
Fixes #11377 
If a CronWorkflow is set with a `ConcurrencyPolicy` of `ReplaceConcurrent`, the CronWorkflow Controller, when it fires, needs to first shut down any existing Workflows.
Right now there is the case in which it tries to shut down an existing Workflow, but by the time it reaches the logic to perform the shutdown, it finds that it's already been shut down. This results in an error. When the error is received by the CronWorkflow code, it does not proceed to launch the new Workflow.
If the Workflow was already shut down, don't consider that to be an error that prevents launching a new Workflow.
=> fix: shouldn't fail to run cronworkflow because previous got shutdown on its own (race condition)

ui/src/app/shared/components/resource-editor/resource-editor.tsx, ui/src/app/shared/components/tags-input/tags-input.tsx, ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx
Partial fix for #9810 
- Use newer, modern React hooks syntax instead of legacy React component lifecycle hooks
- Use newer, modern async/await syntax instead of Promise chains
Combined a few components together as previously requested. These are all components that make use of effects and other hooks (e.g. refs), but are not significantly complicated (unlike #11794, which is one complex component -- an entire page. and #11791 is all components _without_ effects).
Convert 3 components to use hooks: `ResourceEditor`, `WorkflowDrawer`, and `TagsInput`
- `this.props` -> `props`
- `this.state` -> `useState`
- simplify some callbacks now too
- `ref` -> `useRef`
- rename variables to clarify that these are refs which are accessed via `.current`
- `componentDidMount` -> …
=> refactor(ui): convert a few components to use hooks

workflow/controller/dag.go
Fixes #11843
When a node is not present in the nodes map, this implies that the DAG is still running. 
We errored out which is what causes #11843, this fixes that by assuming NodeRunning. 
Tested on the workflow posted in #11843
=> fix: when key not present assume NodeRunning. Fixes 11843

docs/cost-optimisation.md
Fixes #TODO
As platform owner we have enabled [Workflow Archive](https://argoproj.github.io/argo-workflows/workflow-archive/) in our company.
On the other hand, some developer set their CronWorkflow's history limits too large and caused a flood of (completed) pods and workflows, then as a result memory consumption of workflow-controller and other some controllers increased.
I took some times to identify the root cause is CronWorkflow's history limits (are too large, and large limit is not necessary ), so I'd like to suggest to refer that in cost-optimisation.md.
=> docs: add hint for limiting the number of wfs

ui/src/app/shared/components/base-page.tsx, ui/src/app/userinfo/components/user-info.tsx
Partial fix for #9810 
- Use newer, modern functional components compatible with hooks instead of legacy class-based components
- Use newer, modern async/await syntax instead of Promise chains
- also remove a deprecated usage of `BasePage`
- `BasePage` is a deprecated usage of `react-router`'s private context before React made context an official API (it's quite old)
- removing this is necessary to upgrade `react-router-dom` as the old, private context no longer exists in new versions
- I'm also in process of migrating its remaining usages to functional components, this is one of a few PRs to do so (the others are _significantly_ more complex, so I have split them out. See #11794)
- mostly straightforward state refactor from `this.state` to `useState`
- plus …
=> refactor(ui): migrate `UserInfo` to functional component

ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.scss, ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx, ui/src/app/workflows/components/workflows-row/workflows-row.tsx
Fixes #11706 
I want to check history about completed runs in each cron workflows.
You can check the history in cron workflow details page when you click specific cron-workflow.
Also, If the cron workflow doesn't have completed workflows, you can see explanation as above.
Local running
=> feat: show history about completed runs in each cron workflow

test/e2e/functional/stop-terminate.yaml
Relates #11880
Partial fix for #10807 
* Fix flaky test `TestStopBehavior`
* Ensure workflow-level hook is finished after template-level hook is finished.
=> ci: temporal workaround for flakiness of TestStopBehavior

workflow/controller/operator.go
Fixes #11853
When running multiple workflows with mutex synchronization and cache at the same time, there is an issue that mutex key is not released.
The first workflow will run correctly and release the keys, but the second workflow's 1st step will run but it does not release the key.
So this results in infinite pending nodes (like second workflow's 2nd or later nodes) as described in the issue.
Omitting releasing lock in [fulfilled node check after memo](https://github.com/argoproj/argo-workflows/blob/35e4b1700d09bf9359f31ec73f1b08061cfd4b58/workflow/controller/operator.go#L1958) in `executeTemplate` makes this problem.
When checking fulfilled node, this also should release any locks that this node have.
In `executeTemplate`,  lock is released at …
=> fix: Fixed running multiple workflows with mutex and memo concurrently is broken

docs/releases.md
I don't think we've been doing this.
=> docs: CVE fixes are not included in upgrading guide

ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx, ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-list/cluster-workflow-template-list.tsx, ui/src/app/event-sources/components/event-source-details/event-source-details.tsx, ui/src/app/shared/components/use-collect-event.ts, ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Use newer, modern async/await syntax instead of Promise chains
- convert promise chains -> async/await syntax
- this is largely cleaner, newer syntax, and easier to reason about
- for instance, there were a few `.then(set)` in a row which should now be [batched](https://react.dev/learn/queueing-a-series-of-state-updates#react-batches-state-updates) together
- they _may_ have been batched together before too, but not sure, as the chain could have resulted in callbacks being scheduled later, causing unnecessary re-renders
- also convert `services.info.collectEvent` -> `useCollectEvent` for consistency
- and slightly optimize this by removing the unnecessary `.then()`
- we don't do anything on `.then()` and the request is fired async with no await, so it's not needed …
=> refactor(ui): use async/await in several components

renovate.json
Fixes #11691
Uses renovate to keep `/dev/nix/flake.nix` up to date, issuing PRs whenever there is an update.
- @terrytangyuan installed Renovate into the repo
- This PR configures renovate to only monitor the above file and to issue PRs if a change is detected.
In my test environment you can see the renovate dependency dashboard proving that it's only looking at this file and won't affect anything else:
Tweaked until I was happy with the dependency dashboard locally. I have disabled the dashboard here (because it shows as another issue and will likely conflict with stalebot).
=> fix: Automate nix updates with renovate

README.md
Created OpenSSF Scorecard badge for project README.
This was requested by @agilgur5 as part of #9769
=> docs: Add OpenSSF Scorecard status badge to README.md

.github/workflows/changelog.yaml, .github/workflows/ci-build.yaml, .github/workflows/dependabot-reviewer.yml, .github/workflows/docs.yaml, .github/workflows/gh-pages.yaml, .github/workflows/pr.yaml, .github/workflows/sdks.yaml, .github/workflows/snyk.yml
- partly inspired by #11670
- as well as seeing users be confused by some steps
- `git diff --exit-code` had [some confusion](https://github.com/argoproj/argo-workflows/pull/10806#issuecomment-1537913872) in particular
- and me just reading more closely and wanting better descriptions (as I am working on a few CI changes)
- for example, I did not even realize that the steps after an E2E test failure were for debugging purposes until I read the CI code itself
- GH runs some post action hooks etc, so thought that was just clean-up or something
- add names to more steps & jobs in GH Actions Workflows
- specific names for all `git diff --exit-code` as per above
- names for Docs steps
- names PR Title check steps
- names for Snyk dependency scans workflow
- CI workflow names:
- all E2E test …
=> ci: better naming for various steps/jobs

ui/src/app/shared/components/input-filter.tsx, ui/src/app/workflows/components/workflow-timeline/workflow-timeline.tsx
Partial fix for https://github.com/argoproj/argo-workflows/issues/9810
> * [ ]  15. ui/src/app/shared/components/input-filter.tsx:
> * [ ]   44. ui/src/app/workflows/components/workflow-timeline/workflow-timeline.tsx:
- Use newer, modern functional components compatible with hooks instead of legacy class-based components
- `this.state` -> `useState`
- `this.props` -> `props`
- `useRef` to manage references to DOM elements 
- methods -> inner functions
- Mostly no real semantic changes
- manually tested in local environment
InputFilter
WorkflowTimeline
- https://github.com/argoproj/argo-workflows/pull/11800
- https://github.com/argoproj/argo-workflows/pull/11803
=> refactor(ui): InputFilter and WorkflowTimeline components from class to functional

ui/src/app/shared/workflow-operations-map.tsx, ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
Fixes #11905 
- browser [`confirm`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) is a blocking sync method; replace with the conventional and consistently styled `popup.confirm`
- `popup.confirm` creates an HTML modal instead
- this was the last place in the codebase that still used browser `confirm` and not `popup.confirm`
- in particular, as #11905 shows, browser `confirm` was causing the browser to allow users to disable the prompt, which would make it _impossible_ to confirm
- this is because, when there is an archived workflow, two `confirm`s would be used in a row -- one for the batch action and one for the archive delete
- the browser detects two in a row as possible spam / abuse, and has a checkbox to disable prompts for the entire site …
=> fix(ui): use `popup.confirm` instead of browser `confirm`

ui/src/app/workflows/components/workflows-row/workflows-row.tsx
`WorkflowsRow` could have styling issues when the message was too long
- cut it off at 180 chars
- tested with browser devtools on a 4k width screen and 180 was way more than it could display anyway inside 2 columns - so this is an overshoot
- note that per comment, this does _already_ have a CSS `text-overflow`, but when the message was _very_ long, it would still go beyond the width and cause styling issues
- so doubly cut it off with less than a line of JS
- also simplify `onChange` callback
- no need to wrap in an anonymous func
Before, with styling issues:
After, no styling issues and still properly overflows on a ~4k width screen:
=> fix(ui): ensure `WorkflowsRow` message is not too long

ui/src/app/workflows/components/workflow-node-info/workflow-node-info.scss, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
- it seems that with the [new version of `tippy`](https://github.com/argoproj/argo-ui/pull/297) (which was pulled in as part of #11585) the `overflow` property made it show up directly above the text (in the z direction)
- this meant that you could not click on the clipboard to copy because it would cover the icon 😕
This was found by a user and noted [on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1696440502865469). I then reproduced this myself, see below screenshot with incorrect positioning:
- the original PR #8947 that added `overflow` here was for horizontal scrolling for multi-line args in code blocks (`<pre>` elements)
- so I moved the `overflow` into the `pre` element's `class` more specifically and made it specific for the `x` direction
- note that these code …
=> fix(ui): `ClipboardText` tooltip properly positioned

ui/src/app/event-sources/components/event-source-list/event-source-list.tsx
Making sure that the highlighted section shows the same text for the Sensors page and the Event Source page (being 'Show event-flow page):
=> chore: Use same text for Sensors and Event Source

.github/workflows/ci-build.yaml
Partial Fixes #10807 
* `TestParallel` is flaky (It takes ~11sec although the test requires < 10s)
* https://github.com/argoproj/argo-workflows/blob/1a83117b1d45d3c52e8f5ea08c5929b5a4b45e6c/test/e2e/agent_test.go#L67
* Jobs
* https://github.com/argoproj/argo-workflows/actions/runs/6410678697/job/17404702303?pr=11945
* https://github.com/argoproj/argo-workflows/actions/runs/6440659448?pr=11839
* Change `E2E_ENV_FACTOR` to 2 (default is 1)
* https://github.com/argoproj/argo-workflows/blob/1a83117b1d45d3c52e8f5ea08c5929b5a4b45e6c/test/e2e/fixtures/e2e_suite.go#L41-L42
=> ci: E2E_ENV_FACTOR to 2 because TestParallel is very flaky

ui/src/app/shared/components/pagination-panel.tsx
When limiting the number of visible records in the workflow page, the pagination warning is now shown on all pages (not depending on the number of records on that page).
Fixes #11968
=> fix: show pagination warning on all pages (fixes #11968)

docs/walk-through/timeouts.md
Small follow-up to https://github.com/argoproj/argo-workflows/discussions/11940#discussioncomment-7187258, where I realized the "Timeout" page did not specify that the `activeDeadlineSeconds` field can be set in two different places: [Workflow-level](https://argoproj.github.io/argo-workflows/fields/#workflowspec) _and_ [template-level](https://argoproj.github.io/argo-workflows/fields/#template)
- show an example of both -- same example, just `activeDeadlineSeconds` in two different places
- move the field up a bit so it's more visible as well
- also [use active voice](https://kubernetes.io/docs/contribute/style/style-guide/#use-active-voice), per k8s style guide
n/a, docs change
=> docs: specify where `activeDeadlineSeconds` can be set

docs/metrics.md
Fixes a wrong anchor link for real-time-metrics.
=> docs: fix anchor for real-time-metrics

ui/src/app/modals/new-version/new-version-modal.tsx
For 3.4.12+: https://github.com/argoproj/argo-workflows/issues/11851#issuecomment-1741687882
Follow-up to #11742 and #11840
- I removed and fixed the UI date filter in #11840
- if that fix is going to go into 3.4.x, we should remove the "New default" notice in the New Version Modal as it no longer exists
- I added that notice in #11742 before I fixed & removed that default, but neither of those two commits have made it into a patch release yet
- so they can be "squashed" together and the "New default" removed as such
- Remove "New default" mention from the New Version Modal for 3.4
Ran `yarn lint`. Otherwise this is just a simple text change to a modal
=> fix(ui): remove "last month" default date filter mention from New Version Modal

.devcontainer/devcontainer.json, .spelling, docs/running-locally.md
Fixes #11423
Make contributing easier for many users and those without too powerful local specs! Lots of folks have wanted to use it in issues and on Slack, so hopefully this should be a big help! 🙂  
- Codespaces would run indefinitely on the `onCreateCommand` and never finish (seemingly due to `kit`? https://github.com/kitproj/kit/issues/44)
- also it would just eat up CPU hours on Codespaces, even if you closed the tab and turned off your computer
- had to manually go into Codespaces settings and turn it off after GH sent me an email that I used 24 CPU hours overnight while I was asleep 🫠
- use [`postCreateCommand`](https://containers.dev/implementors/json_reference/#lifecycle-scripts) instead of `onCreateCommand`
- `postCreateCommand` runs asynchronously _after_ the container is …
=> build: fix GH Codespaces building indefinitely

workflow/validate/validate.go, workflow/validate/validate_test.go
Fixes #11471 
As described in the above issue, it's currently pretty impossible to use `enum` fields and have `lint` pass. This makes them effectively useless in workflow templates.
Updated the enum checks in the validate code in order to respect `allowEmptyValues`.
Updated unit tests and tweaked code until they passed as expected.
=> fix: Permit enums w/o values. Fixes #11471.

workflow/executor/os-specific/command.go, workflow/executor/os-specific/command_unix.go, workflow/executor/os-specific/command_windows.go
windows based workflows already call .Wait() in signal_windows.go, calling it twice will result in not exiting at all.
Unix based workflows prevent that by releasing the process early on and checking exit code of all running processes.
Windows workflows don't do this and without knowing in-depth how windows processes work, I didn't find a way to achieve a similar "wait for all processes" syscall.
Fixes #11810
The windows-only bug got introduced with PR #11368 but wasn't catched because seemingly windows tests aren't run automatically. 
`simpleStart` is now os specific code and does not attach a WaitDelay nor a Wait to the closer function. 
Ran the changed code locally and ran the windows emissary command tests locally which now run through again.
=> fix(windows): prevent infinite run. Fixes #11810

ui/src/app/shared/components/pagination-panel.tsx
Fixes my review comment in https://github.com/argoproj/argo-workflows/pull/11973#discussion_r1353099743
Fixes #11968 without a regression
- example: if you're on the first page and your pagination limit is 50 while you only have 10 total workflows, then the warning shouldn't show, as you already see all 10 workflows
- this new logic should handle both the first page and the last page issues
- added a comment to word it out as well, which was actually very helpful in debugging and properly writing the logic (as it's a bit convoluted)
Tested manually. See https://github.com/argoproj/argo-workflows/pull/11973#discussion_r1353099743 for more details
Before:
After:
=> fix(ui): don't show pagination warning on first page if all are displayed

test/e2e/hooks_test.go
Almost same as #11384 
Remove flaky assertion which causes nil pointer dereference.
Partial fix for #10807 
```console
=== PASS: HooksSuite/TestTemplateLevelHooksDagSuccessVersion
suite.go:87: test panicked: runtime error: invalid memory address or nil pointer dereference
goroutine 583 [running]:
runtime/debug.Stack()
/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/stretchr/testify/suite.failOnPanic(0xc0006ba820, {0x1d5c7e0, 0x33ed890})
/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:87 +0x39
github.com/stretchr/testify/suite.Run.func1.1()
/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:183 +0x24c
panic({0x1d5c7e0?, 0x33ed890?})
/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f …
```
=> ci: remove flaky assertion from hook e2e test

docs/conditional-artifacts-parameters.md
Conditional Artifacts and Parameters docs had a sizeable amount of duplication about `expr` usage
- Stumbled upon this while answering some user questions
- remove duplication and instead link to the main Expression docs under Workflow Variables, which lists all of this information already and more
- also rewrite the first paragraph while at it
- use active voice, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-active-voice)
- use more direct language, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
n/a
=> docs: replace duplicate Expression docs with a link

api/jsonschema/schema.json, api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/controller_test.go
Fixes #11344
In the workflow_type.go file, the `VolumeClaimTemplates` within the `WorkflowSpec` type was defined as follows:
```go
VolumeClaimTemplates []apiv1.PersistentVolumeClaim `json:"volumeClaimTemplates,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,6,opt,name=volumeClaimTemplates"`
```
However, upon checking the `PersistentVolumeClaim` type, the type defined under "name" doesn't exist; instead, "name" exists within the "metadata" section.
```go
type PersistentVolumeClaim struct {
metav1.TypeMeta `json:",inline"`
// Standard object's metadata.
// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
// +optional
metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
// spec defines …
```
=> fix: remove WorkflowSpec VolumeClaimTemplates patch key

.github/workflows/ci-build.yaml, cmd/argo/commands/lint_test.go, cmd/argo/lint/formatter_pretty_test.go, cmd/argo/lint/lint_test.go, pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, util/archive/archive_test.go, workflow/artifacts/common/load_to_stream_test.go, workflow/common/ancestry_test.go, workflow/executor/executor_test.go, workflow/executor/os-specific/command_test.go, workflow/executor/resource_test.go, workflow/metrics/server_test.go, workflow/util/util_test.go
Fixes #11994
Add CI run for windows to improve reliability of new features/bugfixes on windows.
Adjusts several tests to ensure it works with windows.
Adds build flags to exclude running in windows where it does not make sense.
A few tests are flaky or not working yet and will need further tweaking.
Running `go test ./...`  on windows.
=> ci: add windows unit test run. Fixes #11994

ui/src/app/shared/services/workflows-service.ts
Today, if the Argo server fails to pull archived logs, it won’t use pod logs even if the pod still exists on the cluster. This means that in cases where the final upload fails due to streaming errors (or if the user’s SA does not have RBAC access to the artifact creds), Argo server will not display any logs for the workflow step after failing to retrieve archived logs even if the pod and its logs still exist on the cluster.
This PR adds a fallback to retrieve logs from live pods in those cases.
=> feat: Fall back to retrieve logs from live pods

workflow/controller/operator.go
Relates to #11451
After upgrading to v3.4.11, the error log is often reported from monitoring.
```
level=error msg="was unable to obtain node for " namespace=default workflow=hello-world-jq82w
```
When boundaryID is empty, we don't try to get node and also don't raise any error.
=> fix: suppress error about unable to obtain node

.github/workflows/ci-build.yaml
- windows unit tests (#12011) were merged shortly before my changes to skip tests (#12006) were merged
- they are new, so they also need a conditional now
- add a `needs` and an `if` section to the `tests-windows` job, same exact one as the one in `tests`
no new logic here as this exact conditional is already used for the `tests` job
- windows tests could potentially be optimized to run on a smaller set of changed files
- since they don't run _all_ unit tests, but only a subset of them
=> ci: also skip windows unit test runs based on diff

.github/workflows/changelog.yaml, .github/workflows/dependabot-reviewer.yml, .github/workflows/docs.yaml, .github/workflows/pr.yaml
Partial fix for #12031, Token Permissions
- This is an [OpenSSF Scorecard check](https://github.com/ossf/scorecard/blob/8eaf0d7647a3f50d80615812c72a277fd568fb6d/docs/checks.md#token-permissions): Token Permissions
- Not many changes required, but the ones made ensure that if a new GHA Job is added to an existing GHA Workflow, it will only have read-only permissions unless explicitly specified in the GHA Job itself
Basically follow the OpenSSF Scorecard directions
- default to `permissions.contents: read` for read-only permissions for a GHA Workflow
- this was missing from `pr.yaml` and was `write` for `docs.yaml`
- only add needed permissions per specific GHA Job
- move the `permissions.contents: write` for `docs.yaml` into the `docs:` Job
- also add comments for why all permissions are …
=> ci: ensure least privilege permissions for GHA tokens

docs/manually-create-secrets.md
- the [old link](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token)'s anchor/subheading is no longer correct, update it to the [correct current one](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount)
Stumbled upon this while responding to a user [on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1697738676287909?thread_ts=1697735798.105029&cid=C01QW9QSSSK)
- Updated link
- while at it, make some small copy-edits:
- rename the top heading from "Kubernetes Secrets" to "Service Account Secrets" - this page is not about all secrets, but specifically SA secrets
- NOTE: I did not change the actual link to this …
=> docs: correct link to k8s docs for manually creating Secrets

ui/yarn.lock
Partial fix for #12031, Vulnerabilities
- 77 vulns -> 1 vuln
- the 1 remaining is a dep of `swagger-ui-react`, which has it [pinned to a specific version](https://github.com/argoproj/argo-workflows/blob/5c264c094104645a4c917a9a23615424d564d1e4/ui/yarn.lock#L7702)
- see also https://github.com/argoproj/argo-workflows/pull/11418#issuecomment-1696260188; `swagger-ui-react` is blocked on upgrading due to other devDeps
- Some dependabot PRs have stalled because it's not deduplicating dependencies 😕 
- See https://github.com/argoproj/argo-workflows/pull/11728#issuecomment-1707477279
- Improve OpenSSF Scorecard Vulnerabilities check
- all but one of the vulns currently reported are in JS deps (the remaining one [is a vuln in the AWS Go SDK](https://osv.dev/list?ecosystem=&q=GO-2022-0646) with no …
=> chore(deps): automatically `audit fix` UI deps

README.md
Fixes #9769
- #12031 is a follow-up specific to the security scores
Proper version of #12023 that FOSSA made automatically on integration
- this is the last non-security check we need for CNCF CLOMonitor
- after this, all the non-security checks will be at 100%
- note that while we already use Snyk, it actually does not support Go dep badges: https://support.snyk.io/hc/en-us/articles/360003997277-Badge-Support-for-Repositories (see also https://github.com/cncf/clomonitor/issues/50#issuecomment-1039557687)
- so use FOSSA, which [Argo CD already uses](https://github.com/argoproj/argo-cd/blob/a9f03aa8ccdafc350b96ee90db054b11cad44692/README.md?plain=1#L11) and is already integrated into Argoproj
- we do also have some license checks to resolve there, I am working on those as well
- **EDIT**: …
=> docs: add FOSSA License Badge for CLOMonitor

ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx, ui/src/app/reports/components/reports.tsx
Fixes https://github.com/argoproj/argo-workflows/pull/11794#discussion_r1367772045
- when I refactored the `Reports` component in #11794, I accidentally left in the semi-colon from a copy+paste
- remove the accidentally rendered semi-colon
- also make some tiny optimizations while at it
- consolidate `CronWorkflowDetails`'s `openLink` function to also use `openLinkWithKey`
- yay no duplication!
- all the link behavior is now in one place, especially with this slightly complex function
- refactor const assigned to anonymous func -> named function for better tracing
tested locally, can confirm there is no semi-colon now 😅
=> fix(ui): remove accidentally rendered semi-colon

ui/package.json, ui/yarn.lock
Follow-up to #12036, where the last vulnerable UI dep was unable to be auto-fixed due to being pinned by `swagger-ui-react`
- Partial fix for #12031, Vulnerabilities -- this should be the last UI vuln fixed now
- Proper version of #12047, which did not deduplicate deps, use DCO, etc and wasn't tested
- there are still some build issues to resolve in order to move to 5.x.x, but in the interim, can move to latest 4.x.x
- in particular, this upgrade fixes an XSS CVE in a pinned dep of `swagger-ui-react`, `@braintree/santize-url`: https://security.snyk.io/vuln/SNYK-JS-BRAINTREESANITIZEURL-3330766
- see that it is pinned here, so we could not independently upgrade it without upgrading `swagger-ui-react` itself: https://github.com/argoproj/argo-workflows/blob/5c264c094104645a4c917a9a23615424d564 …
=> chore(deps): upgrade `swagger-ui-react` to latest 4.x.x

server/apiserver/accesslog/interceptor_test.go
This test verifies the behavior of an HTTP request interceptor. It ensures that the interceptor logs specific key-value pairs related to the request, then it calls the next handler correctly, and makes sure it logs the expected information in the correct format.
**I wrote this test because:**
- It is important to make sure the function is logging the right information. Testing it guarantees that the log output contains the correct data.
- Regression Prevention: Acts as a safety net, preventing regressions or unintended changes to the behavior of the interceptor as updates are being made to this repo.
Fixes #TODO
=> chore: adding test for Interceptor

ui/src/app/apidocs/components/apiDocs.tsx, ui/src/app/cron-workflows/components/pretty-schedule.tsx, ui/src/app/cron-workflows/components/schedule-validator.tsx, ui/src/app/event-flow/components/event-flow-details/event-flow-page.tsx, ui/src/app/reports/components/report-container.tsx, ui/src/app/reports/components/reports.tsx, ui/src/app/shared/components/chat-button.tsx, ui/src/app/shared/components/links.tsx, ui/src/app/shared/components/object-parser.ts, ui/src/app/shared/cron.tsx, ui/src/app/tsconfig.json, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Partial fix for #12059
- still more code splitting that can be done
- `swagger-ui-react` was one of the biggest dependencies and only used on the infrequently used `/apiDocs` page
- and it was the sole importer of large dependencies like `dompurify`, `immutable`, `redux`, etc
- shave off ~2MB / 826KB minified / 250KB gzipped from the main bundle
- `charts.js` was also one of the bigger deps and similarly only used on the infrequently used `/reports` page
- shave off ~525KB / 190KB minified / 60KB gzipped from the main bundle
- use `React.lazy` to lazy load them with dynamic imports
- and `React.Suspense` to add a fallback etc
- see https://react.dev/reference/react/lazy and https://webpack.js.org/guides/code-splitting/#dynamic-imports
- also …
=> build(ui): code-split `ApiDocs` and `Reports` components

.github/workflows/ci-build.yaml
This causes master branch to fail. We already uploaded coverage in non-Windows unit tests builds which is more correct since we skip certain tests on Windows.
=> ci: Remove coverage report for Windows tests

ui/src/app/app-router.tsx, ui/src/app/app.tsx, ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-creator.tsx, ui/src/app/cron-workflows/components/cron-workflow-creator.tsx, ui/src/app/cron-workflows/components/cron-workflow-editor.tsx, ui/src/app/cron-workflows/components/cron-workflow-spec-editior.tsx, ui/src/app/cron-workflows/components/cron-workflow-status-viewer.tsx, ui/src/app/event-flow/components/event-flow-details/build-graph.ts, ui/src/app/event-flow/components/event-flow-details/event-flow-page.tsx, ui/src/app/event-sources/components/event-source-creator.tsx, ui/src/app/event-sources/components/event-source-details/event-source-details.tsx, ui/src/app/event-sources/components/event-source-editor.tsx, ui/src/app/event-sources/components/event-source-list/event-source-list.tsx, ui/src/app/event-sources/components/event-source-log-viewer.tsx, ui/src/app/help/components/help.tsx, ui/src/app/login/components/login.tsx, ui/src/app/modals/modal-switch.tsx, ui/src/app/plugins/components/plugin-list/plugin-list.tsx, ui/src/app/sensors/components/sensor-details/sensor-details.tsx, ui/src/app/shared/components/graph/label.tsx, ui/src/app/shared/components/graph/pretty-layout.ts, ui/src/app/userinfo/components/cli-help.tsx, ui/src/app/widgets/workflow-graph.tsx, ui/src/app/widgets/workflow-status-badge.tsx, ui/src/app/workflow-event-bindings/components/workflow-event-bindings/workflow-event-bindings.tsx, ui/src/app/workflows/components/workflow-details/artifact-panel.tsx, ui/src/app/workflows/components/workflow-details/suspend-inputs.tsx, ui/src/app/workflows/components/workflow-logs-viewer/json-logs-field-selector.tsx
- named functions are better for tracing since the name shows up in stack traces etc
- instead of "anonymous"
- similar to many other previous refactor PRs I made that do this as part of other refactors
- convert several functional components and plain functions to use named functions
- instead of consts assigned to anonymous functions
- still a good amount of these leftover, but I think I got over 50%+ now
- got a little tired part way in 😅 
these are stylistic changes outside of traces; they are otherwise semantically equivalent
=> refactor(ui): use named functions for better tracing

.github/workflows/ci-build.yaml
The build has been timed out in master branch due to `-p 1`. Removing it to maximize performance ([verified that the build is successful in a test run](https://github.com/argoproj/argo-workflows/actions/runs/6617999161)).
=> ci: Speed up tests on Windows build

server/workflow/workflow_server.go, server/workflow/workflow_server_test.go
This reverts #11761. See https://github.com/argoproj/argo-workflows/issues/12025 for context.
=> fix: Revert #11761 to avoid argo-server performance issue

workflow/controller/controller.go
When Argo Workflows is configured to use JSON logging to simplify attributes extraction and filtering in Kibana/OpenSearch it produces attributes with conflicting types.
On start, controller will issue message "Current Worker Numbers" with attribute "workflow" equal number of workers. Which automatically mapped to "number" type in OpenSearch. Subsequent messages for actual workflows will have attribute "workflow" equals to actual workflow name. And those messages will be reject by OpenSearch with error like failed to parse field [workflow] of type [long] in document with id 'iFjDZIsBc7pTuVck5LUF'. Preview of field's value: 'okr-workflow-template-fe21b034-99wq9'.
Fixes #TODO
=> fix: conflicting type of "workflow" logging attribute

workflow/artifacts/oss/oss.go
when list a bucket over 100 object,  the response can only return 100 records, so wrote a loop to return all records.
Fixes #TODO
=> fix: oss list bucket return all records

ui/package.json, ui/yarn.lock
=> fix: Upgrade axios to v1.6.0. Fixes #12085

cmd/argo/commands/clustertemplate/create.go, docs/cli/argo_cluster-template_create.md
Fixes #11898 
Changes to support more detailed information when the user runs the argo cluster-template create command
Added examples for some common usages of argo cluster-template create command
RUN `argo cluster-template create --help`
=> docs: Add an example field to argo cluster-template create command. Fixes #11898

docs/memoization.md
Missing update to docs for memoization from #11379. 11379 allows memoization without outputs in 3.5
=> docs: Minor update for memoization

docs/cost-optimisation.md, ui/src/app/workflows/components/workflows-list/workflows-list.tsx, ui/src/models/workflows.ts
Fixes #12160
- after the unification of the Archived + Live Workflow APIs and UIs in #11121, the `WorkflowsList`'s `CostOptimisationNudge` was not altered to account for the additional Archived Workflows
- as such, it started showing up even for users with solid GC and archiving configurations
- change the counting logic to skip archived workflows, which are explicitly excluded in the docs
- using the Workflow Archive is one of [the recommendations](https://argoproj.github.io/argo-workflows/cost-optimisation/#limit-the-total-number-of-workflows-and-pods) in fact
- small code fixes/optimizations
- improve typings
- handle non-existent labels or metadata in `isArchivedWorkflow` func same as in `countsByCompleted` func
- and slightly refactor / clean-up the logic with optional chaining  
- …
=> fix(ui): Cost Opt should only apply to live Workflows

workflow/artifacts/s3/errors.go, workflow/artifacts/s3/errors_test.go
Fixes #9914
Artifact uploads are retried when failing due to transient error, but not with error code `"RequestError"` e.g. in the case of TLS handshake timeout. The error code `"RequestError"` should be marked as transient.
In `s3TransientErrorCodes`, I changed one of the duplicate `"InternalError"` array items to `"RequestError"`. I suspect the duplication may have been made by mistake.
This also aligns with the source referenced in the preceding comment i.e. [retry.go from minio-go](https://github.com/minio/minio-go/blob/92fe50d14294782d96402deb861d442992038109/retry.go#L90-L102).
The specific timeout issue very hard to test, as it is transient, but I added an assertion to `TestIsTransientOSSErr` to make sure that the error code is marked as transient.
=> fix: retry S3 on RequestError. Fixes #9914

util/unstructured/unstructured.go, workflow/controller/controller.go, workflow/controller/controller_test.go, workflow/cron/controller.go, workflow/util/util.go
=> fix: Resource version incorrectly overridden for wfInformer list requests. Fixes #11948

cmd/argo/commands/root.go, cmd/argo/commands/server.go, cmd/workflow-controller/main.go
In #11978 I noticed that `ARGO_LOGLEVEL` did not work for the Server
- `--loglevel` (and `--gloglevel`) were only set [at the parent command, `argo`](https://github.com/argoproj/argo-workflows/blob/b2e3676503999e699cd3aaca62ff7bfff64464af/cmd/argo/commands/root.go#L120), and not in [the `argo server` subcommand](https://github.com/argoproj/argo-workflows/blob/b2e3676503999e699cd3aaca62ff7bfff64464af/cmd/argo/commands/server.go#L42) itself
- however, `viper.AutomaticEnv()` and `viper.BindPFlags(command.Flags())` does not evaluate the parent command (related https://github.com/spf13/viper/issues/646, https://github.com/spf13/viper/issues/375, https://github.com/spf13/viper/issues/801)
- similarly, the code that actually sets the loglevels (which is in the CLI itself), would not run when an …
=> fix(server): allow passing loglevels as env vars to Server

docs/environment-variables.md
`environment-variables.md` had some inconsistencies and mistakes in it.
- I've linked to it a few times and have added relative links from other places in the docs, so would like to make sure the page is accurate etc
- move Server env vars and examples into the Server section
- instead of being in the Controller block
- `GRPC_MESSAGE_SIZE` was used in the example yet wasn't in the Server's env var list
- it was incorrectly in the Controller list, confirmed it was only used [in Server code](https://github.com/argoproj/argo-workflows/blob/a47e46208cd0029ef2e35019207d0b1ee4f85ea4/server/apiserver/argoserver.go#L119)
- also add its previously missing default into the table
- also comment out ellipses in code block so that the block is all valid code
- consistently use 1 sentence per line
- …
=> docs: full copy-edit of `environment-variables.md`

workflow/controller/dag.go, workflow/controller/steps.go
This reverts commit c751e66050a7c16d84ecdfdfe0f7ef59d6ec84c0.
See https://github.com/argoproj/argo-workflows/issues/12165
=> fix: Revert "fix: regression in memoization without outputs (#12130)"

workflow/controller/dag.go, workflow/controller/steps.go
This is a partial revert of #12130 and fixes #12165
Offered as an alternative to a full revert.
Fixes #12165 after @agilgur5's investigations
The ReproduceExample.zip from #12165 goes from 
to
=> fix: Fix for missing steps in the UI

ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/9764#issuecomment-1728735583
- `BASE_HREF` was not handled in a few places and Archived Workflows specifically was missed as it was removed in the 3.5 release
- this PR is to the 3.4.x branch
- add `uiUrl` to the one missing place in an Archived Workflows component
- didn't find any other missing ones for Archived Workflows (searched for `/archived-workflows/`)
~I added this to the `release-3.4.13` branch as there is no 3.4.14 branch yet. We'll want to modify the branch base once that exists.~ **EDIT**: updated to 3.4.14 release branch
I might suggest having a running `3.4.x` (etc) branch in order to have an ongoing branch, and then just tag patches off of that
=> fix(ui): missing `uiUrl` in `ArchivedWorkflowsList`

test/e2e/functional_test.go
Fixes #12129 - see that issue for details.
Add a couple of tests which check memoization still happens without outputs.
These tests fail with c751e66050a7c16d84ecdfdfe0f7ef59d6ec84c0 reverted.
=> test: add functional tests for memoization without outputs

test/e2e/functional/missing-steps.yaml, test/e2e/functional_test.go
This test is providing a regression test for #12165. As promised in #12203.
It verifies that a child link is correctly made in the case of a step with outputs.
This test fails if #12203 is reverted.
=> test: add test for missing child node

test/e2e/fixtures/then.go
By the name of ExpectWorkflowNode I believed that if the node it was selecting for didn't exist the thing wouldn't call f() and would error out.
So I've made it do that.
Existing users of the test framework (the tests) pass
=> test: test framework ExpectWorkflowNode should fail when no node

ui/src/app/apidocs/components/apiDocs.tsx, ui/src/app/reports/components/report-container.tsx, ui/src/app/shared/components/object-editor/object-editor.tsx, ui/src/app/shared/components/suspense-monaco-editor.tsx, ui/src/app/workflows/components/workflow-details/artifact-panel.tsx
Partial fix for #12059 -- this is the largest improvement by a wide margin, though still a little bit left to do
- shave off 7.72MB / 3MB minified / 762KB gzipped from main bundle
- main bundle itself is now only 5.11MB / 2.81MB minified / 553KB gzipped
- i.e. the _entire_ main bundle is smaller than the Monaco bundle 😮 😬
- wrap `react-monaco-editor` into a lazy loaded component
- with some tiny gimmicks to it per in-line comments
- in `ObjectEditor`, asynchronously import `languages` as well in one of its effects
- otherwise all of `monaco-editor` gets imported, per in-line comment
- also rewrite that effect to use modern async/await instead of promise chains
- which ends up a good bit simpler than what it would be with a promise chain with the new async import on …
=> refactor(ui): code-split gigantic Monaco Editor dep

ui/src/app/shared/components/data-loader-dropdown.tsx, ui/src/app/shared/components/editors/key-value-editor.tsx, ui/src/app/shared/components/graph/graph-panel.tsx, ui/src/app/workflows/components/workflow-details/suspend-inputs.tsx, ui/src/app/workflows/components/workflow-logs-viewer/full-height-logs-viewer.tsx, ui/src/app/workflows/components/workflow-logs-viewer/json-logs-field-selector.tsx
- a handful of files had `React.use`, while the rest had `use`
- `use` is definitely more of the convention in the ecosystem as well 
- consistently use the same import style for `React` imports
- also use named functions instead of consts assigned to anonymous functions for better tracing
- was changing these files anyway, might as well get that done too
- tiny optimization in an `onClick` event handler
- primarily stylistic changes outside of the tracing benefits and a tiny optimization
- partially tested manually while working on #12097 (this was just unstaged code I had lying around)
=> refactor(ui): consistent imports: `React.use` -> `use`

docs/variables.md
This change makes it clear that the unit of time reported by workflow.duration is in seconds.
Update variables markdown.
=> docs(variables): state that workflow.duration is reported in seconds

CODEOWNERS
This has not been useful and redundant to approvers.
=> chore: Update CODEOWNERS file

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/enhancement_proposal.md, .github/ISSUE_TEMPLATE/regression.yaml, .github/pull_request_template.md
Update our Issue and PR templates temporarily to gauge interest from the community in doing something like [this](https://github.com/argoproj/argo-workflows/issues/12229).
=> docs: gauge interest in a system to increase community participation

workflow/controller/controller.go, workflow/controller/operator.go
Problem: The workflow cache can have out of date information in it which will resurrect a completed workflow. In this scenario, with an on-exit handler with `when: "{{workflow.status}} != Succeeded"` it may fire the exit handler erroneously.
Firing enough of this workflow into a real cluster fast enough will reproduce this - tested in 3.4.8, 3.4.9, and master
```
kind: Workflow
metadata:
generateName: exit-
spec:
entrypoint: entrypoint
onExit: exit-handler
templates:
- name: entrypoint
container:
image: quay.io/pch/whalesay:latest
command: [ cowsay ]
args: [ "hello world" ]
resources:
limits:
memory: 32Mi
cpu: 100m
- name: ohnoes
container:
image: quay.io/pch/whalesay:latest
command: [ cowsay ]
args: [ "oh noes" ]
resources:
limits:
memory: 32Mi
cpu: 100m …
```
=> fix: completed workflow tracking

workflow/controller/exit_handler.go, workflow/controller/exit_handler_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/12283
Exit handlers should have access to the step status parameter.
I changed the logic that decides whether or not input parameters should be resolved for an exit handler.
I wrote a test.
=> fix: properly resolve exit handler inputs (fixes #12283)

test/e2e/cli_test.go
Fixes #12202 - see that issue for details.
Validate plugin field values when running argo get wf by GRPC
This test fails with 498734f reverted.
=> test: add test for unmarshaling plugin struct by GRPC.

test/e2e/functional_test.go, test/e2e/smoke/with-items-with-hooks.yaml, workflow/controller/operator.go
processAggregateNodeOutputs expects all children to be withItems children, but when there are hooks involved, this is not true. It uses `DisplayName` in an evil way to order the children, but the hooks don't fit it's idea of how displayName should look, so it will panic. I don't attempt to address this evil.
Instead I've opted filter the children in place to make it work.
Fixes #12279 
Functional test included.
=> fix: allow withItems when hooks are involved

workflow/controller/operator.go
We have a product named ManagedArgoWorkflows in AlibabaCloud use eci (virtual-kubelet).
Sometimes the pod failed for some reason (no stock、timeout、schedulerFailed and more than these)，in these conditions, the pod mightly not has containerstatus/condations/messages,  and then the pod will marked success and caused mistake.
So I think we should return failed when the pod is Failed and we can't find message and status in the pod.
Maybe this problem will also occur in other public cloud platforms.
=> fix: return failed instead of success when no container status

workflow/controller/operator.go
- I didn't get a chance to review #12020 before it was merged in, but it added more nesting when there was already some unnecessary nesting
- less nesting = less code complexity
- invert the `boundaryID` conditional from there for less nesting
- and invert the `boundaryNode` conditional as well for less nesting
- **NOTE**: there is a small semantic difference here from the previous code from #11451
- when there is an error retrieving `boundaryNode`, the error will now be returned
- previously it was not returned, but the purpose of the PR was to expose these errors as they are indicative of an underlying logic bug
- and indeed #12020 added the top conditional to avoid an underlying logic bug
- so I think this change is more within the _intent_ of both PRs, but CC @isubasinghe (who …
=> refactor: invert conditionals for less nesting in `includeScriptOutput`

workflow/common/util.go, workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/controller/operator.go, workflow/controller/testdata/dag_wftmpl_hook_with_retry.yaml
Fixes #12120
* Ensure WorkflowTemplateLevelLifeCycleHook wait for each dag task
* Almost same as `onExit` handler #3435
* Add `CheckAllHooksFullfilled` to check child hooked nodes.
This PR resolve #12120
<details>
<summary>yaml</summary>
```yaml
spec:
templates:
- name: main
inputs: {}
outputs: {}
metadata: {}
dag:
tasks:
- name: some-task
template: some-task
arguments: {}
hooks:
failure:
template: exit-handler
arguments: {}
expression: tasks["some-task"].status == "Failed"
- name: finish
template: finish
arguments: {}
dependencies:
- some-task
- name: some-task
inputs: {}
outputs: {}
metadata: {}
container:
name: ''
command:
- sh
- '-c'
args:
- |
echo "Doing great things";
echo "Failing...";
exit 1;
resources: {} …
```
=> fix: ensure wftmplLifecycleHook wait for each dag task

workflow/artifacts/oss/oss.go
when down a flie to path, and the path is not exist which mount by a oss volume. It made a mistake. So I want to create the dir path before functione "GetObjectToFile". Be consistent with the function "GetOssDirectory".
<!--
=> fix: create dir when input path is not exist in oss

workflow/controller/operator.go
Fixes #11856 
`argo_pod_missing` has no default value. It should have a zero value as all the other default metric.
I added zero when operator reconcile pod.
=> feat: add default metric of argo_pod_missing

workflow/controller/healthz.go, workflow/controller/healthz_test.go
Fixes #12326 
The liveness check was passing the WorkflowController's Workflow Informer to some code which assumes that the Informer holds types of `*Workflow` but in fact the Controller's informer holds types of `*Unstructured`. The effect was that the code would panic on the type assertion [here](https://github.com/argoproj/argo-workflows/blame/v3.5.1/pkg/client/listers/workflow/v1alpha1/workflow.go#L68).
Incorporate code which lists the Workflows from the Informer using `*Unstructured` type.
Both through a new unit test, plus through running the Controller and purposely blocking the reconciliation code so I could  hit the healthz endpoint and cause the 500 error.
=> fix: liveness check (healthz) type asserts to wrong type

sdks/python/README.md
Fixes #12364 
I tried installing the version in the README before realizing it was very old and could not be used to follow other parts of the documentation
It's a README change.
I ran the command in the README
=> docs: Remove old version pin in README

.github/workflows/ci-build.yaml, .github/workflows/docs.yaml
These must be bumped together.
Replaces #12374 and #12375 from dependabot
=> chore(deps): bump upload and download artifact to v4

server/artifacts/artifact_server.go, server/artifacts/artifact_server_test.go, ui/src/app/shared/services/workflow-service.test.ts, ui/src/app/shared/services/workflows-service.ts
I want to set inputs artifacts which is dir type in UI.
The example is:
```
kind: Workflow
metadata:
generateName: artifactory-artifact-
spec:
entrypoint: artifact-example
templates:
- name: artifact-example
steps:
- - name: generate-artifact
- - name: consume-artifact
template: print-message
arguments:
artifacts:
from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
- name: log
from: "{{steps.generate-artifact.outputs.artifacts.log}}"
inputs:
artifacts:
- archive:
none: {}
name: danger
oss:
key: aaaaa/store/artifactory-artifact-647sm/log
path: /tmp
container:
args: ["cowsay hello world | tee /tmp/hello_world.txt && cowsay hello world | tee …
```
=> feat: support to show inputs dir artifacts in UI

.github/ISSUE_TEMPLATE/enhancement_proposal.md, .github/pull_request_template.md
This section is only for people who are creating the issue to see.
=> docs: "beyond this issue" section should be hidden in issue/PR templates

mkdocs.yml
Currently, when click "edit" on any of the docs page from the website, it will direct you to a 404 page since it uses hard-coded "master" branch. This PR fixes that by changing it to "main" branch URL instead.
=> docs: Fix incorrect link in edit button

ui/src/app/workflows/components/workflows-row/workflows-row.tsx
Fixes #12422
We'd like to add a PR column that lists the user's PR URL and using annotations since labels have character limits and don't support special characters.
Builds off #10808
- docs state we can use labels and annotations [here](https://github.com/argoproj/argo-workflows/blob/954884d64c7b2d24a2e5fa0641a66692d182fefd/pkg/apis/workflow/v1alpha1/info.go#L21) and [here](https://github.com/argoproj/argo-workflows/blob/954884d64c7b2d24a2e5fa0641a66692d182fefd/docs/workflow-controller-configmap.yaml#L90)
I changed [this file's columns section](https://github.com/argoproj/argo-workflows/blob/954884d64c7b2d24a2e5fa0641a66692d182fefd/manifests/quick-start/base/overlays/workflow-controller-configmap.yaml#L46) from:
```yaml
columns: |
- name: Workflow Completed
type: label
key: …
```
=> fix: custom columns not supporting annotations

test/e2e/functional/stop-terminate.yaml, workflow/controller/dag.go
Fixes #11880
* Ensure workflow wait for onExit hook for DAG template
* #11493 introduces a feature that none of DAG task waits for a hook after shutdown is started.
* But workflows should wait for all onExit hooks completed as commented in https://github.com/argoproj/argo-workflows/issues/11880#issuecomment-1864097420
* Wait for onExit hook even if a shutdown process is started.
* Logic is almost same as steps one
* https://github.com/argoproj/argo-workflows/blob/6ca4d506eb23cb02e7c8cf21700509d0ff4a2c19/workflow/controller/steps.go#L328-L341
* E2E tests
* Fixes #11880
* ![image](https://github.com/argoproj/argo-workflows/assets/83329336/39913b93-cdbc-49ee-95c2-52153f343c86)
=> fix: ensure workflow wait for onExit hook for DAG template (#11880)

docs/quick-start.md
The quick start guide used the regular install.yaml for installation which does not configure the default user to be a valid service account to execute a workflow. This causes any example executions to fail. However the quick-start-minimal.yaml installation does configure this and is clearly suited for this doc so switch to that.
Fixes #12391
Redid the quick start guide with the quick-start-minimal.yaml installation and it worked.
=> docs: change quick-start guide to use quick-start install. Fixes #12391

.github/dependabot.yml, .github/workflows/ci-build.yaml, .github/workflows/docs.yaml
Fixes #12452
The V4 actions seem to have a high tendency to timeout when downloading artifacts.
https://github.com/actions/download-artifact/issues/249
Downgrade actions/download-artifact and actions/upload-artifact from v4 to v3 to fix artifact download timeout issues. Add both download-artifact and upload-artifact to dependabot ignore dependency.
Submit a few empty commits to verify frequency of failures is reduced.
=> fix: CI Artifact Download Timeout. Fixes #12452

.github/ISSUE_TEMPLATE/config.yml, workflow/executor/executor.go
Get the last few missing links that need to point to readthedocs latest
=> docs: change the last missing doc urls to readthedocs

mkdocs.yml
- `docs/retries.md` has a Mermaid diagram that renders out-of-the-box on GH but not on the docs site itself
- needs a Mermaid renderer for `mkdocs`
follow-up to #11005, https://github.com/argoproj/argo-workflows/issues/11390#issuecomment-1876274288, and [Nov 21st Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.kx3ajuyqr2ry)
- add a `pymdownx.superfences` config to render out Mermaid diagrams in `mkdocs` per https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration
Ran `make docs` followed by `open site/retries/index.html` to view in the browser.
Screenshots:
Before:
After:
=> fix(docs): render Mermaid diagrams in docs

mkdocs.yml
- `docs/requirements.txt` is currently being incorrectly hosted on https://argo-workflows.readthedocs.io/en/latest/requirements.txt
- this is a new file that we have to exclude now
follow-up to #12360
- add `/requirements.txt` to `exclude_docs` in `mkdocs.yml`
- specify `/` in front which means only the ones in the `docs/` directory
- see https://www.mkdocs.org/user-guide/configuration/#exclude_docs
- notably, the in-line comments that the docs have don't actually work, it seems to cause the whole `exclude_docs` block to be ignored as a result
1. Run `make docs`
1. Attempt to `open site/requirements.txt` which no longer works (it did prior to this change)
=> fix(docs): exclude `docs/requirements.txt` from docs build

docs/variables.md
Fixed a dead link in the documentation.
Changed the link (the expr-lang repository has moved).
=> docs: Fix dead link in documentation

ui/yarn.lock
CI failed during Snyk scan:
```
Issues with no direct upgrade or patch:
✗ Prototype Pollution [High Severity][https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788] in axios@1.6.2
introduced by swagger-ui-react@4.19.1 > swagger-client@3.24.6 > @swagger-api/apidom-reference@0.89.0 > axios@1.6.2
This issue was fixed in versions: 1.6.4
✗ Improper Input Validation [High Severity][https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6141137] in follow-redirects@1.15.3
introduced by swagger-ui-react@4.19.1 > swagger-client@3.24.6 > @swagger-api/apidom-reference@0.89.0 > axios@1.6.2 > follow-redirects@1.15.3
This issue was fixed in versions: 1.15.4
```
=> fix: Resolve vulnerabilities in axios

.spelling, docs/releasing.md
Per our previous discussions, this would avoid any manual sync with release branches. cc @jmeridth @agilgur5 
Also cc @sarabala1979 who will be doing the upcoming patch releases.
=> docs: Add notes on release branch to work with versioned docs

.github/workflows/stale.yaml, docs/CONTRIBUTING.md
Follow-up to https://github.com/argoproj/argo-workflows/pull/11836#issuecomment-1766672575, a [Slack thread](https://cloud-native.slack.com/archives/C0510EUH90V/p1702069651909869) last month, and a [previous Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit)
- as previously discussed, use the stale action in a much more limited fashion than the previous (deprecated) stale bot
- only run on issues and PRs labeled with `more information needed`
- configured similarly (but not entirely the same) to the previous Stale bot that was removed in #11836
- add a small section on staleness to the Contributing docs under issue triage
- n/a on the action as it runs in CI on a schedule with a very specific config.
- this action is already used [in …
=> ci: add Stale Action for specifically labeled issues and PRs

server/workflow/workflow_server.go
I have a big worklfow. When it failed and retry, it will be slowly. Latency increases with the number of pods. Always letting my automated system（interact with argo server use https) time out.
```
time="2023-12-26T13:02:01.560Z" level=info duration=1m18.730806898s method=PUT path=/api/v1/workflows/default/catch-workflow-8c48s/retry size=194 status=409
```
I found that the main time spent was deleting pods. 
```
time="2023-12-26T13:02:00.126Z" level=info msg="Deleting pod" podDeleted=catch-workflow-8c48s-read-ligands-from-vswdb-op-bmvou-9dzxr-2538960512
time="2023-12-26T13:02:00.328Z" level=info msg="Deleting pod" podDeleted=catch-workflow-8c48s-read-ligands-from-vswdb-op-bmvou-9dzxr-2824246174
time="2023-12-26T13:02:00.527Z" level=info msg="Deleting pod" …
```
=> feat: delete pods in parallel to speed up retryworkflow

ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx, workflow/executor/executor.go
A couple extra links in tandem with #12475; these needed converting to the new docs site as they were cherry-picked into this branch _after_ that PR without additional changes to account for the new URL
- Note that this PR is to the [`release-3.5`](https://github.com/argoproj/argo-workflows/tree/release-3.5) branch
Includes updated links for #12402 and #12149
Checked that the new URLs are correct
=> docs: update backported commits to https://argo-workflows.readthedocs.io/en/release-3.5

README.md
This is to draw attention to security issues. Snyk has been failing for a couple of days but we haven't noticed even before recent patch releases (example fix for a recent issue https://github.com/argoproj/argo-workflows/pull/12515 but the patch release is already out before this). https://github.com/argoproj/argo-workflows/actions/workflows/snyk.yml?query=branch%3Amain
=> docs: Add Snyk status badge to README.md

workflow/controller/steps.go
I have a big and flat workflow( 2000+ ) pod, which have artifacts reference each step. I find it won’t continue running down when it run to around step 100～200. 
After investigation， I find the function "resolveReferences" is too slow. One Step Group node has 1000 step need 300s to resolveReferences and then update the Step Group succeed. After that, then the workflow can run down.  But the default time for woc.operator is 30s.  I have set MAX_OPERATION_TIME to 20 min to succeed the workflow. But I think there is a better solution.
So I want to  speed up resolve reference.
I print the step time when it change to newStepStr use "template.Replace". Maybe I will speed up the "template.Replace"  function future.
Fixes #TODO
=> feat: speed up resolve reference

server/auth/types/claims.go, server/auth/types/claims_test.go
Fixes #12257
- Support Jumpcloud
- Support "email_verified" field as string "true" 
- Unit test included
=> fix: SSO with Jumpcloud "email_verified" field #12257

pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/http_template.go
Fixes #12018 
Fixes `synchronization` of `mutex` not working with http template.
Currently any http template will not work when you use with mutex.
(`withSequence` doesn't matter, however)
When running the issue's example, you can see the error directly in UI.
The first node(`call-endpoint(0:0)`)  is good, but the second (`call-endpoint(1:1)`) is not shown and so the workflow is on infinite pending.
Reason:
Mutex is handled in [executeTemplate](https://github.com/shmruin/argo-workflows/blob/873bacbafc4da79df15e0da728501ad925eef4fc/workflow/controller/operator.go#L1786) of `operator.go`.
But there are two problems when using mutex with http template.
1. **Unavailable to get node type of HTTP by [wfutil.GetNodeType(processedTmpl)](https://github.com/shmruin/argo-workflows/blob/873bacbafc4da7 …
=> fix: Fixed mutex with withSequence in http template broken. Fixes #12018

.github/dependabot.yml
As discussed in a [previous Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.k1l4irxjo6vc) and last month [on Slack](https://cloud-native.slack.com/archives/C0510EUH90V/p1701289310482799?thread_ts=1701102825.624669&cid=C0510EUH90V).
- most of the automated updates from dependabot cause a lot of noise and use up CI time, without adding much
- most often are small patch updates that don't affect our usage of deps
- some can also cause a lot of breakage when they pass CI but break something in a way that doesn't have an automated test (or has a test flake)
- examples in this repo include #12454, #10648, #9041, #8839 etc
- some can also cause lots of merge conflicts with other manual dependency updates
- examples in this repo …
=> ci: disable non-security dependabot updates 

test/e2e/argo_server_test.go, test/e2e/artifacts_test.go, test/e2e/testdata/artifact-workflow-stopped.yaml, test/e2e/testdata/artifactgc/artgc-dag-wf-self-delete.yaml, test/e2e/testdata/complex-global-artifact-passing.yaml, test/e2e/testdata/global-artifact-passing.yaml, workflow/controller/taskresult.go
Fixes #12554
An issue with global artifact passing was introduced in https://github.com/argoproj/argo-workflows/pull/12402.
The fix is to protect the call to `addOutputsToGlobalScope()` in `taskResultReconciliation` with `checkReconciliationComplete()`. This allows reconciliation to promote outputs to the global scope, but only when the workflow is complete.
This ensures that artifacts make it into the archive, while also ensuring that the order of global artifact availability in the workflow isn't disrupted.
Added multiple global artifact passing tests. Notably, `complex-global-artifact-passing.yaml` would frequently (but not always) fail before the fix made in this PR.
=> fix: Global Artifact Passing. Fixes #12554

cmd/argoexec/commands/data.go, cmd/argoexec/commands/resource.go, test/e2e/functional_test.go, test/e2e/resource_template_test.go
I run two example(use latest image):
https://github.com/argoproj/argo-workflows/blob/main/test/e2e/testdata/resource-templates/outputs.yaml 
https://github.com/argoproj/argo-workflows/blob/main/test/e2e/testdata/data-transformation.yaml
I find the workflow succeed but the workflowtaskresult have two is not marked true.
The two is resource && data template. So I want to Mark resource && data report-outputs-completed true.
```
tianshuangkun@B-QGHAMD6M-2124 myworkflow % argo list
NAME                        STATUS      AGE   DURATION   PRIORITY
data-transformation-ff287   Succeeded   2h    2h         0
outputs-fww7h               Succeeded   6h    6h         0
tianshuangkun@B-QGHAMD6M-2124 myworkflow % kubectl get workflowtaskresults -o yaml | grep …
```
=> fix: Mark resource && data template report-outputs-completed true

README.md
The categorization is to be consistent with Argo CD. Also added release badge and LinkedIn badge.
=> docs: Additional badges

ui/src/app/shared/components/suspense-monaco-editor.tsx, ui/src/app/shared/workflow-operations-map.tsx, ui/src/app/widgets/workflow-status-badge.tsx, ui/src/models/index.ts
Unblocks #12516
Follow-up to #12163 & #12290, which unblocked this
Follow-up to https://github.com/argoproj/argo-workflows/pull/12150#discussion_r1382510455 
Same changes can be made for #12158 and the `argo-ui` warnings introduced in #12061
- now that we've migrated from archived `tslint` to `eslint` and updated `prettier` from v1 to v3, we can _finally_ use this [newer TS syntax from TS 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)
- this fixes a few warnings in the build as well as makes things more explicit and efficient
- **note**: there are more warnings to fix around `export type`, but those are all from `argo-ui`'s source code and so can't be fixed from within this repo
- use `import type` syntax in a few files …
=> refactor(ui): use `import type` syntax where possible

.github/workflows/changelog.yaml, .github/workflows/ci-build.yaml, .github/workflows/dependabot-reviewer.yml, .github/workflows/docs.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml, .github/workflows/sdks.yaml, .github/workflows/snyk.yml, .github/workflows/stale.yaml
Partial fix for #12031, "Pinned Dependencies"
- Unpinned GH Actions are about ~80% of the failures in that check right now
- Workflows equivalent of https://github.com/argoproj/argo-cd/pull/11360
- `git` tags are mutable, while SHAs are immutable, so SHAs are [recommended](https://github.com/ossf/scorecard/blob/8eaf0d7647a3f50d80615812c72a277fd568fb6d/docs/checks.md#pinned-dependencies) for better supply chain security
- Note that dependabot [knows how to](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/) update both the SHA and the version comment
- add https://github.com/zgosalvez/github-actions-ensure-sha-pinned-actions to `lint` job to ensure all actions stay pinned
- <details> <summary> Pinned all …
=> ci: pin all GH Actions

Dockerfile, ui/package.json
- this was needed for legacy Webpack v4 support, but as of #11628, we are on Webpack v5 and so this is no longer necessary
- and this is more secure too, as the legacy option was insecure
Remembered that this was no longer needed after https://github.com/argoproj/argo-ui/pull/432#issuecomment-1879816619, I must've forgot I could remove this earlier (or that the flags were even there)
- basically undoes the parts of #11410 that added `--openssl-legacy-provider`
- removes all `--openssl-legacy-provider` flags
1. `yarn build` still works fine
1. `yarn start` still works fine
=> build(ui): remove no longer needed `--openssl-legacy-provider`

util/resource/duration_test.go, util/resource/summary.go
Fixes #12468
Fix cpu ressources consumption estimation.
Change the use of the `.Values()` function (which rounds ressources up to an integer) to `.MilliValues()` which is more accurate for CPU resources, which can be fractional.
The `MilliValues()` documentation mentions that this function may overflow, but the return value is stored in an int64, so the overflow will happen if a container requests more than 9*10^(15) of a ressource. I assume this should be fine for a while.
Tested by submitting the workflow attached to the issue this PR fixes. The result is now what is expected:
```
resourcesDuration:
cpu: 63
memory: 101
```
=> fix(resources): improve ressource accounting. Fixes #12468

Makefile
Only install NPM global deps if they're not already installed
- previously the `make` commands would unconditionally install these global deps, which was unnecessary & inefficient the vast majority of the time
- it would reinstall these every single time I ran these commands
- use `npm list -g` to check if they're installed first
- this exits with error code 1 if it doesn't exist
- note: that was the purpose of the `/usr/local/bin/` part in the `Makefile`, but this is not universally installed in the same place
- can run `npm prefix -g` and concat `/bin/` to that to get the path to your global installs
- on my Mac with versioned node (using [`rtx`](https://github.com/jdx/rtx)), the path is: `/Users/<my-user>/.local/share/rtx/installs/node/20.6.0/bin/`
- in the `devcontainer` with …
=> build(docs): don't install NPM global deps if they're already installed

.spelling, community/sustainability_effort.md, docs/CONTRIBUTING.md
Would like to add time spent on releases to officially count as Sustainability hours.
=> docs: add Releases to Sustainability hours

go.mod, go.sum
I scanned this project using Trivy, and found a Medium CVE with an available fix version:
I bumped the github.com/docker/docker v24.0.0+incompatible to a higher enough version without the CVE.
Run the existing CI/CDs here.
=> chore(deps): fixed medium CVE in github.com/docker/docker v24.0.0+incompatible

test/e2e/artifacts_test.go, workflow/executor/executor.go
Fixes https://github.com/argoproj/argo-workflows/issues/12174
I tried contacting original author from https://github.com/argoproj/argo-workflows/pull/12200 but met no success
We want to expedite this fix and have this ready for the next patch release
To make sure if an artifact contains a subdir and is mounted using volume claim, the workflow runs without failing.
VolumeMount is necessary if the user wants to use ephemeral storage.
Make sure the executor creates a subdirectory before downloading files
Added new e2e test -> e2e failed (verified original issue)
Added code change -> e2e succeed (verified fixed the issue)
=> fix: artifact subdir error when using volumeMount

.github/dependabot.yml
Follow-up to #12360 that added `docs/requirements.txt` (glad to have a proper dep file for that!)
- Follows #12487, which merge conflicted with this, so I waited to make the PR for this one (can see that the original commits were made at the same time)
- same as our other deps, for security updates only
- in particular, a scenario I can see possible is if `mkdocs` has an XSS vuln or something that would impact the docs site
- Add `docs/` `pip` section to `dependabot.yml`
style: reorder dep sections
- put Go, then NPM, then docs, then GH Actions
- i.e. the most important prod impacting deps, then build deps
n/a, this can only be tested after updating
I was thinking about some of the NPM docs deps too, but those don't make it into prod, so I don't think they necessarily need to have …
=> ci: add `mkdocs` Python deps to dependabot security updates 

docs/argo-server-sso.md, docs/data-sourcing-and-transformation.md, docs/events.md, docs/retries.md, docs/variables.md
Follow-up to https://github.com/argoproj/argo-workflows/pull/12469#discussion_r1443145079 and https://github.com/argoproj/argo-workflows/pull/12573#discussion_r1471449979
- most of these should go to the definition in Argo's own docs in `variables.md#expression`
- use https://expr-lang.org/docs/language-definition instead of GH as it has nicer UX
- change internal docs references to expressions to go to `variables.md#expression`, the internal docs definition of it
- change external references to go to https://expr-lang.org/docs/language-definition
- while at it, make some small docs changes in the same place
- more simple and direct, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
- some of these, especially the `data` one, …
=> docs: consolidate expression links

docs/workflow-controller-configmap.yaml
Fixes https://github.com/argoproj/argo-workflows/pull/12446#discussion_r1482271109
- this was erroneously added to the `main` branch in https://github.com/argoproj/argo-workflows/pull/12446#discussion_r1482271109
- it should only be on the `gh-pages` branch, for which all HTML pages redirect to ReadTheDocs now, but this YAML could not be, so we added this comment (see https://github.com/argoproj/argo-workflows/pull/12362#discussion_r1433271044)
- on the `main` branch, this is a confusing as it is a self-reference
- https://argo-workflows.readthedocs.io/en/latest/workflow-controller-configmap.yaml currently points to itself in circular fashion
- remove self-reference comment at the top of `docs/workflow-controller-configmap.yaml` on `main`
n/a, as it's rendered raw in the docs
I …
=> fix(docs): remove `workflow-controller-configmap.yaml` self reference

workflow/controller/operator.go, workflow/controller/operator_test.go
When a retry node has expression, it may appears:
```
Retry node: Running, Pod node: Pending
Retry node: Pending, Pod node: Pending
Retry node: Running, Pod node: Running
```
Slack link:
https://cloud-native.slack.com/archives/C01QW9QSSSK/p1705656605765459
=> fix: retry node with expression status Running -> Pending

workflow/controller/controller.go
Due to the namespace index missing from the workflow informer the healthz endpoint could not list namespace indexes. 
Leading to the following warning message: 
```
listers.go:79] can not retrieve list of objects using index : Index with name namespace does not exist
```
Everytime the healthz endpoint is called.
This fix has been verified in our environment by building the `workflow-controller` image from scratch and deploying it. 
Related Slack thread: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1707918209805259
Fixes healthz endpoint not being able to list namespace indexes.
These changes are similar to what others have done to resolve the issue.
- https://github.com/prometheus-operator/prometheus-operator/pull/1697
- https://github.com/argoproj/argo-cd/pull/2761
Added the …
=> fix(controller): add missing namespace index from workflow informer

.github/workflows/ci-build.yaml, docs/quick-start.md, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/base/kustomization.yaml, manifests/quick-start/base/overlays/argo-server-deployment.yaml
Follow-ups to #12445 and [this related Slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1705544478244329?thread_ts=1705530455.489149&cid=C01QW9QSSSK)
- prior to #12445, the quick start docs used the `install.yaml` instead of the `quick-start-minimal.yaml` manifests
- `install.yaml` is [a cluster install](https://github.com/argoproj/argo-workflows/blob/df79ce47c467823092a3819495418242984ff13e/Makefile#L419), so `quick-start-minimal.yaml` should also use a cluster install to match the past behavior
- without the `cluster-install`, you have to manually navigate to the `argo` namespace in the UI
- and you see an error until you do so, which is confusing to new users (per the above linked Slack thread), who are the target audience of the quick start docs
- the quick start …
=> build(manifests): `quick-start` should use `cluster-install`

ui/src/app/shared/components/pagination-panel.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Fixes #12663, fixes #12626 (as well as https://github.com/argoproj/argo-workflows/issues/12025#issuecomment-1931011600 2.i, the one with the browser network tab screenshot)
Follow-up to #11891 
The `ListWatch` previously _both_ depended on and set `nextOffset`, which was recursive
- note that it technically _does_ depend on it since the `list` uses the whole `pagination` object, but `nextOffset` only changes within the effect or at the same time as another pagination
- so it is safe to remove as a dep
- when pagination was enabled, this recursive dep/set would cause a duplicate request
- in my repro, I only had one duplicate request, as after that `nextOffset` stayed consistent. would have two for each page move
- for other folks in #12663 and #12626, this seemed to have caused an …
=> fix(ui): `ListWatch` should not _both_ set and depend on `nextOffset`

ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/12644 (partially, no markdown)
Visibility would be improved if title/description could also be displayed in CronWorkflow and WorkflowTemplate
Fixed to give priority to title and description.
=> feat: CronWorkflow/WorkflowTemplate title/description in list view

docs/installation.md, docs/workflow-rbac.md
These doc improvements are geared towards guiding users to RBAC details during installation and adding useful notes therein.
These doc changes were motivated by conversations in #12391 
The added notes to the `Workflow RBAC` page were confirmed via the following where `rbac.yaml` included definitions for the `Role`, `ServiceAccount`, and `RoleBinding` in the docs:
```bash
$ minikube start
$ kubectl create namespace argo
$ kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.4/install.yaml
$ kubectl apply -f rbac.yaml
$ argo submit --serviceaccount hello-world --watch https://raw.githubusercontent.com/argoproj/argo-workflows/main/examples/hello-world.yaml
```
=> docs: link to RBAC from installation and add notes

docs/CONTRIBUTING.md
There have been many cases where new contributors asked to get assigned but never worked on it and these issues were kept getting re-assigned. We should consider only assign issues to regular contributors and maintainers going forward. For new contributors, they can just work on a PR directly without being assigned.
=> docs: Add notes on issue assignment in CONTRIBUTING.md

ui/src/app/cron-workflows/cron-workflow-details.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/12645
I want to avoid argo-server going OOM when there is a lot of execution history.
Limited the number of histories to 50.
=> fix: Add limit to number of Workflows in CronWorkflow history

workflow/controller/retry_tweak.go, workflow/controller/retry_tweak_test.go
The root cause is pod have `retryStrategy`, the boundaryNode didn't have template (use `templateRef`), so when find retryNode,  probabilistically found others and cause `"failed to get a template"`.
Some info help review:
Failed workflow(find the wrong retry node):
Succeed worklfow:
Fixes: #12633
=> fix: find correct retry node when using `templateRef`. Fixes: #12633

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #10362 
This bug was found on this issue although its title complains about another bug that doesn't exist.
It is not possible to use the `retries` variable in an `expression` that also uses global variables like `workflow.parameters.<param>`. When the global variables are substituted the retry number isn't available and when the retry number is injected, the global params are not being used for substitution. 
Add the global params to  SubstituteParams when retrying a node 
```yaml
kind: Workflow
metadata:
name: whalesay
spec:
arguments:
parameters:
- name: memreqnum
value: 100
templates:
retryStrategy:
limit: 10
podSpecPatch: |
containers:
- name: main
resources:
limits:
memory: "{{= (sprig.int(retries)+1)* …
```
=> fix: make WF global parameters available in retries

docs/quick-start.md
- these sections list the same thing and are duplicative, so combine them / remove one
- leave the submitting example one as that's specifically written to show the UI vs. the CLI
- having the `port-forward` part when using the CLI doesn't make sense since you don't need it for the CLI
- combine the `port-forward` section with the UI submit example section
- <details><summary>also fix some docs issues in this section</summary>
- grammar issues:
- "Submitting" -> "Submit" -- use present tense, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-present-tense)
- also, the CLI and UI subsections had "Submit" but the top-level had "Submitting", which is inconsistent grammar
- "port-forward" is a k8s verb, not a noun, so "Open a port-forward" is grammatically …
=> docs(quick-start): consolidate UI & port-forward sections

docs/releasing.md, hack/cherry-pick.sh
As Isitha and I now have Approver permissions and were working on the release rotation per #12592, we both used the script and both found some issues, one of which was mentioned in https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1970241749
Fix a few bugs in the script and make it more ergonomic
- error out when the current branch that is checked out is not equivalent to the branch we're doing a cherry-pick on, as you can't cherry-pick onto other branches (see also this [SO question](https://stackoverflow.com/q/13878904/3431180))
- correctly order the commits in reverse chronological order -- the commits should be cherry-picked in the same order they were added
- add a simple `tac` (reverse `cat`) to achieve this
- like the dry-run, commits that aren't going to be …
=> fix(hack): various fixes & improvements to cherry-pick script

workflow/controller/operator_metrics_test.go
Tests were passing when https://github.com/argoproj/argo-workflows/commit/33ad82f689b83875a3b864298221ec3872379a4a was merged but new PRs are failing unit tests now. 
Changed the getMetricStringValue helper to call the String() function
Unit tests will pass
=> test: fix operator metric tests

go.mod, go.sum, workflow/controller/operator_metrics_test.go
Fixes intermittent unit test failures
=> test: fix intermittent operator metrics test failure

workflow/executor/executor.go
Make sure FinalizeOutput executes, let taskresult Completed if taskresult not exists.
When executor didn't have create workflowtaskresult permission.
The workflow won't completed even if all pods completed. Bucause the FinalizeOutput did patch taskresults and annotations.
patch report outputs completed if task result not exists.
=> fix: patch report outputs completed if task result not exists.

Makefile, dev/nix/flake.nix, hack/crdgen.sh, manifests/base/crds/full/argoproj.io_clusterworkflowtemplates.yaml, manifests/base/crds/full/argoproj.io_cronworkflows.yaml, manifests/base/crds/full/argoproj.io_workflowartifactgctasks.yaml, manifests/base/crds/full/argoproj.io_workfloweventbindings.yaml, manifests/base/crds/full/argoproj.io_workflows.yaml, manifests/base/crds/full/argoproj.io_workflowtaskresults.yaml, manifests/base/crds/full/argoproj.io_workflowtasksets.yaml, manifests/base/crds/full/argoproj.io_workflowtemplates.yaml, manifests/base/crds/minimal/argoproj.io_workflowtaskresults.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
This PR upgrades controller-gen to a modern version of controller-gen. The prior version was released in 2020. Some of the manipulation in https://github.com/argoproj/argo-workflows/blob/main/hack/crds.go may no longer be required but it doesn't change the final result either way. 
This is part of a series of PRs to update build dependencies until the build no longer panics on Golang 1.22
The new version of controller-gen adds additional x-kubernetes-map-type which is described in https://github.com/kubernetes/kubernetes/pull/84113. The map-type is manipulated in https://github.com/argoproj/argo-workflows/blob/main/hack/crds.go#L65 and was added in https://github.com/argoproj/argo-workflows/pull/6350. This manipulation may no longer be required. 
I didn't do any manual testing as any …
=> chore(deps): Bump sigs.k8s.io/controller-tools/cmd/controller-gen from v0.4.1 to v0.14.0

ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx, ui/src/models/workflows.ts
Fixes: #12395
Show correct message on UI when podGC is enabled with deleteDelayDuration.
Local test:
no deleteDelayDuration:
with deleteDelayDuration:
=> fix(ui): show correct podGC message for deleteDelayDuration. Fixes: #12395

workflow/controller/operator.go
Fixes: https://github.com/argoproj/argo-workflows/issues/12733
mark task result completed use nodeId instead of podname
=> fix: mark task result completed use nodeId instead of podname. Fixes: #12733

test/e2e/workflow_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes: #12329   
Root cause is when pod set faied from pending, because wait container's Terminated is nil, So this node is reset to pending and causing workflow stuck.
Let workflow Failed when activeDeadlineSeconds exceed.
Set pod Failed when pod set Failed from Pending. (Let workflow failed)
Local test and add some unit test and e2e
=> fix: workflow stuck in running state when using activeDeadlineSeconds on template level. Fixes: #12329

workflow/controller/agent.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go
Fixes #12568
I want to Take effect dag and steps level scheduling constraints. Not just workflow level and template level.
Find the pod's bounaryID's Template and add the scheduling constraints to pod if exists.
ut and e2e test
=> feat: support dag and steps level scheduling constraints. Fixes: #12568

pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/inline_test.go, workflow/templateresolution/context.go
Fixes #12594
I find the root cause is first inline template was store，So the next one in the loop is taken first.
I want the inline templates to be stored before being parsed so that each loop gets the correct template instead of the first one that was parsed.
When storing a template, if it also has an inline template, store it to avoid being parsed.
=> fix: inline template loops should receive more than the first item. Fixes: #12594

ui/yarn.lock
Partial fix for #12031, "Vulnerabilities"
After the Snyk failure for #12753, I also checked OpenSSF Scorecard's current vuln report and found this vuln too: https://github.com/nodejs/undici/security/advisories/GHSA-3787-6prv-h9w3
- update `yarn.lock` to bump `undici`
- `undici` is a transitive dep, used by `swagger-ui-react`
- `swagger-ui-react` -> `swagger-client` -> `undici`
1. Ran `yarn` after, no additional changes
1. Ran `npx yarn-audit-fix && yarn deduplicate` to check for more vulns and auto-update them (same as #12036), no others popped up
- Same for plain `yarn audit`: `0 vulnerabilities found - Packages audited: 1488`
1. Ran `yarn` again, no additional changes
=> fix(deps): upgrade `undici` from 5.28.2 to 5.28.3 due to CVE

cmd/argo/commands/submit.go, docs/cli/argo_submit.md
Supplements #926
The initial implementation neglected to include an example in the documentation.
Adds a simple example to the https://argo-workflows.readthedocs.io/en/latest/cli/argo_submit/ docs
```
cat my-wf.yaml | argo submit -
```
N/A
=> docs(cli): add `stdin` example for `argo submit`. Relates to #926

workflow/controller/controller_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #12210 
Avoid incorrect judgment that dag running causes workflow hang. The fundamental reason is that when the pod is cleaned up, the container is not still displayed as running, which causes the dag to be judged as running in assessDAGPhase.
Set container node error instead of  running when pod was deleted.
test local and e2e.
Before, pod delete but container running:
```yaml
lovely-rhino-544408588:
boundaryID: lovely-rhino
children:
- lovely-rhino-3630214831
- lovely-rhino-1026744615
displayName: A
finishedAt: "2024-03-07T07:07:07Z"
hostNodeName: kind-control-plane
id: lovely-rhino-544408588
message: pod deleted
name: lovely-rhino.A
outputs:
artifacts:
- name: main-logs
s3:
key: lovely-rhino/lovely-rhino-run-544408588/main.log
- name: main2-logs
s3:
key: …
```
=> fix(containerSet): mark container deleted when pod deleted. Fixes: #12210

docs/retries.md, examples/workflow-count-resourcequota.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/base/executor/docker/executor-role.yaml, manifests/quick-start/base/executor/emissary/executor-role.yaml, manifests/quick-start/base/executor/k8sapi/executor-role.yaml, manifests/quick-start/base/executor/kubelet/executor-role.yaml, manifests/quick-start/base/executor/pns/executor-role.yaml, test/e2e/functional/retry-with-artifacts.yaml, test/e2e/smoke/runasnonroot-output-params-pipeline.yaml
=> chore: fix some docs and comment typos

.github/workflows/changelog.yaml, .github/workflows/release.yaml
<details> <summary>Both of these were giving warnings in GH Actions runs during <a href="https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1972029716">the 3.5.5 release</a> </summary>
- [`release.yaml` run](https://github.com/argoproj/argo-workflows/actions/runs/8102509236)
- > Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- Screenshot for posterity: ![Screenshot 2024-03-09 at 3 30 43 AM](https://github.com/argoproj/argo-workflows/assets/4970083/2ac0a51c-5fc1-4edb-a826-c7d34adc1a5d)
- [`changelog.yaml` run](https://github.com/argoproj/argo-workflows/actions/runs/8102509233)
- > Node.js 16 …
=> chore(deps): upgrade `actions/cache` and `create-pull-request` to Node v20

workflow/controller/controller.go, workflow/controller/controller_test.go
Fixes #12778 
To prevent cronworkflow from queueing up pending workflows when
- reached parallelism limit 
- concurrenpolicy-replace already update the spec of the pending workflow to `shutdown: terminated`
Allow workflow in the queue to be processed (operated) regardless of parallelism limit.
We have scenarios
- reach parallelism limit, terminate running workflow (no issue)
- reach parallelism limit, terminate pending workflow (we should not block the queue from processing these workflow, just like semaphore doesn't block the queue from processing pending workflow that got terminated https://github.com/argoproj/argo-workflows/blob/5b3909b9567a5c6fc4fef81ac0785cfddbffb291/workflow/controller/operator.go#L528)
Add test,
test fail
Add code change
test succeed
=> fix: terminate workflow should not get throttled Fixes #12778

test/e2e/hooks_test.go
sleep 1s is sometimes too short to trigger the running hook
Fixes #12844
=> fix(test): wait enough time to Trigger Running Hook. Fixes: #12844

workflow/common/util.go, workflow/controller/controller.go, workflow/signal/signal.go
Addresses https://github.com/argoproj/argo-workflows/pull/12847#discussion_r1543760541
* Use the context from processNextPodCleanupItem in GetExecutorOutput
Existing test coverage will be sufficient
=> refactor: use context from `processNextPodCleanupItem`

go.mod, go.sum
https://github.com/advisories/GHSA-8r3f-844c-mc37
Fixes #TODO
- also bump `github.com/golang/protobuf` to `1.5.4` to make the build pass
=> chore(deps): bump google.golang.org/protobuf to 1.33.0 to fix CVE-2024-24786

test/e2e/fixtures/when.go, workflow/controller/operator.go
Fixes: #12836 
When the cluster pressure is high or execution is slow, `TestStoppedWorkflow` often fail. 
Because artifacts gc didn't execute.
It should be that after the last Failed, the controller has no chance to execute this workflow again.
=> fix: make sure Finalizers has chance to be removed. Fixes: #12836

workflow/controller/operator.go
remove completed taskset status before update worklfow.
Fixes #12832 
We should mark all tasksets complete before mark workflow completed.
=> fix: remove completed taskset status before update workflow. Fixes: #12832

ui/src/app/shared/components/object-editor.tsx
Fixes #12807
Adding support for displaying the line number would enhance the user experience, as it would aid in debugging
Remove `lineNumbers` key in `object-editor.tsx`.
after changes:
before changes:
=> feat(ui): display line numbers in object-editor. Fixes #12807.

SECURITY.md
Fixes #12745
- for ease of use, built-in templates, crediting, single source of truth, etc
- built-in private fork generation for resolution is another nice feature
- as well as consistency [with CD](https://github.com/argoproj/argo-cd/blob/a4b50515381bad9d6db316d49d33efae351c6222/SECURITY.md?plain=1#L68)
- Add another reporting option to the `SECURITY.md` (we already have email), which is using draft GHSAs.
See the [rendered markdown](https://github.com/argoproj/argo-workflows/blob/7ab7f2a2c4cfdbc39148cc72f6d129f60d6453f9/SECURITY.md) in this PR
**Do not merge** until Draft GHSAs are enabled by an admin, i.e. until this link works: https://github.com/argoproj/argo-workflows/security/advisories/new
For clarity and explicitness, draft GHSAs are not equivalent to CVEs. If a draft GHSA is …
=> docs(security): add Draft GHSA option

.github/workflows/ci-build.yaml
Fixes https://github.com/argoproj/argo-workflows/pull/12880#issuecomment-2036064662, https://github.com/argoproj/argo-workflows/pull/12234#discussion_r1550796719
- previously the deduplication commit would fail if there were no changes, so add `--allow-empty` to the commit as a quick fix
- add `--allow-empty` to the `git commit` for deduplicated Dependabot PRs
- also add `name`s to these steps for clarity (per https://github.com/argoproj/argo-workflows/pull/12880#issuecomment-2036064662, following #11752)
Tested this locally and it worked and exited cleanly (exit code `0`):
```sh
git add ui/yarn.lock
git commit -s --alow-empty -m 'chore: deduplicate yarn.lock'
```
Optimize this by adding a conditional to not even try to commit if there are no changes to the `yarn.lock`
=> ci(deps): fix auto deduplication of `yarn.lock` for Dependabot PRs

.github/dependabot.yml
Dependabot's recent automated security updates (#12878, #12879, #12880)  (enabled after https://github.com/argoproj/argo-workflows/pull/12763#issuecomment-1986755883) used the `build(deps)` prefix instead of `chore(deps)`
- note that I changed all their PR titles manually, but their commits still say `build(deps)` and most were auto-merged before I could change the title).
This matches the prefix we normally use for dependency updates (#12850, #12860, etc)
- also this matches what dependabot was previously doing for non-security updates (#12512, #12507, etc), not sure why it used `build(deps)` for security updates (??)
- Add `commit-message.prefix: chore(deps)` to all `package-ecosystem`s in `dependabot.yml`
- dependabot auto-adds `: ` after the prefix
- Add …
=> ci: use `chore(deps)` prefix for dependabot commits

.github/workflows/ci-build.yaml
Fixes https://github.com/argoproj/argo-workflows/pull/12882#discussion_r1552451141 and https://github.com/argoproj/argo-workflows/pull/12887#issuecomment-2038223808 part 3
- I managed to only have one `l` in the code but correctly used two `ll` while testing 🙃
- make sure `--allow-empty` has two `ll`s
Same as #12882, I just apparently typed it correctly while testing but not in the actual code welp
=> ci(deps): fix typo in `--allow-empty`

workflow/artifacts/oss/oss.go
Fixes #12877
https://github.com/argoproj/argo-workflows/blob/0b625a61a3473f9045d35a6bc0ae8a99db73e2ca/workflow/artifacts/oss/oss.go#L342
OSS SDK client offers several functions help upload local files to server. And PutObjectFromFile uses Simple Upload which usually causes (or always from my experience) InvalidArgument or EntityTooLarge error when uploading files larger than 5Gi. 
More info plz see: https://www.alibabacloud.com/help/en/oss/you-cannot-upload-large-objects-by-using-simple-upload?spm=a3c0i.23458820.2359477120.55.7ef56e9boHbYeC
Multipart Upload is the recommended way.
When trying to save files in OSS by Save Func of ArtifactDriver Interface:
- Still use Simple Upload method if file to saved is not larger than 5Gi.
- Or else split it into `size of capacity / 5Gi +1` parts and …
=> fix: use multipart upload method to put files larger than 5Gi to OSS. Fixes #12877

.github/workflows/ci-build.yaml
Reverts #12234, per my comments in https://github.com/argoproj/argo-workflows/pull/12234#discussion_r1552636495 as well as testing in my fork https://github.com/agilgur5/argo-workflows/pull/3#issuecomment-2038818809
- ultimately, it would produce PRs that would not be mergeable as [checks do not run on commits `push`ed via GH Actions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
- so it was fundamentally unworkable and hadn't been tested properly (note the missing "Verification" in the PR)
- I do not know a good solution or workaround to this, but as it doesn't work, it should be removed
- If we find something workable in the future, it can be added then once it's had extensive testing
- Ideally, this should be …
=> ci(deps): remove auto `yarn-deduplicate` on dependabot PRs

docs/requirements.txt
Partial fix for #12031, "Vulnerabilities"
- [8.2.6](https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.6) is 2 years old now
- and there hasn't been an 8.x release since [9.0.0](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.0) was released 1.5 years ago
- in particular, there are some CVEs in transitive deps of `mkdocs-material` now (such as `urllib3` CVEs: [GHSA-g4mx-q9vg-27p4](https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4), [GHSA-hmv2-79q8-fv6g](https://github.com/advisories/GHSA-hmv2-79q8-fv6g), [GHSA-v845-jxx5-vc9f](https://github.com/advisories/GHSA-v845-jxx5-vc9f), etc)
- make the upgrade to 9.x in `docs/requirements.txt`
- none of the removals in 9.0.0 affect our usage
- main noticeable changes I can see are some CSS …
=> chore(deps): upgrade `mkdocs-material` from 8.2.6 to 9.x

test/e2e/cli_test.go, test/e2e/testdata/fail-first-pass-second.yaml, workflow/controller/operator.go
~As part of my investigation and testing for https://github.com/argoproj/argo-workflows/pull/12574, I noticed that workflow update conflicts did not result in the workflow being marked as errored. I believe workflows should be marked as errored upon an update conflict. Additionally, marking workflows with conflicting updates as errored makes it easier to test the issue described in #12574.~
**Edit:** 
As Joibel pointed out, I was mistaken in marking the workflow as errored upon conflict. I didn't notice the `!` infront of `apierr.IsConflict()`, so I interpreted it wrong.
I think the test is still useful.
~Added `persistWorkflowConflictErr(ctx, wfClient, err)` and a call to it in `persistUpdates`~
Added test for manual workflow retry (in attempt to reproduce the issue described in #12574). …
=> test: Manual Retry (CLI) Failed Workflow

workflow/artifacts/oss/oss.go
Fixes #9349
https://github.com/argoproj/argo-workflows/blob/3b4551b6f33bd22519cc98e2d8c157a92720b5d7/workflow/artifacts/oss/oss.go#L226
OSS Artifact Driver still NOT support Artifact Garbage Collection as Delete Func has not been implemented.
Implemented Delete Func of OSS Artifact Driver . 
Plz check with workflow like
```
kind: Workflow
metadata:
generateName: artifact-gc-
spec:
artifactGC:
strategy: OnWorkflowDeletion # the overall strategy, which can be overridden
podMetadata:
annotations:
kubernetes.io/resource-type: eci
templates:
- name: main
container:
image: argoproj/argosay:v2
command:
- sh
- -c
args:
- |
echo "hello world" > /tmp/on-completion.txt
echo "hello world" > /tmp/on-deletion.txt
outputs:
artifacts:
- name: …
```
=> feat: implement Delete func of OSS ArtifactDriver. Fixes #9349

go.mod
Fixes CVE-2023-45288
This fixes the failing Snyk check on main branch.
=> fix(deps): upgrade `http2` to v0.24. Fixes CVE-2023-45288

pkg/apiclient/apiclient.go, pkg/apiclient/argo-server-opts.go, pkg/apiclient/http1-client.go, pkg/apiclient/http1/archived-workflows-service-client.go, pkg/apiclient/http1/cluster-workflow-template-service-client.go, pkg/apiclient/http1/cron-workflow-service-client.go, pkg/apiclient/http1/facade.go, pkg/apiclient/http1/info-service-client.go, pkg/apiclient/http1/workflow-service-client.go, pkg/apiclient/http1/workflow-template-service-client.go
the current implementation does not suite our usecase because the http Fascade interface does not take proxy url we have to use proxy for cross network calls for argo server
so we might as well just allow a fully configured http client to be passed in - this allows more flexible configurations of the HTTP1 client via custom roundtripper
Fixes #12827 
- Allow more flexible configuration for the http1 workflow apiclient so that caller can inject runtime headers (e.g. per-request tracing id) or use a http proxy via roundtripper
- Include the context for the request to argo server so that timeouts can be configured by the caller 
- Add configuration option for `HTTP1Client`
- Have `Facade` use the custom http client if provided
- Use `NewRequestWithContext` to include context from caller
- …
=> feat: allow custom http client and use ctx for http1 apiclient. Fixes #12827

.github/workflows/ci-build.yaml
This fixes the following error on main branch:
```
[2024-04-10T19:30:41.575Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/ab904c41d6ece82784817410c45d8b8c02684457/dist/codecov' failed with exit code 255
```
Ref: https://github.com/codecov/codecov-action/issues/1359 https://github.com/codecov/codecov-action/issues/1284
=> ci: Fix test coverage report upload issue

test/e2e/argo_server_test.go, test/e2e/cli_test.go, test/e2e/testdata/retry-workflow-with-continueon.yaml, workflow/util/util.go, workflow/util/util_test.go
fix: DAG with continueOn in error after retry
Fixes: #11395
local test and e2e test.
After retry:
Before fix: Error and lose some nodes.
After fix: Failed and not lose nodes
=> fix: DAG with continueOn in error after retry. Fixes: #11395

workflow/controller/agent.go
The log level is currently not passed to main and init containers in agent pod.
=> fix: Correct log level for agent containers

workflow/controller/operator.go, workflow/controller/steps.go, workflow/progress/updater.go, workflow/util/util.go
comments here: https://github.com/argoproj/argo-workflows/pull/12817#discussion_r1561980703
=> fix: change fatal to panic. 

workflow/gccontroller/gc_controller.go
Fixes #12636 
try to fix #12636 
modify `gc_controller.go` to ignore deletion for workflow not completed due to a retry operation
test workflow file `fix-12636.yaml`: 
```yaml
kind: Workflow
metadata:
generateName: fix-12636-
spec:
ttlStrategy:
secondsAfterFailure: 30
arguments:
parameters:
- name: fail
value: 'true'
templates:
- name: main
dag:
tasks:
- name: A
template: first-fail
arguments:
parameters:
- name: fail
value: "{{workflow.parameters.fail}}"
- name: B
depends: "A"
template: echo
- name: first-fail
inputs:
parameters:
- name: fail
container:
imagePullPolicy: IfNotPresent
args: 
- |
set -e
if [ "{{inputs.parameters.fail}}" == "true" ]; then
echo "Failing"
exit 1
fi
echo "Succeeded"
- name: …
```
=> fix: workflows that are retrying should not be deleted (Fixes #12636)

workflow/controller/artifact_gc.go
fix an error log message, which currently uses a wrong order of parameter, as mention in #12845 (point 5).
=> fix: correct order in artifactGC error log message

ui/src/app/shared/services/workflows-service.ts
Similar to other PRs I've had that simplify code or fix bugs by using optional chaining
- remove 4 LoC with optional chaining short-hand
- replace conditionals with optional chaining
- `array.findIndex(...) !== -1` is also equivalent to `array.some(...)`
These are semantically equivalent, but I also had this in my local codebase while writing & debugging #12932 et al (which is how I stumbled upon this) and it worked the same
=> refactor(ui): simplify `hasArtifactLogs` with optional chaining

ui/src/app/shared/services/event-source-service.ts
=> fix(ui): default to `main` container name in event source logs API call

cmd/argo/commands/lint.go, cmd/argo/lint/formatter_pretty.go, cmd/argo/lint/formatter_pretty_test.go, docs/cli/argo_lint.md
Fixes #12913 
Visibility would be improved in cases where you capture the output, and include it in a GitHub comment on a Pull Request.
Extend `argo lint` with the `--no-color` flag. When used the flag will disable the colors output by setting [`color.Toggle(false)`](https://github.com/TwiN/go-color/tree/v1.4.1?tab=readme-ov-file#disabling-colors). Apart from that extended unit tests to cover the changes
=> feat(cli): Add `--no-color` support to `argo lint`. Fixes #12913

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/regression.yaml
- there have been many cases of users checking the box despite not testing `:latest`, sometimes not even testing the latest patch version
- this is an effort to clarify that / make it more explicit what that means to hopefully reduce that occurrence
- some recent examples of this occurrence include: https://github.com/argoproj/argo-workflows/issues/12946#issuecomment-2060000421, https://github.com/argoproj/argo-workflows/issues/12802#issuecomment-2007756351, https://github.com/argoproj/argo-workflows/issues/12949#issuecomment-2062322286
@Joibel and I have also briefly talked about this during Contributor Meetings
- Clarify "tested with `:latest`" by adding "image tag" and giving an example
the strings are valid, but otherwise n/a, this is GH specific. there is also no local preview for …
=> chore: clarify `:latest` in bug templates

ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Fixes #12590, Fixes #12759
- Partially replaces #12591 with a root cause fix (that I wrote & pushed [myself](https://github.com/argoproj/argo-workflows/pull/12591#discussion_r1562071827) to the PR) and without an additional feature, so that this can be properly backported to 3.4.x and 3.5.x
Follow-up to #9464
- a node doesn't have to be clicked on in the UI to get logs, you can also click on the top-level logs button
- in this case, there is no nodeId, but we can infer/derive one based on the Pod chosen in the drop-down
- a nodeId is required for archive logs, so this fixes archive logs when no node was chosen
- which is a bug / regression that seems to stem from the `POD_NAMES=v2` change
- use the `podNamesToNodeIDs` map from #9464 to derive a `nodeId`
Manually tested that clicking the …
=> fix(ui): properly get archive logs when no node was chosen

ui/src/app/workflows/components/resubmit-workflow-panel.tsx, ui/src/app/workflows/components/retry-workflow-panel.tsx, ui/src/app/workflows/components/submit-workflow-panel.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx
I noticed this while investigating https://github.com/argoproj/argo-workflows/issues/12868#issuecomment-2033385525, although I don't think this would fix that issue.
Also related to / similar to #12930 
- `document.location.href` causes the browser to load a new page which is a full page load
- `navigation.goto` should always be used when we're routing within the single-page app (SPA)
- this only changes the internal route so only the next component needs to render, not the entire page
- (and user-facing `history`, same as changing the `location`)
- fix `name` and `namespace` in Workflow Details to actually change when the URL changes
- they were previously set as `state` despite not actually being `state`, meaning they only ever received the initial URL and no further changes
- in …
=> fix(ui): use router navigation instead of page load after submit

ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Fixes https://github.com/argoproj/argo-workflows/pull/11121#discussion_r1561987732
- remove the hard `window.location.reload()` on deletion b/c the WorkflowsList page _does_ handle deletions
- not sure what didn't work about it before, the code has improved but is largely semantically equivalent
- I suspect it might have been the same root cause as #11711, i.e. caused by #11661
- remove the `window.location.reload()` and comments about it
- `navigation.goto` is already there and already works properly
<details><summary>Tested deletion locally without the <code>window.location.reload()</code> and it worked fine. </summary>
Screenshots:
Before deletion -- `coinflip-794pg` exists:
After deletion -- clicked into `coinflip-794pg` and clicked _Delete_  -- `coinflip-794pg` no longer exists: …
=> fix(ui): remove unnecessary hard reload after delete

ui/src/app/shared/pod-name.test.ts, ui/src/app/shared/pod-name.ts, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, workflow/util/pod_name.go
Fixes https://github.com/argoproj/argo-workflows/pull/6982#discussion_r1574359684, Fixes https://github.com/argoproj/argo-workflows/pull/9168#discussion_r1574264448
Simplify `getPodName` as it required lots of args that could be retrieved from the existing Workflow and Node. Simplify surrounding code as well
Make it more consistent to the back-end as well, particularly after #12928.
- It seems to have diverged unintentionally within the same PR per https://github.com/argoproj/argo-workflows/pull/6982#discussion_r1574359684 
- simplify calls to `getPodName` to only require the Workflow and Node as args
- the rest can be derived from them, so we can remove all the duplicate, extraneous logic from all callers
- `workflow-details.tsx` was particularly simplified as a result, a whole function …
=> refactor: simplify `getPodName` and make consistent with back-end

ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Retrieving an archived workflow is the fallback now.
Related Slack thread: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1710600357875049\?thread_ts\=1710510295.856659\&cid\=C01QW9QSSSK
Fixes https://github.com/argoproj/argo-workflows/issues/12814
Currently an error appears when loading a workflow because archived workflows are not enabled and the ui tries to get the archived workflow first. 
Changed the order in which workflows are retrieved from the back end.
None, not sure how to verify at the moment.
=> fix(ui): try retrieving live workflow first then archived

cmd/argo/commands/cp.go, test/e2e/fixtures/then.go, util/printer/workflow-printer.go, workflow/controller/artifact_gc.go, workflow/controller/exec_control.go, workflow/controller/operator.go, workflow/util/util.go
The way to get a template name in a `NodeStatus` is different if using template references. Not all places in the code base handle this small detail. I searched for all reads of `NodeStatus.TemplateName` field and replaced it to use the `GetTemplateFromNode` function. This will ensure that the template name is never empty and retrieved uniformly. 
There are three places in the code base that still manually handle these details: 
- https://github.com/argoproj/argo-workflows/blob/main/cmd/argo/commands/common/get.go#L488-L492
- https://github.com/argoproj/argo-workflows/blob/main/workflow/controller/retry_tweak.go#L18-L33. 
- https://github.com/argoproj/argo-workflows/pull/12970#discussion_r1576605599
If you think we should change these to also use `GetTemplateFromNode` let me know.
Fixes …
=> fix: use GetTemplateFromNode to determine template name

server/auth/sso/sso.go, server/auth/types/claims.go, server/auth/types/claims_test.go
When running with `insecureSkipVerify: true` and a `userInfoPath` like `userInfoPath: /userinfo`, the call is falling because it's still checking the certificate.
I pass the `httpClient` built for the SSO as a parameter of the function `GetUserInfoGroups`.
I ran it using Argo CD with Dex and custom (internal certificate).
Argo Workflows doesn't fail anymore about certificate verification.
=> fix: `insecureSkipVerify` for `GetUserInfoGroups`

docs/quick-start.md
Follow-up to https://github.com/argoproj/argo-workflows/pull/12420#discussion_r1443803712
Significantly simplify the wording in the Quick Start and align it to the [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/)
- this doc was quite verbose and wordy prior to these changes, and for one of the first things a user sees, it should be especially simple (the k8s style guide requires that from all docs, but this one is of particular importance)
- small functional / usability changes:
- move Killercoda course to the top, before running k8s, not after
- split out the "Before you start" into a "Prerequisites" section
- now the Killercoda course is a clear alternative to the prereqs as well
- with the functional changes above and from #12560, can now make some stylistic …
=> docs: full copy-edit of Quick Start

workflow/controller/operator.go
Stumbled upon this while discovering #12966.
#2286 seems to make an unnecessary request and that code still exists.
Hit the k8s apiserver less, wait on network requests less
- instead of doing a `get` then a `create`, just do a `create` and ignore if it already exists
The test from #10944 should still pass
=> refactor(controller): optimize PDB creation request

hack/manifests/crdgen.sh
The current logs are misleading which may look like both the minimal and full CRDs are applied to the cluster twice:
```
Patching ...
Creating ...
```
The PR makes it less confusing.
=> build: Remove misleading logs from crdgen.sh

docs/workflow-pod-security-context.md
#12983 
Qualified PSP as deprecated. Added PSS and PSA as requested by @agilgur5 
Previewed in markdown viewer
=> docs: qualify reference to deprecated PSP

.github/dependabot.yml
Follow-up to https://github.com/argoproj/argo-workflows/pull/12887#issuecomment-2038223808 part 2
- generally, security updates for prod deps should be backported, while devDeps are not strictly necessary
- so splitting these is helpful for cherry-picking, especially if there might be conflicts (which may be more likely with devDeps and build chain changes)
- add two `groups` to NPM (the only one where have a devDeps/prod deps split) to split `devDeps` and `deps`
- Followed the docs https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
- note that `applies-to` is necessary as it defaults to `version-updates` per the docs
- I thought it would default to _both_, but they seem to be mutually exclusive in …
=> ci(deps): group Dependabot updates by devDeps vs prod deps

workflow/artifacts/oss/oss.go
Part of #8489
OSS Artifact Driver do not support OpenStream Func to avoid unnecessary file downloading.
Implemented OpenStream Func of OSS Artifact Driver.
Get an artifact which storages in OSS from UI, check the logs of argo-server.
latest version: 
```
time="2024-04-07T13:03:58.700Z" level=info msg="Efficient artifact streaming is not supported for type *oss.ArtifactDriver: see https://github.com/argoproj/argo-workflows/issues/8489"
time="2024-04-07T13:04:10.072Z" level=info msg="Efficient artifact streaming is not supported for type *oss.ArtifactDriver: see https://github.com/argoproj/argo-workflows/issues/8489"
```
submitted version:
```
time="2024-04-07T13:22:29.074Z" level=info msg="OSS OpenStream, key: argo-workflows/input-artifact-oss-k4htb/input-artifact-oss-k4htb/main.log" …
```
=> feat: implement OpenStream func of OSS artifactdriver. Part of #8489

ui/package.json, ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx, ui/src/app/event-sources/components/event-source-list/event-source-list.tsx, ui/src/app/sensors/components/sensor-list/sensor-list.tsx, ui/src/app/shared/components/dropdown/dropdown.tsx, ui/src/app/shared/components/filter-drop-down.tsx, ui/src/app/shared/components/phase-icon.tsx, ui/src/app/shared/components/tags-input/tags-input.tsx, ui/src/app/tsconfig.json, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, ui/src/app/workflows/components/workflow-timeline/workflow-timeline.tsx, ui/yarn.lock
A cherry pick of #11585 to release/3.4
Changes from #11585:
* `archived-workflow-details.tsx` changes to `className`
* `yarn.lock` updated, `react-toastify` still pinned to 9.0.3
Specifically fixes #11448 on 3.4
Fixes #11585 missing from https://github.com/argoproj/argo-workflows/issues/11648#issuecomment-1707441279
`make start UI=true` runs up cleanly.
Built argo-cli image and installed it as the UI in a 3.4.16 install. Ran a workflow and clicked around a lot. I didn't observe anything wrong.
The resolution #11448 has been checked.
=> fix: upgrade `argo-ui` components to latest (3.4 backport)

.github/workflows/retest.yaml
Fixes https://github.com/argoproj/argo-workflows/issues/12864
Typo introduced in https://github.com/argoproj/argo-workflows/pull/13000#discussion_r1589938407.
Add missing quote in the piped `jq` command.
Tested in https://github.com/miltalex/argo-workflows/pull/3 and https://github.com/miltalex/argo-workflows/pull/4 after I pushed the changes in `main` branch in the forked repository.
Extra test case: Trigger `/retest` before workflow finished &rarr; Failing with `This workflow is already running`.
=> fix(ci): Add missing quote in retest workflow. Fixes #12864

workflow/artifacts/oss/oss.go
Fixes #12925
OSS does not support to set different rules at a time for a same prefix and that's why I received a 400 error. And more details added in related issue.
```
time="2024-04-09T16:04:23.147Z" level=info msg="Save artifact" artifactName=out duration=1.270302632s error="oss: service returned error: StatusCode=400, ErrorCode=InvalidRequest, ErrorMessage=\"Found same prefix in different rules\", RequestId=6615670711BF5732361C11E2, Ec=0014-00000085" key=argo-workflows/test/lifecycletime="2024-04-09T16:04:23.147Z" level=error msg="executor error: oss: service returned error: StatusCode=400, ErrorCode=InvalidRequest, ErrorMessage=\"Found same prefix in different rules\", RequestId=6615670711BF5732361C11E2, Ec=0014-00000085"
```
LifecycleRule modified to:
- Set Transitions with …
=> fix: setBucketLifecycleRule error in OSS Artifact Driver.  Fixes #12925

.github/workflows/ci-build.yaml
When the Dockerfile changes we should re-test most of the world
=> ci: run E2E tests if `Dockerfile` changes

Dockerfile
The timestamps in CI are incorrect, and may result in an attempt to rebuild this file when we don't have yarn installed. So don't.
This is a problem introduced in #13018. _edit by agilgur5:_ See also [Slack thread](https://cloud-native.slack.com/archives/C0510EUH90V/p1715172548595289?thread_ts=1715163699.813329&cid=C0510EUH90V) for some debugging details on this
The timestamps don't always line up like expected when we come to check if we need to rebuild ui/dist/app/index.heml in the argocli-build step so force them fixed.
=> fix: don't rebuild `ui/dist/app/index.html` in `argocli-build` stage

test/e2e/executor_plugins_test.go, workflow/common/security_context.go, workflow/controller/agent.go, workflow/controller/artifact_gc.go, workflow/controller/workflowpod.go
We are using Kyverno Policies to enforce different security settings within our cluster. For example running containers as non Root.
But also to explicitly have set the SeccompProfile to RuntimeDefault. See the [official Documentation](https://kubernetes.io/docs/tutorials/security/seccomp/#create-a-pod-that-uses-the-container-runtime-default-seccomp-profile)
Currently the artifact GC is beeing blocked by our Kyverno policy. On my search for values to change the default (e.g. via Helm) i found the code I changed in this PR.
Explicitly Setting the Seccomp Profile to RuntimeDefault when creating the artifact GC Pod.
The E2E tests should catch any issues, if you want me to test this locally let me know
=> feat(executor): set seccomp profile to runtimedefault

Makefile, hack/release-notes.md
- simplifies and consolidates the release notes for each version
- detect OS in the first command and use as env var
- slightly modify `make release-notes` target to handle this properly
- only replace `$version` and not `$ARGO_OS`
1. Ran `make release-notes` and checked that it only substituted `$version`
1. Ran the script on both my macOS laptop and my Linux devcontainer
=> build: simplify release notes as cross-platform

cmd/argo/commands/client/conn_test.go, server/auth/gatekeeper_test.go, server/cache/resource_cache_test.go, server/workflowarchive/archived_workflow_server_test.go, util/env/env_test.go, util/errors/errors_test.go, util/file/fileutil_test.go, util/kubeconfig/kubeconfig_test.go, util/util_test.go, workflow/artifacts/s3/s3_test.go, workflow/controller/operator_test.go, workflow/controller/pod/significant_test.go, workflow/events/event_recorder_manager_test.go, workflow/executor/resource_test.go
Related to https://github.com/argoproj/argo-workflows/pull/12862#discussion_r1567591349, https://github.com/argoproj/argo-workflows/pull/12756#discussion_r1536712741
[`t.Setenv`](https://pkg.go.dev/testing#B.Setenv) handles setting the env var back to what it was after
- automates the `defer` + `Unsetenv` at the end
- and is more correct -- it always sets it back to what it was, not just unsets it
- also catches a few places where the `defer` was missed which could've resulted in some incorrect tests
`os.Setenv` + `os.Unsetenv` -> `t.Setenv`
Existing tests should pass
=> refactor(test): use `t.Setenv`

docs/quick-start.md
I got hung up on these instructions because I copied the commands from the releases page instead of from the quick start page, so I applied `install.yaml` instead of `quick-start-minimal.yaml`. I hope this change will help others not get confused like me :)
I tried `make pre-commit -B` (had to install `go` first) and it failed with `protoc` not found. Do I need to keep working my way through these, or is it OK to ignore for a docs change like this?
Fixes #13032
I followed the quick start instructions explicitly, but ended up with an install that couldn't execute Hello World step.
Alter docs to explicitly instruct the user to install the quick start manifest.
I also moved a warning admonition because I felt it belonged after prose I added in this PR.
Rendered the docs, looked good
=> fix(docs): Clarify quick start installation. Fixes #13032 

workflow/signal/signal.go
Fixes #13011
I added a context timeout to prevent spdy from blocking for a long time
=> fix: add timeout for executor signal

test/e2e/cli_test.go, test/e2e/testdata/retry-workflow-with-continueon.yaml, workflow/util/util.go
ignore retry node when check descendant nodes.
Fixes #13003
=> fix: ignore retry node when check succeeded descendant nodes. Fixes: #13003

test/e2e/fixtures/when.go, test/e2e/retry_test.go, workflow/controller/operator_test.go, workflow/controller/retry_tweak.go
Fixes #9193
The root cause is the workflow's boundaryID is empty. So did't find the retry node to fetch the HostNodeName. 
So I want to find the retry node and fetch the HostNodeName as the new pod‘s nodeAntiAffinity.
Find the correct retrynode when boundaryID is empty.
e2e tests  and ut
=> fix: nodeAntiAffinity is not working as expected when boundaryID is empty. Fixes: #9193

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/executor_swagger.md, docs/fields.md, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/plugins/executor/swagger.yml, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1Backoff.md, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_backoff.py, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1Backoff.md
Fixes #13044 
The current documentation for `maxDuration` in the Argo workflow is unclear and potentially misleading, particularly when used in conjunction with `activeDeadlineSeconds`.
The description does not accurately reflect the behavior observed in the code, where the pod's deadline set by `activeDeadlineSeconds` is overridden by `maxDuration` upon workflow failure.
https://github.com/argoproj/argo-workflows/blob/a1db80aedf9344fd74d7e381b4337fb8fb7e244b/workflow/controller/operator.go#L1053-L1054
This can lead to confusion for users trying to understand how these two parameters interact.
The updated documentation aims to clarify this behavior, ensuring that users have a precise understanding of how `maxDuration` and `activeDeadlineSeconds` work together in the context of workflow …
=> docs: Clarify maxDuration behavior when used with activeDeadlineSeconds. Fixes #13044

workflow/controller/controller.go, workflow/controller/operator.go, workflow/metrics/metrics.go, workflow/metrics/metrics_test.go, workflow/metrics/server.go
Fixes #12790 
Realtime metrics may be cleaned up, even if the workflow is still running.
Adding two boolean value: `realtime` and `complete` in metric to indicate whether the metric is realtime type and whether it is completed.
Enable realtime metric gc only after its workflow is completed.
local test and UT
=> fix: Enable realtime metric gc after its workflow is completed. Fixes #12790

ui/src/app/workflows/components/workflow-creator.tsx
Reduce tech debt, code complexity, etc
- reduce nesting in this effect quite significantly with early returns
- and remove an unnecessary `switch` statement
- (not sure if it had more than one `case` before? it `git blame`s back to #4470 which moved the UI from `argo-ui` to this repo)
No semantic changes, functionally equivalent.
Tested creating a Workflow in different ways and it worked fine.
The diff is much easier to read with [the ignore whitespace setting](https://github.com/argoproj/argo-workflows/pull/13094/files?diff=unified&w=1)
=> refactor(ui): heavily simplify `WorkflowCreator` effect

docs/enhanced-depends-logic.md
docs: update the enhanced depends documentation
It wasn't clear to me what `Omitted` and `Skipped` meant. I'm still not sure I have this correct but I'm going off [advice I got](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1716512517981539) in the Argo Slack.
=> docs: clarify `Skipped` and `Omitted` in enhanced `depends`

.devcontainer/pre-build.sh
Fixes #13109
`chown` command fails for some reason on `.git` folder on my mac M1
I silenced the error by adding `|| true` on the failing command on `.devcontainer/pre-build.sh`
-> The error is probably due to a mac-specific thing. It'll be to do with how the OS has mounted that volume to the dev docker container
-> There is no gitignore-style file for devcontainers, to ignore `.git` directory
The impact of the change are quite small, but the process reached the end
=> fix: silence devcontainer `Permission denied` error. Fixes #13109

.spelling, docs/releases.md
- this has been asked about by users several times [on](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1716901715484439) [Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1717050469207059?thread_ts=1716901715.484439&cid=C01QW9QSSSK)
- as well as at least once on GitHub: #12695
- I also asked about our k8s upgrade policy in [a Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.eb9qvqsmpwns) and [the contributors Slack](https://cloud-native.slack.com/archives/C0510EUH90V/p1712081347503639)
- and I clarified later in [the thread](https://cloud-native.slack.com/archives/C0510EUH90V/p1713383168753329?thread_ts=1712081347.503639&cid=C0510EUH90V) about k8s's guarantees and `client-go`'s matrix, etc
- this PR is …
=> docs: elaborate on k8s compatibility

ui/package.json
Same as https://github.com/argoproj/argo-ui/pull/555, similar to https://github.com/argoproj/argo-cd/commit/b1b5ce211eedfb9354f7661b23b60469f9b103d7
- it was listed as `MIT` for some reason (copy+paste?), while Argo uses Apache, including this repo's own `LICENSE` file
- also CNCF uses Apache
fix `package.json#license` field
=> fix(ui): `package.json#license` should be Apache

persist/sqldb/workflow_archive.go
Fixes https://github.com/argoproj/argo-workflows/pull/12912/files#r1572901283
This PR loads `status.message`, `status.estimatedDuration`, `status.resourceDuration`, and `spec.suspend` for archived workflows, since UI may need them based on [workflows-service.ts](https://github.com/argoproj/argo-workflows/blob/main/ui/src/app/shared/services/workflows-service.ts#L39-L54) and [reports.tsx](https://github.com/argoproj/argo-workflows/blob/bbc1c08ce20e15b07de37f61f4a12889ec962623/ui/src/app/reports/reports.tsx#L59-L65).
=> fix: load missing fields for archived workflows

docs/overrides/main.html
Follow-up to https://github.com/argoproj/argo-workflows/pull/12360#issuecomment-1970762484 and a [previous Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.9ogkxyklinsn) about that
Remove Giscus as it does not work well with versioned documentation and creates inefficient, hard-to-search and hard-to-answer questions
- Giscus creates a separate page for each version of the docs, including `release-3.4`, `release-3.5`, `latest` and `stable`  <details>
- each of those has its own URL, and that is what Giscus uses. Translations would amplify this as well.
- that also means the old GH Pages docs still have their own Giscus pages, but are no longer used 😕
- this makes for lots of duplicative discussion pages, which makes it …
=> docs: remove Giscus integration

Makefile
Fixes #13112
Unable to build the project using `make start UI=true`, and fails because of my M1 arch
I updated the `TARGET_PLATFORM` value on the Makefile to be able to also handle my arch value which is `aarch64`
=> fix(build): `uname` handling for mac M1 arch. Fixes #13112

test/e2e/functional/workflow-exit-handler-sleep.yaml, test/e2e/functional_test.go, workflow/controller/operator.go
Fixes #13052
I have created a workflow with an exit handler. When the exit-handler was running I terminated the workflow. I expected all exit handler nodes to be in the "Failed" phase after termination. However, the "StepGroup" and "Steps" type nodes were still in the "Running" phase. After the event was received the `onExitHandler` template was never executed due to `woc.GetShutdownStrategy().ShouldExecute(true) ` being part of the `if`. This means that it blocks the execute template which updates the node status. 
1.  Remove the `woc.GetShutdownStrategy().ShouldExecute(true)` from `if`
2. Allow `executeTemplate` on the exitNode only if the exit node exists, or if `woc.GetShutdownStrategy().ShouldExecute(true)`
I added an `e2e` test based on the workflow reported on the issue. Apart from …
=> fix: Allow termination of workflow to update on exit handler nodes. fixes #13052

.github/workflows/release.yaml
Fixes https://github.com/argoproj/argo-workflows/pull/12791#issuecomment-2155929515
Per the linked comment above, it seems like `Azure/docker-login` may have set this env var and so when that was changed to `docker/login-action`, this line errored out
- set a default for `$DOCKER_CONFIG` in case it is unset
- Per [Docker's docs](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables), the default is `~/.docker/config.json` (can also confirm locally)
This new line runs locally for me:
```
❯  : ${DOCKER_CONFIG:=~/.docker}; echo "$DOCKER_CONFIG"
/<redacted>/.docker
```
and `$DOCKER_CONFIG` is unset without it
But testing the entire GHA workflow is unfortunately very non-trivial 😕
=> fix(release): set `$DOCKER_CONFIG` if unset

workflow/controller/operator.go
It is likely that a busy kubernetes API will fail to create a PDB occasionally. This results in the whole workflow being marked as failed, when this is most likely something that will succeed on retry.
PDB creation only happens to workflows in state Unknown, so delay marking the workflow is running until after we know if PDB creation has succeeded.
If PDB creation fails then requeue the workflow and log the failure.
Modified `createPDBResource()` to mostly fail (1 in 20 succeeded). Submitted multiple simultaneous copies of [examples/default-pdb-support.yaml](../blob/main/examples/default-pdb-support.yaml) modified for a longer sleep, and ensured they:
* All started eventually
* All started with their PDB having been created
This isn't suitable for a regression test that I can think of …
=> fix: don't fail workflow if PDB creation fails

docs/walk-through/steps.md
Fixes https://github.com/argoproj/argo-workflows/discussions/9907#discussioncomment-6225981, which I discovered after going through all old Giscus discussions per #13138 "Future Work"
Aligns with my other copy-edits of docs pages
Simplify various sentences in the page, follow the style guide, and improve some confusing bits
- specify _which_ CLI command to use, and link to the reference for it as well
- this has confused readers in the past, especially beginners
- refer to the reader as "you", per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#address-the-reader-as-you)
- simplify several sentences, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
- prefer 1 sentence per line of markdown, per [style …
=> docs: copy-edit of Steps page

workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go, workflow/util/util.go, workflow/util/util_test.go
Fixes #11130
Fixes #13122
1. `podSpecPatch` missed keywords `null` after merging(wf/tmpl), so removing fields in map/slice by `podSpecPatch` does not work.
2. workflow-level `podSpecPatch` does not work when workflow is submitted from template by `workflowTemplateRef`.
1. Apply the workflow/template  `podSpecPatch` to the pod spec sequentially avoiding the merge operation.
2. Apply `podSpecPatch` in `woc.execWf.Spec` instead of `woc.wf`.
UT and local test
=> fix: Apply podSpecPatch  in `woc.execWf.Spec` and template to pod sequentially

test/e2e/metrics_test.go, test/e2e/testdata/workflow-dag-metrics.yaml, workflow/controller/dag.go
Fixes #12821
Metrics did not caculate as expected when using `templateDefaults` in workflows of DAG type.
Merge `templateDefaults` into task tmpl when collecting the completed task metrics.
local test and e2e test
=> fix: Merge templateDefaults into dag task tmpl. Fixes #12821

docs/argo-server-auth-mode.md
I linked to this [in Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1717189187821979?thread_ts=1717176020.109829&cid=C01QW9QSSSK) recently and realized how dated it was 😬 
Also aligns with my other docs copy-edit PRs
- this page had some out-of-date information, had inconsistent terminology, and lacked links to several of the features it mentioned
- it sorely needed an update
- remove outdated statement about RBAC mapping
- this feature has existed since SSO RBAC was implemented (#4198), so replace with a link to that feature
- <details><summary>terminology & consistency improvements:</summary>
- "choose" -> "configure"
- "which kube config" -> how to "authenticate"
- there is no kube config in some of these cases either, so this terminology was not only inconsistent with the …
=> docs(server): full copy-edit of auth mode page

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #13058 
Evaluate retry expression after evaluating lastchildstatus,
- so that successful workflow/node doesn't receive `retryStrategy.expression evaluated to false` in the message field
This also aligns with
https://github.com/argoproj/argo-workflows/blob/6c8393fa392557637e9a23faa9a38696acaba207/workflow/controller/operator.go#L1091
- retry only intended to work with nodes that are failed or errored
- add unit test, fail
- add operator change, succeed
- workflow run verify `retryStrategy.expression evaluated to false` doesn't show up on successful workflow
=> fix: only evaluate retry expression for fail/error node. Fixes #13058

server/workflow/store/sqlite_store.go
Fixes #13154
Fixes #13140
[zombiezen/go-sqlite](https://github.com/zombiezen/go-sqlite/blob/main/doc.go#L32) is not thread safe when used through a single connection. The current code is provably racing (run the server with `-race` and a few workflows being run) and it will tell you this if you `argo list` via the server a few times. Unless it crashes first.
This change doesn't attempt to move to a multiple connection model, it's a minimal change to stop the server crashing all the time, by mutexing the use of the sql connection.
Running v3.5.7
Inject 200 `example/dag-diamond.yaml`s into your cluster. Run `argo list -s <server>` to list the workflows. It will crash within a few attempts, usually
With this change it didn't crash in 200 attempts at `argo list`.
`-race` build of the server …
=> fix(server): mutex calls to sqlitex

ui/package.json, ui/yarn.lock
Fixes #7789 
Dropdown arrow was half hidden, and we want to fix it to improve the visual
Upgrade to latest version of argo-ui components
- include fix https://github.com/argoproj/argo-ui/pull/178
build success
arrow visible
functioning normal
---
---
=> fix(ui): upgrade `argo-ui` for visible filter dropdown bar arrow. Fixes #7789

pkg/apiclient/argo-kube-client.go, server/apiserver/argoserver.go, server/workflow/workflow_server.go, server/workflow/workflow_server_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/13177
Try to apply the following manifests into a k8s cluster:
```
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.5.7/namespace-install.yaml
```
With the image built from this PR, don't see the following permission errors anymore:
> 14.612814       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-server" cannot list resource "workflows" in API group "argoproj.io" at the cluster scope
E0614 16:39:14.612865       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Workflow: failed to list …
=> fix(server): don't use cluster scope list + watch in namespaced mode. Fixes #13177

cmd/argoexec/commands/wait.go, test/e2e/artifacts_test.go, test/e2e/fixtures/when.go, test/e2e/testdata/artifactgc/artgc-artifact-not-written.yaml, workflow/executor/executor.go, workflow/executor/executor_test.go
The fact that it's being listed in the NodeStatus is causing ArtifactGC to attempt to delete it (and fail doing so).
Fixes: #12845 
If an Artifact file didn't get written, it shouldn't be in the outputs for the TaskResult (and thus the Outputs for the Node) just because it was listed as an Artifact in the Workflow.
Only if the Artifact file is successfully written does the wait container include it as one of the Output Artifacts in its `WorkflowTaskResult`. The Workflow Controller uses that `WorkflowTaskResult` information to populate the `NodeStatus` of the Workflow. This is the information that ArtifactGC uses to determine what needs to be deleted. 
The person who submitted the Issue [tested](https://github.com/argoproj/argo-workflows/discussions/12845#discussioncomment-9616341) the …
=> fix: don't necessarily include all artifacts from templates in node outputs

docs/enhanced-depends-logic.md
Follow-up to https://github.com/argoproj/argo-workflows/pull/13087#pullrequestreview-2084423364 and my other full page copy-edits of docs
Fixes https://github.com/argoproj/argo-workflows/discussions/8693#discussioncomment-5076751
Addresses the first question of #10363 as well
Heavily simplify the page, elaborate on some details, and use consistent, up-to-date style
larger style changes:
- heavily simplify several sentences and paragraphs, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language) <details>
- remove unnecessary "Introduction" section -- just introduce it
- describe how `depends` improves on `dependencies`, instead of explaining the history and limitations
- same description, but substantially more concise and no longer …
=> docs: full copy-edit of enhanced `depends` page

workflow/controller/controller_test.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go
Fixes #13210
see https://github.com/argoproj/argo-workflows/issues/13210#issuecomment-2175332795
Mark `Pending` nodes of pod type `Failed` when shutting down.
updated UT
=> fix: Mark `Pending` pod nodes as `Failed` when shutting down. Fixes #13210

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/cron-workflows.md, docs/fields.md, docs/variables.md, pkg/apis/workflow/v1alpha1/cron_workflow_types.go, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1CronWorkflowStatus.md, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1StopStrategy.md, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_cron_workflow_status.py, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_stop_strategy.py, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1CronWorkflowStatus.md, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1StopStrategy.md
Docs for `stopStrategy` implemented in #12305 to be released on v3.6
=> docs: add CronWorkflow stopStrategy docs 

ui/src/app/shared/pod-name.test.ts, ui/src/app/shared/pod-name.ts, ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Fixes #13038 
Containerset nodes currently do not retrieve their logs in the UI. This is due to the podname calculation failing, which makes the request to the backend incorrect. This fix will hopefully become obsolete when https://github.com/argoproj/argo-workflows/issues/12528 is fixed, but until then this should do the trick.
Uses a better podname when the node type is `Container`.
Tried a few different containerset templates to verify the fix, and a few none-containetset templates to verify that there is no regression.
=> fix(ui): Use proper podname for containersets. Fixes #13038

docs/argo-server-sso-argocd.md
Fixing wordings for SSO with ArgoCD for client_id
Add a comment in argo-cd/values.yaml in documentation to reflect that `client_id` should be the actual OIDC client-id received from OIDC provider and it should be in plain-text format.
This info was missing earlier.
=> docs(sso): clarify Dex `staticClients` ID for `argo-cd/values.yaml` block

ui/src/app/shared/components/parameters-input.tsx
Fixes #13242 
Per the issue, parameter tooltips/descriptions would disappear for _all_ parameters as soon as you entered any text into any _one_ of the parameter inputs. This buggy behavior would ofc make tooltips substantially less useful.
- the `map` statement missed `description` (and other parts of a `Parameter`) as it only listed a few fields and not all of them
- use spread args to (shallow-)copy over the whole object instead, and then just overwrite the `value` as nothing else changes
- spread makes this a lot more future-proof and less buggy, since we're not re-typing all of the unchanged fields
Confirmed it was working locally after typing some inputs. Screenshot:
This is not directly backportable to 3.4 as the code has changed quite a bit (e.g. this shared component didn't exist …
=> fix(ui): parameter descriptions shouldn't disappear on input

CHANGELOG.md, hack/changelog.sh
Partial fix for https://github.com/argoproj/argo-workflows/pull/13206#discussion_r1643723732
- there's a filter on the commits in the changelog generation script, but the CHANGELOG does not mention that
- say "Selected Changes" to explicitly note that it is not full
- and put a link to the Full Changelog/Full Diff via GH compare view above that
- include all Contributors to the release, not just the filtered ones
- also collapse the list of contributors by default with the HTML `<details>` tag
I ran the `changelog.sh` script locally and committed the resulting CHANGELOG.md in this PR.
- See the [rendered commit](https://github.com/argoproj/argo-workflows/blob/6ee1565702071b919de7e273742afc8811e9f656/CHANGELOG.md)
- I also double-checked the entirety of the diff myself
=> build(docs): include full changelog and all contributors

workflow/controller/controller_test.go, workflow/controller/operator.go
Fixes #12659 
Agent pod will only be created when taskset nodes exist, so do not delete it if it does not exist.
local test and updated UT
=> fix: Only cleanup agent pod if exists. Fixes #12659

util/printer/workflow-printer.go
Follow-up to https://github.com/argoproj/argo-workflows/pull/12970#discussion_r1576647976
Simplify and optimize some code that previously went a long way around to do an equivalent check. It also previously had a bug in that complexity and this makes it more resilient as such
- instead of retrieving a template from the node only to check its type, we can check the type of the node directly
Per https://github.com/argoproj/argo-workflows/pull/12970#discussion_r1661823031:
- Semantically, the template types to node types have a conversion [in the `GetNodeType` function](https://github.com/argoproj/argo-workflows/blob/3f9b992cdddb09633ef329c13eab1823ca6e5f3e/pkg/apis/workflow/v1alpha1/workflow_types.go#L3030) (that is directly above the `IsPodType` function who's usage was removed in this PR) …
=> refactor(cli): simplify counter in printer

workflow/artifacts/s3/s3.go
Fixes #12857
We see error `The specified key does not exist` when gc artifact are not compressed and is directory
Determine if artifact is dir and delete accordingly (used in artifact gc)
Test log
```
time="2024-05-25T03:16:16.108Z" level=info msg="S3 Delete artifactttt: key: fanout/collected-other-datasets/yo-test-zl4wk/"
time="2024-05-25T03:16:16.108Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-05-25T03:16:16.112Z" level=info msg="Listing directory from s3" bucket=my-bucket endpoint="minio:9000" key=fanout/collected-other-datasets/yo-test-zl4wk/
time="2024-05-25T03:16:16.113Z" level=info msg="Deleting object from s3" bucket=my-bucket endpoint="minio:9000" key=fanout/collected-other-datasets/yo-test-zl4wk/hello-world.txt …
```
=> fix: allow artifact gc to delete directory. Fixes #12857

Dockerfile
The following CVEs were found in the argoexec image:
- [CVE-2024-24790](https://security-tracker.debian.org/tracker/CVE-2024-24790)
- [CVE-2024-24789](https://security-tracker.debian.org/tracker/CVE-2024-24789)
Bumped up golang image version to [golang:1.21-alpine3.19](https://hub.docker.com/layers/library/golang/1.21-alpine3.19/images/sha256-ce2562ac25fe59995a4f6d92d8d8b762e5f2facd0c09ca539a75a3e32ab24ce4), which uses go 1.21.12, in the builder image.
Build passed, and the CVEs were resolved from the image.
=> fix(build): bump golang to 1.21.12 in builder image to fix CVEs

.github/workflows/retest.yaml
Follow-up to #13000
- they get triggerred [quite often](https://github.com/argoproj/argo-workflows/actions/workflows/retest.yaml) (for every comment), and though they only run for 2s, it would be good to filter out more of them and use less CI time
- only run on `created` events, skip all `edited` events
- the vast majority of `edited` events will be for unrelated comments
- you can delete and comment again to trigger a retest instead if you had a typo
- only run on PR comments, following [GH docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only)
- it would fail otherwise, but this prevents that scenario entirely
=> ci(retest): filter more comments to use GHA less

test/e2e/resource_template_test.go, test/e2e/testdata/resource-templates/failed.yaml, workflow/executor/resource.go
Fixes #13299 using the simpler/non-breaking change I outlined in https://github.com/argoproj/argo-workflows/issues/13299#issuecomment-2211119337
- Technically a follow-up to #12544
- `kubectl` will `os.Exit(1)` upon error, meaning it won't run through all our error handling code, resulting in a stuck Workflow
- as the respective `workflowtaskresult` will never be marked as complete (or errored etc)
- use the same method that `kubectl`'s [own tests do](https://github.com/kubernetes/kubectl/blob/68dbd0767a9175dd30eb9dc8687ba5167c678c9b/pkg/cmd/explain/explain_test.go#L217), customizing the error with `BehaviorOnFatal`
I tested this worked while testing #13317 (where I hit the bug _a lot_ while testing) and it does work:
```
kubectl get workflow
NAME                        STATUS      AGE …
```
=> fix(resource): catch fatal `kubectl` errors

docs/cron-workflows.md
Made a lot of modifications to this page during reviews of #13280 and #12696, so wanted to make the rest match the current style guides.
Also aligns with all my other full copy-edits of docs pages
- <details><summary>follow the style guides</summary>
- simplify a bunch, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
- use active voice and present tense where possible, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-present-tense)
- avoid Latin phrases, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases)
- avoid leveling words, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-words-that-assume-a-specific-level- …
=> docs: full copy-edit of CronWorkflows page

workflow/controller/operator.go
For better code readability
Use templateScope instead of repeatedly retrieving it from the function.
run locally
=> refactor: use templateScope var instead of repeatedly retrieving it from function

docs/upgrading.md
Three of them used an H2 instead of an H3, see screenshot of the rendered docs:
<details>
</details>
- `##` -> `###` under the "Upgrading to 3.4" section
=> fix(docs): correct headings in 3.4 upgrade notes

cmd/argo/commands/lint_test.go, go.mod, test/e2e/cli_test.go, workflow/common/parse.go
Fixes #13006
Currently, when linting a `CronWorkflow` definition file, `argo lint` fails to detect keys with incorrect capitalization. This oversight can lead to unexpected behavior when applying these definitions using `kubectl`. Prior to this fix, `argo cron create` would ignore capitalization issues and proceed with the provided values, creating an inconsistency between `kubectl` and `argo cron create` behaviors.
By addressing this issue, we aim to:
1. Enhance the linting process to catch capitalization errors early in the development cycle.
2. Align the behavior of `argo cron create/argo submit` with `kubectl`, ensuring both tools report errors for incorrectly capitalized fields.
3. Streamline the workflow creation process by providing consistent feedback across different Argo and …
=> fix(cli): `argo lint` with strict should report case-sensitive errors. Fixes #13006

.devcontainer/pre-build.sh
Follow-up to #13111, might make the `|| true` no longer necessary as well
- it seems like the `-R` isn't necessary??
- that would take very long for me to run and without it I seemed to get a fresh build working fine
- remove the recursive `-R` from the `chown` command in `pre-build.sh`
Did a local rebuild
~Will also confirm with a fresh Codespace of this branch (it's building right now)~
- **EDIT**: Made a fresh Codespace, which built and ran `make start UI=true` successfully (and the UI, Controller, Server et al were running correctly as well)
=> fix(devcontainer): remove `-R` in `chown`

docs/walk-through/artifacts.md
Saw a one character typo while reading the docs. Removed some superfluous trailing whitespace since I already had the file open.
=> docs(artifacts): fix typo and remove superfluous whitespace

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #12997
Root cause:
say we have dag
```
task: A(containerset)
task: B(containerset), depends: A
task: C(containerset), depends: A
```
if task B is processed and started before the controller can process C,
C will find the deepest node in A without considering boundaries and mistakenly attach to B
if a node(containerType) child node do not have the same boundyID, we return the current node as the deepest outbound node.
Tested:
Before code change
- ran the workflow from the issue ticket, failed: incorrect dependency and controller panic
- ran new unit test without change, failed as expected
After code change
- ran the workflow from the issue ticket, succeeded with the correct dependencies
- ran unit test with the code change, succeed
=> fix: constraint containerType outboundnode boundary. Fixes #12997

Makefile
On my polish WSL2 machine sorting seems to be working a bit different than for the rest: https://github.com/argoproj/argo-workflows/pull/13368/commits/1bd4d6681c723b66074ac6ad03068aa974c42446#diff-fba04b914460eece7fe0dab2ede9808db215f0b6c859d6f34293b454b2863a86L28
This env var seems to make it consistent with what's already in the repository.
=> chore: make `.spelling` sorting more deterministic

hack/docs/fields.go, hack/docs/null_fields.go, test/e2e/agent_test.go, test/e2e/argo_server_test.go, test/e2e/artifacts_test.go, test/e2e/cli_test.go, test/e2e/cluster_workflow_template_test.go, test/e2e/cron_test.go, test/e2e/daemon_pod_test.go, test/e2e/estimated_duration_test.go, test/e2e/executor_plugins_test.go, test/e2e/expr_lang.go, test/e2e/failed_main_test.go, test/e2e/functional_test.go, test/e2e/hooks_test.go, test/e2e/http_artifacts_test.go, test/e2e/invalid_command_test.go, test/e2e/malformed_resources_test.go, test/e2e/metrics_test.go, test/e2e/pod_cleanup_test.go, test/e2e/progress_test.go, test/e2e/resource_template_test.go, test/e2e/retry_test.go, test/e2e/run_as_not_root_test.go, test/e2e/semaphore_test.go, test/e2e/signals_test.go, test/e2e/workflow_configmap_substitution_test.go, test/e2e/workflow_inputs_orverridable_test.go, test/e2e/workflow_template_test.go, test/e2e/workflow_test.go
Since [go 1.18](https://go.dev/doc/go1.18) `go fix` will remove the `// +build` lines from code as it is superseded by `//go:build`.
Two autogenerated files still have these in and I cannot see a way to prevent the generators recreating them, but otherwise this is just a tidy up. I considered automating a `go fix` run in CI, but that's hindered by this.
=> chore: remove legacy go build tags

pkg/apis/workflow/v1alpha1/cron_workflow_types.go, pkg/apis/workflow/v1alpha1/cron_workflow_types_test.go, test/e2e/cron_test.go
Using `schedules` with a timezone specified does not work. The cron schedule given to the cron backend includes the CRON_TZ=zone string and should not.
The actual fix is one line to correctly honor the timezone flag on `getSchedules` so that it doesn't double append when that flag is set, nor single append when it is not. GetSchedules() would return an invalid cron string resulting in the error:
```
could not schedule CronWorkflow" cronWorkflow=argo/go-forward error="expected exactly 5 fields, found 6: [CRON_TZ=America/Los_Angeles 30 2 * * *]
```
Added some more unit tests to check this behaves as expected, and a smoke e2e test.
I have to say, the original set of tests for #12616 looked like it really should cover this, so I was surprised when nothing broke when I made the change and it …
=> fix(cron): `schedules` with `timezone`

docs/configure-artifact-repository.md, examples/input-artifact-azure.yaml, workflow/artifacts/azure/azure.go, workflow/artifacts/azure/azure_test.go
Fixes #10297
Currently, argo-workflows support Azure blob storage artifacts by authentication only via Access Keys. Azure, however, also supports auth via [Shared Access Signatures (SAS)](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json).
This PR adds support for authentication via SAS.
To avoid spec changes, we re-use `spec.name.inputs.name.azure.accountKeySecret` to hold either an access key or SAS token. A new `isSASAccountKey` method checks whether the provided secret contains an access key or a SAS token. Since SAS tokens are nothing but URL query parameters, a simple regex can identify a SAS token. Once identified, we use the SAS token to initialize a …
=> feat: Support authentication via Shared Access Signatures (SAS) for Azure artifacts (Fixes #10297) 

docs/upgrading.md, ui/src/app/modals/new-version-modal.tsx
Addresses #12545, https://github.com/argoproj/argo-workflows/discussions/13126#discussioncomment-9643345, #13356, etc
- The Archived Workflows UI merge (#11121) been asked about several times on issues, discussions, and Slack, so address it directly in the docs
- previously, it was mentioned only in [the 3.5 blog post](https://blog.argoproj.io/whats-new-in-argo-workflows-v3-5-f260e8603ca6) and nowhere else, so I can understand some of the confusion as the blog is a bit of a secondary resource that is not the easiest to search either
- add a section in the 3.5 upgrading notes about this
- explicitly say that it is not breaking as the API was not removed
- (although one could say it is "UI breaking")
- also add a small mention about it in the UI's new version modal
Docs and UI builds pass
=> docs: add Archived Workflows merge to the Upgrading Notes

.devcontainer/pre-build.sh
https://github.com/argoproj/argo-workflows/pull/13348 removed a recursive flag from chown. I believe was done because this is slow on macintosh filesystems.
This [breaks codegen](https://cloud-native.slack.com/archives/C0510EUH90V/p1721637621193269) with
```
fatal: could not create leading directories of '/home/vscode/go/src/github.com/gogo/protobuf': Permission denied
```
This is a smaller recursive chown which fixes the issue for me.
=> fix(devcontainer): `chown` regression for `make codegen`

manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, workflow/controller/agent.go, workflow/controller/agent_test.go, workflow/controller/operator.go, workflow/controller/operator_agent_test.go, workflow/controller/taskset.go, workflow/controller/workflowpod.go
Fixes #12703
1. Node status is non-fulfilled when agent pod failed.
2. `argo-cluster-role` can not get secrets `argo-workflows-agent-ca-certificates`
1. Mark non-fulfilled taskSetNodes error when agent pod failed.
2. add secrets `argo-workflows-agent-ca-certificates` get permission to `argo-cluster-role`
UT
Delete `hello-executor-plugin` serviceaccount to simulate agent pod failure scenario.
1. single step example
```yaml
kind: Workflow
metadata:
generateName: hello-
spec:
templates:
- name: main
plugin:
hello: { }
```
```
Name:                hello-q8h7f
Status:              Error
Message:             create agent pod failed with …
```
=> fix: Mark non-fulfilled taskSetNodes error when agent pod failed. Fixes #12703

ui/src/app/event-flow/icons.ts, ui/src/models/event-source.ts
Fixes #13386 
References argoproj/argo-events#1927
Add support for displaying Bitbucket Server event source icon in the Argo event flow UI.
Added icon support for Bitbucket Server event source.
- Tested the UI to ensure the Bitbucket Server event source icon is displayed correctly.
- Built the Docker image and applied it to my k8s cluster to verify.
- Attached screenshots for UI changes.
=> fix(ui): display Bitbucket Server event source icon in event flow. Fixes #13386

tasks.yaml
- while the UI needs the server to connect to the API, it can start and run in parallel
- it also has some small functionality independently of the Server; it'll just error on API requests
- in particular, when I was working on the Server and UI simultaneously (e.g. #13347), any Server change would cause the whole UI task to restart, even if I did not change the UI
- this was pretty slow and inefficient as such, so remove the dep
- remove `ui` task's dependency on `server` task
- remove unnecessary `mutex: download`
- the two dep installations can run concurrently, they're in totally separate directories and use different tools (go vs yarn)
- something I did in https://github.com/argoproj/argo-workflows/pull/11928#discussion_r1343064901 as well
=> fix(build): slightly optimize UI tasks in `kit` `tasks.yaml`

workflow/artifacts/common/load_to_stream.go, workflow/artifacts/common/load_to_stream_test.go
Replaces #13037 
This test has an infrequent flake, see #13037 
The current test counts files in `/tmp` and hopes there are the same number before and after the test, which is fragile
Add a prefix to the stream temporary files.
Only count files in `/tmp` which have this prefix.
Tested locally. Tested with a file called `/tmp/wfstream-asdfasd` and extra logging in the test to show the numbers are as expected.
Tested with the `os.Remove()` removed from `selfDestructingFile.Close()` to show failure.
=> fix(test): load to stream tmp file counting

.github/workflows/ci-build.yaml, docs/releases.md
* k8s 1.26 and k8s 1.27 are eol upstream (https://kubernetes.io/releases/)
* adds test coverage for 1.30
* added test coverage for 1.30 and 1.28
* dropped coverage for 1.26
e2e tests
=> ci: test k8s version 1.28 and 1.30

go.mod
This fixes the following issue in my local setup:
```
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
```
See https://github.com/golang/go/issues/65568
=> build: resolve error for toolchain not available

util/archive/archive_test.go, util/auth/auth_test.go, util/fields/fields_test.go, util/file/fileutil_test.go, util/instanceid/service_test.go, util/intstr/parametrizable_test.go, util/kubeconfig/kubeconfig_test.go, util/printer/workflow-printer_test.go, util/template/replace_test.go, util/template/resolve_var_test.go, util/template/template_test.go, util/template/validate_test.go, util/tls/tls_test.go, util/wait/backoff_test.go
This is part of a series of test tidies started by #13365.
The aim is to enable the `testifylint` `golangci-lint` checker.
This commit converts `assert.Error` checks into `require.Error` for the part of the codebase, as per https://github.com/argoproj/argo-workflows/pull/13270#discussion_r1667248031
In some places checks have been coalesced - in particular the pattern
```go
if assert.Error() {
assert.Contains(..., "message")
}
```
is now
```go
require.ErrorContains(..., "message")
```
Getting this wrong and missing the `Contains` is still valid Go, so that's a mistake I may have made.
=> refactor(tests): `assert.Error` -> `require.Error` (`util/`)

pkg/apiclient/http1/facade_test.go, pkg/apis/workflow/v1alpha1/anystring_test.go, pkg/apis/workflow/v1alpha1/container_set_template_types_test.go, pkg/apis/workflow/v1alpha1/item_test.go, pkg/apis/workflow/v1alpha1/plugin_types_test.go, pkg/apis/workflow/v1alpha1/validation_utils_test.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, pkg/plugins/spec/plugin_types_test.go
This is part of a series of test tidies started by #13365.
The aim is to enable the `testifylint` `golangci-lint` checker.
This commit converts `assert.Error` checks into `require.Error` for the part of the codebase, as per https://github.com/argoproj/argo-workflows/pull/13270#discussion_r1667248031
In some places checks have been coalesced - in particular the pattern
```go
if assert.Error() {
assert.Contains(..., "message")
}
```
is now
```go
require.ErrorContains(..., "message")
```
Getting this wrong and missing the `Contains` is still valid Go, so that's a mistake I may have made.
=> refactor(tests): `assert.Error` -> `require.Error` (`pkg/`)

cmd/argo/commands/clustertemplate/util_test.go, cmd/argo/commands/common/get_test.go, cmd/argo/commands/cron/util_test.go, cmd/argo/commands/list_test.go, cmd/argo/commands/resubmit_test.go, cmd/argo/commands/retry_test.go, cmd/argo/commands/stop_test.go, cmd/argo/lint/lint_test.go, cmd/argoexec/commands/emissary_test.go, cmd/argoexec/commands/emissary_windows_test.go
This is part of a series of test tidies started by #13365.
The aim is to enable the `testifylint` `golangci-lint` checker.
This commit converts `assert.Error` checks into `require.Error` for the part of the codebase, as per https://github.com/argoproj/argo-workflows/pull/13270#discussion_r1667248031
In some places checks have been coalesced - in particular the pattern
```go
if assert.Error() {
assert.Contains(..., "message")
}
```
is now
```go
require.ErrorContains(..., "message")
```
Getting this wrong and missing the `Contains` is still valid Go, so that's a mistake I may have made.
=> refactor(tests): `assert.Error` -> `require.Error` (`cmd/`)

config/config_test.go, config/controller_test.go, config/ttl_test.go, persist/sqldb/archived_workflow_labels_test.go, persist/sqldb/offload_node_status_repo_test.go
This is part of a series of test tidies started by #13365.
The aim is to enable the `testifylint` `golangci-lint` checker.
This commit converts `assert.Error` checks into `require.Error` for the part of the codebase, as per https://github.com/argoproj/argo-workflows/pull/13270#discussion_r1667248031
In some places checks have been coalesced - in particular the pattern
```go
if assert.Error() {
assert.Contains(..., "message")
}
```
is now
```go
require.ErrorContains(..., "message")
```
Getting this wrong and missing the `Contains` is still valid Go, so that's a mistake I may have made.
=> refactor(tests): `assert.Error` -> `require.Error` (other unit tests)

server/auth/serviceaccount/claims.go, server/auth/serviceaccount/claims_test.go, ui/src/app/app-router.tsx, ui/src/app/shared/utils.ts
Fixes #12658, for which the root cause also resulted in confusion in #13316
Follow-up to #9008
- previously, in client auth mode, no SA name or ns was listed, causing `userNamespace` to be `undefined`
- and that would cause `currentNamespace` to be set as the string literal `"undefined"`
- derive the SA name and namespace from the `subject` at the end of `claims.go`
- invert the conditional as well for less nesting and complexity, similar to other refactors of mine
- add some defensive code to the UI as well, so that in case of `undefined` (which should be substantially rarer now), don't set the namespace in the URL to literally "undefined" <details>
- invert `fixLocalStorageString` conditional because it very confusingly would _implicitly_ return `undefined` before
- and catch the case …
=> fix(server): don't return `undefined` SA NS

persist/sqldb/mocks/WorkflowArchive.go, persist/sqldb/null_workflow_archive.go, persist/sqldb/workflow_archive.go, workflow/controller/estimation/estimator_factory.go, workflow/controller/estimation/estimator_factory_test.go
Fixes #13382
- Added a query for during estimation
- Avoided using SQL JSON extraction as it is slow (removed unnecessary columns)
- Changed the filter for phase from `exists` to `phase = 'Succeeded'`
```
2024/07/26 18:32:00 	Session ID:     00001
Query:          SELECT "name", "namespace", "uid", "startedat", "finishedat" FROM "argo_archived_workflows" WHERE (("clustername" = $1 AND "namespace" = $2 AND "instanceid" = $3) AND "phase" = $4 AND "namespace" = $5 AND exists (select 1 from argo_archived_workflows_labels where clustername = argo_archived_workflows.clustername and uid = argo_archived_workflows.uid and name = 'workflows.argoproj.io/cron-workflow' and value = 'hello-world')) ORDER BY "startedat" DESC LIMIT 1
Arguments:      []interface {}{"default", "argo", "", "Succeeded", …
```
=> fix: improve get archived workflow query performance during controller estimation. Fixes #13382

pkg/apis/workflow/v1alpha1/marshall.go, pkg/apis/workflow/v1alpha1/marshall_test.go, workflow/controller/operator_template_scope_test.go
Fix the name of the function, to get better readability.
rename function  `MustUnmarshalClusterWorkflow` -> `MustUnmarshalClusterWorkflowTemplate`
ran locally
=> chore: properly rename `MustUnmarshalClusterWorkflowTemplate`

pkg/apis/workflow/v1alpha1/workflow_types.go, test/e2e/hooks_test.go, workflow/controller/exec_control.go, workflow/controller/exit_handler_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/taskset.go, workflow/controller/workflowpod.go
Fixes #13060 
Fixes #13252
1. This PR https://github.com/argoproj/argo-workflows/pull/12441 has support plugin nodes shutdown, but HTTP node still not.
2. ~~Fixes _ #12659~~  Split to PR: #13294
3. Fixes #13060 Fixes #13252
Execution control has been applied to the nodes with created pods after pod reconciliation. However, pending and suspended nodes do not have created pods, and taskset nodes use the agent pod. Mark these nodes failed when shutting down or exceeding deadline since pod reconciliation does not take effect on them.
~~Agent pod will only be created when taskset nodes exist, so do not delete it if it does not exist.~~
Split to PR: #13294
Only apply execution control for nodes that are not part of exit handler:
- `failNodesWithoutCreatedPodsAfterDeadlineOrShutdown`: `Pending` …
=> fix: Only apply execution control to nodes that are not part of exit handler.

cmd/argo/commands/server.go, pkg/apiclient/argo-kube-client.go, pkg/apis/workflow/v1alpha1/version_types.go, util/help/topics.go, workflow/controller/operator.go
Raised [in response to this](https://github.com/argoproj/argo-workflows/pull/13265#discussion_r1699400713)
Instead of always linking to latest, link to the versioned documentation where the version of the built software is known
Added a method to split the software version into components.
Changed help.`root` to provide a versioned link to documentation and modified all previous `const` values to be functions as this is now runtime determined. Making the whole thing `const` may be possible but the current encapsulation is nice and none of this is important for performance.
Removed the unused WorkflowTemplates doc links
`make codegen` still generates the same link for `argo server`. Forcing the version to 3.5 generates expected 3.5 links.
=> fix(docs): Provide versioned links to documentation

workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go
Fixes #13057
Self reporting progress does not work when `workflows.argoproj.io/progress` is set.
1. Set initial progress from pod metadata if exists before `podReconciliation`.
2. Prevent the node's existing progress from being overwritten with the initial progress in pod metadata: only override it when workflow uses legacy/insecure pod patch.
Local test and UT.
Workflow demo:
```yaml
kind: Workflow
metadata:
generateName: progress-
spec:
templates:
- name: main
dag:
tasks:
- name: progress
template: progress
- name: progress
metadata:
annotations:
workflows.argoproj.io/progress: 0/100
container:
image: alpine
imagePullPolicy: IfNotPresent
command: [ "/bin/sh", "-c" ]
args:
- |
for i in `seq 1 10`; do sleep 10; echo "$(($i*10))"'/100' > …
```
=> fix: Set initial progress from pod metadata if exists. Fixes #13057

util/env/env_test.go, workflow/controller/operator_metrics_test.go, workflow/controller/operator_test.go, workflow/metrics/metrics_test.go, workflow/metrics/work_queue_test.go
Part of [the refactor](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+testifylint+) started by #13365 to enable us to use testifylint, shift to using InEpsilon or InDelta for floating point comparisons. Mostly use `InEpsilon` as it is more resilient, but using `InDelta` for testing against zero.
Reviewers: As with the others in this series, please feel free to apply patches as you see fit.
=> refactor(tests): testifylint don't use `Equal` for floating point tests

.golangci.yml, server/artifacts/artifact_server_test.go, test/e2e/hooks_test.go
This commit enables testifylint and fixes the 5 changes that have crept in since the beginning of trying to enable it.
This is [part of a series](https://github.com/argoproj/argo-workflows/pulls?q=is%3Apr+testifylint+) which aimed to get this enabled as a useful linter.
The version of golangci-lint we use is a bit old (1.55.1), and isn't catching all the things I was expecting. Once this is merged I'll do a follow up to bump golangci-lint to latest (1.60.1) as well.
=> chore(lint): enable testifylint

ui/src/app/cluster-workflow-templates/cluster-workflow-template-details.tsx, ui/src/app/cron-workflows/cron-workflow-details.tsx, ui/src/app/workflow-templates/workflow-template-details.tsx, ui/src/app/workflows/components/workflow-details-list/workflow-details-list.scss, ui/src/app/workflows/components/workflow-details-list/workflow-details-list.tsx
Fixes #13282
I didn't have the authority to reopen the #13283, so I am creating a new one.
As indicated in the Issue, it is inconvenient that the history is not visible in the WorkflowTemplate details.
CronWorkflow can see it, so I would like to see consistency.
<details>
<summary>No history</summary>
</details>
<details>
<summary>No history</summary>
</details>
=> feat(ui): add history to WorkflowTemplate & ClusterWorkflowTemplate details

config/config.go, docs/metrics.md, docs/upgrading.md, docs/workflow-controller-configmap.yaml, test/e2e/metrics_test.go, workflow/controller/controller.go
This appears to [have been slated for 3.5](https://github.com/argoproj/argo-workflows/blob/0322579ac813f345562f384ed6203a7f45faa484/workflow/controller/controller.go#L1361) but it didn't happen.
Note to reviewers: this is part of a stack of reviews for metrics changes. Please don't merge until the rest of the stack is also ready.
=> feat!: enable Prometheus TLS by default

test/e2e/expectedfailures/exit-handler-fail-missing-output.yaml, test/e2e/functional_test.go, workflow/controller/exit_handler.go
Fixes #13445
This PR addresses a critical issue where exit handlers fail when called on a failed step with a `null` or empty output parameter. Specifically, when a step crashes before creating the output file referenced in `valueFrom`, the exit handler encounters a runtime error: `"invalid memory address or nil pointer dereference".` The problem has been observed in Argo Workflow versions 3.5.5 through 3.5.10.
To resolve this issue:
1. Added a `nil` check before calling `params.Value.String()` in the relevant code section.
2. This check ensures that we only attempt to access the parameter value when it exists, preventing the `nil` pointer dereference.
To ensure the effectiveness of this fix and prevent regression, I've added a new end-to-end (e2e) test case. This test case verifies:
1. …
=> fix: avoid exit handler nil pointer when missing outputs. Fixes #13445

.spelling, config/config.go, docs/metrics.md, docs/workflow-controller-configmap.yaml, workflow/controller/controller.go, workflow/metrics/metrics.go
Implemented because of https://github.com/argoproj/argo-workflows/issues/12589#issuecomment-2174216603
Some backends (e.g. prometheus) only support cumulative temporality while others (e.g. dynatrace) only support delta metrics.
It is possible to configure an opentelemetry collector between argo workflow controller and the backend to convert cumulative metrics into delta metrics but it has some limits (e.g. when controller is restarted or when it is scaled up).
This commit enables the choice of temporality for OpenTelemetry
Temporality is always cumulative by definition in Prometheus
Note to reviewers: this is part of a stack of reviews for metrics changes. Please don't merge until the rest of the stack is also ready.
=> feat: enable configuration of temporality in opentelemetry metrics

config/config.go, docs/metrics.md, docs/upgrading.md, docs/workflow-controller-configmap.yaml, workflow/controller/controller.go, workflow/metrics/instrument.go, workflow/metrics/metrics.go, workflow/metrics/modifiers.go, workflow/metrics/modifiers_test.go
Allows removal of metrics, removal of attributes (labels), and reconfiguration of histogram buckets for all metrics using `modifiers` in the workflow-controller-configmap.
Implemented using opentelemetry views, these modifiers work for Prometheus metrics also
Note to reviewers: this is part of a stack of reviews for metrics changes. Please don't merge until the rest of the stack is also ready.
=> feat: enable configuration of individual metrics

Makefile, cmd/argoexec/commands/emissary_test.go, server/auth/sso/sso.go, server/workflow/workflow_server_test.go, workflow/artifacts/http/http_test.go
#13467 enabled testifylint, but the results weren't quite lining up with my expectations, so I'd suggested bumping the linter version. This PR does that.
[golangci-lint 1.60.1](https://github.com/golangci/golangci-lint/releases/tag/v1.60.1) was released yesterday, but that bumps govet causing some hard to resolve errors. I'll wait for the dust to settle on that before attempting that update.
gosimple: fixes to `server/auth/sso/sso.go`
`S1009: should omit nil check; len() for []string is defined as zero (gosimple)`
testifylint: undo assert->require changes in functions where they won't work correctly
`go-require: do not use require in http handlers (testifylint)`
`go-require: require must only be used in the goroutine running the
test function (testifylint)`
=> chore(deps): bump `golangci-lint` from 1.55.1 to 1.59.1

docs/node-field-selector.md
This field was added in #6885 but is not in the documentation [as noted](https://github.com/argoproj/argo-workflows/pull/13343#discussion_r1696732888)
I opted to keep this an opaque value and not document the relationship with `name` as that is an internal detail that users should not rely on.
=> docs: describe `id` in node field selector

docs/metrics.md, docs/upgrading.md, workflow/metrics/metrics_k8s_request.go
This is a new metric which is a superset of the k8s_request_total
metric. The old metric is retained for backwards compatibility.
A common issue with workflows is that it stresses the kubernetes
API. Using this metric you can get insights into how long each type of
request is taking which should enable optimizations to help alleviate
problems in this area.
The new metric has the same attributes/labels of `kind`, `verb` and
`status_code` but now emits them with a time duration for each type of
response.
Note to reviewers: this is now a standlone commit
=> feat: new k8s request duration histogram metric

docs/metrics.md, docs/upgrading.md, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/metrics/counter_pod_phase.go, workflow/metrics/labels.go, workflow/metrics/metrics.go
From #12589
This is a new metric counting how many pods have gone into each pod
phase as observed by the controller.
This is like pods_gauge, but as a counter rather than a gauge.
The gauge is useful at telling you what is happening right now in
the cluster, but is not useful for long term statistics such as "How
many pods has workflows run" because it may never report some pods at
all. This counter can answer that question.
Note to reviewers: this is now a standalone commit
=> feat: new pod phase counter metric

docs/metrics.md, docs/upgrading.md, test/e2e/metrics_test.go, test/e2e/testdata/cronworkflow-metrics.yaml, workflow/cron/operator.go, workflow/metrics/counter_cronworkflow_trigger.go, workflow/metrics/labels.go, workflow/metrics/metrics.go
From #12589.
A new metric which counts how many times each cron workflow has triggered. A simple enough counter which can be checked against expectations for the cron.
Note to reviewers: this is now a standalone commit
=> feat: new cron workflow trigger counter metric

docs/metrics.md, docs/upgrading.md, test/e2e/metrics_test.go, test/e2e/testdata/workflow-pending-metrics.yaml, workflow/controller/operator.go, workflow/metrics/counter_pod_pending.go, workflow/metrics/labels.go, workflow/metrics/metrics.go
The workflow controller is a kubernetes controller creating
pods. Sometimes those pods do not start, and will remain in pending.
This metric counts the number of pods that may have been observed as
pending, by namespace and truncated reason. The reason is the first
part of the kubernetes pod pending `Reason` up to the first `:` if
present.
It ignores all pods in the `PodInitializing` state as this I consider
unremarkable and temporary.
This is intended for users to create alerts on particular `reasons` or
if this metric is climbing unusually rapidly.
Note to reviewers: this is now a standalone commit
=> feat: new pod pending counter metric

workflow/controller/taskresult.go
https://github.com/argoproj/argo-workflows/blob/66e64c86b9b7d24e2b1d181bf49722319b07c461/workflow/controller/taskresult.go#L93
The variable `old` is `*NodeStatus` since #11451, so `&old` and `newNode` is always not equal now.
use `old` instead of `&old`
local test
Workflow Demo:
```yaml
kind: Workflow
metadata:
name: workflow-sleep
spec:
entrypoint: sleep
templates:
- name: sleep
container:
image: alpine:3.18
args: ["sleep 600"]`
```
Controller log:
```
INFO[2024-06-18T14:28:57.179Z] Processing workflow                           Phase= ResourceVersion=765095 namespace=argo workflow=workflow-sleep
INFO[2024-06-18T14:28:57.190Z] resolved artifact repository                  artifactRepositoryRef="argo/#"
INFO[2024-06-18T14:28:57.190Z] …
```
=> fix: Task result comparison is incorrect, leading to inconsistent comparison results.

test/e2e/artifacts_test.go, test/e2e/testdata/artifactgc/artgc-artifact-not-written-failed.yaml, workflow/controller/artifact_gc.go
Fixes #13499 
if workflow pods length is zero, `anyPodSuccess` should be true, then the `removeFinalizer` can be executed without force
`anyPodSuccess := len(pods) == 0`
run `examples/artifact-gc-workflow.yaml` on mac m1 os, and then delete the workflow
=> fix(controller): remove ArtifactGC `finalizer` when no artifacts. Fixes #13499

test/e2e/cli_test.go, test/e2e/testdata/retry-workflow-with-failed-exit-handler.yaml, workflow/util/util.go
Fixes #13196 
Single-node workflow with failed exit handler can not be retried correctly.
Only reset root node when it is `FailedOrError`, remove the default reset logic.
local test and e2e test
=> fix: Do not reset the root node by default. Fixes #13196

examples/work-avoidance.yaml
create `examples/work-avoidance.yaml` 
echo pod occur error:
```
Error: failed to find name in PATH: exec: "bash": executable file not found in $PATH
```
use `sh` instead of `bash`
=> fix(docs): use `sh` instead of `bash` with `busybox`

ui/src/app/cluster-workflow-templates/cluster-workflow-template-list.tsx, ui/src/app/cron-workflows/cron-workflow-list.tsx, ui/src/app/cron-workflows/cron-workflow-status-viewer.tsx, ui/src/app/event-sources/event-source-list.tsx, ui/src/app/sensors/sensor-list.tsx, ui/src/app/shared/components/timestamp.tsx, ui/src/app/shared/use-timestamp.ts, ui/src/app/workflow-templates/workflow-template-list.tsx, ui/src/app/workflows/components/events-panel.tsx, ui/src/app/workflows/components/workflow-artifacts.tsx, ui/src/app/workflows/components/workflow-details-list/workflow-details-list.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, ui/src/app/workflows/components/workflow-summary-panel.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.scss, ui/src/app/workflows/components/workflows-list/workflows-list.tsx, ui/src/app/workflows/components/workflows-row/workflows-row.tsx
Fixes #12943
To give the user the ability to display workflows start/stop time in ISO format.
I added the ability to switch time format with a toggle clock icon. This settings is persisted in localStorage.
I tested on multiple workflows to make sure this settings is shared across workflows.
=> feat(ui): Add start/end workflows ISO display switch

docs/metrics.md
Add workflow_archive_queue to metrics documentation and sort the list alphabetically.
This was introduced in #13418.
=> docs: add `workflow_archive_queue` to metrics docs

workflow/controller/operator.go
Fixes #13373 
https://github.com/argoproj/argo-workflows/issues/12103#issuecomment-2296174496
Mark its taskResult as completed if pod has been terminated not gracefully.
This issue only occurs when `wait` container is terminated not gracefully, it is hard to reproduce it.
1. submit a workflow with a long running pod.
```yaml
kind: Workflow
metadata:
generateName: sleep-example-
spec:
templates:
- name: main
steps:
- - name: sleep
template: sleep
- name: sleep
container:
command: [sh, -c, sleep 3600]
```
2. `kill -9` wait/main container
```shell
ctr task kill --signal 9 8c66238d4723b9237c4e71d3fd16710f5f985d2ce8f7218ff987e143b3e8140b # wait container
ctr task kill --signal 9 …
```
=> fix: Mark taskResult completed if wait container terminated not gracefully. Fixes #13373

persist/sqldb/offload_node_status_repo.go
don't clean up old records when save
Fixes #13220
=> fix: don't clean up old offloaded records during save. Fixes: #13220

go.mod, go.sum
Fix cve CVE-2024-41110 https://nvd.nist.gov/vuln/detail/CVE-2024-41110
=> chore(deps): bump `docker` from 26.1.5 to 27.1.1

.spelling, docs/running-locally.md
add docs note for `make argoexec-image`, if git core.symlinks disable, it may occur error `signal_darwin`
=> docs(contrib): add note for `signal_darwin` error

test/e2e/functional/param-aggregation-fromoutputs.yaml, test/e2e/functional_test.go, workflow/controller/operator.go, workflow/controller/operator_aggregation_test.go
Fixes #13510
`outputs.result` of a `withItems`/`withParams` will be conditionally `json.Marshal`ed.
Other output parameters are always json.Marshalled, which leads to inconsitency and a complete inability to pass JSON out of withItems outputs straight back in as `withItems`
Conditionally Marshal the outputs.params
* avoiding it if the parameter isn't enclosed in `{` or `[`, primarily to avoid bare numbers as they're valid JSON but need quoting here
* falling back to old behaviour if this fails
Additional e2e test tests the example case.
=> fix: aggregate JSON output parameters correctly

workflow/controller/scope.go, workflow/controller/steps_test.go
Fixed the problem of workflow failure when using optional Artifacts and containing subpaths and loops.
Fixes: #13564
=> fix: ignore error when input artifacts optional. Fixes:#13564

.github/workflows/ci-build.yaml
Small refactor of the CI to expose differences between the matrix entries as matrix variables.
Also reduces duplication of the conditional. 
Move whether we build and start the API to being a matrix value rather than evaluated in 3 places
Let's see if CI passes...?
Will check the API isn't built and started in a false case.
=> refactor(ci): move api knowledge to the matrix

workflow/common/util.go, workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix: provide fallback for 3.4 to 3.5 transition with absent `NodeFlag`. Fixes #12162

docs/configure-artifact-repository.md
Missing documentation update from #12908.
Just add `OSS` as streaming capable in v3.6+.
=> docs(artifacts): notate OSS as streaming capable in v3.6+

test/e2e/manifests/mixins/workflow-controller-configmap.yaml
The executor constantly OOMs locally for me when I run with `make start UI=true`. This increases the memory limits to reduce this from happening.
Increase the memory limits in the controller's configmap.
Tested with `kubectl get configmaps` to make sure executor memory limits increased.
=> chore(test): increase executor memory

persist/sqldb/workflow_archive.go
Fixes #13295
The current implementation appears to be causing postgres always unmarshalling workflow json payload for all the records in the table. by adopting a subquery approach, we are able to optimise the query from a runtime of 11495.734 ms to 44.713 ms. the data size is about 417481 argo_archived_workflows and 1794624 argo_archived_workflows_labels.
this new change is backward compatible and it is tested on our production env (using postgresql).
rewriting the generated query to use a subquery without unmarshalling json payload first (effectively reducing workload required from postgres, although arguably postgres should be smart enough to only perform the operation after querying ;)):
previous:
```sql
SELECT name,
namespace,
UID,
phase,
startedat,
finishedat, …
```
=> fix(api): optimise archived list query. Fixes #13295

util/errors/errors.go, workflow/artifactrepositories/artifactrepositories.go
Fixes #9085.
Remove high levels of error messages that aren't errors. Reduce additional observability costs associated with running Argo Workflows, although negligble.
Clarify the difference between side-effect and non-side-effect functions in utility module.
Renames `IsTransientErr` to `LogIsTransientErr`, which is easily undoable if it's more noise than signal.
Introduces a `LogOnlyTransientErr`, which only logs errors if they're transient. Suitable for a use-case such as trying to fetch an object that doesn't exist when it's optional.
No verification performed due to the (deceptive) simplicity of the change.
=> fix: remove non-transient logs on missing `artifact-repositories` configmap

docs/running-locally.md
I noticed the `CTRL` variable was deleted in 05e13182bb6be97ba6f91a24ea0876cc349d9ab6 and now does nothing, so I figured it's best to delete this section to avoid confusion. This has confused one other contributor before: https://github.com/argoproj/argo-workflows/issues/11879
>I don't think using [one terminal for the controller + server and another for the UI works...](https://argoproj.github.io/argo-workflows/running-locally/#using-multiple-terminals). I'm not seeing any reference to CTRL in the make file. When I try to run the command for starting the UI alone (make start CTRL=false) fails since it tries to boot up the controller again (it is already running).
Delete outdated section
N/A
=> docs(contrib): remove outdated section on using multiple terminals

docs/metrics.md, docs/upgrading.md, test/e2e/metrics_test.go, test/e2e/testdata/cronworkflow-metrics-forbid.yaml, test/e2e/testdata/cronworkflow-metrics-replace.yaml, util/telemetry/attributes.go, workflow/cron/operator.go, workflow/metrics/counter_cronworkflow_policy.go, workflow/metrics/metrics.go
The (new for 3.6) `cronworkflows_triggered_total` metric can be misleading with `concurrencyPolicy: Forbid`. In fixing that I believed it would be much more useful to also count these policies being triggered for cases where this is unexpected.
So this PR adds a new metric called `cronworkflows_concurrencypolicy_triggered` which counts the number of times a CronWorkflows `concurrencyPolicy` has changed something.
The `concurency_policy` attribute can be:
* `Forbid`: Counts the number of times a workflow was not started because one was already running
* `Replace`: Counts the number of times a workflow was terminated because it was being replaced
This PR moves the call to increment `cronworkflows_triggered_total` so that it doesn't count workflow runs suppressed by `Forbid`. This is …
=> feat: concurrency policy triggered counter metric

test/e2e/retry_test.go
Running this test on a multi-node cluster may fail this test as originally written.
There are two conceived success modes for the test:
1. Workflow successfully schedules a second pod on the retry, and then the workflow fails as it is designed to fail. That is the `wfv1.WorkflowFailed` branch.
2. Workflow fails to schedule a second pod so it still `wfv1.WorkflowRunning` and this is because there is only one node in the cluster (e.g. running under k3d).
It may actually be that there are multiple nodes in the cluster but only one for test running, or there is an autoscaler available which may fulfil the node but not in 5 seconds.
So this changes the test match text to allow for more available nodes where the retry pod is still at least briefly unschedulable.
=> test: match on multi-node clusters as well

workflow/controller/dag.go
Fixes #13547
It seems more reasonable to judge `processedTmpl != nil`
=> fix(controller): handle `nil` `processedTmpl` in DAGs

test/e2e/hooks_test.go
`http://dummy.restapiexample.com/api/v1/employees` is called as a test endpoint in this test and must respond 2xx for this test to pass. It is offline, so switch to `https://github.com`.
If github is offline we're probably not running CI anyway.
=> test: fix HttpHandler test

Makefile
As a developer when the Makefile changes the version of a program that it uses or another dependency I would like to use the new version of that program or dependency
Created in response to https://cloud-native.slack.com/archives/C0510EUH90V/p1726666701563199
For all make targets that specify their version in the Makefile specify the Makefile as a dependency so they will get refetched if the Makefile changes. This is crude as it will refetch all dependencies regardless of whether they have changed or not, so touching the Makefile will cause a slower rebuild. Correctness trumps speed here in my opinion.
Add `-y` to the `apt get` call installing clang-format so that it becomes non-interactive. It's annoying to have to type `y` when this runs anyway.
Use the special Makefile variable `$@` …
=> build: ensure Makefile driven dependencies are up to date

docs/metrics.md, docs/workflow-creator.md
Tidies metrics page
The metrics page doesn't do material admonitions correctly
Also addressing a couple of other issues on that page.
Title of metrics page changed from `Prometheus Metrics` to just `Metrics` to show it's new role
Two badly done !!! sections fixed, one shown above. Also modified `workflow-creator.md` to change NOTE->Note to match style of the rest of the !!! admonitions
Added spacing around markdown comment as requested before.
Ran `make docs` and viewed both pages to ensure they looked correct at all changed points.
=> docs: fix metrics page admonitions and other tidying

.github/workflows/ci-build.yaml, Makefile
A bunch of tests have been failing intermittently for awhile now, which is blocking PRs. For example, the `E2E Tests (test-executor, v1.28.13+k3s1, minimal, false)` test fails >50% of the time with the error `ErrImageNeverPull: Container image "quay.io/argoproj/argocli:latest" is not present with pull policy of Never.` ([example run]( https://github.com/argoproj/argo-workflows/actions/runs/11022848664/job/30613101811)). Many of these issues can't be diagnosed without access to the k3s logs.
1. Print the k3s logs using `journalctl` on a build failure. You can see k3s is being run with systemd from the output of the `Install and start K3S` step:
```
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink …
```
=> ci: fix flaky image gc and mysql connect + add k3s debug log

docs/sidecar-injection.md
Addresses https://github.com/argoproj/argo-workflows/issues/12103#issuecomment-2376057950
This adds documentation for an annotation to shut down linkerd-proxy containers that are added as a sidecar to workflow pods through the linkerd service mesh.
If these containers are not closed the pod keeps running and is not completed even though the workflow is done
=> docs: add sidecar kill command for linkerd-proxy

Makefile
I'd like to be able to `make <whatever>` and it just work.
`$(GOPATH)/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh` is created as part of installing go-to-protobuf, but this is not a dependency of `pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go` which uses `generate-groups.sh`
If I change the version of code-generator in use I get 
```bash
bash: /home/vscode/go/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh: No such file or directory
```
I have added this as a direct dependency. We could have a make target of `$(GOPATH)/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh` which might make things clearer, but I'm unconvinced it does, so I did the smaller change.
If I change the version of code-generator we use and install it will now do a rebuild …
=> build: fix `Makefile` dependencies for `zz_generated.deepcopy.go` to include `code-generator` which it uses

.github/workflows/ci-build.yaml, test/e2e/manifests/kubelet-configuration.yaml, workflow/artifacts/http/http_test.go
Fixes #12744 (hopefully)
This addresses the comments from https://github.com/argoproj/argo-workflows/pull/13660. Also, it hopefully fixes the flaky `CI / Windows Unit Tests (pull_request)` test suite, but this is kind of a shot in the dark.
The errors from `CI / Windows Unit Tests (pull_request)` indicate it's trying to write temp files to `/tmp`:
```
--- FAIL: TestArtifactoryArtifactDriver_Load/Found (0.00s)
http_test.go:75:
Error Trace:	D:/a/argo-workflows/argo-workflows/workflow/artifacts/http/http_test.go:75
Error:      	Received unexpected error:
open /tmp/found: The system cannot find the path specified.
Test:       	TestArtifactoryArtifactDriver_Load/Found
```
which obviously isn't the right directory under Windows, but the test does pass sometimes, and it seems like writing to the …
=> ci: follow-up changes and fix flaky Windows tests. Fixes #12744

go.mod, workflow/artifacts/azure/azure.go
Fixes #7402
This a follow up to https://github.com/argoproj/argo-workflows/pull/7440 where we missed one file.
* pkgs/errors is no longer maintained
* changed workflow/artifacts/azure/azure.go to use fmt instead of errors
E2E tests will verify
=> refactor(deps): drop `pkg/errors` as a direct dependency

cmd/argo/commands/archive/get.go, docs/cli/argo_archive_get.md, docs/sidecar-injection.md
Fixes #11898 
Modify the argo archive get command for more information
Added examples for the argo archive get command.
run `argo archive get -h`
=> docs(cli): add examples for `argo archive get` with option explanations

workflow/cron/operator.go, workflow/cron/operator_test.go
This PR allows for unresolved variables to be present in cronworkflows during the evaluation of the `when` clause.
This is needed because workflow variables are not accessible/unresolved when the clause is evaluated.
=> fix(cron): allow unresolved variables outside of `when`

docs/metrics.md
The docs now separate prometheus and OTEL metrics information, but there was some prometheus stuff hanging towards the bottom of the page. It makes sense to move this up.
Also people struggled to read the last line about using a headless service, so made it more obvious and updated the example to match.
=> docs: Clarify headless service for promethus scraping

test/e2e/artifacts_test.go, test/e2e/manifests/mixins/workflow-controller-configmap.yaml, test/e2e/testdata/artifactgc/artgc-non-optional-artifact-not-written.yaml, test/e2e/testdata/artifactgc/artgc-optional-artifact-not-written.yaml, workflow/executor/executor.go
Fixes #13583 
Two issues:
1. Optional artifacts that were not written were still being passed back through the `WorkflowTaskResult`, which was causing Artifact GC to try to delete them (and fail to do so)
2. If any non-optional artifact did fail to get saved because it wasn't present, other artifacts would not get saved
To address # 1 above, only write to `WorkflowTaskResult` the artifacts which have been written, whether or not they're marked "Optional". This is what Artifact GC will attempt to delete.
To address # 2 above, don't prematurely return if an artifact fails to be saved.
e2e test for Artifact GC now includes tests for these cases. 
To test # 1 above, see [artgc-optional-artifact-not-written.yaml](https://github.com/argoproj/argo-workflows/pull/13678/files#diff-425d1aaa0cb7f000f …
=> fix: all written artifacts should be saved and garbage collected

examples/artifact-repository-ref.yaml
This example doesn't have anything to do with artifactory.
=> chore(docs): fix artifact repository ref example name typo

ui/src/app/workflows/components/retry-workflow-node-panel.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Fixes #10139
Add the ability to manually retry a single step on workflows.
I based my changes on the retry workflow, but abstracting the `Node Field Selector` with the current selected node, less flexible but very user friendly.
See screenshots
=> feat(ui): Retry a single workflow step manually

ui/src/app/workflows/components/retry-workflow-node-panel.tsx
Attempting to build the UI on `main` currently fails with the following error:
```
ERROR in ./src/app/workflows/components/retry-workflow-node-panel.tsx 26:0-43
Module not found: Error: Can't resolve '../../shared/utils' in '/home/vscode/go/src/github.com/argoproj/argo-workflows/ui/src/app/workflows/components'
```
This is happening due to a merge conflict between https://github.com/argoproj/argo-workflows/pull/13343 and https://github.com/argoproj/argo-workflows/pull/13339. The latter was merged first and deleted `ui/src/app/shared/utils.ts`, which the former is importing. The reason the CI build didn't fail for the former PR is that the branch wasn't up-to-date with `main` at the time of merge.
Fixed `src/app/workflows/components/retry-workflow-node-panel.tsx` to use the new location of …
=> fix(ui): fix build failures due to conflict

go.mod, workflow/executor/os-specific/signal_windows.go, workflow/executor/os-specific/signal_windows_test.go
emissary tries to send a signal but `os/Process.Signal` only supports sending SIGKILL and returns an error for all other cases.
Using code found in hcsshim this changes signal handling in emissary for windows by translating SIGINT and SIGTERM to their appropriate windows signal and sending it to the process.
custom build of argoexec and tested on several windows workflows as well as manual testing on a windows machine.
=> fix(emissary): signal SIGINT/SIGTERM in windows correctly

cmd/workflow-controller/main.go, util/telemetry/exporter_prometheus.go, util/telemetry/exporter_prometheus_test.go, workflow/controller/controller.go
Partial fix for #10807 
While investigating the flaky `MetricsSuite/TestMetricsEndpoint` test, I noticed `listen tcp :9090: bind: address already in use` errors in the controller logs ([example](https://github.com/argoproj/argo-workflows/actions/runs/11221357877/job/31191811077)):
```
controller: time="2024-10-07T18:22:14.793Z" level=info msg="Starting dummy metrics server at localhost:9090/metrics"
server: time="2024-10-07T18:22:14.793Z" level=info msg="Creating event controller" asyncDispatch=false operationQueueSize=16 workerCount=4
server: time="2024-10-07T18:22:14.800Z" level=info msg="GRPC Server Max Message Size, MaxGRPCMessageSize, is set" GRPC_MESSAGE_SIZE=104857600
server: time="2024-10-07T18:22:14.800Z" level=info msg="Argo Server started successfully on http://localhost:2746" …
```
=> fix(controller): handle race when starting metrics server. Fixes #10807

docs/workflow-templates.md
This documentation on a deprecated feature refers to code that was removed in f31e0c6f92ec5e383d2f32f57a822a518cbbef86 / #5035 in February 2021.
It is no longer adding value to keep around, so remove it.
=> docs: delete deprecated & removed immediate template docs

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #13629
When the sync lock is not released, the latest lock-msg is always used as the node message
=> fix(controller): node message should be updated when lock msg changed

docs/environment-variables.md, workflow/controller/estimation/estimator_factory.go
Fixes https://github.com/argoproj/argo-workflows/issues/7271
co-authored by @talebzeghmi in https://github.com/zillow/argo-workflows/pull/1
=> feat: add `SKIP_WORKFLOW_DURATION_ESTIMATION` env var. Fixes #7271

hack/git/hooks/commit-msg
The Git hook that verifies the commit messages consistently fails in both the DevContainer and my Ubuntu 24 desktop if the commit title has a scope:
```
$ printf 'feat(sso): test\n\nSigned-off-by: test' > msg && ./hack/git/hooks/commit-msg msg
grep: warning: ? at start of expression
grep: warning: ? at start of expression
❌ Commit message must be semantic: https://github.com/zeke/semantic-pull-requests
$ grep --version
grep (GNU grep) 3.11
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Mike Haertel and others; see
<https://git.savannah.gnu.org/cgit/grep.git/tree/AUTHORS>.
grep …
```
=> build: fix commit-msg Git hook

ui/package.json, ui/src/app/shared/components/object-parser.test.ts, ui/src/app/shared/components/object-parser.ts, ui/yarn.lock
Fixes #12205
[js-yaml](https://www.npmjs.com/package/js-yaml) has had no releases in over 3 years. Also, the fact it only supports YAML 1.2 is leading to bugs, since Kubernetes uses YAML 1.1 (see https://github.com/kubernetes/kubernetes/issues/34146).
This switches over to [yaml](https://www.npmjs.com/package/yaml), which had a release last month, is [licensed under ISC](https://github.com/eemeli/yaml/blob/main/LICENSE), and supports YAML 1.1. I also added test cases for the parsing/stringifying code.
Copied the example from https://github.com/argoproj/argo-workflows/issues/12205 over to http://localhost:8080/workflow-templates and verified the `mode: 0755` was changed to `mode: 493`:
https://github.com/user-attachments/assets/54690403-4189-499a-a2c1-65293026ea77
=> fix(ui): switch from js-yaml to yaml. Fixes #12205

ui/src/app/shared/components/links.test.ts, ui/src/app/shared/components/links.tsx
Fixes #11741
You cannot create UI links to our own annotations or labels.
Argo Workflows uses the format `workflows.argoproj.io/something` for annotations and labels. These annotations and labels have dots (`.`) in them.
The [links](https://argo-workflows.readthedocs.io/en/stable/links/) documentation says you can access all workflow fields, using a dot to go down into the child entry.
These two conflict making it impossible to access our own labels and annotations, so fix it for annotations and labels.
This was discovered whilst adding an annotation to the workflows that was useful to link from in a separate feature.
When splitting the variable name up use a specialised splitting function that understands that things under `workflow.metadata.labels` and `workflow.metadata.annotations` …
=> fix(ui): allow `links` to metadata with dots. Fixes #11741

workflow/controller/agent.go
Fixes #13654 
When I use the HTTP template, I find it pending all the time. 
Then I saw that the workflow status was error, and encountered a transient error.
error is : `failed to create Agent pod. Reason: Operation cannot be fulfilled on resourcequotas "xxxx": the object has been modified; please apply your changes to the latest version and try again`
When the agent pod creation encounters transient errors, just retry.
=> fix(controller): retry transient error on agent pod creation

workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Fixes point 5 of https://github.com/argoproj/argo-workflows/issues/13089
`ARGO_PROGRESS_FILE` is only used when self reporting progress
=> fix: only set `ARGO_PROGRESS_FILE` when needed. Partial fix for #13089

hack/manifests/crdgen.sh, hack/manifests/crds.go, hack/manifests/main.go, manifests/base/crds/full/README.md, manifests/base/crds/minimal/README.md, manifests/base/crds/minimal/argoproj.io_workflowartifactgctasks.yaml, manifests/base/crds/minimal/argoproj.io_workfloweventbindings.yaml, manifests/base/crds/minimal/argoproj.io_workflowtaskresults.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
Fixes #12166. Partial fix for #8190
The CRDs under `manifests/base/crds/minimal/` are minimized as a workaround for https://github.com/kubernetes/kubernetes/issues/82292. However, `WorkflowEventBinding` and `WorkflowArtifactGCTask` are small enough that minimization isn't necessary. Including the full CRD enables users to use `kubectl explain` to explore the CRD definitions.
* Rename `removeCRDValidation()` to `minimizeCRD()` so it more accurately describes what it's doing and add comments
* Update `minimizeCRD()` to only minimize `cronworkflows.argoproj.io`, `clusterworkflowtemplates.argoproj.io`, `workflows.argoproj.io`, `workflowtemplates.argoproj.io`, `workflowtasksets.argoproj.io`, since the others are small enough they don't need to be minimized
* Add more details to …
=> build: don't minimize CRD for `WorkflowEventBinding` and `WorkflowArtifactGCTask`. Fixes #12166

docs/fields.md, docs/synchronization.md, examples/synchronization-mutex-tmpl-level-legacy.yaml, examples/synchronization-mutex-tmpl-level.yaml, examples/synchronization-mutex-wf-level-legacy.yaml, examples/synchronization-mutex-wf-level.yaml, examples/synchronization-tmpl-level-legacy.yaml, examples/synchronization-tmpl-level.yaml, examples/synchronization-wf-level-legacy.yaml, examples/synchronization-wf-level.yaml, mkdocs.yml
Addresses #13644, https://github.com/argoproj/argo-workflows/pull/13358#discussion_r1770585773 etc: <details>
> > Since people will look at the examples and not know that they have future syntax etc
> 
> Indeed it looks like this is happening almost as soon as this was merged 😕 #13644 plus [two](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1726994955560259) [Slack threads](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1726835793647219?thread_ts=1726835793.647219&cid=C01QW9QSSSK). The issue and former Slack thread are also from a [long](https://github.com/argoproj/argo-workflows/discussions?discussions_q=author%3Ani-todo-spot) [time](https://github.com/argoproj/argo-workflows/issues?q=author%3Ani-todo-spot) user, i.e. not a newbie.
And ofc [this contributor …
=> docs: in-line versioning + deprecation for multi-semaphore

docs/upgrading.md
#13735 and #13719 highlighted and made some deprecations we'd like to remove in a future release.
To aid in ensuring users notice this also add a brief note on them to the upgrading guide.
Links work:
=> docs: add deprecations to upgrading guide

docs/upgrading.md
Fixes #13541
Follow up to add upgrading notes to #12909 
#12909 is a breaking change and wasn't listed in the upgrading notes
Add upgrading notes for this change. The change is subtle and probably affects few users. Some may have worked around it as per #8930 and can optionally remove `toJson` from expressions, but this is not necessary.
`make docs` passes
=> docs: add 3.6 json templating upgrading notes

.gitignore, Makefile, docs/running-locally.md
When working on the DB locally, it's sometimes necessary to make backups, particularly when testing schema migrations (e.g. https://github.com/argoproj/argo-workflows/issues/13601). 
This is similar to https://github.com/argoproj/argo-workflows/pull/13715, and I thought about combining the two PRs, but I figured it's better to keep them separate, since they don't conflict with each other.
This adds two Make targets, `make mysql-dump` and `make postgres-dump`, to run `mysqldump` and `pg_dump`, respectively. I also simplified the existing `make mysql-cli` and `make postgres-cli` commands to use `kubectl exec svc/...` instead of manually grabbing the pod, since passing a service to `kubectl exec` will cause it to automatically select the first (and only) pod in the service.
Tested with both …
=> build: add `make` targets to dump the database

.github/workflows/ci-build.yaml
Partial fix for #10807
Occasionally, tests are being canceled due to exceeding the 30 minute timeout. Example: https://github.com/argoproj/argo-workflows/actions/runs/11358993638/job/31594490093
While there are optimizations we can make to the test suite to mitigate this, sometimes resource contention causes things to slow to a crawl for reasons outside our control. In the example above, it spent 9m15s on "Free up unused disk space", which normally takes ~12s. The only thing that step is doing is running `rm -rf`, so that indicates extremely high I/O contention on the runner.
This removes the timeout so it uses the default of 360 minutes ([docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes)). This is what ArgoCD does …
=> ci: increase timeout for e2e-tests

workflow/cron/operator.go, workflow/cron/operator_test.go
Fixes #13786 
If a CronWorkflow is tested for whether it should run within `startingDeadlineSeconds` it tests it in the wrong timezone.
This doesn't matter for hourly or minutely CWFs.
This doesn't matter if a CWF doesn't have a timezone associated with it.
This test happens on Informer relist, so if the relist occurs at the wrong time the CWF can be erroneously fired.
This was introduced in #12616 (see linked issue) in version 3.6.
The main change is to use `GetSchedulesWithTimezone()` rather than `GetSchedules()` when iterating over the schedules to check startingDeadlineSeconds.
The code was confusing (and confusing before #12616) in that it attempted to modify `timeNow()` to be in a local time. This was irrelevant and made spotting the bug harder. I have removed it. All `time.Time` …
=> fix(cron): correctly run when `startingDeadlineSeconds` and `timezone` are set

docs/walk-through/docker-in-docker-using-sidecars.md
Fixes https://github.com/argoproj/argo-workflows/discussions/13010#discussioncomment-9372559, https://github.com/argoproj/argo-workflows/pull/10778#issuecomment-2105499778
As users have mentioned, DIND does still work and the specific DIND image used comes with Docker Engine and so does not rely on the k8s container engine
- replace the `dockershim` note with one about "Alternatives", since DIND is still not as secure
- use a proper admonition for the note as well, instead of "Note:" with a horizontal rule after
- also follow docs style guide for the rest of the page while at it
- prefer 1 sentence per line, per [style guide](https://argo-workflows.readthedocs.io/en/release-3.5/doc-changes/)
- use active voice, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/# …
=> docs: remove incorrect statement about DIND not working

docs/upgrading.md, docs/workflow-archive.md
This adds documentation for the breaking changes in #13779 and #13761
=> docs: upgrading notes (postgres archive and `ARGO_TEMPLATE`)

workflow/controller/workflowpod.go
Per various GitHub issues and personal experience, the "expected < 2 pods, got 2 - this is a bug" error message mostly happens these days when users accidentally have multiple workflow controllers running. This is usually caused by a bad install, e.g. installing a cluster-wide Argo Workflows alongside a namespace-scoped one, and having both controllers reconciling Workflows.
Improve the error message to advise users to check for this.
I didn't verify this, since it's just a text change.
=> fix: better error message for multiple workflow controllers running

cmd/argo/commands/root.go, test/e2e/cli_test.go
Fixes #13826
https://github.com/argoproj/argo-workflows/pull/13656 changed all CLI commands to use `RunE` instead of `Run` and to use [Cobra validators](https://cobra.dev/#positional-and-custom-arguments) for validating arguments. The default behavior with Cobra is to print the help text for all errors, which can be tedious to scroll through.
This changes the CLI to only print the help text for argument validation errors, which should match the previous behavior.
```
$ ./dist/argo submit 'ANYexampleworkflow.yaml'
Error: open ANYexampleworkflow.yaml: no such file or directory
$ ./dist/argo submit --from workflow/basic 'ANYexampleworkflow.yaml'
Error: cannot combine --from with file arguments
Usage:
argo submit [FILE... | --from `kind/name] [flags]
<SNIP>
```
=> fix: don't print help for non-validation errors. Fixes #13826

ui/src/shared/components/editors/key-value-editor.tsx, ui/src/shared/components/graph/graph-panel.tsx
Fixes some React 18 warnings noted in https://github.com/argoproj/argo-workflows/pull/13069#issuecomment-2159579279:
```
react-dom.development.js:58 Warning: GraphPanel: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```
Future proofs some code that used deprecated `defaultProps` (and has warnings in React 18) by using JS default parameters instead
- `GraphPanel.defaultProps.nodeSize` -> `defaultNodeSize` const
- can't quite seamlessly use a default parameter here as it was also used as a constant in a few places
- `KeyValueEditor.defaultProps.keyValues: {}` -> `keyValues = {}` default parameter
=> refactor(ui): replace deprecated usage of `defaultProps`

docs/upgrading.md
This adds some additional details about the migration introduced in https://github.com/argoproj/argo-workflows/pull/13779, primarily to assist users with a very large number of archived workflows who may not be comfortable with extended downtime.
The manual minimal-downtime migration strategy is inspired by [Altering a Postgres Column with Minimal Downtime](https://making.lyst.com/2020/05/26/altering-a-postgres-column-with-minimal-downtime/).  I tested it locally after populating my local database with 100,000 rows using https://github.com/argoproj/argo-workflows/pull/13715:
```
$ time make postgres-cli < migrate_before.sql
GIT_COMMIT=f25960ac6f63bc3cf1a3b8a9813cf43c61921262 GIT_BRANCH=fix-migrate-jsonb GIT_TAG=untagged GIT_TREE_STATE=dirty RELEASE_TAG=false DEV_BRANCH=true VERSION=latest …
```
=> docs: additional details on jsonb migration for 3.6

docs/swagger.md
Fixes "Future Work" part 2 of https://github.com/argoproj/argo-workflows/pull/13818
As we have versioned docs now (#11390), the Swagger UI should reference the OpenAPI spec of its release, not `main`
In `swagger.md`, change the raw GH URL from `main` to `release-3.5`
- I also backported https://github.com/argoproj/argo-workflows/pull/12518#issuecomment-2439824378 to make this page equivalent to `main` before this change. (the spec was always pointing to `main` both before and after, for clarity)
1. `mkdocs build && open site/swagger/index.html`
1. Confirmed that it loads the Swagger UI properly and loads the `release-3.5` spec. <details><summary>Screenshot:</summary> ![Screenshot 2024-10-26 at 11 40 00 PM](https://github.com/user-attachments/assets/d455b66d-0391-418d-bf68-3ac8945a6acc) …
=> docs: 3.5 Swagger UI should reference 3.5 OpenAPI spec -- 3.5 specific

test/e2e/suspend_test.go
Every PR has been failing the `make lint` checked with the following error since https://github.com/argoproj/argo-workflows/pull/12960 was merged ([example](https://github.com/argoproj/argo-workflows/actions/runs/11636897786/job/32409181464)):
```
assert.Equal(t, 1, len(status.Outputs.Parameters))
^
Error: test/e2e/suspend_test.go:124:4: len: use assert.Len (testifylint)
assert.Equal(t, 1, len(status.Inputs.Parameters))
^
make: *** [Makefile:466: lint] Error 1
```
This is happening due to a conflict between that PR and https://github.com/argoproj/argo-workflows/pull/13467. The latter PR was merged on August 14th, but [the latest CI run for the former](https://github.com/argoproj/argo-workflows/actions/runs/9191558853/job/25278229097) was on May 22nd.
Change to use `assert.Len()`
Ran `make …
=> chore(tests): fix lint failures

ui/package.json, ui/src/workflows/components/workflow-node-info/workflow-node-info.tsx, ui/src/workflows/components/workflow-timeline/workflow-timeline.tsx, ui/yarn.lock
Partial fix for #12059, but removing / replacing a large dep entirely.
- **EDIT**: turns out it's still used by the old version of `chart.js` in the deps, so it instead got code-split into the `Reports` page bundle, see "Notes to Reviewers" below
Follow-up to #12097 
`moment` has been [deprecated since Sep 2020](https://momentjs.com/docs/#/-project-status/) and recommends using native `Intl` or newer libraries that make use of native `Intl`, such as `luxon` and `day.js`
- `moment` is also a very large dependency and hence is ripe for pruning and replacement as well
- shave off ~634KB / 260KB minified / 73KB gzipped from the main bundle by replacing ~15 LoC
- replace all usage of `moment` with regular `Date` functions
- `valueOf()` works the same way for `Date` and `moment`
- `diff` …
=> refactor(deps): remove `moment` dep and usage

util/cmd/glog.go, workflow/controller/agent.go, workflow/controller/artifact_gc.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Fixes #12788, Fixes https://github.com/argoproj/argo-workflows/pull/12929#discussion_r1572707894
- loglevel, gloglevel, and log format were inconsistently set around the codebase for executor containers
- meaning that some had partial settings and some had no settings, depending on the command run etc
- for all commands, including `emissary`, `agent`, `resource`, and `data`
- set loglevel, gloglevel, and log format
- replace `getExecutorLogLevel` helper with `getExecutorLogOpts` helper
- add a helper in `util/cmd/glog.go` to get the gloglevel
Existing tests pass
=> fix: consistently set executor log options 

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/cron-workflows.md, docs/fields.md, pkg/apis/workflow/v1alpha1/cron_workflow_types.go, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1CronWorkflowStatus.md, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_cron_workflow_status.py, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1CronWorkflowStatus.md
The documentation in several places refers to `stopStrategy.condition` but the property is actually `expression`.
A documentation correction.
I updated all references to `stopStrategy.condition` in docs (`md` and code) to be `stopStrategy.expression`, which is the correct prop.
=> docs: fix refs to `stopStrategy.expression`

ui/src/shared/components/object-parser.test.ts, ui/src/shared/components/object-parser.ts
Fixes #13892 
Currently the submit button for workflowtemplates is broken both in main and the new 3.6.0 release. The reason is that the UI thinks the content of the workflowtemplate has been updated in the editor, even when it has not.
The process looks like this:
We fetch the workflow from the backend and keep it as a javascript object, convert it to a yaml string, update the editor content with this string, and then when the editor content is updated we convert it back to a javascript object. We then compare to original object with the parsed object to determine if it has been updated or not. This requires parse and stringify to be inverses, but when we downgraded yaml version from 1.2 to 1.1 in https://github.com/argoproj/argo-workflows/pull/13750 we accidently broke this assumption, …
=> fix(ui): fix broken workflowtemplate submit button. Fixes #13892

server/workflow/workflow_server.go, workflow/controller/operator_test.go, workflow/util/util.go, workflow/util/util_test.go
Fixes #12543 and other retry related issues.
The current retry logic is too simplistic, it relies only on resetting nodes by traversing boundary nodes.
This approach does not work, it needs to be a combination of manual traversal and boundary node traversal.
In addition to this the current logic does not take care of various edge cases, for example container sets.
It was clear some rethinking needed to be done such that:
a) edge cases were taken care of.
b) retry logic was simpler to understand and hopefully fix if any further bug were to arise.
This is a complete rewrite of the `FormulateRetryWorkflow` function.
Extensive testing performed manually to verify that behaviour is as expected.
=> fix: correct retry logic

ui/src/shared/components/linkified-text.tsx
Since [this change](https://github.com/argoproj/argo-workflows/pull/13494/files), URLs are now clickable but splitted in columns which is not the desired behavior
I wrapped the `LinkifiedText` component with a simple span to leave the text on the same line
=> fix(ui): Clickable URLs are messing up formatting in the UI

test/e2e/hooks_test.go, workflow/common/util.go, workflow/common/util_test.go
Fixes #13890
Support for substituting variables in `configMapKeyRef` was added in https://github.com/argoproj/argo-workflows/pull/7542 by manually parsing templates out of the string, instead of using the standard `template.Replace()` function. Since the manual parsing logic uses the same syntax as [simple template tags](https://argo-workflows.readthedocs.io/en/latest/variables/#simple) (e.g. `{{workflow.parameters.cm-name}}`), users reasonably expect it to work the same, but it doesn't, which leads to confusion. Additionally, supporting templates like `{{workflow.parameters.cm-name}}-cm` is important, because that's a common pattern.
This replaces the manual parsing code with the standard `template.Replace()` function that everything else uses. 
Verified by running the example workflow …
=> fix: consistent variable substitution for `configMapKeyRef`. Fixes #13890

test/e2e/signals_test.go, util/errors/errors.go, util/errors/errors_test.go
Fixes #13881
There's many places that can call `IsTransientErr()` with nil, e.g. https://github.com/argoproj/argo-workflows/blob/2fd54884844bb76d760466027afa023c5bfd6b64/util/util.go#L39
This caused `IsTransientErr()` to log `Non-transient error: <nil>`. We shouldn't be generating logs in this case.
Don't log when the error is nil
This can be reproduced locally by running `make start PROFILE=mysql`. Before this change: 
```
$ head -n9 logs/controller.log
time="2024-11-19T05:55:16Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true                                                                                                                                                                                          
time="2024-11-19T05:55:16Z" level=info msg="cron config" …
```
=> fix: don't log non-errors as "Non-transient error: <nil>". Fixes #13881

mkdocs.yml
- `site_url` is required for [canonicalization](https://docs.readthedocs.io/en/stable/canonical-urls.html), which is a prereq for [proper styling on 404s](https://docs.readthedocs.io/en/stable/reference/404-not-found.html) and [creating a `sitemap.xml`](https://stackoverflow.com/a/59295885/3431180)
- Also for certain features like:
- [Instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=site+url#instant-loading)
- [Versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/?h=site+url#publishing-a-new-version) (we use RTD's versioning, but may want some features from here like the version drop-down)
- Add `site_url` config to `mkdocs.yml`
- use [RTD](https://docs.readthedocs.io/en/stable/canonical-urls.html#how-to-specify-the- …
=> build(docs): set `site_url` from ReadTheDocs env var

.github/workflows/ci-build.yaml, docs/releases.md
*  K8s 1.28 is EOL
* increases minimum k8s version in CI to 1.29
E2e tests will verify
=> ci: bump minimum k8s version to 1.29

ui/src/shared/use-editable-object.test.ts, ui/src/shared/use-editable-object.ts
https://github.com/argoproj/argo-workflows/pull/13915 introduced a regression where edits made in an object editor that introduce syntax errors cause a full screen error. 
This is happening because parsing was lifted out of `<ObjectEditor>` and into a reducer. Before https://github.com/argoproj/argo-workflows/pull/13915, the object editor used the following to catch parse errors: https://github.com/argoproj/argo-workflows/blob/eb4f2456e077d89324ea71ef5f5e92cdccd8157a/ui/src/shared/components/object-editor.tsx#L131-L136
After  https://github.com/argoproj/argo-workflows/pull/13915, the parsing logic was moved to `reducer()`, which is executed async, and therefore errors aren't propagated to the `catch (e) {}` block:
https://github.com/argoproj/argo-workflows/blob/1392ef516fd69a2cae875d746c11 …
=> fix(ui): handle parsing errors properly in object editor

.github/workflows/changelog.yaml, .github/workflows/ci-build.yaml, .github/workflows/dependabot-reviewer.yml, .github/workflows/docs.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml, .github/workflows/retest.yaml, .github/workflows/sdks.yaml, .github/workflows/snyk.yml, .github/workflows/stale.yaml
On December 5th, the `ubuntu-latest` runner will start pointing to Ubuntu 24: https://github.com/actions/runner-images/issues/10636
This updates all workflows to use Ubuntu 24 so we don't have any unexpected surprises.
`s/ubuntu-latest/ubuntu-24.04`
Wait for workflows to run
=> ci: pin workflows to Ubuntu 24

workflow/controller/operator.go, workflow/controller/taskresult.go
Fixes https://github.com/argoproj/argo-workflows/issues/13918
'node changed' 'node unchanged' and 'task-result changed' flood the logs when running argo in production with many workflows and parallel runs, move these log statements to debug logging so that we can filter them
Change logging for those three statements from Info to Debug
Run the tests. Log messages should be being logged as debug instead of info
=> feat: Move contextless log messages to debug logging - fixes #13918

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/executor_swagger.md, docs/fields.md, docs/http-template.md, docs/variables.md, docs/walk-through/output-parameters.md, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/plugins/executor/swagger.yml, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1Outputs.md, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_outputs.py, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1Outputs.md
HTTP templates set `output.result` to the response body, but this wasn't documented: https://github.com/argoproj/argo-workflows/blob/1f304ba6780ee043ea5ecd74e06787bcba298f8f/workflow/executor/agent.go#L260
This has confused users (e.g. https://github.com/argoproj/argo-workflows/discussions/13950#discussioncomment-11404302). Additionally, the API docs for `result` only mention script templates, but container templates also set it.
Update relevant docs  
Ran `make docs-serve`
=> docs: correctly document `result` output parameter

server/workflow/workflow_server.go, test/e2e/argo_server_test.go
Cherry pick of patch for https://github.com/argoproj/argo-workflows/security/advisories/GHSA-h36c-m3rf-34h9
=> fix(api): properly authorize GET workflow fallback to archive

workflow/util/util.go
Fixes #13970 
To address issue where a cron intiated create workflow could failed due network issue
Add retry to util.SubmitWorkflow
The `SubmitWorkflow` is used by `argo server.resubmit workflow` and `controller.cron operator`
The original issue was on cron operator, but having retry in the util function allows server to retry resubmit when there's an intermittent issue communicating with the controller, enabling a better user experience.
The code style is identical to how other transient patterns are written.
We currently don't have a process to force k8s network error, thus hard to write additional test.
We do have a test for transient utility and a successful e2e test is an indication that no issue has been introduced
=> fix: cronOperator/serverResubmitWf retry create workflow on transient error. Fixes #13970

.spelling, docs/title-and-description.md
The docs erroneously stated that markdown features for titles/descriptions on things other than Workflows were available in 3.6. This will be a 3.7 feature: https://github.com/argoproj/argo-workflows/pull/12697
=> docs: clarify which version markdown features are in

ui/src/cluster-workflow-templates/cluster-workflow-template-details.tsx, ui/src/shared/get_workflow_params.test.ts, ui/src/shared/get_workflow_params.ts, ui/src/shared/history.ts, ui/src/workflow-templates/workflow-template-details.tsx, ui/src/workflows/components/submit-workflow-panel.tsx, ui/src/workflows/components/workflow-creator.tsx, ui/src/workflows/components/workflows-list/workflows-list.tsx
Fixes #12124
This PR  adds support for developers to prefil submit workflow form by passing in the values through query parameters.
To prefil a submit workflow developers can pass in the following query parameters
```
sidePanel=submit-new-workflow
template=<template that the workflow should follow>
parameters[key]=value // Here the key would be the parameter for the job and value would be the value of the parameter.
You should provide the keys that are supported by the specified template
```
- Updated `workflow-list` component
- Updated `submit-workflow-panel.tsx` component to default entry point if provided.
- Updated `workflow-creator.tsx` to read default values from query parameters.
- The workflow will be prefilled with the parameters that the template supports
- Added new shared …
=> feat(ui): prefill parameters for workflow submit form. Fixes #12124

hack/release-notes.md
This is how I fixed bash script installing using cURL on my macbook.
=> docs: Fixed broken bash script when installing on macos

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #13951
Child node in containerSet stuck `Running` when using `dependencies`.
Mark all its children(container) as deleted if pod deleted.
Local and UT test.
=> fix: mark all its children(container) as deleted if pod deleted. Fixes #13951

ui/src/cron-workflows/cron-workflow-details.tsx, ui/src/cron-workflows/cron-workflow-list.tsx, ui/src/event-flow/event-flow-page.tsx, ui/src/event-sources/event-source-details.tsx, ui/src/event-sources/event-source-list.tsx, ui/src/plugins/plugin-list.tsx, ui/src/reports/reports.tsx, ui/src/sensors/sensor-details.tsx, ui/src/sensors/sensor-list.tsx, ui/src/widgets/workflow-graph.tsx, ui/src/widgets/workflow-status-badge.tsx, ui/src/workflow-event-bindings/workflow-event-bindings.tsx, ui/src/workflow-templates/workflow-template-details.tsx, ui/src/workflow-templates/workflow-template-list.tsx, ui/src/workflows/components/workflow-details/workflow-details.tsx, ui/src/workflows/components/workflows-list/workflows-list.tsx
Fixes #13940 
To resolve issue where user need to click backbutton twice to go back to previous page
useEffect always executes after page render, causing duplicate entry in history.
skip useEffect for initial page load
Clicking on UI make sure below issue doesn't occur
> After transitioning from the list to the detail screen, a browser back is required twice to return to the list.
> This can be observed not only in Workflow, but also in CronWorkflow, WorkflowTemplate, and ClusterWorkflowTemplate.
Check other UI parts perform as usual prior to the change
=> fix(ui): skip history.push on initial page load. Fixes #13940

Makefile
This makes some improvements to the `Makefile` to speed up local development and avoid a common race condition when building.
1. Remove `DOCKER_DESKTOP` because nothing uses it
2. Set `GOPATH` as a [simply expanded variable](https://www.gnu.org/software/make/manual/html_node/Simple-Assignment.html) so `go env GOPATH` isn't executed multiple times
3. Don't run the commands associated with the `ARGOEXEC_PKG_FILES`/`CLI_PKG_FILES`/`CONTROLLER_PKG_FILES` variables unless the target(s) needs them, because they're very slow. This speeds up `make` by ~1.5s for me. Before. 
```
$ time make check-pwd 
GIT_COMMIT=f796449df96888538af873bd6871374c2156db7b GIT_BRANCH=main GIT_TAG=untagged GIT_TREE_STATE=dirty RELEASE_TAG=false DEV_BRANCH=false VERSION=latest
KUBECTX=k3d-k3s-default …
```
=> build: optimize `Makefile` and fix infinite loop

.readthedocs.yml
Fixes an impending deprecation in readthedocs: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
I believe this may need to be cherrypicked to all branches that we produce docs for.
=> docs: explicitly reference mkdocs.yml in readthedocs config

test/e2e/argo_server_test.go, test/e2e/cron_test.go, test/e2e/fixtures/then.go, test/e2e/fixtures/when.go, test/e2e/functional_test.go, test/e2e/metrics_test.go, test/e2e/testdata/cronworkflow-deprecated-schedule.yaml, test/e2e/testdata/cronworkflow-metrics-forbid.yaml, test/e2e/testdata/cronworkflow-metrics-replace.yaml, test/e2e/testdata/cronworkflow_deprecated_schedule.yaml
Fixes #10807
The cron tests have been some of the slowest and flakiest for awhile now, mostly due to using `time.Sleep()` to wait a fixed amount of time. The `TestCronSuite` function tries to workaround the flakiness by running the suite at the 30 second mark, but this is only effective for the first test in the suite.
This changes nearly all the cron tests to remove the `time.Sleep()` calls and instead use the API to poll for changes. The two tests I couldn't fix to stop using `time.Sleep()` are `TestBasicForbid` and `TestCronCountersForbid`, since I don't know of any way of verifying the `concurrencyPolicy` is respected without sleeping.
Also, most of the cron fixture data wasn't specifying workflow metadata properly using [workflowMetadata](https://argo-workflows.readthedocs.io/en/lates …
=> test: fix and optimize flaky cron tests. Partial fix for #10807

util/expr/argoexpr/eval_test.go, workflow/controller/steps.go
Fixes #14031
The  error handling logic for `stepGroup` on `exithook` with illegal expressions should be consistent with `Dag`.
https://github.com/argoproj/argo-workflows/blob/27a59385f62de98b7bddc0087b03df90af29e87e/workflow/controller/dag.go#L289-L300
=> fix(controller): step group stuck on running when exit hook has illegal expression

.github/workflows/ci-build.yaml, .github/workflows/docs.yaml, Makefile
There's three sources of redundancy that are slowing down CI builds:
1. `make install` is being redundantly run three times for each E2E test:
1. In the workflow: https://github.com/argoproj/argo-workflows/blob/6699ab396f830210f6dcac4f00a9328a629c142f/.github/workflows/ci-build.yaml#L349-L350
2. As a prerequisite of `make start`: https://github.com/argoproj/argo-workflows/blob/6699ab396f830210f6dcac4f00a9328a629c142f/Makefile#L547
3. As a dependency by Kit: https://github.com/argoproj/argo-workflows/blob/6699ab396f830210f6dcac4f00a9328a629c142f/tasks.yaml#L39
2.  Similarly, the changes in https://github.com/argoproj/argo-workflows/pull/14012 to centralize binary building aren't actually preventing the binaries from being rebuilt in the E2E tests because `controller` and `cli` are …
=> ci: improve performance by eliminating redundancies

cmd/argoexec/commands/resource.go, cmd/argoexec/commands/wait.go, test/e2e/artifacts_test.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
Archive logs in resource template helps to better observe the life cycle status of the resource.
wait container log
```
time="2024-12-15T09:03:13.109Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: resource-tmpl-wf/resource-tmpl-wf-wf1-2914235474/main.log"
time="2024-12-15T09:03:13.110Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2024-12-15T09:03:13.110Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=resource-tmpl-wf/resource-tmpl-wf-wf1-2914235474/main.log path=/tmp/argo/outputs/logs/main.log
time="2024-12-15T09:03:13.130Z" level=info msg="Save artifact" artifactName=main-logs duration=20.227167ms error="<nil>" key=resource-tmpl-wf/resource-tmpl-wf-wf1-2914235474/main.log …
```
=> feat: support archive logs in resource template. Fixes:#9900

ui/src/workflows/components/workflow-artifacts.tsx, ui/src/workflows/components/workflow-details/workflow-details.scss, ui/src/workflows/components/workflow-node-info/workflow-node-info.scss, ui/src/workflows/components/workflow-node-info/workflow-node-info.tsx
Fixes #8306
From original [issue](https://github.com/argoproj/argo-workflows/issues/8306)
> It takes time to read and understand artifact info now, especially on first columns whose values that may merge with each other.
(https://github.com/argoproj/argo-workflows/issues/8306)
Refactored workflow-details artifacts white-box to include table columns and expand a cell with text too long for it's cell on hover.
Added same functionality to workflow-node-info -> inputs/outputs
=> refactor(ui):  artifacts table Fixes #8306

ui/src/shared/components/editors/key-value-editor.scss, ui/src/shared/components/editors/key-value-editor.tsx, ui/src/shared/components/editors/labels-and-annotations-editor.tsx, ui/src/shared/components/editors/workflow-parameters-editor.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/13934
Our organization allows non-developers to submit workflows using Argo Workflows.
However, since non-developers only submit WorkflowTemplate, etc., we need to have them read the Workflow description from the UI.
For this reason, we adopted markdown, which is easier to read.
If the KeyValueEditor key is `workflows.argoproj.io/title` or `workflows.argoproj.io/description`, it is now expressed in markdown.
On the Metadata tab below, we have verified that the Title and Description are marked down.
Also verified that all other fields have not changed.
```yaml
labels:
workflows.argoproj.io/title: Test-Title
workflows.argoproj.io/description: This-is-a-simple-hello-world-example
annotations:
workflows.argoproj.io/title: '**Test …
```
=> feat: Allow markdown title and description in KeyValueEditor

persist/sqldb/workflow_archive.go, test/e2e/argo_server_test.go
Unfortunately postgres does not handle NULL bytes in the json, this is as a result of a non-compliant implementation of JSON that exists in postgres. See  more details about this limitation [here](https://github.com/argoproj/argo-workflows/issues/13711#issuecomment-2507193576). 
This attempts a search and replace in postgres, it does this by reserving a special phrase for replacement of null bytes. 
On the `GetWorkflows` path, this special phrase is replaced with a null byte.
This has tests and additionally been verified by checking postgres.
=> fix: search and replace null bytes for postgres only.Fixes #13711

workflow/validate/validate.go, workflow/validate/validate_test.go
Fixes #14042 #13773
if nested template has reference, input tmpl args 
unit test
=> fix(controller): validation failed when dynamic templateRef is used in nested template

workflow/validate/validate.go, workflow/validate/validate_test.go
Fixes #13763
Validate template even if they use the same name (happened in nested template situation).
So that all templates are validated and cached in `storedTemplate` upon workflow submission
Include templateScope in validation cache,
so that the validation is aware which `workflowTemplate` is the current `template` coming from, and `template` of the same name from different `workflowTemplate` will not skip validation
Added unit test, test failed
Added code change, unit test passed
=> fix: validate template of the same name. Fixes #13763

ui/src/cron-workflows/cron-workflow-editor.tsx, ui/src/shared/components/editors/graph-viewer.tsx, ui/src/shared/models/workflows.ts, ui/src/workflow-templates/workflow-template-editor.tsx, ui/src/workflows/components/workflow-editor.tsx
Fixes #8646 
Stumbled across the open [issue](https://github.com/argoproj/argo-workflows/issues/8646) while developing a complex workflow, thought I might as well give it a go myself.
First time doing any front-end development.
Added a "graph view" tab to all workflow/template creation/submission pages to visualize the workflow as a graph before submission.
- Preview graph from submit-new-workflow
- Preview graph from submit-new-workflow using workflowTemplateRef
- Preview graph from workflow-templates:
- Preview graph from cluster-workflow-templates:
- Preview graph from cron-workflow:
Ran all workflows/workflow-templates under ui/test/ui/ and visually compared the predicted graph view to the resultant output.
- Preview vs Run, Steps example:
- Preview vs Run, Dag example:
- Preview vs …
=> feat: Fixes #8646 visualize wf before submitting

.github/dependabot.yml, .github/workflows/ci-build.yaml, .github/workflows/docs.yaml
Fixes #12455
See also @agilgur5's commentary from #13027
The github actions `upload-artifact` and `download-artifact` are [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)  and will presumably stop working completely on the 30th of January 2025.
Update all uses of both actions to the latest releases by SHA, matching those introduced in #14012.
Remove the dependabot ignore for these actions so they get dependabot maintained.
This is a "github only" change so CI for this PR and future working or failing are the only mechanisms to check it works.
This PR fixes the warning we were getting - see this run for the PR: https://github.com/argoproj/argo-workflows/actions/runs/12706995546?pr=14070 
Compare to a prior run: …
=> fix: update upload-artifact and download-artifact

.github/workflows/ci-build.yaml, Makefile
As requested in https://github.com/argoproj/argo-workflows/pull/14044#discussion_r1917576753, this adds a simple step to each E2E suite that validates the release manifests using server-side field validation. This is very fast (~2s) and is intended to catch syntactic issues, e.g. bugs in `hack/manifests/crds.go`.
Add `make manifests-validate` that runs [kubectl apply](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_apply/) with `--dry-run=server` to validate the manifests without actually applying them.
Edited `manifests/quick-start-minimal.yaml` and changed this line: https://github.com/argoproj/argo-workflows/blob/b1a65e79fe583134117c33814b54dcaba40c4238/manifests/quick-start-minimal.yaml#L23
to `type: TYPO`, then ran `make manifests-validate` to ensure it correctly …
=> ci: add step to validate release manifests

go.mod, workflow/common/util.go
=> chore: remove leftover code

examples/map-reduce.yaml
Added trailing slash after parts artifact path to treat it as a folder. Fixes artifactGC leaving it behind.
Fixes #14091 
Parts folder remains dangling in S3 after garbage collection.
Added a trailing slash to the parts artifact path to signal that it's a folder.
I have ran the modified workflow and observed that `parts` was visualized as a folder (with listed contents) in the UI and it was properly garbage collected after the workflow is deleted.
=> fix(examples): map-reduce parts artifact path. Fixes #14091

docs/workflow-pod-security-context.md
A note regarding volumes being required for `runAsNonRoot` took me down an incorrect path before I saw that was unnecessary in newer versions. I'm hoping this will save other developers a couple of hours of going down the same path.
Based on the PR discussion, I removed the note since v3.3 is no longer supported.
=> docs: Pod Security Context: Volumes aren't required in >= v3.3 and runAsNonRoot

docs/metrics.md, util/telemetry/builder/docs.go
Fix the table display issue in [metrics.md](https://argo-workflows.readthedocs.io/en/latest/metrics/)
=> docs: fix the table display issue in metrics.md

.github/workflows/ci-build.yaml, docs/releases.md
Verifying the test suite passes on the new K8s release
Changes CI to run against K8s 1.32
E2E tests will suffice
=> ci: test k8s version 1.32

.github/pull_request_template.md
In response to https://github.com/argoproj/argo-workflows/pull/14077#issuecomment-2599000634
I'd like to ensure that documentation is considered for each PR made.
Added a documentation section to the PR template to encourage people to consider it, document if they feel it's unnecessary, and always document `feat` PRs
None, this is a github PR template update
This is self documenting
=> feat: add documentation section to PR template

test/e2e/testdata/cronworkflow-deprecated-schedule.yaml, util/telemetry/instrument.go, util/telemetry/metrics.go, util/telemetry/operators.go, workflow/metrics/counter_log.go, workflow/metrics/gauge_pod_phase.go, workflow/metrics/gauge_workflow_condition.go, workflow/metrics/gauge_workflow_phase.go, workflow/metrics/leader.go, workflow/metrics/metrics.go, workflow/metrics/metrics_custom.go, workflow/metrics/metrics_test.go, workflow/metrics/work_queue.go
Fixes #14076
Also fixes my own bad test case (deprecated schedule test)
The golang map in the userdata for custom metrics was accessed under some circumstances from multiple go routines without an appropriate mutex - as can be seen from the stack trace and panic in #14076
Make the three maps which can be accessed have their own semaphore, instead of attempting to use the single top level one.
Make accessor functions for accessing `instruments` from util/telemetry/metrics so that locks there can be easily reasoned about. (Renamed from `AllInstruments`).
Make a separate lock for `realtimeWorkflows` from util/metrics/metrics and manually implement that.
Make a lock for custom_metric UserData, because that is needed in limited scenarios. Don't lock when this is accessed from test framework …
=> fix: locking in metrics

workflow/controller/operator.go
Fixes #14148
wait container updated progress, and the controller has detected the change in task result, but it was overridden by syncManager's `wfUpdate`.
=> fix(controller): task progress with mutexes not updated. Fixes #14148

.devcontainer/pre-build.sh
When rebuilding the dev container, I'm getting the following:
```
Running the postCreateCommand from devcontainer.json...
[12542 ms] Start: Run in container: /bin/sh -c .devcontainer/pre-build.sh
<SNIP>
+ make kit
GIT_COMMIT=a776b4583972625541a358b3c9a2e1fdc0925763 GIT_BRANCH=main GIT_TAG=untagged GIT_TREE_STATE=dirty RELEASE_TAG=false DEV_BRANCH=false VERSION=latest
KUBECTX=k3d-k3s-default K3D=true DOCKER_PUSH=false TARGET_PLATFORM=linux/amd64
RUN_MODE=local PROFILE=minimal AUTH_MODE=hybrid SECURE=false  STATIC_FILES=true ALWAYS_OFFLOAD_NODE_STATUS=false UPPERIO_DB_DEBUG=0 LOG_LEVEL=debug NAMESPACED=true
go install github.com/kitproj/kit@v0.1.79
go: go: could not create module cache: mkdir /home/vscode/go/pkg: permission denied
make: *** [Makefile:535: kit] Error 1
[21801 ms] …
```
=> build: fix `mkdir /home/vscode/go/pkg: permission denied`

.github/workflows/release.yaml
Fixes #14169
Our github actions/cache version is deprecated and will stop working from March 1st, 2025.
More details here: https://github.com/actions/cache/discussions/1510
- Upgraded the actions/cache to v4.2.0 by pinning the SHA https://github.com/actions/cache/commit/1bd1e32a3bdc45362d1e726936510720a7c30a57
=> chore: upgrade actions/cache to v4.2.0 (Fixes #14169)

.github/workflows/ci-build.yaml, .github/workflows/docs.yaml, docs/CONTRIBUTING.md, docs/releasing.md
Partial revert of #14151
Fixes [/test command not showing in github checks](https://github.com/argoproj/argo-workflows/pull/14151#issuecomment-2643256922) and [extra CI jobs running](https://github.com/argoproj/argo-workflows/pull/14151#issuecomment-2644729397)
The `/test` command isn't as important as the rest of #14151, so just remove it for now as it doesn't work as well as hoped and has issues
Remove `issue_comment` from the actions and associated `if`
Untested as github action code, and changes are a revert.
Reverted documentation for releasing process to use the old manual push, and removed docs on `/test`
=> fix: remove `/test` command comment

util/telemetry/builder/values.yaml, util/telemetry/metrics_list.go
Fixes `pod_total_count` metric
In  #13943 this metric was incorrectly made an ObservableGauge and is broken by this change
Just update the type to be correct so it works again
Observed it counting pods again.
It would be good if this was tested, but it never has been.
None required.
=> fix: correct type of pods_total_count metric

sdks/python/Makefile
Fixes #14159
SDK releases are failing since 3.6.3 and 3.5.14
See https://github.com/pypa/twine/issues/1216 - the suggestions there are either to upgrade packaging or fiddle with setuptools.
Python SDK is deprecated so this code should end up being removed soon.
I cannot reproduce the problem locally in devcontainer, so this is a speculative fix.
None needed.
=> fix(ci): python sdk release process (release-3.6)

.github/workflows/release.yaml
Manually cherry-picked.
Cherry-picked chore: upgrade actions/cache to v4.2.0 (Fixes https://github.com/argoproj/argo-workflows/issues/14169) (https://github.com/argoproj/argo-workflows/pull/14170)
=> chore: upgrade actions/cache to v4.2.0 (Fixes #14169) (#14170)

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go
No known bug reports around this so far
Whilst looking at deprecating single semaphores completely I discovered `getSemaphoreConfigMapRef()` was not multiple semaphore aware.
Rename `getSemaphoreConfigMapRef` to `getSemaphoreConfigMapRefs` and return a list of pointers instead of a pointer.
Make the caller of this iterate the list.
Updated the test case that tests `GetSemaphoreKeys` which is the only user of `getSemaphoreConfigMapRefs` to test this and added an extra entry to be sure it can successfully manage a list.
Not relevant, internal code
=> fix: correct semaphore configmap keys for multiple semaphores

go.mod, go.sum
We deploy Argo Workflows to isolated environments which needs support to pull from corresponding isolated s3 buckets. I have added the corresponding changes to [minio-go](https://github.com/minio/minio-go/pull/2053) to include support for the isolated environments & the release [v7.0.85](https://github.com/minio/minio-go/releases/tag/v7.0.85) have it available.
Bumped minio-go to v7.0.85 in the go.mod
Ran go mod tidy
I pushed the argoexec image with this change into my local kind cluster and able to pull s3 artifacts.
=> chore(deps): bump minio-go to newer version

workflow/util/util.go, workflow/util/util_test.go
Fixes #14180
N/A
This change now correctly types the items entered into the list. 
Verified with a regression test  and additionally manually tested. 
Manual resets on an exit node resets the entire.
=> fix: manual retries exit handler cleanup. Fixes #14180

workflow/artifacts/gcs/gcs.go
Fixes #2841 
Currently if our gcs has the following structure.
```
/test/abc
/test/abcd
```
specifying `key: /test/abc` in input artifact would cause failure due current list funciton will return 
```
/test/abc
/test/abcd
```
The list function should only return `/test/abc`
If the iterator returns a object that matches with our prefix, this indicate the object is a file instead of a directory, we return the file straightaway
- in gcs iterator, a directory will have suffix `/`, it won't match with the cleaned prefix
- in gcs, we can't have a file and a directory with the same name, we won't skip directory if its indeed a directory
Tested with
```
metadata:
name: test
namespace: default
spec:
templates:
- name: artifact-example
steps:
- - name: generate-artifact
template: …
```
=> fix: gcs fix list a file. Fixes #2841

docs/scaling.md, docs/workflow-controller-configmap.yaml
In both the example configmap and the docs, the `resourceRateLimit` `burst` was set to a value lower than the `limit`.  Even worse, it was set to `1`. This means that the `limit` would be perpetually in place even when not needed.
- Update the docs to explain burst a little clearer. Update the example
- Update the example controller configmap to match the docs.
- Added a missing line break
`make docs`
=> docs: Correct sub-optimal burst value for resourceRateLimit

ui/src/cron-workflows/cron-workflow-editor.tsx, ui/src/cron-workflows/cron-workflow-row.tsx, ui/src/cron-workflows/cron-workflow-spec-editor.tsx, ui/src/cron-workflows/cron-workflow-status-viewer.tsx, ui/src/shared/examples.ts, ui/src/shared/models/cron-workflows.ts, ui/src/shared/services/cron-workflow-service.test.ts, ui/src/shared/services/cron-workflow-service.ts
Fixes #14047 and fixes #14009
If you have a `CronWorkflow` that's missing both `schedules` and `schedule`, or has `schedules` set to an empty array, you'll get an error in the UI when visiting `/cron-workflows`. This appears to have been introduced in https://github.com/argoproj/argo-workflows/pull/12616. You could argue this isn't a bug, since such `CronWorkflows` aren't valid, but multiple users have reported this, so we should gracefully handle it.
This updates the UI code that fetches `CronWorkflow`s from the API to normalize the response with a new `normalizeSchedules()` function that sets `schedules` to an empty array if it isn't present and automatically converts `schedule` to `schedules`: https://github.com/argoproj/argo-workflows/blob/8461afb4b276511ad88eeaa93e0d2c688ae07d04/ui/sr …
=> fix: gracefully handle invalid CronWorkflows and simplify logic. Fixes #14047

test/e2e/cron_test.go
Occasionally, the cron E2E suite fails and you'll see the following in the output ([example](
https://github.com/argoproj/argo-workflows/actions/runs/13480065787/job/37664515754?pr=13747)):
>  ◷ test-cron-wf-fail-1-1740291060 Workflow 0s      Workflow processing has been postponed because too many workflows are already running
I think this is happening because the `E2ESuite.DeleteResources()` method that's supposed to clean up `CronWorkflow`s from previous tests isn't being run for subtests, and nearly all the tests in `test/e2e/cron_test.go` are subtests. 
This adds a `TearDownSubTest` method to cleanup all resources after every subtest. Docs:
https://pkg.go.dev/github.com/stretchr/testify/suite#TearDownSubTest
I also deleted the redundant `BeforeTest()` and `TearDownSuite()` methods. …
=> test: fix intermittent cron failures due to parallelism limit

USERS.md, api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/fields.md, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1Parameter.md, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_parameter.py, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1Parameter.md, ui/src/shared/models/workflows.ts
The current description of the `value` field on `Workflow.Parameter` is confusing and suggests that parameters passed to the workflow will not be respected if a value has been set in the workflow definition.
The actual behavior is opposite: The specified value acts as a default and is overridden by any passed values.
- Updated the description to match the actual behavior
- Added *Deutsche Telekom AG* to the list of users
Ran `make pre-commit -B`.
=> fix: incorrect description of value field in Workflow.Parameter

api/jsonschema/schema.json, hack/api/jsonschema/main.go
The current value of `$schema` in `api/jsonschema/schema.json` refers to a schema version that changes over time, which means that there's a possibility that the keywords used in the schema might change meaning unexpectedly when a new version is released.
This PR fixes the schema version to the current latest version, avoiding this potential issue by locking in the expected JSON Schema semantics and meaning that any would-be interpreter does not have to make a network request to find out what version is intended.
I checked that the new schema validates OK in a JSON schema checker.
A passing remark with regard to this comment in `hack/api/jsonschema/main.go`:
```
"$id":     "http://workflows.argoproj.io/workflows.json", // don't really know what this should be
```
It seems relatively …
=> fix(api/jsonschema): use unchanging JSON Schema version

.devcontainer/pre-build.sh, .github/workflows/ci-build.yaml, .spelling, Makefile, docs/releases.md, docs/tested-kubernetes-versions.md, hack/docs/tested-versions.sh, hack/k8s-versions.sh, mkdocs.yml
Signed-off-by: Mason Malone <651224+MasonM@users.noreply.github.com>
(cherry picked from commit f5d59e9a69460196545652f89b351ee60107db0e)
=> docs: autogenerate tested k8s versions and centralize config (#14176) (release-3.6)

server/clusterworkflowtemplate/cluster_workflow_template_server_test.go, server/cronworkflow/cron_workflow_server_test.go, server/workflow/workflow_server_test.go, server/workflowtemplate/workflow_template_server_test.go, workflow/creator/creator.go
Fixes #14121
make actor email label consistent, align with creator email label
`UserActionLabel` function in `workflow/creator/creator.go` is missing Email specific string modification
This function is used in patchShutdownStrategy
Added unit test -> test failed
Added code change -> test succeeded
=> fix(server): consistent actor email label. Fixes #14121

Makefile, docs/tested-kubernetes-versions.md
Fixes kubernetes versions in documentation- this doesn't work as hoped from #14176
Docs get rebuilt on every push to a branch, so `RELEASE_TAG` isn't usable
Use the `GIT_BRANCH` variable and check we're on an appropriate branch
`make docs`
Not needed
=> docs: fix kubernetes versions (release-3.6)

Makefile
Fixes kubernetes versions in documentation - this doesn't work as hoped from #14176 
Docs get rebuilt on every push to a branch, so `RELEASE_TAG` isn't usable
Use the `GIT_BRANCH` variable and check we're on an appropriate branch
`make docs`
Not needed
=> docs: fix kubernetes versions

docs/walk-through/scripts-and-results.md, docs/workflow-concepts.md
People lean into `script` templates for their automatic output capabilities, which `container` templates also offer. Wanted to make this more clear in the docs.
`make docs`
=> docs: clarify that container templates have an automatic result output

cmd/argo/commands/cron/backfill.go, cmd/argo/commands/cron/root.go, docs/cli/argo_cron.md, docs/cli/argo_cron_backfill.md, mkdocs.yml, test/e2e/cli_test.go, test/e2e/cron/cron-backfill-template.yaml, test/e2e/cron/cron-daily-job.yaml, test/e2e/fixtures/e2e_suite.go, workflow/common/common.go, workflow/util/pod_name.go, workflow/util/workflow_name.go
Base #4212
Airflow is easy to backfill. Simplify the use of backfill on Argo.
Support：
```
Provide CLI like argo corn backfill <cronworkflow name> --name <backfill name> --start <startdate> --end <enddate>
```
Part of #2706
```
U-4YKHFNR6-2229 cron-backfill % ./argo cron backfill daily-job --start "Wed, 21 Oct 2024 15:28:00 GMT" --end "Wed, 28 Oct 2024 15:28:00 GMT" --argname data --parallel true
Created 28816 Backfill task for Cronworkflow daily-job
==================================================
Backfill Period :
Start Time : Wed, 21 Oct 2024 15:28:00 GMT
End Time : Wed, 28 Oct 2024 15:28:00 GMT
Total Backfill Schedule: 7
==================================================
Backfill Workflows:
NAMESPACE	 WORKFLOW:
1. argo 	 backfill-wf-jhmpr
tianshuangkun@U-4YKHFNR6-2229 cron-backfill …
```
=> feat(CLI-alpha): support backfill for cron workflow. Part of #2706

workflow/sync/sync_manager.go
This resolves a fatal "concurrent map iteration and map write" error by synchronizing reads and writes to syncLockMap with a read-write mutex. This change has been running in our environment for 7 days (8,764 workflows) without reoccurrence.
Fixes #14300
To stop fatal panics when reading and writing to the `syncLockMap` map at the same time.
- Added a read lock in the `CheckWorkflowExistence` function.
- Replaced the exclusive lock with a read-write mutex.
- For functions that only read syncLockMap, a read lock is used to allow concurrent reads safely.
- Built the Argo Workflows controller image with `make workflow-controller-image`.
- Pushed it to our Artifactory container registry.
- Deployed in a non-production cluster (running production-like workloads in “shadow mode”).
- Monitored …
=> fix(workflow/sync): use RWMutex to prevent concurrent map access

.github/workflows/ci-build.yaml, Makefile, docs/requirements.txt
Fixes the problem found in https://github.com/argoproj/argo-workflows/pull/14302#issuecomment-2742883052
Whilst adding another tool not mentioned in this commit I thought this looked like a better pattern for tool management.
Create a makefile variable for all the tool binaries and use them everywhere.
This will force use some tools which were previously discovered by path to be the actual versions we installed, which might help in some cases.
Install `mkdocs` into a venv to fix the regression introduced in #14302 
Added some dependencies which were missed when doing #13623
`clang-format` is still used from the path, because the rule to install it allows this and I didn't feel like investigating this behaviour right now.
The paths for the node tools were not correct, so corrected them.
I …
=> refactor: tidy tools in makefile

server/workflow/workflow_server.go, server/workflow/workflow_server_test.go, server/workflowarchive/archived_workflow_server.go
Fixes https://github.com/argoproj/argo-workflows/issues/14348
workflow missed `workflows.argoproj.io/creator` label when submitted by resubmit button in Argo UI workflows page or archived workflows page
add `workflows.argoproj.io/creator` label when submit workflow by resubmit button in Argo UI workflows page or archived workflows page
when submit the workflow, you get use kubectl get wf xxx -oyaml to see the `workflows.argoproj.io/creator` label
=> fix: add creator label when submit workflow by the resubmit button in argo UI

docs/events.md, docs/fields.md, examples/workflow-event-binding/github-path-filter-workfloweventbinding.yaml, examples/workflow-event-binding/github-path-filter-workflowtemplate.yaml
I spent quite bit of time trying to figure out what syntax was allowed in the `.spec.event.selector` field so that I could [do complex logic with the selector](https://blog.isaacinit.com/Argo/How-To-Trigger-Argo-Workflows-Based-off-Files-Changed). The word `selector` only appears a couple times in the docs and doesn't lead the reader to discovering the expr-lang syntax.
Adding this clause will make it easier for other readers to discover what I was looking for.
Updated docs.
Read the docs 🙃 
This is a docs update.
=> docs: Add clarity to events.md that the .spec.event.selector field is in expr syntax

server/workflow/store/sqlite_store_test.go
Fixes #14346
`make test` fails as below:
```
--- FAIL: TestStoreOperation (0.00s)
--- PASS: TestStoreOperation/TestAddWorkflow (0.00s)
--- PASS: TestStoreOperation/TestUpdateWorkflow (0.00s)
--- PASS: TestStoreOperation/TestDeleteWorkflow (0.00s)
--- PASS: TestStoreOperation/TestListWorkflows (0.00s)
--- PASS: TestStoreOperation/TestListWorkflows_name (0.00s)
--- PASS: TestStoreOperation/TestListWorkflows_namePrefix (0.00s)
--- PASS: TestStoreOperation/TestListWorkflows_namePattern (0.00s)
--- PASS: TestStoreOperation/TestListWorkflows_finishedBefore (0.00s)
--- FAIL: TestStoreOperation/TestListWorkflows_createdAfter (0.00s)
```
Local TimeZone: CST
`TestListWorkflows createdAfter` list workflows with query:
```SQL
select workflow from argo_workflows
where instanceid = ?
and namespace = ? …
```
=> fix(test): change `createdAfter` to UTC time. Fixes #14346

workflow/controller/controller.go
Fixes #14367
Controller metrics crashes with Nil pointer dereference when metrics server fails to start. This makes it difficult to debug why the metrics server failed because the error message is never reported.
Check error before referencing the metric object.
N/A
N/A
N/A
=> fix: check metric creation before use. Fixes #14367

persist/sqldb/offload_node_status_repo.go
Fixes #14344
When offloading a workflow, it's possible for multiple workers to concurrently call `Save()` with the same workflow, which leads to `ERROR: duplicate key value violates unique constraint "argo_workflows_pkey"` messages in the logs, along with a stack trace.
These messages are cluttering the logs and confusing users. Duplicate key errors are harmless: `Save()` detects them automatically and will return the `version` hash. Since `version` is part of the primary key of the `argo_workflows` table, that means it's guaranteed to be identical to the previously-inserted row.
This decreases the log level of that message to `DEBUG` so that it doesn't clutter the logs. I thought about removing it entirely, but I figured it's worth keeping just in case there's an edge case we need to …
=> fix: silence noisy "Ignoring duplicate key error" messages. Fixes #14344

workflow/controller/controller.go
Fixes #14335 
- The code change is same as [executor configmap retry](https://github.com/argoproj/argo-workflows/blob/main/workflow/executor/executor.go#L708-L712)
- We don't see the error reoccur in our production env after deploy the change
=> fix: semaphore configmap retry on transient error. Fixes #14335

test/e2e/functional/parameter-aggregation-dag-with-retry.yaml, test/e2e/functional_test.go, workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/controller/operator.go
Fixes #14228
Fail to process aggregate outputs for nodes with retries.
1. Support aggregating outputs for nodes of `Retry` type(excluding their children).
2. Support extracting the index of child node if its name has extra brackets.
local test and e2e test
=> fix: process aggregate outputs for nodes with retries. Fixes #14228

ui/src/cron-workflows/cron-workflow-editor.tsx, ui/src/cron-workflows/cron-workflow-list.tsx, ui/src/cron-workflows/cron-workflow-spec-editor.tsx, ui/src/cron-workflows/cron-workflow-status-viewer.tsx, ui/src/shared/examples.ts, ui/src/shared/models/cron-workflows.ts, ui/src/shared/services/cron-workflow-service.test.ts, ui/src/shared/services/cron-workflow-service.ts
This manually cherry-picks https://github.com/argoproj/argo-workflows/pull/14197 onto `release-3.6`, as requested in https://github.com/argoproj/argo-workflows/pull/14197#issuecomment-2820768062.
Ran ` git cherry-pick -s e9e7c4398c00621f697acf0002b7992028958daa`. I had to resolve a conflict in `ui/src/cron-workflows/cron-workflow-row.tsx` because that file doesn't exist in the release branch, since it was added in db6206a22271259c66344f7bcf77de551bf777de by extracting code from `ui/src/cron-workflows/cron-workflow-list.tsx`.
Same testing procedure as https://github.com/argoproj/argo-workflows/pull/14197:
N/A
=> fix: gracefully handle invalid CronWorkflows and simplify logic.  (cherry-pick #14197)

go.mod, go.sum, server/event/dispatch/operation_test.go
Update expr to 1.17.0 the go_modules group (#14307)
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Tianchu Zhao <evantczhao@gmail.com>
(cherry picked from commit 9b7c0c4c4ce1ecb8e1d27df95d14ccef09cffe0f)
=> chore(deps): bump github.com/expr-lang/expr from 1.16.9 to 1.17.0 (#14307) (release-3.6)

workflow/util/util.go
Fixes #14124
In certain scenarios, manual retries do not work properly.
- Retry all failed execution nodes
- Reset all group nodes and non-boundary parent nodes if needed
- Do not retry nodes which their descendant nodes are `Succeeded`
Case 1:
```YAML
kind: Workflow
metadata:
generateName: http-template-
spec:
arguments:
parameters:
- name: url
value: "https://raw.githubusercontent.com/argoproj/argo-workflows/thisisnotahash/pkg/apis/workflow/v1alpha1/generated.swagger.json"
templates:
- name: main
steps:
- - name: fail1
template: http
- name: fail2
template: http
- name: http
http:
url: "{{workflow.parameters.url}}"
```
Case 2:
```YAML
kind: Workflow
metadata:
name: workflow-exit-handler-fail
spec: …
```
=> fix: correct manual retry logic. Fixes #14124

Dockerfile, docs/argo-server.md
Upgrading from 3.6.5 to 3.6.6 will probably cause you to see ALPN errors as per https://github.com/grpc/grpc-go/issues/434 and #14422.
This bakes the disabling flag into the docker image for this warning as a workaround for 3.6.
Built image and substituted it into a running 3.6.6 and found the error went away
Added some notes to the argo server page to document this. I will also highlight this in slack.
=> fix: disable ALPN in argo-server as a workaround

workflow/controller/cache_gc.go
Prevents `nil` pointer dereference when attempting to log invalid objects during ConfigMap cache garbage collection.
Changed the error log from `log.WithField().Error()` to `log.Error()` as there's no additional fields to be added.
`make test` passes locally.
I've also prepared a lint rule change in #14443.
No documentation changes needed.
=> fix: Remove nil ConfigMap reference in cache gc

.golangci.yml
Adds nilness detection to Go vet configuration to catch potential nil pointer dereferences during static analysis.
Modified `golangci-lint` configuration in `.golangci.yml` to use additional nilness linter checks.
Enabled it and found #14442. Once it has been merged, this needs a rebase. Until then the CI pipeline will fail on this PR.
No changes needed.
=> chore: Enable nilness checker in golangci-lint

.github/workflows/release.yaml, docs/access-token.md, docs/argo-server.md, docs/environment-variables.md, docs/managed-namespace.md, examples/k8s-orchestration.yaml
Fixes #13968
None of the rest of argoproj pushes to docker hub any more. With their rate limiting it makes it hard to use.
We have pushed to quay.io for years, so make that the only place we push to
Remove all the actions which push to docker hub.
Fix up a few docs which would attempt to pull from docker hub not quay.io
This is not a 100% purge of images in docker hub, there are still some references to things that don't mention a registry.
There is no intention to delete any old images, just to stop new ones going there.
I'm intending to backport this to 3.6, so comments around whether that is acceptable to reviewers would be helpful. This will allow me to test the release changes.
I have retained docker login within the codebase as our Dockerfile depends on images coming from dockerhub, …
=> feat!: don't push to docker hub

workflow/common/util.go, workflow/controller/controller_test.go, workflow/controller/workflowpod.go
Fixes #12941
This makes the behaviour  of the podSpec patch consistent by processing it via ProcessArgs in the case of template level expressions existing. It also fixes an issue where the replaceMap was emptied out for no reason. 
Performs the same processing applied to workflow level pod spec strategy.
Unit test was added and additionally manual testing was performed.
=> fix: ensure variable sub and processing is performed. Fixes #12941

util/unstructured/unstructured.go, workflow/controller/pod/controller.go
Fixes #14374
This change ensures that pagination happens in our list calls to both pod and workflows. This is needed because when k8s has a large number of resources, it is generally better to perform some amount of pagination. 
Simple change that modified the list calls to use 'continue on' tokens.
Tested to ensure the k8s api calls function as is.
=> fix: added pagination to the workflow and pod listings. Fixes #14374

workflow/controller/pod/controller.go
#14373 uses the `v1` import which was removed as a duplicate of `apiv1` in #14390, so the result does not compile when merged.
Use apiv1 instead.
=> chore: fix merge collision

.github/workflows/release.yaml, Dockerfile, Makefile, docs/workflow-executors.md, docs/workflow-pod-security-context.md
As discussed at Feb 17th 2025 contributor meeting
Security policies for some companies do not like having images where the user is `0` or root.
`argoexec` defaults to running as root, but changing this is likely to break a lot of users workflows.
Supplement this with an `argoexec-nonroot` image which runs as the user 8737, the same user as the rest of the images.
Also update the documentation around this, and remove references executor choices.
Built the image using the Makefile, and ran it in production for a week at pipekit.
Update the executor documentation to match the style guide better, and remove references to choices around the executor. I've retained the `Features` list mostly even though it feels a bit redundant.
Update the workflow pod security context documentation to prefer …
=> feat: non-root argoexec

workflow/sync/sync_manager.go, workflow/sync/sync_manager_test.go
Fix #14461
Fix the issue where some mutexes are not properly released when multiple mutexes are used in a workflow. This ensures all held mutexes are released correctly after execution.
The issue occurred because the logic inside the loop modified the original `MutexHolding` array while iterating over it. To fix this, we create a copy of the `MutexHolding` array and operate on the copy instead. This guarantees that all mutexes are properly released.
Added a test case named `WorkflowLevelMutexAcquireAndReleaseWithMultipleMutex` in `sync_manager_test.go` to verify that all mutexes are correctly acquired and released.
No documentation needed
=> fix: correctly release all mutexes when multiple mutexes are held. FIxes #14461

docs/walk-through/artifacts.md
Minor fix to artifact docs, omitting any other info here (from the PR template).
=> docs(artifacts): add missing metadata field in finalizer example

Dockerfile, docs/argo-server.md, util/tls/tls.go
Fixes #14422
As explained at #14422, any attempt to access the Argo server fails with an ALPN error. Example using curl:
```
$ curl -kv https://localhost:2746/api/v1/workflow-templates/argo 2>&1 | grep ALPN
* ALPN: curl offers h2,http/1.1
* ALPN: server did not agree on a protocol. Uses default.
{"code":14,"message":"connection error: desc = \"transport: authentication handshake failed: credentials: cannot check peer: missing selected ALPN property. If you upgraded from a grpc-go version earlier than 1.67, your TLS connections may have stopped working due to ALPN enforcement. For more details, see: https://github.com/grpc/grpc-go/issues/434\""}
```
Despite appearances, this isn't actually a client-side issue. The problem is that  Go's `net/http` server requires explicitly enabling HTTP/2 …
=> fix: update TLS config to support ALPN. Fixes #14422

.github/workflows/devcontainer.yaml
After https://github.com/argoproj/argo-workflows/pull/14341 was merged, the "Dev Container" workflow on the "main" branch is failing with segfaults when building the image for `arm64` ([example](https://github.com/argoproj/argo-workflows/actions/runs/15206127255/job/42769554389)):
```
[2025-05-23T08:46:25.854Z] #38 39.17 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[2025-05-23T08:46:26.082Z] #38 39.55 Segmentation fault (core dumped)
[2025-05-23T08:46:26.226Z] #38 39.56 dpkg: error processing package libc-bin (--configure):
[2025-05-23T08:46:26.331Z] : Sub-process /usr/bin/dpkg returned an error code (1)
```
The root cause appears to be a kernel bug (https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/2096782/), but I'm not sure. There are reports that downgrading …
=> build: workaround for segfaults when building dev container

docs/walk-through/docker-in-docker-using-sidecars.md
This small PR simply fixes the Buildkit template broken reference. Relevant page: https://argo-workflows.readthedocs.io/en/stable/walk-through/docker-in-docker-using-sidecars/
=> docs: fix Buildkit template

mkdocs.yml
I noticed that, in the field reference part of the docs, text enclosed by two `~~` does not render a strikethrough correctly:
When adding the `pymdownx.tilde` extension in mkdocs the strikethrough are rendered correctly:
```
make docs
make docs-serve
```
=> docs(field reference): add support for strikethrough syntax in mkdocs

workflow/controller/operator.go
Fixes #14495
Workflow stucks `Running` when initContainer in containerSet fails.
Remove unnecessary init container status checks because pod will turn to `Failed` if init container fails.
All nodes including container node will be `Failed` if pod fails.
```YAML
metadata:
name: hello-world-containerset-initcontainerfails
spec:
entrypoint: hello-world
templates:
- name: hello-world
dag:
tasks:
- name: containerset
template: containerset
- name: containerset
containerSet:
containers:
- name: hello
args: ["echo hello"]
- name: world
args: ["echo world"]
initContainers:
- name: setup
args: ["echo intentional failure; exit 1"]
```
=> fix: remove unnecessary init container status checks. Fixes #14495

.spelling, docs/upgrading.md, docs/variables.md, server/event/dispatch/operation_test.go, test/e2e/testdata/workflow-template-with-resource-expr.yaml, util/expr/env/env.go, util/expr/env/env_test.go, util/template/replace_test.go, workflow/controller/controller_test.go, workflow/controller/operator_concurrency_test.go, workflow/controller/operator_test.go, workflow/controller/testdata/workflow-sub-test-6.yaml, workflow/validate/validate_test.go
This PR aims to curate the available Sprig functions, exposing only those that provide unique value beyond the [expr-lang](https://github.com/expr-lang/expr) built-ins and are considered safe for use within workflow expressions. This reduces complexity, relying on expr-lang's built-in functions and memory budgeting where possible.
The [sprig library](https://github.com/Masterminds/sprig) has not received a new release since August 2024 and has many open issues, regarding Go vulnerabilities and bug fixes. This PR reduces dependencies on it, in favor of built-in expr functions.
NOTE: This is a breaking change.
Refactored the initialization of the Sprig function map in `util/expr/env/env.go`. Instead of exposing all functions from `sprig.GenericFuncMap()`, it now filters the full map against …
=> feat!: Introduce curated Sprig function allowlist

.github/workflows/release.yaml, Makefile, docs/workflow-pod-security-context.md
Fixes release 3.6.8
No-one seems to have access to docker-hub so 3.6 cannot be released with the nonroot image as we can't create the repo there. I'd like to sort this before 3.7 hits so it's not getting in the way, so keeping trying here.
In discussion with @isubasinghe we agreed we should have used the tag instead of the image name all along, so switching that here. Makes the code slightly messier.
Make argoexec-nonroot-image locally. Can't test CI except at a release.
Updated with new image names
=> fix: change non-root image to use tag

Makefile, docs/container-set-template.md, docs/debug-pause.md, docs/executor_swagger.md, docs/metrics.md, docs/new-features.md, mkdocs.yml, util/telemetry/builder/values.yaml
mkdocs has been emitting warnings on invalid links which are broken in our docs.
Fix all of them, and reconfigure it to prevent this in the future.
Added configuration of `anchors: warn` to mkdocs.yaml to make missing anchors cause a warning, and because of mkdocs running with `--strict` convert that to a CI failure.
Fix up all broken anchors. Two of note:
* `#interface` in executor_swagger.md really doesn't have anywhere to go, so remove the links with a nasty bit of `sed`. (We already depend on sed)
* The links to an emoji prefixed "Resource requests" title breaks wither mkdocs or markdown-linkcheck whatever you do, so remove the emoji for a full on 90s web experience and a happy developer.
`absolute_links` was changed to [`relative_to_docs`](https://www.mkdocs.org/user-guide/configurati …
=> docs: fix all links and prevent invalid links/anchors

docs/CONTRIBUTING.md
Document something that I think we already kind of do with regard to getting PRs reviewed.
This is somewhat to show we accept PR takeovers, in case someone is willing to pick up an PR but doesn't think they're allowed to.
Add a section on Timeliness to the contributing guidelines suggesting the process for taking over a PR and ensuring credits go to the appropriate person.
One sentence per line
Removed section on not assigning to non-members, this feels unwelcoming.
docs only: Checked in github markdown.
=> docs: update CONTRIBUTORS.md including guidance on PR change request timeliness and PR takeover

docs/workflow-controller-configmap.md, hack/docs/configdoc.go
Tidies output from #14515
Inline type definitions on one line (see TTL).
Embedded structs are inlined - so DBConfig shouldn't actually be used like it looks like it is documented, instead like this generates it.
Mangled the code to recurse into embedded types, and call `normalizeComment` on the comments for inlined types.
Looked at the resulting .md file.
[The newly built](https://argo-workflows--14543.org.readthedocs.build/en/14543/workflow-controller-configmap/) page looks better than the [current one](https://argo-workflows.readthedocs.io/en/latest/workflow-controller-configmap/)
This just changes documentation.
=> docs: tidy up autogenerated wf-configmap

workflow/controller/controller_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/operator_workflow_template_ref_test.go, workflow/util/merge.go, workflow/util/merge_test.go
Fixes #14426 
See the related issue description. It fixes the Inconsistent behavior for Workflow Arguments vs Template inputs to prioritise Value over ConfigMapKeyRef problem, and more in general the way the merge over the parameters containing values is performed.
* Modified the spec merge functionality `JoinWorkflowSpec` inside `workflow/util/merge.go`:
* Arguments.Parameters has patch strategy `merge`
* However when we merge the `Value`, `ValueFrom`, `Default` can conflict if they come from Wf, Wft or DefaultWf
* The change aims of removing this ambiguity, so that the resulting `execWf` uses the proper value given the priority Wf -> Wft -> DefaultWf.
* No UI changes.
Add unit tests to verify the changes. Tested with the given reproducible example from the issue and verified:
```yaml …
```
=> fix!: Adjust parameter value overriding. Fixes #14426

workflow/controller/operator.go
Cherry-picked fix: remove unnecessary init container status checks. Fixes #14495 (#14510)
=> fix: remove unnecessary init container status checks. Fixes #14495  (cherry-pick #14510)

go.mod, go.sum, server/auth/webhook/github.go, server/auth/webhook/interceptor_test.go, test/e2e/argo_server_test.go
Fixes #14388
GitHub has expanded their webhook events system to include newer event types such as `workflow_run`, `workflow_dispatch`, and `workflow_job`. Currently, Argo Workflows doesn't recognize these newer event types in its GitHub webhook authentication mechanism, causing `401` authentication failures when these events are sent. This PR updates the list of supported GitHub webhook event types to align with GitHub's current list of events (within the newest version of the used library).
Updated the `githubMatch` function in `server/auth/webhook/github.go` to include the missing GitHub webhook event types:
- CodeScanningAlertEvent
- DependabotAlertEvent
- DeployKeyEvent
- GitHubAppAuthorizationEvent
- WorkflowDispatchEvent
- WorkflowJobEvent
- WorkflowRunEvent
Additionally, the …
=> fix(server/auth/webhook): update GitHub webhook events list and library version

workflow/executor/executor.go
Fixes #14560
Currently the task result creation is only attempted 5 times when transient errors occur, this doensn't make any sense since we are relient on them to progress the state of the workflow. This change ensure that we retry effectively always when transient errors happen.
Modify the number of steps from 5 to the maximum int32 value.
None performed since this only modifies the parameters passed.
Not documented .
=> fix: retry forevever on task result creation related transient errors. Fixes #14560

server/auth/serviceaccount/claims.go
Set creator when use X509 client certificates.
Fixes #14578 
Loccal Test:
When use an alibaba cloud  ACK cluster kubeconfig.
You can see that after the update, there is creator. So do a local k3d cluster.
=> fix: set creator when use X509 client certificates. Fixes: #14578

cmd/argo/commands/server.go, go.mod, go.sum
Remove the dependency on [`skratchdot/open-golang`](https://github.com/skratchdot/open-golang) which is essentially unmaintained. We already use `pkg/browser` elsewhere.
Tested on linux/amd64 (nixos with gnome) only by running `dist/argo server --browser` and seeing that it opened the browser window for me in my default browser.
=> chore(deps): remove open-golang dependency

.github/workflows/pr.yaml
This PR fixes the feature note detector by using `tj-actions/changed-files`
Note, the output `any-added` of `tj-actions/changed-files` doesn't actually exist in a released version of the action, so I spent several confused attempts to get this to work.
Tested on my fork:
Added a feature note: https://github.com/Joibel/argo-workflows/actions/runs/16148097687
Didn't add a feature note: https://github.com/Joibel/argo-workflows/actions/runs/16148153499
=> fix: fix for feature note changed files

workflow/controller/operator.go
Fixes #14497 
This issue is difficult to reproduce. The scenario occurs when:
1. During taskResultReconciliation() execution, the Pod has either not yet finished running, or the Pod has finished but the task result cache has not been synced in time. As a result, the outputs parameters in taskResult are not set in status.nodes.
2. However, when podReconciliation() executes, the Pod has already completed, and the node is marked as Succeeded. This causes the workflow to proceed further. When the outputs of the node is required by other node, that would lead to an error.
Make the phase of the node unchange when the pod is completed and outputs are not set in the status.node
local test
=> fix: Make the phase of the node unchange when the pod is completed and outputs are not set in the status.node

cmd/argo/commands/root.go, cmd/workflow-controller/main.go, docs/upgrading.md, pkg/apis/workflow/v1alpha1/workflow_types.go, server/apiserver/argoserver.go, util/cmd/cmd.go, util/cmd/log.go, util/env/env.go, util/errors/errors.go, util/file/fileutil.go, util/logging/logging.go, util/logging/slog.go, util/logging/test_hook.go, workflow/controller/artifact_gc.go, workflow/controller/controller.go, workflow/controller/dag.go, workflow/controller/operator.go, workflow/controller/steps.go, workflow/controller/taskset.go, workflow/controller/workflowpod.go, workflow/cron/controller.go, workflow/gccontroller/gc_controller.go
Another follow on from #14527 and #14642.
This follows 14642 by removing print and warning from log levels (first two commits in the chain).
The third commit removes panic and fatal by adding WithPanic and WithFatal.
Whilst fixing up the callers of these methods I've improved them slightly by using WithError() for more structured logs.
This commit also implements https://github.com/argoproj/argo-workflows/pull/14527#discussion_r2163680318 by removing the mutex in the logger and all the hook copies, because they're now immutable for the lifetime of the parent logger.
With this we're down to the base `levels` from slog instead of the large number from logrus.
Upgrading notes added, but previously other log levels were never documented (not that I can find that if they were).
=> chore: remove more log levels and implement speedups

test/e2e/functional/parameter-aggregation-steps-with-retry.yaml, test/e2e/functional_test.go, workflow/controller/dag.go, workflow/controller/operator.go
Fixes #14647
Filter retried nodes and only aggregate outputs of their parent nodes.
E2E test and local test
=> fix: process aggregate outputs for steps node with retries. Fixes #14647

.devcontainer/builder/devcontainer-lock.json, .devcontainer/builder/devcontainer.json
There's a mismatch between the Golang version defined by `gomod` and the version used in the `devcontainer`. This change fixes that. 
- Updated `.devcontainer/builder/devcontainer.json` to use Golang `1.24.4`
- used `devcontainer` CLI to update "lock" file
- tested manually that the devcontainer is building using `make devcontainer-build`
=> chore: update devcontainer golang version

cmd/argoexec/commands/emissary.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
Cherry pick for 3.6 release
PR: https://github.com/argoproj/argo-workflows/pull/14633
(cherry picked from commit d86867cd97ba397b26ae790f2fdc89c07986e6cb)
=> fix: Sidecar terminates itself after the main container is finished. Closes #10612 (cherry-pick #14633)

workflow/controller/controller.go, workflow/controller/operator.go, workflow/metrics/metrics_custom.go, workflow/metrics/metrics_test.go
Fixes #14694
Realtime metrics may be cleaned up, even if the workflow is still running.
- Adding boolean value: `complete` in metric to indicate whether the metric is completed.
- Adding two functions: `CompleteRealtimeMetricsForWfUID` and `DeleteRealtimeMetricsForWfUID` to clearly distinguish whether to directly clean realtime metrics or only mark them as completed.
- Enable realtime metric gc only after its workflow is completed.
local test and UT
=> fix: GC realtime metrics after workflow completed. Fixes #14694

ui/src/shared/pod-name.test.ts, ui/src/shared/pod-name.ts
Fixes #14652 
When specifying a multibyte string with withParam, it returns the name of a POD that does not exist on k8s.
- Supports multibyte character strings
- Add a test
```
% k get po -n argo with-multibyte-smnwv-cat-612121745
Error from server (NotFound): pods "with-multibyte-smnwv-cat-612121745" not found
% k get po -n argo
NAME                                   READY   STATUS      RESTARTS      AGE
with-multibyte-smnwv-cat-4115705801    0/2     Completed   0             10s
```
```
% k get po -n argo with-multibyte-vg86n-cat-1799227071
NAME                                  READY   STATUS      RESTARTS   AGE
with-multibyte-vg86n-cat-1799227071   0/2     Completed   0          11s
argo: % k get po -n argo
NAME                                  READY   STATUS      RESTARTS      AGE …
```
=> fix(ui): Add multibyte character support tests for pod name generation

workflow/controller/cache/cache.go, workflow/controller/cache/configmap_cache.go
Fixes #14701
Empirical data shows a thundering herd problem on configmaps when workflows are highly parallel. 
We do not gain exclusive access to configmaps on load/save operations despite the current code suggesting that we do. I believe this is a result of many `MemoizationCache` objects being created. This change ensures that we obtain a lock on the cacheFactory before a call to `GetCache`, this should ensure only one cache. 
I've also added a retry block on save/load operations, treating conflict errors as transient errors. 
The decision to not add to the TransientError function was deliberate. I think conflict errors being treated as transient
errors are somewhat context dependent, hence the omission. 
This was a small fix, I think the ideal fix for these sort of issues is much more …
=> fix: prevent thundering herd on cache save/load. Fixes #14701

workflow/cron/operator.go
Fixes #14712
allow cron patch to use `TRANSIENT_ERROR_PATTERN` env var
just like how all other codes that interact with the k8s api
=> fix: cron patch use defaultRetry. Fixes #14712

pkg/apiclient/argo-kube-client.go, server/apiserver/argoserver.go, util/rbac/rbac.go, util/rbac/rbac_test.go, workflow/controller/controller.go, workflow/controller/ns_watcher.go
Fixes https://github.com/argoproj/argo-workflows/issues/14688
Currently Argo Server is always starting the ClusterWorkflowTemplateInformer even when running on namespace mode (without RBAC access to ClusterWorkflowTemplates).
Workflow controller is also creating the informer for namespaces, which also needs RBAC. This was introduced in https://github.com/argoproj/argo-workflows/pull/14188
Updated the Argo Server startup to only init the ClusterWorkflowTemplateInformer if it has RBAC access.
Updated the Workflow controller to only init namespace innformer when it has RBAC access.
Also created a new util/rbac package to hold the function HasAccessToClusterWorkflowTemplates because it is used by argo-server, workflow controller and apiclient. Let me know if you think that creating a new …
=> fix: only init Informers if SA has apropriate RBAC access. Fixes #14688

.spelling, Dockerfile, docs/argo-server.md
This reverts commit ce1b4471a64b4f20305d44fbbe2f3a9f242c8dcb.
With #14567 now in we can revert this
=> chore: revert fix: ignore ALPN by using the env variable hack (#14588)

test/e2e/functional/parameter-aggregation-steps-with-retry.yaml, test/e2e/functional_test.go, workflow/controller/dag.go, workflow/controller/operator.go
(cherry picked from commit 85b4c649d01e64dafc75760cf96c1abfdce463f8)
=> fix: process aggregate outputs for steps node with retries. Fixes #14647 (#14651) (release-3.6)

test/e2e/argo_server_test.go
On `release-3.6`, the `TestArgoServerSuite/TestReadinessProbe` test is failing with `invalid "Content-Type" response header`. Example: https://github.com/argoproj/argo-workflows/actions/runs/16828111449/job/47669457916
That test was backported in https://github.com/argoproj/argo-workflows/pull/14742, but it's conflicting with the changes in https://github.com/argoproj/argo-workflows/pull/11707, which haven't been backported to `release-3.6`. The latter PR changed the behavior of the server when `STATIC_FILES` is disabled. Before that change, the response for the root path won't have `Content-Type: text/html`, but aftewards it does, even though the response body is empty (since `index.html` will be an empty file when `STATIC_FILES=false`).
Before:
```
$ curl http://localhost:2746 -v
* Host …
```
=> test: fix TestReadinessProbe due to conflict

pkg/apiclient/http1/facade.go, pkg/apiclient/http1/facade_test.go
Fixes #14753
As described in issue #14753, query parameters are not passed when using a DELETE request. Code generated by `grpc-gateway` only allows path and query parameters for a `DELETE` request, so the `facade` code is updated to accommodate that. In general, the body can be used, but the command for generating the code needs to be updated.
https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-openapiv2/main.go#L22
Allowed
- manual testing
- added unit test
=> fix: allow query parameters for DELETE method and disable body marshaling. Fixes #14753

workflow/controller/operator.go
Fixes #14715
Whenever a daemon pod Fails/errors the retryStategy is being ignored. The current code logic will skip the retry, and The message “Node not set to be retried” shows on the logs. However:
- workflow controller is still creating a new daemon node, ignoring the retryStrategy rules
- that node is not copying the children (step 2 in picture below)
- the killed daemoned node is marked as fulfilled with success ( I think this is by design)
- the workflow is set as failed event though the new daemon node is running
This leaves a zombie pod (monitor(1)) and If the global retry strategy is set, the workflow is retried.
No longer creates new children when a daemoned retry node was set as failed or errored, which only happens when woc.processNodeRetries() decides that is not to be …
=> fix: retry strategy being ignored by daemoned nodes. Fix #14715

workflow/controller/operator.go
During a highly parallel workflow re-using the same template in a massive fan out it's been seen that you can get a panic, trimmed here:
```
fatal error: concurrent map iterarion and map write
encoding/json.Marshal({0x24148c0, 0xc16e8a1408})
/opt/bb/libexec/go/src/encoding/json/encode.go:175 +0xbe
github.com/argoproj/argo-workflows/v3/workflow/controller.substitutePodParams(0xc16e8a1408, 0xc00204d4d0, 0xc20e4006c8)
/go/src/github.com/argoproj/argo-workflows/workflow/controller/workflowpod.go:586 +0x290
```
Ensure templates which come from the common template store are copied before modification
This is very hard to reproduce, so not really tested.
None, just a bug fix
=> fix: ensure pod used container templates are copies

.github/workflows/ci-build.yaml
The describe and logs step in CI show up as "MySQL" when it actually means MySQL or Postgres (or neither if none was deployed for this test suite). This PR simply changes the word MySQL to Database.
=> fix: ci step titles MySQL->Database

Makefile
* Add `print-variables` target that `start` calls, and use `echo` so that output is not interleaved when run from `make start`
* This will help newcomers to the project familiarise with the codebase
=> chore: Add `help` make target and document key targets

test/e2e/expectedfailures/pod-termination-failure.yaml
Cherry-picked fix: moved off deprecated bitnami Docker images. Fixes 14785 from #14786
=> fix: moved off deprecated bitnami Docker images. Fixes 14785 (cherry-pick release-3.6)

test/e2e/expectedfailures/pod-termination-failure.yaml
Cherry-picked fix: moved off deprecated bitnami Docker images. Fixes 14785 from #14786
=> fix: moved off deprecated bitnami Docker images. Fixes 14785 (cherry-pick release-3.7)

workflow/artifacts/git/git.go
Cherry-picked fix: Fixes git over azure devops Fixes #11705 from #13875
=> fix: Fixes git over azure devops Fixes #11705 (cherry-pick release-3.6)

workflow/artifacts/git/git.go
Cherry-picked fix: Fixes git over azure devops Fixes #11705 from #13875
=> fix: Fixes git over azure devops Fixes #11705 (cherry-pick release-3.7)

test/e2e/cli_test.go, test/e2e/expectedfailures/misreference-template-name.yaml, test/e2e/smoke/empty-template-steps.yaml, workflow/templateresolution/context.go
Fixes #14861
We need to check if the template is nil before using it. If it is we return and give helpful message.
I moved the if check to check if the `tmpl` (template) is nil before usage.
I added a test to show that we don't currently consider empty steps to be a linting error, as mentioned in [the issue](https://github.com/argoproj/argo-workflows/issues/14861). If we change our minds later we have a test that will break if so. :smile:
Added linting test to the e2e tests for linting.
=> fix: linting pointer error when template name is invalid

workflow/common/common.go, workflow/controller/controller.go, workflow/controller/operator.go
Avoid deleting from the throttle queue when reapply fails.
When a running  workflow want to update to Succeeded, but it meet reapply failed. In this time, if is was remove from throttle queue, the workflow will be running forever. 
Because the admit function will prevent it from reconceil while not in running queue. 
And the 20min resync will not add it in pending queue because the resourceVersion not change.
=> fix: avoid deleting from the throttle queue when reapply fails.

workflow/validate/validate.go, workflow/validate/validate_dag_test.go, workflow/validate/validate_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/14042 https://github.com/argoproj/argo-workflows/issues/13773
Before this fix, the validation will failed if workflow contains dynamic templateRef.
Decide to skip validate dynamic templateRef instead of find a way to validate them due to the complexity and cases where its impossible to validate
- e.g. the templateRef depends on the output from a previous step
Added test for dynamic templateRef validation. copy from https://github.com/argoproj/argo-workflows/pull/14053
Added test to validate the regression introduced by previous templateRef validation implementation attempt
=> fix: skip validate dynamic templateref
