- .gitignore
> Update .gitignore to include Eclipse specific changes.

- common/python/ax/cluster_management/app/cluster_installer.py
- saas/argocli/src/applatix.io/argo/cmd/app.go
- saas/argocli/src/applatix.io/argo/cmd/common.go
- saas/argocli/src/applatix.io/argo/cmd/job.go
- saas/argocli/src/applatix.io/argo/cmd/login.go
- saas/argocli/src/applatix.io/argo/cmd/root.go
- saas/argocli/src/applatix.io/argo/cmd/util.go
- saas/argocli/src/applatix.io/argo/cmd/yaml.go
- saas/axamm/src/applatix.io/axamm/axamm_server/application.go
- saas/common/src/applatix.io/api/application.go
- saas/common/src/applatix.io/api/client.go
- saas/common/src/applatix.io/api/common.go
- saas/common/src/applatix.io/api/service.go
- `argo app list` to display running apps
- `argo app show <appname>` to display details about an app
- `argo job logs <service_id>` to retrieve logs for container in a job
- `argo job show --tree` improvements to be able to distinguish parallel vs. sequential steps in a workflow
> Issue #6: Argo CLI features and improvements:

- .argo/argo-platform-unit-tests.yaml
- platform/source/lib/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py
- platform/tests/minion_manager/aws/aws_bid_advisor_test.py
- platform/tests/minion_manager/aws/aws_minion_manager_test.py
- platform/tests/minion_manager/broker_test.py
> Minion-manager unit tests.

- saas/axops/src/ui/src/app/views/+applications/app-overview/app-overview.component.ts
It resolve issue with multiply results on the list if user is changing filter quickly.
> Application screen - added unsubscribe to get application.

- saas/axops/src/ui/npm-shrinkwrap.json
- saas/axops/src/ui/package.json
Bump argo-ui-lib to get tabs component fix
> [Firefox] Tabs doesn't work #49

- saas/axops/src/ui/src/app/common/customValidators/CustomRegex.ts
Password regex now checks if input contains at least one uppercase character
> #93: Password regex checks if uppercase letter incl.

- saas/axops/src/ui/src/app/model/task.ts
- saas/axops/src/ui/src/app/services/task.service.ts
- saas/axops/src/ui/src/app/views/+timeline/branches-overview/branches-overview.component.ts
- saas/axops/src/ui/src/app/views/+timeline/branches.view-models.ts
- saas/axops/src/ui/src/app/views/+timeline/job-details/job-details.component.ts
> Issue #47 - Use template branch instead of commit branch to identify job branch

- common/python/ax/cloud/aws/aws_s3.py
- common/python/ax/cloud/cloud.py
> Issue #113: don't query aws metadata server to get initial region for head bucket

- saas/axops/src/ui/src/app/views/+timeline/jobs-overview/jobs-overview.component.ts
Fixes https://github.com/argoproj/argo/issues/60
> Issue #60 - Implement client side pagination for active jobs

- saas/axops/src/ui/src/app/views/+applications/deployment-details/deployment-details.scss
> Issue 139: Fix for background at the 'Revision History' panel

- saas/axops/src/ui/src/app/app.scss
- saas/axops/src/ui/src/app/views/+applications/application-details/application-details.html
- saas/axops/src/ui/src/app/views/+applications/application-details/application-details.scss
- saas/axops/src/ui/src/app/views/+volumes/volumes-overview/volumes-overview.component.html
> 154 floating tabs

- saas/axops/src/ui/src/app/views/+timeline/revision/revision.component.ts
> Issue 141: Added live refresh to revision details screen

- saas/axops/src/ui/src/app/views/+timeline/job-step-summary/job-step-summary.component.ts
- saas/axops/src/ui/src/app/views/+timeline/job-step-summary/job-step-summary.html
Fixes https://github.com/argoproj/argo/issues/169
> Issue #169 - No error in UI - workflow step details

- saas/axdb/BaseDockerfile
- saas/axdb/Dockerfile
- saas/axdb/base-install.sh
- saas/axdb/preDockerBuild.sh
- saas/axdb/src/applatix.io/axdb/utils.go
Also including some gofmt error fixes.
> Issue #178: Fix cqlsh problem with new python version.

- saas/axops/src/applatix.io/axops/service/template.go
- saas/axops/src/applatix.io/axops/template.go
Change is required to implement Metrics screen enhancement. UI should be able to get unique list of template name and repo pairs.
> Issue #57 - Allow loading unique list of templates using /v1/templates API

- saas/axops/src/ui/src/app/common/global-search-input/view-models.ts
- saas/axops/src/ui/src/app/common/labels-filters/labels-filters.html
- saas/axops/src/ui/src/app/common/templates-filters/templates-filters.component.ts
- saas/axops/src/ui/src/app/common/templates-filters/templates-filters.html
- saas/axops/src/ui/src/app/common/templates-filters/templates-filters.scss
- saas/axops/src/ui/src/app/model/custom-view.ts
- saas/axops/src/ui/src/app/services/template.service.ts
- saas/axops/src/ui/src/app/views/+global-search/global-search-filter/global-search-filter.component.ts
- saas/axops/src/ui/src/app/views/+global-search/global-search-filter/global-search-filter.html
- saas/axops/src/ui/src/app/views/+global-search/jobs-list/jobs-list.component.ts
- saas/axops/src/ui/src/app/views/+metrics/test-dashboard/test-dashboard.component.ts
- saas/axops/src/ui/src/app/views/+metrics/test-dashboard/test-dashboard.html
> Issue 184: Added filter by template at the Global search for jobs.

- .gitignore
- platform/source/lib/ax/platform/cluster_version.py
- platform/source/lib/ax/platform/platform.py
- platform/source/tools/axtool.py
Fixes #142 
In main repo, we should not include the concept "portal". Separate scripts will be prepared for enterprise version
> Issue #142: remove portal report code from main repo

- saas/axops/src/ui/src/app/views/+metrics/test-dashboard/test-dashboard.component.ts
- saas/axops/src/ui/src/app/views/+metrics/test-dashboard/test-dashboard.html
- saas/axops/src/ui/src/app/views/+metrics/test-dashboard/test-dashboard.scss
> Issue 185: Metrics chart click events navigate to global search with filter parameters

- devops/src/ax/devops/gateway/event_translators/__init__.py
- devops/src/ax/devops/gateway/event_translators/bitbucket.py
- devops/src/ax/devops/gateway/event_translators/github.py
- devops/src/ax/devops/gateway/event_translators/gitlab.py
- devops/src/ax/devops/gateway/rest.py
Correctly parsing the webhook events
> Issue #221: Latest commits didn't trigger ci job on dev cluste

- saas/common/src/applatix.io/common/utils.go
PR fixes: https://github.com/argoproj/argo/issues/215
> Issue #215 - UI is unable to render template details page

- common/python/ax/cluster_management/app/cluster_installer.py
Fixes #258 by querying axops pod using label selector during password generation
> Issue #258: query axops pod using label during password generation

- common/python/argo/template/v1/container.py
- platform/source/lib/ax/platform/container.py
- platform/source/lib/ax/platform/container_specs.py
- platform/source/lib/ax/platform/deployments.py
- platform/source/lib/ax/platform/pod.py
- platform/source/lib/ax/platform/resources.py
- platform/source/lib/ax/platform/rest.py
- platform/source/lib/ax/platform/secrets.py
- platform/source/lib/ax/platform/task.py
Still doing some tests but testing is hard since, wfe changes and axops changes are required for a proper workflow to show up in axmon
> axmon changes for configs are k8s secrets

- saas/axops/src/ui/src/app/services/volumes.service.ts
- saas/axops/src/ui/src/app/views/+timeline/revision/revision.html
- saas/axops/src/ui/src/app/views/+volumes/volume-details/volume-details.component.ts
- saas/axops/src/ui/src/app/views/+volumes/volume-details/volume-details.html
- saas/axops/src/ui/src/app/views/+volumes/volume-details/volume-details.scss
- saas/axops/src/ui/src/app/views/+volumes/volumes-overview/volumes-overview.component.html
- saas/axops/src/ui/src/app/views/+volumes/volumes-overview/volumes-overview.component.ts
> Issue 137: Volumes screen cleanup - updated loaders, date range selector moved to top bar.

- saas/axops/src/ui/src/app/views/+timeline/jobs-overview/jobs-overview.component.ts
- saas/axops/src/ui/src/app/views/+timeline/jobs-overview/jobs-overview.html
- saas/axops/src/ui/src/app/views/+timeline/jobs-overview/jobs-overview.scss
> Issue #248: Added loader mockup to the jobs screen page.

- saas/axops/src/ui/src/app/views/+timeline/branches-overview/branches-overview.component.ts
- saas/axops/src/ui/src/app/views/+timeline/timeline/timeline.component.ts
> Issue 249: Timeline screen - fix for breadcrumbs

- saas/axops/src/ui/src/app/services/configuration.service.ts
- saas/axops/src/ui/src/app/services/group.service.ts
- saas/axops/src/ui/src/app/services/tool.service.ts
- saas/axops/src/ui/src/app/views/+config-management/config-management-overview/config-management-overview.component.ts
- saas/axops/src/ui/src/app/views/+config-management/config-management-overview/config-management-overview.html
- saas/axops/src/ui/src/app/views/+config-management/config-management-overview/config-management-overview.scss
- saas/axops/src/ui/src/app/views/+user-management/saml-config/saml-config.component.ts
> Issue #247: configuration users page update loaders

- .argo/test-yamls/test-secrets.yaml
- devops/src/ax/devops/axsys/axsys_client.py
- saas/axops/src/applatix.io/axops/configuration.go
- saas/axops/src/applatix.io/axops/configuration/configuration.go
- saas/axops/src/applatix.io/axops/configuration/schema.go
- saas/axops/src/applatix.io/axops/router.go
- saas/axops/src/applatix.io/axops/service/preprocess.go
- saas/common/src/applatix.io/template/examples/secrets.yaml
- saas/common/src/applatix.io/template/param.go
* Incorporates @sytianhe database schema changes for k8s secret support
* Axops conditionally substitutes configs depending on if it is a secret
* Clean up REST API interfaces
> Config secrets

- saas/axops/src/ui/src/app/model/configuration.ts
- saas/axops/src/ui/src/app/services/configuration.service.ts
- saas/axops/src/ui/src/app/views/+config-management/config-management-overview/config-management-overview.component.ts
- saas/axops/src/ui/src/app/views/+config-management/config-management-panel/config-management-panel.component.ts
- saas/axops/src/ui/src/app/views/+config-management/config-management-panel/config-management-panel.html
Please don't merge since required API changes are not merged yet.
> Issue #268 - Support creating secret configs in UI

- saas/axops/src/ui/src/app/model/view-preferences.ts
- saas/axops/src/ui/src/app/services/view-preferences.service.ts
- saas/axops/src/ui/src/app/views/+applications/app-overview/app-overview.component.ts
- saas/axops/src/ui/src/app/views/+config-management/config-management-overview/config-management-overview.component.ts
- saas/axops/src/ui/src/app/views/+policies/policies-overview/policies-overview.component.ts
- saas/axops/src/ui/src/app/views/+service-catalog/service-catalog-overview/service-catalog-overview.component.ts
- saas/axops/src/ui/src/app/views/+timeline/timeline/timeline.component.ts
> #231: store filter preferences

- platform/source/tools/container_outer_executor.py
> Issue #295: Kubernete secrets failed for Argo CI

- build/ax/build/saas.py
- saas/axops/build-in-contr.sh
- saas/axops/src/ui/config/webpack.dev.js
- saas/axops/src/ui/package.json
- saas/axops/src/ui/scripts/build.sh
PR allows to skip time consuming UI build steps is build started in debug mode:
```
./build/build_saas.py -s axops -np --debug
```
> Issue #284 - Improve axops build speed in dev mode

- build/ax/build/saas.py
- saas/axops/build-in-contr.sh
- saas/axops/src/ui/config/webpack.dev.js
- saas/axops/src/ui/package.json
- saas/axops/src/ui/scripts/build.sh
This reverts commit e09b265121cb95d14fe2cba4962e7cbce192281f.
> Revert "Issue #284 - Improve axops build speed in dev mode (#297)"

- saas/axops/src/applatix.io/axops/axops_server/main.go
- saas/axops/src/applatix.io/axops/project.go
- saas/axops/src/applatix.io/axops/router.go
- saas/axops/src/applatix.io/axops/s3.go
- saas/common/src/applatix.io/s3cl/s3cl.go
> changes in axops to talk to any s3 compatible object store

- common/python/ax/cloud/aws/aws_s3.py
- common/python/ax/cluster_management/app/cluster_installer.py
- common/python/ax/cluster_management/app/options/install_options.py
- common/python/ax/kubernetes/ax_kube_yaml_update.py
- devops/src/ax/devops/gateway/gateway.py
- platform/config/service/argo-wfe/axscheduler-svc.yml.in
- platform/config/service/config/argo-wfe-platform-bootstrap.cfg
- platform/source/lib/ax/platform/cluster_config/cluster_config.py
- platform/source/lib/ax/platform/platform.py
- platform/source/lib/ax/platform/rest.py
- platform/source/lib/ax/platform/task.py
- platform/source/tools/axmon.py
- platform/source/tools/container_outer_executor.py
- platform/source/tools/container_waiter.py
Needs an S3 compatible bucket. Tested with Argo running on minikube writing the Google Cloud bucket.
> Install Argo on minikube.

- saas/axops/src/ui/src/app/views/+integrations/slack-panel/slack-panel.html
> Error message fix

- README.md
> Fixed incorrect link to installation

- common/python/ax/cluster_management/argo_cluster_manager.py
- platform/source/lib/ax/platform/cluster_infra.py
- platform/source/tools/container_waiter.py
Had to move get_host_ip into common. Tested manually that the host and
port information is obtained correctly.
Subsequent commit will automate S3Proxy installation.
> Get S3Proxy url before installing Argo components.

- saas/axops/src/ui/src/app/views/+config-management/config-management-overview/config-management-overview.component.ts
Fixes https://github.com/argoproj/argo/issues/330
> Issue #330 - Configuration overview page is crashing during loading

- saas/axops/src/ui/src/app/views/+timeline/jobs-overview/jobs-overview.component.ts
> Issue #316: Fixed timeline live update jobs without repo

- saas/axops/src/ui/src/app/views/+timeline/jobs.service.ts
> Issue #324: - Fix for resubmit jobs without template_id.

- saas/axops/src/ui/src/app/views/+timeline/job-details/job-details.component.ts
> Issue #332: Fixed not clickable 'All Branches' in breadcrumbs for Jobs

- common/python/ax/cluster_management/app/options/__init__.py
- common/python/ax/cluster_management/app/options/install_options.py
- common/python/ax/cluster_management/argo_cluster_manager.py
This deletes the "axsys" and "axuser" namespaces.
> Uninstall Argo platform.

- lite/README.md
Updated README.md to add a note and link about prererequisites for using MiniKube.
Also reorganized "On Your Laptop" and "On Your Kubernetes Cluster" sections.
Minor formatting edits to make the text flow better visually
> Updated README.md to for Minikube

- platform/source/lib/ax/platform/cluster_config/consts.py
Testing Done:
1. Reproduced test failures before this fix. Verified that tests
succeeded after the fix.
> Set default cluster provider to ARGO.

- common/python/ax/cluster_management/app/cluster_installer.py
- common/python/ax/cluster_management/app/options/install_options.py
- platform/source/lib/ax/platform/platform.py
Testing Done:
1. Removed local "default" AWS profile.
2. Installed Argo on AWS and minikube.
> Actually use the user-provided cloud-profile.

- saas/axamm/src/applatix.io/axamm/deployment/utils.go
> Axamm should suppress external routes for user provided cluster

- platform/source/lib/ax/platform/rest.py
Testing done:
1. Prior to this change, accessing the "Settings" -> "System Settings" page would throw exceptions in axmon and a corresponding error on the UI.
2. Verified that after this change, there are no axmon and UI errors.
> Avoid get/set spot-instances config on user-provided clusters.

- saas/axops/src/ui/src/app/common/artifacts/artifacts.component.ts
- saas/axops/src/ui/src/app/services/artifacts.service.ts
- saas/axops/src/ui/src/app/views/+timeline/jobs.service.ts
Fixes https://github.com/argoproj/argo/issues/371
> Issue 371 - Use 'v1/artifacts?action=download' to download step artifact

- platform/config/service/argo-all/axops.yml.in
- platform/config/service/argo-gke/axops.yml.in
- platform/config/service/argo-wfe/axops.yml.in
- saas/axops/src/applatix.io/axops/system.go
- saas/axops/src/applatix.io/axops/utils/utils.go
- saas/common/src/applatix.io/template/context.go
> Add API to AXOPS to retreive enabled feature sets

- platform/source/lib/ax/platform/platform.py
> fixed install error when a previously uninstalled cluster had apps

- cmd/argoexec/commands/sidecar.go
- workflow/controller/workflowpod.go
- workflow/executor/executor.go
- Sidecar container runs along with main container
- It monitors the main container and waits unitl the main container completes
- Implements command wait()
> Adding sidecar container

- cmd/argo/commands/install.go
This commit checks whether Kubernetes cluster has a "cluster-admin" role and
if so, does the following:
* Create the "argo" serviceAccount.
* Create a clusterrolebinding called "argo-cluster-role" that binds to the
"cluster-admin"
Testing Done:
* Verfified that new service account and cluster rolebinding is created if they're absent.
* Verified that if service account and cluster rolebinding are present, the new code is a no-op.
* Verified that when cluster-admin is not present, the code is a no-op.
* Verified that new service account can be in "kube-system" or "default" namespace (whatever is specified by the --install-namespace option)
> Create serviceAccount & roleBinding if necessary.

- workflow/controller/controller.go
> Update controller config automatically on configmap updates

- ui/src/app/+help/help.component.ts
- ui/src/app/+workflows/workflow-details-page/workflow-details-page.component.ts
- ui/src/app/+workflows/workflow-details-page/workflow-details-page.html
- ui/src/app/+workflows/workflow-details-page/workflow-details.scss
- ui/src/app/+workflows/workflows-list-page/workflows-list-page.component.ts
- ui/src/app/app.module.ts
- ui/src/app/layout/top-bar/top-bar.component.ts
- ui/src/app/services/events.service.ts
- ui/src/app/services/index.ts
- added page titles depend which screen is open
- Workflow details page, added fixed tabs, adjusted width of tabs content to screen
- fix for missing function to close yaml viewer
- adjusted styles in workflow summary sliding panel. There was issue with displaying whole yaml viewer content (last couple lines wasn't visible)
> V2 style adjustments and small fixes

- ui/api/app.ts
Implemented changes allows to filter workflows by status. Examples:
`/api/workflows` returns all workflows
`/api/workflows?status=Succeeded` returns succeeded workflows
`/api/workflows?status=Succeeded&status=Failed` returns succeeded and failed workflows
> Issue #547 - Support filtering by status in API GET /workflows

- cmd/argo/commands/common.go
- cmd/argo/commands/delete.go
- cmd/argo/commands/get.go
- cmd/argo/commands/install.go
- cmd/argo/commands/list.go
- cmd/argo/commands/submit.go
- test/e2e/e2e_test.go
- test/e2e/install_test.go
- test/e2e/workflow_test.go
This commit creates basic e2e test:
InstallSuite: Installs Argo
WorkflowRunSuite: Runs a basic workflow.
To run all tests:
$ go test -v github.com/argoproj/argo/test/e2e -check.vv -kubeconfig /path/to/.kube/config
To run a specific suite:
$ go test -v github.com/argoproj/argo/test/e2e -check.vv -check.f InstallSuite -kubeconfig /path/to/.kube/config
> Basic E2e tests.

- cmd/argo/commands/install.go
- test/e2e/install_test.go
This makes Install() testable. Also, it makes the code more readable since each function
operates on arguments passed to it instead of global variables.
> Parameterize Install() and related methods.

- ui/api/app.ts
- ui/api/console-proxy.ts
- ui/api/main.ts
- ui/api/utils.ts
- ui/package.json
- ui/yarn.lock
PR implements API which allows to ssh into step main container. Usage example:
`ws://localhost:8001/api/steps/default/argo-wf-h44ft-2080616812/exec?cmd=sh`
> Implement API to ssh into pod

- ui/src/app/+workflows/workflow-details-page/workflow-details-page.html
Fixed issue with not displaying whole content of the tabs on the workflow details screen.
> Adjusted tabs content size to see horizontal and vertical scrolls.

- ui/package.json
- ui/yarn.lock
> Upgrade ui-lib

- examples/global-parameters-complex.yaml
- examples/global-parameters.yaml
- workflow/common/common.go
- workflow/common/util.go
- workflow/common/validate.go
- workflow/common/validate_test.go
- workflow/controller/operator.go
- workflow/controller/workflowpod.go
Implementation for allowing access to global parameters in workflow with simple and complex example. global parameters are accessed using workflow.parameter.<parameter name>
> Implementation for allowing access to global parameters in workflow

- ui/src/app/+workflows/workflows-list-page/workflow-steps/workflow-steps.component.html
> Added limit for number of steps in workflows list

- ui/src/app/+workflows/workflow-details-page/workflow-details-page.html
- ui/src/app/app.scss
- ui/src/app/common/toolbar/toolbar.html
- ui/src/app/common/toolbar/toolbar.scss
- ui/src/app/layout/top-bar/top-bar.component.scss
- ui/src/app/layout/top-bar/top-bar.html
- ui/src/assets/styles/_config.scss
> Removed empty toolbar

- demo.md
* Changed `argo` to `./argo` in multiple other places.
* Clarified that the UI will be accessible on the internal port if on Minikube
> Made minor changes to the documentation.

- Gopkg.lock
- Gopkg.toml
- cmd/argo/commands/wait.go
- test/e2e/wait_test.go
- workflow/client/client.go
E.g.
```
$ argo wait argo-ci-2vbv7 hello-world-g6pjv hello-world-r8brq
hello-world-r8brq completed at 2017-12-18 22:27:13 -0800 PST
hello-world-g6pjv completed at 2017-12-18 21:39:12 -0800 PST
argo-ci-2vbv7 completed at 2017-12-18 22:35:24 -0800 PST
```
Added e2e test for the command.
> Add `argo wait` for waiting on workflows to complete.

- workflow/common/validate.go
- workflow/common/validate_test.go
Partially addresses issue #620 by adding:
* path collision between input artifacts and volumeMounts
* activeDeadlineSeconds > 0
> Add validation checks for volumeMount/artifact path collision and activeDeadlineSeconds (#620)

- examples/README.md
Gents... I have added simple documentation to ensure people do not run into the same issues that I did by incorrectly installing minio. Perhaps this is legacy of watching the TGIK videos... :) and not reading the documentation thoroughly.
Rhys
> Document and clarify artifact passing

- workflow/controller/operator.go
Issues with retry on the dag branch
> Fix retry in dag branch

- cmd/argo/commands/get.go
Working version of cli for dag based nodes types. May need some prettifying for display. Based on constructing render trees based on the nodes relationships
> Initial work for dag based cli for everything. get now works

- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/types.go
- pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go
- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
This closes #737 
Not yet tested in a real cluster though.
> Support workflow pod tolerations

- cmd/argo/commands/submit.go
Implements https://github.com/argoproj/argo/issues/747
> Issue #747 - Support --instanceId parameter in submit a workflow

- CHANGELOG.md
- workflow/controller/operator.go
- workflow/controller/operator_test.go
Fix spelling from `parallism` to `parallelism`
> Minor spell fix for parallelism

- workflow/executor/executor.go
Patch for this issue https://github.com/argoproj/argo/issues/770
> parse the artifactory URL before appending the artifact to the path

- Dockerfile-cli
- Makefile
Although I ended up using kubectl for my cron use case, I believe this is still useful. But feel free to close if you don't need it.
> Build argo cli image

- Gopkg.lock
- cmd/argo/commands/logs.go
> Issue #660 - Support rendering logs from all steps using 'argo logs' command

- workflow/controller/workflowpod.go
* Use socket type for hostPath to mount docker.sock
* Fix format
> Use socket type for hostPath to mount docker.sock (#804)

- workflow/controller/steps.go
Fixes https://github.com/argoproj/argo/issues/816
> Issue #816 - fix updating outboundNodes field of failed step group node

- examples/README.md
- examples/k8s-owner-reference.yaml
Example & docs motivated by #837.
> Owner reference example

- workflow/controller/operator.go
Fixes https://github.com/argoproj/argo/issues/825
> Issue #825 - fix locating outbound nodes for skipped node

- README.md
- examples/README.md
Also noted `argo logs -w` as that can be very helpful.
> Minimal DAG docs

- README.md
We are using argo in our CI pipeline at [Datadog](https://www.datadoghq.com/) :+1: 
We appreciate all the work you're doing, awesome project !
> Add datadog to the argo users

- examples/retry-script.yaml
- pkg/apis/workflow/v1alpha1/types.go
- test/e2e/functional/retry-script.yaml
- workflow/common/validate.go
- workflow/controller/operator.go
Fixes [#889](https://github.com/argoproj/argo/issues/889)
> Issue #889 - Support retryStrategy for scripts

- examples/README.md
* Add syntax highlighting for all YAML snippets and most shell snippets for examples/README.md
* Clean up some whitespace at ends of lines
* Those shell snippets that are mostly outputs (like whalesay) have been left alone :)
> [examples/README.md] Add syntax highlighting for all YAML snippets and most shell snippets

- README.md
KintoHub is using Argo.
Argo is THE build and deploy system used at KintoHub. We are even deploying our own Infrastructure using it.
> Add new organization using argo

- errors/errors.go
- workflow/artifacts/s3/s3.go
- workflow/controller/exec_control.go
- workflow/controller/operator.go
- workflow/controller/steps.go
- workflow/executor/kubelet/kubelet.go
- workflow/executor/resource.go
Fix some format issues, to make "make test" happy.
> Fix format issues to resolve build errors

- api/openapi-spec/swagger.json
- cmd/argo/commands/list.go
- cmd/argo/commands/submit.go
- docs/workflow-controller-configmap.yaml
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/types.go
- pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go
- workflow/controller/config.go
- workflow/controller/controller.go
- workflow/controller/throttler.go
- workflow/controller/throttler_test.go
> Issue #740 - System level workflow parallelism limits & priorities

- demo.md
Fix a small typo in demo.md that I encounted when reading through the
getting started guide.
> Fix typo in demo.md

- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/namespace-install/overlays/03d_argo-ui-deployment.yaml
Closes https://github.com/argoproj/argo/issues/1114
> Issue #1114 - Set FORCE_NAMESPACE_ISOLATION env variable in namespace install manifests

- Makefile
closes https://github.com/argoproj/argo/issues/1084
> add support for ppc64le and s390x

- README.md
- cmd/argo/commands/get.go
- cmd/argo/commands/list.go
Adding Quantibio in Who uses Argo
> Adding Quantibio in Who uses Argo

- workflow/ttlcontroller/ttlcontroller.go
Closes https://github.com/argoproj/argo/issues/1132
> Issue #1132 - Fix panic in ttl controller

- workflow/controller/dag.go
- workflow/controller/exec_control.go
- workflow/controller/operator.go
- workflow/controller/steps.go
Closes https://github.com/argoproj/argo/issues/1040
> Issue #1040 - Kill daemoned step if workflow consist of single daemoned step

- workflow/executor/resource.go
> Replace exponential retry with poll

- README.md
We're using and contributing Argo. :)
> Add Preferred Networks to users in README.md

- cmd/argo/commands/submit.go
> Issue #988 - Submit should not print logs to stdout unless output is 'wide'

- workflow/controller/dag.go
workflow/controller/dag_test.go:21 TestDagRetrySucceeded fails in master
> minor fix: access dag phase with retries

- README.md
As part of the initiative to promote open source culture at Intuit, we are reviewing the text of projects featured on OpenSource.Intuit.com for spelling and grammar. Thanks!
> Update README with typo fixes

- workflow/executor/docker/docker.go
> Include stderr when retrieving docker logs

- README.md
Add Gardener to the users of argo.
https://github.com/gardener/gardener
https://github.com/gardener/test-infra
> Add Gardener to "Who uses Argo"

- README.md
assumed blog posts are listed in reverse-chronological order
> Admiralty: add link to blog post, add user

- README.md
Max Kelsen is utilising Argo throughout our organisation to manage data processing and machine learning pipelines. 
Incredibly thankful to the great community!
> Add Max Kelsen to USERS in README.md

- README.md
Long overdue, let me know if there is anything else I need to do to get this merged.
> chore: add IBM to official users section in README.md

- README.md
> [README] Add OVH as official user

- examples/output-parameter.yaml
> Fix typo in docs

- workflow/executor/executor.go
> Terminate all containers within pod after main container completes

- demo.md
This reverts commit 5635c33aa263080fe84e29a11a52f86fee583ca2.
> Revert "Update demo.md (#1396)"

- README.md
> Added codec.ai to the Argo community list

- cmd/argo/commands/wait.go
> Fix: 1008 `argo wait` and `argo submit --wait` should exit 1 if workflow fails 

- README.md
Add Commodus Tech as official user
> Add Commodus Tech as official user

- workflow/controller/dag.go
I'm not sure how this got into the repo, but there's a compiler error at `workflow/controller/dag.go:69`. This fixes it
> Fix a compiler error

- demo.md
Fix issue #1512 
Pls @sarabala1979 take a look
> Fix issue [Documentation] kubectl get service argo-artifacts -o wide

- workflow/controller/controller.go
- workflow/controller/controller_test.go
- workflow/controller/operator.go
- workflow/templateresolution/context.go
- workflow/templateresolution/context_test.go
- workflow/validate/validate.go
Solves #1529 
I used an informer to efficiently query WorkflowTemplates.
> Use cache to retrieve WorkflowTemplates

- demo.md
Fix issue #1546 
cc @sarabala1979
> Optimize argo binary install documentation

- manifests/namespace-install.yaml
- manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml
- workflow/controller/controller.go
Fixes #1579 
We needed to use `NewFilteredSharedInformerFactory` to limit the namespaces.
> Fix workflow template in namespaced controller

- Gopkg.lock
- cmd/argo/commands/get.go
- cmd/argo/commands/template/get.go
- test/test.go
- workflow/common/util.go
- workflow/controller/config_controller.go
- workflow/controller/controller_test.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
- workflow/controller/workflowpod_test.go
- workflow/templateresolution/context_test.go
- workflow/util/util.go
- workflow/validate/validate.go
- workflow/validate/validate_test.go
> Update from github.com/ghodss/yaml to sigs.k8s.io/yaml

- Gopkg.lock
- api/openapi-spec/swagger.json
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- workflow/artifacts/s3/s3.go
- workflow/executor/executor.go
This PR will resolve #1571  Support ability to assume IAM roles in S3 Artifacts
> Issue1571  Support ability to assume IAM roles in S3 Artifacts 

- workflow/executor/executor.go
I've seen very intermittent errors from the Kubernetes API on GKE when waiting for container completion, this adds a retry to the call.
> Added retry around RuntimeExecutor.Wait call when waiting for main container completion

- README.md
argoproj slack invite link somehow changed
> updated invite link

- cmd/argoexec/commands/wait.go
* Supports service meshes such as Istio where all traffic is routed
through the sidecar.
> Delay killing sidecars until artifacts are saved

- examples/global-outputs.yaml
> Fixed the example wrong comment

- workflow/validate/validate.go
> Removed unneeded  code from previous PR

- workflow/controller/dag.go
- workflow/controller/operator.go
My fix for dag output aggregation in #1648 was totally wrong and I fixed it correctly.
> Fix DAG output aggregation correctly

- workflow/controller/steps.go
The template is got from a template context when step outputs w/ `WithItem` or `WithParam` are aggregated because the direct child node doesn't exist for such a case. However, I realized expanded nodes for `WithItem` and `WithParam` uses the same template except for input parameters, so we can use the first expanded node to get the child node template from stored templates.
> Use stored templates to aggregate step outputs

- workflow/controller/steps.go
I fixed the child note template handling.
> Fix child node template handling

- README.md
We use Argo projects for our internal workflows
> [User] Update Argo users list

- README.md
Add community blog post on Argo Ansible role: Provisioning Argo Workflows on OpenShift
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   README.md
> Add new community blog post to README

- examples/README.md
See https://github.com/argoproj/argo/issues/1701
> `restartPolicy` -> `retryStrategy` in examples

- README.md
Update invitation link to generic, non-expiring one.
> Fix invitation link.

- examples/pod-spec-from-previous-step.yaml
@sarabala1979 Please review it.
> template for pod spec from output of previous step

- workflow/util/util.go
I've made a stab at attempting to unquote the strings from the parameters-file. See #1718. 
I'm a complete Golang newb so style may be way off.
> unquote strings from parameter-file

- demo.md
> binary up version

- cmd/argo/commands/list.go
Supported `no-headers` as kubectl does is very useful to process lists by command line.
```
$ argo list
NAME                                         STATUS                AGE   DURATION   PRIORITY
workflow-template-level-host-aliases-s6msl   Running               10m   10m        0
volumes-pvc-trvzl                            Running               10m   10m        0
volumes-existing-2jv79                       Running               10m   10m        0
suspend-template-hd6zm                       Running               10m   10m        0
$ argo list --no-headers
workflow-template-level-host-aliases-s6msl   Running               10m   10m        0
volumes-pvc-trvzl                            Running               10m   10m        0
volumes-existing-2jv79                       Running …
```
> Support no-headers flag

- examples/continue-on-fail.yaml
- examples/daemon-nginx.yaml
- examples/parallelism-nested-workflow.yaml
> Fix some issues in examples

- workflow/controller/operator.go
> Fix withParam node naming issue

- README.md
Additional resources:
- https://github.com/CermakM/argo-client-python
- https://github.com/thoth-station/ansible-role-argo-workflows
- https://github.com/thoth-station/common/blob/master/thoth/common/workflows.py
- https://github.com/thoth-station/workflows
And others... :)
> Added Red Hat to the list of Argo users

- pkg/apis/workflow/v1alpha1/workflow_types.go
- workflow/controller/operator.go
https://github.com/argoproj/argo/issues/1822
> fix: Fix a couple of nil derefs

- workflow/controller/config_controller.go
> fix: Panic if DB context has issue

- workflow/controller/workflowpod.go
Remove duplicate code of "Set schedulerName" block
> Code duplication

- docs/getting-started.md
> fix(docs): Update instructions for linux users

- .circleci/config.yml
- test/e2e/manifests/workflow-controller-configmap.yaml
Checklist:
The intention behind this PR is to replace Argo CI with faster, more robust, and better reported builds.
> test: Adds 'test' and 'ui' jobs to CI

- .github/ISSUE_TEMPLATE/question.md
Questions are frequently asked and there is no issue template for them.
> docs: Add question option to issue templates

- README.md
Added Peak.ai in the companies list that officially using Argo. We at Peak are developing a new product feature that is machine learning code workflow as a service based on Argo workflows/DAG.
Checklist:
> docs: Updated Readme.md for companies using Argo:

- .github/pull_request_template.md
> docs: Update PR template to demand tests.

- Dockerfile
> fix(argoexec): updated jq version to 1.6. Fixes #1936

- Makefile
> fix: Fix makefile IMAGE_TAG

- Makefile
> fix: No longer delete the argo ns as this is dangerous

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement_proposal.md
> docs: Encourage users to upvote issues relevant to them

- .circleci/config.yml
- Makefile
- cmd/argo/commands/token.go
- cmd/server/auth/authorizer.go
- cmd/server/workflowarchive/archived_workflow_server.go
- cmd/workflow-controller/main.go
- manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml
- manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/namespace-install/argo-server-rbac/argo-server-role.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- test/e2e/argo_server_test.go
- test/e2e/cli_test.go
- test/e2e/fixtures/e2e_suite.go
- test/e2e/fixtures/env.go
- test/e2e/manifests/postgres.yaml
- test/e2e/manifests/postgres/overlays/workflow-controller-deployment.yaml
- test/e2e/smoke_test.go
- util/kubeconfig/kubeconfig.go
- util/kubeconfig/token.go
- util/kubeconfig/token_test.go
- workflow/controller/controller.go
- workflow/controller/operator.go
- workflow/controller/workflowpod.go
Checklist:
While attempting to add support for K3D I found and fixed a bunch of issues:
* feat(controller): Exposes container runtime executor as CLI option.
* fix(rbac): Corrects RBAC roles.  
* test: Add support for K3D.
* test: Run all tests using v2 token.
* build: Speeds up builds.
> feat(controller): Exposes container runtime executor as CLI option.

- docs/rest-api.md
> chore: fix typo

- examples/README.md
Change controller to container to make it less confused
Checklist:
> docs: fix README.md under argo/examples

- workflow/common/placeholder.go
- workflow/validate/validate.go
- workflow/validate/validate_test.go
> fix(validate): Allow placeholder in values taken from inputs. Fixes #1984

- Makefile
- test/e2e/smoke_test.go
> chore: Smoke tests are timing out, give them more time

- examples/README.md
Just a quick fix of old 404 link to one of docs.
> docs: Update link to configure-artifact-repository.md

- cmd/server/apiserver/argoserver.go
> fix(persistence): Allow `argo server` to run without persistence

- cmd/server/workflow/workflow_server.go
- cmd/server/workflow/workflow_server_test.go
- test/e2e/fixtures/persistence.go
- test/e2e/fixtures/when.go
> fix: offload Node Status in Get and List api call

- Gopkg.lock
- test/e2e/argo_server_test.go
- test/e2e/fixtures/util.go
- test/e2e/testdata/argo-server-test-role.yaml
Fix https://github.com/argoproj/argo/issues/1954
> fix: Fix permission test cases

- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> fix: Do not expect workflowChange to always be defined

- workflow/controller/config_controller.go
> fix(controller): Do not crash if cm is empty. Fixes #2069

- cmd/argo/commands/server.go
- server/apiserver/argoserver.go
- server/static/response-rewriter.go
- server/static/static.go
> fix(ui): Add support for bash href. Fixes #2100

- server/static/static.go
> fix: route all unknown web content requests to index.html

- server/artifacts/artifact_server.go
> fix: Allow download of artifacts in server auth-mode. Fixes #2129

- cmd/argo/commands/auth/root.go
- cmd/argo/commands/auth/token.go
- cmd/argo/commands/root.go
- test/e2e/cli_with_server_test.go
> fix: Change `argo token` to `argo auth token`. Closes #2149

- cmd/argo/commands/cron/lint.go
- cmd/argo/commands/delete.go
- cmd/argo/commands/lint.go
- pkg/apiclient/classic-workflow-service-client.go
- test/e2e/cli_test.go
- workflow/validate/lint.go
Checklist:
Depended on by #2116
> chore: Update lint command to use apiclient. See #2116

- cmd/argo/commands/auth/token.go
- util/kubeconfig/kubeconfig.go
> fix: Fixed the Exec Provider token bug

- README.md
> docs(README): Sort list and add Greenhouse

- test/e2e/expectedfailures/failed-step-event.yaml
- test/e2e/expectedfailures/failed-step.yaml
- test/e2e/expectedfailures/pod-termination-failure.yaml
- test/e2e/expectedfailures/volumes-pvc-fail-event.yaml
- test/e2e/functional/continue-on-failed.yaml
- test/e2e/functional/success-event.yaml
- test/e2e/smoke/artifact-passing.yaml
- test/e2e/smoke/basic-2.yaml
- test/e2e/smoke/basic.yaml
- test/e2e/smoke/hello-world-workflow-tmpl.yaml
- test/e2e/testdata/basic.yaml
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Checklist:
This is not actually needed in the tests and could confuse.
> test: Remove podGC

- test/e2e/cli_with_server_test.go
> fix: Fixed the e2e test . failure

- ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
- ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx
- ui/src/app/shared/components/base-page.tsx
- ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx
- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> fix: Namespace and phase selection in UI

- README.md
> docs: Update ReadMe for EBSCO

- ui/src/app/login/components/login.tsx
> fix: Correct login instructions.

- ui/src/app/shared/services/workflows-service.ts
> fix: Remove quotes from UI

- test/e2e/fixtures/e2e_suite.go
> test: Correctly report e2e test diagnostics

- Makefile
> build: Fix ARGO_TOKEN

- go.mod
- go.sum
> chore: Run `go mod tidy`

- README.md
added Ramboll Shair to the official users
Checklist:
> docs: added Ramboll Shair to the official users

- ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
> fix: display error message when deleting archived workflow fails. Fix #2145

- workflow/controller/operator.go
Checklist:
I've created an enhancement [proposal](https://github.com/argoproj/argo/issues/1887) and discussed it with the community.
> feat: Label workflow-created pvc with workflow name

- go.sum
- persist/sqldb/offload_node_status_repo.go
- server/apiserver/argoserver.go
- test/e2e/fixtures/persistence.go
- test/e2e/manifests/mysql.yaml
- test/e2e/manifests/mysql/overlays/workflow-controller-deployment.yaml
- test/e2e/manifests/no-db.yaml
- test/e2e/manifests/no-db/overlays/workflow-controller-deployment.yaml
- test/e2e/manifests/postgres.yaml
- test/e2e/manifests/postgres/overlays/workflow-controller-deployment.yaml
- workflow/controller/config_controller.go
- workflow/controller/controller.go
> fix(offload): Fix bug which deleted completed workflows. Fixes #2233

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> feat: Add Pod Name to UI

- README.md
> docs: Add Cartrack into officially using Argo

- server/apiserver/argoserver.go
Checklist:
Fixes #2249 (maybe it fixes it - maybe not).
This can be merged as soon as builds are green and should be back-ported to v2.5.
> fix: Ignore bookmark events for restart. Fixes #2249

- server/workflowarchive/archived_workflow_server.go
- server/workflowarchive/archived_workflow_server_test.go
> fix(archive): Return correct next page info. Fixes #2255

- Makefile
- test/e2e/cli_test.go
> fix: Correctly report version. Fixes #2264

- ui/src/app/shared/services/requests.ts
- ui/src/app/shared/services/workflows-service.ts
> fix: Fixes double logging in UI. Fixes #2270

- persist/sqldb/migrate.go
Checklist:
* [ x] Optional. I've added My organization is added to the README.
Fixes #2278.
Can be merged as soon as approved. Needs back-porting.
> fix(persistence): Fix bug in migrating cluster name. Fixes #2278

- cmd/argo/commands/resume.go
- cmd/argo/commands/suspend.go
- pkg/apiclient/classic-workflow-service-client.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- test/e2e/cli_test.go
- test/e2e/fixtures/then.go
- test/e2e/testdata/sleep-3s.yaml
> chore(cli): Migrate `argo suspend` and `argo resume` to use API client. See #2116

- cmd/argo/commands/root.go
Checklist:
Fixes #2281
This can be merged as soon as approved and needs to be back-ported to v2.5
> fix(cli): Reinstate `argo wait`. Fixes #2281

- Makefile
> build(swagger): Fix argo-server swagger so version does not change.

- docs/managed-namespace.md
- docs/workflow-controller-configmap.yaml
> docs: More detail for namespaced installation

- test/e2e/functional/loops-empty-param.yaml
- test/e2e/functional_test.go
- workflow/controller/steps.go
> fix: Skip empty withParam steps. Fixes #1864

- workflow/cron/controller.go
- workflow/cron/operator.go
> fix: Remove active wf from Cron when deleted

- api/openapi-spec/swagger.json
Checklist:
CAN THE APPROVER PLEASE MERGE TOO?
> fix(swagger): Fix the broken swagger.

- README.md
> docs: Update Argo Rollouts description

- go.sum
- ui/src/app/shared/components/resource-submit.tsx
> feat: Allow Worfklows to be submitted as files from UI

- workflow/cron/operator.go
- workflow/cron/operator_test.go
> fix: Add timezone support to startingDeadlineSeconds

- docs/argo-server.md
- Removes spurions whitespace as well
Checklist:
> docs: correct server authentication default

- README.md
> docs(README): Add Prudential to the users list.

- cmd/argoexec/commands/root.go
- server/apiserver/argoserver.go
- workflow/controller/controller.go
> chore: Log version (structured) on component start-up

- ui/README.md
Fixed the broken image in the readme and updated a few bullet points.
Checklist:
> fix: Update readme for UI

- docs/CONTRIBUTING.md
- ui/src/app/index.html
Checklist:
I also added Kustomize to the build docs per [this discussion](https://argoproj.slack.com/archives/C8J6SGN12/p1583518664311700).
> fix: add noindex meta tag to solve #2381

- docs/argo-server.md
- docs/getting-started.md
Checklist:
Looked like this feature was only documented in code, so I added a section to the Argo Server docs.
I also added a link to server docs from getting-started. Hoping I haven't crossed the fine line between sufficient and bloated documentation in getting-started. Happy to hear thoughts on that.
> chore: document BASE_HREF

- Makefile
Checklist:
```
[acollins8@intuitdepe1a95 argo (⎈ |k3s-default:argo) ((v2.6.2))]$ make status
[acollins8@intuitdepe1a95 argo (⎈ |k3s-default:argo) (release-2.6)]$ make status
[acollins8@intuitdepe1a95 argo (⎈ |k3s-default:argo) (master)]$ make status
```
> fix: Build with the correct version if you check out a specific version

- CHANGELOG.md
> docs: update CHANGELOG.md. Closes #2397

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> feat(ui): add Env to Node Container Info pane. Closes #2471

- Dockerfile
- Dockerfile.dev
- Makefile
Patched Dockerfile, Dockerfile.dev and Makefile to add support for arm64 platform.
Fixes: #2080 
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
> feat: Add support for arm64 platform

- api/openapi-spec/swagger.json
- hack/swaggify.sh
> chore: Fix Swagger for PDB to support Java client

- test/e2e/cli_test.go
> test: Fix test

- workflow/metrics/controller_metrics.go
> fix: Fix potential panic

- examples/rest-examples.md
Checklist:
* [ c] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ b] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ not applicable] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [not applicable ] I've signed the CLA and required builds are green.
> docs: couple of examples for REST API usage of argo-server

- workflow/controller/operator_template_scope_test.go
This reverts commit b1ad163ac17312d103c03bf6a88069f1b055ea7d.
Checklist:
See #2498
> chore: Revert "fix: fix template scope tests (#2498)"

- cmd/argo/commands/client/conn.go
- cmd/argo/commands/server.go
> fix: Fixes --kubeconfig flag. Fixes #2492

- ui/src/app/workflows/components/workflow-dag/workflow-dag-render-options-panel.tsx
- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Closes: #2536 and #2406
Demo: https://cl.ly/261180c4bbc4
> feat: Add node type and phase filter to UI

- workflow/cron/controller.go
> chore: Error -> Warn when Parent CronWf no longer exists

- docs/configure-artifact-repository.md
Sorry for my mistake [#2578](https://github.com/argoproj/argo/pull/2578).
Checklist:
> chore: fix wrong Configuring Your Artifact Repository document.

- cmd/argo/commands/lint.go
- ui/src/app/app.tsx
- ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx
- ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-list/cluster-workflow-template-list.tsx
- ui/src/app/shared/examples.ts
- ui/src/app/shared/services/index.ts
- ui/src/models/index.ts
Fixes lint errors from #2525 and #2552
> fix: Fixes lint errors

- workflow/common/convert.go
- workflow/common/convert_test.go
> fix: Fixes panic in toWorkflow method

- test/e2e/argo_server_test.go
- test/e2e/cli_test.go
- test/e2e/cluster_workflow_template_test.go
- test/e2e/cron_test.go
- test/e2e/functional_test.go
> chore: Add comments to issues

- test/e2e/argo_server_test.go
- test/e2e/fixtures/e2e_suite.go
> fix: fix test cases. Fixes #2619

- Makefile
- hack/update-mocks.sh
- server/workflow/workflow_server.go
- util/logs/workflow-logger.go
> fix: Fix logs part 2

- Makefile
> ci: Fix codegen job

- docs/variables.md
- workflow/controller/steps.go
> fix: Add input paremeters to metric scope

- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
> fix: Add DAG as default in UI filter and reorder

- test/e2e/cli_test.go
- test/e2e/functional_test.go
> test: Fix flakey DeleteCompleted test

- test/e2e/fixtures/util.go
> test: Increase runCli timeout to 1m

- OWNERS
> docs: Update OWNERS

- ui/src/app/shared/template-resolution.ts
> fix: Add compatiblity mode to templateReference

- Dockerfile
- Dockerfile.dev
> build: Retry curl 3x

- Dockerfile
- Dockerfile.dev
- hack/maybe-skip-job.sh
- hack/recurl.sh
> ci: Recurl

- Makefile
Fixes #2770
Typo in variable declaration
> fix: Naming error in Makefile

- workflow/controller/controller_test.go
- workflow/controller/operator_template_scope_test.go
> fix(test): fix template scope tests. Fixes #2432

- docs/fields.md
- examples/recursive-for-loop.yaml
Example contributed by @samath117
> docs: Add example of recursive for loop

- .circleci/config.yml
- cmd/argoexec/commands/root.go
- server/apiserver/argoserver.go
- sonar-project.properties
- workflow/controller/controller.go
> fix: Print correct version in logs.

- docs/metrics.md
- workflow/controller/operator.go
- workflow/validate/validate.go
- workflow/validate/validate_test.go
Fixes #2817 
(#2815 and #2818 to be fixed in separate PR)
> fix: Enforce metric naming validation

- pkg/apis/workflow/v1alpha1/workflow_types.go
> fix: Artifact panic on unknown artifact. Fixes #2824

- test/e2e/functional_test.go
> test: Skip TestStopBehavior. See #2833

- cmd/argo/commands/server.go
- server/apiserver/argoserver.go
- ui/src/app/webpack.config.js
> chore: Configure webpack dev server to proxy using HTTPS

- docs/variables.md
- examples/exit-code-output-variable.yaml
> docs: Fix exit code example and docs

- .circleci/config.yml
- sonar-project.properties
> fix: Don't configure Sonar on CI for release branches

- docs/workflow-templates.md
> docs: Fix typo ".yam" -> ".yaml"

- config/config.go
- config/ttl.go
- manifests/quick-start-mysql.yaml
- manifests/quick-start-no-db.yaml
- manifests/quick-start-postgres.yaml
- manifests/quick-start/base/overlays/workflow-controller-configmap.yaml
- persist/sqldb/mocks/WorkflowArchive.go
- persist/sqldb/null_workflow_archive.go
- persist/sqldb/workflow_archive.go
- workflow/common/metrics.go
- workflow/controller/controller.go
- workflow/controller/controller_test.go
- workflow/controller/operator.go
- workflow/controller/operator_metrics_test.go
- workflow/metrics/collector.go
> feat: Add metric retention policy

- .circleci/config.yml
> ci: Remove context to stop unauthorized errors on test jobs

- workflow/executor/os-specific/chroot_darwin.go
- workflow/executor/os-specific/signal_darwin.go
- workflow/util/util_test.go
> build: Fix Darwin build

- persist/sqldb/migrate.go
> fix: Fixes MySQL 5.7 issue - default null value for timestamp column - Fixes #2932

- hack/port-forward.sh
> fix: typo in port-forward.sh

- cmd/argo/commands/wait.go
- cmd/argo/commands/watch.go
> fix(cli): Re-establish watch on EOF

- server/workflow/workflow_server.go
- util/logs/workflow-logger.go
> fix(cli): Remove info logging from watches. Fixes #2955

- .circleci/config.yml
- Dockerfile
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
Checklist:
* [ x ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ x ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ x] I've signed the CLA.
* [ x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ x] My builds are green. Try syncing with master if they are not. 
* [ x] My organization is added to USERS.md.
> chore: Upgraded to Node 14.0.0

- Makefile
> build: Build dev images from cache

- docs/cluster-workflow-templates.md
**Bug fix**
Correct typo with link reference 
Checklist:
> fix(docs): Typo with link reference

- docs/configure-artifact-repository.md
keyPrefix is deprecated; use keyFormat instead: https://github.com/argoproj/argo/blob/master/config/config.go#L183
Checklist:
> fix: configure-artifact-repository.md

- util/argo/audit_logger.go
- util/argo/audit_logger_test.go
> fix(events): Correct event API Version. Fixes #2994

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> fix(ui): Displays command args correctly pre-formatted.

- cmd/argoexec/commands/wait.go
> fix(executor): Save script results before artifacts in case of error. Fixes #1472

- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix(controller)!: Correctly format workflow.creationTimestamp as RFC3339. Fixes #2974

- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- workflow/executor/executor.go
> fix(artifacts): Allow tar check to be ignored. Fixes #2140

- workflow/executor/resource.go
> fix(executor): Properly handle empty resource results, like for a missing get. Fixes #1823

- config/config.go
- docs/workflow-controller-configmap.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- manifests/quick-start/mysql/overlays/workflow-controller-configmap.yaml
- manifests/quick-start/postgres/overlays/workflow-controller-configmap.yaml
- persist/sqldb/sqldb.go
> chore: Add ability to configure maximum DB connection lifetime

- USERS.md
> docs(users): Add Isbank to users.md

- docs/README.md
- docs/fields.md
- docs/work-avoidance.md
- examples/work-avoidance.yaml
> docs: Document work avoidance.

- util/logs/workflow-logger.go
Fixes: https://github.com/argoproj/argo/issues/3065
> fix: Graceful error handling of malformatted log lines in watch

- workflow/controller/operator.go
> fix(controller): Do not panic if `woc.orig` in not hydrated. Fixes #3118

- workflow/controller/workflowpod.go
- workflow/executor/executor.go
> fix(OSS): Fix bug in OSS artifacts

- pkg/apiclient/workflow/workflow.proto
- ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx
- ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx
- ui/src/app/shared/services/workflows-service.ts
- ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx
- ui/src/models/workflows.ts
> feat: Add 'submit --from' to CronWorkflow and WorkflowTemplate in UI. Closes #3112

- ui/src/app/workflows/components/workflow-panel/workflow-panel.tsx
Checklist:
This bug causes an error page to appear when re-submitting a failed workflow in the UI.
This can be merged as soon as green.
> fix(ui): Fix label error

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> feat(ui): Persist DAG rendering options in local storage. Fixes #3120

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.scss
- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> fix(ui): Input artifacts labelled in UI. Fixes #3098

- api/openapi-spec/swagger.json
- docs/fields.md
- pkg/apiclient/_.secondary.swagger.json
- pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.swagger.json
- pkg/apiclient/cronworkflow/cron-workflow.swagger.json
- pkg/apiclient/workflow/workflow.swagger.json
- pkg/apiclient/workflowarchive/workflow-archive.swagger.json
- pkg/apiclient/workflowtemplate/workflow-template.swagger.json
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- ui/src/models/workflows.ts
> feat(ui): Add Alibaba Cloud OSS related models in UI

- workflow/metrics/metrics.go
> chore: Master needs lint

- workflow/controller/operator.go
> chore: Remove unused nodeType in initializeNodeOrMarkError()

- docs/rest-api.md
> docs: fix api swagger file path in docs

- USERS.md
docs: Add Graviti as official Argo user
> docs: Add Graviti as official Argo user

- cmd/workflow-controller/main.go
- docs/scaling.md
> feat(controller): Add `--qps` and `--burst` flags to controller

- workflow/controller/workflowpod.go
> chore: Remove unused pod in addArchiveLocation()

- cmd/argo/commands/cron/create.go
- test/e2e/cli_test.go
Closes https://github.com/argoproj/argo/issues/3194
> feat: Add '--schedule' flag to 'argo cron create'

- workflow/validate/validate.go
- workflow/validate/validate_test.go
Fixes https://github.com/argoproj/argo/issues/3213
> fix(controller): Ensure image name is present in containers. Fixes #3213

- workflow/common/util.go
- workflow/controller/operator.go
- workflow/cron/operator.go
> feat(logging): Made more controller err/warn logging structured

- docs/variables.md
> docs: Correct available fields in {{workflow.failures}}

- .circleci/config.yml
> build: Disable Circle CI and Sonar

- pkg/apis/workflow/v1alpha1/workflow_types.go
- test/e2e/functional_test.go
- test/e2e/smoke/workflow-template-whalesay-template.yaml
- test/e2e/testdata/workflow-template-ref-exithandler.yaml
> fix: ExitHandler support on workflowtempalteRef

- workflow/controller/operator.go
> fix(controller): More structured logging. Fixes #3260

- ui/src/app/shared/duration.ts
- ui/src/app/shared/resources-duration.tsx
- ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx
> fix(ui): Update workflow drawer with new duration format

- workflow/controller/config.go
> fix: Fixed panic on archiveLabelSelector nil

- ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx
- ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx
> fix(ui): Allow render of templates without entrypoint. Fixes #2891

- Makefile
> build: Allow to change k8s namespace for installation

- README.md
> docs: Update CI Badges

- docs/releasing.md
> docs: Update releasing.md

- cmd/argo/commands/delete.go
- cmd/argo/commands/list.go
- cmd/argo/commands/list_test.go
- server/workflow/workflow_server.go
> fix: Fix delete --complete

- cmd/argo/commands/logs.go
- cmd/argo/commands/resubmit.go
- cmd/argo/commands/retry.go
- cmd/argo/commands/submit.go
- cmd/argo/commands/wait.go
- cmd/argo/commands/watch.go
Checklist:
I've not added any tests! I think the significant parts of this code is effectively tested already.
> feat(cli): Add --logs to `argo [submit|resubmit|retry]. Closes #3183

- workflow/common/common.go
> chore: Clean up unused constants

- USERS.md
It's now renamed to be Ant Group (short for Ant Financial Services Group).
Checklist:
> docs: Rename Ant Financial to Ant Group

- ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
> fix(ui): Compiler error from workflows toolbar

- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> fix(ui): runtime error from null savedOptions props

- workflow/common/common.go
- workflow/common/convert.go
- workflow/common/convert_test.go
> feat(controller): Label workflows with their source workflow template. Fixes #3326 

- Makefile
- Procfile
- hack/port-forward.sh
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- manifests/quick-start/base/overlays/argo-server-deployment.yaml
> fix: Remove broken SSO from quick-starts

- docs/fields.md
- hack/docgen.go
Fixes: https://github.com/argoproj/argo/issues/3202
Thanks for the reminder @alexec
> docs: Field fix (ParallelSteps -> WorkflowStep)

- USERS.md
> docs: Adding InVision to Users

- workflow/controller/controller.go
- workflow/controller/controller_test.go
- workflow/controller/event_recorder_manager.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix(controller): Allow events to be sent to non-argo namespace. Fixes #3342

- cmd/argo/commands/cron/get_test.go
- cmd/argo/commands/get_test.go
- go.mod
- go.sum
- server/workflow/workflow_server_test.go
- util/printer/workflow-printer.go
- workflow/common/convert_test.go
- workflow/controller/operator_metrics_test.go
- workflow/controller/steps_test.go
- workflow/cron/operator_test.go
- workflow/util/util_test.go
- workflow/validate/validate.go
> chore: Simplify deps by removing YAML

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> fix: Fix UI bug in DAGs

- server/workflow/workflow_server.go
- server/workflow/workflow_server_test.go
> fix(server): Fix `context cancelled` red herring error. Fixes #3073

- .github/stale.yml
> build: Enable Stale Bot

- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
- ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
> fix(ui): Confirmation of workflow actions

- ui/src/models/workflows.ts
Removing these since they are not used in the UI and have been very outdated and hard to maintain.
Checklist:
> chore(ui): Remove unused interfaces for artifacts

- workflow/controller/operator.go
> fix: Running pods are garaged in  PodGC onSuccess 

- docs/fields.md
- examples/cluster-workflow-template/workflow-template-ref-with-entrypoint-arg-passing.yaml
- examples/cluster-workflow-template/workflow-template-ref.yaml
> chore: Added CWFT WorkflowTemplateRef example

- docs/cost-optimisation.md
- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Slight grammar tweak. Changing _maybe_ to _may be_ where it's used as a verb instead of an adverb.
> chore: maybe -> may be

- docs/workflow-controller-configmap.yaml
Add a snippet about useSDKCreds
Checklist:
> docs: Update config example to include useSDKCreds

- workflow/controller/dag.go
- workflow/controller/dag_test.go
Fixes: https://github.com/argoproj/argo/issues/3395
> fix: Ensure non-leaf DAG tasks have their onExit handler's run

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> fix(ui): Render DAG with exit node

- server/auth/sso/sso.go
> fix(sso): Remove unused `groups` claim. Fixes #3411

- USERS.md
> docs: Add Sohu as official Argo user

- workflow/controller/operator.go
> fix(controller): Prevent panic on nil node. Fixes #3436

- cmd/argo/commands/stop.go
- docs/cli/argo_stop.md
> docs: typo in argo stop --help

- ui/package.json
- ui/yarn.lock
My local build (`yarn install`) was having issues. Upgrading this library fixes them
> chore: Upgrade node-sass

- go.mod
- go.sum
> chore: update aws-sdk-go version

- docs/quick-start.md
> docs: Fixed some typos

- docs/cli/argo_logs.md
> docs: Fix CLI docs

- docs/quick-start.md
> docs: In quick-start. Use http, not https for link

- cmd/argo/commands/list.go
- cmd/argo/commands/list_test.go
> feat(cli): List only resubmitted workflows option

- examples/output-parameter.yaml
- workflow/common/util.go
- workflow/common/util_test.go
Closes: https://github.com/argoproj/argo/issues/3319
> feat: Attempt to resolve nested tags

- workflow/controller/operator.go
- workflow/controller/operator_test.go
Fixes: https://github.com/argoproj/argo/issues/3471
> fix: Pass resolved arguments to onExit handler

- test/e2e/cli_test.go
- test/e2e/testdata/retry-omit.yaml
- workflow/controller/dag.go
- workflow/util/util.go
Fix #3524 
**Still needs test**
> fix: Fix when retrying Workflows with Omitted nodes

- .github/no-response.yml
> chore: Enable no-response bot

- docs/access-token.md
Checklist:
* [b ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
> docs: Correct type Fixes #3546

- docs/workflow-templates.md
Checklist:
Before the change, the website/docs look like this,
> docs: Change formatting to put content into code block

- test/e2e/cli_test.go
- test/e2e/testdata/retry-omit.yaml
Fixes https://github.com/argoproj/argo/issues/3540
> fix: Fix flakey TestRetryOmitted

- test/e2e/ui/ui-render-many-nodex.yaml
- ui/src/app/workflows/components/workflow-dag/graph/collapsible-node.ts
- ui/src/app/workflows/components/workflow-dag/graph/dfs-sorter.ts
- ui/src/app/workflows/components/workflow-dag/graph/shifter.ts
- ui/src/app/workflows/components/workflow-dag/workflow-dag-render-options-panel.tsx
- ui/src/app/workflows/components/workflow-dag/workflow-dag.scss
- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Closes https://github.com/argoproj/argo/issues/3527
Click to expand
> feat: Collapse children in UI Workflow viewer

- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> fix(ui): cannot read property 'push' of undefined when filtering by label. Fixes #3550

- server/auth/gatekeeper.go
> fix(server): Ignore not-JWT server tokens. Fixes #3562

- cmd/argo/commands/delete.go
- docs/cli/argo_delete.md
- test/e2e/cli_test.go
> feat(cli): Support deleting resubmitted workflows

- .github/workflows/ci-build.yaml
> build: Increase timeout

- docs/configure-artifact-repository.md
> docs: Add documentation for configuring OSS artifact storage

- server/workflow/workflow_server.go
- util/util.go
- util/util_test.go
Fixes https://github.com/argoproj/argo/issues/3625
> fix: Fix 'malformed request: field selector' error

- docs/workflow-controller-configmap.yaml
Checklist:
This keeps catching people out.
> docs: Add comment to config map about SSO auth-mode

- docs/README.md
> docs: Update link to examples so works in raw github.com view

- docs/metrics.md
- workflow/metrics/metrics.go
- workflow/metrics/metrics_test.go
- workflow/metrics/util.go
- workflow/metrics/util_test.go
> fix: Enforce metric Help must be the same for each metric Name

- docs/default-workflow-specs.md
> docs: Fix type in default-workflow-specs.md

- ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx
> chore(ui): Add label to 'from' section in Workflow Drawer

- workflow/controller/controller.go
- workflow/controller/pod/log.go
- workflow/controller/pod/significant.go
- workflow/controller/pod/significant_test.go
> fix(controller): Adds ALL_POD_CHANGES_SIGNIFICANT

- docs/rest-api.md
> docs: Correct version. Fixes #3697

- cmd/argo/commands/delete.go
- test/e2e/cli_test.go
> fix: Fix bug with 'argo delete --older'

- docs/windows.md
Adds a note as requested in #3682.
FYI @lippertmarkus 
Checklist:
> docs(windows): add note about artifacts on windows

- workflow/controller/dag.go
- workflow/controller/dag_test.go
> fix: Ensure target task's onExit handlers are run

- hack/test_report.go
- hack/test_report_test.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix(controller): Tolerate PDB delete race. Fixes #3706

- docs/variables.md
- workflow/controller/operator.go
- workflow/controller/operator_test.go
enhancement discussed in https://github.com/argoproj/argo/issues/3708
Checklist:
> feat(operator): Add scope params for step startedAt and finishedAt #3708

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> fix: Fix workflow onExit nodes not being displayed in UI

- test/e2e/argo_server_test.go
> chore: Format test code

- Makefile
> test: Increase cron test timeout to 7m

- ui/src/app/help/components/help.tsx
Checklist:
~~* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~~
Fixes #3762
> fix(ui): Remove outdated download links. Fixes #3762

- docs/cron-workflows.md
> docs: Add section on CronWorkflow crash recovery

- USERS.md
> chore: add New Relic to USERS.md

- .github/workflows/docker-image.yml
> ci: Change workflow for pushing images. Fixes #2080

- test/e2e/cli_test.go
- test/e2e/functional_test.go
Checklist:
See #2833 and #3540 
These two tests are failing often. They both pass locally. I don't know if they are failing due to a software fault.
> test: Skip TestStopBehavior and TestRetryOmit

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> fix(ui): crash when workflow node has no memoization info. Fixes #3838

- ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
> chore(ui): correct a typo

- USERS.md
We user Argo for Video Processing Jobs on our platform & it's been great so far. Thank you! :)
> chore(users): Add Fynd Trak to the list of Users

- test/e2e/argo_server_test.go
- test/e2e/cli_test.go
- test/e2e/cli_with_server_test.go
- test/e2e/cluster_workflow_template_test.go
- test/e2e/fixtures/e2e_suite.go
- test/e2e/fixtures/then.go
- test/e2e/fixtures/when.go
- test/e2e/functional_test.go
- test/e2e/malformed_resources_test.go
- test/e2e/smoke_test.go
- test/e2e/workflow_template_test.go
> test: Fix flaky e2e tests

- .github/workflows/ci-build.yaml
- test/e2e/cli_test.go
- test/e2e/functional_test.go
Fixes https://github.com/argoproj/argo/issues/3823
> test: Fix TestRetryOmit and TestStopBehavior

- util/retry/retry.go
> feat(controller): Set default retry factor to 2. Closes #3911

- docs/workflow-controller-configmap.yaml
Adding SSL options to example configmap.
both PRs:
https://github.com/argoproj/argo/pull/1867/files
https://github.com/argoproj/argo/pull/1756/files
seem not to be documented anywhere. This PR fixes parts of that.
> docs: Update workflow-controller-configmap.yaml with SSL options

- docs/roadmap.md
> docs: Correct Java client project link

- Makefile
- cmd/argo/commands/version.go
- test/e2e/cli_test.go
- test/e2e/cli_with_server_test.go
> fix(cli): Allow `argo version` without `KUBECONFIG`. Fixes #3943

- docs/workflow-submitting-workflow.md
Nothing serious, it just took me ages because I did not see it.
> fixed typo in docs

- Dockerfile
> build: Allow build with older `docker`. Fixes #3977

- cmd/argo/commands/cron/get_test.go
- workflow/controller/operator.go
- workflow/controller/operator_metrics_test.go
- workflow/controller/operator_test.go
Fixes: https://github.com/argoproj/argo/issues/3976
Thanks to @kevinhwang for the bug report
> fix: Create global scope before workflow-level realtime metrics

- USERS.md
Adding Stillwater to the list of Argo workflow users
Checklist:
> docs: Adding Stillwater Supercomputing

- USERS.md
- docs/workflow-controller-configmap.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- manifests/quick-start/base/overlays/workflow-controller-configmap.yaml
- pkg/apis/workflow/v1alpha1/info.go
- test/e2e/argo_server_test.go
- ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> feat(ui): Add `startedAt` and `finishedAt` variables to configurable links. Fixes #3898

- server/auth/sso/sso.go
> fix(server): Removes minor XSS vulnerability. Fixes #3942

- workflow/common/convert.go
- workflow/validate/validate.go
- workflow/validate/validate_test.go
Fixes https://github.com/argoproj/argo/issues/3989
> fix: Consider WorkflowTemplate metadata during validation

- api/openapi-spec/swagger.json
- docs/fields.md
- docs/swagger.md
- examples/dag-task-level-timeout.yaml
- examples/step-level-timeout.yaml
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/openapi_generated.go
> fix: Step and Task level timeout examples

- workflow/controller/operator.go
> fix(controller): Revert `resubmitPendingPods` mistake. Fixes #4001

- .github/workflows/ci-build.yaml
- ui/package.json
- ui/src/app/workflows/components/workflow-dag/workflow-dag-render-options-panel.tsx
- ui/src/app/workflows/components/workflow-dag/workflow-dag.scss
- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.scss
- ui/yarn.lock
Fixes: #3595 
Example: https://share.getcloudapp.com/d5uEj7bZ
> feat(ui): Introduce modal DAG renderer. Fixes: #3595

- ui/src/app/shared/components/resource-editor/resource-editor.tsx
> fix(ui): Report errors when uploading files. Fixes #3994

- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
> fix(ui): Allow you to view timeline tab. Fixes #4005

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> fix(ui): Correctly show pod events. Fixes #4016

- ui/src/app/shared/utils.ts
> fix(ui): Do not save undefined namespace. Fixes #4019

- docs/argo-server-sso.md
- docs/artifact-repository-ref.md
- docs/default-workflow-specs.md
- docs/enhanced-depends-logic.md
- docs/events.md
- docs/links.md
- docs/memoization.md
- docs/metrics.md
- docs/node-field-selector.md
- docs/offloading-large-workflows.md
- docs/resource-duration.md
- docs/submit-workflow-via-automation.md
- docs/synchronization.md
- docs/tls.md
- docs/webhooks.md
- docs/work-avoidance.md
- docs/workflow-archive.md
- docs/workflow-creator.md
- docs/workflow-events.md
- docs/workflow-requirements.md
- docs/workflow-submitting-workflow.md
> docs: Update pages to GA. Closes #4000

- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Fixes https://github.com/argoproj/argo/issues/3966
> fix: Don't save label filter in local storage. Fixes #3966

- USERS.md
> Add Data4Risk to users list

- USERS.md
> remove the space

- docs/fields.md
- examples/buildkit-template.yaml
- examples/buildkit.yaml
> docs: Add `buildkit` example. Closes #2325

- Dockerfile
- Dockerfile.dev
- Dockerfile.windows
- USERS.md
Checklist:
I've used https://github.com/GoogleContainerTools/container-structure-test for docker specific tests. I can add this if that's desirable.
I've signed the CNCF CLA. Is there another one?
> chore(executor): upgrade `kubectl` to 1.18. Closes #3996

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
- workflow/util/util.go
- workflow/util/util_test.go
> fix: Tolerate malformed workflows when retrying

- workflow/util/util_test.go
> chore: Fix merge error

- workflow/artifacts/gcs/gcs.go
This partially fixes #3682 problems with GCS on Windows, which were related to filepath handling. I checked all calls of `filepath.Clean()`.
For the S3 problems stated in the #3682 we first need to merge https://github.com/argoproj/pkg/pull/27 and afterwards create a new git tag in argoproj/pkg so that i can create a PR in this repo to update the module for Argo workflows.
Checklist:
> fix(artifacts): Make artifacts cross-platform compatible. Fixes #3682

- workflow/controller/controller.go
> fix: Improve better handling on Pod deletion scenario 

- workflow/controller/operator.go
- workflow/util/util.go
- workflow/util/util_test.go
Checklist:
Fixes #3719
Related to #3751
> feat(controller): Write back workflow to informer to prevent conflict errors. Fixes #3719

- docs/fields.md
- workflow/controller/operator.go
- workflow/controller/operator_workflow_template_ref_test.go
> fix(controller): Correct the order merging the fields in WorkflowTemplateRef scenario. Fixes #4044

- workflow/util/util.go
> fix(cli): Add retry to retry ;). Fixes #4101

- ui/src/app/app.tsx
Checklist:
See #4084
This is only a partial fix to this issue. Probably not enough to totally fix it, but maybe enough to mitigate it for cluster installs, and low risk.
> fix(ui): No longer redirect to `undefined` namespace. See #4084

- ui/src/app/shared/components/error-notice.tsx
- ui/src/app/shared/components/error-panel.tsx
- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Checklist:
Closes #4087
* Add a "reload" button to the error panel so that we can provide an error recovery actions. By default this is reload the page after 2m.
> feat(ui): Improve error recovery. Closes #4087

- workflow/controller/pod/significant.go
- workflow/controller/pod/significant_test.go
> fix(controller): Treat annotation and conditions changes as significant

- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
> fix(ui): Show "waiting for data" while waiting for pod logs. Fixes #3916

- USERS.md
> docs: Added PDOK to USERS.md

- server/workflow/workflow_server.go
- workflow/util/util.go
- workflow/util/util_test.go
Checklist:
Fixes #4101
My previous fix was not enough. It just retries the conflict repeatedly instead of just once. This makes sure we get the workflow again.
> fix(cli): Add retry to retry, again. Fixes #4101

- USERS.md
uses argo workflows for ingestion pipelines.
Checklist:
> Adding reserved.ai to users list

- workflow/executor/docker/docker.go
Fix a race condition caused by setting err in DockerExecutor.Kill concurrently from both the main goroutine and the forceKill goroutine.
Checklist:
> fix(executor): race condition in docker kill. Fixes #3053

- USERS.md
> docs: Add Onepanel to USERS.md

- api/openapi-spec/swagger.json
- docs/fields.md
- docs/swagger.md
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- server/workflow/workflow_server.go
- workflow/validate/validate.go
Fixes https://github.com/argoproj/argo/issues/4102
> chore: Deprecate unused RuntimeResolution field

- pkg/apis/workflow/register.go
- workflow/util/util.go
- workflow/util/util_test.go
> fix(controller): Correct unstructured API version. Caused by #3719

- ui/yarn.lock
PR upgrades argo-ui library version
> refactor: upgrade argo-ui library version

- workflow/cron/controller.go
- workflow/cron/operator.go
Fixes: https://github.com/argoproj/argo/issues/4171
> fix: Ensure CronWorkflows are persisted once per operation

- workflow/executor/executor.go
fix(executor): Update executor retry config for ExponentialBackoff.
Checklist:
> fix(executor): Update executor retry config for ExponentialBackoff.

- USERS.md
> docs: add Mixpanel to argo/USERS.md

- .github/workflows/docker-image.yml
- docs/releasing.md
…nifest later (#4127)"
This reverts commit c8eed1f23adcdb9dfd99c81e2ba1a053ab27d558.
Checklist:
Fixes #4216
> fix: Revert "chore: try out pre-pushing linux/amd64 images and updating ma… Fixes #4216

- workflow/controller/dag.go
- workflow/controller/steps.go
> fix(controller): reduce withItem/withParams memory usage. Fixes #3907

- workflow/controller/operator.go
- workflow/controller/operator_metrics_test.go
> fix(controller): Apply Workflow default on normal workflow scenario Fixes #4208

- docs/variables.md
The existing YAML example is not formatted correctly. Resulting in it not applying cleanly if used directly.
Checklist:
> docs: Correct formatting of variables example YAML

- workflow/cron/operator.go
> fix(controller): Check the correct object for Cronworkflow reapply error log

- Makefile
- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> fix(ui): Revert bad part of commit

- docs/synchronization.md
> docs: correct a typo

- docs/async-pattern.md
- docs/workflow-of-workflows.md
> docs: Minor formatting fixes

- test/e2e/argo_server_test.go
- test/e2e/cli_test.go
- test/e2e/fixtures/e2e_suite.go
- test/e2e/fixtures/then.go
- test/e2e/fixtures/when.go
- test/e2e/smoke/artifact-passing.yaml
> test: Tidy up E2E tests

- ui/src/app/shared/components/cost-optimisation-nudge.tsx
- ui/src/app/shared/components/nudge.tsx
- ui/src/app/shared/components/security-nudge.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
- ui/src/models/workflows.ts
> feat(ui): Add a nudge for users who have not set their security context. Closes #4233 

- workflow/cron/operator.go
> fix(controller): Fix cron-workflow re-apply error.

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> fix(ui): Ignore missing nodes in DAG. Fixes #4232

- workflow/controller/operator_concurrency_test.go
> fix: TestMutexInDAG failure in master

- examples/README.md
- examples/sidecar-dind.yaml
Compatible with docker in docker 19.03 or above
Checklist:
> docs: Docker TLS env config

- ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
- ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx
- ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx
- ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx
- ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx
Checklist:
#4265 
You can reproduce this issue without `--namespaced` parameter.
> fix(ui): Resolve undefined namespace correctly

- Dockerfile
Checklist:
* [X ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.
> fix(ci): add non-root user to Dockerfile

- docs/variables.md
- workflow/common/util.go
- workflow/common/util_test.go
> feat(controller): Allow whitespace in variable subsitution. Fixes #4286

- workflow/executor/pns/pns.go
- workflow/executor/pns/pns_test.go
> fix(executor): Retrieve containerId from cri-containerd /proc/{pid}/cgroup. Fixes #4302

- docs/configure-artifact-repository.md
> docs: Fix typo in docs for artifact repository

- workflow/cron/controller.go
> chore(controller): Refactor the CronWorkflow schedule logic with sync.Map

- util/util.go
- workflow/controller/operator.go
- workflow/controller/operator_workflow_template_ref_test.go
- workflow/validate/validate.go
- workflow/validate/validate_test.go
> fix: merge artifact arguments from workflow template. Fixes #4296

- cmd/argo/commands/template/lint.go
- test/e2e/cli_test.go
- test/e2e/testdata/workflow-templates/invalid-workflowtemplate.yaml
- test/e2e/testdata/workflow-templates/workflowtemplate.yaml
> fix(cli): Return exit code on Argo template lint command

- workflow/executor/executor.go
- workflow/executor/executor_test.go
> fix(executor): Fix the artifacts option in k8sapi and PNS executor Fixes#4244

- ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
> fix(ui): correct typing errors in workflows-toolbar

- ui/src/app/workflows/components/events-panel.tsx
#4164
Checklist:
* [] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
> fix(ui): correct typing errors in events-panel

- docs/workflow-executors.md
- docs/workflow-pod-security-context.md
> docs: Fix typos (/priviledged/privileged/)

- .github/workflows/ci-build.yaml
- config/config.go
- config/controller.go
- config/controller_test.go
- persist/sqldb/sqldb.go
- server/apiserver/argoserver.go
- server/apiserver/config.go
- test/e2e/fixtures/persistence.go
- workflow/controller/config.go
- workflow/controller/config_test.go
- workflow/controller/controller.go
- workflow/metrics/metrics.go
- workflow/metrics/metrics_test.go
- workflow/metrics/server.go
> refactor: De-couple config

- USERS.md
- docs/fields.md
> docs: Fix a copy-paste typo in the docs

- workflow/controller/operator.go
- workflow/validate/validate.go
Fixes: https://github.com/argoproj/argo/issues/4372
> fix: Fix intstr nil dereference

- workflow/cron/controller.go
Fixes: https://github.com/argoproj/argo/issues/4308
Checklist:
> fix: Use DeletionHandlingMetaNamespaceKeyFunc in cron controller

- docs/events.md
> docs: Fix typo in events.md

- ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx
> fix(ui): correct typing errors in workflow-drawer

- workflow/controller/estimation/estimator.go
- workflow/controller/estimation/estimator_test.go
> fix(controller): Fix estimation of duration for DAGs. Fixes #4386

- ui/src/app/reports/components/reports.tsx
> fix(ui): Ignore running workflows in report. Fixes #4387

- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
> fix(ui): correct log viewer only showing first log line

- ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-list/cluster-workflow-template-list.tsx
- ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-summary-panel.tsx
- ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx
- ui/src/app/shared/components/example-manifests.tsx
- ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx
- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> feat(ui): Sign-post examples and the catalog. Fixes #4360

- workflow/validate/validate.go
- workflow/validate/validate_test.go
> fix(validate): Local parameters should be validated locally. Fixes #4326

- USERS.md
> docs: Add Acquia to USERS.md

- cmd/argo/commands/server.go
- server/apiserver/argoserver.go
- server/static/static.go
Fix: https://github.com/argoproj/argo/issues/3397
Checklist:
> fix(server): Add x-frame config option. Fixes #3397

- workflow/controller/controller.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix(controller): Design-out event errors. Fixes #4364

- test/e2e/fixtures/e2e_suite.go
- test/e2e/fixtures/when.go
> ci: Speed up e2e tests by 25%

- workflow/validate/validate.go
- workflow/validate/validate_test.go
> fix: Fix validation with Argo Variable in activeDeadlineSeconds

- persist/sqldb/workflow_archive.go
- server/workflowarchive/archived_workflow_server.go
- ui/src/app/shared/components/pagination-panel.tsx
Fixes #3775
Signed-off-by: Daniel Herman <dherman@factset.com>
Checklist:
> fix(ui): fix the `all` option in the workflow archive list

- server/auth/gatekeeper.go
- server/auth/mode.go
- server/auth/mode_test.go
Related to https://github.com/argoproj/argo/pull/4412
Checklist:
> fix: Ensure redirect to login when using empty auth token

- workflow/controller/operator_wfdefault_test.go
> fix(test):  fix TestWFDefaultWithWFTAndWf flakiness

- Dockerfile
> build: Reuse IMAGE_OS instead of hard-coded "linux"

- USERS.md
> docs: Add bonprix to Argo users

- USERS.md
- ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> fix: link templates not replacing multiple templates with same name

- Dockerfile
> fix(build): Missing arg lines caused files not to copy into containers

- workflow/controller/controller.go
> fix(controller): Correct default port logic

- docs/cost-optimisation.md
I found it confusing that workflows had to be deleted from the system to reclaim resources. I updated the documentation to help reflect this a little.
> docs: Update cost optimisation  to include information about cleaning up workflows and archiving

- USERS.md
> docs: Added CloudSeeds as one of the users for argo

- test/e2e/stress/many-massive-workflows.yaml
> chore: Updated stress test YAML

- examples/README.md
> docs: fix a typo in example

- ui/package.json
- ui/yarn.lock
> fix(ui): Fix Snyk issues

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> feat(ui): Add links to init and wait logs

- workflow/creator/creator.go
- workflow/creator/creator_test.go
> fix(controller): Deal with hyphen in creator. Fixes #4058

- workflow/sync/sync_manager.go
- workflow/sync/sync_manager_test.go
> fix(controller): Cleanup the synchronize  pending queue once Workflow get deleted

- docs/fields.md
- examples/parameter-aggregation-dag.yaml
- workflow/controller/operator.go
- workflow/controller/operator_test.go
Add tests for https://github.com/argoproj/argo/pull/4374
> test: Add test for aggrgate parameters 

- pkg/apis/workflow/v1alpha1/cron_workflow_types.go
- pkg/apis/workflow/v1alpha1/cron_workflow_types_test.go
- workflow/cron/controller.go
- workflow/cron/operator.go
> fix(controller): Only patch status.active in cron workflows when syncing

- .github/ISSUE_TEMPLATE/config.yml
Signed-off-by: Jesse Suen <Jesse_Suen@intuit.com>
> chore: direct users to ask questions on GitHub discussions

- Makefile
> ci: Pin kustomize version

- manifests/cluster-install/workflow-controller-rbac/workflow-controller-role.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
> fix(controller): Fix the RBAC for leader-election

- workflow/controller/controller.go
> fix(controller): Fixed Leader election name

- manifests/cluster-install/workflow-controller-rbac/workflow-controller-role.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
> fix(controller): Fixed RBAC on leases

- docs/configure-artifact-repository.md
> docs: minor typo fix

- ui/src/app/shared/template-resolution.ts
- ui/src/models/workflows.ts
> fix(ui): Fix UI YAML for in workflows with stored spec. Fixes #4691

- test/e2e/functional_test.go
> test: Fix `TestDeletingRunningPod`. Fixes #4778

- docs/workflow-executors.md
> docs: Clarify PNS security

- workflow/executor/executor.go
> chore: Remove redundant "from" in log message

- .gitignore
- examples/memoize-simple.yaml
- examples/validation_test.go
Checklist:
I'm contributing on my own time, not for any organization.
Fixes https://github.com/argoproj/argo/issues/4626
> fix: Memoize Example (Issue 4626)

- hack/crdgen.sh
- manifests/base/crds/full/argoproj.io_clusterworkflowtemplates.yaml
- manifests/base/crds/full/argoproj.io_cronworkflows.yaml
- manifests/base/crds/full/argoproj.io_workflows.yaml
- manifests/base/crds/full/argoproj.io_workflowtemplates.yaml
- pkg/apis/workflow/v1alpha1/workflow_types.go
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
Checklist:
> fix(crds): Inline WorkflowSteps schema to generate valid OpenAPI spec

- Makefile
- go.mod
- go.sum
- util/util_test.go
- workflow/sync/sync_manager_test.go
> build: Fix lint

- .github/workflows/docker-image.yml
> feat: Publish images to Quay.io

- ui/src/app/events/components/events-details/build-graph.ts
- ui/src/app/sensors/components/sensor-details/sensor-details.tsx
- ui/src/app/sensors/components/sensor-list/sensor-list.tsx
- ui/src/app/sensors/components/sensor-logs-viewer.tsx
- ui/src/app/sensors/components/sensor-logs-window.tsx
- ui/src/app/sensors/components/sensor-side-panel.tsx
- ui/src/app/sensors/components/utils.ts
- ui/src/models/workflows.ts
Signed-off-by: Derek Wang <whynowy@gmail.com>
Checklist:
> feat: Add logs button on detail page and show status icon

- Makefile
> build: sudoless `make codegen -B`

- ui/src/app/shared/components/graph/graph-panel.tsx
> fix(ui): Show non-pod nodes

- test/e2e/manifests/minimal/kustomization.yaml
> build: Inline Argo Events CRD URLs to reduce build errors

- USERS.md
> docs: add Devtron labs to USERS.md

- go.mod
> chore: Remove self-referential replace directive in go.mod

- docs/security.md
- mkdocs.yml
Fixes broken build on master:
https://github.com/argoproj/argo/actions/runs/519570747
> docs: Fix broken docs

- ui/src/app/shared/components/icon.ts
- ui/src/app/shared/components/links.tsx
- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
> fix: Use button in side panel links

- ui/src/app/shared/components/graph/graph-panel.scss
- ui/src/app/shared/components/graph/graph-panel.tsx
Closes #3485.
This is a basic search tool that checks the label of a node. This change also affects the event flow page. Filtering is done in the same way as other filters. Note that the search results are also filtered by other filters.
No search keyword
With keyword "gen"
Display in mobile mode
Event flow page
Checklist:
> feat(ui): Node search tool in UI Workflow viewer

- test/e2e/functional_test.go
> test: Delete TestDeletingRunningPod

- README.md
Add the link to the video that explains Workflows
> docs: Video

- workflow/cron/operator.go
> fix: Skip the Workflow not found error in Concurrency policy

- ui/src/app/shared/components/graph/graph-panel.scss
https://share.getcloudapp.com/WnuBNr2O
> feat: DAG render options panel float through scrolling

- examples/dag-diamond.yaml
- ui/src/app/shared/components/graph/label.test.ts
- ui/src/app/shared/components/graph/label.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/5020
Before: 
After:
> fix: Prefer to break labels by '-' in UI

- USERS.md
> docs: Add Jungle to USERS.md

- workflow/artifacts/artifacts.go
> fix(executor): Fix S3 policy based auth. Fixes #5110

- Makefile
- docs/releasing.md
Closes https://github.com/argoproj/argo-workflows/issues/5034
> chore: Add SHA256 checksums to release

- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
This PR completes the inputs and outputs panel by adding result and exit code.
> feat(ui): Surface result and exit-code outputs

- docs/fields.md
- examples/workflow-template/templates.yaml
> fix: Revert the unwanted change in example 

- USERS.md
> docs: Add DLR to USERS.md

- cmd/argo/commands/archive/delete.go
- cmd/argo/commands/archive/get.go
- cmd/argo/commands/archive/list.go
- cmd/argo/commands/archive/root.go
- cmd/argo/commands/auth/root.go
- cmd/argo/commands/server.go
- cmd/argo/commands/version.go
- docs/cli/argo.md
- docs/cli/argo_archive.md
- docs/cli/argo_archive_delete.md
- docs/cli/argo_archive_get.md
- docs/cli/argo_archive_list.md
- docs/cli/argo_auth.md
- docs/cli/argo_auth_token.md
- docs/cli/argo_server.md
- docs/cli/argo_version.md
> chore: Add missing CLI short docstrings

- docs/metrics.md
Checklist:
* [x ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
> docs: Grafana dashboard link added to metrics.md

- docs/scaling.md
> docs: typo

- docs/workflow-templates.md
> docs: document the WorkflowTemplate workflowMetadata feature

- Dockerfile
- Makefile
> fix(controller): Fix timezone support. Fixes #5181 

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> fix: Consder templateRef when filtering by tag

- workflow/controller/scope.go
- workflow/controller/scope_test.go
Fixes: https://github.com/argoproj/argo-workflows/issues/5169
> fix: Ensure whitespaces is allowed between name and bracket

- ui/src/app/workflows/components/workflows-row/workflows-row.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/5210
> fix: Checkbox is not clickable

- cmd/argo/commands/server.go
- docs/cli/argo_server.md
> chore(server)!: Required authentication by default. Resolves #5206

- cmd/argo/commands/server.go
> chore(server)!: Enable TLS by default. Resolves #5205

- test/e2e/fixtures/e2e_suite.go
- test/e2e/testdata/data-transformation-artifact-repository-ref.yaml
Fixes https://github.com/argoproj/argo-workflows/issues/5222
> fix: Flakey TestDataTransformationArtifactRepositoryRef

- workflow/controller/controller.go
- workflow/cron/controller.go
> feat(controller): Reused existing workflow informer. Resolves #5202

- .github/workflows/ci-build.yaml
> ci: Enable emissary on CI :-o

- .github/workflows/ci-build.yaml
- workflow/executor/pns/pns.go
> fix(executor): Fix concurrency error in PNS executor. Fixes #5250

- Makefile
- ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
> fix: Fixes around archiving workflows

- USERS.md
> docs: Add Onepanel to projects

- ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> fix: Use ScopedLocalStorage instead of direct localStorage

- test/e2e/functional_test.go
- test/e2e/testdata/retry-on-error-workflow.yaml
Trying to get master a bit greener.
> test: Fix tests

- ui/src/app/shared/components/graph/graph-panel.tsx
- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> fix: Minor UI fixes

- workflow/controller/operator_test.go
> fix(test): Flaky TestWorkflowShutdownStrategy 

- cmd/argo/commands/server.go
- cmd/argoexec/commands/root.go
- cmd/workflow-controller/main.go
- docs/cli/argo_server.md
- util/cmd/cmd.go
This option makes the log easier to parse and aggregate by services like Stackdriver, Splunk, and Logstash. 
Checklist:
>  feat: Support structured JSON logging for controller, executor, and server

- Makefile
Fixes https://github.com/argoproj/argo-workflows/issues/5340
> fix: Ensure DEV_BRANCH is correct

- Dockerfile
> fix: Ensure release images are 'clean'

- Makefile
> fix: More Makefile fixes

- mkdocs.yml
> docs: Add data doc to website

- workflow/controller/operator_workflow_template_ref_test.go
> fix(test): TestWorkflowTemplateRefWithShutdownAndSuspend flaky

- docs/security.md
Signed-off-by: Jesse Suen <Jesse_Suen@intuit.com>
> docs: add documentation about network security

- ui/src/app/shared/components/links.tsx
> fix(ui): Fix link button. Fixes #5429

- workflow/controller/operator.go
- workflow/controller/operator_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/5426
> fix: Fix getStepOrDAGTaskName

- server/auth/mode.go
> feat(server): Disable Basic auth if server is not running in client mode

- test/e2e/cron_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/5442
> test: Make cron test suite robust

- manifests/base/workflow-controller/workflow-controller-deployment.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
possibly part of https://github.com/argoproj/argoproj/issues/40
Checklist:
> fix: Run controller as un-privileged

- docs/environment-variables.md
> docs: Add instruction on configuring env vars for controller and executor

- workflow/controller/controller.go
> fix(controller): Enable metrics server on stand-by  controller

- workflow/common/util.go
- workflow/common/util_test.go
> fix: allow mountPaths with traling slash

- USERS.md
> docs: added Intralinks

- USERS.md
> docs: Add Robinhood as user

- USERS.md
> docs: Add ByteDance as user

- README.md
> docs: Add badge to @argoproj Twitter handle

- ui/src/app/shared/components/graph/graph-panel.scss
- ui/src/app/workflows/components/workflow-details/workflow-details.scss
- ui/src/app/workflows/components/workflow-drawer/workflow-drawer.scss
- ui/src/app/workflows/components/workflows-row/workflows-row.tsx
Before(overlapping):
After:
Before(empty scrollbar):
After:
Before(overlapping):
After:
> fix(ui): various ui fixes

- README.md
> docs: Update link to the new CNCF Slack channel

- workflow/executor/resource.go
Fixes https://github.com/argoproj/argo-workflows/issues/5722.
Checklist:
> fix(executor): Remove unnecessary check on resource group

- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- docs/argo-server-sso-argocd.md
- docs/fields.md
- hack/swagger/secondaryswaggergen.go
> chore(url): move edge case paths to /argo-workflows/

- cmd/argo/commands/archive/list.go
- cmd/argo/commands/delete.go
- cmd/argo/commands/list.go
- cmd/argo/commands/stop.go
- cmd/argo/commands/stop_test.go
- cmd/argo/commands/terminate.go
- docs/cli/argo_archive_list.md
- docs/cli/argo_delete.md
- docs/cli/argo_list.md
- docs/cli/argo_stop.md
- docs/cli/argo_terminate.md
- test/e2e/cli_test.go
> feat(cli): Stop workflows by label selector and field selector

- docs/managed-namespace.md
mention that CRD are used and so cluster admin is needed
> docs: Update managed-namespace.md

- hack/free-port.sh
Signed-off-by: Iven Hsu <ivenvd@gmail.com>
Checklist:
> chore: Prevent free-port.sh from killing browsers

- go.mod
- go.sum
- pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.pb.go
- pkg/apiclient/cronworkflow/cron-workflow.pb.go
- pkg/apiclient/event/event.pb.go
- pkg/apiclient/eventsource/eventsource.pb.go
- pkg/apiclient/info/info.pb.go
- pkg/apiclient/sensor/sensor.pb.go
- pkg/apiclient/workflow/workflow.pb.go
- pkg/apiclient/workflowarchive/workflow-archive.pb.go
- pkg/apiclient/workflowtemplate/workflow-template.pb.go
- pkg/apis/workflow/v1alpha1/generated.pb.go
Signed-off-by: NikeNano <niklas.sven.hansson@gmail.com>
Checklist:
Fixes #5605
> fix: upgrade github.com/gogo/protobuf. Fixes #5605

- docs/ide-setup.md
> docs: fix typo

- workflow/util/util.go
Fixes https://github.com/argoproj/argo-workflows/issues/5796.
Checklist:
> fix: Reset workflow started time to current when retrying workflow. Fixes #5796

- docs/variables.md
> fix(docs): Add note about hyphenated variables

- docs/async-pattern.md
> docs: fix typo in async-pattern page

- cmd/argo/commands/resubmit.go
- cmd/argo/commands/resubmit_test.go
- docs/cli/argo_resubmit.md
- test/e2e/cli_test.go
Closes #5584
Closes #3931
This is the last piece of the above tickets.
> feat(cli): resubmit workflows by label and field selector

- docs/empty-dir.md
> docs: Fix emptyDir pattern example. Fixes #5825

- util/file/fileutil.go
- util/file/fileutil_test.go
- workflow/executor/docker/docker.go
> feat: Allow to toggle GZip implementations in docker executor

- cmd/argo/lint/lint.go
- cmd/argo/lint/lint_test.go
> feat(cli): Support input from device files for lint command

- USERS.md
Signed-off-by: Caue Santos <caueasantos@gmail.com>
> docs: Added organization

- util/expr/env/env.go
> fix(controller): Remove un-safe Sprig funcs. Fixes #5286

- workflow/controller/controller_test.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix: Fix active pods count in node pending status with pod deleted.

- .github/workflows/changelog.yaml
- .github/workflows/release.yaml
- .gitignore
- CHANGELOG.md
- Makefile
- hack/changelog.sh
- hack/release-notes.md
Goals:
* Reduce work.
* Reduce mistakes.
* Provide a single place to find change.
Method:
* Make the CHANGELOG.md automated and reproducible.
* Automatically commit it to master when it changes.
How do we fix it when it is wrong?
* Create a `dev-*` branch and let Github Actions update it.
* Make fix on that branch.
> ci: Auto-generate changelog

- workflow/controller/operator.go
- workflow/controller/operator_workflow_template_ref_test.go
> fix(controller): Suspend and Resume is not working in WorkflowTemplateRef scenario

- docs/empty-dir.md
> docs: fixed typo

- docs/widgets.md
fixed spelling
Checklist:
Tips:
> small fixes of spelling mistakes

- docs/CONTRIBUTING.md
> docs: Update code of conduct link.

- docs/workflow-executors.md
Signed-off-by: Maximilian Roos <m@maxroos.com>
Checklist:
Tips:
Currently
> docs: fix indentation

- ui/src/app/shared/services/workflows-service.ts
Fixes #5966
Signed-off-by: Daniel Herman <dherman@factset.com>
> fix(ui): ensure that the artifacts property exists before inspecting it

- cmd/argo/commands/cron/get.go
- cmd/argo/commands/get.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
Checklist:
closes: #5912 #5843 
Tips:
> fix(controller): Empty global output param crashes

- workflow/validate/validate.go
- workflow/validate/validate_dag_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/5993. 
Checklist:
Tips:
> fix(validate): Fix DAG validation on task names when depends/dependencies is not used. Fixes #5993

- docs/workflow-archive.md
> Mention that 'archive' do not support logs of pods

- docs/faq.md
- mkdocs.yml
> docs: Add FAQ

- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
> fix(ui): typo

- docs/running-locally.md
> docs: Update Go version to 1.15 in local dev guide

- USERS.md
> docs: Add VMware to USERS.md

- ui/src/app/shared/components/object-editor/object-editor.tsx
A user had complained the editor was smaller than in v2.12 and harder to use.
This PR:
* Makes the editor a minimum of 600px high. Bigger still on taller monitors.
* Adds "jump" buttons to quickly jump to the cursor to the line of top-level fields, typically "metadata:",  "spec:" or "status:".
> fix(ui): Add editor nav and make taller

- hack/release-notes.md
> docs: Add link to changelog in release notes

- docs/environment-variables.md
> docs: Document default values for the environment variables

- workflow/executor/executor.go
- workflow/executor/executor_test.go
> fix(executor): Improve artifact error messages. Fixes #6070

- docs/environment-variables.md
- workflow/executor/common/common.go
Fixes https://github.com/argoproj/argo-workflows/issues/5943. 
Checklist:
Tips:
> feat(executor): Configurable interval for wait container to check container statuses. Fixes #5943

- docs/upgrading.md
@sarabala1979 I want to pre-empty questions about the Emmissary.
> docs: Update upgrading.md

- docs/upgrading.md
> docs: Document v3.2 upgrading (alpine)

- docs/running-locally.md
Checklist:
* [x ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
Tips:
> add troubleshooting notes section for running-locally docs

- workflow/executor/resource.go
Fixes https://github.com/argoproj/argo-workflows/issues/6118.
Checklist:
Tips:
> fix(executor): Check whether any errors within checkResourceState() are transient. Fixes #6118.

- examples/README.md
See behavior mentionned in https://github.com/argoproj/argo-workflows/issues/6097#issuecomment-856166000
Checklist:
Tips:
> docs: Document the extraction of data from a k8s resource

- Makefile
- docs/stress-testing.md
- hack/capture-pprof.sh
- hack/port-forward.sh
- test/e2e/manifests/stress/argo-server-deployment.yaml
- test/e2e/manifests/stress/kustomization.yaml
- test/e2e/manifests/stress/workflow-controller-configmap.yaml
- test/stress/tool/main.go
> chore: Update stress rig and docs. Fixes #6136

- util/expr/env/env.go
> fix(controller): Performance improvement for Sprig. 

- USERS.md
> docs: Update Graviti's website link

- ui/src/app/shared/utils.ts
> fix(ui): Fix-up local storage namespaces. Fixes #6109

- ui/src/app/event-flow/components/event-flow-details/event-flow-page.scss
> fix(ui): Fix event-flow scrolling. Fixes #6133

- test/e2e/cli_test.go
> test: Fix logging test

- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Closes: https://github.com/argoproj/argo-workflows/issues/6069
Checklist:
Tips:
> feat(ui): Add checkbox to check all workflows in list. Fixes #6069

- workflow/controller/operator.go
> fix(controller): Allow retry on transient errors when validating workflow spec. Fixes #6163

- CHANGELOG.md
- hack/changelog.sh
> docs: Fix changelog order for .0 tags

- USERS.md
> docs: Add KarrotPay in USERS.md

- docs/fields.md
- examples/workflow-count-resourcequota.yaml
- hack/capture-pprof.sh
> docs: Add workflow-count-resourcequota.yaml example

- workflow/executor/emissary/binary.go
> fix(executor): emissary - make argoexec executable from non-root containers. Fixes #6238

- docs/workflow-controller-configmap.yaml
> docs(controller): configmap add emissary executor

- docs/events.md
- Add yaml rendering
- Add bash rendering
Checklist:
Tips:
> docs: Fix code format

- util/kubeconfig/kubeconfig.go
- util/kubeconfig/roundtripper.go
> fix(cli): v3.1 Argo Auth Token

- USERS.md
> docs: Add Alibaba Group to USERS.md
