docs/running-locally.md
=> docs: Update running-locally.md

docs/releasing.md
=> docs: Specify steps to ensure clean state when releasing

workflow/controller/operator.go, workflow/controller/workflowpod_test.go
This reverts commit 64ae33034d30a943dca71b0c5e4ebd97018448bf.
This PR reverts #4492 which changes the way args are passed to a script template. Due to this change we are not able to override `args` with a docker image and an entrypoint with an `exec "$@"` in argo workflow 2.12.x.
This is convenient to execute the docker entrypoint of the base image and then execute the script in the workflow. We use it to do some privileged action and then drop those privileges before executing the script passed in the workflow. You can find more information in #4782 with an example to test the behavior that brokes in 2.12.x.
This revert will obviously break the behavior that the author of this commit has intended to introduce so I don't know if reverting is the best things to do...
Resolves #4782
=> fix(controller): Revert prepending ExecutorScriptSourcePath which brought a breaking change in args handling

workflow/validate/validate.go, workflow/validate/validate_dag_test.go
This PR fixes #2314 . It was closed since I didn't create the PR in time.
Actually a test case for this issue already exists, but the fixture was set up incorrectly such that the test didn't capture this issue.
Tested locally for both artifacts and parameters with the following sample:
```yaml
kind: Workflow
metadata:
generateName: output-parameter-
spec:
entrypoint: abc
templates:
- name: abc
dag:
tasks:
- name: generate-parameter
- name: consume-parameter
template: print-message
dependencies: ["generate-parameter"]
arguments:
parameters:
value: "{{tasks.generate-parameter.outputs.parameters.hello-param}}"
artifacts:
- name: message2
from: "{{tasks.generate-parameter.outputs.artifacts.hello-art}}" …
```
=> fix: Fail DAG templates with variables with invalid dependencies

docs/workflow-executors.md
When using docker as executors, both messages in `stdout` and `stderr` are stored into `outputs.result` since we use `docker logs` to capture the output of a container. I think this is something that is worth being noted since it leads to errors, even for our workflow examples. For instance, [parameter-aggregation](https://github.com/argoproj/argo/blob/master/examples/parameter-aggregation.yaml) fails in step `divide-by-2` when the controller tries to unmarshal the input parameter, `+ echo 2\n2`, which contains the message in `stderr` of the step's ancestor.
Checklist:
=> doc: Add a note for docker executors regarding outputs.result

test/e2e/daemon_pod_test.go, test/e2e/fixtures/when.go, workflow/controller/exec_control.go, workflow/controller/exec_control_test.go
Fixes: https://github.com/argoproj/argo/issues/5002
**Still need testing**
Checklist:
=> fix: Unmark daemoned nodes after stopping them

ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Resolves #5027
Rather than hiding the inputs below the summary, I put them into an inputs tab. Then I realized I wanted to see inputs and outputs at the same time, so I could understand the outputs in the context of the inputs.
=> fix(ui): Display all node inputs/output in one tab. Resolves #5027

examples/ci-output-artifact.yaml, examples/ci.yaml
=> fix(examples): Fix golang build for CI examples

ui/src/app/workflows/components/workflow-details/workflow-details.scss
Currently the DAG graph container overflows into scroll, creating a situation where the main page has a scroll and the DAG graph also has one. See how the node is cut where the DAG's scroll ends:
This fixes that
=> fix: Don't allow graph container to have its own scroll

ui/src/app/workflows/components/workflow-details/workflow-details.tsx
When using `document.location.href = ...` we cause a new page to be loaded. This takes resources and flashes a white blank page to the user, which is bad UX.
By using the page's existing React state infrastructure, we can avoid this page load.
Checklist:
=> fix: Use React state to avoid new page load in Workflow view

config/config.go, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/controller.go
Use case: we need some grace period to allow other services to complete the pod information collection (e.g. log and db persistence), especially during high load where those services have certain amount of delays.
Checklist:
=> feat: Allow to specify grace period for pod GC

pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go
Our use case is to retry only on transient errors but opening this PR to discuss if there's any better approach. 
Checklist:
=> feat(controller): Add retry policy to support retry only on transient errors

docs/environment-variables.md
Currently we have the use of environment variables in many places at different levels but there's no documentation on them. This PR takes an initial stab at documenting them. 
cc @alexec @simster7 
Checklist:
=> docs: Add document for environment variables

api/jsonschema/schema.json, api/openapi-spec/swagger.json, examples/daemon-nginx.yaml, examples/daemon-step.yaml, examples/dag-daemon-task.yaml, examples/dag-disable-failFast.yaml, examples/default-pdb-support.yaml, examples/influxdb-ci.yaml, examples/retry-backoff.yaml, examples/retry-container.yaml, examples/retry-on-error.yaml, examples/retry-script.yaml, examples/retry-with-steps.yaml, hack/swagger/kubeifyswagger.go
Checklist:
I am contributing on my own time.
Fixes https://github.com/argoproj/argo/issues/4817
=> fix: Invalid OpenAPI Spec (Issue 4817)

USERS.md, docs/workflow-controller-configmap.yaml
https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml has invalid config, so change it using following latest config.
https://github.com/argoproj/argo-workflows/blob/a50ddb206cd57a4667a3daa35e37bb9ed80f8cf0/config/config.go#L101-L102
=> docs: Update workflow-controller-configmap workflowRestrictions example doc

docs/environment-variables.md, go.mod, go.sum, util/file/fileutil.go, util/file/fileutil_test.go
For relatively large workflows, using pgzip to parallelize the (de)compression would greatly speed up the (de)hydration process, especially when the size overhead during compression can be neglected.
Checklist:
=> feat: Support pgzip as an alternative (de)compression implementation

.github/workflows/docker-image.yml
Need an engineering or dev build? Push your branch to `origin` with a `dev-` prefix and GitHub will build it for you!
You will need write access to repo for this.
```
git push origin dev-feature
```
=> feat: Build dev-* branches as engineering builds

Makefile
This wasn't an issue earlier and only came up recently when using a different version of golangci-lint since https://github.com/argoproj/argo-workflows/pull/5072 requires a newer version for various linters.
cc @alexec 
Checklist:
=> build: Fix path to golangci-lint binary

ui/src/app/shared/components/filter-drop-down.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx, ui/src/app/workflows/components/workflows-row/workflows-row.tsx
=> fix: Multiple UI fixes

workflow/common/common.go, workflow/controller/operator.go, workflow/executor/executor.go, workflow/executor/resource.go
=> fix: Better message formating for nodes

examples/validator.go
Before (unhelpful):
```
Validation failed - data-transformations.yaml: Must validate one and only one schema (oneOf)
key is required
```
After (helpful):
```
Validation failed - data-transformations.yaml: Must validate one and only one schema (oneOf) in (root)
key is required in (root).spec.templates.1.data.source.artifactPaths.s3
```
=> fix: Specify where in YAML validation error occurred

cmd/argo/commands/server.go, docs/environment-variables.md, docs/tls.md
Before:
```
(⎈ |k3d-k3s-default:argo)➜  argo-workflows git:(tmp) curl -kv https://localhost:2746/workflows --tls-max 1.1
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 2746 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
CApath: none
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS handshake, Server hello (2):
* TLSv1.1 (IN), TLS handshake, Certificate (11):
* TLSv1.1 (IN), TLS handshake, Server key exchange (12):
* TLSv1.1 (IN), TLS handshake, Server finished (14):
* TLSv1.1 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.1 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.1 (OUT), TLS handshake, Finished (20):
* TLSv1.1 (IN), TLS change cipher, …
```
=> feat(server): Enforce TLS >= v1.2

ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx, ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx, ui/src/app/event-flow/components/event-flow-details/event-flow-page.tsx, ui/src/app/event-sources/components/event-source-details/event-source-details.tsx, ui/src/app/event-sources/components/event-source-list/event-source-list.tsx, ui/src/app/sensors/components/sensor-details/sensor-details.tsx, ui/src/app/sensors/components/sensor-list/sensor-list.tsx, ui/src/app/shared/use-query-params.ts, ui/src/app/workflow-event-bindings/components/workflow-event-bindings/workflow-event-bindings.tsx, ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/5186
The react `useState` takes as parameter only an initial value. Once the hooks are created, if the value passed in to `useState` changes it has no effect on the state of the hooks.
> During the initial render, the returned state (state) is the same as the value passed as the first argument (initialState).
>
> The setState function is used to update the state. It accepts a new state value and enqueues a re-render of the component.
https://reactjs.org/docs/hooks-reference.html#usestate
Since the only way the react state reads the query parameters is as an argument to `useState`, if we change the URL without changing the react state, the change will not propagate to down to the react state. With this change, we use an effect on the …
=> fix: Propagate URL changes to react state

examples/README.md, examples/retry-on-error.yaml
Document the new retry policy introduced in https://github.com/argoproj/argo-workflows/pull/4999. This was brought up in https://github.com/argoproj/argo-workflows/issues/4493#issuecomment-785614925. 
Checklist:
=> docs: Document the new OnTransientError retry policy

docs/workflow-controller-configmap.md
If you create your own configmap for workflow-controller you have to also specify it to argo-server.
Checklist:
=> docs: workflow-controller-configmap.md entry about argo-server.

workflow/controller/controller.go
When running multiple controllers within the same namespace if they share the lease lock name one of the will fail to start due to the metrics server not coming up and so the health check fails. Having unique names based off the LEADER_ELECTION_IDENTITY env variable should fix this and allow leaders election to work with multiple controllers in the same namespace.
Checklist:
=> fix(controller): Leader Lease Shared Name

ui/src/app/shared/components/pagination-panel.tsx
=> fix: Do not display pagination warning when there is no pagination

docs/environment-variables.md, workflow/controller/controller.go
One of our large clusters were under high load the other day and the current lease/leader configuration needs to be adjusted to avoid frequent leader election and reduce etcd’s pressure under such load. Otherwise, the etcd server would not be able to handle too many requests and fail with error like `Failed to update lock: etcdserver: too many requests`, which leads to periodically restart of the controller.
This PR exposes relevant configurations via environment variables.
Checklist:
=> feat(controller): Allow to modify time related configurations in leader election

community/README.md
This page is the 1st result when searching for Argo community meetings but there isn't a link! Adding one here.
Checklist:
=> docs: Add link to community calendar

docs/fields.md, examples/pod-gc-strategy-with-label-selector.yaml, examples/pod-gc-strategy.yaml
This documents the new `podGC.labelSelector` introduced in https://github.com/argoproj/argo-workflows/pull/5090. I added a new example instead of reusing the existing `examples/pod-gc-strategy.yaml` since it will likely overwhelm new users.
Checklist:
=> docs: Add example on using label selector in pod GC

pkg/apis/workflow/v1alpha1/item.go, pkg/apis/workflow/v1alpha1/item_test.go
=> fix(controller): Work-around Golang flaw. Fixes #5192

workflow/controller/pod/significant.go, workflow/controller/pod/significant_test.go
For pod GC strategy with label selector as implemented in https://github.com/argoproj/argo-workflows/pull/5090, the completed pods may not be added to `woc.completedPods` when the completed pods do not match with the given label selector during pod reconciliation. 
For example, depending on the infra setup, the completed pods might be only marked with certain labels after we've done collecting all the meta information from those completed pods, which means we would miss that earlier pod reconciliation. Once we miss that earlier pod reconciliation loop, there aren't other changes besides the additional labels so `SignificantPodChange()` always returns `false`. 
This PR makes sure that we take the labels change into account. We cannot use `ALL_POD_CHANGES_SIGNIFICANT` because that would …
=> fix(controller): Take labels change into account in SignificantPodChange()

workflow/artifactrepositories/artifactrepositories.go
Key and ref are incorrectly swapped. Also added quotes around key so the error message is easier to read.
Checklist:
=> fix: Fix swapped artifact repository key and ref in error message

workflow/artifacts/oss/oss.go
This is to support data sourcing and transformation with the `data` template implemented in https://github.com/argoproj/argo-workflows/pull/4958. 
cc @simster7 @alexec 
Checklist:
=> feat: Support ListObjects() for Alibaba OSS artifact driver

workflow/artifacts/oss/oss.go
The current implementation is incorrect and will trigger ListBuckets permission error. This PR switches to use `bucket.ListObjects()` so only the permission for listing objects in a particular bucket is required.
Checklist:
=> fix: Use bucket.ListObjects() for OSS ListObjects() implementation

workflow/artifacts/oss/oss.go
Currently if we miss a trailing slash in the OSS key when the object is a directory, we'll get `oss: service returned error: StatusCode=404, ErrorCode=NoSuchKey, ErrorMessage="The specified key does not exist"`, which is pretty misleading and takes a while for new users to debug. 
Note that I am following the existing retry mechanism. Even though it's not ideal but it's consistent with existing behavior. The retry mechanism and error catalog will probably be improved separately in https://github.com/argoproj/argo-workflows/issues/5220. 
Checklist:
=> feat: Improve OSS artifact driver usability when load/save directories 

ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
=> feat: Track nodeView tab in URL

Makefile, server/static/files.go.stub
=> fix: Makefile target

docs/environment-variables.md, workflow/executor/executor.go
It would be good to allow these to be configurable. I've seen several people from the community forking the repo and change these settings manually to accommodate their environments.
Checklist:
=> feat(executor): Configurable retry backoff settings for workflow executor

workflow/controller/operator.go
=> fix(controller): Backward compatible workflowTemplateRef from 2.11.x to  2.12.x

workflow/validate/validate.go, workflow/validate/validate_test.go
Fixes: https://github.com/argoproj/argo-workflows/issues/5318
Checklist:
=> fix: Disallow object names with more than 63 chars

workflow/artifacts/oss/oss.go, workflow/artifacts/oss/oss_test.go
This is related to https://github.com/argoproj/argo-workflows/issues/5220 but with a focus on OSS artifact driver.
Checklist:
=> fix: Only retry on transient errors for OSS artifact driver

docs/README.md
I noticed that on the Argo Workflows Docs site, there is no explanation about what Argo Workflows is or why you might want to use it on the first page.  I pretty much copied and pasted the content from the README to start with, and we can iterate on it from there.
=> docs: copy information about what is argo to the docs landing page

workflow/executor/resource.go, workflow/executor/resource_test.go
=> fix(executor): Fix resource patch when not providing flags. Fixes #5310

go.sum, server/event/dispatch/operation.go
This allows you to do this in your WorkflowEventBinding:
```yaml
spec:
event:
selector: ...
submit:
metadata:
name: 'payload.repository.slug + "-" + sprig.trunc(8, payload.changes[0].toHash)'
```
Signed-off-by: Stephan van Maris <s.vanmaris@e-village.nl>
Checklist:
=> feat: Add helper functions to expr when parsing metadata. Fixes #5351

workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Signed-off-by: Peixuan Ding <dingpeixuan911@gmail.com>
When submitting a WF with an invalid PodSpecPatch:
```yaml
kind: Workflow
metadata:
generateName: pod-spec-patch-
spec:
templates:
podSpecPatch: '{"container"}'
container:
args: ["hello world"]
```
The error message incorrectly states `Fail to marshal the Pod spec`. I believe this is a mistake. This PR fixes it.
Also changed a bunch of `Fail to` to `Failed to` in order to be more consistent with other error messages.
=> fix(controller): Fixed wrong error message

workflow/util/util.go
Currently `StopWorkflow()` replies on a for loop and only resilient to `apierr.IsConflict` errors. This PR does a small refactoring and allows `StopWorkflow()` to account for other transient errors similar to `TerminateWorkflow`.
Checklist:
=> feat: Allow transient errors in StopWorkflow()

workflow/validate/validate.go, workflow/validate/validate_test.go
CronWorkflows have fewer max chars allowed in their name because when workflows are created from them, they are appended with the unix timestamp (`-1615836720`). This lower character allowance allows for that timestamp to still fit within the 63 character maximum.
=> fix: Do not allow cron workflow names with more than 52 chars

workflow/controller/controller_test.go
fixes #5366
Checklist:
Based on failed. it couldn't find the pods to delete. I updated 'workflowname`  so it will create pod with name.
```log
time="2021-03-16T15:14:37Z" level=info msg="Updated message  -> Stopped with strategy 'Terminate'" namespace=default workflow=
2462
time="2021-03-16T15:14:37Z" level=info msg="Marking workflow completed" namespace=default workflow=
2463
time="2021-03-16T15:14:37Z" level=info msg="Checking daemoned children of " namespace=default workflow=
2464
time="2021-03-16T15:14:37Z" level=info msg="Workflow update successful" namespace=default phase=Failed resourceVersion= workflow=
2465
time="2021-03-16T15:14:37Z" level=info msg="Processing workflow" namespace=default workflow=
2466 …
```
=> fix(test): Fix TestWorkflowTemplateRefWithShutdownAndSuspend flakyness

util/logs/log-k8s-requests.go, workflow/executor/k8sapi/client.go
Fixes https://github.com/argoproj/argo-workflows/issues/5371. 
The log would look like the following instead of `"Watch pods 403"` after this change:
```
time="2021-03-11T22:49:01.704Z" level=info msg="Watch pods 403 {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods \\\"resubmit-5dnvx-1087928915\\\" is forbidden: User \\\"system:serviceaccount:argo:default\\\" cannot watch resource \\\"pods\\\" in API group \\\"\\\" in the namespace \\\"argo\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"resubmit-5dnvx-1087928915\",\"kind\":\"pods\"},\"code\":403}\n"
```
Checklist:
=> fix(executor): Surface error when wait container fails to establish pod watch

workflow/common/parse.go, workflow/common/util_test.go
Instead of seeing a nil pointer panic (e.g. in https://github.com/argoproj/argo-workflows/issues/5422), we should avoid appending results that are nil (which is not what `SplitWorkflowYAMLFile()` expects from each parse result) so the error message would be more readable. Example output after this change:
```
dist/argo submit -n argo --watch https://github.com/argoproj/argo-workflows/blob/master/examples/volumes-pvc.yaml --serviceaccount argo
INFO[2021-03-16T23:34:30.665Z] No Workflow found in given files
```
There are obviously multiple ways to fix this so I am open to suggestions on the best way.
Checklist:
=> fix(cli): Only append parse result when not nil to avoid panic

workflow/controller/operator_workflow_template_ref_test.go
Checklist:
Based on the log the Last testcase didn't create POD because the previous testcase POD was in the process of deleting.  Add workflow name for each testcase so it will create a new POD name for each testcase
```
time="2021-03-17T23:22:51Z" level=info msg="Processing workflow" namespace=default workflow=workflow-template-hello-world
2446
time="2021-03-17T23:22:51Z" level=info msg="Updated phase  -> Running" namespace=default workflow=workflow-template-hello-world
2447
time="2021-03-17T23:22:51Z" level=info msg="Pod node workflow-template-hello-world initialized Pending" namespace=default workflow=workflow-template-hello-world
2448
time="2021-03-17T23:22:51Z" level=info msg="Created pod: …
```
=> fix(test): TestWorkflowTemplateRefWithShutdownAndSuspend flakiness

ui/src/app/archived-workflows/components/archived-workflow-filters/archived-workflow-filters.tsx, ui/src/app/shared/components/checkbox-filter/checkbox-filter.scss, ui/src/app/workflows/components/workflow-filters/workflow-filters.scss, ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Before:
After:
Fixes https://github.com/argoproj/argo-workflows/issues/5443
=> fix: Various UI fixes

manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/base/workflow-role.yaml
These are required to run the memoization example: https://github.com/argoproj/argo-workflows/blob/master/examples/memoize-simple.yaml
```
time="2021-03-18T14:11:42.810Z" level=info msg="Saving ConfigMap cache entry" key=test-5 name=my-config namespace=argo nodeId=memoized-simple-workflow-6mftb
time="2021-03-18T14:11:42.814Z" level=info msg="Create configmaps 403"
time="2021-03-18T14:11:42.814Z" level=error msg="Failed to save node outputs to cache" error="could not save to config map cache: configmaps is forbidden: User \"system:serviceaccount:argo:argo\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"argo\"" namespace=argo nodeID=memoized-simple-workflow-6mftb workflow=memoized-simple-workflow-6mftb
time="2021-03-18T14:31:01.181Z" level=info msg="Update …
```
=> fix(controller): Add permissions to create/update configmaps for memoization in quick-start manifests

workflow/cron/controller.go
=> chore: Remove unused work queue in Cron controller

docs/workflow-templates.md
Improved the document of `WorkflowTemplate`, by 
- Fixed the type `The submit ...` to `Then submit ...`
- Added example of submitting a `Workflow` from the existing `WorkflowTemplate`, because most of the `WorkflowTemplate` should have parameters
Checklist:
=> docs: fixed the typo, `The submit ...` doesn't make sense

workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/5473.
Checklist:
=> fix(controller): Only set global parameters after workflow validation succeeded to avoid panics

workflow/controller/operator.go, workflow/controller/operator_concurrency_test.go, workflow/controller/operator_test.go
Fixes: https://github.com/argoproj/argo-workflows/issues/5481
Checklist:
=> fix(controller): Fix workflows with retryStrategy left Running after completion

ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/login/components/login.tsx, ui/src/app/shared/components/object-editor/object-editor.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Fixes #5496 
Fixes https://github.com/argoproj/argo-workflows/issues/5494
=> fix(ui): Multiple UI fixes

docs/windows.md
fixes #5376
Review please @lippertmarkus :)
Checklist:
=> docs: add limitation about windows versions

Dockerfile
Before making this fix, I kept getting `level=fatal msg="open argo-server.key: permission denied"` on OpenShift. 
After making this fix, I've been able to successfully deploy argo-server.
Signed-off-by: Shoubhik Bose <shbose@redhat.com>
Checklist:
=> fix: certs in non-root

cmd/workflow-controller/main.go, config/controller.go, workflow/controller/controller.go, workflow/cron/controller.go, workflow/metrics/server.go, workflow/sync/sync_manager.go
=> chore: Handling panic in go routines

util/errors/errors.go
While investigating stability issues we discovered that Argo wasn't retrying various failing k8s api calls. We didn't really understand what was going on until we deployed an experimental Argo build containing additional logging. 
Therefore we propose make the root cause of failures more obvious and indicate if an error is considered to be transient or not.
Checklist:
=> fix: Add logging to aid troubleshooting

Dockerfile
* Using short names is subject to the risk of hitting squatted registry namespaces
* If a user's configuration is set to pull images from somewhere other then Dockerhub, the user may unknowingly pull a malicious image.
possibly part of https://github.com/argoproj/argoproj/issues/40
Signed-off-by: Shoubhik Bose <shbose@redhat.com>
Checklist:
=> fix: avoid short names in Dockerfiles

api/jsonschema/schema.json, api/openapi-spec/swagger.json, hack/swaggify.sh, ui/src/app/event-sources/components/event-source-editor.tsx, ui/src/app/sensors/components/sensor-editor.tsx, ui/src/app/shared/components/object-editor/object-editor.tsx
Screenshot of the error notice:
=> fix(ui): Correct Argo Events swagger

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, workflow/common/util.go, workflow/controller/controller_test.go, workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/steps.go
Split from https://github.com/argoproj/argo-workflows/pull/5478
=> fix(controller): Use node.Name instead of node.DisplayName for onExit nodes

manifests/base/argo-server/argo-server-deployment.yaml, manifests/base/workflow-controller/workflow-controller-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
- Using short names is subject to the risk of hitting squatted registry namespaces
- If a user's configuration is set to pull images from somewhere other then Dockerhub, the user may unknowingly pull a malicious image.
possibly part of https://github.com/argoproj/argoproj/issues/40
Signed-off-by: Shoubhik Bose <shbose@redhat.com>
Checklist:
=> fix: avoid short names in deployment manifests

docs/variables.md
=> fix: Spelling Mistake

USERS.md
Fulfilling my obligation to check all tick boxes at https://github.com/argoproj/argo-workflows/pull/5521
=> docs: Add Softonic as user

cmd/argo/commands/server.go, cmd/argo/commands/server_test.go
=> fix: Default to insecure mode when no certs are present

workflow/common/common.go, workflow/controller/cache/cache.go, workflow/controller/cache/configmap_cache.go, workflow/controller/cache_test.go
This is the first step mentioned in https://github.com/argoproj/argo-workflows/issues/5406. 
Controller to manage GC of configmaps based on this timestamp will be added as a follow-up PR later as it requires additional work. We can start using this timestamp in our cluster and experiment with different options in the meantime (hopefully gather more experience and feedback on GC strategies through the process). **Our immediate need is to have a better way to tell whether a cache is still useful.**
cc @simster7 Could you take a look when you get a chance?
Checklist:
=> feat(controller): Add last hit timestamp to memoization caches

cmd/argo/commands/server_test.go, cmd/argo/lint/lint_test.go, cmd/argoexec/commands/emissary.go, cmd/argoexec/commands/emissary_test.go, examples/example-golang/main.go, examples/validation_test.go, examples/validator.go, hack/crds.go, hack/docgen.go, hack/parse_examples.go, hack/swagger/secondaryswaggergen.go, server/artifacts/artifact_server_test.go, server/auth/serviceaccount/claims_test.go, test/e2e/cli_test.go, util/archive/archive_test.go, util/file/fileutil_test.go, util/util.go, workflow/artifacts/gcs/gcs.go, workflow/artifacts/git/git.go, workflow/artifacts/git/git_test.go, workflow/artifacts/hdfs/hdfs.go, workflow/executor/common/common.go, workflow/executor/emissary/binary.go, workflow/executor/emissary/emissary.go, workflow/executor/executor.go, workflow/executor/executor_test.go, workflow/util/util_test.go
=> chore: Lint master

USERS.md
=> docs: Add Zhihu as user

Makefile
=> fix: Build static files in engineering builds

workflow/controller/workflowpod.go
To test this,lets merge it and make sure https://workflows.apps.argoproj.io/ can run coin flip
=> fix(executor): GODEBUG=x509ignoreCN=0

workflow/common/common.go, workflow/controller/cache/configmap_cache.go, workflow/controller/cache_test.go
Timestamps contain invalid characters and not suitable as labels, which fails to save caches with the following error:
```
time="2021-03-27T03:39:05.545Z" level=error msg="Failed to save node outputs to cache" error="error creating cache entry: ConfigMap \"my-config\" is invalid: metadata.labels: Invalid value: \"2021-03-27T03:39:05Z\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" namespace=argo nodeID=memoized-simple-workflow-7zkx9 workflow=memoized-simple-workflow-7zkx9
```
This PR removes this label introduced in …
=> fix: Remove invalid label for last hit timestamp from caches

persist/sqldb/workflow_archive.go
=> fix(controller): clean up before insert into argo_archived_workflows_labels

cmd/argo/commands/server.go, server/apiserver/argoserver.go
=> fix: Switch InsecureSkipVerify to true

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/5574
=> fix(controller): Consider nested expanded task in reference

workflow/artifacts/git/git.go, workflow/artifacts/git/git_test.go
=> fix: parse username from git url when using SSH key auth

ui/src/app/shared/components/graph/graph-panel.scss, ui/src/app/workflows/components/workflow-details/workflow-details.scss, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.scss
let workflow dag and node info scroll independently
so that users don't need to scroll back and forth when trying to view details from different template
before:
after:
Checklist:
=> feat(ui): let workflow dag and node info scroll independently

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix(controller): Workflow hangs indefinitely during ContainerCreating if the Pod or Node unexpectedly dies

cmd/argo/commands/get.go, cmd/argo/commands/get_test.go, docs/cli/argo_get.md
Closes #3090
Adds `short` option to `-o` flag to `argo get` command:
```
$: ./argo get hello-world-44bzs -o short
STEP                  TEMPLATE  PODNAME            DURATION  MESSAGE            NODENAME
◷ hello-world-44bzs  whalesay  hello-world-44bzs  1m        ContainerCreating  microk8s-vm
```
=> add -o short option for argo cli get command

docs/quick-start.md
on my machine it runs over https
Checklist:
=> docs: server runs over https

cmd/argo/commands/client/conn.go, cmd/argo/commands/server.go, cmd/argoexec/commands/root.go, cmd/workflow-controller/main.go
=> feat: Identifiable user agents in various Argo commands

workflow/artifacts/oss/oss.go
=> fix: Surface error during wait timeout for OSS artifact driver API calls

cmd/argoexec/commands/root.go
=> chore: Correctly log version string and remove unnecessary error check

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/5600
=> fix: Make task/step name extractor robust

docs/argo-server-sso-argocd.md, docs/argo-server-sso.md, docs/argo-server.md, mkdocs.yml
A redo of #5535, which adds some more info around how secrets should be set, and Kubernetes manifests as examples for those who don't deploy with Helm.
Checklist:
=> docs: manifests for SSO using ArgoCD Dex, to be used with Kustomize

workflow/artifacts/s3/error_codes.go, workflow/artifacts/s3/errors.go, workflow/artifacts/s3/errors_test.go, workflow/artifacts/s3/s3.go, workflow/artifacts/s3/s3_test.go
Closes #5220 
Hi,
This PR fixes the issue of executor retrying non-transient S3 errors.
I took the list of retryable errors from [the minio-go repo](https://github.com/minio/minio-go/blob/92fe50d14294782d96402deb861d442992038109/retry.go#L90-L102).
As of today, this package doesn't have any unit tests. As the logic is getting more complex it's kind of risky to have no tests. I'll see if I can add some. (Might need some minor refactoring)
Thanks!
=> fix(artifacts): only retry on transient S3 errors

cmd/argoexec/commands/wait.go, workflow/executor/executor.go
=> fix(executor):Failure node failed to get archived log

workflow/artifacts/git/git.go, workflow/artifacts/git/git_test.go
- Fixes Issue 5629.
Checklist:
=> fix: git clone on non-default branch fails (Fixes #5629)

workflow/controller/operator.go
This link is now located under sig-architecture: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
Checklist:
=> chore: Update link to k8s API conventions

api/jsonschema/schema.json, api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/info.go, pkg/apis/workflow/v1alpha1/openapi_generated.go, ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx, ui/src/app/shared/components/links.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
=> feat(ui): support any yaml reference in link

ui/src/app/userinfo/components/cli-help.tsx
=> fix(ui): strip inner quotes from argoToken

docs/cron-workflows.md
=> docs(cron): add dst description

workflow/executor/resource.go
In the current implementation, `strings.Contains(jsonString, "NotFound")` block would never be reached since the error would be returned immediately if it's not transient. Also switched to use `apierr.IsNotFound(err)` which is more robust than string matching.
Checklist:
=> fix(executor): Correctly surface error when resource is deleted during status checking

docs/tls.md
=> docs(tls): 3.0 defaults to tls enabled

README.md
I discussed with @alexmt and he's going to reuse the existing link with instructions to join the CNCF workspace and channels. See https://github.com/argoproj/argo-cd/pull/6044#discussion_r614325390 for more context. Reverting previous change.
This reverts commit eab122bba07b8907ee4ab6b1d8d72dcf0adc17fa.
Checklist:
=> docs: Revert "docs: Update link to the new CNCF Slack channel (#5681)"

Dockerfile
Needed for the `mount` option on some build system (e.g. ours).
=> build: Specify Dockerfile version

workflow/artifactrepositories/artifactrepositories.go, workflow/artifactrepositories/artifactrepositories_test.go
=> fix(controller): Correct bug for repository ref without default key. Fixes #5646

workflow/controller/operator.go
I am not sure if this is the intended behavior but currently cache is saved regardless of node's status, which is not useful and counter-intuitive to our users. 
For example, a failed node may have no output like `{"nodeID":"memoized-simple-workflow-fzvkz","outputs":null,"creationTimestamp":"2021-04-19T13:17:28Z"}` and then if a new template retrieves the cache, it will become successful and subsequent steps would fail due to the lack of outputs from the previous step.
Let me know if this currently behavior is indeed desired. Then we probably need to introduce a toggle for this. We have no use case to save cache for unsuccessful nodes.
Checklist:
=> fix: Only save memoization cache when node succeeded

docs/argo-server-sso.md
I am working to setup an installation with a built out rbac scheme to allow one server and controller to let multiple users create workflows in various other namespaces. It took me longer than it should have to get it working and I believe these notes would help others.
Checklist:
=> docs: Added clarifying points for multi-namespace usage

ui/src/app/workflows/components/workflows-row/workflows-row.tsx
The table header and content don't seem to be aligned. #5678 changed the header width but not the content width.
| Before                                                                                                                                        	| After                                                                                                                                         	|
|-----------------------------------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------------------------------	|
| ![Screen Shot 2021-04-21 at 8 22 01 PM](https://user-images.githubusercontent.com/1311594/115638026-8 …
=> fix(ui): Fix workflow list table column width mismatch

server/apiserver/argoserver.go, server/artifacts/artifact_server.go, server/artifacts/artifact_server_test.go, ui/src/app/shared/services/workflows-service.ts, ui/src/app/webpack.config.js, ui/src/app/workflows/components/workflow-artifacts.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
=> fix(server): Fix the issue where GetArtifact didn't look for input artifacts

ui/src/app/userinfo/components/cli-help.tsx
Checklist:
Unfortunately my last PR #5677 still has a little bug in the regular expression. The auth token we get from the cookie is sometimes wrapped by quotes (`"`) and sometimes it is not. Therefore the regex wraps the matched token with optional quotes (`"?(.*)"?`). This regex matches`"token"` such as `token`. The problem is the first case (`"token"`). In this case the captured bit inside the parentheses would also match the second quote (`token"`) because the part inside the parentheses (`(.*)`) matches all characters greedily. This can be fixed by matching lazily (`.*?`) as proposed in the Merge request.
Sorry for this - I guess the screenshot testing was not successful. Nevertheless here's more screenshots of the running system before and after my fix:
before:
after:
=> fix(ui): Fix greediness in regex for auth token replacement

docs/events.md
Corroborated by expr docs and one person's test in the CNCF Slack.
Checklist:
=> chore: Fix expr array equality operator

ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.scss, ui/src/app/workflows/components/workflow-details/workflow-details.tsx
I noticed that the workflow summary page is not scrollable. There is no way to scroll down and view the whole workflow manifest. This PR fixes it by wrapping the `argo-container` with a scrollable container.
| Before                                                                                                                                         	| After                                                                                                                 	|
|------------------------------------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
| ![Screen Shot 2021-04-22 at 11 34 20 …
=> fix(ui): Fix workflow summary page unscrollable issue

USERS.md, ui/src/app/app-router.tsx, ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx, ui/src/app/cron-workflows/components/cron-workflow-creator.tsx, ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/event-flow/components/event-flow-details/event-flow-page.tsx, ui/src/app/event-sources/components/event-source-creator.tsx, ui/src/app/event-sources/components/event-source-list/event-source-list.tsx, ui/src/app/reports/components/reports.tsx, ui/src/app/sensors/components/sensor-creator.tsx, ui/src/app/sensors/components/sensor-list/sensor-list.tsx, ui/src/app/shared/utils.ts, ui/src/app/workflow-event-bindings/components/workflow-event-bindings/workflow-event-bindings.tsx, ui/src/app/workflow-templates/components/workflow-template-creator.tsx, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx, ui/src/app/workflows/components/workflow-creator.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
addresses https://github.com/argoproj/argo-workflows/issues/5577
In older versions of Argo, running the server with a managed namespace prevented you from being able to browse to other namespaces within the UI. This ability was lost in V3, such that you could manually change the URL to attempt to view resources in other namespaces. Additionally, in the older versions, Simply browsing to "/workflows" would show you workflows in the managed namespace, so the users did not even really need to be aware of where their workflows were running at all.
It seems like this behavior is still INTENDED in v3, given code in the [namespace filter](https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/shared/components/namespace-filter.tsx#L6) and in the [app …
=> fix(ui): Remove the ability to change namespaces via the UI in Managed Namespace Mode. Closes #5577

ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
#5498 Fixed the labels not being remembered issue. However, when the user switched from an earlier version of Argo to the latest, the UI crashes because `selectedLabels` was not previously stored in the localStroage.
To reproduce:
1. Clear localStorage
1. Checkout a version before #5498 4eb351cbaf82bbee5903b91b4ef094190e1e0134 (e.g. dfe6ceb430d2bd7c13987624105450a0994e08fc)
1. Play Argo UI for a bit, then switch back to the latest master commit
1. UI crashes now
This will give an unpleasant user experience when they upgrade Argo version. This PR fixes the crashing issue by simply adding some checks.
/cc @simster7
=> fix(ui): Fix the UI crashing issue

ui/src/app/workflows/components/workflow-node-info/workflow-node-info.scss
The UI currently has a strange flickering issue on Chrome 90.0.4430.93
The issue is introduced because the container `workflow-node-info` is not long enough. Whenever the dropdown is triggered, it overflows the container, having scroll bar to appear. The scroll bar then squeezes the width of the container.
I propose a simple fix to set the height of `workflow-node-info` to full screen, so that dropdown won't overflow the container anymore.
Before & after:
| Before                                                                                                                             	| After                                                                                                                             	|
|---------------------------------------------------------------------- …
=> fix(ui): Fix an UI dropdown flickering issue

docs/workflow-events.md, test/e2e/functional_test.go, workflow/controller/controller_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
This pull request adds a `Running` event to WorkflowNode execution, outlined in https://github.com/argoproj/argo-workflows/issues/5320.
Besides the updated unit and functional tests, I ran this change locally with Argo Events installed and a sensor and trigger set up to deliver webhooks to another locally-running server.
Below is a running log of my testing steps as I iterated on this change. Discrete thoughts/iterations are separated by a horizontal line.
------------
Running [the hello-world example](https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml), I have so far not seen any `WorkflowNodeRunning` event anywhere. I'm not sure why this is the case, but I will continue to look and see what I am …
=> feat: Emit WorkflowNodeRunning Event

util/errors/errors.go
fixes #5769   : change the log level to warn level
Signed-off-by: Ryan Lo <lowc1012@gmail.com>
Checklist:
=> fix: change log level to warn level

pkg/apis/workflow/v1alpha1/generated.pb.go
CI on master branch is failing.
The reason is that #5780 upgraded the protobuf version and #5731 needs protobuf regenerated.
=> build: fix codegen failure on master branch

workflow/controller/operator.go, workflow/util/util.go, workflow/util/util_test.go
=> Fix: Node set updating global output parameter updates global. #5699

cmd/argo/commands/retry.go, cmd/argo/commands/retry_test.go, docs/cli/argo_retry.md
Part of #3931 and #5584.
This is very similar to #5752
| By Label                                                                                                                                      	| By Field                                                                                                                                      	|
|-----------------------------------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------------------------------	|
| ![Screen Shot 2021-05-03 at 1 33 22 AM](https://user-images.githubusercontent.com/1311594/116844009-c94faa80-abaf-11eb-944d-33c453d32d42.png) 	| ![Screen Shot …
=> feat(cli): Retry workflows by label selector and field selector

workflow/controller/operator.go
Before: `unable to parse 3ss as a duration`
After: `unable to parse 3ss as a duration time: unknown unit "ss" in duration "3ss"`
Checklist:
=> chore: Surface parse duration error in operator

docs/node-field-selector.md
Signed-off-by: softwarebloat <nico.lino1991@gmail.com>
Checklist:
=> docs: wrong parent name of 'wait-approval' step

ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx
Signed-off-by: Nick Palumbo <npalumbo8@bloomberg.net>
Checklist:
=> fix(ui): dont show cluster workflows in namespaced mode. Closes #5841

workflow/util/util.go, workflow/util/util_test.go
Previous PR #5798 fixed the case for workflow-level `activeDeadlineSeconds` but template-level `Timeout` still does not work as expected when retrying the workflow since the `StartedAt` for each node has not been reset to current time. Failed nodes would get error `Template xxx exceeded its deadline` instantly when getting retried if they previously exceeded the timeout. 
Related issue https://github.com/argoproj/argo-workflows/issues/5796.
Checklist:
=> fix: Reset started time for each node to current when retrying workflow

docs/environment-variables.md, workflow/controller/indexes/workflow_index.go, workflow/cron/controller.go
@sarabala1979 further analysis confirmed what I thought:
* `util.FromUnstructured` is expensive, especially when called in a loop.
* 7x CPU increase was only on one of the 7 clusters. 
* Other clusters did increase, but by only about 1.2x
* v2.12 introduced `syncAll` which call `FromUnstructured` in a loop every 10s. I hope we can change the 10s to 60s. @simster7 ?
* `WorkflowSemaphoreKeysIndexFunc` did increase CPU usage on two clusters. We can disable it on one cluster to test to see if it is a cause.
=> feat(controller): Add config for potential CPU hogs

Dockerfile.windows
Allows to configure the windows version used for argoexec (see #5376). This allows us to easily build a version of the argoexec docker image without the need to adjust the Dockerfile itself (instead just pass `--build-arg IMAGE_OS_VERSION=1909`). 
Fixes #5546 (rebased PR on current master)
The `IMAGE_OS` and `IMAGE_ARCH` build args were unused and hence I removed them. 
possibly @lippertmarkus to review? :) 
Checklist:
=> feat: configurable windows os version

docs/memoization.md, workflow/controller/cache/configmap_cache.go, workflow/controller/cache_test.go
Currently the error look like the following if the size exceeds etcd limit:
```
time="2021-05-06T09:07:55Z" level=error msg="Failed to save node outputs to cache" error="error creating cache entry: ConfigMap \"reuse-task\" is invalid: []: Too long: must have at most 1048576 characters" namespace=argo nodeID=xxx workflow=xxx
```
With this PR, the error is now more informative so users know what to do and we can save update API calls (imagine if many nodes are using the same cache, they'll make that many API calls that turn out to fail, which would increase load of k8s apiserver).
Checklist:
=> docs: Add FAQs in memoization doc and add link in the err message

.github/workflows/ci-build.yaml, Makefile, Procfile, hack/free-port.sh, hack/port-forward.sh
The pattern of job failures suggests to me it fails if you start using `PROFILE=mysql`. This PR simplifies that.
* Stop running the UI on CI (this saves 3m).
* Fix a bug in `free-port.sh` that means it exits early.
=> test: 3m faster and more robust e2e

workflow/controller/operator.go
=> workflow-controller: use parentId instead of parentname

hack/changelog.sh
This is to make it easier to inspect changes in each commit in the auto-generated markdown file.
Example outputs:
```
* [0368c2ea](https://github.com/argoproj/argo-workflows/commit/0368c2eadfe34a979973e0b40b6cb4c288e55f38) Allow use of public repos without prior registration (#36)
* [e7e3c509](https://github.com/argoproj/argo-workflows/commit/e7e3c5095c0a1b4312993a234aceb0b90d69f90e) Support -f/--file flag in `argocd app add` (#35)
* [d256256d](https://github.com/argoproj/argo-workflows/commit/d256256defbf6dcc733424df9374a2dc32069875) Update CONTRIBUTING.md (#32)
```
Checklist:
Tips:
* Sign-off …
=> ci: Add links to commit hashes in auto-generated changelog

docs/argo-server.md, docs/async-pattern.md, docs/rest-api.md, docs/rest-examples.md, docs/security.md, docs/stress-testing.md, docs/workflow-submitting-workflow.md
Goal:
* Cheaply reduce the number of users asking about this.
Method:
* Correct docs.
Screenshot:
Fixes #5866
=> docs: Change `http` to `https` for argo-server. Fixes #5866

docs/fields.md, examples/dag-custom-metrics.yaml
DAG/TASK custom metrics example.
1. Emit custom metrics per each tasks using `withItems`.
2. Emit custom metric per task workflow.
```bash
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-A",status="Succeeded"} 7
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-B",status="Succeeded"} 7
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-ONE-A",status="Succeeded"} 7
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-ONE-B",status="Succeeded"} 6
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-TWO-A",status="Succeeded"} 6
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-TWO-B",s …
```
=> feat: DAG/TASK Custom Metrics Example

manifests/cluster-install/argo-server-rbac/argo-server-clusterolebinding.yaml, manifests/cluster-install/kustomization.yaml, manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrolebinding.yaml
Checklist:
*This is a personal PR
Tips:
Fix: #4345
Continue: #4807, #4919
References:
* https://github.com/kubernetes-sigs/kustomize/issues/2717
* https://github.com/kubernetes-sigs/kustomize/issues/136
* https://github.com/kubernetes-sigs/kustomize/issues/1377
=> fix(installation): Enable capacity to override namespace with Kustomize

docs/variables.md
=> chore: fix whitespace issue

examples/README.md
This is a very small typo fix to the "Documentation by Example" README and a suggestion to link to the Github directory holding the YAML files for all of the examples on this docs page. 
Tested on my fork.
Checklist:
Tips:
=> docs: Fix typo on examples page, add link to GH directory

workflow/executor/resource.go
We cannot use `obj.GetSelfLink()` directly since it is deprecated and will be removed after Kubernetes 1.21: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1164-remove-selflink
Checklist:
Tips:
=> fix(executor): Fix compatibility issue with k8s>=1.21 when selfLink is no longer populated

cmd/argoexec/commands/root.go, workflow/common/common.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
As discussed in PR #5946, this is the first step in getting rid of reading the pod annotations in the executor.
Checklist:
Tips:
=> feat: Pass include script output as an environment variable

manifests/base/workflow-controller/workflow-controller-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
1s is too short under stress. I want to be cautious about restarting, hence 30s rather than a shorter time like 10s.
=> fix(controller): Increase readiness timeout from 1s to 30s

ui/src/app/shared/services/workflow-service.test.ts, ui/src/app/shared/services/workflows-service.ts
Fixes #5983 
Fixes #6015 
Hi,
This is a UI fix for the log issue.
The issue is that the UI tries to retrieve the logs from `input-artifacts` by mistake.
=> fix(ui): Fix link for archived logs

ui/src/app/shared/components/chat-button.tsx, ui/src/app/shared/components/pagination-panel.tsx
Changed placing of chat/"get help" button.  Fix #5817
Signed-off-by: Kasper Aaquist Johansen <kasperaaquist@gmail.com>
Before: https://www.dropbox.com/s/0u3f6sjzjjneygj/before.png?dl=0
After: https://www.dropbox.com/s/ymxsq97b1ckgmbf/after.png?dl=0
I have tried to align it such it is placed top middle of the drop down menu.
=> fix(ui): Changed placing of chat/get help button. Fixes #5817

docs/quick-start.md, docs/workflow-executors.md
Closes: https://github.com/argoproj/argo-workflows/issues/5434
Closing the loop on #5434: Argo works fine in GKE Autopilot if the `k8sapi` executor is used. I opted to add custom manifests for GKE Autopilot for better user experience, easier automation for creating Argo in Autopilot clusters, and better extensibility if we decide that other configurations are right for Autopilot.
Checklist:
Tips:
* Say how how you tested your changes. If you changed the UI, attach …
=> docs: Must use k8sapi to run on GKE Autopilot

test/e2e/resource_template_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
Caught a bug while debugging issues with https://github.com/argoproj/argo-workflows/pull/6014. Also fixes #5981. 
For resource templates, main container is used as a wait container. We need to check its termination status before queue the pod for cleanup. Otherwise, when `cleanUpPod` is called during node assessment/reconciliation, the main container would have been killed by clean-up and then wf is marked as failed even though the pod is succeeded (if wf status update happens a little late than pod the cleanup, which explains why builds in https://github.com/argoproj/argo-workflows/pull/6014 only fail occasionally).
Example controller log from PNS test-executor in https://github.com/argoproj/argo-workflows/runs/2676799345:
```
controller | time="2021-05-26T16:25:15.758Z" level=info …
```
=> fix(controller): Only clean-up pod when both main and wait containers have terminated. Fixes #5981

test/e2e/resource_template_test.go, workflow/executor/resource.go, workflow/executor/resource_test.go
See context in https://github.com/argoproj/argo-workflows/issues/6008. Also Fixes #6045. 
Checklist:
Tips:
=> fix(executor): Fix compatibility issue when selfLink is no longer populated for k8s>=1.21. Fixes #6045

workflow/controller/controller.go
=> fix(controller): Handling panic in leader election

ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Fixes some annoyances:
1. The pod name auto-complete was blank on load, rather than "All".
2. The filter input loses focus when `grep` changes (due to re-render), so I increased the delay to 1s to cheaply mitigate this.
3. The highlighting was only working for fixed values, and only the first occurrence. Now correctly uses RegExp and highlight all values.
=> fix(ui): Tweak workflow log viewer

docs/quick-start.md
Signed-off-by: Kaito Ii <kaitoii1111@gmail.com>
Currently, the release page is filled with Pre-releases. The user needs to scroll through the pages to get to the stable release.
It would be better for the user to be able to access the latest stable release directly from the link.
=> Point to latest stable release

Dockerfile, workflow/executor/resource.go
=> fix(executor): Fix `kubectl` permission error

workflow/executor/resource.go
Per feedback in https://github.com/argoproj/argo-workflows/issues/6097#issuecomment-856071975. Resource JSON objects can be really large and we log too much at info level.
Checklist:
Tips:
=> chore(executor): Adjust resource JSON object log to debug level

Makefile, manifests/cluster-install/argo-server-rbac/argo-server-clusterolebinding.yaml, manifests/cluster-install/kustomization.yaml, manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrolebinding.yaml, manifests/install.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
=> build: Fix `make codegen`

USERS.md
=> docs: add Glovo to users

docs/sidecar-injection.md, test/e2e/fixtures/needs.go, test/e2e/signals_test.go, test/e2e/testdata/sidecar-injected-kill-annotation-workflow.yaml, workflow/common/common.go, workflow/controller/controller.go, workflow/signal/signal.go
=> fix(executor): Fix emissary kill. Fixes #6030

test/e2e/fixtures/needs.go, workflow/executor/docker/docker.go
=> fix(executor): Fix docker not terminating. Fixes #6064

docs/events.md
Closes #6123
Trying to use the argo workflows events and I noticed that some crucial explanations are missing here. Further infos in the issue 6123.
Checklist:
Tips:
=> docs: Update events.md

examples/README.md
=> docs: Add note on the requirements of resource templates. Fixes #5566

Makefile
Use make command to build argo-workflows container images, the images not output to docker.When use docker run command to start container will pull image from dockerhub
Checklist:
=> build image output to docker

go.mod, go.sum, workflow/artifacts/oss/oss.go
There's security risk in the previous version of `ListObjects()` since it tries to obtain the ownership information of the objects by default. Switching to `ListObjectsV2` is more secure and preferred.
Checklist:
Tips:
=> chore: Upgrade Alibaba OSS to use more secure ListObjectsV2()

ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx, ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx, ui/src/app/workflows/components/submit-workflow-panel.tsx, ui/src/app/workflows/components/workflow-creator.tsx
Checklist:
I am committing on my own time.
Local testing showing this fix in action:
<details><summary>Using this WorkflowTemplate</summary>
<p>
```
metadata:
name: whalesay-test
spec:
entrypoint: whalesay-template
arguments:
parameters:
value: hello
templates:
- name: whalesay-template
inputs:
parameters:
- name: message-param-1
container:
image: argoproj/argosay:v2
args: ["echo", "{{inputs.parameters.message-param-1}}"]
imagePullPolicy: IfNotPresent
- name: whalesay-template-two
inputs:
parameters:
- name: message-two
container:
image: argoproj/argosay:v2
args: ["echo", "{{inputs.parameters.message-two}}"]
imagePullPolicy: IfNotPresent
```
</p>
</details>
=> fix: Allow setting workflow input parameters in UI. Fixes #4234

cmd/argoexec/commands/emissary.go, test/e2e/artifacts_test.go, test/e2e/fixtures/e2e_suite.go, test/e2e/fixtures/given.go, test/e2e/fixtures/then.go, test/e2e/fixtures/when.go
=> fix(executor): Capture emissary main-logs. Fixes #6145

examples/buildkit-template.yaml, examples/cluster-workflow-template/cluster-wftmpl-dag.yaml, examples/cluster-workflow-template/clustertemplates.yaml, examples/container-set-template/graph-workflow.yaml, examples/container-set-template/outputs-result-workflow.yaml, examples/container-set-template/sequence-workflow.yaml, examples/dag-coinflip.yaml, examples/dag-continue-on-fail.yaml, examples/dag-daemon-task.yaml, examples/dag-diamond-steps.yaml, examples/dag-diamond.yaml, examples/dag-disable-failFast.yaml, examples/dag-multiroot.yaml, examples/dag-nested.yaml, examples/dag-targets.yaml, examples/dag-task-level-timeout.yaml, examples/exit-handler-dag-level.yaml, examples/key-only-artifact.yaml, examples/loops-dag.yaml, examples/map-reduce.yaml, examples/parallelism-nested-dag.yaml, examples/parameter-aggregation-dag.yaml, examples/pod-spec-from-previous-step.yaml, examples/resubmit.yaml, examples/workflow-template/dag.yaml, examples/workflow-template/templates.yaml
This probably should have been done some time ago. `depends` was released in v2.9 and is the preferred way to specify DAG dependencies. However, the examples don't reflect that and many users will not be aware of the existence of `depends` unless they search the docs. I propose we feature `depends` in the examples instead.
Checklist:
Tips:
=> docs: Use 'depends' instead of 'dependencies' in examples

docs/workflow-controller-configmap.yaml, server/auth/sso/sso.go
We currently need to front Argo behind two endpoints with unique URLs and this currently causes issues as you have to configure the redirect URL when setting up SSO.
Many other tools we use like JupyterHub and MLFlow will use the Host header to "guess" the redirect URL when you have not explicitly set it, this has the benefit of not needing to configure the redirect URL and in our case enables us to serve Argo behind two endpoints without issue.
I saw no existing tests around this code path in the sso module, I am happy to write some if requested but for now I have tested the changed in our environment and verified that existing behavior still works when the redirect URL is set.
Checklist:
Tips:
* Your PR needs to pass the required checks before it can be approved. If the check is not …
=> feat(server): Allow redirect_uri to be automatically resolved when using sso

persist/sqldb/explosive_offload_node_status_repo.go, persist/sqldb/mocks/OffloadNodeStatusRepo.go, persist/sqldb/offload_node_status_repo.go, workflow/controller/controller.go, workflow/controller/indexes/indexes.go, workflow/controller/indexes/uid_index.go
Offloaded nodes are periodically garbage collected. The garbage collector first compiles a map of node status versions to keep (based on available k8s resources) and assumes that all other node statuses can be deleted. For workflows without a value for 'OffloadNodeStatusVersion' it is assumed that the nodes are not (or no longer) being offloaded. 
Unfortunately this is not always correct: we observed (quite regularly) that node status information was deleted prematurely, destroying active workflows and/or making it impossible to review workflow results afterwards.
While investigating the issue we discovered that the workflows provided by the workflow lister are sometimes hydrated and because of that do not yet have a value for 'OffloadNodeStatusVersion'. However this doesn't necessarily …
=> fix(controller): dehydrate workflow before deleting offloaded node status

docs/roadmap.md
It looks like RBAC for SSO is already implemented by https://github.com/argoproj/argo-workflows/pull/4198 so hopefully it can be removed from the roadmap as it is also documented? https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac
Checklist:
* [n/a] ~~My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).~~ I am researching Argo, and have not adopted it yet.
Tips:
=> docs: Remove RBAC for SSO from Roadmap (Already implemented)

workflow/validate/validate.go
fix #6189 
before:
after:
Signed-off-by: BOOK <book78987book@gmail.com>
Checklist:
Tips:
=> fix(controller): Wrong validate order when validate DAG task's argument

docs/workflow-executors.md
When switching from docker executor to k8sapi/kubelet executor, the behaviour on what gets captured in `steps/tasks.outputs.result` is a little different.
In an error-free run, argo docker executor will only store the stdout in step/task's result. However, when using k8sapi/kubelet executor, due to k8s logs unable to differentiate between stdout and stderr, k8sapi/kubelet will also store the warning messages. This may cause issues if downstream depends on the `outputs.result` (e.g. withParam)
https://github.com/kubernetes/kubernetes/issues/28167
Checklist:
Tips:
* Sign-off your commits to pass the …
=> docs(executor): document k8s executor behaviour with program warnings

ui/src/app/shared/components/clipboard-text.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
=> feat(ui): Add copy to clipboard shortcut

config/config.go, test/e2e/pod_cleanup_test.go, workflow/controller/controller.go, workflow/controller/operator.go
The PR https://github.com/argoproj/argo-workflows/pull/5033 was meant to fix the issue of delaying pod deletion for some period so things like logging scrapers can do their thing before the pod goes away.
Based on my comments https://github.com/argoproj/argo-workflows/pull/5033#discussion_r581354568 this won't actually work as intended and another solution is needed.
My fix in this PR aims to delay the actual deletion by some configurable value and the deletion logic will then either delete immediately or queue the deletion for after this period.
@terrytangyuan tagging you as you did the original PR and tagging @alexec as you were the reviewer, as you might have more insight here. I have written an initial test here but am happy to expand coverage if desired.
One area I am not sure about …
=> feat(controller): Delay pod GC deletion by a configurable amount (default 5s)

workflow/executor/emissary/emissary.go
Fixes #6238 
In this PR, I verified a real workflow works end to end with non-root users.
```
kind: Workflow
metadata:
generateName: hello-world-
spec:
entrypoint: hw
templates:
- name: hw
container:
image: curlimages/curl:latest
command: [sh, -c, "echo hello"]
```
Tips:
=> fix(executor): emissary - make /var/run/argo files readable from non-root users. Fixes #6238

docs/running-locally.md, hack/recurl.sh
=> docs: docs and hacks improvements

docs/argo-server.md
Since v3.0, `argo server` defaults to `--secure=true` and therefore only serves HTTPS, which means that the Ingress example from these docs will no longer work OOTB. Ingress controllers need to be told the backend uses HTTPS.
This PR attempts to clarify that and provide examples for Traefik and ingress-nginx.
=> docs: document using ingress with TLS enabled

docs/variables.md
Signed-off-by: Michael Crenshaw <michael@crenshaw.dev>
I ran tests to confirm that dot-notation access fails and that string index notation works.
=> docs: document how to access hyphenated steps in expression templates

hack/crds.go, manifests/base/crds/minimal/argoproj.io_clusterworkflowtemplates.yaml, manifests/base/crds/minimal/argoproj.io_cronworkflows.yaml, manifests/base/crds/minimal/argoproj.io_workfloweventbindings.yaml, manifests/base/crds/minimal/argoproj.io_workflows.yaml, manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml, manifests/base/crds/minimal/argoproj.io_workflowtemplates.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
workaround fix #6256 
set x-kubernetes-map-type to skip ReconcileFieldSetWithSchema
ReconcileFieldSetWithSchema causes timeout when updating large crd
Checklist:
Tips:
=> fix(crd): temp fix 34s timeout bug for k8s 1.20+

cmd/argo/commands/cron/create.go, test/e2e/cli_test.go
Currently we only copy the workflow spec after we applied the submit options but generateName/name cannot be overridden. This PR fixes this issue.
Checklist:
Tips:
=> fix(cli): Overridding name/generateName when creating CronWorkflows if specified

util/fields/fields.go, util/fields/fields_test.go
This PR resolves #6284 by ensuring that a list request to a nested field does not cause parent fields to be ignored. I added a small unit test to the existing test suite to ensure the fix works as expected and doesn't contradict previous features.
=> fix(fields): handle nexted fields when excluding

docs/environment-variables.md, workflow/controller/retry_tweak.go
Currently this has been hard-coded to `"kubernetes.io/hostname"` and will not be reliable on different environments (`k3s` or some internal k8s distributions). For example, `k3s` uses `k3s.io/hostname` so we won't be able to test `RetryOnDifferentHost` if it's hard-coded.
Checklist:
Tips:
=> feat(controller): Allow configurable host name label key when retrying different hosts

examples/README.md, examples/exit-handlers.yaml, workflow/controller/operator_test.go, workflow/validate/validate.go, workflow/validate/validate_test.go
resolves https://github.com/argoproj/argo-workflows/issues/5484
also fixes 
since the https://github.com/argoproj/argo-workflows/blob/master/docs/variables.md#global says workflow.duration is available globally
Checklist:
Tips:
=> fix(controller): allow workflow.duration to pass validator

workflow/controller/operator.go
The original code isn't retrying due returning non-nil error on ExponentialBackoff
fixes: https://github.com/argoproj/argo-workflows/pull/6178 #6163
Checklist:
Tips:
=> fix(controller): fix retry on transient errors when validating workflow spec

USERS.md, examples/grafana-dashboard.json
This PR imports `ArgoWorkflow Metrics` dashboard from the Grafana library to this repository.
It also apply some fixes:
- Rename the dashboard from `ArgoWorkflow Metrics` to `ArgoWorkflows`
- Replace the broken mascot image link to the same as ArgoCD dashboard
- Delete the alert functionality of  the `Workflow Errors` widget since it's not supported anymore (when datasource is templated). See https://github.com/grafana/grafana/issues/36110
- Compatibility with GitOps import. See https://github.com/grafana/grafana/issues/10786#issuecomment-568788499 
Checklist:
=> chore: import grafana dashboard

docs/configure-artifact-repository.md
It's worth adding this since our users encounter this issue very often.
Checklist:
Tips:
=> docs: Add note on additional required permission for createBucketIfNotPresent for OSS driver

workflow/controller/operator.go, workflow/controller/operator_test.go
a workflow like below will result in
- first pod produce duration ~= 9223372036.123456
- second pod produce duration ~= 15.123456
This PR fixes this, making first pod produce duration = 0
```
kind: Workflow
metadata:
generateName: exit-handlers-
spec:
entrypoint: run
templates:
- name: run
steps:
- - name: run1
template: duration
- - name: run2
template: duration
- name: duration
container:
args: ["echo {{workflow.duration}}; sleep 15;"]
```
Checklist:
Tips:
* Run `make pre-commit -B` to fix codegen or lint …
=> fix(controller): allow initial duration to be 0 instead of current_time-0

docs/workflow-controller-configmap.yaml
I tried configuring my Argo-Server to use s3 as an artifact repository, and then archive all logs automatically, and it worked fine. But then when I wanted to load those logs in the Argo-Server UI using the link `https://<arg_server_host>/artifacts/argo/<workflow_name>/<pod_name>/main-logs` I got the following error:
```
failed to create new S3 client: WebIdentityErr: failed fetching WebIdentity token: 
caused by: WebIdentityErr: unable to read file at /var/run/secrets/eks.amazonaws.com/serviceaccount/token
caused by: open /var/run/secrets/eks.amazonaws.com/serviceaccount/token: permission denied
```
Reading through similar issues here: https://github.com/kubernetes-sigs/external-dns/pull/1185 I found out that IRSA requires this setting on the Deployment: …
=> docs: updating documentation on how to setup IRSA on AWS

workflow/artifacts/gcs/gcs.go, workflow/artifacts/gcs/gcs_test.go
The current gcs artifact exponentialbackoff is not working.
- fix retry
- added only retry on transient error
gcs bucket accepts about 1000 write request initially, then autoscales up. [link](https://cloud.google.com/storage/docs/request-rate#auto-scaling)
When having over 1000 write request in a burst from stale, we will see some errors.
Tested with below workflows/config on gke:1.18.17-gke.1901 with
- argo-workflow 3.1.1 + gcloud bucket1
- argo-workflow 3.1.1 + gcloud bucket2 + this PR
<details>
<summary>Workflows</summary>
```
kind: Workflow
metadata:
generateName: stress-test-
labels:
workflows.argoproj.io/container-runtime-executor: emissary
spec:
entrypoint: loops-dag
podGC:
strategy: OnWorkflowSuccess
templates:
- name: loops-dag
dag:
tasks:
- name: …
```
=> fix(executor): fix GCS artifact retry

workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
=> fix(controller): Force main container name to be "main" as per v3.0. Fixes #6405

cmd/argoexec/commands/emissary.go, workflow/executor/emissary/emissary.go, workflow/executor/os-specific/umask_darwin.go, workflow/executor/os-specific/umask_linux.go, workflow/executor/os-specific/umask_windows.go
This fully fixes emissary + nonroot.
I've tested sidecars, input/output parameters and artifacts
Checklist:
Tips:
=> fix(executor/emissary): fix nonroot sidecars + input/output params & artifacts

USERS.md, config/config.go, config/node_events.go, workflow/controller/operator.go, workflow/controller/operator_test.go
Because of how kubernetes aggregates events and how Argo sends both
workflow and node events with the same involved object (the workflow),
some workflow and node events can get merged into a single event, without
specifying which nodes are merged into one. This makes it challenging to
respond to phase changes for nodes that have a particular annotation
because kubernetes ignores annotations when checking if an event is
similar.
Creating an opt-in feature to send node events for nodes of type "Pod"
with the involved object set to the associated pod will force kubernetes
to send an event for each pod instead of aggregated several events into
a single event and thus make it possible build a system solely that
responds to node phase changes using Argo Workflows and Argo Events.
An alternative …
=> feat(controller): opt-in to sending pod node events as pod

workflow/executor/emissary/emissary.go
Checklist:
re #6391 
I took the liberty of not adding tests because it's a 1 line change and there are currently no tests for the emissary executor :stuck_out_tongue:
=> fix(emissary): throw argo error on file not exist

USERS.md, workflow/artifacts/oss/oss.go
to fix problem: #6293 
I have used the following workflow to test, and the result is correct.
```yaml
kind: Workflow
metadata:
name: test-archive-none
spec:
entrypoint: oss-getter-and-uploader
templates:
- name: oss-getter-and-uploader
inputs:
artifacts:
- name: oss-none-empty-dir
path: "/mnt/input/none-empty"
oss:
key: "some/none-empty"
archive:
none: {}
- name: oss-empty-dir
path: "/mnt/input/empty-dir"
oss:
key: "some/emptydir"
archive:
none: {}
- name: oss-file
path: "/mnt/input/file"
oss:
key: "some/file"
archive:
none: {}
- name: oss-3level
path: "/mnt/input/3level"
oss:
key: "some/3level-dir"
archive:
none: {}
container:
image: 'alpine:latest'
command: ['/bin/sh', '-c']
args: ["cp -rf /mnt/input /mnt/output"]
volumeMounts:
- name: out
mountPath: …
```
=> fix: support archive.none for OSS directory artifacts

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, server/artifacts/artifact_server_test.go
Fixes #6024.
Hi, sorry for this late PR. Been busy with work lately.
This simply adds a nil pointer check for input artifacts, similar to what had been done to the output artifacts.
https://github.com/argoproj/argo-workflows/blob/eb6503cb106b3660437f9f1f703db69330a99a87/pkg/apis/workflow/v1alpha1/workflow_types.go#L2529-L2534
This is to prevent a nil point panic when the user tries to get input artifacts from a step without any input artifacts specified.
To reproduce the issue, submit a workflow without any input artifacts, and try to get an input artifact from one of the steps.
Thanks!
=> fix(server): Fix nil pointer error when getting artifacts from a step without artifacts

ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/retry_tweak.go, workflow/controller/retry_tweak_test.go, workflow/controller/workflowpod.go, workflow/util/retry/retry.go, workflow/util/retry/retry_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/6248
Fixes https://github.com/argoproj/argo-workflows/issues/5830
This PR fixes the following issues:
- assign `HostNodeName` earlier before the next pod is retried
- collect hostnames from errored /failure nodes in complex workflow by iterating over the tree
- `FAIL HOSTS` in UI
- inject `affinity` with failed host before the pod is scheduled
Additionally, the fix allows merging affinity from `spec` and `podSpecPatch`.
I've tested in a few ways:
- local K3D cluster
- in a private cluster with prod application
- unit tests
All tests were run from simple to more complex workflows.
[example-workflow.txt](https://github.com/argoproj/argo-workflows/files/6880350/template-pod-spec-patch.txt)
=> fix(controller): fix retry on different hosts

docs/running-at-massive-scale.md, mkdocs.yml
=> docs: Document running at massive scale. Fixes #6443

workflow/executor/docker/docker.go
Fixes https://github.com/argoproj/argo-workflows/issues/6352
After `docker wait` exits 0, there is a chance the container is still in "Created" state.
I'm not sure why that happens, but it now happens stably on GKE per my observation.
the fix is a workaround to check container status after `docker wait` and do `docker wait` again if we found some containers haven't finished yet.
I reproduced the issue in #6352 stably as explained in https://github.com/argoproj/argo-workflows/issues/6352#issuecomment-892523099.
Then I verified with this PR, the issue never shows up again.
Checklist:
Tips:
* Sign-off your commits to pass the DCO check: `git commit …
=> fix(executor/docker): fix random errors with message "No such container:path". Fixes #6352

test/e2e/fixtures/when.go, test/e2e/functional_test.go, workflow/common/common.go, workflow/controller/operator.go
With the ability to configure node events to be sent with the involved
object set to the pod, it would be handy if annotations were provided
in the event that would allow the pod/node to understand which workflow
it belongs to.
* Run the server locally
* Submit a workflow
* Print out the events and their annotations
✅ confirmed that pod events included workflow annotations. Here is an example:
✅ confirmed that events for the workflow did not contain these annotations (e.g. the `WorkflowRunning` event)
✅ confirmed that non-pod events did not contain these annotations (e.g. `WorkflowNodeRunning` events for a DAG node type):
I couldn't find a good way to assert that events had certain annotations in the unit tests. I attempted to use If anyone has a good idea on how to do that, I'm open to …
=> feat: Annotate pod events with workflow name and UID

test/e2e/argo_server_test.go, util/kubeconfig/kubeconfig.go
=> fix: Remove client private key from client auth REST config

CHANGELOG.md, USERS.md, hack/changelog.sh
Signed-off-by: Steve McClain <steve@marmalade.co>
Checklist:
This is a very small quality-of-life fix to the `hack/changelog.sh` script, discussed with @alexec in [slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1628089130121200?thread_ts=1628042232.101000&cid=C01QW9QSSSK). It now shows the date the tag was created instead of the date of the tagged commit.
=> build: Fix changelog script to display the tag creation date

ui/src/app/userinfo/components/user-info.tsx
Signed-off-by: Tetsuya Shiota <tetsuya.shiota.1231@gmail.com>
Checklist:
Tips:
`<dl>` is a more appropriate tag than `<p>` to display user detail info. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p
Before:
After:
=> feat(ui): use dl tag instead of p tag in user-info ui

docs/running-locally.md
Checklist:
Tips:
`make start PROFILE=SSO` didn't work in my environment.
But `make start PROFILE=sso` work in my environment.
```
% cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```
I guess that is caused by whether the filesystem is case-sensitive or not.
```
% make start PROFILE=SSO
GIT_COMMIT=080538f76e5b7162323fa70339bf6030ace68a51 …
```
=> docs: PROFILE=SSO to PROFILE=sso for case-sensitive filesystem

cmd/argo/commands/server.go, util/help/topics.go
Quick Fix - I believe `ArgoSever` is meant to be `ArgoServer` 🙃
=> chore: ArgoSever mistype

manifests/base/argo-server/argo-server-deployment.yaml, manifests/base/workflow-controller/workflow-controller-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
closes #6539 
Signed-off-by: Hong Wang <wanghong230@gmail.com>
Tests:
Faked the tag locally with v9.9.9, and run make manifests, inspected the manifests
% cat dist/manifests/quick-start-postgres.yaml |grep v9.9.9
docker/whalesay:v9.9.9:
image: quay.io/argoproj/argocli:v9.9.9
- quay.io/argoproj/argoexec:v9.9.9
image: quay.io/argoproj/workflow-controller:v9.9.9
Generate the manifest with latest tag, installed the manifest successfully, the hello world workflow worked
=> fix: replace docker.io with quay.io to avoid the image pull limit

Makefile
Signed-off-by: Hong Wang <wanghong230@gmail.com>
Tips:
* You can ask for help! 
Before:
% make lint
GIT_COMMIT=37395d6818ba151213a1bb8338356cf553c2404a GIT_BRANCH=master GIT_TAG=untagged GIT_TREE_STATE=clean RELEASE_TAG=false …
=> fix: use golangci-lint v1.37.0 to support apple M1

.github/workflows/ci-build.yaml, Makefile, docs/running-locally.md, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
Since Kubernetes v1.14, kustomize became a subcommand in kubectl so we can just use `kubectl` instead. We are currently using `KUBECTL_VERSION=1.19.6` so we should have `kustomize` already.
Tips:
* If changes were requested, and you've made them, then dismis the review to get it …
=> build: Switch to use kustomize subcommand in kubectl

Dockerfile
Fixes https://github.com/argoproj/argo-workflows/issues/6556.
Tips:
=> build: Add missing libcap binary to fix argoexec image build

.gitignore, Dockerfile, Makefile, cmd/argo/commands/server.go, cmd/argo/commands/server_test.go, util/tls/tls.go, util/tls/tls_test.go
This is a first pass resolution to issues raised within #6355
the tls util was taken from `argo-cd`'s utilities and an additional `tlsConfig` helper added to simplify the initilisation process of the server.
=> fix: Generate TLS Certificates on startup and only keep in memory

workflow/executor/docker/docker.go
This is a follow up fix of https://github.com/argoproj/argo-workflows/pull/6508.
I start to observe "container does not exist" errors after deploying argo v3.1.6 to KFP test clusters.
After some investigations, I found out this bug, `d.GetExitCode` expects a container name, not a container ID, so it always fail with "container not found" here.
https://github.com/argoproj/argo-workflows/blob/e0103ccd6ff7cb7b1eb4f369c5829fc8560d94ce/workflow/executor/docker/docker.go#L159
The original issue https://github.com/argoproj/argo-workflows/issues/6352 happens when the main container starts slower than the wait container and main container stays in "Created" state for a while (e.g. when one node is assigned too many Pods).
Before the fix in https://github.com/argoproj/argo-workflows/pull/6508, upon …
=> fix(executor/docker): fix failed to wait for main container to complete: timed out waiting for the condition: container does not exist

workflow/executor/pns/pns.go
In PNS executor, there is a panic `concurrent map writes` on `p.pidFileHandles`. When error occurs, the `Wait` method will be re-invoked, and starts a new goroutine, the `p.pidFileHandles` will be concurrently assigned. This fix adds a lock to protect it.
panic log:
```
time="2021-08-19T04:02:13.596Z" level=info msg="Starting Workflow Executor" executorType=pns version=v3.1.6-patch
time="2021-08-19T04:02:13.600Z" level=info msg="Creating PNS executor (namespace: test, pod: sparkly-bear-m6bxb, pid: 36)"
time="2021-08-19T04:02:13.600Z" level=info msg="Creating a K8sAPI executor"
time="2021-08-19T04:02:13.600Z" level=info msg="Executor initialized" includeScriptOutput=false namespace=test podName=sparkly-bear-m6bxb template="{\"name\":\"argosay\",\"inputs\":{\"parameters\":[{\"name\":\"messag …
```
=> fix(executor/pns): panic of pidFileHandles concurrent writes

workflow/artifacts/gcs/gcs.go, workflow/artifacts/gcs/gcs_test.go
Fixes #6576
I'm not really sure how to write proper `e2e` or `unit` tests for this fix as it involves stubbing the GCS API... I am deploying this fix to our staging cluster and testing it just now. I'll comment here with the tests carried out and the outcomes.
=> fix(gcs): backoff bool should be false if error is transient

workflow/controller/controller_test.go
This has been removed in https://github.com/argoproj/argo-workflows/pull/6297 but it's actually being used in unit tests: 
```
workflow/controller/operator_test.go:3483:4: undefined: createRunningPods
workflow/controller/operator_test.go:3525:2: undefined: createRunningPods
```
See failed build on master branch: https://github.com/argoproj/argo-workflows/runs/3392422636
This PR adds it back and moves it closer to where it's being used.
cc @simster7 
=> fix: Fix unit test with missing createRunningPods()

cmd/argoexec/commands/root.go, workflow/executor/docker/docker.go, workflow/executor/k8sapi/k8sapi.go, workflow/executor/kubelet/kubelet.go, workflow/executor/pns/pns.go
When using the PNS executor, we are currently observing the following log:
```
time="2021-08-21T02:08:59.598Z" level=info msg="Creating PNS executor (namespace: argo, pod: memoized-simple-workflow-with-cache-gc-wfnjj, pid: 7)"
time="2021-08-21T02:08:59.598Z" level=info msg="Creating a K8sAPI executor"
```
This is confusing and caused by `NewPNSExecutor` that uses `NewK8sAPIExecutor` as a delegate with "k8sapi" in the log. This PR disambiguates this and moves the log to the root.
=> fix(executor): Disambiguate PNS executor initialization log

server/apiserver/argoserver.go, server/auth/gatekeeper.go, test/e2e/argo_server_test.go
=> fix!: Enable authentication by default on Argo Server `/metrics` endpoint. Fixes #6592

README.md
Fix the `How to write workflow specs` link going to the raw github content page.
Signed-off-by: Andrey Melnikov <vafilor@gmail.com>
=> fix: readme link going to raw page

.github/workflows/release.yaml
Fixes #6541. The `push-linux-amd64-images` step is the same as the `push-images` step but only used the `linux/amd64` platform.
=> Build Docker manifest only when all dependencies are ready

cmd/argo/commands/node.go, examples/suspend-template-outputs.yaml
Example is incorrect and also fixes a panic when not enough arguments were supplied.
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
Tips:
=> fix: `argo node set` panic: index out of range and correct docs

api/openapi-spec/swagger.json, pkg/apiclient/_.primary.swagger.json
Fixes #6606
adds OpenAPI documentation for the following endpoints
/artifacts
/input-artifacts
/artifacts-by-uid
/input-artifacts-by-uid
At first I was considering exposing a grpc service like the other `/api/v1` endpoints. Upon closer inspection that seemed a bit more complicated since you can't just return a `text/plain` response with the logs like the existing artifact service does. With grpc you would need to wrap the data in a message. Instead of trying to rework any of that it seemed much simpler to just add the existing artifiact endpoints to the OpenAPI spec.
=> docs: adds OpenAPI definitions for artifact routes

.github/workflows/ci-build.yaml, examples/expression-tag-template-workflow.yaml
=> ci: run `make test-examples` on CI

ui/src/app/reports/components/reports.tsx
=> fix(ui): report phase button alignment. Fixes #4974

workflow/artifacts/hdfs/hdfs.go
fixes #6598
reference code:
https://github.com/colinmarc/hdfs/blob/v1.1.3/stat.go#L21
https://github.com/colinmarc/hdfs/blob/e2c734b8518275eeb74661de28966a00b9b6c212/exceptions.go#L10
hdfs.Stat returns:
os.ErrNotExist
ErrPermission
default error wrap in os.pathError
Tips:
* If changes were requested, and you've made them, then …
=> fix(executor): handle hdfs optional artifact at retriving hdfs file stat. Fixes #6598

workflow/executor/k8sapi/client.go
=> fix: Fix kill sidecar timeout issue. Fixes ##6693

docs/environment-variables.md, test/e2e/fixtures/then.go, workflow/common/common.go, workflow/controller/controller.go, workflow/controller/exec_control.go, workflow/controller/indexes/indexes.go, workflow/controller/indexes/workflow_index.go, workflow/controller/indexes/workflow_index_test.go, workflow/controller/node_counters.go, workflow/controller/node_counters_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go, workflow/util/pod_name.go, workflow/util/pod_name_test.go, workflow/util/util.go, workflow/util/util_test.go
This PR is a continuation of Alex's PoC  #6647 that fixes #1319. It:
- Sets pod names to a concatenation of the wf name, template name, and hash
- Allows for an override of the pod name to the node id if the env `USE_LEGACY_POD_NAMES` is set to true
- Stores the node id as an annotation on the pod
Sample terminal output:
```
$ kubectl get pods -n argo
NAME                                   READY   STATUS      RESTARTS   AGE
minio-786d5cbc44-c9ppg                 1/1     Running     7          19h
retry-test-p7jzr-whalesay-2308805457   0/2     Completed   0          13h
retry-test-p7jzr-whalesay-2378053249   0/2     Completed   0          13h
```
=> feat: Add template node to pod name. Fixes #1319

workflow/controller/workflowpod_test.go
Recent PR #6712 Added TestPodExists
the code is fine, runs well in local machine but somehow in github ci, it fails very often
#6753 https://github.com/argoproj/argo-workflows/runs/3632323865?check_suite_focus=true
#6749 https://github.com/argoproj/argo-workflows/runs/3627112929?check_suite_focus=true
I tested using
```
assert.Equal(t, "hello-world", pod.Name)
assert.Equal(t, "hello-world", pod.ObjectMeta.Name)
assert.Equal(t, pod.Name, pod.ObjectMeta.Name)
```
They indeed show the same value in github CI
but using `woc.podExists(pod.Name)` just fails
changing to `woc.podExists(pod.ObjectMeta.Name)` seems to solve the issue
Tips:
* Your PR needs to pass the required checks before …
=> fix(controller): TestPodExists unit test

docs/quick-start.md, examples/README.md
Very minor fix to the "!!! note" not rendering in quick-start.md (https://argoproj.github.io/argo-workflows/quick-start/).
While I was at it, I combined the consecutive GKE "notes" into one, with the shell snippet.
Here are the rendered changes, for your consideration ![new-quick-start](https://user-images.githubusercontent.com/2049051/133863533-7762dbfb-4dae-43fe-81b1-d821dc4ebd2b.jpg)
=> docs: Fix bad callout render in quick-start docs

workflow/controller/workflowpod_test.go
Fixes #6458
There's a slight delay between creating pod and informer getting this event,
which result in flaky test
Tested using
`go test -count=100 -run=TestPodExists ./workflow/controller`
Tips:
=> fix(controller): TestPodExists test, add delay. Fixes #6458

workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/validate/validate.go, workflow/validate/validate_dag_test.go
Fixes #6684
Signed-off-by: smile-luobin <smile.luobin@gmail.com>
Tips:
=> fix: Fix bugs, unable to resolve tasks aggregated outputs in dag outputs. Fixes #6684

ui/src/app/workflow-event-bindings/components/workflow-event-bindings/workflow-event-bindings.tsx
=> fix(ui): workflow event binding typo

util/expand/expand.go, util/expand/expand_test.go, util/expr/env/env.go, util/template/expression_template.go
=> fix: Fix expression template random errors. Fixes #6673

cmd/argo/commands/server.go, cmd/workflow-controller/main.go, docs/environment-variables.md, go.mod
This is a proposal for https://github.com/argoproj/argo-workflows/issues/5914. It uses https://github.com/spf13/viper to parse environment variables from the flag names.
I tested this like this:
=> feat: Add env vars config for argo-server and workflow-controller

docs/workflow-archive.md
A few minor additional details have been added to the Workflow Archive doc pages. 
* Tables generated during the database migration have been listed
* Details about workflow-controller  startup failures with an incomplete set of tables have been added
* Required database permissions for postgres has been explicitly stated. 
I ran into some issues trying to utilize a different postgres schema and strict role permissions and thought these additional details may help others.
Signed-off-by: Anthony Scott <anthony@canthonyscott.com>
Tips:
* …
=> docs: Additional details added to workflow archive doc pages

api/jsonschema/schema.json, hack/jsonschema/main.go
If definitions are associated to Kubernetes resources, they may have this attribute to identify this:
https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/README.md#x-kubernetes-group-version-kind. For object definitions, it is a list (as I did here in the PR): https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/explain/test-swagger.json#L34-L40
Context:
We generate a [library](https://jsonnet-libs.github.io/argo-workflows-libsonnet/) from the json schema and we use this attribute to determine which objects are actual Kubernetes resources
=> docs: Add `x-kubernetes-group-version-kind` attribute to JSON schema

ui/src/app/workflows/components/workflow-dag/genres.ts
Fix https://github.com/argoproj/argo-workflows/issues/6794
=> fix: add HTTP genre and sort

.golangci.yml, persist/sqldb/backfill_nodes.go, persist/sqldb/migrate.go
Updated code to defer closing sql.Rows recommended by linters
resolves #6838 
The `sqlclosecheck` linter says to use defer but not sure if this is the best way to handle returning the error. I am also not sure if its possible to hit a scenario where the code gets an error on `rs.Scan` and `rs.Close` as an example. Currently the code only sets the error in the defer func if there were no errors previously.
=> chore: enabled `rowserrcheck` and `sqlclosecheck` linters

docs/security.md
I'm assuming Arfactory should be Artifactory?
=> docs: Fix typo on docs/security.md

workflow/controller/container_set_template_test.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go, workflow/validate/validate_test.go
=> fix(controller): default volume/mount to emissary. Fixes #7118

workflow/executor/agent.go, workflow/executor/http/http.go, workflow/executor/http/http_test.go
`template.HTTP.timeoutSeconds` is completely ignored as of now. This PR respects the value entered by the user.
Tips:
=> fix: Respect template.HTTP.timeoutSeconds

Makefile, cmd/argoexec/commands/root.go, docs/environment-variables.md, docs/progress.md, pkg/apis/workflow/v1alpha1/progress.go, pkg/apis/workflow/v1alpha1/progress_test.go, test/e2e/progress_test.go, test/e2e/testdata/progress-workflow.yaml, workflow/common/common.go, workflow/controller/container_set_template_test.go, workflow/controller/controller.go, workflow/controller/controller_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go, workflow/executor/executor.go, workflow/executor/executor_test.go, workflow/progress/updater.go, workflow/progress/updater_test.go
port of argo-workflow pod progress code to current codebase and extended to handle EOF streams.
most of the code is by @alexec from: https://github.com/argoproj/argo-workflows/pull/4015/files
closes #1658, #4245
I just started to test this code in my cluster, therefore I'd like to wait with considering this PR ready until I'm more confident. 
An initial review would be great though!
I didn't implement the part with reporting also a progress message as the whole pod status reporting got changed meanwhile and I'm not sure if we need it anyway. 
Thanks :)
=> feat: self-reporting workflow progress. Fixes #1658, #4245

test/e2e/cli_test.go, test/e2e/smoke/basic-invalid.yaml, workflow/common/parse.go
When submitting a file with invalid YAML the CLI output is not helpful:
```
$ argo submit invalid.yaml
INFO[2021-11-02T12:25:12.398Z] No Workflow found in given files
```
This PR prints the relevant YAML parsing error
```
$ argo submit invalid.yaml
ERRO[2021-11-02T12:25:12.397Z] yaml file at index 0 is not valid: error converting YAML to JSON: yaml: line 12: did not find expected key
INFO[2021-11-02T12:25:12.398Z] No Workflow found in given files
```
* Say …
=> fix: Return error when YAML submission is invalid

.github/workflows/ci-build.yaml
GitHub Actions runs CI checks in order. Sometimes they get throttled, so required checks only run after non-required checks finish. If a required check if flakey, it will be useful to know if it fails as soon as possible, so the run can be cancelled and CI re-run.
Example from this PR:
Tips:
* Add you organization to …
=> build: Reorder CI checks so required checks run first

.gitattributes
Python is recognized as the main language of this repo but most of the Python code is auto-generated and shouldn't be included as part of the classification.
Reference: https://github.com/github/linguist/blob/master/docs/overrides.md#generated-code
=> chore: Add .gitattributes to ignore generated Python code for linguist

.github/workflows/ci-build.yaml, .gitignore, Makefile
=> chore: publish CI test results

ui/src/app/event-sources/components/event-source-list/event-source-list.tsx, ui/src/app/pipelines/components/pipeline-list/pipeline-list.tsx, ui/src/app/sensors/components/sensor-list/sensor-list.tsx
=> fix(ui): Correctly show zero-state when CRDs not installed. Fixes #7001

docs/retries.md
I didn't realize that kubeflow pipelines was using an argo version too old to get certain retry features, so thought I'd add version requirements to the docs.
cc @jli
Signed-off-by: Josh Carp <jm.carp@gmail.com>
Tips:
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if …
=> docs: Document version requirements for newer retry features.

workflow/executor/executor_test.go
Fixes #7148
Testing: ✅ 
Unit tests are sufficient, given this is a unit test change.
=> fix(test): Make TestMonitorProgress Faster

server/clusterworkflowtemplate/cluster_workflow_template_server.go, server/clusterworkflowtemplate/cluster_workflow_template_server_test.go, server/workflow/workflow_server.go, server/workflow/workflow_server_test.go, server/workflowtemplate/workflow_template_server.go, server/workflowtemplate/workflow_template_server_test.go, workflow/util/util.go, workflow/validate/validate.go, workflow/validate/validate_test.go
This change allows linting and creation of workflow templates without requiring parameter values. As best as I can determine, this fixes a regression of previous behavior.
------
Unit tests were added to prove the behavior shown below.
Using this workflow example from the issue, I can lint and create a template without specified parameter values.
```a.yaml
metadata:
name: hello-world-parameters
spec:
arguments:
parameters:
templates:
container:
image: docker/whalesay
command: [ cowsay ]
args: [ "{{workflow.parameters.message}}" ] 
```
Lint:
```
$ ~/git/argo-workflows/dist/argo lint ./a.yaml 
✔ no linting errors found!
```
Create:
```
$ ~/git/argo-workflows/dist/argo template …
```
=> fix: allow wf templates without parameter values (Fixes #6044)

cmd/argo/commands/resubmit.go, docs/cli/argo_resubmit.md
This flag has been there for several years and it's been working well so proposing to remove the "experimental" in the doc.
Tips:
=> docs(cli): Move --memoized flag from argo resubmit out of experimental

hack/port-forward.sh
This is a very simple change that changes the `sleep` bash command syntax to a format that should work everywhere.
For some unknown reason, the new macOS 12 ships with a `sleep` command which has to be called like `sleep 1` rather than `sleep 1s`.
=> fix: ci sleep command syntax for macOS 12

ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, ui/src/models/workflows.ts
For [this example](https://github.com/argoproj/argo-workflows/blob/master/examples/init-container.yaml), we cannot view user supplied init container logs in the UI. The log is available via `kubectl logs` though.
The custom init container name `hello` should show up in the selections.
Before the change:
After the change:
=> feat(ui): Support log viewing for user supplied init containers

ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
This fixes a bug where an empty regex applied to all log lines would prefix every characters with `\u001b[1m\u001b[43;1m\u001b[37m\u001b[0m` (normally used to wrapped RegExp matches for highlighting). This bug removes any formatting made using ANSI color sequences.
Before:
After:
Fixes https://github.com/argoproj/argo-workflows/issues/7189
Signed-off-by: Guillaume Fillon <guillaume.fillon@auth0.com>
=> fix: Fix ANSI color sequences escaping

hack/git/hooks/commit-msg
This doesn't seem necessary if the message looks good.
```
$ git commit -m "chore: Remove unnecessary message in commit-msg git hook"
Your commit message is acceptable
[master 0a22ec1d] chore: Remove unnecessary message in commit-msg git hook
1 file changed, 1 deletion(-)
```
=> chore: Remove unnecessary message in commit-msg git hook

docs/running-locally.md
This PR updates the path we suggest checking out code into for local development from `$(GOPATH)/src/github.com/argo-workflows` to `$(GOPATH)/src/github.com/argoproj/argo-workflows`, as it was previously incorrect.
=> docs: fix checkout path for local dev

ui/src/app/reports/components/reports.tsx, ui/src/app/shared/services/workflow-template-service.ts, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx, ui/src/app/workflows/components/workflow-creator.tsx, ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx
Co-authored-by: Adrian Wawrzak <wawrzak.adrian@ericsson.com>
In case of higher number of templates, especially over slow internet connection there is no reasonable time the request can be completed giving us nothing in return. Workflow templates pagination is meant mainly to help with that. If you see drawbacks of having it implemented only in UI component, please consider another enhancement to this implementation. We would appreciate if it could get in any form into some upcoming release (although it is NOT critically urgent).
=> feat(ui): add pagination to workflow-templates.

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/fields.md, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1Template.md, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1Template.md, sdks/python/client/openapi_client/model/io_argoproj_workflow_v1alpha1_template.py
=> docs: fix typo timout -> timeout

cmd/argo/commands/archive/get.go, cmd/argo/commands/get.go
**What was the issue?**
When submitting a workflow using `argo submit somefile.yaml`, if the workflow does not explicitly specify a `spec.serviceAccountName`, the output of the command would look like this: 
```
❯ argo submit workflow-artifact-repo-ref-test.yaml
Name:                artifactory-repository-ref-vp472
Status:              Pending
Created:             Thu Nov 18 15:24:57 +0100 (now)
Progress:
```
The important bit here is the `ServiceAccount: default` bit. In my case, I have configured a default ServiceAccount in the `workflowDefaults` section of the workflow-controller configmap. This means that my workflow will not run with `ServiceAccount: default`, but with the ServiceAccount I specified there. See the command below: …
=> fix: improve feedback to user when submitting a workflow from the CLI w/o a serviceaccount specified

docs/argo-server-sso.md
docs: Mention default callback address endpoint in SSO docs 
Signed-off-by: jmeridth <jmeridth@gmail.com>
=> docs: Update SSO documentation to mention default callback address endpoint

examples/suspend-template-outputs.yaml
The comments above uses `argo node set suspend-outputs` so we need a fixed workflow name. 
=> docs: Fix workflow name in suspend outputs example

util/env/env.go, util/env/env_test.go
Set but empty env vars should use the default value instead of panic-ing
Tips:
=> fix: Use default value for empty env vars

workflow/util/util.go
=> fix: pod name shown in log when pod deletion

ui/src/app/workflows/components/submit-workflow-panel.tsx
When we have large workflows, it has some delays to submit workflow in workflow template ui. At that time, UI has no feedback.
After clicking submit button, the button shows `Loading...`.
https://user-images.githubusercontent.com/915731/144739056-a42f8242-f858-4f46-b6db-134a25fe7366.mov
=> feat(ui): submit workflow make button disable after clicking

server/workflowarchive/archived_workflow_server.go, server/workflowarchive/archived_workflow_server_test.go
Error message that is returned when user tries to list archived workflows and doesn't specify a namespace is very generic and hard to understand. This PR tries to make it a bit more clear as to what might be the cause of the issue, to help guide the user.
I thought that it might be a good idea to check if `namespace` is an empty string, and if it is, return a custom error for this case, telling user that `namespace` can't be empty. But I assume that this would not be correct for cases when Argo-Workflows runs with ClusterRole permissions?
=> fix: improve error message for ListArchivedWorkflows

workflow/util/util.go, workflow/util/util_test.go
node has TemplateRef.Template field rather than TemplateName field
fixes #7315 
Tips:
=> fix: argument of PodName function (fixes #7315)

workflow/executor/agent.go, workflow/executor/agent_test.go
=> fix: Propogate errors in task worker and don't return

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/regression.md
The rest of the diagnostics are only necessary when workflow pods have been created.
=> chore: Add a note on when to provide diagnostics for workflow pods

workflow/common/configmap.go
Fixes #7356. Currently the error message is misleading as the configmap exists in the specified namespace.
=> chore: Improve error message when configmap is not found. Fixes #7356

docs/memoization.md
Signed-off-by: roofurmston <thomas.furmston@deliveroo.co.uk>
This PR aims to improve the documentation for the memoization page in the following ways:
- It removes the beta tag on the page. (From discussion in the Argo Workflow slack channel it was indicated that this feature is no longer in beta.)
- Adds a note on changes required to the default installation in order to use step memoization. 
Rationale, there have been several issues in Github in which people have had difficulty implementing the simple memoization example. One cause was people having difficulty with the required permissions. For example, [https://github.com/argoproj/argo-workflows/issues/6942](https://github.com/argoproj/argo-workflows/issues/6942).
Also, as a tangential point, currently memoization has consistent …
=> docs: remove memoization beta and add install note

workflow/validate/validate.go, workflow/validate/validate_test.go
#7383
If an `initContainer` omits the `name` key, the workflow will immediately fail now.
Example workflow from original issue:
```
kind: Workflow
metadata:
generateName: spurious-
spec:
templates:
- name: main
dag:
tasks:
- name: spurious
template: spurious
- name: spurious
retryStrategy:
retryPolicy: Always
initContainers:
- image: alpine:latest
command:
- sleep
- "15"
container:
command:
- echo
- "i am running"
```
Output:
```
FATA[2021-12-14T11:11:46.032Z] Failed to submit workflow: templates.main.tasks.spurious initContainers must all have container name
```
=> fix: added check for initContainer name in workflow template

.github/workflows/sdks.yaml
Currently this is also running on master branch, which would fail the CI. Example: https://github.com/argoproj/argo-workflows/runs/4534564425?check_suite_focus=true
=> fix: Disable SDK release from master branch

sdks/python/Makefile, sdks/python/sdk_version.py
When the Python SDK was migrated to the Argo Workflows repository, we kept the `argo-workflows` name for the Python
package as we wanted to publish it to the same PyPi project on the public index. However, the existing `argo-workflows`
package was on version 5.0.0 already, while Argo Workflows was on 3.x.x. We wanted to publish the SDK as version 6.0.0
to indicate backwards incompatibility. So, this script takes the Argo Workflows tag, when a new release is created,
takes the major version, adds 3 to it, and prints to stdout the new version, which is:
- ARGO_MAJOR+3.ARGO_MINOR.ARGO_PATCH
Fixes: #7423 
Functional testing:
```
((python) ) ➜  python git:(fv/py-sdk-versioning) ✗ ./sdk_version.py …
```
=> feat: Add Python SDK versioning script

docs/http-template.md, docs/variables.md, examples/http-success-condition.yaml
See discussion in https://github.com/argoproj/argo-workflows/discussions/7376#discussioncomment-1820675. It's better to add a version in the doc. v3.3 is kind of predicted. If there's a better practice, please let me know.
=> docs: Add a note on version for HTTP template successCondition

workflow/controller/operator.go, workflow/controller/operator_workflow_template_ref_test.go
fixes #7266 
Example output: 
```
Name:                cluster-workflow-template-hello-world-lk5vb
Status:              Error
Message:             cannot get resource clusterWorkflowTemplate at cluster scope
Conditions:          
Completed           True
Created:             Fri Dec 17 09:20:15 -0800 (1 minute ago)
Started:             Fri Dec 17 09:21:19 -0800 (1 second ago)
Finished:            Fri Dec 17 09:21:19 -0800 (1 second ago)
Duration:            0 seconds
Progress:            0/0
This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```
=> fix: submitting cluster workflow template on namespaced install returns error

docs/fields.md, examples/k8s-json-patch-workflow.yaml
As there is an example how to patch a k8s pod with new **annotations**, it is a bit different in case of the **workflow** crd resource. 
I spent some time trying to patch a workflow with annotations (for easier searching by custom fields), used an example how to patch a pod, but ended up with "invalid request" errors from `kubectl` while trying to apply the patch during workflow run.
Turned out it needs `labels` instead of `annotations`. Kinda obvious, but not that easy to catch
✔️ Sign-off your commits to pass the DCO check: `git commit --signoff`.
✔️ Say how how you tested your changes. If you changed the UI, attach screenshots.
I have run the example on my argo installation and then checked results in the UI, see the screenshoot below
=> docs: patching workflow with labels example

docs/mentoring.md
=> docs: Fix typo mentees -> mentors

docs/workflow-templates.md
I think there is a problem in [workflow-templates.md](https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-templates.md?plain=1#L158)
The problem is:
In WorkflowTemplate
args: ["{{workflow.parameters.global-parameter}}"] is `global-parameter` here.
But in Workflow,
It is referred as `global`
=> docs: Fixing the missing -parameter word in workflow-templates docs

workflow/metrics/metrics_test.go, workflow/metrics/work_queue_test.go
The workqueues created in `TestWorkflowQueueMetrics` and `TestMetricsWorkQueue` will leak goroutines if we  don't shutdown them in the end of tests:
```
leaks.go:82: found unexpected goroutines:
[Goroutine 36 in state chan receive, with k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop on top of the stack:
goroutine 36 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000364f60)
/home/yuanting/work/dev/goprojects/argo-workflows/vendor/k8s.io/client-go/util/workqueue/queue.go:204 +0xa7
created by k8s.io/client-go/util/workqueue.newQueue
/home/yuanting/work/dev/goprojects/argo-workflows/vendor/k8s.io/client-go/util/workqueue/queue.go:62 +0x1af
]
```
=> fix: Shutdown workqueues to avoid goroutine leaks

pkg/apis/workflow/v1alpha1/marshall.go, pkg/apis/workflow/v1alpha1/marshall_test.go
This adds a more readable and easier recoverable message for the case when the input is of length 0. 
This was reported by OSS-fuzz ([issue 43202](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43202)).
=> fix: out of range in MustUnmarshal

docs/variables.md
Based on the field reference, `expression` is the correct field name rather than `when`. https://argoproj.github.io/argo-workflows/fields/#fields_14
=> docs: fix retryStrategy field name

workflow/progress/updater.go, workflow/progress/updater_test.go
To me the PR is ready but i'm not able to try it locally as stated in #7436 
That's why i left it as Draft
=> fix: http template doesn't update progress. Fixes #7239

util/wait/backoff.go, workflow/artifacts/s3/errors.go, workflow/artifacts/s3/s3.go, workflow/artifacts/s3/s3_test.go, workflow/executor/executor.go, workflow/executor/retry/retry.go
When connection problems occur while loading artifacts, the workflow init step exits and the workflow fails. This is a regression.
We propose a fix in this PR for issue: #7349.
Fixes #7349
In this PR we add an extra check for Transient errors every time the S3 Transient errors are checked.
Tips:
* Add you organization to …
=> fix: transient errors for s3 artifacts: Fixes #7349

workflow/util/util.go
An issue was found by a fuzzer whereby `nil` can be passed to `ApplySubmitOpts` and a nil-dereference would occur on [this line](https://github.com/argoproj/argo-workflows/blob/26c1224b0d8b0786ef1a75a58e49914810d3e115/workflow/util/util.go#L243):
`wfLabels := wf.GetLabels()`
This PR fixes that.
=> fix: nil-pointer in ApplySubmitOpts

docs/container-set-template.md
Diamond DAG e.g. a diamond `a -> b -> d` and  `a -> b-> d`, i.e. `b` and `c` run at the same time.  
Maybe replace  `a -> c-> d` with `a -> b-> d`
=> docs: fix typo in container-set-template.md

util/unstructured/workflow/conditions.go
Fixes a crash found by [the operator fuzzer](https://github.com/cncf/cncf-fuzzing/blob/main/projects/argo/operator_fuzzer.go) where the type assertion of `m["type"]` and `m["status"]` would crash Argo because either was `nil`.
@terrytangyuan @hblixt @jannfis
OSS-fuzz issue: https://oss-fuzz.com/testcase-detail/4663831211671552
=> fix: Fix type assertion bug

cmd/argo/commands/cron/list.go
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>
Added the timezone to the output of argo cron list):
```
NAME                         AGE   LAST RUN   NEXT RUN   SCHEDULE                           TIMEZONE     SUSPENDED
my-cron-workflow-c90cadee    20h   2h         14h        45 12,13,14,15,16,17,18,19 * * *                false
my-cron-workflow2-f4f27c90   20h   20h        26s        * * * * *                          US/Central   true
```
Note that the timezone field is empty when there is no timezone specified in the CronWorkflow object.  Since the cron server appears to default to UTC when no timezone is specified (at least as I understand that time.Now() returns the local time in UTC), would it make …
=> feat: Adds timezone to argo cron list output (#7557)

workflow/controller/operator.go, workflow/controller/operator_test.go
Signed-off-by: Peixuan Ding <dingpeixuan911@gmail.com>
Hi, this PR fixes an issue where `supplied` workflow parameters are not correctly set in the global parameters. See #7563 for more details.
For example, in the following workflow template, the parameter `name` is supplied by UI or CLI. However, it will not be set in the global parameters because both `valueFrom` and `value` exist at the runtime. The workflow controller only looks for `configMapKeyRef` when `valueFrom` is set.
```yaml
metadata:
name: workflow-template-whalesay-template
spec:
arguments:
parameters:
- name: name
valueFrom:
supplied: {}
entrypoint: whalesay-template
templates:
- name: whalesay-template
container:
image: docker/whalesay
args: …
```
=> fix: Fix supplied global workflow parameters, fixes 

workflow/controller/operator.go, workflow/controller/steps.go, workflow/controller/steps_test.go, workflow/metrics/util.go, workflow/validate/validate.go, workflow/validate/validate_test.go
- Fixes #6053 
I submitted this workflow:
```
kind: Workflow
metadata:
generateName: whale-my-resources-
spec:
metrics:
prometheus:
- name: duration
help: duration
gauge:
realtime: false
value: "{{resourcesDuration.cpu}}"
templates:
script:
image: alpine:3
command: [/bin/sh]
source: |
sleep 20
```
The metrics were logged without error.
I then changed the workflow to use `realtime: true` and submitted again, with the same result.
=> fix: resolve resourcesDuration

ui/src/app/cron-workflows/components/pretty-schedule.tsx, ui/src/app/cron-workflows/components/schedule-validator.tsx
argo-workflows doen't support cron `second`, but it is possible to create from yaml. At that time cron workflow ui doesn't show error.
```yaml
kind: CronWorkflow
metadata:
name: my-cronworkflow-template-1
spec:
schedule: "*/2 * * * * *"
workflowSpec:
entrypoint: whalesay-template
workflowTemplateRef:
name: my-workflow-template-1
arguments:
parameters:
- name: message1
value: hello from cron
```
Copy schedule validator from cron editor has schedule validator into pretty-schedule.
https://github.com/argoproj/argo-workflows/blob/d7a1e16514e30a197c53296b270748647c615bbb/ui/src/app/cron-workflows/components/schedule-validator.tsx#L8-L20
=> fix: show invalid cron schedule error on cron status ui

examples/buildkit-template.yaml
I spent a few hours trying to figure out why the example in buildkit-template.yaml was not working with a private insecure docker registry.
The problem was a bug in the moby/buildkit version used in this example: moby/moby#40814. I updated the version so other people waste time like I did.
=> fix: update old buildkit version in buildkit-template.yaml

cmd/argo/commands/list.go, cmd/argo/commands/list_test.go
Fixes #7581
Hi, this PR fixes an issue where `argo list -o name` has inconsistent display order than `argo list`. The root cause is that we sort workflows based on `CreationTimestamp` and `FinishedAt`:
https://github.com/argoproj/argo-workflows/blob/f1fe3bee498ac7eb895af6f89a0eba5095410467/pkg/apis/workflow/v1alpha1/workflow_types.go#L130-L145
So we need to make sure these two fields are included in the name-only field selectors as well, in order to have a consistent sort.
Workflows have inconsistent display order with / without `-o name`
Workflows have consistent display order now
Thanks!
Signed-off-by: Peixuan Ding <dingpeixuan911@gmail.com>
=> fix: Fix inconsistent ordering of workflows with the list command. 

ui/package.json, ui/src/app/event-flow/components/event-flow-details/event-flow-page.tsx, ui/src/app/event-sources/components/event-source-log-viewer.tsx, ui/src/app/pipelines/components/pipeline-logs-viewer.tsx, ui/src/app/sensors/components/sensor-logs-viewer.tsx, ui/src/app/shared/components/dropdown/dropdown.tsx, ui/src/app/shared/services/event-source-service.ts, ui/src/app/shared/services/pipeline-service.ts, ui/src/app/shared/services/requests.ts, ui/src/app/shared/services/sensor-service.ts, ui/src/app/shared/services/workflows-service.ts, ui/src/app/shared/utils.ts, ui/src/app/workflows/components/events-panel.tsx, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx, ui/src/app/workflows/components/workflow-timeline/workflow-timeline.tsx, ui/yarn.lock
mainly upgrade [rxjs 6.x](https://github.com/ReactiveX/rxjs/blob/6.x/docs_app/content/guide/v6/migration.md).
@types/react-form/react-helmet/react-autocomplete are deleted from argo-ui, but argo-workflows uses them.
```sh
yarn upgrade argo-ui@"https://github.com/argoproj/argo-ui.git#v2.5.0"
yarn add -D '@types/react-form@^2.16.1' '@types/react-helmet@^6.1.0' '@types/react-autocomplete@^1.8.5'
```
argo-ui@v2.5.0 is required for https://github.com/argoproj/argo-workflows/pull/7387
----
<details>
<summary>autocomplete</summary>
</details>
<details>
<summary>workflow logs</summary>
https://user-images.githubusercontent.com/915731/150440630-68b956e8-bcac-44c5-9f4e-cdc751c4808f.mov
</details>
<details>
<summary>dropdown</summary>
</details>
<details>
<summary>timeline</summary> …
=> chore: upgrade argo-ui v2.5.0

docs/executor_plugins.md
Signed-off-by: Peixuan Ding <dingpeixuan911@gmail.com>
Hi, I've been trying the executor plugin and found several issues with the docs. This PR fixes them. Please see the inline comments for more details.
Thanks!
=> docs: Fix executor plugin example in docs

workflow/common/util.go, workflow/common/util_test.go
This adds support for overridable default input artifacts as described in  #2026. An earlier PR was opened in #7341 but it was not showing the diff accurately due to https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch hence this was opened.
=> feat: add overridable default input artifacts #2026 

util/tls/tls.go
Fixes #7632
**PLEASE NOTE**:
- [InsecureSkipVerify](https://pkg.go.dev/crypto/tls#:~:text=InsecureSkipVerify%20bool) is not relevant in the context of a server, as it is for client config so "crypto/tls accepts any certificate presented by the server and any host name in that certificate". In short, this line shouldn't be here
- As far as I can see, it seemed to be needed because it (as a part of `tls.Config` is passed into `apiserver.ArgoServerOpts` (seen [here](https://github.com/argoproj/argo-workflows/blob/master/cmd/argo/commands/server.go#L161))
- In turn, I think this `InsecureSkipVerify: true` is used in other areas ([here](https://github.com/argoproj/argo-workflows/blob/1df69afb6fa57598862edc083c6c0b968e728035/server/auth/sso/sso.go#L131) for instance)
- The correct way, would be …
=> fix: TLS problem in UI. Fixes #7632

.github/workflows/gh-pages.yaml
This reverts commit 17342bacc991c1eb9cce5639c857936d3ab8c5c9 as it breaks the pages deployment: https://github.com/argoproj/argo-workflows/runs/4954762195?check_suite_focus=true
The error is ` Error: Action failed with "not found deploy key or tokens"`, which needs to be looked into separately. My guess is the existing way that configured the personal token is not compatible with the new version.
=> chore: Revert "chore(deps): bump peaceiris/actions-gh-pages from 2.5.0 to 3.8.0 (#7642)"

cmd/argo/commands/get.go, cmd/argo/commands/get_test.go, test/e2e/fixtures/then.go, workflow/controller/operator.go, workflow/controller/workflowpod.go, workflow/util/pod_name.go, workflow/util/pod_name_test.go, workflow/util/util.go
This PR:
- Invokes the workflow utils PodNames function in the cmd printNode function to add the updated pod name to the printout
- Modifies the PodNames function to take the version as a parameter, allowing it to be invoked in the cli when the `POD_NAMES` environment variable isn't present
- Fixes #7646 
```
Name:                dag-diamond-xtpd7
Status:              Succeeded
Conditions:
PodRunning          False
Completed           True
Created:             Wed Jan 26 16:32:00 -0500 (13 seconds ago)
Started:             Wed Jan 26 16:32:00 -0500 (13 seconds ago)
Finished:            Wed Jan 26 16:32:13 -0500 (now)
Duration:            13 seconds
Progress:            4/4
ResourcesDuration: …
```
=> fix: Match cli display pod names with k8s. Fixes #7646

go.mod, go.sum, pkg/apiclient/argo-server-client.go, server/apiserver/argoserver.go
=> chore(deps): bump google.golang.org/grpc from v1.38.0 to v1.41.1

sdks/python/sdk_version.py
=> fix: Handle release candidate versions in Python SDK version. Fixes #7692

workflow/validate/validate.go, workflow/validate/validate_dag_test.go
=> fix: Fix argo lint panic when missing param value in DAG task. Fixes #7701

sdks/python/README.md, sdks/python/examples/hello-world-from-object.py, sdks/python/examples/hello-world-from-raw-yaml.py
See https://github.com/argoproj/argo-workflows/issues/7293#issuecomment-1024731592. 
=> docs: Correct the use of _check_return_type in Python SDK examples

server/artifacts/artifact_server.go, server/artifacts/artifact_server_test.go
Signed-off-by: Paco Guzman [pacoguzmanp@gmail.com](mailto:pacoguzmanp@gmail.com)
Fixes https://github.com/argoproj/argo-workflows/issues/7717
---
Tips:
=> fix: artifacts.(*ArtifactServer).GetInputArtifactByUID ensure valid request path. Fixes #7717

server/auth/gatekeeper.go
ref https://github.com/argoproj/argo-workflows/issues/4271
I want to know who call api. 
Currently gatekeeper SSO log has audit feature, but there is no `Email` information. If not, it is difficult to figure out who call api.
In this PR, I add `claims.Email` into gatekeeper audit log like a following.
```
argo-server | time="2022-02-04T22:44:08.800Z" level=info msg="selected SSO RBAC service account for user" email=kilgore@kilgore.trout loginServiceAccount=argo-server serviceAccount=argo-server ssoDelegated=false ssoDelegationAllowed=false subject=Cg0wLTM4NS0yODA4OS0wEgRtb2Nr
```
=> feat: add claims.Email into gatekeeper audit log entry

ui/src/app/shared/pod-name.test.ts, ui/src/app/shared/pod-name.ts
Signed-off-by: J.P. Zivalich <jp@pipekit.io>
This PR:
- Falls back to the v1 pod names in the UI if no templateName or templateRef is set on a given node - my hypothesis is that certain virtual nodes might not have a a templateName or templateRef set as seen here: https://github.com/argoproj/argo-workflows/issues/7595#issuecomment-1017776672
- Fixes #7595 
@liuzqt Could you run one of your workflows locally using this PR branch to test if it is working? I want to validate that I don't have to make an additional change to the workflow controller
=> fix: Use v1 pod name if no template name or ref. Fixes #7595 and #7749

ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-details/cluster-workflow-template-details.tsx, ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx, ui/src/app/workflows/components/submit-workflow-panel.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
I want to input multiline parameter into Submit Workflow form.
- ~~Add `inputType: string` field into parameter~~
- ~~Currently this field accept 'textarea' only. It would be used for `date`, `checkbox`, and so on.~~
- based on https://github.com/argoproj/argo-workflows/pull/7768#discussion_r800222295, this feature is discarded.
- Change single value parameter form with `textarea`
- Increase submit workflow panel width.
close https://github.com/argoproj/argo-workflows/issues/7696
=> feat: submit workflow form parameter uses textarea input

cmd/argo/commands/get.go, pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, util/printer/workflow-printer.go
fixes #7726 
Previously if a user started a Workflow from a WorkflowTemplate using the CLI, the serviceAccount and securityContext was not set based upon the StoredWorkflowSpec like is expected. Now, when serviceAccount and securityContext are checked for in `get.go`, `GetExecSpec()` is run to check if `wf.Status.StoredWorkflowSpec` is set or not. If so, it will reference this spec instead as expected.
Example WorkflowTemplate:
```
metadata:
name: my-workflow-template-test
namespace: argo
spec:
securityContext:
runAsNonRoot: false
serviceAccountName: argo
templates:
- name: main
metadata:
container:
command:
- bash
- -c
- echo 'Hello from WT'; env; sleep 15
image: ubuntu
name: main
```
Submitting through CLI:
``` …
```
=> fix: submitting Workflow from WorkflowTemplate will set correct serviceAccount and securityContext. Fixes #7726

manifests/base/argo-server/argo-server-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
Signed-off-by: Vrukshali <tvrukshali@gmail.com>
Fixes https://github.com/argoproj/argo-workflows/issues/7285
=> fix: Add env to argo-server deployment manifest. Fixes #7285

docs/executor_plugins.md
Refs #7683 
I improved the "Executor Plugins" docs page:
* Explain that `argo executor-plugin build` assumes the script is saved in `server.* `
* Pretty print the args + disable stdout buffering so that it's easy to understand the RPC
* Add the UID for the `nobody` user to make the given plugin runnable (before that it would complain that `runAsNonRoot` is true but the image uses UID 0 per default)
=> docs: Improve consistency of plugin template docs

cmd/argoexec/commands/emissary_test.go, workflow/artifacts/git/git_test.go, workflow/artifacts/s3/s3_test.go, workflow/executor/executor_test.go, workflow/util/util_test.go
A small enhancement here.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

server/workflow/workflow_server.go
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43808&q=argo&can=1
The crash occurs because `req.Workflow` is `nil`:
https://github.com/argoproj/argo-workflows/blob/0e80356f06bf3e2d29b1c12bd1ed2412bc9ee211/server/workflow/workflow_server.go#L497-L501
`nil` is passed to:
https://github.com/argoproj/argo-workflows/blob/0e80356f06bf3e2d29b1c12bd1ed2412bc9ee211/util/instanceid/service.go#L31-L37
... where it is then passed to:
https://github.com/argoproj/argo-workflows/blob/0e80356f06bf3e2d29b1c12bd1ed2412bc9ee211/util/labels/labeler.go#L8-L13
... where it fails when `obj.GetLabels()` is called.
This PR adds an early check for `req.Workflow`.
=> fix: Add nil-check in LintWorkflow

Dockerfile.windows
Fixes #7931 
The newest chocolatey package for docker-cli v20.10.12 places the binary in a `docker` subdirectory.
=> fix: Fix broken Windows build

workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/steps.go
When `when` is not parameterized and evaluates to false, we skip resolving artifact.
But later withSequence (step/task expansion) still attempts to resolve the artifact causing the pipeline error
Fixes #7940 
Error
`failed to resolve {{tasks.get-items.outputs.artifacts.items}}`
<details>
<summary>Workflow</summary>
```
kind: Workflow
metadata:
namespace: argo
generateName: handle-large-output-results-
spec:
entrypoint: handle-large-output-results
templates:
- name: handle-large-output-results
dag:
tasks:
- name: get-items
template: get-items
- name: sequence-param
template: echo
dependencies: [get-items]
when: 1 != 1
arguments:
parameters:
- name: index
value: "{{item}}"
artifacts:
- name: items
from: "{{tasks.get-items.outputs.artifacts.items}}" …
```
=> fix(controller): skip resolve artifact if withSequence is skipeed. Fixes #7940 

.gitignore, pkg/apis/workflow/v1alpha1/progress.go, workflow/progress/updater.go, workflow/progress/updater_test.go
Fixes #7918
Fixes #7925 
This PR also include what I think is a correction to behaviour. Previously failed/error nodes were considered complete. That seems incorrect to me. I think only succeded nodes should count.
=> fix: Report container, plugin and HTTP  progress. Fixes #7918

USERS.md, workflow/controller/controller.go
Should fix https://github.com/argoproj/argo-workflows/issues/7613
Signed-off-by: Shyukri Shyukriev <shyukri.shyukriev@mariadb.com>
Fixes #7613
=> fix: Fix/client go/releaseoncancel. Fixes  #7613

.github/workflows/ci-build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, hack/git/hooks/commit-msg
This frees up Github runners for other builds, reducing delay in CI feedback.
=> ci: Auto-cancel redundant builds

mkdocs.yml
Signed-off-by: caelan-io <45773958+caelan-io@users.noreply.github.com>
Adds lifecyclehook doc to mkdocs.yml to appear in the online documentation.
Thanks @alexec for reminder.
=> docs: Add lifecyclehook doc to mkdocs.yml

util/errors/errors.go, util/errors/errors_test.go
fix(executor): Retry kubectl on internal transient error
Signed-off-by: wujayway <wujayway@gmail.com>
Fixes fix(executor): Retry kubectl on internal transient error
This PR(https://github.com/argoproj/argo-workflows/pull/6472, https://github.com/argoproj/argo-workflows/issues/6467) only fix retry kubectl on k8s api error.
We also need to retry kubectl on internal transient error.
=> fix(executor): Retry kubectl on internal transient error

workflow/util/plugins/configmap.go, workflow/util/plugins/plugin.go
Changes:
* `Content-Type` header is added to `template.execute` RPC calls → apart from technical correctness this makes it easier to use because many frameworks rely on this header for JSON parsing
✅ Has an integration test in [test/e2e/executor_plugins_test.go](https://github.com/argoproj/argo-workflows/blob/9aa04a1493c01782ed51b01c733ca6993608ea5b/test/e2e/executor_plugins_test.go)
* `argo executor-plugin build .` copies the `metadata/namespace` from the plugin manifest to the ConfigMap
✅ Tested on my local machine
=> fix(plugins): UX improvements

test/e2e/artifacts_test.go, workflow/common/common.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
This was overlooked and means that certain workflows still need `get pods` permission.
See #4940
Depended on by #8120
=> fix: Remove need for `get pods` from Emissary

docs/cron-workflows.md
Fixes #8137
Minor clarification and format improvement. See #8137 for more details:
| Before                                                                                                                                                                                                                     	| After                                                                                                                                                                   	|
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------- …
=> docs: Minor improvement to the Cron schedule on day light saving time

persist/sqldb/sqldb.go
This PR adds a feature to setting mysql options for upper.io/db.v3/mysql
=> feat: add mysql options

workflow/executor/agent.go
Signed-off-by: wujayway <wujayway@gmail.com>
Fixes #8139
Use for loops instead of for range. Avoid go problems on `time.After` with closure.
=> fix: task worker requeue wrong task. Fixes #8139

docs/running-locally.md
Fixes e2e test docs steps indentation. 
Earlier : 
Now:
=> docs: minor tab indentation

examples/README.md
Update link to point to website spec documentation for Workflow rather than code.
=> docs: change examples workflow spec link from code to website docs

.github/workflows/ci-build.yaml, cmd/argoexec/commands/root.go, test/e2e/argo_server_test.go, test/e2e/fixtures/needs.go, test/e2e/run_as_not_root_test.go, test/e2e/signals_test.go, workflow/common/common.go, workflow/controller/workflowpod_test.go, workflow/executor/executor.go, workflow/validate/validate.go, workflow/validate/validate_test.go
=> fix: removed deprecated k8sapi executor. Fixes #7802

docs/workflow-restrictions.md
Fix a typo in the example config for workflow-restrictions, so the example will match the [reference file](https://argoproj.github.io/argo-workflows/workflow-controller-configmap.yaml).
Using the current example configuration would result in the following error:
```
invalid type for io.k8s.api.core.v1.ConfigMap.data: got "string", expected "map"
```
=> docs: typo in example for Workflow Restrictions

util/util.go
=> fix: do not panic when termination-log is not writeable. Fixes #8220

cmd/argo/commands/archive/resubmit.go, cmd/argo/commands/archive/retry.go, cmd/argo/commands/archive/root.go, docs/cli/argo_archive_resubmit.md, docs/cli/argo_archive_retry.md, server/workflowarchive/archived_workflow_server.go, server/workflowarchive/archived_workflow_server_test.go, test/e2e/argo_server_test.go
Fixes #7907 
It is currently only possible for an archived workflow to be retried through the CLI by using `kubectl create` then `argo retry`. This feature removes the need to do this set of operations by retrying workflows directly from the archive with the argo CLI: `argo archive retry {uid}`. This cli command supports the wait, watch or log flags as `argo retry`.
=> feat: add archive retry command to argo CLI. Fixes #7907

.github/workflows/gh-pages.yaml
Fixes the issue when building docs page:
AttributeError: module 'jinja2' has no attribute 'contextfilter'
See https://github.com/mkdocs/mkdocs/issues/2799.
=> build: Pin jinja2==3.0.0 to fix pages deployment

.github/workflows/ci-build.yaml, .golangci.yml, Makefile
=> chore: Make `make lint` faster

workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix: improve error message when the controller is set `templateReferencing: Secure`

workflow/artifacts/git/git.go
Signed-off-by: Dillen Padhiar <dpadhiar99@gmail.com>
Fixes #8282 
Argo workflows could not checkout a git artifact if the branch name matched a local file in the repo. This is amended by using `git checkout rev --`. The double-hyphen denotes that everything before it is a branch and after is a path.
Example workflow: 
```
kind: Workflow
metadata:
generateName: input-artifact-git-
spec:
entrypoint: git-clone
templates:
- name: git-clone
inputs:
artifacts:
- name: argo-source
path: /src
git:
repo: https://github.com/dpadhiar/argo-cd-tokens.git
revision: "demo"
container:
image: golang:1.10
args: ["git status && ls && cat VERSION"]
workingDir: /src
```
Workflow controller logs:
```
logs | input-artifact-git-hkkgr init …
```
=> fix: git artifact checked out even if local file matches name of working branch. Fixes #8282

ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Signed-off-by: Dillen Padhiar <dpadhiar99@gmail.com>
Fixes #8297 
Previously, the default number of workflows displayed by the UI was 500. This can cause the UI to load for a long time if there are too many workflows being shown. Instead, we can list only by default to decrease this load.
=> fix: reduce number of workflows displayed in UI by default. Fixes #8297

ui/src/app/workflows/components/submit-workflow-panel.tsx
Fixes #7311
The following GIF shows the submission of the example workflow from https://github.com/argoproj/argo-workflows/issues/7311#issuecomment-1026411700.
* Workflow can be submitted with workflow parameters given, even if a non-default entrypoint is selected.
=> feat: Always Show Workflow Parameters

workflow/executor/executor.go
https://app.snyk.io/org/argoproj/project/e917d104-c0c4-477b-853c-9d1451b6f803
You can test these fixes locally:
```
$ snyk code test --severity-threshold=high ./workflow/executor 
Testing ./workflow/executor ...
✔ Test completed
Organization:      argoproj
Test type:         Static code analysis
Project path:      ./workflow/executor
✔ Awesome! No issues were found.
```
=> fix: Remove path traversal CWE-23

examples/README.md
Fixes a typo in `examples/README.md`: overriten => overridden
See: https://dictionary.cambridge.org/us/dictionary/english/overridden
=> fix: typo in examples/README.md: overriten => overridden

.github/workflows/gh-pages.yaml
New version has been released https://github.com/mkdocs/mkdocs/issues/2799 that should fix the issue we we had https://github.com/argoproj/argo-workflows/pull/8254.
=> chore: Upgrade mkdocs to 1.2.4 and remove unnecessary jinja2

go.mod, go.sum
Upgrades argoproj-labs/go-git fork to v5.4.4
This brings in a fix for support of gitmodules with absolute paths.
Fixes  #8377
=> fix: Absolute submodules in git artifacts. Fixes #8377

docs/configure-artifact-repository.md, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/base/minio/minio-deploy.yaml, manifests/quick-start/base/minio/minio-service.yaml
Minio is redirecting to random port when we try to access the dashboard with port forwarding using quick-start manifests.
Related discussion: https://stackoverflow.com/questions/68317358/minio-local-dashboard-is-not-opening
Potential solution: expose different port for dashboard
Signed-off-by: Grzegorz Bielski <pesiok@gmail.com>
=> fix: open minio dashboard on different port in quick-start

Dockerfile.windows
=> fix: Remove binaries from Windows image. Fixes #8417

util/errors/errors.go, workflow/controller/controller.go
My recent change has resulted in trying to SIGTERM the wait contain, when it no longer exists.
=> fix: Do not log container not found

.github/pull_request_template.md
Fixed sign-off flag in pull request template. Changed it from `--sign-off` to the correct `--signoff
=> docs: fixed sign-off flag of git commit

workflow/controller/controller.go, workflow/controller/exec_control.go, workflow/controller/pod_cleanup_key.go
Fixes #8545
Problem: When a step hits it deadline, we delete the pod. Because we delete the pod, we loose all information about the success or failure of the pod. Instead of deleting, we must SIGTERM the pod's containers.
=> fix: Terminate, rather than delete, deadlined pods. Fixes #8545

cmd/argo/lint/formatter_pretty.go, cmd/argo/lint/formatter_pretty_test.go, go.mod, go.sum, test/e2e/fixtures/e2e_suite.go, test/e2e/fixtures/given.go, test/e2e/fixtures/print.go
The author changed his username and package gomod path since version 1.0.1,
Causing Dependabot unable to update the package
Fixes #8643
=> fix: update go-color path/version

workflow/controller/exec_control.go
Signed-off-by: i342464 <kesavan.s@sap.com>
Fixes #8692
=> fix: Fixed podName in killing daemon pods. Fixes #8692

ui/src/app/shared/duration.ts
Fixes #8650
This increases the default number of significant figures when formatting durations.
Before:
After: 
Signed-off-by: Immanuel Buder <immanuel_buder@intuit.com>
=> feat: Increased default significant figures in formatDuration. Fixes #8650

api/jsonschema/schema.json, api/openapi-spec/swagger.json, manifests/base/crds/full/argoproj.io_clusterworkflowtemplates.yaml, manifests/base/crds/full/argoproj.io_cronworkflows.yaml, manifests/base/crds/full/argoproj.io_workflows.yaml, manifests/base/crds/full/argoproj.io_workflowtasksets.yaml, manifests/base/crds/full/argoproj.io_workflowtemplates.yaml, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1LifecycleHook.md, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_lifecycle_hook.py, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1LifecycleHook.md
Since we also support `templateRef`.
=> fix: Template in Lifecycle hook should be optional

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/startup.sh, .spelling, docs/running-locally.md
Fixes #8589
Tested with commands and access to UI
```
make argoexec-image
make start API=true PROFILE=mysql
make pre-commit -B
```
---
working:
- MacOS 12.2 with M1 Pro
- Microsoft Windows 10 Pro: 10.0.19044 Build 19044
- Ubuntu 20.04 LTS with Docker Desktop
not working
- Ubuntu 20.04 LTS with docker (The k3d does not detect dind correctly and end up using the incorrect setting when create k3s cluster)
---
with
- windows wsl2 with i7-11800h 16vcore 10GB ram
- macbook pro with m1 pro 8vcore 16GB ram
- Ubuntu 20.04 LTS i5-4200u 4vcore 6GB ram
(assuming all dependencies are preinstalled)
||locally win-wsl2|dev-container win-wsl2|dev-container mac-m1pro|dev-container ubuntu|
|-|-|-|-|-|
|dev-container build|na|7m|25m|17m|
|make pre-commit -B|3m30s|4m15s|11m30s|9m42s|
|make …
=> feat: running locally through dev container

.markdownlint.yaml, docs/running-locally.md, docs/workflow-executors.md
=> fix: mkdocs uses 4space indent for nested list

test/e2e/hooks_test.go, util/expr/argoexpr/eval.go, workflow/controller/exit_handler.go, workflow/controller/hooks.go
=> fix: Exit lifecycle hook should respect expression. Fixes #8742

docs/CONTRIBUTING.md
I think it'd be good to update the CONTRIBUTING doc sinced the `help wanted` label is removed
=> docs: update contributing label section

docs/quick-start.md
Remove a leftover "`" character
=> fix: fix a command in the quick-start page

.github/workflows/dependabot-reviewer.yml
The auto-approved/merged PRs land on forks and has diverged significantly from the upstream (since we got different dependabot PRs), e.g. https://github.com/terrytangyuan/argo-workflows (master branch in the fork is [18 commits ahead](https://github.com/terrytangyuan/argo-workflows/compare/argoproj:master...master), [132 commits behind](https://github.com/terrytangyuan/argo-workflows/compare/master...argoproj:master) argoproj:master.
=> build: Disable auto-approve/merge dependabot PRs on forks

README.md, USERS.md
Add Orchest to ecosystem.
Orchest is an open source data pipeline orchestrator based on Kubernetes, you can read more here: https://docs.orchest.io/
=> Add Orchest to ecosystem

cmd/argoexec/commands/artifact/delete.go, cmd/argoexec/commands/artifact/root.go, cmd/argoexec/commands/root.go, workflow/common/common.go
Fixes #8669 
Implemented `argoexec artifact delete` per Alex's original PoC for artifact garbage collection.
=> feat: add artifact delete to argoexec CLI. Fixes #8669

ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Signed-off-by: Dakota Lillie <dakota.lillie@icloud.com>
Fixes #8916
This PR addresses an issue where code blocks would overflow their container in the UI.
**Before:**
**After:**
I have tested this in Chrome, Firefox, and Safari. Safari does have an issue where the scrollbar does not increase the height of the element (notice the lack of padding below the code block):
Without the `hidden` overflow-y setting, this would cause an additional vertical scrollbar to appear. I'm inclined to believe this is a bug in Safari, as manually updating any height-related style in the browser, even a random one like "line-height", causes Safari to fix itself:
https://user-images.githubusercontent.com/20373585/173118493-043429b7-796f-4331-b2fc-df49fdee27e3.mov
Needless to say, changing the "line-height" in …
=> fix: long code blocks overflow in ui. Fixes #8916

workflow/controller/controller.go, workflow/controller/operator.go
After Controller leader election we need to make sure cluster Workflow Template Informer's cache is updated first. Otherwise, we call Lister() on it before it's ready.
Fixes #8956
=> fix: sync cluster Workflow Template Informer before it's used

docs/variables.md
Signed-off-by: Caelan U <caelan_u@pipekit.io>
Related to #8867 and #8960 
I think it makes sense to document this unintended behavior for now. @JPZ13 and I will be working on a partial fix, but we should collect more reproducible examples from the community as @tczhao noted in [his comment](https://github.com/argoproj/argo-workflows/pull/8867#pullrequestreview-987687004) on #8867.
=> docs: Add variable tag whitespace issue

workflow/controller/controller.go, workflow/hydrator/hydrator.go
Fixes #8976 
If a workflow fails to be hydrated / dehydrated, it can be hard to tell what the issue may be. Many times, it may be because the workflow is too large and thus this change will log the size of the workflow so they may investigate for this case.
=> feat: log workflow size before hydrating/dehydrating. Fixes #8976

util/errors/errors.go, util/errors/errors_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/9013
This treats `connection reset by peer` network errors as transient so that they can be retried.
=> Treat 'connection reset by peer' as a transient network error. Fixes #9013

pkg/apiclient/offline-workflow-service-client.go, server/clusterworkflowtemplate/cluster_workflow_template_server.go, server/workflow/workflow_server.go, server/workflowtemplate/workflow_template_server.go, workflow/controller/operator.go, workflow/util/util.go, workflow/validate/validate.go, workflow/validate/validate_dag_test.go, workflow/validate/validate_test.go
validate.ValidateWorkflow() no longer sets wfConditions so removing it to clean up the code
=> chore: remove unused code: validate.ValidateWorkflow() no longer sets wfConditions 

workflow/controller/operator.go
We shouldn't be performing this release logic except in the case of our returning.
=> fix: sync lock should be released only if we're retrying

test/e2e/cli_test.go, test/e2e/fixtures/given.go, test/e2e/testdata/retry-nested-dag-test.yaml, workflow/util/util.go, workflow/util/util_test.go
Currently, retry does not work on nested DAG and node groups. As a result, these node statuses will be missing. This PR fixes it.
=> feat: Support retry on nested DAG and node groups

ui/src/app/shared/pod-name.ts
Fixes #9167. This is a regression and needs to be backported.
=> fix: Workflow details accessing undefined templateRef. Fixes #9167

persist/sqldb/mocks/WorkflowArchive.go, persist/sqldb/null_workflow_archive.go, persist/sqldb/workflow_archive.go, server/workflowarchive/archived_workflow_server.go, server/workflowarchive/archived_workflow_server_test.go
Signed-off-by: hadesy <6346047+hadesy@users.noreply.github.com>
Fixes support RemainingItemCount in archivedWrokflow
=> fix: support RemainingItemCount in archivedWrokflow

workflow/controller/exec_control.go, workflow/controller/operator.go
golangcli-lint recently went from version 1.47.0 to 1.47.1. I think that must be why we're all of a sudden seeing this error:
`Error: workflow/controller/exec_control.go:18:50: (*wfOperationCtx).applyExecutionControl - ctx is unused (unparam)`
as here: https://github.com/argoproj/argo-workflows/runs/7419737341?check_suite_focus=true
=> fix: remove unused argument which is triggering in lint (needed for PRs to pass CI)

cmd/workflow-controller/main.go, workflow/controller/config.go, workflow/controller/controller.go, workflow/controller/workflowpod.go
related to: #7361
fixes #8986
TODO: add test
Signed-off-by: Hunter-Thompson <aatman@auroville.org.in>
=> feat: log format option for wait and init containers. Fixes #8986

ui/src/app/app-router.tsx, ui/src/app/shared/utils.ts
The namespace is `undefined` upon clicking the workflows tab on the lefthand menu (see screenshot). This can be resolved upon refreshing or re-opening the tab. The issue is that the namespace state variable in React is not being set after we get the user namespace. This PR will fix the issue.
=> fix: Set namespace to user namespace obtained from /userinfo service

docs/work-avoidance.md, mkdocs.yml
https://argoproj.github.io/argo-workflows/work-avoidance/ (404)
Is it deleted accidentally (in #8562) ?
=> docs: restore work-avoidance page

Makefile
See context in https://github.com/argoproj/argo-workflows/pull/9186. 
=> ci: Pin golangci-lint to v1.47.1

docs/argo-server.md, server/apiserver/argoserver.go, test/e2e/argo_server_test.go
Fixes #9205
https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html
=> feat: APIratelimit headers and doc

docs/walk-through/sidecars.md, examples/daemon-nginx.yaml, examples/daemon-step.yaml, examples/dag-daemon-task.yaml, examples/influxdb-ci.yaml, examples/validator.go
- Fix minor issues so that user can run examples without error
- Modified validator, ignores integer port number error
the integer port number error is due to the limitation of swagger 2.0 which only allows users to specify 1 data type for a given field.
https://github.com/argoproj/argo-workflows/blob/master/api/openapi-spec/swagger.json#L14353-L14355
=> fix: example wf, port data format and missing command

README.md
Update bash command, fix broken installation link in the `Quickstart` section to the raw [**quick-start-postgres**](https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-postgres.yaml) manifest and include a disclaimer regarding the installation.
This makes it consistent with the documentation's [quickstart section](https://argoproj.github.io/argo-workflows/quick-start/).
Signed-off-by: vedantthapa <thapavedant@gmail.com>
=> docs: Update and fix quickstart section

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/fields.md, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go
`limit` is currently ambiguous in documentation. It represents the maximum number of retries that will be attempted in addition to the first attempt. For example, `limit = 1` means two attempts total, `limit = 99` means one hundred attempts total, etc. This change attempts to clarify the ambiguity.
Fixes #TODO
=> docs: Update RetryStrategy.limit documentation

workflow/artifacts/azure/azure.go
In certain cases, if there is a failure reading from azure blob storage,
an empty error was used in the return error format string rather than
the correct original error.
Signed-off-by: Brian Loss <brianloss@gmail.com>
Fixes #TODO
=> fix: pass correct error obj for azure blob failures

workflow/artifacts/gcs/gcs.go
We have a function `isTransientGCSErr()` here which attempts to
`Unwrap()` errors which we have wrapped using `fmt.Errorf()`. This will
only work if the `%w` format string has been used, otherwise no
`Unwrap()` method is created.
This should enable retrying on transient GCS upload errors, and avoid
failures like
```
executor error: upload /tmp/argo/outputs/logs/main.log: writer close:
googleapi: Error 503: We encountered an internal error. Please try
again., backendError
```
Which we've been seeing.
=> fix(gcs): Wrap errors using `%w` to make retrying work

server/artifacts/artifact_server.go, server/artifacts/artifact_server_test.go
This is a partial fix for Issue [9277](https://github.com/argoproj/argo-workflows/issues/9277)
There are 2 issues:
1. The UI shows the wrong bucket name if Template.ArchiveLocation is configured
2. The file cannot be downloaded from the back end if Template.ArchiveLocation is configured (because we look in the wrong bucket).
This fixes problem 2 but not problem 1.
=> fix: Look in correct bucket when downloading artifacts (Template.ArchiveLocation configured)

pkg/apiclient/http1/facade.go
Signed-off-by: lijie <lijie0123lj@gmail.com>
Fixes #8622
http Body.Close() is not enough for some keep-alive http connections
http1 tcp connection leak because of set http keep alive but http.Client just dispose without close its connection
To fix this, there are three solutions:
1. reuse http client, which is a larger change
2. invoke client.CloseIdleConnection() before it dispose, which has no advantage over solution-3
3. disable http keep alive, which is choosed
=> Fixes #8622: fix http1 keep alive connection leak

cmd/argo/commands/delete.go, cmd/argo/commands/list.go, cmd/argo/commands/terminate.go, docs/cli/argo_delete.md, docs/cli/argo_list.md, docs/cli/argo_terminate.md
This is based on a PR that @Amirioelmos contributed (but couldn't get 'codegen' to work locally):
https://github.com/argoproj/argo-workflows/pull/9264
https://github.com/argoproj/argo-workflows/pull/9263
=> docs: fix typo in argo flags

workflow/util/util.go, workflow/util/util_test.go
Fix bugs in retry workflow if the failed node has children nodes. Fix #9244.
For example.  node `t2` was failed, but it has child node `t3`.
{
"apiVersion": "argoproj.io/v1alpha1",
"kind": "Workflow",
"metadata": {
"generateName": "test-pipeline-"
},
"spec": {
"arguments": {},
"entrypoint": "test-pipeline-dag",
"templates": [
{
"dag": {
"tasks": [
{
"arguments": {},
"name": "t1",
"template": "succeeded"
},
{
"arguments": {},
"depends": "t1",
"name": "t2",
"template": "failed"
},
{
"arguments": {},
"depends": "t2 || t2.Failed",
"name": "t3",
"template": "succeeded"
},
{
"arguments": {},
"depends": "t3",
"name": "t4-1",
"template": "succeeded"
},
{
"arguments": {},
"depends": "t3",
"name": "t4-2",
"template": "succeeded"
},
{
"arguments": {},
"depends": "t3",
"name": "t4-3",
"template": …
=> feat: fix bugs in retryWorkflow if failed pod node has children nodes. Fix #9244

workflow/util/util.go
=> fix: Deleted pods are not tracked correctly when retrying workflow

test/e2e/artifacts_test.go
Realized the test had a typo where some of the artifact names were wrong. The reason it worked before was because it's looking in Minio to make sure the artifacts were deleted, and since they were never there it confirmed it.
=> fix: ArtifactGC e2e test was looking for the wrong artifact names

workflow/artifacts/gcs/gcs.go, workflow/artifacts/oss/oss.go
Signed-off-by: Jingkai Hung <jkhung@netbasequid.com>
Fixes #[9271](https://github.com/argoproj/argo-workflows/issues/9271)
=> fix: Retry for http timeout error. Fixes #9271

server/workflow/workflow_server.go
Quick fix for artifactGC. Error message check is preventing successful artifact GC workflows from being deleted. Will add better check before 3.4 release.
=> fix: removed error check which prevented deleting successful artGC wfs. 

workflow/util/util.go, workflow/util/util_test.go
Issues that we are fixing in this PR:
* The skipped nodes need to be kept as skipped. Otherwise, the workflow will be stuck on running.
* The previously supplied parameters needed to be reset for suspended nodes. Otherwise, `argo node reset` would not work as expected.
=> fix: Properly reset suspended and skipped nodes when retrying

ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
=> fix: Incorrect alignment for archived workflow. Fixes #9433

docs/argo-server-sso.md, pkg/apis/workflow/v1alpha1/workflow_phase.go, ui/src/app/shared/components/object-editor/object-editor.tsx, workflow/controller/dag.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
=> chore: remove duplicate word in comments

workflow/sync/lock_name.go, workflow/sync/lock_name_test.go
Add support for slashes in mutex names. 
Fixes #9394
=> feat: support slash in synchronization lock names. Fixes #9394

ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Hoping this Fixes #9434 but we'll see
At least it does fix the issue seen when running examples/dag-coinflip.yaml
Root cause was that this UI code was never updated to reflect the change to POD_NAMES v2, so it was still assuming that the Pod Name and Node ID would be equal.
=> fix: link to "get artifacts from logs" was assuming Node ID was equal to Pod Name

ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
This is useful for debugging purposes. When there are a lot of similar node names, I had to look for the unique IDs from node statuses. 
=> feat: Add node ID to node info panel

ui/src/app/shared/services/sensor-service.ts
Fixes https://github.com/argoproj/argo-workflows/issues/9459
=> fix: default to 'main' container in Sensor logs. Fixes #9459

ui/src/app/shared/services/workflows-service.ts
Fixes #9434 
This fixes the use case that a Pod has been GC'ed and enables the UI to get the log from the artifact in this case.
This reverts a change made to this function [here](https://github.com/argoproj/argo-workflows/commit/3fdf30d9f9181d74d81ca3184b53bbe661ecb845#).
=> fix: for pod that's been GC'ed we need to get the log from the artifact

config/config.go, config/config_test.go, test/e2e/argo_server_test.go
HtmlEncode replaces special characters with character strings that are recognised by the HTML engine itself to render the content of the page
URLEncode replaces special characters with characters that can be understood by web browsers/web servers for the purpose of addressing
Should use URLEncode instead, since the config links are JS buttons to an external page
Fixes #9435
=> fix: use urlencode instead of htmlencode to sanitize url

docs/configure-artifact-repository.md
Provide a bash script to use aliyun cli to create oss bucket, ram user with limit permission. Then create ConfigMap and Secret to config artifact repository.
Signed-off-by: yuhui.zy <yuhui.zy@alibaba-inc.com>
Fixes #TODO
=> docs: config aliyun oss as artifact repo to enhance user experience

docs/running-locally.md
The [text](https://argoproj.github.io/argo-workflows/running-locally/#development-container) states `Configure Docker Desktop to use BuildKit:` yet has `"buildkit": false`.  This changes it to `true`.
Matches the [Docker Desktop docs](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds)
[Original PR that added this text](https://github.com/argoproj/argo-workflows/pull/8677)
Signed-off-by: jmeridth <jmeridth@gmail.com>
=> docs(dev-container): Fix buildkit doc for local dev

.github/workflows/changelog.yaml, .github/workflows/ci-build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, .github/workflows/sdks.yaml, .github/workflows/snyk.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows.
GitHub Actions workflows have a GITHUB_TOKEN with write access to multiple scopes.
Here is an example of the permissions in one of the workflows:
https://github.com/argoproj/argo-workflows/runs/8125260622?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- changelog.yaml
- ci-build.yaml
- gh-pages.yaml
- release.yaml
- sdks.yaml
- snyk.yml
The following workflow file already has the least privileged token permission set:
- dependabot-reviewer.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the …
=> ci: add minimum GitHub token permissions for workflows

test/e2e/hooks_test.go
See https://github.com/argoproj/argo-workflows/issues/9591.
=> ci: Skip TestTemplateLevelHooks test

pkg/apiclient/apiclient.go
Signed-off-by: wujunwei <wjw3323@live.com>
Fixes #9585
Fix panic: runtime error: invalid memory address or nil pointer dereference
=> fix: avoid panic when not passing AuthSupplier

server/artifacts/artifact_server.go, server/artifacts/artifact_server_test.go, workflow/util/util.go, workflow/util/util_test.go
Handle artifact retrieval when the workflow node has no templateName set but
does have templateRef set instead. Added a unit test that was broken before
the changes and works after the changes.
Fixes #9631, #9644
Signed-off-by: Brian Loss <brianloss@gmail.com>
=> fix: Fixed artifact retrieval when templateRef in use. Fixes #9631, #9644.

ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
Signed-off-by: Dakota Lillie <dakota.lillie@icloud.com>
Fixes #9614, #9433
- Fix multiple issues with the archived workflows UI in 3.4.0, including that the step graph was no longer centered, and the node details were shifted down the page
My understanding is that these issues were introduced with #8963. I did not test the archived workflows page when I developed this feature (that's my bad), and some of the CSS changes appear to have impacted the archived workflows page.
This PR is intended to "stop the bleeding" and make the archived workflows page appear normal again. It does not implement the resizable side panel functionality for the archived workflows page. Doing so will require a more significant refactor, since the resizable side panel implementation uses a custom hook, and the …
=> fix: broken archived workflows ui. Fixes #9614, #9433

Makefile
It's more comfortable we could avoid entering password when clang-format already exists
=> build: install clang-format only if not exists

util/errors/errors.go, util/errors/errors_test.go, workflow/util/plugins/plugin.go
Fixes: #9664
- Added unit test testcase in `util/errors/errors_test.go`: tests *url.Error also can be a transient network error.
=> fix: retry ExecutorPlugin invocation on transient network errors Fixes: #9664

Makefile, README.md, cmd/argo/commands/server.go, docs/cli/argo_server.md, manifests/base/argo-server/argo-server-certificate.yaml, manifests/base/argo-server/argo-server-deployment.yaml, manifests/base/argo-server/kustomization.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, server/apiserver/argoserver.go
Signed-off-by: vladimir ivanov <vladimir.ivanov@grasshopperasia.com>
Fixes #5582
Add --tls-certificate-secret-name parameter to server command.
Since server runs on localhost:2746, get an error in the UI "certificate is valid for ... not for localhost". Therefore the merge request set `InsecureSkipVerify` on TLSconfig for grpc client on the gateway.
Tested to to work with secret provided by cert-manager (added to manifests).
=> Add --tls-certificate-secret-name parameter to server command. Fixes #5582

workflow/controller/exec_control.go
Fixes #9587 
This handles workflow-controller panic when stop a wf using plugin.
=> fix: Workflow-controller panic when stop a wf using plugin. Fixes #9587

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/regression.yaml
From observation, users will get and fill in “no resources found in default namespace” in the form if they are not in Argo namespace.
=> docs: Add namespace in issue templates

util/logs/workflow-logger.go
Fixes #9573
argo logs abort early caused by bufio.ErrTooLong
=> fix: Log early abort. Fixes #9573

workflow/controller/agent.go
Fixes #9704 
Set scheduling constraints to the agent pod by the workflow
=> fix: Set scheduling constraints to the agent pod by the workflow. Fixes #9704

test/e2e/workflow_configmap_substitution_test.go, workflow/controller/operator.go
=> fix: default not respected in setting global configmap params. Fixes #9745

docs/configure-artifact-repository.md
Signed-off-by: Lukas Heppe <lukas.heppe@agido.com>
Fixes #TODO
When using the IAM policy provided in the docs I couldn't view the logs via UI. By allowing the `ListBucket` Policy on the bucket instead of the objects within, I was able to retrieve those. 
The prinicple is also described in the AWS Blog post https://aws.amazon.com/de/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/.
=> fix: fix iam permissions to retrieve logs from aws s3

test/e2e/functional_test.go
partial fix to #9027 
This test fails intermittently (such as [here](https://github.com/argoproj/argo-workflows/actions/runs/2667409389/jobs/4152256492)) because the "Message" on the Pod sometimes gets cleared. The test is looking for the "Message" but it showed up and then got cleared. It seems to me that what we're verifying here is that the activeDeadlineSeconds got passed to the Pod so I've changed the check to that.
=> chore: address flakey e2e test ("TestParametrizableAds")

docs/running-locally.md
Updated document for ui development to use node >= 16.15.0,
There is an issue: `--no-experimental-fetch is not allowed in NODE_OPTIONS`  when run `yarn --cwd ui start` with `node < 16.15.0` and the `yarn --cwd ui start` is using on makefile (`make start UI=true`).
FYI: There is no issue when run `cd ui && yarn start` it worked well with node >= `v16.0.0`.
Tested with `yarn --cwd ui start`:
- if node is `< v16.15.0`, node will get `--no-experimental-fetch is not allowed in NODE_OPTIONS`.
- if it node `>= v16.15.0` node will ignore this config
References:
- node18: [docs](https://nodejs.org/dist/latest-v18.x/docs/api/cli.html#--no-experimental-fetch)
- node17: [docs](https://nodejs.org/dist/latest-v17.x/docs/api/cli.html#--no-experimental-fetch) (optional is not available)
- node16: …
=> docs: update nodejs to >= 16.15.0

workflow/executor/os-specific/signal_windows.go
Fixes https://github.com/argoproj/argo-workflows/issues/9797
=> fix: exit code always be '0' in windows container. Fixes #9797

ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
Fixes #9669 
In containerset, the log is stored in the parent of the selected node.
We retrieve the log info through `workflow.status.nodes[nodeid]`
it happens in the existing approach the `nodename - .[^.]*$` is same as `nodeid` of parent node for simple container set wf.
However, when we have multiple container sets in a wf this is no longer valid.
Tests:
<details>
<summary>container set with retry</summary>
```yaml
kind: Workflow
metadata:
generateName: sequence-
labels:
workflows.argoproj.io/test: "true"
annotations:
workflows.argoproj.io/description: |
This workflow demonstrates running a sequence of containers within a single pod.
workflows.argoproj.io/version: ">= 3.1.0"
spec:
templates:
- name: main
containerSet:
containers:
- …
```
=> fix(ui): containerset archive log query params. Fixes #9669

cmd/argo/commands/list.go
Signed-off-by: aditya-shrivastava aditya.shrivastava251@gmail.com
Fixes #9281 
E2E tests already present in https://github.com/argoproj/argo-workflows/blob/master/test/e2e/cli_test.go
=> fix: P/R/C reporting in argo list -o wide. Fixes #9281

docs/running-locally.md
The documentation used round braces around variable names (GOPATH and KUBE_NAMESPACE). However, round braces around variable names are correct only in Makefiles. In a shell context they stand for command substitution.
Removing the braces allows to paste the examples in the terminal.
=> Remove wrong braces in documentation

docs/walk-through/artifacts.md
Signed-off-by: awwwd <amitauddy94@gmail.com>
Fixes #9525 
=> docs: usage of podSpecPatch for large size artifacts Fixes #9525

workflow/validate/validate.go
When I encountered this problem, I spent some time to find the reason, so I want people to know the reason faster.
=> docs: explain why maxCharsInObjectName is 63 characters

workflow/artifacts/artifacts.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Fixes #9867
Adds mount of the SSE-C secret, if SSE-C is configured. Fixed the secret key used when reading the SSE-C key. Adds unit test to validate the mounts. Also tested inside a different project, where Argo and another component both read/write SSE-C encrypted objects from/to AWS S3.
=> fix: mount secret with SSE-C key if needed, fix secret key read. Fixes #9867

workflow/artifacts/gcs/gcs.go
=> fix: cleaned key paths in gcs driver. Fixes #9958

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go
=> fix: assume plugins may produce outputs.result and outputs.exitCode (Fixes #9966)

cmd/argo/commands/common/get.go, cmd/argo/commands/common/get_test.go, test/e2e/fixtures/then.go, workflow/controller/exec_control.go, workflow/controller/operator.go, workflow/controller/workflowpod.go, workflow/util/pod_name.go, workflow/util/pod_name_v1_test.go, workflow/util/pod_name_v2_test.go, workflow/util/util.go
=> fix: use correct node name as args to PodName. Fixes #9906

docs/environment-variables.md, server/workflowarchive/archived_workflow_server.go, server/workflowarchive/archived_workflow_server_test.go
This is to handle the situation where the UI is not responsive and crashes when the list of values for certain labels is extremely large.
=> feat: Support disable retrieval of label values for certain keys

test/e2e/artifacts_test.go, workflow/controller/artifact_gc.go, workflow/controller/artifact_gc_test.go
Partial fix to #9953 
Issue was that we were only adding the Condition based on failure of individual artifacts. In this case, the GC Pod never got to the point of attempting deletion of an artifact (it couldn't read what the artifacts were in fact), so there was no reporting of individual artifacts' status. Now a Condition will be written if the Pod fails as well.
Fixes #TODO
=> fix: if artifact GC Pod fails make sure error is propagated as a Condition

Dockerfile, Dockerfile.windows
Fixes #10006 
We are taking one minor version less than v1.25.3 (based on https://storage.googleapis.com/kubernetes-release/release/stable.txt)
which is v1.24 and v1.24.5 contains the security fixes.
Reference: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#important-security-information
=> fix: Upgrade kubectl to v1.24.8 to fix vulnerabilities

.github/workflows/release.yaml, Makefile
Signed releases #9769 
This PR implements container images to be signed using ```sigstore/cosign```  It also consolidates the checksums of the cli-binaries into a single file then signs it.   
TLDR: https://docs.sigstore.dev/cosign/git_support
1. [Install Cosign](https://docs.sigstore.dev/cosign/installation) on your workstation. Linux, Homebrew, and container options are available.  Execute the command ```cosign --version``` to verified it has been installed correctly.
2. Create or have a valid GitHub PAT token available.
3. Export your PAT as the environment variable "GITHUB_TOKEN"
4. Execute ```cosign generate-key-pair github://argoproj/argo-workflows``` This will start the process of creating the GitHub Secrets automatically for you, and prompt you to enter a password.  This Password …
=> chore: sign container images on quay and signed releases

workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix(operator): Workflow stuck at running when init container failed. Fixes #10045

.spelling, docs/walk-through/artifacts.md, workflow/controller/artifact_gc.go
Fixes #9953 
Improve documentation to make clear the RoleBinding required for ArtifactGC. Also improve error message on Workflow.
=> fix: Documentation to clarify need for RoleBinding for ArtifactGC

test/e2e/progress_test.go, test/e2e/testdata/progress-workflow.yaml, workflow/controller/taskresult.go
Re-adds an EventHandler to trigger an update when a WorkflowTaskResult got added/updated. Without this, a workflow progress only gets updated upon completion or every 20mins.
Fixes #10096
Reverts skipping of related Test (#8459)
=> fix: reconcile wf when taskresult is added/updated. Fixes #10096

cmd/argo/commands/server.go, docs/cli/argo_server.md, server/apiserver/argoserver.go
Signed-off-by: vladimir.ivanov <vladimir.ivanov@grasshopperasia.com>
Fixes #5582 
Add --tls-certificate-secret-name parameter to server command.
Since server runs on localhost:2746, get an error in the UI "certificate is valid for ... not for localhost". Therefore the merge request set InsecureSkipVerify on TLSconfig for grpc client on the gateway.
Tested to to work with secret generated by cert-manager.
=> fix: Add --tls-certificate-secret-name parameter to server command. Fixes #5582 

server/auth/sso/sso.go
Fixes #9259
Due to the custom `http.Transport` created inside `newSso`. All the OAuth2 related API calls are missing the proxy information because of:
```go
// Create http client with TLSConfig to allow skipping of CA validation if InsecureSkipVerify is set.
httpClient := &http.Client{Transport: &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: c.InsecureSkipVerify}}}
```
Which is used in:
```go
func (s *sso) HandleCallback(w http.ResponseWriter, r *http.Request)
...
oauth2Context := context.WithValue(ctx, oauth2.HTTPClient, s.httpClient)
oauth2Token, err := s.config.Exchange(oauth2Context, r.URL.Query().Get("code"), redirectOption)
```
The [`DefaultTransport`](https://go.dev/src/net/http/transport.go ) of `http` sets the Proxy. And since `s.httpClient` was created with a …
=> fix: Ensure the SSO http client takes into consideration http proxies, Fixes #9259

cmd/argoexec/commands/emissary.go, go.mod, go.sum, test/e2e/functional/tty.yaml, test/e2e/functional_test.go, test/e2e/testdata/output-artifact-with-s3-bucket-creation-enabled.yaml, workflow/executor/os-specific/command.go, workflow/executor/os-specific/command_unix.go, workflow/executor/os-specific/command_windows.go
=> fix: emissary detects tty and wraps command in pseudo terminal. Fixes #9179

Dockerfile, Makefile
This PR:
- Refactors the Dockerfile to cache packages in the builder stage
- Caches go modules
- Caches node modules
- Uses alpine images for the builder and ui
- Refactors the makefile to use buildkit
Note: On this PR, I can get the build of all three images needed to run the codebase down to about 30 seconds total (with caching), where a build of all three images on the master branch takes about 30 minutes total on my machine
Fixes #10134
=> build: Use alpine, buildkit, and refactor pkg caching. Fixes #10134

cmd/argo/commands/server.go, docs/cli/argo_server.md
Fixes:
> Please correct me if I'm wrong.
Every time argo-server reads and writes resources, it performs r/w on kube-apiserver. Therefore rest.Config.Burst and QPS are both key parameters.
https://github.com/kubernetes/client-go/blob/release-1.26/rest/config.go#L114-L120
So I set it as flag to support setting when the user starts the argo server (when the user does not specify, we use 30 as burst and 20.0 as qps), like...
```bash
argo server --kube-api-qps 100 --kube-api-burst 200
````
=> feat(server): add kube-api throttle options

cmd/argoexec/commands/wait.go
=> fix (argo wait): use functions to constrain ctx instead of blocks

workflow/controller/exit_handler_test.go, workflow/controller/http_template_test.go, workflow/controller/taskset.go
Fixes https://github.com/argoproj/argo-workflows/issues/7080
Fix for the bug of exit-handler problem for this PR: https://github.com/argoproj/argo-workflows/pull/7084 (Using NodeID to get child node in GetNodeByName function by mistake)
Detailed introduction can be found in the argo-workflows slack channel: https://cloud-native.slack.com/archives/C01QW9QSSSK/p1670507275924099
=> fix: ensure HTTP reconciliation occurs for onExit step nodes

workflow/common/convert.go, workflow/common/convert_test.go
Signed-off-by: jie zhang <zhangjie609610@163.com>
Feat: support finalizers in workflowMetadata 
=> feat: support finalizers in workflowMetadata

test/e2e/artifacts_test.go, test/e2e/fixtures/when.go
Fixes #10230 
Artifact GC can't be reliably tested if the Workflow being executed fails (i.e. the artifact may have not been successfully written to minio in the first place so we can't verify the condition that certain artifacts should still be there). Skip the test in this case. 
Ideally, we'd determine the root cause for the intermittent failure of the Workflows (I did some analysis [here](https://github.com/argoproj/argo-workflows/issues/10230#issuecomment-1362084926)) but until then, this will prevent false test failures.
=> Skip Artifact GC test if Workflow fails

examples/k8s-resource-log-selector.yaml
The TFJob spec in Kubeflow has been changed recently. Updating the example so that it works again.
=> docs: Fix success/failure conditions in k8s-resource-log-selector example

docs/conditional-artifacts-parameters.md
Signed-off-by: Amritpal Nagra <amritpalnagrame@gmail.com>
Typo fixes in a documented example.
=> docs: update typo in step reference

USERS.md
adding our company name to the Argo Workflow users
Signed-off-by: Balaji Siva <balaji@opsmx.com>
Fixes #TODO
=> docs: add OpsMx to users

workflow/controller/operator.go
Signed-off-by: Sushant20 <sushant.c@somaiya.edu>
Fixes https://github.com/argoproj/argo-workflows/issues/10270
=> fix: print template and pod name in workflow controller logs for node failure scenario

manifests/quick-start/sso/dex/dex-deploy.yaml
Signed-off-by: Jiacheng Xu <xjcmaxwellcjx@gmail.com>
This PR fixes the not working dex in quickstart manifests:
1. https://quay.io/repository/dexidp/dex only has tags <= `v2.28.1` and upstream switched to use `ghcr.io` for images(https://github.com/dexidp/dex/releases)
2. Dex pods crash because the `serve` command is not in `$PATH` and the command should be `dex serve /data/config.yaml`.
=> fix: fix not working dex deployment in quickstart manifests

ui/package.json, ui/src/app/shared/hooks/uselocalstorage.ts, ui/src/app/webpack.config.js, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.scss, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx, ui/yarn.lock
Fixes #3474
* [] Run `make pre-commit -B` to fix codegen and lint problems.
=> feat: allow switching timezone for date rendering. Fixes #3474

.github/workflows/release.yaml
This fixes the release workflow:
```
docker.io/***/workflow-controller:latest-linux-arm64 is a manifest list
```
https://github.com/argoproj/argo-workflows/actions/runs/4077164697/jobs/7026848613
Co-authored-by: Jesse Suen <jesse@akuity.io>
=> ci: Pin buildx action version to fix release workflow

Dockerfile, config/config.go, persist/sqldb/sqldb.go
Signed-off-by: Rajshekar Reddy <reddymh@gmail.com>
Fixes #10234 
* [] Once required tests have passed, mark your PR "Ready for review".
=> Fixes #10234 - Postgres SSL Certificate fix

Dockerfile
hi guys, I faced with a problem recently.  
I changed the code of ui and run `make argocli-image` to get new argocli image, but ui changes does not work.  
It finally turned out to be that I forgot to run `STATIC_FILES=true make server/static/files.go` to generate `server/static/files.go` from ui code.
I think it is better to force rebuild static files when build argocli image, it will helps avoid such problem in ui development.
=> chore: Force rebuild staticfiles when build argocli image.

cmd/argo/commands/common/get.go, cmd/argoexec/commands/wait.go, cmd/argoexec/main.go
This MIGHT fix these:
Fixes #10518 
Fixes #10337 
Fixes #10033 
Fixes #10490
=> fix: Correct SIGTERM handling. Fixes #10518 #10337 #10033 #10490

cmd/argo/commands/lint.go, cmd/argo/commands/lint_test.go, cmd/argo/lint/lint.go, pkg/apiclient/offline-client.go, pkg/apiclient/offline-cluster-workflow-template-service-client.go, pkg/apiclient/offline-cron-workflow-service-client.go, pkg/apiclient/offline-workflow-service-client.go, pkg/apiclient/offline-workflow-template-service-client.go
https://github.com/argoproj/argo-workflows/pull/10059 was tested in very specific cases it seems (sorry about that 😬), because a couple things are wrong:
- Linting directories does not work anymore
- Resolving references in a namespace which doesn't show up in the given args, panics
In this PR, I fix those issues but I also add functional tests that checks that all of these cases work from the cmd level 
I did not add to the `argo/lint/lint_test.go` tests and instead put the tests earlier down the line because the current tests do not cover the creation and configuration of the offline client (which is the part that is failing here, the actual linter was not modified in the PR above)
=> fix: Resolve issues with offline linter + add tests

cmd/argoexec/commands/emissary.go
Artifacts can be optional, logging a missing output artifact as error has too high severity, this will be highly visible in the logs requiring attention. Change severity to warning, similar with what is being logged in wait container: https://github.com/argoproj/argo-workflows/blob/master/workflow/executor/executor.go#L316
Fixes #change log severity when artifact is not found
=> fix: change log severity when artifact is not found

.github/workflows/gh-pages.yaml, .github/workflows/release.yaml, ui/package.json
Signed-off-by: Alex Collins <alexec@users.noreply.github.com>
Fixed the [broken builds](https://github.com/argoproj/argo-workflows/actions/workflows/release.yaml).
=> build: Upgrade to Node 19 to fix release build

.github/workflows/ci-build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, Dockerfile, Dockerfile.windows, go.mod
v1.18 has reached end of life: https://endoflife.date/go
=> chore: Upgrade Go to v1.19

cmd/argo/commands/client/conn_test.go, cmd/argo/commands/lint_test.go, cmd/argo/lint/lint.go, pkg/apiclient/offline-client.go, util/file/fileutil.go
Follow-up to https://github.com/argoproj/argo-workflows/pull/10059 and https://github.com/argoproj/argo-workflows/pull/10559
The offline linter is working well in ideal scenarios, I am linting a set of files/directory in 5 seconds where it used to take ~5 minutes
However, I did find issues after testing some more:
Given an non-existent file, it panics (I inverted the `info.IsDir()` statement and the one checking for errors) 
There's a disconnect between the `filepath.Walk` in the linter and the one building the offline client which means that there were other issues (such as stdin not working)
To fix those issues once and for all, I extracted the walk func to a common path (`file.WalkManifests`); that way, we are sure that changes are always reflected in both locations
I also added some …
=> fix: panic in offline linter + handling stdin

.github/workflows/ci-build.yaml
This will fix the failing builds.
=> ci: Increase unit test timeout to 10m

.github/workflows/ci-build.yaml, .github/workflows/release.yaml, Dockerfile, docs/running-locally.md, ui/package.json
Node 19 is not LTS. Node 18 is, but does not work with the SSO problem.
This fixes that.
=> build: Revert to Node 16 LTS

.github/pull_request_template.md
* Github checks are green. - this is impossible to know before opening the PR.
* DCO check has been removed. Added link to DCO app.
* Once required tests have passed, mark your PR "Ready for review". - this is something to do after the PR has been created.
=> docs: Minor edits on pull_request_template.md

workflow/common/util.go
Fixes：
In the process of troubleshooting #10490, we found that our `wait` received more than one sigterm.
However, when wf-controller sends sigterm for the second time (actually through argoexec kill), it may cause container-crash (signal processing is asynchronous), and we need this part of the log to support our troubleshooting.
=> fix: added logs related to executing commands in the container

docs/configure-artifact-repository.md
In old docs, `keyFormat` was incorrectly saying that workflow variables are optional. They're mandatory, without them all artifacts are saved to same place and overriding each other.
More context [in this slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1677707500865799)
=> docs: Modify keyFormat in GCS docs to refer to workflow

.github/dependabot.yml
This PR:
- Tells dependabot to ignore updates to react-router-dom and @types/react-router-dom
- The goal is to temporarily avoid future ui issues related to react router migrations as we've seen in #10590 and #10587
=> build: Skip react-router-dom on dependabot

workflow/executor/executor.go
Changed executor dir permission mode to 0o755 from 0o700
Fixes #9651
=> fix: executor dir perm changed to 755. Fixes #9651

Makefile
I am unsure how to fix this error so temporarily disable this so that other PRs can be merged.
https://github.com/argoproj/argo-workflows/actions/runs/4406056997/jobs/7717770785
```
/opt/hostedtoolcache/node/19.7.0/x64/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:324
if (fn === null) throw new Error("Callback was already called.");
^
Error: Callback was already called.
at /opt/hostedtoolcache/node/19.7.0/x64/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:324:36
at /opt/hostedtoolcache/node/19.7.0/x64/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:248:17
at /opt/hostedtoolcache/node/19.7.0/x64/lib/node_modules/markdown-link-check/index.js:129:13
at /opt/hostedtoolcache/node/19.7.0/x64/lib/node_modules/markdown-link-check …
```
=> ci: Temporarily disable docs link check to unblock PRs

.github/workflows/release.yaml
See context in https://github.com/argoproj/argo-workflows/pull/10471#issuecomment-1428160009.
=> ci: Upgrade buildx to v0.10.4 and disable provenance

docs/walk-through/loops.md
The loops documentation is 'by example' only. I have attempted to improve this to explain what is going on, and why someone might use each form of loops
This is a documentation only change. The examples are unchanged.
=> docs: Improve documentation on loops

workflow/artifacts/gcs/gcs.go
All this does is change the order, it lets the error check run before the attrs.Name is accessed. 
Fixes #10691
=> fix: ensure error returns before attrs is accessed. Fixes #10691

examples/conditional-artifacts.yaml
Fix a typo in the example document.
=> docs: fix typo in examples

tasks.yaml
This project has been moved to a different org.
=> docs: Update link to kitproj/kit

test/e2e/cli_test.go, test/e2e/testdata/retry-with-recreated-pvc-test.yaml, workflow/util/util.go
This fixes a bug where a retried workflow would fail with the error `persistentvolumeclaim xxx not found` if the PVC is deleted previously (e.g. volumeClaimGC strategy is set to `OnWorkflowCompletion`). We can fix this by resetting the PVC in workflow status so that the operator could recreate the PVC.
=> fix: PVC in wf.status should be reset when retrying workflow

docs/quick-start.md
Add extra not emphasising on using `https` rather than `http` to access server UI
Added context to help who might fall for the same sequence explained in https://github.com/argoproj/argo-workflows/issues/10719
=> docs: Update quick-start.md

persist/sqldb/sqldb.go, workflow/controller/config.go
Fixes #10498. The issue is that after change https://github.com/argoproj/argo-workflows/commit/b0f0c589e626650ca01a635f773af983e213fbec introduced in 3.4.5, new DB sessions are re-created every time when the configmap changes. This PR allows reusing the DB session.
=> fix: DB sessions are recreated whenever controller configmap updates. Fixes #10498

.devcontainer/devcontainer.json
The devcontainer is missing a python installation, this prevents contributors from performing a `make docs` command. This PR adds python to the devcontainer to overcome this issue.
`make docs` now successfully builds the docs within the devcontainer.
=> chore: Add python to devcontainer for make docs

docs/configure-artifact-repository.md
I found the IRSA documentation lacking so wanted to add to it.
Also favoured giving the full-blown s3 bucket policy for users who skim, and then using the sentence to encourage users to remove unused policy actions. This will reduce the questions in slack on the subject.
=> docs: Enhance s3 setup docs with IRSA information

examples/retry-backoff.yaml
Why this PR: Wrong example yaml file for `retry-backoff.yaml`
Change I made: removed `1d` comment.
Fixes https://github.com/argoproj/argo-workflows/issues/4088
@alexec
=> docs: Remove days in examples/retry-backoff.yaml

workflow/artifacts/s3/errors.go
These errors are in the backoff retry loop and users are not clear what/whether errors are retried.
=> chore: Print out transient S3 errors

workflow/executor/agent.go, workflow/executor/agent_test.go
=> fix(agent): no more requeue when the node succeeded

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go
When a template is inline inside a WorkflowTemplate or ClusterWorkflowTemplate we must still create a stored version of it. This fix changes the 'name' given to those from `/scope/templateName/` (where after the last / should be a name but there isn't) to /scope/templateName/inline/name' where name can be step name or task name.
I have added inline as it's possible to name an inline step the same as a template in the same WorkflowTemplate.
Tested against the test cases from #10737.
Fixes #10737
=> fix: Fix inlined templates in templates

.github/workflows/snyk.yml
Scan security vulnerabilities before release to avoid issues like https://github.com/argoproj/argo-workflows/issues/10811
=> ci: Enable Snyk on release branches

workflow/controller/operator.go, workflow/controller/operator_test.go
This would help debug issues, especially when a workflow contains many steps and we have to check individual pod/container statuses.
=> feat: Surface container waiting reason and message

cmd/argo/commands/delete.go, docs/cli/argo_delete.md
The `argo list` CLI command accepts an `--chunk-size n` argument, but the `argo delete` command does not. In our case, this was problematic because the large number of old workflows we had was causing unbounded list queries to fail, and the sensible remedy (deleting old workflows) was not possible because (for example) `argo delete --since 30d` could not be chunked in the same way that listing could.
This PR adds a `--query-chunk-size n` argument to `argo delete`, which is applied when the command is fetching the workflows it will delete. The name `query-chunk-size` is different from the list command option `chunk-size` to avoid the implication that it will delete according to the specified chunk - but please suggest a better name if you have one.
The flag is passed directly to …
=> feat: add chunk size argument to delete cli command

workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix: Workflow stuck at running for failed init containers with other names. Fixes #10717

docs/walk-through/loops.md
An error occurred in the example due to the lack of annotation symbols.
Add missing symbols and delete blank lines.
Fixes #TODO
=> docs: Fix comments

workflow/templateresolution/context.go
The workflow template resolver used to be able to recurse. This was removed 2 years ago, but the code that prevents infinite recursion is still in the code base.
I have just removed code, and things still compile and tests pass. As I've changed a call interface and things still compile I'm happy I cannot have missed anything.
The UI has not changed
=> chore: Remove legacy recursion preventer from template resolution

go.mod, go.sum
https://github.com/argoproj/argo-workflows/issues/10811#issuecomment-1501767095 
[CVE-2023-28840: Encrypted overlay network may be unauthenticated](https://github.com/moby/moby/security/advisories/GHSA-232p-vwff-86mp)
[CVE-2023-28841: Encrypted overlay network traffic may be unencrypted](https://github.com/moby/moby/security/advisories/GHSA-33pg-m6jh-5237)
[CVE-2023-28842: Encrypted overlay network with a single endpoint is unauthenticated](https://github.com/moby/moby/security/advisories/GHSA-6wrf-mxfj-pf5p)
=> fix: Upgrade docker to v20.10.24 for CVE-2023-28840, CVE-2023-28841, CVE-2023-28842

test/e2e/fixtures/given.go, test/e2e/functional/template-default-image.yaml, test/e2e/functional_test.go, workflow/validate/validate.go, workflow/validate/validate_test.go
Made changes to validation to check if the script/container Image has been set in templateDefaults
**Testing**
Added unit tests to verify these situations
Also created the following via the locally deployed UI and then submitted both via the UI and they were successful:
```
metadata:
generateName: demo-
spec:
entrypoint: demo
templateDefaults:
script:
command: [sh]
workingDir: "/src"
templates:
- name: demo
script:
source: |
pwd
```
and a cron workflow
```
kind: CronWorkflow
metadata:
generateName: demo-cron
spec:
schedule: "00 4 * * 2"
timezone: "UTC"
workflowMetadata:
generateName: demo-cron-test-
workflowSpec:
entrypoint: demo
templateDefaults:
script: …
```
=> fix: Allow script and container image to be set in templateDefault. Fixes #9633

test/e2e/hooks_test.go
Fixes #10897
also relate with https://github.com/argoproj/argo-workflows/issues/10807#issuecomment-1503807149
This issue unreproducible at local but pretty consistent on ci enviroment.
I guess if task end to early, running hook can't meet conditions so never trigger. (on slow environment)
This issue can prevent by sleeping 1 second.
You guys think this is bug that need to make new ticket?
=> fix: Flaky test about lifecycle hooks. Fixes #10897

docs/walk-through/artifacts.md
Ahead of the kubecon presentation on Artifact GC, took another glance at the Artifact GC documentation, and it could use some improvement. (This will be referenced in the slides.)
=> docs: Artifact GC documentation around dealing with failures needed improvement 

Makefile, docs/swagger.md
Currently the link in the [API reference page](https://argoproj.github.io/argo-workflows/swagger/) points to the API spec in JSON, which is not readable. This PR adds a simple HTML code snippet that renders Swagger UI with the spec to `swagger.md` so that it displays the API docs directly.
We can also put the HTML code in a separate file and simply make the link in the API reference page point to that file. I think it's more straightforward to embed Swagger UI like this.
One issue with Swagger UI is that it's slow when it loads information about a certain path or schema after a user clicks on it. This is probably because the API spec is too large. I tested generating Swagger UI in static HTML, but it also took some time for my browser to load a certain path.
`make docs`
Though I also …
=> docs: Add Swagger UI to the API reference page

workflow/controller/taskresult.go
Say why you made your changes.
fix issue that stop/termante workflow then retry meet error: Workflow operation error
https://github.com/argoproj/argo-workflows/issues/10285
Say what changes you made.
Update taskresult.go, when does not get node by node id, do not return the empty node
Say how you tested your changes.
I  merge this change to v3.3.10, retry as described in issue https://github.com/argoproj/argo-workflows/issues/10285, this issue does not appear
=> fix: Workflow operation error. Fixes #10285

examples/daemoned-stateful-set-with-service.yaml
Kubernetes is migrating its image registry from [k8s.gcr.io](http://k8s.gcr.io/) to [registry.k8s.io](http://registry.k8s.io/).
Part of kubernetes/k8s.io#4780.
=> chore: migrate from k8s.gcr.io to registry.k8s.io

workflow/gccontroller/gc_controller.go
- Say why you made your changes:
This log can not reflect the workflow which is to be deleted correctly. The call of Delete function returns nil does not mean the workflow has been successfully. We have seen it in production environment sometimes which is confused us.
- Say what changes you made:
Adjust the log msg.
- Say how you tested your changes:
Add finalizer and wait gc_controller to delete
Fixes #10929
=> chore: Adjust gc_controller log to be more accurate. Fixes #10929

go.mod, go.sum
This PR bumps https://github.com/argoproj-labs/go-git to latest version v5.4.7, which has the potential fix for cloning issues with azure devops.
Fixes #10600
=> chore: bump argoproj-labs/go-git to v5.4.7. Fixes #10600

CONTRIBUTING.md
Add a root `CONTRIBUTING.md` that directs to `docs/CONTRIBUTING.md`
- having a `CONTRIBUTING.md` at the root of the repo is a common convention
- I looked at the root of the repo initially, didn't find it, then checked the website, but potential contributors may think it doesn't exist as a result
=> docs: add `CONTRIBUTING.md` at root of repo, directing to `docs/`

docs/argo-server-sso.md
Add a `!!! Note` section to the cluster SA for NS delegation explicitly stating that it is _required_
- my team did not realize that this was strictly required before NS delegation would work, so we had a pretty confusing time of debugging
- in particular we thought the RO "optional" suggestion meant that if we didn't want to give users RO to the whole cluster, we could skip it -- but it actually means that we don't have to give any RBAC at the cluster level at all, but still do need _some_ SA, even if it has no RBAC bound to it
- there's a decent bit of nuance here, so figure this can be more explicitly called out as a pre-req as such
- also fix some typos / grammar / formatting on this page
Something else my team and I had trouble with while debugging #10927
=> docs(sso): cluster SA _must_ be mapped to before NS SA can apply

USERS.md, docs/variables.md, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go, workflow/validate/validate_dag_test.go
This PR adds the ability to template tasks hostNodeName. We would like to use it to utilize some node local caching/setups (eg with things like node attached SSDs).  
This will make our lives easier with templating nodeSelectors.
I've also added my current employer as a user; please let me know if you wish it to be in a different PR.
=> feat(operator): Add hostNodeName as a template variable

.github/workflows/pr.yaml
To provide the same contributing settings for Argo projects. since other projects like the argo-rollouts and argo-cd have already adopted the PR title checker to conform to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
=> ci: add PR title conventional commits checker

docs/retries.md, docs/variables.md, workflow/common/common.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go
As requested in #9937 add a message field to lastRetry to allow fine grained control of retries.
Tested with unit test and a manually with a simple workflow which conditionally retried on `lastRetry.message=="some words"`
Fixes #9937
=> feat: Add lastRetry.message

workflow/controller/hooks.go, workflow/controller/hooks_test.go, workflow/validate/validate.go
The error message for a missing or empty expression was `unable to evaluate expression '': unexpected token EOF (1:1)`. This changes it to a more useful `Expression required for hook <hook path>`.
Also attempt to validate to prevent this problem upfront.
Fixes #10910
=> fix: Generate useful error message when no expression on hook

docs/mentoring.md
Docs CI is failing on a silly thing - `docs/mentoring.md` is changed by running `make docs` - I pushed those changed
=> chore: fixed docs ci

.github/workflows/ci-build.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml, .golangci.yml, Dockerfile, Dockerfile.windows, Makefile, go.mod, pkg/apiclient/http1/facade.go
This fixes the following CVEs:
https://github.com/advisories/GHSA-v4m2-x4rp-hv22
https://github.com/advisories/GHSA-fp86-2355-v99r
https://github.com/advisories/GHSA-9f7g-gqwh-jpf5
https://github.com/advisories/GHSA-8v5j-pwr7-w5f8
=> fix: Upgrade Go to v1.20. Fixes #11023

workflow/executor/taskresult.go
In large-scale scenarios on cloud, we find the are so many workflowtaskresults left in the cluster (over a million), causing the cluster to fail to work. After investigation, we determined that there is something wrong with the pod owner reference.
=> fix: change pod OwnerReference to clean workflowtaskresults in large-scale scenarios

workflow/controller/controller.go
Noticing occasional panics when the Workflow is no longer in the Informer cache and we get a deletion event due to a type assertion. The actual type is `cache.DeletedFinalStateUnknown`.
=> fix: handle panic from type assertion

ui/src/app/shared/pod-name.test.ts, ui/src/app/shared/pod-name.ts
I noticed that sometimes the UI shows the wrong pod name. Specifically for running pods.
I noticed that this change https://github.com/argoproj/argo-workflows/commit/cc9d14cf0d60812e177ebb447181df933199b722 made pod name format v2 to be default even when the annotation is missing in the backend, but this behavior was never coded into the UI code.
This tries to fix it.
Fixes #11015
=> fix: ui getPodName should use v2 format by default (fixes #11015)

ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
=> fix: UI crashes when retrying a containerSet workflow. Fixes #11061

test/e2e/manifests/postgres/kustomization.yaml
Fix missing resources(eventbus, eventsources, sensors) when running E2E tests with postgres profile.
=> chore: Fix missing resources when running E2E tests with postgres profile

util/help/topics.go
Getting an error message:
```
FATA[2023-05-16T16:05:39.091Z] this is impossible if you are not using the Argo Server, see https://argoproj.github.io/argo-workflows/cli/ 
```
However, the page https://argoproj.github.io/argo-workflows/cli/ has empty content.
=> docs: Fix link to Argo CLI help page

workflow/controller/operator_concurrency_test.go
The test TestSynchronizationForPendingShuttingdownWfs/PendingShuttingdownStoppingWf regularly fails in github actions unit test stage.
This should probably be looked at, but for now stop needing quite so many retries to push through simple changes.
Commented out test with a note on reason why.
=> fix: Disable unreliable test

.devcontainer/devcontainer.json
Commit a5581f83abd4b6d45b1bad6c9a5d471077e8427f updated golang required to build in go.mod to 1.20.
This makes the devcontainer compatible
Update the version of golang to 1.20 in the devcontainer specification
Smoke test that I can now run make using this container, as opposed to it failing immediately.
=> chore: update go to 1.20 in devcontainer

util/archive/archive.go
Output artifacts in .tgz format that are created on Windows result in wrong directory and file structure when unpacked by 7-zip or on Linux.
Example:
1. Folder structure Windows is
`A\B\C.txt `
2. An output artifact in .tgz format is generated from this (on Windows)
3. The resulting .tgz archive is opened in 7zip
```
(folder) "A\"
(folder) "A\B\"
(file)   "A\B\C.txt"
```
When generating the tar archive the pathes that are written to the tar-file's file header are converted to use forward slashes instead of backslashes independent of the current operation systems path format.
When the above example is repeaded after this fix then 7zip shows the correct folder structure:
```
(folder) A
(folder)   B
(file)       C.txt
```
=> fix: Fixed path separator in .tgz output artifacts created on windows. Fixes #10562

.devcontainer/pre-build.sh
If you attempt `make start` from inside a devcontainer you will be told you need to setup various entries in hosts as per docs/running-locally.md. This fix does that step for you.
I develop inside the supplied devcontainer with just the devcontainer CLI, and this commit would mean I can skip a step in getting started.
Only changes to the devcontainer startup. There are few other options as to how to do this change, as /etc/hosts is initially managed by devcontainer itself.
After the change /etc/hosts in a container brought up with `devcontainer up` contain the entries listed in running-locally.md that are necessary for make start.
=> fix: Setup /etc/hosts for running inside devcontainer

examples/coinflip.yaml, examples/dag-coinflip.yaml, examples/hello-world.yaml
Couler is no longer actively maintained by me: https://github.com/couler-proj/couler
=> docs: Remove references to Couler in examples

go.mod, go.sum, server/sensor/sensor_server_test.go
Adding test coverage for the `ListSensors` function: Without these tests there would be no validation of the ListSensors behavior. This functionality is invoked in the `_SensorService_ListSensors_Handler` func & the `request_SensorService_ListSensors_0` func
I introduced two tests, `TestListSensors` and T`estListSensors_SensorClientNotSet`, to cover different scenarios in the ListSensors function. The first test validates the behavior when the sensor client is not set, while the second test specifically tests the case where the sensor client is set to nil.
`TestListSensors` verifies that the ListSensors function correctly handles the scenario where the sensor client is not set. It expects an error indicating the sensor client is missing, then checks that the list is nil. …
=> chore: adding test coverage for ListSensors func

api/jsonschema/schema.json, api/openapi-spec/swagger.json, docs/fields.md, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1PodGC.md, sdks/java/client/docs/IoArgoprojWorkflowV1alpha1VolumeClaimGC.md, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_pod_gc.py, sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_volume_claim_gc.py, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1PodGC.md, sdks/python/client/docs/IoArgoprojWorkflowV1alpha1VolumeClaimGC.md
Mention defaults for PodGC `strategy` and `volumeClaimGC` in the Fields reference page
- Given that these are for garbage collection (GC), they're kind of important to know for operators 😅 
- the defaults were previously not mentioned in the docs, so I had to look through the source code to find these:
- `volumeClaimGC`: https://github.com/argoproj/argo-workflows/blob/1ba8d317113509c48d9a7959f2bee6ee2e812802/pkg/apis/workflow/v1alpha1/workflow_types.go#L484
- PodGC `strategy`: https://github.com/argoproj/argo-workflows/blob/1ba8d317113509c48d9a7959f2bee6ee2e812802/pkg/apis/workflow/v1alpha1/workflow_types.go#L1050
I found this out the hard way when I realized our clusters had a bunch of unused PVCs laying around 😬 
Should there be a separate column in the tables for all the defaults? I …
=> docs: mention defaults for PodGC `strategy` and `volumeClaimGC`

examples/pod-gc-strategy-with-label-selector.yaml, examples/pod-gc-strategy.yaml
Mention the default `podGC.strategy` in the examples
Follow-up to https://github.com/argoproj/argo-workflows/pull/10971#pullrequestreview-1403456869
Same as #10971
Add a line in `pod-gc-strategy` and `pod-gc-strategy-with-label-selector` that mentions the default for `podGC.strategy`
- by default, Pods are not deleted: https://github.com/argoproj/argo-workflows/blob/1ba8d317113509c48d9a7959f2bee6ee2e812802/pkg/apis/workflow/v1alpha1/workflow_types.go#L1050
=> docs: mention PodGC `strategy` default in examples

.devcontainer/devcontainer.json, .devcontainer/pre-build.sh
make pre-commit doesn't work in devcontainer, with this commit it does.
I'd like an easy way for everyone to be able to maintain workflows, and devcontainers are nearly there.
This fixes that by
a) Moving GOPATH to /home/vscode/go
b) Installing protoc (apt package protobuf-compiler)
c) Ensuring ~/go is writable (so subdirs can be created)
d) Ensuring /home/vscode/go/bin is on the path too
Using /home/vscode/go rather than /go is necessary when doing all the protocol malarky due to requirements on subdirectories.
Launched a new devcontainer with these changes, and ensure `make pre-commit` reaches the end successfully. The resulting tree is unchanged, so all the generated code matches that in git.
=> fix: Make devcontainer able to pre-commit

ui/src/app/shared/components/filter-drop-down.tsx, ui/src/app/shared/components/graph/graph-panel.tsx
Fixes #11129 
So users don't have to manually check and uncheck workflow DAG filter checkboxes
as another group, it would alter the checked state of the other group.  This was due
to non-unique ID attribute.  Changed it so IDs were unique by including grouping index.
All unchecked, `Select All` unchecked:
All checked, `Select All` is checked:
One unchecked, `Select All` is unchecked:
Tested locally/manually
=> feat: Add `Check All` checkbox to workflow dag filter options. Fixes #11129

docs/variables.md, test/e2e/functional/entrypointName-template.yaml, test/e2e/functional/entrypointName-workflow.yaml, test/e2e/functional_test.go, workflow/common/common.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go
Issue #6772 asks for the template name, but we cannot always know what this is (simplest unknowable is kubectl apply of a workflow with a generateName). This is a split from PR #10745 to just provide the variable mainEndpoint, which is set to the name of the invoked entrypoint, which is controllable, knowable, and could be used in the same way, and seems like a useful thing to have anyway.
See new test cases for verification.
=> feat: mainEntrypoint variable

test/e2e/hooks_test.go, workflow/controller/hooks.go, workflow/controller/hooks_test.go
Fixes #11113 
Fixes #11117 
- Check hooked node statuses even workflows completed.
- Check hooked node statuses in `executeWfLifeCycleHook` and `executeTmplLifeCycleHook`
- Unit tests and e2e-tests
- fixes issue #11113 
- ![image](https://github.com/argoproj/argo-workflows/assets/83329336/77ad18ea-e788-4184-8b6f-711cdef6f3ce)
- fixes issue #11117
- Note that we should sleep for some seconds in jobs to wait for trigger Running hooks.
- This problem might be resolved by parallel executing of Running hooks, but that is beyond the scope of this PR.
- ![image](https://github.com/argoproj/argo-workflows/assets/83329336/d09a9cd8-2d81-44dc-b0da-fc1e09c6f2c0)
<details><summary>manifest</summary>
```yaml …
```
=> fix: check hooked nodes in executeWfLifeCycleHook and executeTmplLifeCycleHook (#11113, #11117)

docs/links.md, ui/src/app/shared/components/links.test.ts, ui/src/app/shared/components/links.tsx
Some workflows have specific context which can help greatly in the logs. This would allow the custom link created to optionally contain values from the workflow. As it stands now, `null` is returned which messes up the url.
ex: The link can have a url
`https://app.datadoghq.com/logs?query=pod_name:${metadata.name}-*&from_ts=${status.startedAtEpoch}&to_ts=${status.finishedAtEpoch}&live=false${workflow.metadta.annotations.additionalLogParams}`.
For the workflows that have defined `metadata.annotations.additionalLogParams: '&col=service,@client_id'` the link will be something like 
`https://app.datadoghq.com/logs?query=pod_name:mypod-*&from_ts=874654846548764464&to_ts=null&live=false&col=service,12345` 
and for those that don't have it defined the url will be …
=> feat(ui): Ignore missing vars in custom links

dev/nix/flake.lock, dev/nix/flake.nix
This optimises the nix build time by depending on the required files, changing the docs for example shouldn't force a rebuild.
=> build: use only relevant files in build

server/auth/sso/sso.go
Changed way customClaimGroups are handled in `server/auth/sso/sso.go` `HandleCallback`. 
Before: if failed to retrieve, throws 401 Unauthorized 
After: keeps `groups` nil, logs the error encountered
Fixes #11032
=> fix: Remove 401 Unauthorized when customClaimGroup retrieval fails, Fixes #11032

util/template/template_test.go
This PR adds some tests that were created during the investigation of #11131
Two new tests were added to `template_test.go`, which previously only tested templates with expressions (e.g. `{{= true == false}}`.
The new tests test the behavior of replacing variables with values from the `replaceMap`.
Also, `template_test.go` has been refactored to a table driven design, because there was a lot of duplicated code betwen the test cases.
Ran `go test ./util/template/...`
=> test: add and refactor test for parameters with double and single quote for template replace

docs/memoization.md, workflow/controller/cache/configmap_cache.go, workflow/controller/cache_test.go, workflow/controller/operator_test.go
Ensure that config-maps used for memoization aren't actually important for other uses. Config-maps created for memoization would have the label `workflows.argoproj.io/configmap-type: Cache`, but this was not validated.
This commit changes that, and both load and saving to an existing config-map will require that label to be present, or else the workflow will error with a hopefully helpful message indicating the problem.
All existing config-maps which were created by memoization will have this label already. The only concern is where a config-map existed prior to the first save by memoization. Before this change the config-map could still be used, and now workflows will error instead.
This improves security and prevents writing to the `workflow-controller-configmap` by memoization.
I …
=> fix: prevent memoization accessing wrong config-maps

ui/src/app/workflows/components/workflows-row/workflows-row.tsx
This fixes an issue that causes the workflow list page to crash when the workflow is just submitted and does not have labels yet.
```
./src/app/workflows/components/workflows-row/workflows-row.tsx/WorkflowsRow.prototype.render/WorkflowsRow<@http://localhost:8080/main.ac06adb506164b3d7bc2.js:392200:37
./src/app/workflows/components/workflows-row/workflows-row.tsx/WorkflowsRow.prototype.render@http://localhost:8080/main.ac06adb506164b3d7bc2.js:392199:48
finishClassComponent@http://localhost:8080/main.ac06adb506164b3d7bc2.js:296661:31
updateClassComponent@http://localhost:8080/main.ac06adb506164b3d7bc2.js:296611:44
beginWork@http://localhost:8080/main.ac06adb506164b3d7bc2.js:298121:16
callCallback@http://localhost:8080/main.ac06adb506164b3d7bc2.js:279689:14 …
```
=> fix: Workflow list page crashes for workflow rows without labels

examples/k8s-jobs.yaml
The current example doesn't work. This one is easier to understand and is what's used in other resource template examples such as `examples/k8s-orchestration.yaml`.
=> docs: Consistent example in k8s-jobs.yaml

util/errors/errors.go, util/errors/errors_test.go
Fixes #11236
This treats ```Connection refused``` network errors as transient so that they can be retried.
=> fix: Treat "connection refused" error as a transient network error.

workflow/util/merge.go, workflow/util/merge_test.go
Any hook in workflowDefaults will cause `Error: merging object in json
but data type is not struct, instead is: map`.
This is down to how StrategicMergePatch handles maps of objects and limitations in merging them (a starting point for understading this is https://github.com/golang/go/issues/33487).
Instead, we copy the map of hooks, patch it out of the patch, perform the merge as before and then manually apply it.
Fixes: #11095
There is a new test that covers the merging. Verified by changing workflowDefaults to add a hook and checking that I could run the resulting workflow.
=> fix: Allow hooks to be specified in workflowDefaults

.github/workflows/release.yaml, Dockerfile.windows
Fixes #10738
and the fact that Windows builds were not releasing.
Older builds were on the 1809 container, which isn't supported any more. Chocolatey recently dropped support and this is what killed the build.
The container we are replacing went out of Microsoft support in November 2020, so this shouldn't be a huge surprise for Windows users: https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1809-end-of-servicing
Updates to a supported version of Windows and allows the release mechanism to work again.
- Upgraded dockerfile to ltsc2022
- CI runs on server 2022
I'm not super familiar with how windows containers work (if they do at all :p) but I think this now means that workflows will only run on server 2022 - it looks like containers are pinned to their host in the least …
=> fix: Upgrade windows container to ltsc2022

test/e2e/testdata/loops-steps-limited-parallelism-pvc.yaml, test/e2e/workflow_template_test.go, workflow/controller/operator.go
Fixes #11119 
Modified PVC cleanup logic so that it does not trigger on `ErrParallelismReached` 
Wrote a test with a workflow using loops and two pvc's . Constrained parallelization by setting `parallelism: 1` in the workflow.
=> fix: do not delete pvc when max parallelism has been reached. Fixes #11119

workflow/controller/controller.go, workflow/controller/controller_test.go
fixes #9875
fixes bugs in throttler and syncManager initialization in WorkflowController.
Previously, we just list all running workflows in the `wc.namespace` to initialize throttler and syncManager.
https://github.com/argoproj/argo-workflows/blob/b07de995f3d2a7a38fddb29386fc3e844fb5f30c/workflow/controller/controller.go#L368
As we can install argo-workflows as `cluster-install`, we may create workflows in any namespaces, instead of just in the `wc.namespace`. 
this initialize function may broken the throttler and syncManager if there are workflows running in other namespaces.
=> fix: fix bugs in throttler and syncManager initialization in WorkflowController

.github/workflows/ci-build.yaml, docs/releases.md
We currently test against k8s 1.21. This has been out of support for some time (since 2022-06-28), nobody should be using it.
This PR updates the CI to run against k8s 1.27. 1.27 goes EOL on 2024-06-28.
- Updated CI to test against k8s 1.27
- Modifed docs to explain this fact.
CI passes. (it has passed, there's some github issue causing the results to not come back to prs properly)
=> chore: use k8s 1.27 for CI

docs/memoization.md, docs/work-avoidance.md
Despite #10769 and #10426 both having examples of memoization not working with the examples having no output, no-one has picked up on this.
To address this improve the documentation for memoization and work-avoidance, linking the two ideas and pointing people who want to skip steps towards work-avoidance unless they are really doing what memoization was designed to do.
Issue #10426 is problematic in that some steps get memoized when perhaps they should't, so this commit shouldn't close it.
Fixes #10769
=> docs: Link memoization and work-avoidance

workflow/controller/controller.go
Fixes #11177
Fix Argo DB init conflict when deploy workflow-controller with multiple replicas.
Move the DB init logic to after the leader election completed.
After the code modification, tested the workflow-controller deployment in my environment with 
multiple replicas (3 and 5), both work ok.
=> fix: Argo DB init conflict when deploy workflow-controller with multiple replicas #11177

docs/running-at-massive-scale.md, docs/scaling.md
- ["Running At Massive Scale"](https://argoproj.github.io/argo-workflows/running-at-massive-scale/) is in the User Guide, while ["Scaling"](https://argoproj.github.io/argo-workflows/scaling/) (along with HA, DR, etc) is in the Operator Guide
- link the two to each other as they have different information
- rate limit and GC in one, horizontal and vertical scaling and sharding in the other
- I was actually looking for docs on rate limiting after finding [some config](https://github.com/argoproj/argo-helm/blob/5f55ef2c4cc16d4c91faaf1bdb7e0c1d7385435a/charts/argo-workflows/values.yaml#L75) for it, but couldn't find it in the Operator Guide. Stumbled upon it later in the User Guide.
- Add a "Miscellaneous" section in both docs that has one sentence that links to the other
n/a
Should these …
=> docs: back-link the two separate scaling pages

docs/faq.md, server/auth/gatekeeper.go
- link was requested by Alex, fixes #5832
- also shorten the error message to "token not valid" as, in my experience at least, "for running mode" actually significantly increased confusion (c.f. https://github.com/argoproj/argo-workflows/issues/4991#issuecomment-1466465686)
- everyone on my teams thought that it meant we misconfigured our auth or that only one mode could be used at a time - but actually, we were just missing the `"Bearer "` prefix for our token
- my comment about the `"Bearer "` prefix (https://github.com/argoproj/argo-workflows/issues/4991#issuecomment-1466465686) got a few upvotes, so thought this would be worth documenting as well
- add a link to the auth error message in `gatekeeper.go` when the token is invalid
-  shorten the error message as well, per above …
=> docs(auth): add link to FAQ on invalid token error

Makefile, docs/mentoring.md, docs/workflow-concepts.md
- `make docs-linkcheck` found two broken links
- command runs fine on my local machine now, so maybe https://github.com/argoproj/argo-workflows/pull/10678 was due to an error that was patched
- while fixing that, noticed that the Nix folder got moved to `dev/nix/` in https://github.com/argoproj/argo-workflows/pull/10999/commits/c505e80f572242ebbbef850f6dbd36979ebb8c3d
- fixed both broken links by adding versioned permalinks to updated locations
- uncomment `docs-linkcheck` from `make docs`
- corrected Nix directory comment
Ran `make docs`
=> docs: fix broken links + add back check

cmd/workflow-controller/main.go, workflow/controller/controller.go, workflow/metrics/server.go, workflow/metrics/server_test.go
Fixes #10037
Our datadog agents on GKE collect prometheus metrics from multiple workflow-controllers through the k8s Service. However, the metrics server only starts on the leader workflow-controller, causing some datadog agents to frequently output "Connection refused" error logs.
Therefore, I am aiming to resolve this issue.
I have tried to implement the comment: https://github.com/argoproj/argo-workflows/issues/8283#issuecomment-1379988006
I have added tests and verified the functionality locally.
=> fix(controller): Enable dummy metrics server on non-leader workflow controller

examples/buildkit-template.yaml
add readinessProbe
Fixes #TODO
we got this error `could not connect to unix:///run/buildkit/buildkitd.sock after 10 trials`, when we test buildkit-daemonless.sh build.
Add readinessProbe to make sure The buildkit service start succeeded.
https://github.com/docker/buildx/blob/bab60779cf4df24e73b5692e98f61a80555d1537/driver/kubernetes/manifest/manifest.go#L57-L63
=> docs: Update buildkit-template.yaml

ui/package.json, ui/yarn.lock
We know it's safe to do this for this particular one. The other pinned ones might be there for a reason (potentially breaking)
=> fix: Add ^ to semver version

.gitattributes
There are several more files/folders that are generated (and _not_ [`.gitignore`](https://github.com/argoproj/argo-workflows/blob/5264584496ebb62c7098daa986692284b9e6478a/.gitignore#L25)'d)
- This makes diffs etc easier to read by collapsing these files by default
c.f. [GitHub](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) [Docs](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#generated-code)
- Java SDK docs are [generated](https://github.com/argoproj/argo-workflows/blob/5264584496ebb62c7098daa986692284b9e6478a/Makefile#L257), similar to Python
- CRDs are [generated](https://github.com/argoproj/argo-workflows/blob/5264584496ebb62c7098daa986692284b9e6478a/Makefile#L373)
- quick start …
=> chore: mark more files as generated

ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
Currently, there's no error message indicating why a batch action failed. This PR surfaces that error.
=> chore: Surface batch action error message on workflow list view

server/workflow/workflow_server.go, server/workflow/workflow_server_test.go, ui/src/models/workflows.ts
See discussions in https://github.com/argoproj/argo-workflows/pull/11121#discussion_r1259744758
Live workflow is more up-to-date.
=> fix: Live workflow takes precedence during merge to correctly display in the UI

docs/security.md
Full UI access has some requirements to it, so wanted to add an example `Role` somewhere in the docs for it
- I was looking for something like this myself, but couldn't find it
- A centralized location that could be updated & reviewed sounded very helpful to me as a user
- `pods/log` and `events` were ones one of my teams missed on a first pass (causing #11326)
For one of our platforms, users _only_ have access to the Argo UI and do _not_ have k8s API access. So they would not be covered by traditional `view` roles that may be aggregated to. This was used in combination with [SSO RBAC Namespace Delegation](https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac-namespace-delegation).
- Create a "UI Access" subsection under "User Permissions" on the "Security" page
- Primarily …
=> docs: add UI Access section to Security page

docs/security.md
Was looking to make an addition to the Security page and stumbled upon a few typos
- "workflow requirements features" -> "workflow restrictions feature"
- remove extra space
- add missing closing paren
n/a
=> docs: fix some small typos on Security page

docs/argo-server-sso.md
- Stumbled upon some typos on the page
- Use simpler and more direct language, per the [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
- there are (many) more changes that could be made to the docs according to the k8s style guide, but (significantly) limited myself right now to places I'm already applying fixes to 😅
- didn't want to do wholesale copy-editing of all docs at this point 😅  
- for example, using ["you"](https://kubernetes.io/docs/contribute/style/style-guide/#address-the-reader-as-you) and avoiding ["we"](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-using-we), which are switched between many times in the docs. (also, replacing ["latin phrases"](https://kubernetes.io/docs/contribute/style/style-guide/ …
=> docs: fix typos and simplify wording on SSO page

.github/workflows/gh-pages.yaml
This is more secure and supported https://github.com/peaceiris/actions-gh-pages#supported-tokens
=> build: Remove personal token for docs publishing

test/e2e/hooks_test.go
This fixes one of the flaky tests https://github.com/argoproj/argo-workflows/issues/10807#issuecomment-1631618088. I've seen this multiple times this week.
=> test: Fix flaky test TestWorkflowLevelHooksWaitForTriggeredHook

.github/workflows/gh-pages.yaml
This should fix the issue below:
```
remote: Permission to argoproj/argo-workflows.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/argoproj/argo-workflows.git/': The requested URL returned error: 403
Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```
=> ci: Grant write permission to docs workflow

.github/workflows/release.yaml
I noticed some duplicate code in the release yaml that could be compacted down.
Ran the release a number of times on our fork.
(If you're reviewing all my commits you'll see that I experimented with improving the caching. Due to the way the docker container is constructed, more agressive caching results in failed builds, so I have reverted those changes.)
=> chore: Reduce release yaml

README.md
The intro video is 2-year old and does not capture things correctly.
=> docs: Remove outdated intro video and links in README

workflow/controller/controller.go, workflow/controller/informer/tolerant_cluster_workflow_template_informer.go, workflow/controller/informer/tolerant_workflow_template_informer.go
Fixes #11134. 
The reason for this change is that `resourceVersion=0` does not honor the `limit` in API calls (related issue https://github.com/kubernetes/kubernetes/issues/59684#issuecomment-364627127), which results in making significant LIST calls without `limit`. Below are some screenshots from experiments (credit to Jesse). Same results for other non-pod resources.
Even though we may see `limit=100&resourceVersion=0` in the controller logs, the API server does not honor the limit.
=> fix: Correct limit in controller List API calls. Fixes #11134

.devcontainer/devcontainer.json, .devcontainer/pre-build.sh, docs/running-locally.md
This PR introduces the possibility to connect to services outside the `k3d` cluster used in DevContainer by setting up a distinct hostname. 
The magic hostname `host.docker.internal` is re-used and injected in the `devcontainer.json` and the CoreDNS configmap.
Within the same Docker environment a Web container running `nginx` has been created. After that, VSCode with DevContainer is started. When DevContainer is up and running, exec a shell in a pod and issue:
```
kubectl exec -ti deploy/minio -- curl -v telnet://host.docker.internal:80
* Rebuilt URL to: telnet://host.docker.internal:80/
*   Trying 172.17.0.1...
* TCP_NODELAY set
* Connected to host.docker.internal (172.17.0.1) port 80 (#0)
=> feat: Enable local docker ip in for communication with outside k3d

docs/workflow-concepts.md
The documentation does not talk about Workflows Server and Workflow controller
I added few basic descriptions about that components.
Just take a look at the rest of the documentation.
=> docs: link Core Components to Architecture

workflow/util/util.go
…ally after manually stopped
No, I just met a problem in my work, but I made no issue but fix it myself because of time constraints
Most of the users I am responsible for use workflow-templates to create workflows. However, there is a problem that has been bothering us: after the workflows created through the workflow templates are manually stopped, when retrying the failed node (because of the Stop operation) and all subsequent nodes will be skipped. Here is an example:
After manually stopped:
Ater manually retried:
After carefully reading the relevant code, we finally realized that in the `FormulaRetryWorkflow` function, `newWF.Status.StoredWorkflowSpec.Shutdown` should be set to an empty string instead of keeping the shutdown information.
The following is a sample workflow template …
=> fix: Enable the workflow created by a wftmpl to retry after manually stopped

ui/src/app/workflows/components/workflows-list/workflows-list.tsx, ui/src/app/workflows/components/workflows-row/workflows-row.tsx
- Fix broken ui on a workflow list.
- Pre
- Post
N/A
=> fix: Modify broken ui by archived col

server/auth/sso/sso.go
Fixes #11369
The current implementation of the OAuth2 callback handler lacks sufficient logging, making it difficult to identify errors and misconfigurations related to SSO (Single Sign-On). By adding detailed logs, we can simplify the process of configuring SSO and troubleshoot any issues that may arise.
Due to the insufficient logs in the oauth2 callback handler, it wasn't easy to identify the errors and misconfigurations about sso.
If the servers writes detailed logs, it would help the process configuring sso.
I have added error logging to the `/oauth2/callback` handler.
To verify these changes, I performed the following tests:
1. Test with an incorrect client secret - I set the client secret to `foobarbaz`, which is an invalid value.
```
time="2023-07-16T12:04:06.600Z" level=info …
```
=> feat: Improve logging in the oauth2 callback handler

test/e2e/hooks_test.go
```
✔ lifecycle-hook-tmpl-level-dtcwf   Workflow  43s     
└ ✔ step-1                          Pod       7s      
└ ✔ lifecycle-hook-tmpl-level-dtcwf Steps     43s     
└ ✔ [0]                             StepGroup 24s     
└ ✔ step-1.hooks.running            Pod       4s      
└ ✔ step-1.hooks.succeed            Pod       12s     
└ ✔ [1]                             StepGroup 19s     
└ ✔ step-2                          Pod       4s      
└ ✔ step-2.hooks.succeed            Pod       5s      
suite.go:87: test panicked: runtime error: invalid memory address or nil pointer dereference
goroutine 670 [running]:
runtime/debug.Stack()
/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
github.com/stretchr/testify/suite.failOnPanic(0xc00033fd40, {0x1b90420, 0x2f63060}) …
```
=> test: Comment out a flaky test in TestTemplateLevelHooksStepSuccessVersion

docs/releasing.md, hack/what-to-cherry-pick.sh
Currently the script only works for "fix" commits so this PR generalizes it and added more clarity in the instructions.
=> docs: Improve release instructions

docs/roadmap.md
Per our discussion in contributors meeting, the current Google Docs is messy and we'll switch to use the markdown file.
=> docs: Add notice in roadmap.md

go.mod, workflow/artifacts/azure/azure.go, workflow/artifacts/azure/azure_test.go
Fixes #11385
To fix #11385
Before, azure artifact driver would not create/make the local subdir for the file to be downloaded into. Now it does.
Tested with azurite. The test is included but skipped by default.
=> fix: download subdirs in azure artifact. Fixes #11385

Makefile
This is to avoid issues like the following, where a step takes longer to run than usual on GitHub Actions.
```
● retry-with-recreated-pvc   Workflow  0s      
└ ● retry-with-recreated-pvc Steps     0s      
└ ● [0]                      StepGroup 0s      
└ ◷ generate                 Pod       0s      
cli_test.go:897: timeout after 1m0s waiting for condition
../../dist/argo -n argo retry retry-with-recreated-pvc
exit status 1time="2023-07-19T01:36:47.880Z" level=fatal msg="rpc error: code = InvalidArgument desc = workflow must be Failed/Error to retry"
cli_test.go:900: 
Error Trace:	/home/runner/work/argo-workflows/argo-workflows/test/e2e/cli_test.go:900
/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:265 …
```
=> ci: Bump E2E_WAIT_TIMEOUT to avoid E2E test failures in CI

workflow/common/convert.go
Fixes #7286
Currently, the creator labels of a CronWorkflow that has creator labels are not propagated to the Workflow to be scheduled.
I made some labels related to the creator of a CronWorkflow to be propagated to the Workflow to be created.
The list of labels is as follows.
- `workflows.argoproj.io/creator`
- `workflows.argoproj.io/creator-email`
- `workflows.argoproj.io/creator-preferred-username`
1. Create a simple CronWorkflow like the following in the web console of an SSO-enabled environment:
```yaml
metadata:
name: cron-workflow-test
spec:
workflowSpec:
templates:
inputs: {}
outputs: {}
metadata: {}
container:
name: ''
image: alpine:3.6
command:
- sh
- '-c'
args:
- date; sleep 3
resources: {}
arguments: {}
schedule: '* * * * *' …
```
=> feat: Propagate creator labels of a CronWorkflow to the Workflow to be scheduled

test/e2e/hooks_test.go
```
Condition "to be Succeeded" met after 7s
Checking expectation example-stepsflt4x
example-stepsflt4x : Succeeded 
hooks_test.go:425: 
Error Trace:	/home/runner/work/argo-workflows/argo-workflows/test/e2e/hooks_test.go:425
/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:68
/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:43
/home/runner/work/argo-workflows/argo-workflows/test/e2e/hooks_test.go:423
Error:      	Not equal: 
expected: "1/1"
actual  : "2/2"
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-(v1alpha1.Progress) (len=3) "1/1"
+(v1alpha1.Progress) (len=3) "2/2"
Test:       	TestHooksSuite/TestTemplateLevelHooksWaitForTriggeredHook
Checking expectation example-stepsflt4x
```
=> test: Comment out a flaky assertion in TestTemplateLevelHooksWaitForTriggeredHook

ui/src/app/shared/services/workflows-service.ts, ui/src/app/workflows/components/resubmit-workflow-panel.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflows-row/workflows-row.tsx, ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx, ui/src/models/workflows.ts
Fixes #11371 
- Add query string `uid` to the workflow detail page.
- Pass `uid` from the workflow list page.
- Use `uid` in the following functions
- `getArchived`
- `resubmitArchived`
1. Prepare two archived workflows
1. Successfully opened
1. Resubmit with changed param
1. Create a finite-ttl workflow 
URL: `http://localhost:8080/workflows/argo/omniscient-dragon?tab=workflow`
2. Workflow gone by GC
URL is set to: `http://localhost:8080/workflows/argo/omniscient-dragon?tab=summary&uid=4dd0192a-d976-4584-a13b-3e3a8eb196af`
3. Refresh page
=> fix: add query string to workflow detail page(#11371)
