- USERS.md
https://www.linkedin.com/company/wooliesx/
Checklist:
Tips:
> docs(users): Add WooliesX

- workflow/artifacts/gcs/gcs.go
Checklist:
re #6276 
I took the liberty of not adding tests because it's a 1 line change and there are currently no tests for the gcs artifact driver :stuck_out_tongue: 
@tymokvo I know you implemented this changed and asked whether we should submit a PR, I went to the liberty of just submitting it and letting the maintainers decide whether or not they want it merged :smile:
> fix(gcs): throw argo not found error if key not exist

- go.mod
- go.sum
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>
Closes #6049
See fix description in https://github.com/argoproj/pkg/pull/43
> fix: Server crash when opening timeline tab for big workflows

- workflow/controller/operator.go
> fix(controller): Mark workflows wait for semaphore as pending. Fixes #6351

- docs/environment-variables.md
- server/apiserver/argoserver.go
…MaxGRPCMessageSize for argo-server
Checklist:
Tips:
> feat: added support for GRPC_MESSAGE_SIZE env var 

- workflow/artifacts/gcs/gcs.go
Tested with 
workflow
```
kind: Workflow
metadata:
generateName: data-transformations-
labels:
workflows.argoproj.io/test: "true"
namespace: default
spec:
entrypoint: data-transformations
templates:
- name: data-transformations
steps:
- - name: list-log-files
template: list-log-files
- - name: process-logs
template: process-logs
withParam: "{{steps.list-log-files.outputs.result}}"
arguments:
parameters:
- name: file-name
value: "{{item}}"
- name: list-log-files
data:
source:
artifactPaths:
name: test-bucket
gcs:
bucket: gcp-public-data-landsat
key: LC08/01/001/003/LC08_L1GT_001003_20140812_20170420_01_T2
transformation:
- expression: "filter(data, {# endsWith \"TIF\"})"
- name: process-logs
inputs:
parameters:
- name: file-name
container:
image: …
```
> feat(executor): enable gcs artifact ListObjects, supports data-transformations

- workflow/executor/docker/docker.go
> fix(executor): Remove 15s guard for Docker executor. Fixes #6415

- util/template/template.go
- workflow/controller/dag.go
- workflow/controller/operator.go
- workflow/controller/steps.go
> fix(controller): Reinstate support for outputs.results for containers. Fixes #6428

- docs/environment-variables.md
- hack/check-env-doc.sh
- server/apiserver/argoserver.go
…AGE_SIZE to argo-server
Checklist:
Tips:
> feat(server): support changing MaxGRPCMessageSize using env variable

- ui/src/app/shared/components/clipboard-text.tsx
Before:
After:
Checklist:
Tips:
> fix(ui): Do not display clipboard if there is no text

- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
Signed-off-by: AntoineDao <antoinedao1@gmail.com>
Fixes #6449
Checklist:
> fix(controller): set resources from script templates

- USERS.md
I joined [Ubie](https://ubie.life/en). As we use Argo Workflows, Events and Rollouts, I added the company to the users.
Checklist:
> docs: Add Ubie to users

- workflow/controller/operator.go
closes #6445 
Checklist:
Tips:
> fix(controller): Exit template shouldn't fail with max parallelism reached

- USERS.md
Checklist:
With 🧡 from Gitpod.
> docs(users): add gitpod

- .github/workflows/ci-build.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/release.yaml
- Dockerfile
- Dockerfile.windows
- Makefile
- go.mod
- go.sum
Fixes #5563
Needed for dataflow compatability.
> feat!: Upgrade to Golang 1.16. Fixes #5563

- .github/workflows/ci-build.yaml
- test/e2e/argo_server_test.go
> build: Fix build. Fixes #6484

- CHANGELOG.md
- workflow/controller/operator.go
- workflow/controller/operator_workflow_template_ref_test.go
closes #6469 
Checklist:
Tips:
> fix(controller): Delete the PVCs in workflowtemplateRef

- workflow/executor/docker/docker.go
Fixes #6352 
Second attempt for reverted PR: #6499 
Checklist:
Tips:
> fix(executor/docker): re-revert -- fix random errors with message "No such container:path". Fixes #6352

- docs/argo-server-auth-mode.md
Signed-off-by: Hong Wang <wanghong230@gmail.com>
Checklist:
Tips:
> docs: Update the Auth doc default mode

- USERS.md
- docs/installation.md
For convenience, include a link to the latest release in the installation Wiki page.
> Add link to latest release in installation.md

- CHANGELOG.md
- workflow/util/util.go
- workflow/util/util_test.go
> fix(controller): Fix panic in addParamToGlobalScope

- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- workflow/controller/taskset.go
- workflow/controller/taskset_test.go
> fix(controller): fix taskset warning in Non-HTTP Template scenario

- go.mod
- go.sum
- server/auth/sso/sso.go
> fix: Upgrade pkg to v0.10.1. Fixes #6521

- workflow/controller/operator.go
- workflow/controller/operator_concurrency_test.go
> fix: Fix the Status update for node with synchronization lock

- docs/quick-start.md
- docs/running-locally.md
Updating Quickstart guide to include recommendation to change default passwords.
Checklist:
Tips:
> docs: TOB-ARGO-TM16: Update Quickstart guide

- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
Checklist:
Fixes https://github.com/argoproj/argo-workflows/issues/5942
Tips:
> fix: use execWf when setting PodMetadata

- cmd/argo/commands/server.go
> fix: Fix `x509: certificate signed by unknown authority` error

- USERS.md
- docs/argo-server-sso.md
- server/auth/sso/sso.go
- server/auth/types/claims.go
- server/auth/types/claims_test.go
…d with Okta
Signed-off-by: Gage Orsburn <gorsburn@botkeeper.com>
Tips:
> feat: Adding SSO support for Okta. Fixes #6165

- workflow/artifacts/oss/oss.go
This would be helpful for admins to debug and audit.
> feat(artifact): Allow to set bucket logging for OSS artifact driver

- docs/workflow-archive.md
> Add period

- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- go.mod
- go.sum
- test/e2e/ui/ui-pipeline.yaml
- ui/src/app/pipelines/components/pipeline-details/pipeline-details.tsx
- ui/src/app/pipelines/components/pipeline-details/pipeline-graph.ts
- ui/src/app/shared/components/icon.ts
- ui/src/models/step.ts
> feat: upgrade argo-dataflow to v0.0.90

- .github/workflows/changelog.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/release.yaml
- .github/workflows/snyk.yml
Fixes https://github.com/argoproj/argo-workflows/issues/6581.
> ci: Disable builds on forks

- docs/fields.md
- examples/exit-handler-slack.yaml
Signed-off-by: J.P. Zivalich <j.p.zivalich@gmail.com>
This PR adds a slack webhook exit handler example to the `/examples` directory. Resolves #4152
>  docs: Add slack exit handler example. Resolves #4152 

- mkdocs.yml
Fixes https://github.com/argoproj/argo-workflows/issues/6627.
Tips:
> docs: Fix incorrect link to examples

- manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml
- manifests/install.yaml
> fix: Fixed typo in clusterrole

- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- go.mod
- go.sum
> feat: Upgrade dataflow to v0.0.98

- workflow/controller/controller_test.go
- workflow/controller/indexes/workflow_index.go
- workflow/controller/indexes/workflow_index_test.go
> fix: Do not index complete workflow semaphores

- wf.yaml
- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix(controller): Set finishedAt for workflow with Daemon steps

- docs/workflow-templates.md
Fixes #6678. cc @sarabala1979 
Tips:
> docs: Add section to clarify how to use parameters in workflow templates

- hack/release-notes.md
Fix #6671
Signed-off-by: makocchi-git <makocchi@gmail.com>
> docs: Update download url

- docs/workflow-templates.md
> docs: Add note on the support for priority in workflow templates

- ui/src/app/shared/components/button.tsx
- ui/src/app/shared/components/upload-button.tsx
fixes #4975
checked all elements that import button, all looks good
- import {Button}
- import {UploadButton}
- import {LinkButton}
- import {Links}
old(left)-new(right)
Tips:
> fix(ui): button margin

- .github/workflows/snyk.yml
- ui/package.json
- ui/yarn.lock
> fix: run Snyk on UI. Fixes #6604

- persist/sqldb/mocks/WorkflowArchive.go
- persist/sqldb/null_workflow_archive.go
- persist/sqldb/workflow_archive.go
- server/workflowarchive/archived_workflow_server.go
- server/workflowarchive/archived_workflow_server_test.go
- test/e2e/fixtures/e2e_suite.go
- ui/src/app/archived-workflows/components/archived-workflow-filters/archived-workflow-filters.tsx
- ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
- ui/src/app/reports/components/reports.tsx
- ui/src/app/shared/services/archived-workflows-service.ts
- workflow/controller/estimation/estimator_factory.go
- workflow/controller/estimation/estimator_factory_test.go
fixes #5824 to a certain extend
workflow URL:
localhost:8080/workflows/argo/**lovely-dragon**
archived workflow URL:
localhost:8080/archived-workflows?name=**lovely-dragon**
Tips:
> feat: archivewf add name filter. Fixes #5824

- workflow/controller/steps.go
- workflow/controller/steps_test.go
> fix: panic in prepareMetricScope

- ui/src/app/shared/components/timestamp.tsx
> fix(ui): handle undefined timestamp. Fixes #6447

- ui/src/app/shared/services/workflows-service.ts
> feat(ui): logsViewer use archived log if node finished and archived. Fixes #5504

- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
- workflow/util/util.go
Added a test to verify.
Fixes #6583
> fix: remove windows UNC paths from wait/init containers. Fixes #6583

- workflow/artifacts/git/git.go
- workflow/artifacts/git/git_test.go
> fix(executor): allow emptyRepo artifact input. Fixes #5857

- docs/README.md
> docs: Fix link to examples in website

- cmd/argo/commands/root.go
- docs/cli/argo.md
> docs: Fix docs typo.

- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix: Daemond status stuck with Running

- examples/README.md
* Fixes indentation that delineates parallel vs sequential steps
Tips:
> docs: Fix indentation describing how steps work

- USERS.md
Signed-off-by: yangtian9999 <yangtian9999@163.com>
Tips:
> docs: Add Sutpc company into the user list.

- examples/dag-conditional-artifacts.yaml
> fix a typo in example file dag-conditional-artifacts.yaml

- USERS.md
We (incrmntal Ltd.) are using argo to schedule our workflows and pipelines on kubernetes in EKS/AWS.
> Add "incrmntal" to list of users

- docs/cli/argo_server.md
- util/help/topics.go
> fix: update outdated links for cli

- USERS.md
We are using Argo Workflows to create MLOps platform for the Camera Intelligence team in Cisco Meraki.
Thank you for building this project!
/assign @terrytangyuan 
/cc @ramdootp @amsaha
> docs: Add Cisco to list of users

- USERS.md
This file is missing and will be added back once https://github.com/argoproj/argoproj/pull/90 is merged.
> docs: Fix link to community survey

- workflow/controller/operator.go
- workflow/controller/operator_metrics_test.go
> fix: Missing duration metrics if controller restart

- workflow/ttlcontroller/ttlcontroller.go
- workflow/ttlcontroller/ttlcontroller_test.go
Signed-off-by: NikeNano <niklas.sven.hansson@gmail.com>
Tips:
> chore: clean up of the TTL controller and remove unused function

- pkg/apiclient/http1/facade.go
> fix(apiclient): Remove default client in facade. Fixes #6733 

- pkg/apiclient/argo-kube-workflow-service-client.go
- pkg/apiclient/watch-intermediary.go
> feat: implement WatchEvents for argoKubeWorkflowServiceClient. Fixes #6173

- .github/workflows/ci-build.yaml
- .golangci.yml
- cmd/argo/commands/cron/get_test.go
- cmd/argo/commands/resubmit.go
- cmd/argo/commands/retry.go
- cmd/argoexec/commands/agent.go
- cmd/argoexec/commands/root.go
- pkg/apiclient/watch-intermediary.go
- server/apiserver/argoserver.go
- test/e2e/cli_test.go
- test/e2e/functional_test.go
- util/kubeconfig/kubeconfig.go
- workflow/common/util.go
- workflow/controller/agent_test.go
- workflow/controller/controller.go
- workflow/controller/dag_test.go
- workflow/controller/indexes/configmap_index_test.go
- workflow/controller/operator_workflow_template_ref_test.go
- workflow/controller/steps_test.go
- workflow/controller/taskset_test.go
- workflow/controller/workflowpod.go
- workflow/cron/controller.go
- workflow/executor/common/common.go
- workflow/executor/emissary/emissary.go
- workflow/signal/signal.go
- workflow/sync/mutex_test.go
- workflow/sync/throttler_test.go
- workflow/ttlcontroller/ttlcontroller_test.go
- workflow/util/merge_test.go
> chore: enable `gci` and `ineffassign` linters

- examples/cron-backfill.yaml
> fix(docs): cron backfill example. Fixes #6832

- workflow/artifacts/http/http.go
- workflow/artifacts/http/http_test.go
Signed-off-by: smile-luobin <luobin_smile@163.com>
Tips:
> fix(exec): Failed to load http artifact. Fixes #6825

- .golangci.yml
- util/kubeconfig/kubeconfig.go
- workflow/executor/kubelet/client.go
Updated code to handle closing response body in locations detected by` bodyclose` linter. 
resolves #6837
> chore: enabled `bodyclose` linter

- .golangci.yml
- workflow/controller/operator_test.go
- workflow/controller/workflowpod_test.go
> chore: enabled exportloopref linter

- USERS.md
> docs: Add Promaton to users.md

- ui/src/app/workflows/components/submit-workflow-panel.tsx
- ui/src/models/workflows.ts
Testing:
Explanation of test steps:
1. Submit template from workflow templates view with default main parameter. New behavior: the default parameter value appears in the UI.
2. Submit entrypoint template from workflow templates view with no default parameters. The default parameter value appears in the UI for message 1, but is successfully overridden on submission.
This is the `arg-defaults` workflow template:
```
metadata:
name: arg-defaults
spec:
templates:
- name: main
inputs:
parameters:
default: "main-default"
dag:
tasks:
- name: say
template: say-message
arguments:
parameters:
- name: message2
value: "{{inputs.parameters.message}}"
- name: say-message
inputs:
parameters:
- name: message1 …
```
> fix(UI): use default params on template submit form. Fixes #6779

- docs/client-libraries.md
- sdks/python/README.md
- sdks/python/examples/hello-world-from-raw-yaml.py
- sdks/python/examples/hellow-world-from-object.py
> docs: Add examples to illustrate two ways of using Python SDK

- docs/upgrading.md
> docs: Add TLS metrics commit in upgrading guide

- cmd/argoexec/commands/root.go
- cmd/argoexec/main.go
- util/util.go
- workflow/executor/executor.go
Code Refactoring mentioned in issue  #6999
> refactor: Fixing typo WriteTeriminateMessage #6999

- USERS.md
- docs/node-field-selector.md
Signed-off-by: Kyle Hanks <khanks@investvoyager.com>
> fix: typo in node-field-selector.md

- .github/ISSUE_TEMPLATE/enhancement_proposal.md
- .github/ISSUE_TEMPLATE/regression.md
> docs: Edits on issue templates for different issue types

- docs/argo-server-sso.md
Signed-off-by: bjenuhb <basanth_jenuhb@intuit.com>
Tips:
> docs: update documentation for SSO namespace delegation

- workflow/executor/executor.go
- workflow/executor/k8sapi/client.go
Signed-off-by: momom <51011095+momom-i@users.noreply.github.com>
Tips:
* You can ask for help! 
Fix #6886
> feat: Add FAQ link to unknown pod watch error. Fixes #6886

- docs/workflow-templates.md
Fixes #6824
Make the workflow template UI dropdown selection example more obvious to the user
---
Tips:
> docs(ui): document wftemplate enum dropdown. Fixes #6824

- .golangci.yml
> chore: faster `make lint`

- .github/workflows/ci-build.yaml
- Makefile
- workflow/artifacts/git/git_test.go
- workflow/controller/controller.go
- workflow/controller/controller_test.go
- workflow/executor/executor_test.go
> chore: faster `make test`

- .github/workflows/ci-build.yaml
> chore: faster `make codegen`

- .github/workflows/ci-build.yaml
- .gitignore
- Makefile
- hack/git/hooks/commit-msg
> chore: fix `make test`

- workflow/common/common.go
- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
Signed-off-by: Denis Melnik <denis@codefresh.io>
Adding annotation of default container to workflow pod according to the issue #5643.
> feat(controller): Add default container annotation to workflow pod. FIxes: #5643

- workflow/controller/operator.go
- workflow/controller/operator_test.go
Signed-off-by: Josh Carp <jm.carp@gmail.com>
Tips:
> chore(controller): s/retryStrategy.when/retryStrategy.expression/

- docs/client-libraries.md
> docs: add Hera workflows URL to the client library doc

- workflow/executor/executor.go
> fix: do not patch empty progress. fixes #7184

- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- test/e2e/pod_cleanup_test.go
- workflow/controller/controller.go
- workflow/controller/operator.go
- workflow/controller/pod_cleanup.go
- workflow/controller/pod_cleanup_test.go
- workflow/validate/validate.go
- workflow/validate/validate_test.go
Fixes #7159
Pods should be labelled if there are not going to be deleted.
> fix: refactor/fix pod GC. Fixes #7159

- docs/running-locally.md
This PR cleans up the "Running Locally" developer guide.
> docs: improve local dev guide

- cmd/argoexec/commands/emissary.go
- cmd/argoexec/commands/wait.go
- test/e2e/functional/pause-after.yaml
- test/e2e/functional/pause-before-after.yaml
- test/e2e/functional/pause-before.yaml
- test/e2e/functional_test.go
- workflow/controller/workflowpod.go
> feat: pause steps so users can shell in and debug them. Fixes #6841

- docs/workflow-executors.md
> docs: Mention Emissary will kill sub-processes

- docs/workflow-executors.md
> chore(docs/workflow-executors.md): remove extra spaces.

- SECURITY.md
Resolves https://github.com/argoproj/argo-workflows/issues/6971
Signed-off-by: Jesse Suen <jesse@akuity.io>
> docs: update contact information for security issues

- USERS.md
> docs: Add datarobot to users.md

- docs/fields.md
- hack/docgen.go
> docs: Remove non-workflow types from fields.md

- ui/src/app/workflows/components/events-panel.tsx
> fix(ui): Fix events error. Fixes #7320

- SECURITY.md
Signed-off-by: Michael Crenshaw <michael@crenshaw.dev>
Closes https://github.com/argoproj/argo-workflows/issues/7330
> docs: add link from security.md to docs/security.md

- .github/workflows/ci-build.yaml
- Makefile
- hack/check-logging.sh
- test/e2e/agent_test.go
- workflow/controller/agent.go
- workflow/controller/cache_gc.go
- workflow/controller/controller.go
- workflow/controller/operator.go
- workflow/controller/taskset.go
- workflow/executor/agent.go
> fix: Use and enforce structured logging. Fixes #7243 

- docs/workflow-controller-configmap.yaml
docs: Added in-code docs for sso option insecureSkipVerify
docs: removed pointless whitespaces
Signed-off-by: Siebren Zwerver <siebren@siebjee.nl>
> docs: Added in-code docs for sso option insecureSkipVerify

- Makefile
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- manifests/quick-start/base/overlays/workflow-controller-configmap.yaml
- test/e2e/fixtures/needs.go
- workflow/controller/container_set_template_test.go
- workflow/controller/controller.go
- workflow/controller/controller_test.go
- workflow/controller/operator_test.go
- workflow/controller/workflowpod_test.go
- workflow/validate/validate_test.go
> fix: Correct default emissary bug. Fixes #7224

- USERS.md
Signed-off-by: henrywangx <henrywangx@gmail.com>
Tips:
> docs: add Inceptio Technology into users

- hack/release-notes.md
> docs: Differentiate instructions for installing different components. Fixes #7470

- USERS.md
> docs: Add Gllue to list of users

- workflow/controller/operator.go
- workflow/controller/operator_test.go
fixes #7332 
By adding to the guard condition for child nodes, `processAggregateNodeOutputs` now only iterates over successful child nodes which are not `Retry` type. We ignore `Retry` nodes to avoid duplicate copies of output parameters in nodes.
Example workflow from issue:
```
kind: Workflow
metadata:
name: hr-retry-replication
namespace: argo
selfLink: >-
/apis/argoproj.io/v1alpha1/namespaces/argo/workflowtemplates/hr-retry-replication
uid: 43fe4ce6-1851-4de2-9739-53ff9ffba987
resourceVersion: 
labels:
app.kubernetes.io/managed-by: Helm
annotations:
meta.helm.sh/release-name: hr-retry-replication
meta.helm.sh/release-namespace: argo
managedFields:
- manager: Go-http-client
operation: Update
fieldsType: FieldsV1 …
```
> fix: only aggregates output from successful nodes

- workflow/controller/operator.go
Fixes https://github.com/argoproj/argo-workflows/issues/7476.
`ProcessArgs` is used in both workflow pod and operator. However, only the operator has access to the configmap informer. When the workflow pod tries to resolve the input parameters from global arguments, the value becomes non-nil and in this case, the operator should try to retrieve the parameter value from the configmap. We need to modify the logic in operator to have valueFrom take precedence over the incorrect value.
> fix: Global param value incorrectly overridden when loading from configmaps. Fixes #7476

- sdks/python/README.md
- sdks/python/examples/hello-world-from-object.py
- sdks/python/examples/hello-world-from-raw-yaml.py
Fixes https://github.com/argoproj/argo-workflows/issues/7293. 
> docs: Add additional args to avoid type checks. Fixes #7293

- sdks/python/client/argo_workflows/__init__.py
- sdks/python/client/argo_workflows/api_client.py
- sdks/python/client/argo_workflows/configuration.py
- sdks/python/client/setup.py
- sdks/python/sdk_version.py
Fixes #7516. Reference: https://www.python.org/dev/peps/pep-0440/
> fix: Make dev version of the Python SDK PEP440 compatible. Fixes #7516

- Makefile
> chore(cli): add windows .exe extension

- workflow/controller/operator.go
Signed-off-by: henrywangx <henrywangx@gmail.com>
Tips:
> fix: handle source file is empty for script template

- sdks/python/README.md
Signed-off-by: fruttasecca <gobbijacopo91@gmail.com>
Tips:
> docs: fix python SDK README.md example import

- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/7406
I tested via unit test.
> fix(controller): fix pod stuck in running when using podSpecPatch and emissary

- .github/workflows/ci-build.yaml
- .github/workflows/release.yaml
I hope this fixes the broken builds.
> chore: Update CI node

- .github/workflows/snyk.yml
> chore: Remove dupe image scanning

- server/artifacts/artifact_server.go
> fix: Support artifact ref from tmpl in UI. Fixes #7587

- docs/use-cases/machine-learning.md
- docs/use-cases/other.md
> docs: More resources on machine learning

- docs/survey-data-privacy.md
> docs: Update privacy page. Fixes #7610

- docs/workflow-executors.md
> docs: Update executors docs for 3.3 release

- workflow/artifacts/git/git.go
Fixes #7593
Signed-off-by: jack.stone@cambridgeconsultants.com
Tips:
> fix: Fix non-standard git username support

- server/artifacts/artifact_server.go
This fixes an index out of bounds issue in #7636. We register an error when we know an out of bounds issue will arise and return. 
Fixes #7636
> fix: error when path length != 6. Fixes #7636

- Makefile
> chore: Remove `docker buildx` command.

- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- workflow/controller/operator.go
> fix: Support terminating with `templateRef`. Fixes #7214

- .github/pull_request_template.md
```diff
- * Say how how you tested your changes. If you changed the UI, attach screenshots.
+ * Say how you tested your changes. If you changed the UI, attach screenshots.
```
> docs: fix double appearance of how

- test/e2e/daemon_pod_test.go
- test/e2e/fixtures/when.go
> test: Add daemon set tests. Fixes #7409

- Dockerfile
I tried to run this, it seg faulted numerous times, but my PR doesn't change anything that this target should touch. 
Tips:
> chore(deps): Update docker version to latest to address critical vulnerabilities 

- sdks/python/README.md
> docs: Add docs on installing Python package and versioning

- docs/executor_plugins.md
- docs/plugins.md
- mkdocs.yml
- plugins/README.md
> docs: Improve plugin template docs. Fixes #7683

- .github/workflows/gh-pages.yaml
- docs/mentoring.md
- mkdocs.yml
closes #7129
Tips:
Default
Dark Mode
> docs: Add toggle for dark mode

- workflow/cron/operator.go
- workflow/cron/operator_test.go
> fix: Missed workflow should not trigger if Forbidden Concurreny with no StartingDeadlineSeconds

- README.md
- docs/security.md
- mkdocs.yml
> docs: Make SECURITY.md easy to discover. Fixes #7756

- docs/workflow-executors.md
https://argoproj.github.io/argo-workflows/workflow-executors/
> docs: emissary workflow executor document nested blocks

- .github/workflows/release.yaml
> chore: Correct VERSION in release job. Fixes #7766

- docs/workflow-concepts.md
Signed-off-by: jyc <zamonia500@gmail.com>
Tips:
Why i'd like to enhance this documentation:
* Current documentation feels like argo doesn't have a way to run steps inner list one by one.
> docs: Make the description of `Steps` more infomative

- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
> feat: Surface container and template name in emissary error message. Fixes #7780

- docs/artifact-repository-ref.md
> docs: Clarification and edits on artifact repository reference docs

- docs/mentoring.md
> docs: Clarify mentoring and Google Summer of Code process

- examples/README.md
- examples/sidecar-dind.yaml
- examples/sidecar-nginx.yaml
- examples/sidecar.yaml
Add command to the sidecar examples,
so that they are runnable with the default emissary executor
> docs: add command to sidecar examples

- cmd/workflow-controller/main.go
- docs/upgrading.md
- workflow/controller/controller.go
- workflow/controller/controller_test.go
This removes the pod workers and the pod queue and directly writes into the workflow queue instead. 
Fixes #4090
> feat: remove pod workers. Fixes #4090

- .github/ISSUE_TEMPLATE/mentoring_request.md
- docs/mentoring.md
> docs: Add issue template for mentoring requests

- cmd/argo/commands/cron/create.go
fix(cli): fix typo in argo cron error messages
> fix(cli): fix typo in argo cron error messages

- docs/variables.md
`errors are not often not raised` - this description doesn't make sense, and it should be `errors are often not raised`.
Fixes #TODO
> docs: Fixed the typo in the document

- docs/upgrading.md
> docs: Add missing link to commit on removal of pod workers

- workflow/controller/operator.go
- workflow/controller/operator_metrics_test.go
Signed-off-by: Oleg Mayko <oleg.mayko@swisscom.com>
Fixes #7819
> fix: trim spaces while parse realtime metrics value. Fixes #7819

- sdks/python/.gitignore
- sdks/python/Makefile
Signed-off-by: Baz Chalk <boruch11@gmail.com>
Fixes #7881
> fix: Add license to python sdk. Fixes #7881

- docs/quick-start.md
Adding slightly more detail during submission portion of workflow quick start doc.
A nice follow up may be to include some UI instructions for the workflow below.
> docs: provide more details in quick start during workflow submit

- plugins/executor/hello/README.md
- plugins/executor/hello/hello-executor-plugin-configmap.yaml
- plugins/executor/hello/plugin.yaml
- plugins/executor/slack/README.md
- plugins/executor/slack/plugin.yaml
- plugins/executor/slack/slack-executor-plugin-configmap.yaml
> chore: Reduced Python plugins permissions

- persist/sqldb/backfill_nodes.go
- persist/sqldb/migrate.go
> fix: Fix `rowserrcheck` lint errors

- workflow/progress/updater.go
> fix: Remove unnecessary check on HTTP node type

- .github/ISSUE_TEMPLATE/mentoring_request.md
> docs: Update mentoring_request.md

- workflow/controller/agent.go
> feat: Reduce agent pod permissions. Fixes #7914

- .github/ISSUE_TEMPLATE/mentoring_request.md
- docs/mentoring.md
> docs: Clarify expectations of the mentor/mentee relationship.

- .github/dependabot.yml
@alexec is okay with increasing the limit to 2 now.
> chore: Allow dependabot to open two prs

- .github/workflows/ci-build.yaml
- Dockerfile
- Dockerfile.windows
> chore: Update kubectl versions in Dockerfiles

- pkg/apis/workflow/v1alpha1/workflow_types.go
- workflow/controller/controller_test.go
- workflow/controller/exec_control.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
- workflow/progress/updater.go
> fix: Re-factor `assessNodeStatus`. Fixes #7996

- docs/executor_plugins.md
Signed-off-by: NikeNano <niklas.sven.hansson@gmail.com>
Fixes #TODO
> feat: fix path for plugin example

- test/e2e/functional/synchronization-tmpl-level-mutex-semaphore.yaml
- test/e2e/semaphore_test.go
- workflow/sync/sync_manager.go
- workflow/sync/sync_manager_test.go
> fix: panic on synchronization if workflow has mutex and semaphore

- USERS.md
Signed-off-by: descrepes <alexandre.lemao@yubo.live>
We are using Argo Workflows to automate everything.
Thank you for building this project!
> docs: Yubo added to users

- docs/executor_plugins.md
Signed-off-by: NikeNano <niklas.sven.hansson@gmail.com>
https://github.com/argoproj/argo-workflows/blob/b7a525be4014e3bdd28124c8736c25a007049ae7/cmd/argo/commands/executorplugin/io.go#L25
Fixes #TODO
> fix: argo plugins docs refer to plugin.* but should be server.*

- .github/stale.yml
> ci: Do not stale issues labelled mentoring or tech-debt. Fixes #8052

- workflow/controller/exec_control.go
> fix: Stop the workflow if activeDeadlineSeconds has beed patched

- docs/workflow-controller-configmap.yaml
- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
> feat: Expand `mainContainer` config to support all fields. Fixes #7962

- docs/lifecyclehook.md
Fixes #7686. Adds a doc detailing the `LifecycleHook` feature in v3.3.
@sarabala1979 for approval
> docs: Add doc for LifecycleHook feature, Fixes #7686

- workflow/controller/exec_control.go
> fix: e2e TestStopBehavior

- docs/container-set-template.md
> docs: Add note on enhanced depends logic in container set template

- pkg/apis/workflow/v1alpha1/workflow_types.go
- workflow/controller/exec_control.go
> fix: Fix the TestStopBehavior flakiness

- manifests/README.md
Current version is outdated (https://github.com/argoproj/argo-workflows/issues/8068#issuecomment-1058213598).
> docs: update installation docs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/regression.md
- .github/pull_request_template.md
> docs: Update issue/PR templates to reduce problems.

- docs/executor_plugins.md
- docs/plugin-directory.md
- mkdocs.yml
> docs: Start plugin directory

- docs/high-availability.md
- docs/installation.md
- docs/upgrading.md
- manifests/README.md
> docs: Clarify production installation best practices.

- docs/managed-namespace.md
> docs: should this say 'separate?'

- workflow/controller/controller_test.go
- workflow/controller/operator.go
- workflow/controller/pod_cleanup.go
This tech-debt will make it easier to implement clean-up for multi-cluster.
Depended on by #8120
> feat: Change pod clean-up to use informer.

- docs/managed-namespace.md
> docs: clarifying how to do cluster-scope installation

- Dockerfile
Fixes https://github.com/argoproj/argo-workflows/issues/8161
The `argoexec` image should now have a `/etc/mime.types` file. How to test:
```
docker build --target argoexec -t argoexec:fix .
docker run --entrypoint ash --rm argoexec:fix -c "ls -lah /etc/mime.types"
=> -rw-r--r--    1 root     root       68.8K Jan 15  2021 /etc/mime.types
docker run --entrypoint ash --rm argoexec:latest -c "ls -lah /etc/mime.types"
=> ls: /etc/mime.types: No such file or directory
```
> fix: add /etc/mime.types mapping table

- manifests/base/workflow-controller/workflow-controller-deployment.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- test/e2e/manifests/stress/workflow-controller-deployment.yaml
- workflow/controller/config.go
This should mitigate the problem for some users.
See #8124
> feat: Use pinned executor version.

- docs/running-locally.md
> docs: Add docs for run e2e tests locally

- workflow/controller/steps.go
> fix: workflow.duration is not available as a real time metric

- docs/running-locally.md
> docs: fix running-locally.md

- workflow/executor/agent.go
Signed-off-by: maybaby <berlinsaint@126.com>
Fixes [8185](https://github.com/argoproj/argo-workflows/issues/8185)
> fix:  requeue not delete the considererd Task flag

- docs/plugin-directory.md
Signed-off-by: maybaby <berlinsaint@126.com>
Doc Update: add argo volcano job plugin as [8185](https://github.com/argoproj/argo-workflows/issues/8185)
> docs: add argo volcano job plugin

- Makefile
> chore: bump goimports version in Makefile 0.1.6 -> 0.1.7. Fixes #8200

- docs/workflow-executors.md
> docs: Add deprecation notice on K8s API executor

- Makefile
to handle /etc/hosts format with one line per IP address
Fixes #8241
> fix: grep pattern in Makefile

- workflow/controller/hooks.go
- workflow/controller/hooks_test.go
> fix: Hook with wftemplateRef

- workflow/sync/sync_manager.go
> fix: Panic in Workflow Retry

- .github/workflows/dependabot-reviewer.yml
> build: Automated dependabot reviews. Fixes #8255

- .github/governance.yml
- .github/workflows/governance.yml
> build: Enable governance bot. Fixes #8256

- workflow/controller/taskset.go
Signed-off-by: wujayway <wujayway@gmail.com>
Fixes #8245 
Every time controller reconciles the workflowset patch workflow status on workflowset.
> fix: patch workflow status to workflow. Fixes #8245

- manifests/cluster-install/argo-server-rbac/argo-server-clusterolebinding.yaml
- manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrolebinding.yaml
- manifests/install.yaml
Fixes #TODO
Please refer to https://github.com/argoproj/argo-workflows/issues/8250 for more information.
> Remove hardcoded namespace in kustomize file #8250

- ui/package.json
- ui/src/app/shared/pagination.ts
- ui/yarn.lock
> fix: Snyk security recommendations (Node). Fixes #8288

- server/auth/sso/sso.go
> fix: Snyk security recommendations (Golang). Fixes #8288

- sdks/python/sdk_version.py
> chore: Fix Python version on `-dev` branches.

- USERS.md
Adds [Trendyol](https://trendyol.com) to USERS.md
> docs: Trendyol added to USERS.md

- api/openapi-spec/swagger.json
- pkg/apiclient/_.primary.swagger.json
- sdks/java/client/docs/ArtifactServiceApi.md
- sdks/python/client/argo_workflows/api/artifact_service_api.py
- sdks/python/client/docs/ArtifactServiceApi.md
> fix: Fix response type for artifact service OpenAPI and SDKs. Fixes #7781

- manifests/base/crds/full/argoproj.io_workflows.yaml
- manifests/base/crds/minimal/argoproj.io_workflows.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/workflow_types.go
- util/printer/workflow-printer.go
- util/printer/workflow-printer_test.go
> feat: add message column to `kubectl get wf` and `argo list`. Fixes #8307

- examples/README.md
Signed-off-by: Manik Sidana <maniksidana019@gmail.com>
Fixes #8342
> fix: Erratum in docs. Fixes #8342

- server/artifacts/artifact_server.go
> fix: removed error from artifact server 401 response. Fixes #8382

- api/openapi-spec/swagger.json
- pkg/apiclient/_.primary.swagger.json
- sdks/java/client/docs/ArtifactServiceApi.md
- sdks/python/client/argo_workflows/api/artifact_service_api.py
- sdks/python/client/docs/ArtifactServiceApi.md
> fix: replace `podName` with `nodeId` in `_.primary.swagger.json`. Fixes #8384

- ui/src/app/shared/list-watch.ts
- ui/src/app/shared/retry-observable.ts
> fix: Back-off UI retries. Fixes #5697

- hack/docgen.go
- hack/null_docgen.go
nothing but run the `go fmt ./...`
> chore: fmt code

- test/e2e/retry_test.go
- workflow/controller/operator.go
> fix: prevent backoff when retryStrategy.limit has been reached. Fixes #7588

- go.mod
Merges all the `require` blocks into one block to try to reduce merge conflicts.
> chore: Tidy go.mod

- test/e2e/progress_test.go
- test/e2e/testdata/progress-workflow.yaml
> test: Fix `TestLoggedProgress`. Fixes #8411

- .github/workflows/ci-build.yaml
> ci: change CI to run `make lint`

- docs/argo-server-sso.md
- docs/argo-server.md
- docs/container-set-template.md
- docs/cron-workflows.md
- docs/executor_swagger.md
- docs/links.md
- docs/mentoring.md
- docs/releasing.md
- docs/security.md
Update docs md files to fix some spelling mistakes.
Signed-off-by: Jesse Antoszyk <22500761+jcantosz@users.noreply.github.com>
> docs: correct typos in docs

- workflow/controller/workflowpod.go
> fix: Fix bug in entrypoint lookup

- Makefile
Signed-off-by: Clemens Lange <clemens.lange@cern.ch>
Fixes #8450 
I tried this locally on my computer with an M1 processor and the additional binary (and archive) is built correctly when running `make clis`.
> feat: Add darwin-arm64 binary build. Fixes #8450

- test/e2e/pod_cleanup_test.go
- tmp.yml
- workflow/controller/controller_test.go
- workflow/controller/pod_cleanup.go
> fix: PodGC works with WorkflowTemplate. Fixes #8448

- Makefile
- workflow/controller/operator.go
> build: Fail `lint` on woc mis-use.

- manifests/base/workflow-controller/workflow-controller-deployment.yaml
- manifests/base/workflow-controller/workflow-controller-metrics-service.yaml
- manifests/install.yaml
- manifests/namespace-install.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
> fix: Revert controller readiness changes. Fixes #8441

- test/e2e/progress_test.go
This test is still flakey. #8458
> test: Skip `TestLoggedProgress`.

- cmd/argoexec/commands/wait.go
- workflow/executor/emissary/emissary.go
- workflow/executor/executor.go
- workflow/executor/mocks/ContainerRuntimeExecutor.go
> chore: remove `ListContainerNames` and `KillSidecars`. Fixes #8469

- Makefile
- go.mod
- go.sum
- ui/.gitignore
Signed-off-by: mboussarov <miroslav_boussarov@intuit.com>
Fixes #TODO
> build: Updated Makefile to make goreman work

- .github/stale.yml
Fixes https://github.com/argoproj/argo-workflows/issues/8434. We discussed this a bit at today's meeting. Let me know if you have any suggestions. 
cc @alexec @danielhelfand @sarabala1979
> chore: Tweak stale bot configuration and include mentoring label

- Dockerfile
- debug.out
- workflow/controller/container_set_template_test.go
- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
Fixes https://github.com/argoproj/argo-workflows/issues/8376
> feat: add empty dir into wait container

- go.mod
- go.sum
- workflow/artifacts/common/common.go
- workflow/artifacts/gcs/gcs.go
- workflow/artifacts/git/git.go
- workflow/artifacts/hdfs/hdfs.go
- workflow/artifacts/http/http.go
- workflow/artifacts/oss/oss.go
- workflow/artifacts/raw/raw.go
- workflow/artifacts/s3/s3.go
- workflow/artifacts/s3/s3_test.go
> feat: Added a delete function to the artifacts storage. Fixes #8470

- docs/intermediate-inputs.md
- mkdocs.yml
- ui/src/app/shared/services/workflows-service.ts
- ui/src/app/workflows/components/workflow-details/suspend-inputs.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
- workflow/controller/operator.go
- workflow/controller/operator_test.go
Signed-off-by: bjenuhb <Basanth_JenuHB@intuit.com>
Fixes https://github.com/argoproj/argo-workflows/issues/8425
> feat: add capability to choose params in suspend node.Fixes #8425

- docs/intermediate-inputs.md
> docs: Intermediate parameters should be available after v3.4

- server/artifacts/artifact_server.go
- test/e2e/argo_server_test.go
Signed-off-by: mboussarov <miroslav_boussarov@intuit.com>
Fixes #TODO
> feat: Add correct CSP/XFO to served artifacts. Fixing #8492

- workflow/common/common.go
- workflow/controller/operator.go
- workflow/controller/operator_test.go
Signed-off-by: bjenuhb <Basanth_JenuHB@intuit.com>
Fixes https://github.com/argoproj/argo-workflows/issues/8474
> feat: add finalizer for artifact GC

- server/artifacts/artifact_server.go
- server/artifacts/artifact_server_test.go
Signed-off-by: mboussarov <miroslav_boussarov@intuit.com>
Fixes #8514
> feat: Do not return cause of internal server error. Fixes #8514

- pkg/apis/workflow/v1alpha1/workflow_types.go
Signed-off-by: Dillen Padhiar <dpadhiar99@gmail.com>
Quick small typo fix.
> fix: ArtifactGCOnWorkflowDeletion typo quick fix

- pkg/apis/api-rules/violation_exceptions.list
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
Signed-off-by: Dillen Padhiar <dpadhiar99@gmail.com>
Added json tag to `ArtifactGCStrategies` and ran `pre-commit -B`.
> fix: added json tag to ArtifactGCStrategies

- pkg/apis/workflow/v1alpha1/workflow_types_test.go
> fix: unit test for `ArtifactSearchResults`. Fixes #8561

- docs/running-locally.md
Removed superfluous 'how' from sentence in docs
> docs: removed superfluous 'how' from sentence

- server/artifacts/artifact_server.go
> fix: Correct CSP. Fixes #8560

- server/artifacts/artifact_server.go
- test/e2e/argo_server_test.go
It took several commits some of which contained un-related changes, to get this right. I want a single commit containing only the change so I can cherry-pick to release branch. So this PR reverts the changes. And I will then follow with a fix in PR #8585.
> chore: Remove artifact Content-Security-Policy

- workflow/controller/controller.go
Signed-off-by: wujayway <wujayway@gmail.com>
Fixes #8587
> fix: Don't panic on executor plugin event handler. Fixes #8587

- server/apiserver/argoserver.go
- server/artifacts/artifact_server.go
- test/e2e/argo_server_test.go
> fix: Added artifact Content-Security-Policy

- docs/releasing.md
- hack/release-notes.md
- hack/what-to-cherry-pick.sh
> chore: Update releasing guide. Fixes #8595

- examples/README.md
Fixes https://github.com/argoproj/argo-workflows/issues/8601.
> docs: Fix link to examples. Fixes #8601

- README.md
GitHub had some changes and they are now in a column.
> docs: Re-arrange badges to be in one row

- test/e2e/artifacts_test.go
- test/e2e/fixtures/then.go
> test: e2e test support for artifacts updated. Fixes #8521.

- pkg/apiclient/http1/facade.go
> fix: close http body. Fixes #8622

- Makefile
> chore: Upgrade stern to latest. Fixes #8613

- .github/dependabot.yml
Signed-off-by: Derek Wang <whynowy@gmail.com>
Fixes #TODO
> chore: reduce dependencybot frequency

- docs/walk-through/dag.md
> docs: fix broken formatted link

- cmd/argo/commands/client/conn.go
- cmd/argo/commands/cp.go
- cmd/argo/commands/root.go
- docs/cli/argo.md
- docs/cli/argo_cp.md
- mkdocs.yml
- pkg/apis/workflow/v1alpha1/workflow_types.go
- test/e2e/cli_test.go
- test/e2e/testdata/basic-artifact-workflow.yaml
Signed-off-by: mihirpandya-greenops <mihir@greenops.io>
Fixes [#695](https://github.com/argoproj/argo-workflows/issues/695)
Tested feature locally by running workflows with artifacts and copying artifacts to a directory using different flag combinations.
> feat: `argo cp` to download artifacts. Fixes #695

- docs/running-locally.md
Slightly easier to navigate,
instead of googling where's k3d/kind/minikube installation guide
> docs: add installation link to running locally dependencies

- docs/enhanced-depends-logic.md
- workflow/controller/dag.go
- workflow/controller/dag_test.go
> fix: Handle omitted nodes in DAG enhanced depends logic. Fixes #8654

- workflow/artifacts/git/git.go
> fix: Add auth to Git fetch. Fixes #8380

- ui/.npmrc
- ui/package.json
> feat(ui): add node version constraint

- pkg/apis/workflow/v1alpha1/workflow_types.go
- test/e2e/cli_test.go
- workflow/artifacts/raw/raw_test.go
> chore: Fix lint errors

- Makefile
- docs/argo-server-sso.md
- docs/artifact-visualization.md
- docs/cluster-workflow-templates.md
- docs/container-set-template.md
- docs/cost-optimisation.md
- docs/default-workflow-specs.md
- docs/events.md
- docs/high-availability.md
- docs/http-template.md
- docs/installation.md
- docs/rest-api.md
- docs/rest-examples.md
- docs/running-at-massive-scale.md
- docs/running-locally.md
- docs/synchronization.md
- docs/tls.md
- docs/walk-through/custom-template-variable-reference.md
- docs/walk-through/the-structure-of-workflow-specs.md
- docs/walk-through/volumes.md
- docs/widgets.md
- docs/workflow-archive.md
- docs/workflow-of-workflows.md
- docs/workflow-pod-security-context.md
- docs/workflow-templates.md
> docs: address various typos throughout our documentation

- docs/high-availability.md
- docs/synchronization.md
- docs/tls.md
> docs: fixing and clarifying some of our documentation

- .github/dependabot.yml
> feat(ui): Dependabot auto dependency update

- workflow/controller/hooks.go
`Expression 'completed' is always 'false' `.
> fix: Simplify return logic in executeTmplLifeCycleHook

- test/e2e/hooks_test.go
> fix: Temporarily fix CI build. Fixes #8757.

- test/e2e/hooks_test.go
> fix: Skip TestExitHookWithExpression() completely

- workflow/common/ancestry.go
- workflow/common/ancestry_test.go
Fixed issue mentioned in https://github.com/argoproj/argo-workflows/issues/8654#issuecomment-1126737844.
> fix: Omitted task result should also be valid

- USERS.md
Adds Argonaut as a happy Argo Workflows user.
Signed-off-by: Surya Oruganti
> docs: add argonaut to users.md

- ui/package.json
> fix: set NODE_OPTIONS to no-experimental-fetch to prevent yarn start error

- docs/running-locally.md
Added info about node >= 16 being a dependency for running the UI
Fixes #TODO
> docs(running-locally): update dependencies info

- test/e2e/functional_test.go
- workflow/controller/workflowpod.go
> feat: remove size limit of 128kb for workflow templates. Fixes #8789

- .github/dependabot.yml
- ui/package.json
- ui/yarn.lock
This was causing issue earlier and reverted. Also added this to ignore.
Reverts argoproj/argo-workflows#8820
> Revert "chore(deps-dev): bump style-loader from 0.20.3 to 2.0.0 in /ui"

- .github/workflows/ci-build.yaml
- ui/package.json
- ui/src/app/archived-workflows/components/archived-workflow-filters/archived-workflow-filters.tsx
- ui/src/app/reports/components/reports.tsx
- ui/src/app/shared/use-query-params.ts
- ui/src/app/webpack.config.js
Changes:
* Fix `yarn start`.
* Fixed some warnings.
* Add basic CI test.
> chore: Fix `yarn start`

- USERS.md
> add pismo.io to argo users

- cmd/argo/commands/common/get.go
- cmd/argo/commands/common/get_test.go
- util/printer/workflow-printer.go
- util/printer/workflow-printer_test.go
Signed-off-by: TheSwarnim <swarnimpratap132@gmail.com>
Fixes #8713
I've removed the function [PrintSecurityNudges ](https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/util/printer/workflow-printer.go#L117) and all its invocations from the codebase.
The invocations are located at:
- https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/cmd/argo/commands/common/get.go#L167
- https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/cmd/argo/commands/common/get.go#L167
In the second invocations, basically, it's the test function for the `PrintSecurityNudges` function. Since the test case is of no use if the original function is removed. So I deleted the whole function.
To make sure that …
> Removed Security Nudge and all its invocations

- .github/ISSUE_TEMPLATE/config.yml
Signed-off-by: “[Kevin George<“kevingeorge232@gmail.com”>
Fixes  #8868
> docs: Remove 30m to talk anything Argo #8868

- Makefile
This enables you to call "make start GCFLAGS='all=-N -l'" to enable the code to be built with optimization turned off, meaning you can debug your application with "dlv attach <pid>" and get values for all of the variables.
> feat: enable gcflags (compiler flags) to be passed into 'go build'

- api/openapi-spec/swagger.json
- pkg/apiclient/_.primary.swagger.json
- sdks/java/client/docs/ArtifactServiceApi.md
- sdks/python/client/argo_workflows/api/artifact_service_api.py
- sdks/python/client/docs/ArtifactServiceApi.md
fix: fix swagger error. Fixes #8830 #8859
> fix: Fixed Swagger error. Fixes #8830

- ui/src/app/workflows/components/submit-workflow-panel.tsx
> Add left-margin to the question circle next to parameter name in Submit Workflow Panel

- workflow/controller/controller.go
> fix: Only signal running containers, ignore failures.

- mkdocs.yml
> docs: Add link to Argo LinkedIn page

- docs/upgrading.md
- persist/sqldb/migrate.go
Fixes #8836.
This PR addes indexes. This may cause performance degradation during migrate if a large number of archived workflows are in the table. You may want to add this as a note in the release note.
> feat: add indexes for improve archived workflow performance. Fixes #8836

- docs/walk-through/continuous-integration-examples.md
- examples/ci-workflowtemplate.yaml
Fixes #8813, related to #8944 
Users have been requesting CI examples in the community, so I added another update to this doc.
> docs: Add more CI examples to CI doc, fixes #8813

- OWNERS
https://github.com/argoproj/argoproj/issues/137
> docs: add @tczhao as reviewer

- .github/dependabot.yml
- ui/package.json
- ui/yarn.lock
Similar to https://github.com/argoproj/argo-workflows/pull/8839
---
Reverts #9034 
Added raw-loader to depbot ignore
Fixes #9040
> Revert "chore(deps-dev): bump raw-loader from 0.5.1 to 4.0.2 in /ui (#9034)"

- docs/workflow-rbac.md
Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>
> docs: fix typo in workflow-rbac.md

- manifests/namespace-install.yaml
- manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml
- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
> chore: Remove redundant service account RBAC in manifests

- docs/http-template.md
The `request.body` and `request.headers` refer to the request body and request headers respectively.
> docs: http response -> request

- ui/src/app/workflows/components/workflow-creator-info/workflow-creator-info.scss
- ui/src/app/workflows/components/workflow-creator-info/workflow-creator-info.tsx
- ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx
- ui/src/app/workflows/components/workflow-summary-panel.tsx
- ui/src/models/workflows.ts
> feat(ui): Add workflow author information to workflow summary and drawer

- docs/workflow-creator.md
> docs: Add preferred username to creator labels

- server/artifacts/artifact_server.go
- server/artifacts/artifact_server_test.go
Co-authored-by: Joaquín Martín <joaquinmnsm@gmail.com>
Co-authored-by: Francisco Baron <baronizquierdo@gmail.com>
On-behalf-of: @clarityai-eng <tech@clarity.ai>
Signed-off-by: Ivan Sanchez <sanfru.ivan@gmail.com>
Fixes #8746
> fix: Do not error when getting log artifacts from GCS. Fixes #8746

- docs/mentoring.md
> docs: Change the branch of cncf/foundation from master to main

- USERS.md
Hi, VP R&D of Reco here. We <3 Argo Workflows and use is extensively internally :)
Fixes #9181 - https://github.com/argoproj/argo-workflows/issues/9181
> Update USERS.md with Reco

- sdks/java/README.md
Fixes https://github.com/argoproj/argo-workflows/discussions/9194.
> docs: Fix link to GitHub Packages registry instructions

- .devcontainer/startup.sh
From
```
127.0.0.1 dex\n127.0.0.1 minio\n127.0.0.1 postgres\n127.0.0.1 mysql\n127.0.0.1 azurite
```
To
```
127.0.0.1 dex
127.0.0.1 minio
127.0.0.1 postgres
127.0.0.1 mysql
127.0.0.1 azurite
```
This approach is doesn't rely on echo version
https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html
> fix: line return in devcontainer host file 

- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Seems there's no response from the original author, thus picking it up
Fixes #8648
> ui: remove workflowlist searchbox

- .github/workflows/ci-build.yaml
- .golangci.yml
- Makefile
- test/e2e/functional_test.go
> chore: Imporve the unit test and e2e time

- sdks/java/README.md
> docs: correct jar version

- workflow/artifacts/s3/errors.go
Signed-off-by: Dana Pieluszczak <danajp@users.noreply.github.com>
Fixes #9248
> fix: add ServiceUnavailable to s3 transient errors list Fixes #9248

- ui/src/app/shared/utils.ts
Signed-off-by: Loric ANDRE <loric.a@padoa-group.com>
Fixes https://github.com/argoproj/argo-workflows/issues/9266
> Fix: user namespace override (Fixes #9266)

- USERS.md
- sdks/python/README.md
Signed-off-by: Deepyaman Datta <deepyaman.datta@utexas.edu>
Fixes syntax error in the README example, and replaces instance of using backslash for line continuation (not recommended by PEP-8, not used by Black, etc.) to be consistent with the updates.
> docs: fix formatting in Python SDK Getting Started

- docs/use-cases/webhdfs.md
> docs: fix broken links to Apache HDFS

- examples/ci.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1QH8CGaLUqKyZ42rGz2BPFF43McuEz8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=I8GOtyA)
Fixes #TODO
> docs: Update ci.yaml

- ui/src/app/shared/conditions-panel.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/9371.
> fix: Fix blank workflow details page after workflow submission

- ui/src/app/shared/components/graph/graph-panel.scss
- ui/src/app/shared/components/graph/icon.tsx
> fix(ui): Correctly show icons in DAG. Fixes #9372 & #9373

- USERS.md
Signed-off-by: Savin <savingoyal@gmail.com>
Fixes #TODO
> docs: Add Metaflow to USERS

- ui/src/app/workflows/components/workflow-details/artifact-panel.tsx
Fixes #9391. Screenshot after the fix:
> fix: Artifact panel crashes when viewing artifacts. Fixes #9391

- workflow/controller/operator.go
> fix: Invalid memory address or nil pointer dereference

- cmd/argo/commands/common/wait.go
- workflow/controller/controller.go
> fix: Argo waiter: invalid memory address or nil pointer dereference 

- docs/walk-through/daemon-containers.md
add influxdb's container cmd 
Signed-off-by: lkad <eloony@163.com>
Fixes #command is needed for V3.3.5 and later
> docs: command is needed for V3.3.5 and later

- docs/running-locally.md
Signed-off-by: Tim Collins <tim@thecollins.team>
> Docs: V minor typo fix - Running Locally

- docs/http-template.md
Signed-off-by: Tim Collins <tim@thecollins.team>
Fixes #9195
> docs: Explain RBAC requirements for http template. Fixes #9195

- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- docs/fields.md
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- sdks/java/client/docs/IoArgoprojWorkflowV1alpha1WorkflowSpec.md
- sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_workflow_spec.py
- sdks/python/client/docs/IoArgoprojWorkflowV1alpha1WorkflowSpec.md
Fixes #8762
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
> docs: Deprecate PodPriority field in WorkflowSpec (Fixes #8762)

- workflow/validate/validate.go
> fix: Only validate manifests for certain resource actions. Fixes #9418

- workflow/util/util.go
- workflow/util/util_test.go
Only remove the descendants of a suspended node but not the suspended node itself. The descendants of a suspended node need to be removed since because the conditions should be re-evaluated based on the modified supplied parameter values.
> fix: Descendants of suspended nodes need to be removed when retrying workflow

- docs/plugin-directory.md
Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>
add Chaos Mesh Plugin
> docs: add Chaos Mesh Plugin

- docs/walk-through/output-parameters.md
Signed-off-by: kasteph <hello@stephsamson.com>
Fixes  #8921
> docs: add section on `outputs.result`

- workflow/artifacts/gcs/gcs.go
> feat: added support for artifact GC on GCS

- server/artifacts/artifact_server.go
Apparently Issue 9434 is still seeing the "artifact not found" error even when running with POD_NAMES v1. Want to put [this](https://github.com/argoproj/argo-workflows/commit/26ab0aed8ba19571ffe3a2b048fcb43cbd1986e3) UI fix into RC3 along with this more verbose logging, so if the error is still happening we'll have more information about the Workflow Status.
> chore: more verbose logging to uncover more info for Issue 9434

- workflow/controller/controller_test.go
- workflow/controller/operator_test.go
- workflow/controller/workflowpod.go
- workflow/controller/workflowpod_test.go
adds --log-format and --loglevel flags to "argoexec emissary" for
consistent logging output.
related to: #8986 #9169 #7361
> feat: log format option for main containers

- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Fixes #9491 
In [this](https://github.com/argoproj/argo-workflows/commit/26ab0aed8ba19571ffe3a2b048fcb43cbd1986e3) PR there was an accidental change that I thought was just the linter reformatting things, but it seems there was an accidental "real" change made in there I didn't notice.
> fix: revert accidental commit in UI logs viewer

- .github/ISSUE_TEMPLATE/bug_report.md
Signed-off-by: Alex Collins <alexec@users.noreply.github.com>
> chore: Remove `triage` label.

- cmd/argoexec/commands/emissary_test.go
- test/e2e/signals_test.go
- test/e2e/testdata/signaled-workflow.yaml
- workflow/executor/os-specific/signal_darwin.go
> fix: Capture exit code of signaled containers. Fixes #9415

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/regression.md
The goal of this PR is to:
* Reduce the number of bug/regression reports by getting users to see if their bug has been fixed in the latest version
* Improve the quality of the reports by adding the check list.
* Align the regression and bug report templates.
> docs: Update bug/regression templates to reduce/improve reports

- docs/cron-workflows.md
Signed-off-by: Tim Collins <tim@thecollins.team>
Fixes #TODO
> docs: Define cron syntax. Fixes #9493

- manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml
Signed-off-by: Takao Shibata <chise.alter.pasta@gmail.com>
Fixes #9545
> fix: enable workflow-aggregate-roles to treat workflowtaskresults. Fixes #9545

- .spelling
- docs/configure-artifact-repository.md
- docs/upgrading.md
> docs: new S3 access requirements as of v3.4

- docs/argo-server-sso-argocd.md
fix doc
Signed-off-by: 66li <37136076+66li@users.noreply.github.com>
Fixes #TODO
> docs: Update argo-server-sso-argocd.md

- workflow/cron/operator.go
> fix: Error message if cronworkflow failed to update

- docs/configure-artifact-repository.md
Signed-off-by: Brian Loss <brianloss@gmail.com>
Fixes #9595
> docs: Update default artifact repository docs to describe process for Azure Blob Storage. Fixes #9595

- .github/ISSUE_TEMPLATE/bug_report.yaml
> docs: Fixes issues with bug report template

- .github/workflows/ci-build.yaml
- docs/fields.md
- examples/data-transformations.yaml
- hack/test-examples.sh
> ci: Auto-retry e2e tests

- USERS.md
Adding Elastic as a User to Argo Workflow
Signed-off-by: Christopher Cutajar <60098546+christophercutajar@users.noreply.github.com>
> docs: Adding Elastic as a User

- docs/fields.md
- examples/loops-arbitrary-sequential-steps.yaml
> docs: add loop-arbitrary-sequential-steps example. Fixes 8081

- server/apiserver/argoserver.go
> fix: add authorization from cookie to metadata

- workflow/controller/dag.go
- workflow/controller/operator_concurrency_test.go
> fix: render template vars in DAGTask before releasing lock.. Fixes #9395

- USERS.md
Signed-off-by: emagana <112656855+emagana@users.noreply.github.com>
Fixes #TODO
> Adding Splunk as Argo Workflows User

- USERS.md
docs: Add Datable to USERS.md
Signed-off-by: kyaukyuai <y.kakui@gmail.com>
> docs: Add Datable to USERS.md

- workflow/validate/validate.go
- workflow/validate/validate_test.go
Without this change we get error:
`Recovered from panic: runtime error: invalid memory address or nil pointer dereference`
Signed-off-by: Ricardo Rosales <728243+missingcharacter@users.noreply.github.com>
> fix: `value` is required when parameter is of type `enum`

- USERS.md
As we are heavily using the argo ecosystem for the management of our OpenShift Clusters and applications as well as implementing our CICD solutions we would like to reflect that on the users list :)
> docs: add Gepardec to users

- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- manifests/quick-start/base/httpbin/httpbin-deploy.yaml
> fix: quick-start-* manifests pointing to invalid httpbin image tag. Fixes #9659

- .github/pull_request_template.md
Signed-off-by: Alex Collins <alexec@users.noreply.github.com>
Fixes #TODO
> docs: update PR template to improve PR quality

- ui/src/app/modals/new-version/new-version-modal.tsx
v3.4 is released, we should update the UI version info brief as well
> feat(ui): add v3.4 feature info

- cmd/argoexec/commands/agent.go
- docs/executor_swagger.md
- pkg/plugins/executor/objectmeta.go
- pkg/plugins/executor/swagger.yml
- workflow/common/common.go
- workflow/controller/agent.go
- workflow/executor/agent.go
> fix: Send workflow UID to plugins. Fixes #8573

- ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
> fix(ui): missing url href formatting in template link. Fixes #9764

- ui/src/app/shared/components/links.tsx
> fix: fixed url encoded link template

- README.md
Part of #9769 
Signed-off-by: Eddie Knight <iv.eddieknight@gmail.com>
> chore: Added Artifact Hub badge to readme

- .github/workflows/sdks.yaml
> fix: SDK CI workflow

- .devcontainer/devcontainer.json
Fixes #9830 
See https://containers.dev/implementors/json_reference/#lifecycle-scripts
> fix: trigger startup.sh at devcontainer startup instead of create

- workflow/controller/controller.go
> fix: Mutex is not initialized when controller restart

- .spelling
- docs/quick-start.md
- docs/training.md
Signed-off-by: Tim Collins <tim@thecollins.team>
> docs: Reference new Killercoda course

- ui/src/app/cluster-workflow-templates/components/cluster-workflow-template-list/cluster-workflow-template-list.tsx
Tested with UI
- loading cluster wf template
- no cluster wf template
- exist cluster wf template
---
> refactor: ui, convert cluster workflow template to functional component

- ui/src/app/shared/components/links.test.ts
- ui/src/app/shared/components/links.tsx
> fix(ui): Apply url encode and decode to a `ProcessURL`. Fixes #9791

- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
> fix: show pending workflows in workflow list Fixes #9812

- cmd/argo/commands/cron/resume.go
Signed-off-by: Pedro López Mareque <Pedro.lopez.mareque@gmail.com>
Fixes #9955
> docs: fix typo in the NewResumeCommand documentation

- OWNERS
See https://github.com/argoproj/argoproj/pull/170. 
Congrats! @juliev0 🎉 
> chore: Update reviewers

- README.md
> docs: Add links to use cases

- docs/configure-artifact-repository.md
Signed-off-by: Arjun Gopisetty <arjun.gopisetty@gmail.com>
I found a few typos in the IAM policy JSON used for configuring a S3 bucket as an artifact repository.
> docs: correct s3 iam policy json

- workflow/util/util.go
- workflow/util/util_test.go
> Fixes #10003: retry handler even if it succeded

- ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx
> fix(ui): search artifact by uid in archived wf. Fixes #9968

- docs/configure-artifact-repository.md
- docs/walk-through/artifacts.md
artifact delete is implemented through artifact driver not explicitly s3
https://github.com/argoproj/argo-workflows/blob/master/cmd/argoexec/commands/artifact/delete.go#L80-L85
https://github.com/argoproj/argo-workflows/blob/master/workflow/artifacts/artifacts.go
> docs: artifact gc also supports other drivers

- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- docs/executor_swagger.md
- docs/fields.md
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/plugins/executor/swagger.yml
- sdks/java/client/docs/IoArgoprojWorkflowV1alpha1SuspendTemplate.md
- sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_suspend_template.py
- sdks/python/client/docs/IoArgoprojWorkflowV1alpha1SuspendTemplate.md
> docs: Clarify SuspendTemplate.duration.

- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
Signed-off-by: fsiegmund <siegmund@slb.com>
Fixes #10051
> fix(ui): use podname for EventPanel name param (#10051)

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/regression.yaml
I noted that the YAML in the issue was in a fenced block, but neither logs were. 
> docs: Update issue templates so logs are code-fenced

- .spelling
- docs/kubectl.md
> chore: remove the unnecessary symbol from a title

- workflow/artifacts/s3/s3.go
Fixes #10083
I'm extremely surprised no one has raised a bug about this before. Makes me suspicious.
> fix: Correct behaviour of `CreateBucketIfNotPresent`. Fixes #10083

- server/auth/sso/sso.go
Signed-off-by: neo502721 <zgmhdu@163.com>
Fixes #10089 
> fix: SSO insecureSkipVerify not work. Fixes #10089

- ui/src/app/shared/annotations.ts
- ui/src/app/shared/services/workflows-service.ts
- ui/src/app/workflows/components/workflows-row/workflows-row.tsx
Fixes #6529 (partially, no markdown)
TL;DR
Add the following to your workflow annotations to get a title/description to show on the workflow list page:
```yaml
spec:
annotations:
workflows.argoproj.io/title: 'this is a title'
workflows.argoproj.io/description: 'this is a description'
```
Signed-off-by: jmeridth <jmeridth@gmail.com>
Fixes #TODO
> feat: Workflow title/description in workflow list view. Fixes #6529

- cmd/argo/commands/common/get.go
> fix: Support other output artifact types in argo get

- ui/src/app/shared/components/error-notice.tsx
Signed-off-by: Mayursinh Sarvaiya <marvinduff97@gmail.com>
Fixes #9274 
> fix: error component showing inaccurate errors. Fixes #9274

- Dockerfile
- test/e2e/resource_template_test.go
- test/e2e/testdata/resource-templates/outputs.yaml
- workflow/executor/resource.go
> fix: Make `jq` work. Fixes #9860

- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- docs/executor_swagger.md
- docs/fields.md
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/plugins/executor/swagger.yml
- sdks/java/client/docs/IoArgoprojWorkflowV1alpha1Template.md
- sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_template.py
- sdks/python/client/docs/IoArgoprojWorkflowV1alpha1Template.md
- ui/src/models/workflows.ts
Signed-off-by: John Lin <johnlinp@gmail.com>
> docs: fix typo of the word "daemon"

- config/controller.go
- workflow/controller/controller.go
- workflow/controller/controller_test.go
> fix: Auto update workflow controller configmap

- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
> fix: ensure metadata is not undefined when accessing label. Fixes #10227

- USERS.md
Add cloud scale
Signed-off-by: Nandita <105474264+nandita-cloudscaleinc@users.noreply.github.com>
Fixes #TODO
> docs: add CloudScale to user list

- workflow/common/common.go
Signed-off-by: huiwq1990 <huiwq1990@163.com>
Just cleanup unused code.
> feat: cleanup code

- manifests/quick-start-minimal.yaml
- manifests/quick-start-mysql.yaml
- manifests/quick-start-postgres.yaml
- manifests/quick-start/base/minio/minio-deploy.yaml
Signed-off-by: Julie Vogelmani <julie_vogelman@intuit.com>
Fixes #10310
> fix: fix minio image at older working version

- USERS.md
Signed-off-by: Sreejith Kesavan <86766485+sreejithtessell@users.noreply.github.com>
Fixes #TODO
> docs: Add Tessell as an organisation using Argo Workflows

- go.mod
- go.sum
> chore: bump argoproj-labs/go-git to v5.4.6. Fixes #10225

- docs/plugin-directory.md
> docs: submit a argo workflow executor plugin

- USERS.md
Signed-off-by: Junaid Rahim <junaidrahim8d@gmail.com>
Fixes #TODO
> docs: add Atlan as an org using argo workflows

- workflow/executor/executor.go
the current implementation is actually:
1. try to upsert TaskResult
2. if step(1) fails, we will try to update the Pod's annotations
Fixes: null
> fix(executor):  make the comment of reportOutputs clearer

- server/event/dispatch/operation.go
- server/event/dispatch/operation_test.go
> feat: support set generateName in the eventbinding

- docs/plugin-directory.md
> docs: submit a workflow plugin: atomic

- docs/releases.md
Signed-off-by: huiwq1990 <huiwq1990@163.com>
Fixes https://github.com/argoproj/argo-workflows/issues/8198
> docs: add kubernetes compatibilit

- server/clusterworkflowtemplate/cluster_workflow_template_server.go
- server/cronworkflow/cron_workflow_server.go
- server/event/dispatch/operation.go
- server/event/event_server.go
- server/event/event_server_test.go
- server/eventsource/event_source_server.go
- server/sensor/sensor_server.go
- server/utils/errors.go
- server/utils/errors_test.go
- server/workflow/workflow_server.go
- server/workflow/workflow_server_test.go
- server/workflowarchive/archived_workflow_server.go
- server/workflowtemplate/workflow_template_server.go
> fix: Return correct http error codes. Fixes #9237

- docs/CONTRIBUTING.md
Signed-off-by: Caelan U
Somehow our community meeting info got lost in our docs, so adding it back in since folks were asking me about where to find the Google Doc and Zoom link.
> docs: Add monthly community meeting info

- docs/enhanced-depends-logic.md
> docs: fix typo in enhanced-depends-logic.md

- docs/container-set-template.md
no such file or directory appears when run the container-set-template in the example.
Fixes: 
When I tried to run the [container-set-template-](https://github.com/argoproj/argo-workflows/blob/49647896e1db3bf36ea3aa879a77c7756d648190/docs/container-set-template.md) workflow in the sample, I encountered the following error (and it can be reproduced).
```bash
Name:                container-set-template-qkrbz
Status:              Error
Message:             Error (exit code 1): open /mainctrfs/workspace/message: no such file or directory
Conditions:
PodRunning          False
Completed           True
Created:             Thu Feb 02 17:59:42 +0800 (3 …
```
> fix(docs): container-set-template workflow example

- OWNERS
See https://github.com/argoproj/argoproj/pull/190.
> docs: Update OWNERS from membership meeting

- workflow/common/util.go
- workflow/common/util_test.go
Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>
> chore: remove deadcode in workflow/common

- Dockerfile
- Dockerfile.windows
- docs/running-locally.md
- go.mod
- go.sum
- workflow/executor/resource.go
- workflow/executor/resource_test.go
Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>
related #7799
itchyny/gojq is well maintenanced and widely used. https://pkg.go.dev/github.com/itchyny/gojq?tab=importedby
argo-cd and argo-events already use gojq.
TestResourceTemplateWithOutputs seems fine.
> feat: replace jq with gojq

- pkg/apiclient/offline-client.go
- pkg/apiclient/offline-cron-workflow-service-client.go
- test/e2e/fixtures/then.go
- workflow/controller/artifact_gc.go
> chore: fix duplicated imports

- cmd/argo/commands/submit.go
- cmd/argo/commands/submit_test.go
> fix: Priority don't work in workflow spec. Fixes #10374

- ui/package.json
- ui/yarn.lock
Reverts argoproj/argo-workflows#10547
> Revert "chore(deps): bump react-router-dom and @types/react-router-dom in /ui"

- README.md
* Also put list in alphabetical order
Fixes #10604
> Add Hera to Ecosystem list, Fixes #10604

- USERS.md
> docs: add Tuhu to users

- docs/fields.md
- examples/http-success-condition.yaml
This PR fixes the broken master build by disabling a test that just repeats a E2E test (albeit named differently and using different file).
Once required tests have passed, mark your PR "Ready for review".
If changes were requested, please address the feedback and then dismiss the review to get it reviewed again.
> test: Disable broken unneeded test

- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
> fix(ui): reword Workflow `DELETED` error

- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- workflow/controller/exec_control.go
> fix: ensure children containers are killed for container sets. Fixes #10491

- Dockerfile
- config/config.go
- persist/sqldb/sqldb.go
Closes https://github.com/argoproj/argo-workflows/issues/10731.
Reverts argoproj/argo-workflows#10300. Argo server and controller cannot start with Postgres setup.
> Revert "Fixes #10234 - Postgres SSL Certificate fix"

- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix: Workflow stuck at running when init container failed but wait container did not. Fixes #10717

- USERS.md
Add Karrot to user of this project
> docs: Add Karrot to users

- USERS.md
As we are heavily using the argo ecosystem for the management of our workflows, we would like to reflect that on the users list :)
> docs: Add Salesforce to USERS.md

- USERS.md
Add Phrase to the list of companies that use Argo.
> docs: Add Phrase to USERS.md

- workflow/templateresolution/context.go
- workflow/templateresolution/context_test.go
> docs: Improve docs in context.go

- test/e2e/hooks_test.go
- workflow/controller/hooks.go
- workflow/controller/operator.go
> fix: make workflow status change after workflow level lifecycle hooks complete. Fixes #10743, #9591

- .github/workflows/ci-build.yaml
> ci: Pin K3s to v1.26.3+k3s1. Fixes #10869

- test/e2e/hooks_test.go
- workflow/controller/dag.go
> fix: Fix not working Running state lifecycle hooks in dag task. Fixes #9897

- ui/src/app/app.tsx
- ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
Change app.tsx to functional component.
Tested on UI, specifically those methods that got removed.
Fixes #9810
> chore: refactor app.tsx. Fixes #9810

- docs/walk-through/artifacts.md
Explain the new forceFinalizerRemoval flag in the Artifact GC docs
> docs: forceFinalizerRemoval

- workflow/controller/controller_test.go
- workflow/controller/healthz.go
- workflow/controller/operator.go
> fix: Validate label values from workflowMetadata to avoid controller crash. Fixes #10872

- ui/src/app/shared/services/archived-workflows-service.ts
- ui/src/app/shared/services/cluster-workflow-template-service.ts
- ui/src/app/shared/services/cron-workflow-service.ts
- ui/src/app/shared/services/event-service.ts
- ui/src/app/shared/services/event-source-service.ts
- ui/src/app/shared/services/index.ts
- ui/src/app/shared/services/info-service.ts
- ui/src/app/shared/services/sensor-service.ts
- ui/src/app/shared/services/workflow-service.test.ts
- ui/src/app/shared/services/workflow-template-service.ts
- ui/src/app/shared/services/workflows-service.ts
- ui/src/models/workflows.ts
Also tested on UI especially on workflow page, e.g. clicking button and getting log
Partially Fixes https://github.com/argoproj/argo-workflows/issues/9810
> chore: refactor ui share service.

- docs/key-only-artifacts.md
- This fixes a small typo, instead of specific changing it to specify.
- No testing was required for this
> docs: Fixing small typo

- pkg/apis/workflow/v1alpha1/workflow_types.go
- workflow/util/pod_name.go
- workflow/util/pod_name_v2_test.go
> fix: Incorrect pod name for inline templates. Fixes #10912

- docs/argo-server-sso-argocd.md
- docs/argo-server-sso.md
- Purpose
- Clarify some notes on SSO and SSO RBAC.
> docs: note on  SA's secrets for SSO RBAC

- docs/lifecyclehook.md
> docs: provide an explanation for the lifecycle hook

- workflow/controller/operator.go
- workflow/controller/operator_test.go
> fix: Check AlreadyExists error when creating PDB. Fixes #10942

- USERS.md
Update Argo Workflow user list.
> docs(users): add StreamNative to the list of users

- workflow/artifacts/oss/oss.go
- workflow/artifacts/s3/s3.go
- workflow/common/util.go
- workflow/controller/workflowpod.go
- workflow/executor/common/common.go
TODO: Say why you made your changes.
TODO: Say what changes you made.
TODO: Say how you tested your changes.
TODO: Attach screenshots if you changed the UI.
Fixes  some comments
> chore: fix some comments

- USERS.md
Add Procore to the list of companies that use Argo Workflows.
> docs(users): Add Procore to USERS.md

- workflow/controller/workflowpod_test.go
https://github.com/argoproj/argo-workflows/issues/10807#issuecomment-1538975454 
Example failed test: https://github.com/argoproj/argo-workflows/actions/runs/4918943572/jobs/8785931921
> chore: Fix flaky test in workflowpod_test.go

- docs/workflow-archive.md
Archived workflows not deleted from DB at startup. Describe how archiveGC and archiveTTL parameters work. #10904
Some aspects of workflow archiving need more details in the docu
Added description for archiveGC and archiveTTL parameters 
MD preview looks correct 
Fixes #10904
> docs: archiveGC and archiveTTL parameters #10904

- test/e2e/functional_test.go
Part of https://github.com/argoproj/argo-workflows/issues/10807
> chore: Fix flaky test in functional_test.go

- README.md
Some improvements and removed redundant sections.
> docs: Refresh README.md

- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
> fix: UI crashes when retrying a containerSet workflow. Fixes #11061

- api/jsonschema/schema.json
- api/openapi-spec/swagger.json
- docs/executor_swagger.md
- docs/fields.md
- pkg/apis/workflow/v1alpha1/generated.proto
- pkg/apis/workflow/v1alpha1/openapi_generated.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/plugins/executor/swagger.yml
- sdks/java/client/docs/IoArgoprojWorkflowV1alpha1Backoff.md
- sdks/python/client/argo_workflows/model/io_argoproj_workflow_v1alpha1_backoff.py
- sdks/python/client/docs/IoArgoprojWorkflowV1alpha1Backoff.md
Fixes #10368
Update the Documentation of MaxDuration in the backoff strategy to make it more clear.
> docs: update MaxDuration docs. Fixes 10368

- docs/fields.md
- hack/docgen.go
Fixes #TODO
I found some tildes while reading [field reference](https://argoproj.github.io/argo-workflows/fields/) and thought it's typo of strikethrough.
> docs: fix markdown formatting

- workflow/controller/operator.go
We saw this panic on our cluster - want to add more information to the panic to help with debugging.
> chore: more info for debugging panic

- docs/releases.md
Per discussions in today's contributors meeting.
> docs: Adjust release schedule for minor releases

- docs/scaling.md
Mention the hot-standby and just link to the HA docs for more details
- addresses https://github.com/argoproj/argo-workflows/issues/7623#issuecomment-1205888128
- this is not horizontal scaling per se, but it is closely related as it requires running 2 replicas
- the missing mention here was confusing to me, my teams, and other Argo users (per https://github.com/argoproj/argo-workflows/issues/7623#issuecomment-1205888128, if not more)
- Just add one tiny sentence under horizontal scaling with a link to the HA docs
n/a
> docs: mention the hot-standby under horizontal scaling

- USERS.md
Add Adyen as user of Argo Workflows
Company name to the USERS.md file
N/A
> docs: add Adyen to user

- Makefile
Example: https://github.com/argoproj/argo-workflows/actions/runs/5486613895/jobs/9996937003
> ci: Disable flaky link check

- docs/fields.md
https://github.com/argoproj/argo-workflows/actions/runs/5487616567/jobs/10000061450
> ci: Fix broken codgen build

- ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
- ui/src/models/workflows.ts
> feat: Support batch deletion of archived workflows. Fixes #11324

- .github/workflows/gh-pages.yaml
Looks like env var are not effective.
> ci: Switch to use “with” in gh-pages.yaml 

- USERS.md
We recently learned how to spell the name of our company and we're just showing off.
(Fixes a typo in users.md)
> chore: correct spelling of Pipekit in users.md

- .devcontainer/pre-build.sh
For dev/test parity
- https://github.com/argoproj/argo-workflows/pull/11267 updated CI to 1.27
- update devcontainer `k3d` to use `k3s` 1.27
- found https://github.com/k3d-io/k3d/issues/92#issuecomment-1606249994 to specify the version
- update devcontainer `kubectl` to use 1.27
Ran updated commands in my own devcontainer.
```
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (build-k8s-127) $ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", …
```
> build: use k8s 1.27 in devcontainer to match CI

- docs/work-avoidance.md
Complete my sentence from PR #11257
> docs: Finish describing memoization

- test/e2e/cli_test.go
Fixes flaky test mentioned in https://github.com/argoproj/argo-workflows/issues/10807#issuecomment-1636659294
> test: Fix flaky TestLogProblems

- Makefile
- docs/README.md
https://argoproj.github.io/argo-workflows/ is super outdated and does not contain much information. It should be the same as the root level README. Ideally we should use the root level README but I am not sure if it works  with mkdocs when working outside of `docs` folder: https://github.com/argoproj/argo-workflows/blob/master/mkdocs.yml#L37
> docs: Update README.md for home page

- .spelling
- docs/client-libraries.md
Per our discussion in contributors meeting.
> docs: Set expectations for auto-generated client libraries

- README.md
Signed-off-by: Gosha <gosha@rookout.com>
Fixes #TODO
> docs: add piper to ecosystem

- examples/pod-gc-strategy-with-label-selector.yaml
- examples/pod-gc-strategy.yaml
- as the docs currently get released immediately, some users think this feature (that I implemented in #11325) is already available, but it actually hasn't been released yet
- Fixes #11412
- Related to #11390 (the case of future / unreleased docs, as opposed to past docs)
- add a comment in the `podGC` examples that specifies it requires Argo >=3.5
- similar to the comments in [`docs/workflow-controller-configmap.yaml`](https://github.com/argoproj/argo-workflows/blob/34ffc875c3a165580e02cbfa0df2cc8da30d74a0/docs/workflow-controller-configmap.yaml#L26)
n/a
> docs(podGC): specify that `deleteDelayDuration` requires >=3.5

- ui/src/app/workflows/components/workflows-list/workflows-list.scss
- ui/src/app/workflows/components/workflows-list/workflows-list.tsx
- ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.scss
Fixes #11442 
The `position:sticky` in the workflows-toolbar is not working.
For a better UX, we changed the workflows-toolbar component from not being position sticky to being able to see the toolbar after scrolling.
- before
- after
> fix: UI toolbar sticky

- docs/workflow-controller-configmap.yaml
- to make sure that users know this is not yet available (see also https://github.com/argoproj/argo-workflows/pull/10808#issuecomment-1622972793)
- #10808 will be released with the next minor release, which is v3.5
basically similar to my own #11445 applying to my own #11297
- I think I made the PR before the comments on #10808 mentioning that it isn't yet available. I hadn't realized it wasn't released yet since the PR is 3 months old already. Mentioned this feature [on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1690473310462639?thread_ts=1690464409.545419&cid=C01QW9QSSSK) yesterday and then saw the comment 😅 
- add a comment to `docs/workflow-controller-configmap.yaml` to specify the version requirement for `columns`
- consistent with the other version comments in this …
> docs: specify that custom `columns` requires >=3.5

- cmd/argoexec/commands/emissary.go
> fix: Ignore failed read of exit code. Fixes #11490

- test/e2e/workflow_inputs_orverridable_test.go
- workflow/common/configmap.go
- workflow/common/util.go
- workflow/common/util_test.go
- workflow/controller/dag.go
- workflow/controller/operator.go
- workflow/controller/workflowpod.go
Fixes [#10182 
](https://github.com/argoproj/argo-workflows/issues/10182)
> fix: valueFrom in template parameter should be overridable. Fixes 10182

- OWNERS
https://github.com/argoproj/argoproj/issues/208
Thanks @alexec for all your hard work as the lead!
> docs: Remove @alexec from owners list

- README.md
Recently featured on CNCF East Asia Twitter & LinkedIn page:
[Social Media Post: CNCF](https://www.linkedin.com/posts/zubair-haque_define-your-cicd-pipeline-with-argo-workflows-activity-7079510488954413058-jBGp?utm_source=share&utm_medium=member_desktop)
This shows users a way to use Argo Workflows as a CI tool for their Internal Developer Platforms & pipelines, you can achieve this goal without having to do anything complex like setting up a Runner (which competitors like Gitlab & Jenkins require), By the way this concept allowed us to deliver at scale & was mentioned by Argo Project maintainers from Intuit during Kubecon 2022.
Fixes #TODO
> docs: Adding Define your CI/CD pipeline with Argo Workflows blog post

- cmd/argoexec/commands/emissary_test.go
- workflow/executor/os-specific/command_test.go
Fixes #11368
Run test fail
Replace echo -n with echo ..\c"
make test
> fix: fail test on pr #11368

- docs/async-pattern.md
- docs/walk-through/volumes.md
- `suspend` and `resource` steps were mentioned in these two docs, but did not have links
- add links to template types' docs when they are mentioned in these two pages
- also consistently use "`suspend` step" (instead of a few different variations of that)
n/a
> docs: add links when referencing template types

- cmd/argo/commands/resume.go
- docs/cli/argo_resume.md
Fixes #TODO
add resume command validate avoid input empty param.
> chore: Validate `argo resume` arguments

- Makefile
- test/e2e/images/argosay/v1/Dockerfile
Fixes #10435
- Fix security
- Run examples on MacOS
- Upgrade base image
- Add/update build command for multiple arch
https://hub.docker.com/repository/docker/sonbui00/argosay
Run `DOCKER_PUSH=true make argosayv1` to build and push v1
Then  run `DOCKER_PUSH=true make argosay` to build and push v2
> fix: upgrade base image for security and build support arm64 #10435

- util/cmd/cmd.go
- util/cmd/cmd_test.go
- util/expr/argoexpr/eval_test.go
- util/util_test.go
- workflow/controller/config.go
Fixes #TODO
add util package ut.
> chore: Add unit tests for utils

- workflow/metrics/util.go
Fixes #TODO
I found a typo of error
changed a error name (invalidMetricLabelrror to invalidMetricLabelError)
> chore: correct typo (invalidMetricLabelrror to invalidMetricLabelError)

- dev/nix/flake.lock
- dev/nix/flake.nix
Updates node version to v20, fixes #11410
> build: update node to v20 in nix flakes. Fixes #11410

- ui/src/app/workflows/components/workflows-toolbar/workflows-toolbar.tsx
> fix: Only confirm DB deletion when there are archived workflows. Fixes #11658

- cmd/argo/commands/completion.go
Fix arog logs command completion
> fix: argo logs completion

- ui/src/app/modals/new-version/new-version-modal.tsx
Thanks @rwong2888 for reporting! https://cloud-native.slack.com/archives/C020XM04CUW/p1693249027693179
> fix: Add missing new version modal for v3.5

- .spelling
- docs/running-locally.md
This is asked very often. Adding these notes to help new contributors.
> docs: Add notes on using pprof for development

- docs/upgrading.md
This is referenced in release notes.
> docs: Add v3.5 upgrading notes

- USERS.md
Fixes docs: Adding KPMG to list of users
Signed-off-by: Ansuman Swain
> docs: Add KPMG to users

- cmd/argoexec/commands/emissary.go
- cmd/argoexec/main.go
- test/e2e/signals_test.go
- test/e2e/testdata/signaled-container-set-workflow.yaml
- workflow/controller/operator.go
- workflow/executor/os-specific/signal_darwin.go
- workflow/executor/os-specific/signal_windows.go
> fix: Support OOMKilled with container-set. Fixes #10063.  FOR 3.4.11 only

- server/workflow/workflow_server.go
- util/file/fileutil.go
- workflow/controller/operator_concurrency_test.go
> chore: pkg imported more than once

- docs/configure-artifact-repository.md
Fixes #TODO
- In [configure artifact-repository](https://argoproj.github.io/argo-workflows/configure-artifact-repository/), Helm installation   for mac is in this documentation. 
I think it will be better remove this description and add link to [helm documentation.](https://helm.sh/docs/intro/install/).
Changed documentation is like this
> docs: Remove helm installation guide and Add helm documentation link

- docs/use-cases/data-processing.md
- docs/use-cases/machine-learning.md
The book is related to these two use cases that leverage Argo Workflows.
> docs: Add links to Distributed ML Patterns book

- workflow/metrics/metrics_test.go
- workflow/metrics/util.go
- Validate prometheus metric labels in realtime gauge metric
> fix: add prometheus label validation for realtime gauge metric

- ui/src/app/shared/components/error-panel.tsx
- ui/src/app/shared/components/inline-table/inline-table.tsx
- ui/src/app/shared/components/nudge.tsx
- ui/src/app/shared/components/pagination-panel.tsx
- ui/src/app/shared/conditions-panel.tsx
- ui/src/app/shared/resources-duration.tsx
- ui/src/app/workflow-templates/components/workflow-template-creator.tsx
- ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx
- ui/src/app/workflow-templates/components/workflow-template-editor.tsx
- ui/src/app/workflow-templates/components/workflow-template-filters/workflow-template-filters.tsx
- ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx
- ui/src/app/workflows/components/events-panel.tsx
- ui/src/app/workflows/components/workflow-artifacts.tsx
- ui/src/app/workflows/components/workflow-creator-info/workflow-creator-info.tsx
- ui/src/app/workflows/components/workflow-creator.tsx
- ui/src/app/workflows/components/workflow-dag/workflow-dag-render-options-panel.tsx
- ui/src/app/workflows/components/workflow-editor.tsx
- ui/src/app/workflows/components/workflow-from.tsx
- ui/src/app/workflows/components/workflow-labels/workflow-labels.tsx
- ui/src/app/workflows/components/workflow-logs-viewer/full-height-logs-viewer.tsx
- ui/src/app/workflows/components/workflow-logs-viewer/json-logs-field-selector.tsx
- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
- ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
- ui/src/app/workflows/components/workflow-panel/workflow-panel.tsx
- ui/src/app/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.tsx
- ui/src/app/workflows/components/workflows-row/workflows-row.tsx
- ui/src/app/workflows/components/workflows-summary-container/workflows-summary-container.tsx
Partial fix for #9810
- Use newer, modern functional components compatible with hooks instead of legacy class-based components
- Several of the simpler components in `worflows/components/` were relatively quick to refactor, so did so
- Stumbled upon them while reviewing some UI PRs like #11790, figured I might as well convert them
- Others I just added to this PR as I was asked to consolidate PRs due to lack of approvers right now
- most of these are pure functional components
- migrate several components from class-based to functional:
- `shared/components/error-panel.tsx`
- `shared/components/inline-table/inline-table.tsx`
- `shared/components/inline-table/nudge.tsx`
- this one is technically the most "complex" (still very simple) on this list as it has a single variable of boolean …
> refactor(ui): migrate several components from class to functional

- workflow/artifacts/http/http.go
Part of https://github.com/argoproj/argo-workflows/issues/8489.
> feat: Support artifact streaming for HTTP/Artifactory artifact driver

- docs/configure-artifact-repository.md
Added some docs related to https://github.com/argoproj/argo-workflows/issues/8489 https://github.com/argoproj/argo-workflows/pull/11823
> docs: Add notes on artifact streaming

- README.md
- docs/README.md
It currently shows "failing" but is actually passing. I've observed the false positive many times so let's remove it.
> docs: Remove CI status badge from README.md

- ui/src/app/workflows/components/retry-workflow-panel.tsx
- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
> fix: Correctly retry an archived wf even when it exists in the cluster. Fixes #11903

- ui/src/app/shared/components/parameters-input/parameters-input.tsx
Partial fix for #9810 
Use newer, modern functional components compatible with hooks instead of legacy class-based components
- `this.props` -> arguments
- `this.state` -> useState
- methods -> inner functions
- Pure refactor, no real semantic changes
- Tested in Local environment 
- Screenshot below of `submit-workflows-panel`
> refactor(ui): convert ParametersInput to functional components

- manifests/quick-start/base/prometheus/prometheus-deployment.yaml
- workflow/gccontroller/gc_controller_test.go
Fixes typo in prometheus-deployment.yaml and gc_controller_test.go
> chore: Fix typo in `prometheus-deployment.yaml` and `gc_controller_test.go`

- ui/src/app/shared/components/dropdown/dropdown.tsx
- ui/src/app/shared/components/filter-drop-down.tsx
Partial fix for #9810 
Convert legacy class components to use the modern syntax of functional components and hooks
- Remove this statement and change to a React hook
- Change methods to regular functions
- Remove React lifecycle and change to useEffect
- [Removing scroll events](https://github.com/argoproj/argo-workflows/pull/11901#pullrequestreview-1651714439)
In my local environment, I checked the drop-down filters on the Event Flow page to see the change.
> refactor(ui): converting a drop-down component to a functional component

- hack/cherry-pick.sh
Addressed comments in https://github.com/argoproj/argo-workflows/pull/12040.
> chore: Incorporate suggestions from #12040

- OWNERS
https://github.com/argoproj/argoproj/pull/257
Congrats! @agilgur5 @joibel
> chore: Add agilgur5 and joibel to reviewers

- workflow/artifacts/oss/oss.go
> feat: implement IsDirectory for OSS

- util/logs/workflow-logger.go
Fix stream leak
Fix stream leak
> fix: leak stream

- pkg/apiclient/argo-kube-client.go
> fix: Add identifiable user agent in API client. Fixes #11996

- USERS.md
This PR adds the content from https://github.com/argoproj/argo-workflows/pull/12249 to `USERS.md` since I believe it would be a good place to gauge interest, especially for organizations.
> docs: Add interest gauge in USERS.md

- docs/metrics.md
Just a docs improvement. Please suggest better wording if it doesn't make as much sense as it should 
Inspired by #5291
> docs: try to explain the metric `operation_duration_seconds` better

- README.md
- docs/README.md
My book [Distributed Machine Learning Patterns from Manning Publication](https://github.com/terrytangyuan/distributed-ml-patterns) uses Argo Workflows and would be a good resource for people who use it for ML use cases.
> docs: Add Distributed Machine Learning Patterns book

- workflow/controller/controller.go
- workflow/controller/controller_test.go
When I submit a workflow. It didn't work successed for some reason(such as no stock), some of pod is  still Pending.
So I terminate the workflow.  But the pending pod was not deleted.
After awhile, the pending pod is running , but the workflow has failed and caused some waste of resources.
So, we need to delete pending pod when workflow terminated.
> fix: delete pending pod when workflow terminated 

- USERS.md
Add DP Technology to USERS.md (https://www.dp.tech/)
<!--
> docs: add DP Technology to USERS.md

- docs/README.md
See https://github.com/argoproj/argo-workflows/pull/12306#pullrequestreview-1796722746
> docs: Add link to Killercoda interactive course in docs/README.md

- community/sustainability_effort.md
This is a new dedicated channel for this effort.
> docs: Mention #argo-wf-sustainability in sustainability efforts

- workflow/executor/agent.go
> fix: http template host header rewrite(#12385)

- hack/cherry-pick.sh
Fixes:
```
git: 'cp' is not a git command. See 'git --help'.
```
@sarabala1979
> chore: Update cherry-pick.sh

- docs/debug-pause.md
> docs: Fix path

- util/errors/errors.go
- util/errors/errors_test.go
I meet a err when I submit lots of workflow, the workflow sometimes failed with a err:
And  i search the audit log in apiserver logstore with
```
* and clusterId and "resource quota evaluation timed out" and content: argo-executor and podIp
```
the result is only one:
```
1 httplog.go:127] "HTTP" verb="POST" URI="/apis/argoproj.io/v1alpha1/namespaces/argo/workflowtaskresults" latency="10.019206806s" 
``` 
Only find one item, it means didn't retry. But the root cause is apiserver undering great pressure. We can succeed workflow by retry to create workflowresult. So I want to add resource quota evaluation timed out to transient.
> fix: add resource quota evaluation timed out to transient

- docs/configure-artifact-repository.md
Fixes #12551 
https://github.com/minio/minio/issues/18685#issuecomment-1865023630
Changed the minio chart repo
> fix: update minio chart repo

- go.mod
- go.sum
To fix https://github.com/advisories/GHSA-9763-4f94-gfch
Fixes #TODO
> chore(deps): bump github.com/cloudflare/circl to 1.3.7 to fix GHSA-9763-4f94-gfch

- util/errors/errors.go
These errors occasionally occur on LKE (Linode hosted kubernetes) in response to normal actions, and are perfectly retriable. It isn't unreasonable to have these errors exposed to users, even if it doesn't appear to happen on any other cluster types I've tried.
We have tried to replicate with toy clusters.
Put the errors in the code rather than expect users to have to do this themselves.
Verified using the TRANSIENT_ERROR_PATTERN by a customer as I don't have access to an LKE cluster.
> fix: make etcd errors transient

- docs/installation.md
- use [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) that come with the material theme instead of a unicode caution sign
- consistent with the design of the docs 
- replace unicode caution signs with admonitions
- be more specific in the notes as well
- using a remote base is not inherently "dangerous" as the previous sentence said without elaboration
- instead specify that you should use a full hash when using a remote base
- and add a link to Kustomize's remote base docs
- similarly in the second note, specify what "tip" means
- and specify what you should do instead of using `latest`
1. `mkdocs build` passes
1. Looks as expected:
- Before:
- After:
> docs(install): use material admonition instead of unicode caution

- mkdocs.yml
Follow-up to https://github.com/argoproj/argo-workflows/issues/11390#issuecomment-1876274288 
- I noticed this while looking at CD's `mkdocs.yml` for differences
- [CD](https://github.com/argoproj/argo-cd/blob/d9df2525c57d4870215a6ce149dbedd08ae05fdb/mkdocs.yml#L222) and [Rollouts](https://github.com/argoproj/argo-rollouts/blob/bc992a3fe082e6dc19529194b331d7134928257d/mkdocs.yml#L147) both have this unicode character "⧉" to indicate that a link is external
- it's also a nice touch to indicate an external link (vs. an internal link)
- here's a screenshot of CD's ToC: 
- add this to Workflows's `mkdocs.yml`'s headers/ToC as well for consistency
1. `mkdocs build` passes
1. Screenshot: ![Screenshot 2024-01-12 at 9 13 51 PM](https://github.com/argoproj/argo-workflows/assets/4970083/c0a2c6eb-471 …
> docs: add unicode char next to external links in header/ToC

- community/sustainability_effort.md
The sustainability initiative looks really good
would like to contribute more
> docs: add tczhao to sustainability incentive

- community/sustainability_effort.md
Motivation: addressing some concerns related to Sustainability Effort
> docs: some updates to Sustainability Effort policies

- docs/container-set-template.md
small typo fix in container-set-template.md
> docs: typo fix in container-set-template.md 2

- docs/container-set-template.md
this is a tiny typo fix in container-set-template.md
> docs: typo fix in container-set-template.md

- USERS.md
We've been running Argo Workflows for about a year now, and we'd like to make it official 😄
> docs: Add PayIt to USERS.md

- docs/workflow-rbac.md
These changes are in response to [this comment thread](https://github.com/argoproj/argo-workflows/pull/12680#discussion_r1495298824)
> docs: remove Workflow RBAC 3.5.2 note and example

- USERS.md
> docs: add SternumIOT to USERS.md

- workflow/executor/executor.go
Log change.  task set -> task result
> fix(log): change task set to task result.

- docs/argo-server-sso-argocd.md
Thanks for the docs! They were really helpful - I fixed a small issues in the values.yaml I encountered when following them
> docs: update Helm values for SSO config

- go.mod
- go.sum
Snyk has been [failing on `main`](https://github.com/argoproj/argo-workflows/actions/runs/8161595234/job/22310705952) since yesterday due to a new CVE: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-6371508
Update `go.mod` and `go.sum`:
- `pgx` is an indirect dep, used by `upper/db`
- `pgx` 4.18.1 -> 4.18.2, `pgconn` 1.14.1 -> 1.14.3, `pgproto3` 2.3.2 -> 2.3.3
Tests still pass
> fix(deps): upgrade `pgx` from 4.18.1 to 4.18.2 due to CVE

- cmd/argo/commands/archive/resubmit.go
- cmd/argo/commands/archive/retry.go
- cmd/argo/commands/version.go
> chore: fix function comments

- .gitattributes
Follow-up to #11321, one of my first PRs to Argo, where, per the PR description "Notes to Reviewers", I wasn't 100% sure if this was generated or not. I didn't get a response then, but I now know the answer myself -- it is.
- Make diffs easier to read by collapsing `pkg/client/` diffs
- Note: GH does automatically [detect](https://github.com/github-linguist/linguist/blob/aa11c2caa4cdd199d0ab67ea3e579cd6767a1127/lib/linguist/generated.rb#L326) these files as generated, but we've had a number of PRs to generated code (e.g. #12208, https://github.com/argoproj/argo-workflows/pull/12838#discussion_r1536703662), so I figure it is good to be more explicit
Mark `pkg/client/**` as generated code in `.gitattributes`
- this is generated in the `Makefile` in [this …
> chore: mark `pkg/client/` as generated code

- docs/argo-server-sso-argocd.md
Clarify that staticClients id is the OIDC client ID, not the secret name.
Fixes #TODO
> docs(sso): clarify Dex `staticClients` ID

- README.md
- docs/README.md
- As preferred by [the docs style guide](https://argo-workflows.readthedocs.io/en/latest/doc-changes/)
- now that `docs/README.md` is synced with `README.md` (#12752), thought this was a good time to update
- I actually made the modifications at the same time, but held off on this to reduce the diff as it's independent of that change and would merge conflict if made in parallel
- reformat `README.md` and `docs/README.md`
1. no visual changes -- see [rendered markdown](https://github.com/argoproj/argo-workflows/blob/27537774eec4723b0807ab75714b55127233cf86/README.md) in this PR
1. `make docs` passes
> docs: reformat README as 1 sentence per line of markdown

- .github/workflows/release.yaml
Fixes #12828
Recently, Sigstore has published a new TUF trust root.
https://sigstore.slack.com/archives/C01DGF0G8U9/p1710871645742299
https://blog.sigstore.dev/tuf-root-update/
A new TUF trust root doesn't support Cosign v1.13.2, so we should upgrade Cosign to v1.13.6 or v2.
- Upgrade Cosign to v2
- Set the command line option `-y`
```
-y, --yes=false:
skip confirmation prompts for non-destructive operations
```
Without this option, `cosign sign` and `cosign sign-blob` don't work in CI.
> chore(deps): upgrade Cosign to v2.2.3

- docs/argo-server.md
Updates the Ingress example on the Argo Server docs page, as Ingress is no longer in beta as of Kubernetes v1.19.
The example was wrong / outdated.
N/A
N/A
> docs: Update Argo Server docs Ingress apiVersion example

- workflow/controller/operator_persist_test.go
- workflow/controller/operator_test.go
- workflow/controller/workflowpod_test.go
- workflow/executor/common/common_test.go
- workflow/validate/validate_test.go
> chore: fix function name in comment

- USERS.md
Motivation
We've been running Argo Workflows for about a year now, and we'd like to make it official 😄
> docs: Add CloudGeometry to USERS.md

- ui/src/app/workflows/components/workflow-details/workflow-details.tsx
- ui/src/models/workflows.ts
Fixes [this Slack thread](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1712142240797399), no formal bug report was filed unfortunately
Fixes a bug where the Workflow Details page would error out with: `TypeError: Cannot read properties of undefined (reading 'workflows.argoproj.io/workflow-archiving-status')`
- use optional chaining to handle case of no labels
- similar to changes in #12170 for `isArchivedWorkflow`, which is just below `isWorkflowInCluster`
No repro was provided unfortunately, but these are the only two places where this label is accessed and so could result in such an error.
> fix(ui): handle non-existent labels in `isWorkflowInCluster`

- ui/src/app/shared/retry-observable.ts
Noticed this syntax was deprecated in my editor while debugging #12672. Turns out it's nothing too big, but figure I'd update it while I was at it
- `subscribe` with multiple arguments has been [deprecated and replaced](https://rxjs.dev/deprecations/subscribe-arguments) with object / Observer syntax
- multi-arg was difficult to use / read, while this variant is very explicit
In `retry-observable.ts`, replace `subscribe` deprecated multi-args with clearer single arg object / Observer syntax
I had this change locally while working on #12672, it did not change any behavior
> chore(ui): update deprecated RxJS syntax

- README.md
- docs/README.md
https://www.onepanel.ai/  cann't be access, it should be github address https://github.com/onepanelio/onepanel.
> chore: change onepanel project address. 

- README.md
- docs/README.md
Fixes #12613, related to #13033
Piper is at a new URL / repo per [its README](https://github.com/Rookout/piper/blob/440953e2dbf0a447531b31fad7827a4bdd9b103a/README.md?plain=1#L5)
update Piper's links in `README.md` and `docs/REAMDE.md` 
`make docs` passes
> docs: update link to Piper

- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
simplify & optimize some of the state in the `WorkflowLogsViewer` component
- only retrieve values from `localStorage` once, on the initial state set
- the callback only happens once, while previously it was retrieved on every render but only used on the first
- also improve the typings a bit by using generics instead of a cast
- replace the secondary log filter state with a debounce
- it was giving a 1000ms delay, which is exactly what you can do with a debounce
- and we already have a debounce func in the utils, so just re-use that
<details><summary>Screenshot of the filter still working: </summary>
</details>
> refactor(ui): optimize state in logs viewer 

- test/e2e/cli_test.go
- test/e2e/testdata/resubmit-dag-with-dependencies.yaml
- workflow/util/util.go
Fixes: #12936
delete skipped node when resubmit with memoized
> fix: delete skipped node when resubmit with memoized.Fixes: #12936

- USERS.md
Add Maya Philippines as an Org user of this project
> docs: Add Maya as Org user

- USERS.md
Apologies for the extra space
Remove extra space
> docs: fix Maya Org User link

- OWNERS
https://github.com/argoproj/argoproj/pull/299
Congratulations and thank you all for your hard work!
@Joibel @tczhao @shuangkun
> chore: Update OWNERS from recent promotions

- community/sustainability_effort.md
Jason's switched projects at work and no longer has time for Workflows, unfortunately.
> chore: remove Jason Meridth from Sustainability Effort

- docs/stress-testing.md
Fixes #TODO
fix typo error gcloud cli
fix typo : gloud -> gcloud
Using `gcloud` CLI
> fix(docs): Fix `gcloud` typo

- cmd/argo/commands/completion.go
- docs/cli/argo.md
- docs/cli/argo_completion.md
Fixes  #13127
the fish user better cli user experience
> feat: argo cli support fish completion

- docs/argo-server-sso.md
Make instruction clearer. 
`Typically an organization`  vs `Typically on organization`
Just modifying grammar.
Ran Make docs
> docs: correct typo in SSO instructions

- .spelling
- docs/releases.md
Follow-up to #13132 and #11934
- did a full style guide audit of this page too, similar to my previous PRs, but there wasn't _too_ much to change here
- hoping to get through _all_ the docs pages eventually
- remove duplicated note about breaking changes being listed in the upgrading guide
- the next section says the same thing
- simplify release cycle section, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
<details><summary>other minor style changes: </summary>
- put italics around the fact that Argo doesn't use SemVer -- just to be _more_ explicit
- replace use of jargon such as "shipped", per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-jargon-and-idioms)
- use more consistent language …
> docs: minor copy-edits to releases page

- docs/metrics.md
Link to a more up-to-date Grafana dashboard.
Previous: https://grafana.com/grafana/dashboards/13927-argoworkflow-metrics/, has not received an update in 2+ years (not since early 2022)
New: https://grafana.com/grafana/dashboards/20348-argo-workflows-metrics/, has received updates in 2024
Pipekit was working on this and I was wondering where their dashboard was and then I saw it in two [recent](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1715607073926439) [Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1716303716690499?thread_ts=1716303570.506539&cid=C01QW9QSSSK) threads.
- just update the link, nothing else
`make docs` passes
- disclaimer that this is Pipekit's up-to-date fork of the community one previously linked
- ideally, we should maintain an official …
> docs: link to a more up-to-date Grafana dashboard

- workflow/artifacts/oss/oss.go
> fix: oss internal error should retry. Fixes #13262

- test/e2e/workflow_test.go
- workflow/util/pod_name.go
- workflow/util/pod_name_v2_test.go
Supersede #12928 and add test.
Fixes #12895
Fixes #12937
> fix: correct pod names for inline templates. Fixes #12895

- manifests/quick-start/base/httpbin/my-httpbin-cred-secret.yaml
- manifests/quick-start/base/minio/my-minio-cred-secret.yaml
- manifests/quick-start/base/overlays/workflow-controller-configmap.yaml
- manifests/quick-start/minimal/overlays/workflow-controller-configmap.yaml
- manifests/quick-start/mysql/argo-mysql-config-secret.yaml
- manifests/quick-start/mysql/overlays/workflow-controller-configmap.yaml
- manifests/quick-start/postgres/argo-postgres-config-secret.yaml
- manifests/quick-start/postgres/overlays/workflow-controller-configmap.yaml
- manifests/quick-start/sso/dex/dex-cm.yaml
- manifests/quick-start/sso/overlays/workflow-controller-configmap.yaml
Seen this before, but was more striking while searching for YAML files without `kind`s (for test purposes) in #13317 -- all other files were very quickly discernible 
- several manifests, particularly Secrets and ConfigMaps, had the "header" with `kind` and `metadata` at the bottom
- but still had `apiVersion` at the top
- this is pretty confusing to look at and doesn't match the rest of the manifests, so make it consistent
- move `kind` and `metadata` to the top of the manifests, under `apiVersion`, as is common k8s convention
n/a, pure style change
> chore(manifests): consistently put k8s "header" at the top

- README.md
- docs/README.md
- the link went to `main`, but the query for the badge did not
- this should only show `main`, and then for release branches show the release branch
- this will need manual backporting as such (np, I can do that)
- add a branch query to the SVG
- Copied from the [Actions page](https://github.com/argoproj/argo-workflows/actions/workflows/snyk.yml?query=branch%3Amain)'s "Create status badge" button (under the 3 dots)
- Can see the [rendered manifest](https://github.com/argoproj/argo-workflows/blob/5a81c4c1eeba1da355d5ccea392ec5d4441b4a0c/README.md)
> docs: only display `main` status for Snyk badge

- docs/title-and-description.md
noticed a typo in the docs
fixed misspelling of `titile` to `title`
no red squiggly line from the spellchecker
> docs: fix typo in title example

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/regression.yaml
Just a small grammar and consistency issue I noticed while writing up #13324  etc
- "what you expected" -> "what did you expect"
- also make the bug templates use two full sentences instead
Pure string change. See also [rendered commit](https://github.com/argoproj/argo-workflows/blob/2d1443ed7c36c0ab17e7f135e67498c70fe5643c/.github/ISSUE_TEMPLATE/regression.yaml)
> chore(gh): fix grammar error in regression template

- Makefile
Just some reorganization I've been brewing for a while
- some of these were mixed in random places
- instead put them together with related chunks
- categories:
- `VERSION` with other build metadata
- test options together
- docker image publishing options together
- pure env vars all together
- other misc changes:
- remove unused `DEV_IMAGE`
- remove some unnecessary new lines between related variables
- in-line some comments
pure style change, no semantic changes
This is ofc subjective and there's potentially many other things to reorganize too (like splitting up the `Makefile` tasks into more files), but I think I got something somewhat small here that is definitively better than the previous version
> refactor: reorganize some `Makefile` variables

- .devcontainer/devcontainer.json
Some services' ports were missing in the `devcontainer.json#forwardPorts` config, which I noticed while [trying to get Dex forwarding working](https://cloud-native.slack.com/archives/C0510EUH90V/p1720741178268569)
- include all services in [`hack/port-forward.sh`](https://github.com/argoproj/argo-workflows/blob/0d706d0027e92a0abe9a58a4aae841465f1c99ec/hack/port-forward.sh#L22) (plus the `webpack-dev-server`)
- adds:
- another minio port
- prometheus ports + Controller's pprof port
- dex port
- Postgres + MySQL ports
- azurite port
> fix(devcontainer): expose ports for all services

- cmd/argo/commands/template/list.go
- docs/cli/argo_template_list.md
Fixes #13309
support `-l` selector param for template client
support `-l` selector param for template client
run locally and tested
> feat(cli): support `-l` flag for `template list`. Fixes #13309

- .snyk
Fixes https://github.com/argoproj/argo-workflows/issues/13405.
Reference doc: https://docs.snyk.io/manage-risk/policies/the-.snyk-file#use-the-.snyk-file-with-snyk-open-source
> ci: temporarily ignore false positive Snyk vulnerability for `jackc/pgx/v4`

- api/openapi-spec/swagger_test.go
- cmd/argo/commands/common/submit.go
- examples/dag-daemon-task.yaml
- ui/src/models/workflows.ts
- util/tls/tls_test.go
- workflow/controller/dag.go
- workflow/controller/operator.go
> chore: fix some typos in comments

- .snyk
Fixes https://github.com/argoproj/argo-workflows/issues/13405.
> ci: Remove Synk ignore for vulnerability for jackc/pgx/v4

- ui/src/app/workflows/components/workflow-drawer/workflow-drawer.tsx
Fixes #11949
Issue 11949 want to add full name in details.
Added full name in details.
I built argo in my local, and watched the change in ui.
> feat(ui): add full workflow name in list details. Fixes #11949

- community/sustainability_effort.md
I spoke to Bala, and unfortunately he's not able to put in the required hours for this.
> docs: remove Bala from Sustainability Effort

- community/sustainability_effort.md
Adding myself to the sustainability initiative. I've already contributed a few things: https://github.com/argoproj/argo-workflows/pulls/MasonM
N/A
N/A
> docs: add MasonM to sustainability_effort.md

- cmd/argo/commands/archive/delete.go
- docs/cli/argo_archive_delete.md
Fixes #11898
Modify the argo archive delete command for more information
Added example for the argo archive delete command.
run `argo archive delete -h`
> docs(cli): add example for `argo archive delete`

- workflow/controller/controller.go
> fix: add `cronWorkflowWorkers` log. Fixes: #13681

- cmd/argo/commands/lint_test.go
- cmd/argo/lint/formatter_pretty_test.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
- workflow/artifacts/common/load_to_stream_test.go
- workflow/executor/executor_test.go
Fixes #11994 (or rather adjusts a few things fixed in #12011)
Adjusts changes based on review feedback.
> fix(test): windows tests fixes. Fixes #11994

- ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/13056 per https://github.com/argoproj/argo-workflows/issues/13056#issuecomment-2383564895
> fix(ui): remove leading slash in `uiUrl` for ArchivedWorkflowList redirect. Fixes #13056

- USERS.md
Added Pvotal Technologies to USERS.md
Fixes #TODO
> docs: add Pvotal Technologies to USERS.md

- config/config.go
- config/workflow_events.go
- config/workflow_events_test.go
- docs/workflow-controller-configmap.yaml
- workflow/controller/operator.go
Fixes https://github.com/argoproj/argo-workflows/issues/13042
> feat: add config to skip sending workflow events. Fixes #13042

- community/sustainability_effort.md
Unfortunately, I no longer have bandwidth to participate in this. :(
> chore: remove Julie from Sustainability Effort

- ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Fixes https://github.com/argoproj/argo-workflows/issues/10993
> fix(ui): clarify log deletion in log-viewer. Fixes #10993

- ui/src/app/shared/components/graph/graph-panel.tsx
- ui/src/app/workflows/components/workflow-dag/workflow-dag-render-options-panel.tsx
- ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Fixes #11106.
It's confusing to look at the Workflows graph with templateRef and tasks having the same names. Creates linear graph without template hierarchy.
- Added the ability to show the invoking template name on nodes. To keep the actual display, I added the switch button on the toolbar. Also updated the title to include the full id and name of the node as the test is truncated.
- Added the grouping by templateRef using `boundaryId`. This seems to have the desired results. 
Demo
https://github.com/user-attachments/assets/763ea3b5-7349-405f-8fa9-420d9a8a091e
I tested on simple workflows, especially the one listed on the original issue, see screen recording
> feat(ui): Group nodes based on `templateRef` and show invoking template name. Fixes #11106

- docs/new-features.md
Fix a link in new-features. Self explanatory.
> docs: fix new feature link

- .devcontainer/devcontainer.json
Follow-up to #13349, I missed the docs service
port `8000` is normally used by `mkdocs serve` per its logs:
```
INFO    -  [18:34:01] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [18:34:01] Serving on http://127.0.0.1:8000/
```
Add port `8000` to the `devcontainer.json#forwardPorts` config
Note that like `make docs`, there is a `make docs-serve` task as well, which is [referenced in the contributing docs](https://argo-workflows.readthedocs.io/en/release-3.5/doc-changes/#running-locally)
> build(devcontainer): expose port of `mkdocs serve`

- ui/src/workflows/components/workflow-dag/workflow-dag.tsx
Fixes #13834
-  When implementing https://github.com/argoproj/argo-workflows/pull/13511 I used the same default as the "Toggle artifacts" button, but obviously not the desired default behavior
- I inverted default values for 
- group by templateRefs
- show invoking template name
| Before  |  After |
|---|---|
|  ![Screenshot 2024-10-29 at 10 55 24](https://github.com/user-attachments/assets/a2714ca8-3145-4a2b-b7c1-bdeae3e6717e) |  ![Screenshot 2024-10-29 at 10 55 35](https://github.com/user-attachments/assets/ed519856-02e9-4ffa-8d35-abcc7374e363) |
> fix(ui): disable new graph filter options by default

- OWNERS
- community/sustainability_effort.md
I have not agreed with several Argoproj decisions that fundamentally go against my values and that I think are antithetical to several foundational rules and norms.
As these decisions have increased over time and moreso in recent times, rather than decreased, _despite_ my best efforts, I can no longer in good faith commit to contributing to the project.
As always, I let my actions and my contributions speak much louder than my words.
- remove myself from `OWNERS` and `sustainability_effort.md`
- passes the eyeball check
> chore: remove `@agilgur5` from OWNERS and Sustainability Effort

- examples/README.md
Noticed this during https://github.com/argoproj/argo-workflows/pull/13645 et al when setting up embedded examples
- it previously said things were moved to the walk through, but the whole directory is still used
- perhaps in the past this README in the past was used like a walk through, but this is no longer accurate and is confusing / misleading
- update it to mention its usage in the docs, such as in embedded examples like in https://github.com/argoproj/argo-workflows/pull/13645 and the [Field Reference](https://argo-workflows.readthedocs.io/en/release-3.5/fields/)
- could also remove the file entirely, but the directory is used, so I figure it could have a short summary of how/where it is used
markdown renders correctly (see [rich …
> docs: update `examples/README.md` to its current usage

- CODEOWNERS
- OWNERS
Promote jswxstw to reviewer
Promote Joibel to lead
As per https://github.com/argoproj/argoproj/pull/342
> chore: promotions from membership meeting (Nov 2024)

- .github/workflows/snyk.yml
Fixes #13975 
Fix the snyk scan only 
Create the missing file as per #11707 for the snyk scan.
Completely untested, can't really be tested except in `main` or a `release` branch
> fix(ci): snyk scan

- .github/ISSUE_TEMPLATE/bug_report.yaml
Another tiny typo that was annoying me.
> docs: correct minor typo in issue template

- test/e2e/resource_template_test.go
Although the TestResourceTemplateAutomountServiceAccountTokenDisabled test case ran successfully
```
3991 % argo list
NAME                                                          STATUS      AGE   DURATION   PRIORITY   MESSAGE
k8s-resource-tmpl-with-automountservicetoken-disabled-2wgh8   Succeeded   27s   16s        0
k8s-wf-resource-xgtrq                                         Succeeded   25s   7s         0
```
However, the log of the main pod showed that there was some problem with the permissions of the SA used.
```
13991 % kubectl logs k8s-resource-tmpl-with-automountservicetoken-disabled-2wgh8
time="2024-12-15T08:20:32.736Z" level=info msg="capturing logs" argo=true
time="2024-12-15T08:20:32.736Z" level=debug msg="ignore signal child exited" argo=true …
```
> chore(test): set serviceaccount to default for executor.

- docs/argo-server-sso.md
Reading the documentation of [SSO RBAC](https://argo-workflows.readthedocs.io/en/stable/argo-server-sso/#sso-rbac) and found the typo:
> The precedence is used to determine which service account to use whe Precedence is an integer.
should be
> The precedence is used to determine which service account to use when Precedence is an integer.
`s/whe/when/`
> docs: fix the typo of the description of `Precedence`

- docs/workflow-concepts.md
I noticed that not all the template types are documented in the template definitions overview so this PR addresses that.
Also formats the page in accordance with the docs guidelines
> docs: Add all the template types to the core concepts page

- server/clusterworkflowtemplate/cluster_workflow_template_server.go
- server/clusterworkflowtemplate/cluster_workflow_template_server_test.go
- server/cronworkflow/cron_workflow_server.go
- server/cronworkflow/cron_workflow_server_test.go
- server/event/dispatch/operation.go
- server/workflow/workflow_server.go
- server/workflow/workflow_server_test.go
- server/workflowtemplate/workflow_template_server.go
- server/workflowtemplate/workflow_template_server_test.go
- workflow/common/common.go
- workflow/creator/creator.go
- workflow/creator/creator_test.go
- workflow/util/util.go
- workflow/util/util_test.go
Fixes #14102 
when sso is enabled, server will add actor labels so that we know who was making the changes to resource
instead of relying on matching timeline with the audit log
added labels
```
workflows.argoproj.io/actor:
workflows.argoproj.io/actor-email:
workflows.argoproj.io/actor-preferred-username:
workflows.argoproj.io/action:
```
relevant label will be added when user perform the following action
- workflow
- terminate
- stop
- suspend
- resume
- workflowTemplate
- update
- clusterWorkflowTemplate
- update
- cronWorkflow
- update
The code follows the same pattern as the existing creator code but instead, we are recording/labelling other workflow actions.
Added unit tests
> feat: label actor action when making change to workflow/template. Fixes #14102

- docs/security.md
This PR does not fix any issue on file.
I just happened to notice the problem when reading the docs.
Simply deleted a duplicate entry that looks like a typo.
None.
> docs: delete duplicate entry in example Role

- docs/security.md
While reading the [documentation](https://argo-workflows.readthedocs.io/en/latest/security/#ui-access) on setting up RBAC and SSO, I noticed that the `cronworkflows` resource is duplicated. 
This PR removes the duplicate entry to keep the role definition clean and accurate.
> docs: remove duplicate of UI Access resource

- docs/fields.md
- examples/exit-handler-step-level.yaml
- examples/template-on-exit.yaml
Find some examples has the deprecated `onExit` field. This PR revises those examples and follows the latest practice.
2 example manifest got changed.
Removed the `onExit` from step and changed to `hooks.exit.template`.
Submitted the workflows to a private Argo workflow 3.6.2 service and it passed.
> chore: revise examples with `onExit` fields

- .spelling
- docs/container-set-template.md
Make the docs easier to understand
- Reformat the docs to adhere with the kubernetes documentation style guide (as requested in the docs contributing guide).
- Remove the explicit need to run emissary because emissary is now the only supported executor
- Be explicit that ContainerSet templates only run container templates. (a lot of slack users ask if you can run scripts in containerSets).
- Lean more into when to use and not use containerSet templates as this has caused confusion in slack before
> docs: Improvements to ContainerSet Templates docs

- .github/workflows/pr.yaml
A lot of security improvements from this version.
> ci: Update sematic PR check to v5.5.3

- test/e2e/testdata/cronworkflow-deprecated-schedule.yaml
- util/telemetry/instrument.go
- util/telemetry/metrics.go
- util/telemetry/operators.go
- workflow/metrics/counter_log.go
- workflow/metrics/gauge_pod_phase.go
- workflow/metrics/gauge_workflow_condition.go
- workflow/metrics/gauge_workflow_phase.go
- workflow/metrics/leader.go
- workflow/metrics/metrics.go
- workflow/metrics/metrics_custom.go
- workflow/metrics/metrics_test.go
- workflow/metrics/work_queue.go
> fix: locking in metrics (backport release-3.6)

- docs/argo-server.md
Fixes #14182
- Clarify that the API rate limit argument is a per-second value, not a per-minute one
- Conform to our docs guidelines
`make docs`
> docs: Clarify argo server rate limiting

- docs/workflow-concepts.md
I found a broken link so wanted to fix it.
Corrects a broken link to the k8s docs
1. `make docs
2. Clicked a link
> docs: fix broken link on workflow-concepts.md

- docs/scaling.md
We noticed that there was no documentation for this feature outside of the example controller configmap.
- Documented the `resourceRateLimit` feature.
`make docs`
> docs: add resourceRateLimit information to scaling docs

- ui/src/workflows/components/retry-workflow-node-panel.tsx
Fixes #14208
The override parameter div in the ui for retry node panel is not scrollable, so when the list of parameters is long, all of the other buttons are unreachable without zooming out.
Add css `overflow:auto` to the override parameters div
Changes are verified with local argo ui via `make start UI=true`
> fix(ui): scrollable override parameter div for retry node panel. Fixes #14208

- examples/exit-handler-step-level.yaml
One liner for a line missed in https://github.com/argoproj/argo-workflows/pull/14127
> chore: remove `onExit` in example

- docs/high-availability.md
Addressing feedback from a now-merged PR: https://github.com/argoproj/argo-workflows/pull/14173#discussion_r1981741108
Clarify the scalability of the argo server.
`make docs`
> docs: Clarify that the argo server can be scaled horizontally

- pkg/apis/workflow/v1alpha1/workflow_types.go
- pkg/apis/workflow/v1alpha1/workflow_types_test.go
(cherry picked from commit 581950f7ae9f039a10d392d40a111f8f33e06eb3)
> fix: correct semaphore configmap keys for multiple semaphores (#14184) (release-3.6)

- ui/src/shared/components/dropdown/dropdown.scss
…14290
Fixes #14290
When multiple browsers are displayed on a single screen, argo-dropdown moves off-screen, making it unusable.
- Fixed CSS issues and set argo-dropdown to a fixed position.
> fix: Prevent dropdown from disappearing when shrinking the viewport

- workflow/common/common.go
Fixes #TODO
Just fixing a typo.
> fix: Fix typo in common.go

- .devcontainer/devcontainer-lock.json
- .devcontainer/devcontainer.json
- .github/dependabot.yml
The Dev Container currently isn't reproducible, which means contributors can run into weird bugs that we can't reproduce locally.
* Add a `devcontainer-lock.json` file, which was auto-generated by VS Code, so that the features we use are pinned. Spec: https://github.com/devcontainers/spec/blob/482e5f9e022c82f0f12e776f196df81a440eae03/docs/specs/devcontainer-lockfile.md
* Update Dependabot to keep the lockfile up-to-date. Docs: https://containers.dev/guide/dependabot
* Pin the base image to the Ubuntu version used in CI: https://github.com/argoproj/argo-workflows/blob/8691b9b186ef0d8157933d35d1d658b0e1729b74/.github/workflows/ci-build.yaml#L30
Rebuilt the dev container in VS Code
N/A
> build: add devcontainer-lock.json and pin base image

- CHANGELOG.md
- hack/changelog.sh
Fixes #14293
Cherry-picked commits (e.g. https://github.com/argoproj/argo-workflows/commit/9e532061c064d1205610b1932a0fb3c4dc053421) are being attributed to `gcp-cherry-pick-bot[bot]` in `CHANGELOG.md` instead of the original author, since the bot overwrites author information. Also, the contributor list isn't sorted properly.
This fixes `hack/changelog.sh` using `git shortlog --summary --group=author --group=trailer:co-authored-by` to extract the original author from the `co-authored-by` trailer. Relevant docs: https://git-scm.com/docs/git-shortlog#:~:text=co-authored-by
I also fixed the script to set the locale so the list is sorted properly, exclude bots, and omit empty sections.
Ran `./hack/changelog.sh > CHANGELOG.md` in the DevContainer and committed the result
N/A
> fix: incomplete/unsorted contributors list in CHANGELOG.md. Fixes #14293

- go.mod
- workflow/artifacts/s3/errors.go
- workflow/artifacts/s3/s3.go
- workflow/artifacts/s3/s3_test.go
Move s3 pkg back to improve maintainability.
For #14312
> refactor: move s3 pkg from argoproj to workflow repo. Part of #14312

- server/artifacts/artifact_server.go
- workflow/controller/artifact_gc.go
Fixes #TODO
When the ?? characters were initially added to the error log, it might have been intended to express surprise or uncertainty about the situation. However, in the final output error message, ?? does not provide any additional useful information to users or developers and may instead cause confusion.
If this simple cleanup deviates from the original intent, or if I’ve misunderstood what the developer initially meant to convey, feel free to close this PR.
> chore: Remove the "??" character from the error log

- USERS.md
Add Priceline.com to users list
> docs: add Priceline to USERS.md

- .spelling
- docs/plugin-directory.md
Add a plugin lets Argo Workflows orchestrate PyTorch jobs.
> chore(plugin): add pytorch job plugin.

- workflow/controller/controller.go
https://github.com/argoproj/argo-workflows/pull/14336#issuecomment-2817725179
> chore(lint): remove duplicate imports.

- pkg/apiclient/argo-kube-client.go
Fixes error when using caching in argo kube client. Currently SQL store is not started and therefore client cannot list workflows. 
Start workflow server when creating a new one. 
Executed locally.
> fix: refactor argoKubeClient to start argo server when creating workflowServiceClient

- workflow/controller/operator_test.go
- workflow/util/util.go
- workflow/util/util_test.go
Cherry pick of (#13734)
(cherry picked from commit 497f338764b68d6f3607113bf7a451d57d1427c4)
> fix: correct retry logic (#13734) (release-3.6)

- workflow/util/util.go
- workflow/util/util_test.go
From #14181 
(cherry picked from commit 7ecb17f95255771e1b3408f0614285e51fc384fd)
> fix: manual retries exit handler cleanup. Fixes #14180 (#14181) (release-3.6)

- workflow/util/util.go
From #14328 
(cherry picked from commit bd13b1c92bdb6cbc60c71f7664c4472e6fdc1d3f)
> fix: correct manual retry logic. Fixes #14124 (#14328) (release-3.6)

- README.md
- docs/README.md
> docs: Update link to X in README.md

- USERS.md
Just added company I work for to the USERS.md
> docs: Added Swissblock Technologies to USERS.md

- util/tls/tls.go
Cherry-pick of #14435 forward to main
> fix: update TLS config to support ALPN. (#14435) (cherry-pick main)

- ui/src/shared/artifacts.ts
Fixes #14226 
Tested, UI displays fine in both scenario and is able to display artifact correctly
<details>
<summary>workflow with empty artifact</summary>
```
kind: Workflow
metadata:
generateName: input-artifact-s3-
spec:
entrypoint: input-artifact-s3-example
templates:
- name: input-artifact-s3-example
inputs:
parameters:
- name: path
value: ""
artifacts:
- name: my-art
path: /my-artifact
s3:
key: "{{inputs.parameters.path}}"
optional: true
container:
image: debian:latest
args: ["echo hello world"]
```
</details>
workflow with actual artifact
https://github.com/argoproj/argo-workflows/blob/14121-actor-label-email-fix/examples/artifact-passing.yaml
> fix: ui render with empty artifact

- .golangci.yml
- pkg/apiclient/http1/server-sent-events-client.go
- pkg/apis/workflow/v1alpha1/container_set_template_types.go
- pkg/apis/workflow/v1alpha1/workflow_types.go
- workflow/artifacts/gcs/gcs.go
- workflow/artifacts/raw/raw.go
- workflow/sync/lock_name.go
Fixes #14405 - part 1
This change fixes ST1016 linting issue and enables it again
Updated all the affected files.
CI
> fix: Fix ST1016 linting issue. Fixes #14405

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/regression.yaml
github has a new type system that we can use instead of the labels 
https://docs.github.com/en/issues/tracking-your-work-with-issues/configuring-issues/managing-issue-types-in-an-organization
* updates the issue templates to use types instead of labels
n/a
n/a
> chore: update issue templates to use types instead of labels

- docs/synchronization.md
Just some documentation updates around multiple controller locks.
> docs: improve synchronization docs

- docs/releasing.md
I was talking through the releasing of workflows with @isubasinghe and decided this was best done in formal docs, hence this.
Explain the feature release process as I see it.
`make docs` and checking CI docs here
This is a documentation only change
> docs: document feature releases

- util/errors/errors.go
etcd was only under pressure for a moment, but it quickly returned to normal.
```
time="2025-06-30T22:06:32.226Z" level=info msg="Alloc=7778 TotalAlloc=16916 Sys=23653 NumGC=6 Goroutines=9"
time="2025-06-30T22:06:32.251Z" level=warning msg="Non-transient error: etcdserver: too many requests"
time="2025-06-30T22:06:32.251Z" level=error msg="executor error: etcdserver: too many requests"
time="2025-06-30T22:06:32.252Z" level=info msg="Deadline monitor stopped"
```
> fix: add etcd too many requests transient.

- .github/workflows/pr.yaml
Increase the checkout depth for https://github.com/argoproj/argo-workflows/actions/runs/16131368362/job/45519315561?pr=14527 - speculative fix
> fix: do PR check with some depth for merge-base

- workflow/controller/operator.go
A fix for the changed signature of Info in #14527 for a line introduced in #14625
> fix: merge collision fix

- cmd/argo/commands/template/get.go
- docs/cli/argo_template_get.md
Fixes #11898 
Modify the argo template get command for more information
Added examples for the argo template get command.
run `argo template get -h`
> docs(cli): add examples for `argo template get` with option explanations

- cmd/argo/commands/template/delete.go
- docs/cli/argo_template_delete.md
Fixes #11898 
Add detailed outputs that include command options when running the `argo template delete` command.
* `cmd/argo/commands/template/delete.go` - Added Examples to the `argo template delete` command help.
* `docs/cli/argo_template_delete.md` - Updated docs to include those examples.
RUN `argo template delete --help`
> docs(cli): add usage examples for `argo template delete`

- workflow/sync/multi_throttler.go
Only remove when pending namespace queue exists, avoid panic.
Fixes #14669
> fix: only remove when pending namespace queue exists. Fixes:#14669

- workflow/cron/operator.go
Cherry-pick of #14713 to release-3.7
> fix: cron patch use defaultRetry. Fixes #14712 (#14713)

- util/telemetry/instrument.go
- util/telemetry/operators.go
- workflow/metrics/metrics_custom.go
…#14700)
(cherry picked from commit 14a58fb27e6280be50a2bc126381f42924e3d0fb)
Cherry pick of #14700 to release-3.7
> fix: use Float64ObservableCounter for counter metrics. Fixes #14425 (#14700)

- ui/src/workflows/components/submit-workflow-panel.tsx
Fixes #14704
Fixes #14734
Workflow submit no longer discards the enum
```
metadata:
name: test
spec:
entrypoint: print-message
arguments:
parameters:
value: test1
enum:
- test1
- test2
templates:
- name: print-message
container:
image: busybox
command: ["echo"]
args: ["{{workflow.parameters.message}}"]
```
> fix: submit workflow template with enum. Fix #14704

- ui/src/shared/components/editors/workflow-parameters-editor.tsx
Fixes #14550
The update request now populates the ValueFrom, if available.
> fix: cronworkfow update via UI when parameter is using valueFrom. Fixes #14550

- config/controller.go
- workflow/controller/controller.go
(cherry picked from commit https://github.com/argoproj/argo-workflows/commit/d9ea1e82a82f6f21210cce44c2880e650ef4cee3)
> fix: watch for dynamic changes to the Controller ConfigMap in its installation namespace. Fixes #14673 (#14675) (release-3.6)

- OWNERS
See https://github.com/argoproj/argoproj/pull/380. 
Congratulations! @blkperl Thank you for your contributions!
> chore: Add @blkperl to reviewers in OWNERS file

- workflow/artifacts/s3/s3.go
> fix: S3 artifacts failing with missing region when using roleARN

- workflow/util/util.go
Cherry-picked fix: only reset failed or error retry node. Fixes #14796 from #14803
> fix: only reset failed or error retry node. Fixes #14796 (cherry-pick release-3.7)

- util/errors/errors.go
When the wait container encounters this error due to high API server pressure, the workflow may become stuck forever.
```
responseObject:{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: request did not complete within requested timeout - context canceled","reason":"Timeout","details":{},"code":504}
responseStatus:{"metadata":{},"status":"Failure","message":"Timeout: request did not complete within requested timeout - context canceled","reason":"Timeout","details":{},"code":504}
```
Add retries to prevent update failures.
> fix: retry when occasionally timeout. 

- OWNERS
https://github.com/argoproj/argoproj/issues/356
> chore: add @masonm to owners files.
