argoproj/argo-workflows

.argo/test-yamls/fixtures-dynamic.yaml, saas/axops/src/applatix.io/axops/service/preprocess.go, saas/common/src/applatix.io/template/param.go, saas/common/src/applatix.io/template/workflow.go
This change restores support for capturing output artifacts from dynamic fixtures, which was broken during the YAML redesign.
=> Issue #8: Support capturing output artifacts from dynamic fixtures

saas/axops/src/applatix.io/axops/secret.go, saas/axops/src/applatix.io/axops/secret/secret.go, saas/axops/src/applatix.io/axops/tool.go, saas/axops/src/applatix.io/axops/tool/interface.go, saas/axops/src/applatix.io/axops/tool/schema.go, saas/axops/src/applatix.io/axops/tool/tool.go, saas/axops/src/applatix.io/axops/tool/utils.go, saas/axops/src/applatix.io/axops/utils.go
- Try to avoid the way we are using a pointer field to point the struct itself.
=> Clean up axops/tool

platform/source/lib/ax/platform/minion_manager/cloud_provider/aws/aws_bid_advisor.py
The lock is already acquired.
Testing Done:
1. Without this change, the minion-manager hangs while switching from
on-demand to spot instances.
2. With this change, the switch happened successfully.
Closes #10
=> Do not acquire lock in get_spot_instance_price().

saas/axops/src/ui/src/app/common/template-viewer/template-viewer.component.ts, saas/axops/src/ui/src/app/common/template-viewer/template-viewer.html, saas/axops/src/ui/src/app/common/template-viewer/template-viewer.scss, saas/axops/src/ui/src/app/views/+service-catalog/service-history/service-history.component.ts, saas/axops/src/ui/src/app/views/+service-catalog/service-history/service-history.html, saas/axops/src/ui/src/app/views/+service-catalog/service-history/service-history.scss, saas/axops/src/ui/src/app/views/+timeline/job-details/job-details.scss
Templates history screen - "YAML" button is not floating anymore. Adjust yaml panel be able to scroll to the end of yaml.
Job details screen - adjust yaml panel body to fill full height of panel.
=> Yaml panel adjusting.

common/python/ax/cluster_management/app/cluster_upgrader.py
we should not set upgrade_kube and upgrad_service to False if user specifies `--force-upgrade`
Tested upgrading cluster to same version with --force-upgrade, it worked
Fixes #33
=> Issue #33: fix force-upgrade semantics

common/python/ax/cluster_management/app/cluster_upgrader.py
Fixes #32 
This is not caught, probably because I was using a very old shell that has this environment variable already.
We need this environment variable as this is used by master manager.
Verified that AX_TARGET_CLOUD is set in upgrade-kubernetes.sh env, and upgrade went through
=> Issue #32: export AX_TARGET_CLOUD to upgrade-kubernetes.sh

.argo/test-yamls/pod-throughput-test.yaml, platform/source/lib/ax/platform/axmon_main.py, platform/source/lib/ax/platform/pod.py, platform/source/lib/ax/platform/rest.py, platform/source/lib/ax/platform/task.py
This change is to axmon to generate a Pod spec for Tasks instead of
generating a Job spec. It will now be up to workflow executor and
workflow ADC to ensure that tasks that did not complete due to node
failure or other conditions are restarted.
=> Change Tasks to use Kubernetes Pods instead of Jobs (#41)

.argo/test-yamls/argo-stress-test.yaml
Fixes #2 
All yaml checkers passed:
```
[.argo/test-yamls/argo-stress-test.yaml]
- OK    Applaix Stress Every 20 minutes #1
- OK    Applaix Stress Every 20 minutes #2
- OK    Applaix Stress Every 20 minutes #3
- OK    Applaix Stress Every 20 minutes #4
- OK    Applaix Stress Every 20 minutes #5
- OK    Applaix Stress Every 30 minutes
- OK    Applaix Stress Every Hour
- OK    Applaix Stress Every 2 Hours
- OK    Applaix Stress Every 10 Minutes
- OK    Applaix Stress Every 5 Minutes #1
- OK    Applaix Stress Every 5 Minutes #2
- OK    Applaix Stress Every 5 Minutes #3
- OK    Applaix Stress Every 5 Minutes #4
- OK    Applaix Stress Every 5 Minutes #5
- OK    Applaix Stress Every 1 Minutes #1
- OK    Applaix Stress Every 1 Minutes #2
- OK    Applaix Stress Every 1 Minutes #3
- OK    Applaix …
```
=> Issue #2: add back argo-stress-test.yaml with yaml new design

saas/axops/src/applatix.io/axops/policy.go, saas/axops/src/applatix.io/axops/policy/policy.go, saas/axops/src/applatix.io/axops/policy/policy_test.go, saas/axops/src/applatix.io/axops/policy/schema.go, saas/axops/src/applatix.io/axops/policy_test.go, saas/axops/src/applatix.io/axops/yaml/gc.go, saas/axops/src/applatix.io/axops/yaml/ingest.go
This change changes `enabled` to be a simple bool instead of bool pointer -- not sure why it was originally made a pointer. Also the embedded template can be made a non-pointer.
=> Issue #71: policy struct simplifications: remove bool pointer and template pointer

saas/axdb/BaseDockerfile, saas/axdb/Dockerfile, saas/axdb/base-install.sh, saas/axdb/preDockerBuild.sh, saas/tests/luceneindex/Dockerfile, saas/tools/BaseDockerfile, saas/tools/KafkaTestDockerfile, saas/tools/base-install.sh, saas/tools/kafka/Dockerfile, saas/tools/preDockerBuild.sh, saas/tools/rest-proxy/Dockerfile, saas/tools/schema-registry/Dockerfile, saas/tools/zookeeper/Dockerfile
This commit reduces container sizes. Two major side effects.
- Base linux container is upgraded from 8.5 to 9.1. Upstream 9.1 is smaller than 8.5.
- Old JDK/JRE 8u71 is not available from Oracle any more. Upgrade to 8u144.
Other changes include:
- Move install code to separate script. This creates single layer so that cleanup is easier.
- Add extra cleanup to remove unnecessary deb packages, maven build cache (100MB), all documentations, jdk source code, pyc files, all of which take anywhere from 10MB+ to 100MB+.
End result:
axdb: 1.4GB -> 583MB
kafka: 1.09GB -> 639MB
zookeeper: 1.09GB -> 639MB
=> Issue #28: Reduce axdb, zookeeper and kafka container sizes.

.argo/test-yamls/aws-s3-regional-test.yaml, common/python/ax/cloud/aws/aws_s3.py, platform/tests/aws_s3/mock.py, platform/tests/aws_s3/test_aws_s3.py, platform/tests/aws_s3/testdata.py
Fixes #30 , so we can get region reliably in gov regions.
Forced sigV4 to get bucket region. There are standalone s3 code in devops codebase and saas codebase, but since they did not go wrong in sigv4 only regions and we cannot test them in gov cloud regions, I'm not changing them
All s3 tests passed reliably
=> Issue #30: enforce signature V4 to get bucket region

common/python/ax/cloud/aws/__init__.py, common/python/ax/cloud/aws/consts.py, common/python/ax/cloud/aws/util.py, platform/cluster/aws/util.sh, platform/source/lib/ax/platform/ax_master_manager.py, platform/source/lib/ax/platform/ax_minion_upgrade.py, platform/source/lib/ax/platform/cluster_buckets.py, platform/source/lib/ax/platform/cluster_instance_profile.py, platform/source/tools/ax-upgrade-misc.py
Fixes #45 
When creating IAM role / bucket policy, we need to dynamically generate policy string based on aws partition.
Tested install and upgrade and they worked
=> Issue #45: get aws partition based on region

platform/cluster/saltbase/salt/docker/init.sls
This is fundaentally bad bootstrap script from kube-up. It starts docker/kubelet in the same time when docker graph storage is configured and all salt configurations are updated. There is always
race among these initialization steps.
Kube-up calls salt and doesn't restart docker afterwards on AWS and instead let docker health checker to detect and restart. Because of race, docker health checker sometimes misses this too. Docker daemon ended up with old generic options rather than ones provided by salt. Docker daemon responded to `docker info` and `docker ps` call but wouldn't start any containers as it's told to use device mapper as graph storage but underlying storage is overlay2.
The correct fix would be using systemd in right way to define dependencies among OS booting, network config, …
=> Issue #90: Hack to force restart docker after salt call.

platform/cluster/saltbase/salt/kubelet/kubelet-healthcheck
Removed Pod IP address leak check as it has already been fixed:
https://github.com/kubernetes/kubernetes/pull/37036
kubelet healthcheck constantly ping kubelet healthz endpoint, if it failed, try to restart kubelet.
Tested healthcheck by manually call `systemctl stop kubelet`:
```
Aug 30 00:39:35 ip-10-128-1-9 systemd[1]: Starting Run kubelet-healthcheck once...
Aug 30 00:39:35 ip-10-128-1-9 [kubelet-healthcheck]: Kubelet not healthy, sleeping for 90 seconds for it to recover
Aug 30 00:39:45 ip-10-128-1-9 kubelet-healthcheck[14744]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Aug 30 00:39:45 ip-10-128-1-9 kubelet-healthcheck[14744]: Dload  Upload   Total   Spent    Left  Speed
Aug 30 00:39:45 ip-10-128-1-9 [kubelet-healthcheck]: Kubelet still not healthy, …
```
=> Issue #96 restart kubelet if kubelet is not healthy

common/python/ax/aws/meta_data.py
The class is a generic client to get AWS metadata, so it should not assert pod/kube host.
=> Issue #125: AWSMetaData class should not assert on_kube_host or in_pod

devops/src/ax/devops/workflow/adc_main.py, devops/src/ax/devops/workflow/ax_workflow_executor.py
- As containers are running as pod instead of job (#41), ADC becomes the only entity that can restart a failed workflow executor (WFE). Currently the revival thredhold is set as 10 min which is too high. The change is changing the threhold to 1 min and sending heartbeat every 30 seconds from WFE to ADC.
=> Issue #95: ADC takes a long time to revive WFE

common/python/ax/aws/meta_data.py, common/python/ax/util/network.py
Once assertion at AWS meta is removed, get_public_ip would return invalid IP if it runs on EC2 instance without external IP. Raise exception if that is case. Also make sure same thing is doen for external servers.
=> Issue #125: Need to fix get_public_ip to raise exception.

bash-helpers.sh
Makes it easier to describe pods.
=> Use pod short-names for kdesc.

saas/axops/src/ui/src/app/views/+config-management/config-management-panel/config-management-panel.component.ts
Update validators in the add configuration form. Value shouldn't have any restrictions.
Fixes #133
=> Issue 133: Configuration Management - update validators. 

saas/axops/src/ui/src/app/common/volumes-list/volumes-list.component.ts, saas/axops/src/ui/src/app/views/+fixtures/fixture-classes/fixture-classes.component.ts, saas/axops/src/ui/src/app/views/+fixtures/fixture-instances/fixture-instances.component.ts, saas/axops/src/ui/src/app/views/+volumes/volume-edit-panel/volume-edit-panel.component.ts, saas/axops/src/ui/src/app/views/+volumes/volume-edit-panel/volume-edit-panel.html, saas/axops/src/ui/src/app/views/+volumes/volumes-overview/volumes-overview.component.html, saas/axops/src/ui/src/app/views/+volumes/volumes-overview/volumes-overview.component.ts
Added edit option to Volumes main page. Adjusted dropdown actions for Volumes and Fixtures screens.
Fixes #140 
@alex please take a look at the Rahuls comment in issue. If you can describe me when reassign should be visible. I'll update this PR accordingly:
> - Display reassign only when it's applicable. @alexmt we have discussed those usecases in the past.
=> Issue 140: Missing action options

.argo/argo-platform-unit-tests.yaml, common/python/ax/cloud/aws/aws_s3.py, common/python/ax/cloud/gke/gcs.py, common/python/ax/cluster_management/app/cluster_installer.py, common/python/ax/cluster_management/app/cluster_pauser.py, common/python/ax/cluster_management/app/cluster_restarter.py, common/python/ax/cluster_management/app/cluster_uninstaller.py, common/python/ax/cluster_management/app/cluster_upgrader.py, common/python/ax/cluster_management/app/common.py, common/python/ax/cluster_management/app/state/__init__.py, common/python/ax/cluster_management/app/state/consts.py, common/python/ax/cluster_management/app/state/state.py, common/python/ax/cluster_management/argo_cluster_manager.py, common/python/ax/meta/config_s3_path.py, platform/source/lib/ax/platform/ax_cluster_info.py, platform/tests/cluster_state_machine/mock.py, platform/tests/cluster_state_machine/test_cluster_state_transition.py
Resolves #146 
Implemented a state machine mechanism to ensure cluster management operations to be triggered correctly. Added unit tests for state machine, also separated cluster management operations into pre_run, run, and post_run stages.
=> Issue #146: add cluster state machine to ensure cluster management operations can be triggered properly

.argo/argo-platform-unit-tests.yaml
Fixes #202 Looks like there is a python3 incompatibility with the test. Unit test should run under python2 environment. The added module is used for argocluster command only and currently it runs only under python2 so it's fine.
Unit test is now passed. https://dev.applatix.net/app/timeline/jobs/8074e6a6-976a-11e7-89cf-0a58c0a88335;tab=workflow
=> Issue #202: fix broken cluster state machine unit test

platform/containers/prometheus/run.sh
The idea is to clear the data folder when there is a crash happens.
=> Issue #191: prometheus-deployment crash in stress testing

common/python/ax/cluster_management/app/cluster_pauser.py, common/python/ax/cluster_management/app/cluster_restarter.py, common/python/ax/cluster_management/app/cluster_uninstaller.py, common/python/ax/cluster_management/app/cluster_upgrader.py, common/python/ax/meta/config_s3_path.py, platform/source/lib/ax/platform/ax_cluster_info.py
Resolves #145 
When a cluster is registered to portal, portal is going to put a flag in its s3 bucket. argocluster CLI is checking this flag, if set, it aborts operation from CLI. Verified that CLI is aborted by manually setting the flag in S3
=> Issue #145: argocluster CLI should abort operation if the cluster is supported by portal

.argo/argo-platform-unit-tests.yaml, platform/source/lib/ax/platform/ax_asg.py, platform/source/lib/ax/platform/minion_management/spot_instance_option_manager.py, platform/source/lib/ax/platform/minion_manager/README.md, platform/source/lib/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py, platform/source/lib/ax/platform/rest.py, platform/tests/spot_instance_option_manager_test.py
Testing Done:
1. Added unit tests for spot-instance-option-manager
2. Also verified that the AXMON APIs for get/put of the spot-instance config options work as expected.
Closes #176.
=> Return correct spot-instance option from axmon REST API.

common/python/ax/cluster_management/app/cluster_uninstaller.py, common/python/ax/cluster_management/app/cluster_upgrader.py, common/python/ax/cluster_management/app/options/common.py, common/python/ax/cluster_management/app/options/install_options.py, platform/cluster/aws/util.sh, platform/source/lib/ax/platform/kube_env_config.py, platform/source/tools/ax-upgrade-misc.py, platform/source/tools/master_manager.py, platform/source/tools/upgrade-kubernetes.sh
Fixes #17 
We need to set profile to None (NoneType) if user does not provide one, in this case, we fully leaves boto3 client to figure out credentials.
Tested all cluster operations without specifying cloud profile
=> Issue #17: take None as a valid cloud profile

common/python/ax/cluster_management/app/options/__init__.py, common/python/ax/cluster_management/app/options/common.py, common/python/ax/cluster_management/app/options/install_options.py, common/python/ax/cluster_management/argo_cluster_manager.py, platform/config/service/basic/access-key-secret.yml.in, platform/config/service/basic/axartifactmanager-svc.yml.in, platform/config/service/basic/axdb-svc.yml.in, platform/config/service/basic/axmon-svc.yml.in, platform/config/service/basic/axops-internal-svc.yml.in, platform/config/service/basic/axops-svc.yml.in, platform/config/service/basic/axops.yml.in, platform/config/service/basic/axsys-namespace.yml.in, platform/config/service/basic/axuser-namespace.yml.in, platform/config/service/basic/axworkflowadc-svc.yml.in, platform/config/service/basic/gateway-pvc.yml.in, platform/config/service/basic/gateway-svc.yml.in, platform/config/service/basic/kafka-zk-pvc.yml.in, platform/config/service/basic/kafka-zk-svc.yml.in, platform/config/service/basic/redis-pvc.yml.in, platform/config/service/basic/redis-svc.yml.in, platform/config/service/basic/registry-secrets.yml.in, platform/config/service/basic/registry-svc.yml.in, platform/config/service/basic/secret-key-secret.yml.in, platform/config/service/config/basic-platform-bootstrap.cfg, platform/source/lib/ax/platform/cluster_config/consts.py, platform/tests/install_options_tests.py
In this commit, simply the PlatformOnlyInstallConfig object is created.
In subsequent commits, more functionality will be added to this for
actually installing Argo.
Added unit-tests related to PlatformOnlyInstallConfig.
Also tested manually. install-platform-only does nothing right now.
Simply logs a message and exits.
=> Create PlatformOnlyInstallConfig and related objects.

common/python/ax/cluster_management/app/__init__.py, common/python/ax/cluster_management/app/cluster_installer.py, common/python/ax/cluster_management/app/options/install_options.py, common/python/ax/cluster_management/argo_cluster_manager.py, platform/config/cloud/standard/cloud_template_user_provided.json, platform/source/lib/ax/platform/ax_cluster_info.py, platform/source/lib/ax/platform/cluster_config/__init__.py, platform/source/lib/ax/platform/cluster_config/cluster_config.py, platform/source/lib/ax/platform/cluster_config/consts.py, platform/tests/install_options_tests.py
The run() method of the PlatformOnlyInstaller object will actually
install Argo components.
Testing done:
1. Modified the install_options_test and they run.
2. Verified that existing cluster installation is unaffected.
=> Create PlatformOnlyInstaller object.

common/python/ax/cluster_management/argo_cluster_manager.py, common/python/ax/meta/cluster_id.py, common/python/ax/meta/config_s3_path.py, devops/src/ax/devops/gateway/gateway.py, platform/source/lib/ax/platform/container_specs.py
This is based on the user provided bucket name when installing
Argo on user provided clusters.
=> Add ARGO_LOG_BUCKET_NAME and  ARGO_DATA_BUCKET environment variable.

platform/source/lib/ax/platform/container_specs.py
Testing Done:
1. The dind-test-wf workflow hangs without this change. The description
of the pod shows that docker-graph-storage has type "unknown".
2. With this change, the docker-graph-storage volume has type EMPTYDIR
and the workflow completes successfully.
=> Use EMPTYDIR for dind only for non-aws environments.

common/python/ax/cloud/aws/aws_s3.py, devops/src/ax/devops/artifact/artifactmanager.py, platform/config/service/argo-wfe/axops-svc.yml.in, platform/config/service/argo-wfe/s3proxy.yml, platform/source/lib/ax/platform/sidecar/log_collector.py, platform/source/tools/container_outer_executor.py, saas/axops/src/applatix.io/axops/s3.go
- manifest for s3proxy
- for minikube expose 8082 port for axops since https with minikube has some issues
- s3 features like server side encryption and acl are not used when cloud is minikube 
- s3 signed url feature is used only when cloud is aws
resolves: #312
=> changes to artifact management to support any s3 compliant object store

platform/config/service/argo-wfe/kafka-zk-svc.yml.in
=> use headless service for kafka in minikube

platform/config/service/config/argo-wfe-platform-bootstrap.cfg, platform/source/lib/ax/platform/task.py
Without these, the init containers are not able to download artifacts.
=> Add S3 cred overrides to init containers.

common/python/ax/aws/meta_data.py
Without this, installation of Argo on minikube without specifying
"--cloud-region" failed. With this, the installation went smoothly.
=> Return "unknown-region" if not running in AWS.

devops/src/ax/devops/scm/factory.py
Resolves: https://github.com/argoproj/argo/issues/365
=> argo-checkout should fallback to passwordless mode if axops API is not available

platform/source/lib/ax/platform/application.py
This makes it possible to identify namespaces created by Argo and only
operate on those. e.g. during installation or upgrade.
Testing done:
1. Scripted code for creation, listing and deletion of namespaces.
Worked as expected.
=> Add labels to Argo created namespaces.

common/python/ax/cloud/aws/aws_s3.py, common/python/ax/cluster_management/app/options/install_options.py, common/python/ax/cluster_management/argo_cluster_manager.py
1. Make cluster-bucket optional for minikube. And mandatory for AWS.
2. Create Cloud object early.
3. Make cluster-name mandatory.
4. Ignore get_region exceptions is boto client can't be created.
=> Misc. fixes to install argo-only.

platform/source/lib/ax/platform/cluster_version.py
This should be safe to do since the ACL mentioned in the code is the
same as the default ACL set by AWS [1].
Having the explicitl ACL is not good for S3 proxy. S3proxy barfs on a
put_object call when the ACL is specified.
[1] http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html
=> Remove explicit ACLs when installing cluster_version.

platform/config/service/config/argo-all-platform-bootstrap.cfg
This allows creation and use of volumes in Applications.
Closes #383.
=> Run fixturemanager when installing "argo-all".

platform/source/lib/ax/platform/container_specs.py
The FlexVolume plugin is not present on user-provided kubernetes
clusters. Therefore, it should not use the DOCKERGRAPHSTORAGE type.
Testing done:
1. Without this change, a "dind" workflow simply stalls in the init
state becuase the volume is not resolved.
With this change, the dind workflow ran and completed successfully.
=> Use EMPTYDIR on user-provided clusters.

common/python/ax/kubernetes/client.py, saas/argocli/src/applatix.io/argo/cmd/cluster.go
This change does two things:
1) During `argo cluster`, additionally mounts the user's home directory to the same location inside axclustermanager
2) Adds the ability to authenticate using client certificates to the python kubernetes client (both in the swagger api client and the requests session)
Combined, this enables argocluster to install minikube without the extra step of inline certificates and generating the token field.
=> Support minikube install without inlining certificates

Gopkg.lock, Gopkg.toml, api/workflow/v1/types.go, cmd/argoexec/commands/artifacts.go, cmd/argoexec/commands/root.go, examples/input-artifact-s3.yaml, examples/install.yaml, workflow/artifacts/artifacts.go, workflow/artifacts/s3/s3.go, workflow/common/common.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
- Argo executor init container first commit
- Init container is responsible for downloading input artifacts for the user container
- Reading the Kubernetes downward api to interpret the workflow template (annotation file)
- Using minio go sdk to support private (minio), aws s3 and google api.
=> Argo Executor init container

api/workflow/v1/types.go, cmd/argoexec/commands/root.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
Adds a field in template to indicate the archive path for all step level artifacts. Populated by default in the controller, but can be overridden in template manifest. Teach executor to understand and handle the archive location, enabling users to override where their artifacts should reside.
=> Introduce Template.ArchiveLocation to store all related step level artifacts to a job, understood by executor

cmd/argo/commands/list.go, cmd/argoexec/commands/root.go, cmd/argoexec/commands/sidecar.go, workflow/controller/controller.go, workflow/executor/executor.go
Restores the functionality of executor killing a sidecar as part of the `wait` command
=> Restore and formalize sidecar kill functionality as part of executor

api/workflow/v1/types.go, cmd/argoexec/commands/artifacts.go, examples/output-parameter.yaml, workflow/executor/executor.go
- Output as parameter will get content from a user-specified file and save as output parameter
- The parameter then can be referenced from the later steps
=> Add support for output as parameter

util/cmd/cmd.go
The IsURL check simply called url.ParseRequestURI and relied on whether it errors
or not to detect whether the given string is a url or not. Turns out that
url.ParseRequestURI does not error out if the given string is a complete
filesystem path /path/to/file.
This commit hardens the IsURL check. It checks whether the returned URL object
by url.ParseRequestURI() has an actual Host component or not. If not, isURL returns
false.
Testing Done:
* argo submit failed with a full-path prior to this change. Worked after.
* argo submit succeeded with a url before and after.
Refs #509.
=> Harden the IsURL check

Gopkg.lock, Gopkg.toml, cmd/argo/commands/install.go
This commit checks whether the Kubernetes version is >= v1.8
It fails the installation otherwise.
Testing Done:
* Verified the version check succeeds for v1.8
* Verified that the version check fails for v1.7
Refs #473
=> Check Kubernetes version.

cmd/argo/commands/const.go, cmd/argo/commands/install.go, cmd/argo/commands/uninstall.go
If Argo specific clusterRoleBinding and serviceAccount were
created during install, they should get deleted on uninstall. This
commit does just that.
Testing Done:
* Verified that clusterRoleBinding and serviceAccount get deleted.
=> Delete clusterRoleBinding and serviceAccount.

examples/fun_with_gifs.yaml
This commit adds an example of processing gifs using ImageMagick and gifsicle.
The workflow creates a PVC that is used for locally storing the downloaded
images and then running 'convert' and 'gifsicle' on these images.
The output gets written in the PV itself in a "output" directory. This directory
is then considered as an artifact and uploaded to the cloud.
=> Add example of GIF processing using ImageMagick

errors/errors_test.go, test/e2e/e2e_test.go, test/e2e/install_test.go, workflow/common/validate_test.go
```
$ go test -v ./...argo list
can't load package: package list: cannot find package "list" in any of:
/usr/local/Cellar/go/1.9.2/libexec/src/list (from $GOROOT)
/Users/shri/ws/go/src/list (from $GOPATH)
shri@argo:[13:56](gke) go test -v ./...
shri@argo:[13:56](gke) go test -v ./...
?       github.com/argoproj/argo    [no test files]
?       github.com/argoproj/argo/api/workflow/v1alpha1    [no test files]
?       github.com/argoproj/argo/apiserver    [no test files]
?       github.com/argoproj/argo/apiserver/schema    [no test files]
?       github.com/argoproj/argo/cmd/argo    [no test files]
?       github.com/argoproj/argo/cmd/argo/commands    [no test files]
?       github.com/argoproj/argo/cmd/argo-apiserver    [no test files]
?       github.com/argoproj/argo/cmd/argoexec    [no …
```
=> Fix tests.

Gopkg.lock, errors/errors.go, workflow/client/client.go, workflow/controller/controller.go, workflow/controller/operator.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
1. Switch to using SharedIndexInformer to provide shared resource
state with other controllers.
2. Use workqueue in lieue of channels which prevents work backlog,
stale state, true concurrency, and enable future improvements
such as rate limited retry and backoff.
3. Add ability to PATCH workflows to prevent errors related to having
too old resource versions.
4. Pod updates no longer result in an 1:1 workflow update and instead
adds the workflow name back to the workqueue. This allow database
updates to be batched in a single db update.
=> Multiple scalability improvements to controller

test/e2e/e2e_test.go, test/e2e/install_test.go, test/e2e/workflow_test.go
This will make it possible to run "go test" without having to configure a Kubernetes
cluster.
=> Skip e2e tests if Kubeconfig is not provided.

.argo/build.yaml, .argo/checkout.yaml, Dockerfile-ci-builder, Makefile, ui/Dockerfile, ui/Dockerfile.builder
PR contains argo v1 build template. Argo v1 dind uses docker version which does not support multi-stage builds. Due to this limitation, I had to stop using multi-stage builds it 'ui-image' make step and updated make file accordingly. 
Successfully build example: https://argo-v1.applatix.net/app/timeline/jobs/e64b164c-dd7d-11e7-af7b-0a58c0a88113
=> Issue #549 - Prepare argo v1 build config

cmd/argo/commands/const.go, cmd/argo/commands/install.go, cmd/argo/commands/uninstall.go
This updates the installer and uninstaller to create & delete the UI service as part of install/uninstall.
=> Create the argo-ui service with type ClusterIP as part of installation (resolves #582)

.argo/build.yaml, api/workflow/v1alpha1/workflow.go, cmd/argo/commands/common.go, cmd/argo/commands/get.go, cmd/argo/commands/install.go, cmd/argo/commands/list.go, cmd/argo/commands/logs.go, cmd/argo/commands/submit.go, cmd/argoexec/commands/root.go, cmd/workflow-controller/main.go, errors/errors.go, gometalinter.json, workflow/common/util.go, workflow/common/validate.go, workflow/controller/controller.go, workflow/controller/operator.go, workflow/controller/workflowpod.go, workflow/executor/executor.go
Running:
```
$ make lint
```
Now produces zero errors. This should give us an A+ on the golang report card so we can add a badge to our README.md.
The following linters are enabled:
"vet",
"gofmt",
"deadcode",
"errcheck",
"varcheck",
"structcheck",
"ineffassign",
"unconvert"
=> Address all issues in code caught by golang linting tools (resolves #584)

.dockerignore, Makefile, workflow/common/validate_test.go
The Makefile no longer assumes that the project root is in a valid GOPATH _**when performing builds in a docker container**_. It must still be in a valid GOPATH when running native golang build targets (non-docker) like `make cli`, `make controller`, `make executor`.
Also added a `make test` target, which will be added to CI.
=> Fix some wrong GOPATH assumptions in Makefile. Add `make test` target. Fix unit tests

Makefile, cmd/argo/commands/install.go, cmd/argoexec/commands/root.go, util/cmd/cmd.go, version.go, workflow/common/common.go, workflow/controller/controller.go
The `argo version` will now produce the following output:
Version output at a git tag (with the tag being v2.0.0-alpha3):
```
$ argo version
argo: v2.0.0-alpha3
BuildDate: 2017-12-14T22:52:36Z
GitCommit: f955deacc638b67b9be10fdac0c371ca705cd218
GitTreeState: clean
GitTag: v2.0.0-alpha3
GoVersion: go1.9.2
Compiler: gc
Platform: darwin/amd64
```
Version output at a commit with a clean git tree state:
```
$ argo version
argo: v2.0.0+f955dea
BuildDate: 2017-12-14T22:51:13Z
GitCommit: f955deacc638b67b9be10fdac0c371ca705cd218
GitTreeState: clean
GoVersion: go1.9.2
Compiler: gc
Platform: darwin/amd64
```
Version output at a commit with a dirty git tree state:
```
$ argo version
argo: v2.0.0+f955dea.dirty
BuildDate: 2017-12-14T22:56:16Z
GitCommit: f955deacc638b67b9be10fdac0c371ca705cd218 …
```
=> Comply with semantic versioning. Include build metadata in `argo version` (resolves #594)

cmd/argo/commands/get.go, cmd/argo/commands/submit.go
```
$ ./dist/argo submit examples/hello-world.yaml --output json
{
"metadata": {
"name": "hello-world-jgnhz",
"generateName": "hello-world-",
"namespace": "default",
"selfLink": "/apis/argoproj.io/v1alpha1/namespaces/default/workflows/hello-world-jgnhz",
"uid": "aaf4e8f2-e1f8-11e7-8dd9-42010a8a00c4",
"resourceVersion": "320353",
"creationTimestamp": "2017-12-16T00:32:59Z"
},
"spec": {
"templates": [
{
"name": "whalesay",
"inputs": {},
"outputs": {},
"container": {
"name": "",
"image": "docker/whalesay:latest",
"command": [
"cowsay"
],
"args": [
"hello world"
],
"resources": {}
}
}
],
"entrypoint": "whalesay",
"arguments": {}
},
"status": {
"phase": "",
"startedAt": null,
"finishedAt": null,
"nodes": null
}
}
$ ./dist/argo submit examples/hello-world.yaml
Name: …
```
=> Add option to print output of submit in json.

Gopkg.lock, api/workflow/v1alpha1/types.go, cmd/argo/commands/get.go, examples/exit-handlers.yaml, test/e2e/expectedfailures/exit-handler-failed.yaml, workflow/common/common.go, workflow/common/util.go, workflow/common/validate.go, workflow/common/validate_test.go, workflow/controller/operator.go
This resolves issue #495.
* Introduce spec.onExit field for specifying a template to run upon workflow completion
* Make {{workflow.name}} available as a global variable
* Make {{workflow.status}} available in the scope for exit handlers
* Simplify some of the workflow spec validation
Output from `argo get` with a workflow using exit handlers:
```
$ argo get exit-handlers-fpkb4
Name:             exit-handlers-fpkb4
Namespace:        default
Status:           Failed
Message:          failed with exit code 1
Created:          Sat Dec 16 05:59:41 -0800 (14 hours ago)
Started:          Sat Dec 16 20:33:31 -0800 (20 minutes ago)
Finished:         Sat Dec 16 20:33:43 -0800 (20 minutes ago)
Duration:         12 seconds
STEP                    PODNAME                         MESSAGE
✖ …
```
=> Support for workflow exit handlers

api/workflow/v1alpha1/types.go, examples/timeouts.yaml, workflow/controller/workflowpod.go
This adds the field `activeDeadlineSeconds` to the template spec which gets carried forward to the pod spec. This gives us kubernetes pod timeout for free. Below is an example of a 10s timeout enforced on a container which sleeps for 1 minute:
```
$ argo get timeouts-d4qhf
Name:             timeouts-d4qhf
Namespace:        default
Status:           Failed
Message:          Pod was active on the node longer than the specified deadline
Created:          Sat Dec 16 07:16:49 -0800 (17 hours ago)
Started:          Sat Dec 16 21:54:37 -0800 (2 hours ago)
Finished:         Sat Dec 16 21:54:47 -0800 (2 hours ago)
Duration:         10 seconds
STEP               PODNAME         MESSAGE
✖ timeouts-d4qhf  timeouts-d4qhf  Pod was active on the node longer than the specified deadline
```
=> Add ability to timeout a container/script using activeDeadlineSeconds

cmd/argo/commands/install.go, workflow/common/common.go, workflow/controller/controller.go, workflow/controller/workflowpod.go
This resolves issue #508.
This change introduces the concept of a user-defined controller "instance id." When set in the controller's configmap, the controller's workflow and pod watch will only see events from workflows/pods with the `workflows.argoproj.io/controller-instanceid` matching the supplied instance id.
When omitted (the default behavior), the workflow controller will only watch events from workflow/pods which *do not* have the `workflows.argoproj.io/controller-instanceid` label.
The end result is that we can now support multiple controllers per cluster, without necessarily tying a controller to a namespace. Perhaps more importantly, it enables the workflow controller to be bundled/packaged as part of a higher level application similar to how a database would.
=> Introduce controller instance IDs to support multiple workflow controllers in a cluster (resolves #508)

test/e2e/functional/script-with-input-art.yaml, workflow/common/util.go, workflow/controller/controller.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
This resolves issue #617.
Resolve controller panic when a script template with an input artifact was submitted.
Utilize the kubernetes.Interface and fake.Clientset to support unit test mocking.
Added a unit test to reproduce the panic. Add an e2e test to verify functionality works.
=> Resolve controller panic with script template and input artifact

Gopkg.lock, Makefile, api/workflow/v1alpha1/types.go, cmd/argoexec/commands/init.go, cmd/argoexec/commands/resource.go, cmd/argoexec/commands/root.go, examples/k8s-jobs.yaml, workflow/common/common.go, workflow/common/validate.go, workflow/common/validate_test.go, workflow/controller/operator.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go, workflow/executor/executor.go
This implements issue #606.
It introduces a new template type, resource, which has the following fields:
```
// ResourceTemplate is a template subtype to manipulate kubernetes resources
type ResourceTemplate struct {
// Action is the action to perform to the resource.
// Must be one of: create, apply, delete
Action string `json:"action"`
// Manifest contains the kubernetes manifest
Manifest string `json:"manifest"`
// WaitCondition is a label selector expression which describes the conditions
// of the k8s resource in which it is acceptable to proceed to the following step
WaitCondition string `json:"waitCondition,omitempty"`
// FailCondition is a label selector expression which describes the conditions
// of the k8s resource in which the step was considered failed
FailCondition string …
```
=> Implementation for resource templates and resource wait/fail conditions

CHANGELOG.md, cmd/argo/commands/common.go, cmd/argo/commands/install.go, cmd/argo/commands/uninstall.go, pkg/apis/workflow/register.go, pkg/apis/workflow/v1alpha1/register.go, pkg/apis/workflow/v1alpha1/types.go, workflow/common/common.go, workflow/common/createcrd.go, workflow/controller/operator.go, workflow/controller/workflowpod.go
This resolves issue #656.
When setting the ownership reference of a pod/pvc, we should also set the `controller: true`. Although this field is marked optional in the API, on at least one cluster it panics the k8s scheduler when left unset. I believe this to be a k8s bug. In general, I believe the controller should be set when applying ownership from the creator resource.
Also moved the CRD constants out of the v1alpha1 package, since they are constants that will not change from version to version.
=> Prevent a potential k8s scheduler panic from incomplete setting of pod ownership reference

examples/fun-with-gifs.yaml
Kubernetes doesn't guarantee any parallelism if two pods use the same volume. To avoid
confusion, this commit simply resorts to sequential steps.
=> Remove parallel steps that use volumes.

demo.md
I found this confusing when trying to reuse an existing minio deployment in a separate namespace.  Does this advice seem reasonable?  I think the behaviour is right, as it keeps secret handling simple, it just wasn't obvious to me.
Feel free to close and just take as docs feedback 😀
=> Clarify where the Minio secret comes from

cmd/argo/commands/const.go, cmd/argo/commands/install.go, cmd/argo/commands/uninstall.go, demo.md, test/e2e/e2e_test.go, workflow/common/common.go, workflow/common/util.go, workflow/controller/controller.go
This addresses issue #662.
It creates two new service accounts (argo and argo-ui) and ClusterRoles (argo-cluster-role and argo-ui-cluster-role) as part of install, These roles have the bare minimum privileges necessary to run the workflow-controller and argo-ui respectively.
@alexmt please review argo-ui cluster role and let me know if there are additional privileges needed by argo-ui that I am not aware of.
=> Use minimal ClusterRoles to be used by workflow-controller and argo-ui

cmd/argo/commands/list.go, examples/influxdb-ci.yaml
* sort workflows by finished time
* add --running, --completed, --status XXX filters
* add -o wide option to show parameters
Example output:
```
$ go run cmd/argo/main.go list -o wide
NAME                      STATUS      AGE    DURATION   PARAMETERS
hello-world-zjq7g         Pending     2m     1d
influxdb-ci-kpphp         Running     5m     5m         repo=https://github.com/influxdata/influxdb.git,revision=master
argo-ci-4jjwj             Running     5m     5m         revision=master,repo=https://github.com/argoproj/argo.git
influxdb-ci-5bssm         Failed      1d     1d
argo-ci-gqsrc             Failed      31m    12m        revision=master,repo=https://github.com/argoproj/argo.git
argo-ci-27v92             Succeeded   32m    13m …
```
=> Improvements to `argo list`

Gopkg.lock, cmd/argoexec/commands/root.go, examples/daemon-nginx.yaml, pkg/apis/workflow/v1alpha1/types.go, workflow/common/common.go, workflow/controller/operator.go, workflow/controller/steps.go, workflow/executor/executor.go, workflow/executor/resource.go
This change creates a downward communication channel from the controller to executor through
the use of pod annotations. Its initial use will be to terminate daemoned containers by
updating 'ExecutionControl' parameters to the executor. In this case, it updates the deadline
value to be a zero-value timestamp. The executor has been modified to now monitor updates to the annotations and will obey the updated deadline, allowing deadlines to be set/updated/unset after initial start.
In the future, ExecutionControl can be extended to support things like workflow, step, dag
level timeouts, as well as the ability to to cancel a workflow without deleting pods.
Resolves issue #499.
Partially implements support for #527.
=> Introduce communication channel from workflow-controller to executor through pod annotations

cmd/argoexec/commands/init.go, cmd/argoexec/commands/root.go, cmd/argoexec/commands/wait.go, cmd/workflow-controller/main.go, gometalinter.json, util/retry/retry.go, util/stats/stats.go, workflow/common/util.go, workflow/controller/controller.go, workflow/executor/executor.go
* add retries and memoization for executor k8s API calls
* recover from unexpected panics and annotate the error.
=> Executor hardening

workflow/controller/controller_test.go, workflow/controller/operator.go, workflow/controller/workflowpod.go
Resolves issue #686
Relying on a JSON merge patch to persist workflow updates has been shown to be unreliable.
This change switches us to use the Update mechanism, which may not be as performant, and
will on occasion cause the controller to redo work (upon resource conflicts), but it will
likely be more reliable way of persisting workflow resource changes.
=> Switch to Updating workflow resources instead of Patching 

cmd/argo/commands/install.go
k8s 1.8 has ClusterRole and ClusterRoleBinding in v1 version. Installation currently fails because these are not in the right versions. Fixing the issue.
=> Fix RBAC resource versions in install

workflow/artifacts/s3/s3.go
when using aws keys, an extra newline was being added to both
secret/access key. I could not figure out what was adding this newline,
and feel confident that I was not adding it during my base64 encoding
process, so I added a patch to remove newlines so that I could evaluate
argo with S3.
=> Trim spaces from aws keys

ARTIFACT_REPO.md
If you omit bucket region from your config and it is not residing in
us-east-1, the minio client fails with not-very-helpful errors: 400
error unless the aws policy: s3:GetBucketLocation is assigned to your
aws user.
This patch makes a note of this in the docs.
=> Add note about region discovery.

examples/README.md, examples/coinflip-recursive.yaml, examples/coinflip.yaml, examples/dag-coinflip.yaml, examples/k8s-orchestration.yaml, examples/loops-param-result.yaml, examples/parallelism-limit.yaml, examples/resubmit.yaml, examples/retry-container.yaml, examples/retry-with-steps.yaml, examples/scripts-python.yaml, test/e2e/functional/sidecar-volumes.yaml, test/e2e/stress/pod-limits.yaml, workflow/common/validate_test.go, workflow/controller/operator_test.go
Alpine based python image is 8x times smaller, so it is reasonable to use it
instead of giant debian/jessie one.
docker.io/python    3.6                 336d482502ab        9 days ago          692 MB
docker.io/python    alpine3.6           78d64a211a65        6 weeks ago         83.8 MB
=> examples: use alpine python image

ARTIFACT_REPO.md, workflow/artifacts/s3/s3.go, workflow/executor/executor.go
**What**
- When static credentials are not provided in the configmap or workflow configuration, fetch credentials for IAM role from EC2 endpoint.
**Why**
Provide flexibility in configuring S3 credentials.
Addresses https://github.com/argoproj/argo/issues/786
**Testing**
Given the current implementation, unit testing is not possible without a significant refactoring of the S3 driver to allow for dependency injection.
All current UTs pass.
Locally, testing may be performed by deploying https://github.com/jtblin/aws-mock-metadata configured with `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN` (if expiring credentials are being used).
=> Add ability to use IAM role from EC2 instance for AWS S3 credentials

workflow/controller/workflowpod.go
Fix for #803 
Using right hostPath type related to https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
=> Use socket type for hostPath to mount docker.sock

pkg/apis/workflow/v1alpha1/types.go
Primary motivation is to avoid an empty string phase value, which is
awkward to map to JSON in languages other than Go, and surprising as
it only arises in ADDED events.
This is could be a disruptive change for workflow clients expecting the
empty value, but not sure this is likely in practice.
A newly added workflow now gives:
```json
"status": {
"finishedAt": null,
"startedAt": null
}
```
The time values already have omitempty but as they're structs this
doesn't help. The nulls here are consistent with time serialization
elsewhere in Kubernetes so probably best left as is.
=> Omit empty status fields.

cmd/argo/commands/completion.go, cmd/argo/commands/root.go
The subcommand follows the pattern of kubectl's completion support,
though that has considerable extensions.
zsh support in cobra is minimal at the moment and doesn't support flag
completion. However, there are open PRs against it, so it doesn't seem
worth going the Kubernetes route which modifies the bash output to make
it suitable for zsh.
An obvious next step would be completing to workflow names. I doubt this
would be as useful as pod completions in kubectl, as there isn't often
a useful prefix (if you run many of the same type of workflow).
=> Minimal shell completion support

cmd/argo/commands/common.go, cmd/argo/commands/install.go, cmd/argo/commands/uninstall.go, demo.md, install/install.go
This update the argo cli commands for `install` and `uninstall` to use the same `--namespace` flag as all other commands instead of the installation-specific flag `--install-namespace` (removing it entirely).
Closes #812
=> install & uninstall commands use --namespace flag

examples/influxdb-ci.yaml
Currently, with https://github.com/influxdata/influxdb repository, master branch, 
influxdb-ci.yml example doesnot work any more.
Some minor fixes through this commit
- Use golang:1.9.2 image as base image
- dont use gdm dependency manager any more... switching to dep
- remove test-cov-influxql section because influxql is no longer generated here
- remove test-unit resources request section to be able to run on small k8s cluster
Thanks for your review :-)
And thanks for your hard work on Argo, I just start to play with it and it's really awesome !
=> Fix influxdb-ci.yml example

examples/README.md, examples/arguments-artifacts.yaml, examples/input-artifact-http.yaml, test/e2e/functional/global-param-sub-with-artifacts.yaml, test/e2e/functional/param-sub-with-artifacts.yaml, workflow/common/validate_test.go
All these examples were 755 which still left files executable but weirdly: --wxrw--wx.
I've changed the txt file to 0644 as it doesn't make much sense for that to be executable.
Related discussion: https://argoproj.slack.com/archives/C8J6SGN12/p1524363671000019
=> Use octal syntax for mode values

README.md
At Gladly we set out to reinvent customer service, and we're using argo to help us do it. Currently we're using argo to orchestrate the building of our production machine learning models and see the potential to apply argo to several other use cases.
=> Add gladly as an official argo user

cmd/argo/commands/logs.go
Argo 2.0 outputted logs to stdout (via kubectl). This reinstates that behaviour by avoiding the builtin println in favour of fmt.Println.
=> Avoid `println` which outputs to stderr

examples/README.md
This is an update to the documentation that adds a little more information on referencing global workflow parameters.  This was first mentioned here:
https://groups.google.com/forum/#!topic/argoproj/4ln8JYLpS0o
=> Add documentation on global parameters

workflow/artifacts/git/git.go
Since rev-parse is not fully implemented in go-git ie: missing shorthand commits: dca595f using git rev-parse in that specific case.
=> Resolve revision added ability to specify shorthand revision and other things like HEAD~2 etc

Gopkg.lock, Gopkg.toml, cmd/workflow-controller/main.go, workflow/controller/controller.go, workflow/metrics/collector.go, workflow/metrics/server.go
Implements [#896](https://github.com/argoproj/argo/issues/896)
This PR instruments argo with basic workflow metrics and golang telemetry. It's heavily influenced by https://github.com/kubernetes/kube-state-metrics and is disabled by default. It has to be explicitly configured in the ConfigMap, e.g.:
```
config: |
metricsConfig:
enabled: true
path: /metrics
port: :8080
telemetryConfig:
enabled: true
path: /metrics
port: :8081
```
I made it use the same informer and allow a user to override the workflow resync period to get metrics more often ( 1 minute I think would be optimal). The other option I am thinking about is running it in a sidecar, but it makes it more difficult to make sure configs do not diverge and use the same label selectors. It also seems reasonable that the controller …
=> Issue #896 - Prometheus metrics and telemetry

workflow/metrics/collector.go
Rename Prometheus metrics according to the metric and label naming conventions. See: https://prometheus.io/docs/practices/naming/
=> Rename Prometheus metrics

cmd/argo/commands/submit.go
For workflows that have many parameters, or cases where the workflows should be run with slightly different requirements, it can be useful to have a file containing parameters instead of submitting via the command line.
This commit adds support for the `--parameter-file` (`-f`) command line option to provide a new-line-delimited file of parameters.  These parameters can still be overridden by the `--parameter` (`-p`) flags.
Comments in parameter files are also supported and denoted by a `#` character.
See #796 for more information
=> Add parameter-file support

workflow/executor/executor.go
`tar -tf` will detect compressed tars correctly.
`tar -tzf` will seemingly blindly filter with gzip which causes single-file ZIPs to be accidentally understood as tgz files.
If we match such a tar we explode trying to untar as that call doesn't pass the option to uncompress and correctly spots that the file is not a tar.
Closes #984.
=> Don't force gzip filtering in the tar test

cmd/workflow-controller/main.go, workflow/controller/config.go, workflow/controller/controller.go, workflow/controller/workflowpod.go
I'm customizing some features of Argo with minikube and want to use locally built controller and executor images. I'd like to specify executor image pull policy along with executor image. Could you consider adding this feature?
=> Add imagePullPolicy config for executors

examples/archive-location.yaml
I found the `generateName` of this example is different from the file name of the example while the other examples are the same as the filenames.
=> Fix example pod name

demo.md
I had to disable the persistence option of Minio to make the demo example work. Otherwise, I have to create a `/export` directory for a persistent volume. I think using `emptyDir` is enough for the demo.
=> Disable Persistence in the demo example

examples/README.md
I was getting 
```
2018/09/23 17:00:20 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field ScriptTemplate.env of type v1.EnvVar
```
before this change
=> Fix error in env syntax

workflow/executor/executor.go
Closes https://github.com/argoproj/argo/issues/1033
=> Issue #1033 - Workflow executor panic: workflows.argoproj.io/template workflows.argoproj.io/template not found in annotation file

cmd/argoexec/commands/root.go, docs/workflow-controller-configmap.yaml, workflow/common/common.go, workflow/common/util.go, workflow/controller/config.go, workflow/controller/workflowpod.go, workflow/executor/common/common.go, workflow/executor/k8sapi/client.go, workflow/executor/k8sapi/k8sapi.go, workflow/executor/kubelet/client.go, workflow/executor/kubelet/kubelet.go
I implemented Kubernetes API executor which has been discussed in #902.
Although I implemented the same functions as Kubelet executor, the kubelet originally doesn't work as I submmited the issue #1003. So far, I confirmed `argo logs` and the hello-world, archive-location, scripts-bash and timeouts-step examples work with my Kubernetes API executor, and I tested other functions by returning nil immediately in `Wait()` function of the executor and put a short sleep in workflow steps to workaround the issue #1003.
I think it's enough to use Argo with simple examples like hello-world. Could you consider merging it?
By the way, I use Argo in my company [Preferred Networks](https://www.preferred-networks.jp/en). Please also consider adding my company to the list as described …
=> K8sAPI Executor

workflow/artifacts/git/git.go, workflow/controller/operator.go
For example when you have a project with a submodule and you checkout to a sha that changes the submodule the submodule directory is dirty still doesn't update it.
=> Submodules are diry after checkout -- need to update

workflow/validate/validate.go, workflow/validate/validate_test.go
Implements [#1047](https://github.com/argoproj/argo/issues/1047)
This workflow should be valid now:
```
kind: Workflow
metadata:
generateName: spec-arg-snake-case-
spec:
arguments:
artifacts:
- name: __kubectl
http:
url: https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl
parameters:
- name: my_snake_case_param
value: "hello world"
templates:
inputs:
artifacts:
- name: __kubectl
path: /usr/local/bin/kubectl
mode: 0755
container:
args: ["cowsay {{workflow.parameters.my_snake_case_param}} | tee /tmp/hello_world.txt && ls  /usr/local/bin/kubectl"]
```
=> Parameter and Argument names should support snake case

workflow/controller/workflowpod.go
Use case:
We have an admission webhook that looks at all the pods and adds further annotations apart from other processing based on namespace. Since the pod does not have the namespace explicitly set, we have to go through hoops to figure out the namespace. Having the namespace set explicitly simplifies the process. This should help others with similar use-cases.
=> Add namespace explicitly to pod metadata

errors/errors.go, workflow/executor/k8sapi/k8sapi.go, workflow/executor/kubelet/client.go, workflow/executor/kubelet/kubelet.go
Currently, the kubelet executor emits an error log like below.
```
failed to save outputs: container docker://58a3e33e584d0daaaeed73f1ad91ae5bfec4b8cea30775efec9a037346af7f4d is terminated: &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2018-10-28 14:07:26 +0000 UTC,FinishedAt:2018-10-28 14:07:26 +0000 UTC,ContainerID:docker://58a3e33e584d0daaaeed73f1ad91ae5bfec4b8cea30775efec9a037346af7f4d,}
```
And the k8sapi executor emits an error log like below.
```
failed to save outputs: unable to upgrade connection: container not found ("main")
```
However, I think it's not clear for users what to do by these errors. We should raise a clear error if the called method is not supported in the executor.
=> Raise not implemented error

Gopkg.lock, Gopkg.toml, cmd/argo/commands/completion.go
I added auto-completion for workflows.
https://github.com/spf13/cobra/pull/730
I had to update cobra to [avoid `custom_func` overiding](https://github.com/spf13/cobra/pull/730).
=> Auto-complete workflow names

README.md
If user is looking at documentation through https://argoproj.github.io/argo-cd then absolute links redirect to github markdown file.
=> Use relative links on README file

workflow/artifacts/s3/s3.go
1. Added retry logic to load and save function in s3.go
=> #1081 added retry logic to s3 load and save function

examples/README.md
Fixed as the following error occurred.
error message:
```
2018/12/03 11:30:18 Failed to submit workflow: spec.arguments.parameters[0].name: 
'log_level' is invalid: name must consist of alpha-numeric characters or '-', 
and must start with an alpha-numeric character (e.g. My-name1-2, 123-NAME)
```
```
2018/12/03 11:31:14 Failed to parse workflow: error unmarshaling JSON: 
while decoding JSON: json: cannot unmarshal array into Go struct field Template.name 
of type v1alpha1.Template
```
version:
```
argo: v2.2.1
BuildDate: 2018-10-11T16:25:59Z
GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
GitTreeState: clean
GitTag: v2.2.1
GoVersion: go1.10.3
Compiler: gc
Platform: darwin/amd64
```
=> Fix examples docs of parameters.

workflow/common/common.go, workflow/controller/workflowpod.go
Currently the workflow pod may report an exception 
> Got an exception “hostPath type check failed: /var/lib/docker is not a directory”
if the path is not available.
According to chat in the slack room with @jessesuen , volumeDockerLib is not needed anymore.
=> Remove docker_lib mount volume which is not needed anymore

cmd/argoexec/commands/wait.go
`SaveArtifacts` deletes the files that `SaveParameters` might still need, so we're calling `SaveParameters` first.
Fixes https://github.com/argoproj/argo/issues/1124
=> Fix output artifact and parameter conflict

workflow/util/util.go
I am creating a custom controller which creates argo workflows, it would be easier if there is a way to include `	OwnerReferences` on the workflow resources. This will help cleaning up all the workflows when the custom resource (owner) is deleted.
Verified the code by including and not including OwnerRef object.
=> allow ownerReferences

test/e2e/expectedfailures/failed-retries.yaml, workflow/controller/steps.go, workflow/controller/steps_test.go, workflow/controller/testdata/steps-failed-retries.yaml
When iterating a step group, we were prematurely breaking a loop and not allowing the re-evaluation of a retry node to happen. This resulted in a workflow that would forever be Running.
=> Fix issue where steps with exhausted retires would not complete

Dockerfile-argoexec, Dockerfile-builder, Dockerfile-ci-builder
Add support for multiple archs.
NOTE: gometalinter does not support ppc64le currently, but this PR does not block the amd64.
=> add support for other archs

ARTIFACT_REPO.md, demo.md
Minio stable chart does not append `-minio` postfix as of https://github.com/helm/charts/commit/68da43ea17582b6c74d8b8956b1b20ee49d8d420#diff-163614ce2babd587c18bb85cba01f520 .
=> Reflect minio chart changes in documentation

test/e2e/ui/ui-dag-with-params.yaml, workflow/controller/dag.go, workflow/controller/operator.go
=> Issue #1136 - Fix metadata for DAG with loops

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go
`make update-codegen` was not executed in https://github.com/argoproj/argo/pull/1161.
I think we may want to prevent from merging PR with CI failure.
=> Update codegen for network config

workflow/validate/validate.go
I think we should validate `Artifacts` in `ArchiveLocation` because it is copied to artifacts in inputs and outputs later.
=> Validate ArchiveLocation Artifacts

workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
I got the following error when I submitted a workflow with the K8sAPI executor in my production environment which uses PSP.
```
pods "argo-chainer-mnist-vmtwz-139714430" is forbidden: unable to validate against any pod security policy: [spec.volumes[1].hostPath.pathPrefix: Invalid value: "/var/lib/docker": is not allowed to be used spec.volumes[2].hostPath.pathPrefix: Invalid value: "/var/run/docker.sock": is not allowed to be used spec.volumes[1].hostPath.pathPrefix: Invalid value: "/var/lib/docker": is not allowed to be used spec.volumes[2].hostPath.pathPrefix: Invalid value: "/var/run/docker.sock": is not allowed to be used]
```
I fixed the condition of added volumes and volumeMounts to workflow pods and wrote a simple test.
=> Do not mount unnecessary docker socket

examples/daemon-step.yaml, examples/influxdb-ci.yaml, pkg/apis/workflow/v1alpha1/types.go, workflow/controller/operator.go
=> Issue #1113 - Wait for daemon pods completion to handle annotations

examples/README.md
It relates to issue #796 and #966 and describe how to use parameters files in workflow documentation
=> Add documentation how to use parameter-file's

docs/rest-api.md
Two commits: 
* add the link to the Ruby kubernetes gem
* add a link to a Ruby example on how to start an Argo workflow from a remote Ruby app.
=> Fischerjulian adds ruby to rest docs

Dockerfile
Correcting the base image of `argoexec` in the Dockerfile.
Closes #1209.
=> Dockerfile: argoexec base image correction (fixes #1209)

workflow/controller/operator.go
I found an error while I'm setting up the Argo controller. I wanted to set the executor image pull policy file by configmap but it was not taken for resource templates.
=> Set executor image pull policy for resource templates

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/types.go, pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go, workflow/controller/workflowpod.go
Add schedulerName field to template spec for container/script template. Users can use custom scheduler for workflow pods. 
see comments in #1109
=> add schedulerName

workflow/controller/dag.go
Fixes issue described at https://github.com/argoproj/argo/issues/1190#issuecomment-459898488
Workflow stuck in running state forever if it has dag step with depends on a successfully completed node with retries and this dag step is a dependency for something else.
=> Issue #1190 - Fix incorrect retry node handling

docs/workflow-controller-configmap.yaml, workflow/common/common.go, workflow/controller/config.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Our production k8s cluster operators have banned accessing the k8s apiserver with an in-cluster strategy (using a service account). We have to configure the executor with a kube config file to access it in an out-of-cluster strategy. It may be helpful for other users.
=> Executor can access the k8s apiserver with a out-of-cluster config file

workflow/executor/resource.go
It seems that using `valueFrom: jsonPath: ...` when definining the value of an output parameter for a `resource` template leads to the value being enclosed in single quotes.
For example, here is the output of the Argo pod that creates the resource:
```
time="2019-02-22T21:42:02Z" level=info msg="Saving resource output parameters"
time="2019-02-22T21:42:02Z" level=info msg="[kubectl get PersistentVolumeClaim./example-1-5qkgt-mypvc -o jsonpath='{.metadata.name}' -n kubeflow]"
time="2019-02-22T21:42:03Z" level=info msg="Saved output parameter: mypvc-name, value: 'example-1-5qkgt-mypvc'"
time="2019-02-22T21:42:03Z" level=info msg="Annotating pod with output"
```
I would expect the value to be without quotes, so it can be used as is to refer to the newly-created resource in other parts of the …
=> Remove extra quotes around output parameter value

workflow/metrics/server.go
If you follow the configmap reference here: https://github.com/Path-AI/argo/blob/master/docs/workflow-controller-configmap.yaml#L99 and try to start the Prometheus metrics listener, you get logs like this:
```
time="2019-02-25T20:55:10Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\n# metricsConfig controls the path and port for prometheus metrics\nmetricsConfig:\n  enabled: true\n  path: /metrics\n  port: 8080\n"                                                                                                                                                                             
time="2019-02-25T20:55:10Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2019-02-25T20:55:10Z" level=info msg="Starting prometheus metrics …
```
=> Fix the Prometheus address references

examples/README.md, workflow/executor/resource.go
This PR is fixed the Issue#1223 reported by @shanesiebken. Argo kubernetes resource workflow failed on patch action because argoexec is not passing -p/--patch option to kubectl command. --patch or -p option is required for kubectl patch action.
This PR is including the manifest content as patch argument in kubectl command. 
This Fix will support the Patch action in Argo kubernetes resource workflow.
This Fix will support only **JSON merge strategic** in patch action
=> Fixed Issue#1223 Kubernetes Resource action: patch is not supported

workflow/executor/docker/docker.go, workflow/util/file/fileutil.go
This PR is addressing the Issue#1165 reported by @alexfrieden.
Issue/Bug: Argo workflow is finishing the step successfully even artifact does exist.
Fix: Validate the created gzip contains artifact. if artifact doesn't exist, Current step/stage/task will be failed with the log message.
Sample Log:
'''
INFO[0029] Updating node artifact-passing-lkvj8[0].generate-artifact (artifact-passing-lkvj8-1949982165) message: failed to save outputs: **File or Artifact does not exist. /tmp/hello_world.txt**
'''
=> Issue#1165 fake outputs don't notify and task completes successfully

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/types.go, pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Our GPU cluster highly depends on priority classes and our custom scheduler. We want to set them per workflow or template.
@alexmt @jessesuen Could you consider merging this change?
=> Support Priority Fields in Workflow Pods

workflow/controller/operator.go
For that pod which has already been tag `workflows.argoproj.io/completed: "true"`. It shouldn't be tag again and again.
In some large workflow,  these redundant tag action will cause much press to apiServer and cost much time. 
@jessesuen @alexmt WDYT ?
=> Reduce redundancy pod label action

api/openapi-spec/swagger.json, examples/README.md, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/types.go, workflow/executor/resource.go
* This adds the ability to pass a mergeStrategy to a patch resource.
this is valuable because the default merge strategy for kubernetes is
'strategic', which does not work with Custom Resources.
* This also updates the resource example to demonstrate how it is used
=> Add the `mergeStrategy` option to resource patching

util/file/fileutil.go, util/file/fileutil_test.go, workflow/executor/docker/docker.go
The check to see if the source path was in the tgz archive was wrong
when source path was a folder, the arguments to strings.Contains were
inverted.
This fixes #1274.
=> Fix bug with DockerExecutor's CopyFile

docs/variables.md, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go
=> Add workflow labels and annotations global vars

api/openapi-spec/swagger.json, examples/dns-config.yaml, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/types.go, pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go, workflow/controller/workflowpod.go
```
kind: Workflow                  # new type of k8s spec
metadata:
generateName: hello-world-    # name of the workflow spec
spec:
entrypoint: whalesay          # invoke the whalesay template
templates:
- name: whalesay              # name of the template
container:
image: docker/whalesay
args: ["hello world"]
resources:                # limit the resources
limits:
memory: 32Mi
cpu: 100m
dnsConfig:
nameservers:
- 1.2.3.4
options:
- name: ndots
value: "2"
```
Add @jessesuen @sarabala1979 for reviewers.  Thanks
=> Add dns config support

workflow/controller/exec_control.go, workflow/controller/operator.go
I test many situations on every size workflow, found that there's a problem on large or medium workflow. As the workflow grows larger, the state sync of the pod is slower and slower. In the end, there will even be a situation where the state of the pod in the workflow differs from the state of the actual apiServer storage by more than 20 minutes. I use the test case below.
<details>
<summary>test case</summary>
```
kind: Workflow
metadata:
generateName: pod-limits-
spec:
entrypoint: pod-limits
arguments:
parameters:
- name: limit
value: 300
templates:
- name: pod-limits
steps:
- - name: run-pod
template: run-pod
withSequence:
count: "{{workflow.parameters.limit}}"
- - name: run-pod-2
template: run-pod
withSequence:
count: "{{workflow.parameters.limit}}"
- …
```
=> Speed up podReconciliation using parallel goroutine

docs/variables.md, examples/artifact-path-placeholders.yaml, workflow/common/common.go, workflow/common/util.go, workflow/controller/operator_test.go, workflow/validate/validate.go, workflow/validate/validate_test.go
Adds the following placeholders that resolve to local file paths specified in the `inputs` /`outputs` sections:
* `{{inputs.artifacts.<NAME>.path}}`
* `{{outputs.artifacts.<NAME>.path}}`
* `{{outputs.parameters.<NAME>.path}}`
Fixes https://github.com/argoproj/argo/issues/1257
=> Added support for artifact path references

workflow/controller/operator.go
For the function `checkandEstimate`. I just test it using this case.
<details>
<summary>test case</summary>
```
kind: Workflow
metadata:
generateName: pod-limits-
spec:
entrypoint: pod-limits
arguments:
parameters:
- name: limit
value: 300
templates:
- name: pod-limits
steps:
- - name: run-pod
template: run-pod
withSequence:
count: "{{workflow.parameters.limit}}"
- - name: run-pod-2
template: run-pod
withSequence:
count: "{{workflow.parameters.limit}}"
- - name: run-pod-3
template: run-pod
withSequence:
count: "{{workflow.parameters.limit}}"
- - name: run-pod-4
template: run-pod
withSequence:
count: "{{workflow.parameters.limit}}"
- - name: run-pod-5
template: run-pod
withSequence:
count: "{{workflow.parameters.limit}}"
- - name: run-pod-6
template: …
```
=> Refactor checkandEstimate to optimize podReconciliation

examples/README.md
- fix order in TOC
- fix links
- specify language in fenced code blocks
Closes #1309
=> Fix formatting issues in examples documentation

workflow/executor/common/common.go, workflow/executor/k8sapi/client.go, workflow/executor/kubelet/client.go
All calls to these methods previously generated a panic at runtime
because the calls resolved to the default, panic-always implementation,
not to the overrides provided by `k8sAPIClient` and `kubeletClient`.
Embedding an exported interface with unexported methods into a struct is
the only way to implement that interface in another package.  When doing
this, the compiler generates default, panic-always implementations for
all methods from the interface.  Implementors can override exported
methods, but it's not possible to override an unexported method from the
interface.  All invocations that go through the interface will come to
the default implementation, even if the struct tries to provide an
override.
=> Export the methods of `KubernetesClientInterface`

workflow/controller/dag.go, workflow/controller/operator.go, workflow/controller/steps.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Hello, I am a member of @Arrikto and we are currently working on kubeflow/pipelines#801.
For our design to work properly we need to create and use kubernetes resources (`PVC`s and `VolumeSnapshots`, to be exact) using resource templates and `Workflow` parameters for their names. The PVCs must then be mounted by some pods.
I understand that the existing `volumeClaimTemplates` workflow attribute already supports parameter substitution, but we need to access PVCs which already exist outside the workflow, so we need to get their names as workflow parameters, and use them in `volumes`.
This PR implements parameter substitution in the `Volumes` attribute, both for global parameters as well as for output parameters of tasks and steps.
=> Support parameter substitution in the volumes attribute

workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
I found the following 2 bugs around volumes and fixed them.
- Volumes only mounted in InitContainers are not set in the pod.
- Template-local volumes are not used at all.
=> Fix volumes

workflow/controller/workflowpod.go
Due to wrong `map` initialization, input parameters where appended to `woc.globalParams`.
This PR fixes #1340.
=> Fix #1340 parameter substitution bug

workflow/controller/when_test.go
( If this knowledge is worth ... )
INPUT: `"ref/branch/master == ref/branch/master"`
OUTPUT:
```
Failed to evaluate 'when' expresion 'ref/branch/master == ref/branch/master': Value 'ref' cannot be used with the modifier '/', it is not a number
```
`/` is evaluated division.
So character that included `/` needs to be surrounded by a single quote.
=> Add when test for character that included `/`

workflow/artifacts/git/git.go
The current implementation for git (using ssh key) does't works fine with multiples `git` artifacts are defined:
```
- name: code
path: /workdir/src
git:
...
- name: plywood
path: /workdir/src/plywood
git:
repo: ....
```
It returns error `failed to load artifacts: mkdir /root/.ssh: file exists`
The reason fo that is the creation of `~/.ssh` many times which is failing at the second key in the list even if it is the same key.
This PR simply check if the directory exists or not before trying to create it.
=> fix multiple ssh key

cmd/argo/commands/common.go, cmd/argo/commands/get.go, cmd/argo/commands/resubmit.go, cmd/argo/commands/retry.go, cmd/argo/commands/submit.go, cmd/argo/commands/watch.go
For some large workflow.  `argo get` command will return very very long line to read.  
So inspired by `argo list` command.   Add `--status` flag for get command.
Pls @sarabala1979 @jessesuen take a look,  thanks.
=> Add --status filter for get command

api/openapi-spec/swagger.json, cmd/argoexec/commands/resource.go, examples/k8s-set-owner-reference.yaml, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/types.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/executor/resource.go, workflow/validate/validate.go, workflow/validate/validate_test.go
This PR solves #1317.
When you create workflows with resource templates, you may want to delete the generated resources when the workflows are deleted. Currently, we need to set `OwnerReference` by using a technique of:
https://github.com/argoproj/argo/blob/64370a2d185db66a8d2188d986c52a3b73aaf92b/examples/k8s-owner-reference.yaml#L23-L28
However, I think setting `OwnerReference` should be something more intuitive because the generated resources tend to be chid resources of workflows. This PR provides a boolean option to set `OwnerReference` (`false` by default) and also validate resource manifest format.
I purposely didn't use the proposed option name `cascadeDelete` because it actually doesn't cascade `delete` if the `OwnerReference` of the generated resource is removed manually before …
=> Support an easy way to set owner reference

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/types.go, workflow/controller/operator_test.go, workflow/validate/validate.go, workflow/validate/validate_test.go
I found a resource template without action causes an avoidable error of `unknown shorthand flag: 'f' in -f` in the generated pod.
This PR may conflict with #1333, so I will update either of this or that PR once the other gets merged.
=> Validate action for resource templates

test/e2e/expectedfailures/dag-exhausted-retries.yaml, test/e2e/functional/dag-with-retries.yaml, workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/controller/testdata/dag-exhausted-retries-xfail.yaml
Resolves https://github.com/argoproj/argo/issues/1190
=> Fix issue where a DAG with exhausted retries would get stuck Running

docs/example-golang/main.go
Make locating kubeconfig in example os independent. This addresses issue #1392.
=> Make locating kubeconfig in example os independent

ARTIFACT_REPO.md
In the non-default artifact repo section, when showing the gcs example the bucket name said 'my-aws-bucket-name'. I've updated this to say 'my-gcs-bucket-name'.
Super minor change but I've been banging my head against artifact repo outputs all day and this was bothering me.
See issue #1424
=> Typo fix in ARTIFACT_REPO.md

workflow/executor/pns/pns.go
Due to timing issues, PNS would intermittently fail to capture the logs of a script container, instead returning an empty string. Adding the follow option resolved the issue.
=> PNS executor intermitently failed to capture entire log of script templates

cmd/argo/commands/list.go
For some k8s cluster which already run many workflows.   The argo list command will return about 1-2k+ workflows.  In this situation, argo list will output error message like this 
```
stream error http2.streamerror{streamid:0x1, code:0x2, cause:error(nil)} w
```
To avoid this situation, we should set the limit for argo list command,  this will increase argo list command usability and robustness.
@jessesuen @sarabala1979   Pls take a look.
=> Add paging function for list command

cmd/argo/commands/completion.go, cmd/argo/commands/list.go, cmd/argo/commands/submit.go
Resolve Issue #1436 and #1440, to improve user experience for command-line completion with bash.
This is what I'm doing on my Mac.  You just need to write the completion script to a file so you can source it.
```
make cli
sudo cp -R dist/argo `which argo`
argo completion bash > /usr/local/etc/bash_completion.d/argo
. /usr/local/etc/bash_completion.d/argo
```
```
Edwins-MacBook-Pro:argo edwin$ argo logs 
artifact-passing-br72f-4272859315  coinflip-5ktdk-666293366           coinflip-qvqbl-630379513           steps-ptdtq-1129304726
artifact-passing-br72f-570194761   coinflip-jg4g6-2175945733          coinflip-rd6v4-1951658687          steps-ptdtq-126479429
artifact-passing-mldqq-3331757295  coinflip-jmvx7-2288525212          coinflip-rd6v4-2832038430          steps-sp22h-1028943132 …
```
=> Improve bash completion

demo.md
Signed-off-by: Aisuko <urakiny@gmail.com>
Follow the demo's doc,  there may have some misunderstanding，please see link below
https://github.com/helm/charts/blob/62b33b47d8ffd8c9fa2c727a2a962f1754a0eb5d/stable/minio/templates/_helpers.tpl#L15
So, If you would like to install `minio chart` as name `argo-artifacts`, the `fullnameOverride ` is more helpful then `--name`, it's a release name for `helm`.
=> docs: Fix demo's doc issue of install minio chart

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/types.go, pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
`supplementalGroups` is widely used in my company's cluster but there's no way to set `PodSecurityContext` though Argo.
=> Support PodSecurityContext

examples/README.md, examples/dag-disable-failFast.yaml
Add doc about failFast feature.
@jessesuen @sarabala1979 Pls take a look.
=> Add doc about failFast feature

cmd/argo/commands/logs.go
Fixes #1435.
I added `--no-color` flag just with the same way as `get` command.
=> Add --no-color flag to logs command

test/e2e/expectedfailures/dag-disbale-failFast-2.yaml, workflow/controller/dag.go
The dependencies are as follows :
```
step1：      A
/     \
step2：  B       C
|
step3：  D
|
step4：  E
```
If node D is failed, the workflow will hang forever.  
Test case is here:
<details>
<summary>dag test case</summary>
```
kind: Workflow
metadata:
generateName: dag-primay-branch-
spec:
entrypoint: statis
templates:
- name: a
container:
image:  docker/whalesay:latest
args: ["hello world"]
- name: b
retryStrategy:
limit: 2
container:
args: ["sleep 30; echo haha"]
- name: c
retryStrategy:
limit: 3
container:
args: ["echo intentional failure; exit 2"]
- name: d
container:
args: ["echo intentional failure; exit 2"]
- name: e …
```
=> Fix failFast bug:   When a node in the middle fails, the entire workflow will hang

cmd/argo/commands/submit.go
=> Fix: Argo CLI should show warning if there is no workflow definition in file #1486

docs/variables.md, workflow/common/common.go, workflow/controller/operator.go
This PR exposes the workflow priority as a variable.
This can be useful for using it to derive pod priority, for example.
=> Exposed workflow priority as a variable

workflow/common/ancestry.go, workflow/common/ancestry_test.go, workflow/common/util.go, workflow/controller/dag.go, workflow/validate/validate.go
This PR fixes the unpredictable behavior when using global artifacts.
This inconsistency is caused when calculating the ancestors of a task.
There a map is used to store the visited ancestors that is afterwards transformed into an array.
But the order of gomap is randomized as stated [here](https://blog.golang.org/go-maps-in-action#TOC_7):
> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since the release of Go 1.0, the runtime has randomized map iteration order. 
Therefore, the visited map is just replaced with an array and now the right order is guaranteed.
Fixes #1366 #1438
=> Fix #1366 unpredictable global artifact behavior

examples/continue-on-fail.yaml
Researching how this `parallelism` config feature functions and came across this example that I think wasn't accurately reflecting the description it had at the top of the file. 
PS. Great work on Argo!
=> Change 'continue-on-fail' example to better reflect its description

Makefile, cmd/argo/commands/list.go, cmd/argoexec/commands/root.go, workflow/controller/dag.go, workflow/executor/executor.go
This fixes an issue with the `make lint` target, where if a developer
has golangci-lint installed and also has linter errors, the linter fails
with an error, causing the next case to fall through (and the old linter
is run).
This also fixes all of the linter errors that had somehow cropped up in
the repo.
This should be the resolve all the issues preventing `make precheckin` from passing.
=> Fix the lint target

workflow/controller/operator_test.go
I'm not sure how to ask this without sounding rude - Is there a reason that code is being merged into master without passing the CI gates? There have been several of these over the past few weeks, for example https://github.com/argoproj/argo/pull/1505, https://github.com/argoproj/argo/pull/1500
=> Fix a compiler error in a unit test

Dockerfile, workflow/controller/operator_test.go
=> Fixed #1287 Executor kubectl version is obsolete

cmd/argo/commands/submit.go, util/cmd/cmd.go, util/cmd/cmd_test.go, workflow/util/util.go
This PR allows overriding workflow labels in 'argo submit', the same way they can be overridden in 'kubectl run'
=> Allow overriding workflow labels in 'argo submit'

workflow/common/util.go, workflow/validate/validate.go, workflow/validate/validate_dag_test.go, workflow/validate/validate_test.go
The function `ProcessArgs` returns an updated template, but using it in validation causes unit test errors. It confuses developers when they implement something around input/output parameters and arguments like #1490. I fixed it so it won't confuse them in the future.
=> Fix validation

cmd/argo/commands/logs.go
VirtualKubelet is [here](https://github.com/virtual-kubelet/virtual-kubelet).   
When argo run workflow in virtual kubelet env,   the virtual kubelet return not standard log entry. It will cause empty content when `argo logs`.
=> Fix argo logs empty content when workflow run in virtual kubelet env

docs/variables.md, workflow/common/util.go, workflow/controller/operator_test.go, workflow/validate/validate.go
This change allows you to use {{input.parameters}} to fetch the full parameters list as a JSON string.
=> Expose all input parameters to template as JSON

cmd/argo/commands/lint.go
This PR resolves #1547
It adds a missing call to ```InitWorkflowClient()``` which initializes the wfClientset object used for validation.
=> Fix uninitialized wfClientset in the Lint command

.gitignore, Makefile
I think we should track test coverage and write more tests so we can easily modify the code in the future.
I wanted to set up codecov for the coverage tracking. Could some one set up the ci with `CODECOV_TOKEN` in https://codecov.io/gh/argoproj/argo?
=> Add coverage make target

Gopkg.lock, test/e2e/functional/artifact-input-output-samedir.yaml, util/archive/archive.go, workflow/common/util.go, workflow/common/util_test.go, workflow/executor/executor.go, workflow/executor/executor_test.go, workflow/validate/validate.go
Resolves https://github.com/argoproj/argo/issues/1566
When collecting an output artifact which happens to overlap with an input, the executor fails to capture it since it thinks it needs to copy it from the base image layer (e.g. using docker cp, or PNS). This fixes the logic so that it properly detects when the artifact should be copied directly from the shared volume mounted in the wait container.
=> Fix issue saving outputs which overlap paths with inputs

workflow/common/util.go, workflow/controller/operator.go, workflow/templateresolution/context.go, workflow/templateresolution/context_test.go, workflow/validate/validate.go
When I implemented [the WorkflowTemplate CRD](https://github.com/argoproj/argo/pull/1312) initially, I merged templates from the bottom to the top with processing args. However, we can't make [wildcard parameters and arguments](https://github.com/argoproj/argo/pull/1490) in this way, because parameters come from the top.
I changed the template resolution to process inputs and arguments before recursively resolving templates and merge the other fields after. By this approach, we can process arguments in arguments properly and will be able to make the wildcard parameters.
=> Fix inputs and arguments handling during template resolution

workflow/metrics/collector.go
I'm monitoring workflow-controller metrics with Datadog.
I want to group a specific metric (e.g. `argo_workflow_completion_time`) and display it in the graph, but I can't do this because there is no common tag(label) set in Workflow Resource.
I want to add `entrypoint`  to workflow default labels for each metric.
rel. https://github.com/argoproj/argo/issues/1384
=> Add entrypoint label to workflow default labels

util/archive/archive.go, workflow/executor/common/common.go, workflow/executor/pns/pns.go, workflow/executor/resource.go, workflow/util/util.go
=> Remove redundant codes

pkg/apis/workflow/v1alpha1/workflow_types.go
This PR registers resource templates as leaf templates, enabling retryStrategy for resource templates.
This closes #1370
=> Regard resource templates as leaf nodes

workflow/controller/workflowpod.go
The mount path of the docker.sock should not depend on the host path of the docker.sock
#1606
=> Do not relocate the mounted docker.sock

test/e2e/expectedfailures/dag-failFast-hang.yaml, workflow/controller/dag.go
In this case
```
kind: Workflow
metadata:
generateName: dag-hang-failFast-
spec:
entrypoint: retry-with-dags
templates:
- name: retry-with-dags
dag:
failFast: false
tasks:
- name: A
template: success
- name: B
template: success-2
dependencies:
- A
- name: C
template: sub-dag2
dependencies:
- A
- name: D
dependencies:
- A
- C
template: success
- name: sub-dag
dag:
tasks:
- name: fail
template: fail
- name: success1
template: success
- name: fail
container:
command: [sh, -c, exit 1]
image: alpine
retryStrategy:
limit: 1
- name: sub-dag2
steps:
- - name: sub-dag-a
template: success
- - name: sub-dag-b
template: fail
- name: success
container:
command: [sh, -c, exit 0]
image: alpine
retryStrategy:
limit: 1
- name: success-2
container:
command: [sh, -c, sleep …
```
=> Fix DAG enable failFast will hang in some case

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go
This change adds merge keys to the types defined by Argo, allowing the types to be recognized for StrategicMergePatching, as opposed to the less powerful JSONMergePatch strategy.
We have an example of this in action using [our branch of Kustomize](https://github.com/keleustes/kustomize/tree/armadacrd):
```
git clone --single-branch --branch armadacrd git@github.com:keleustes/kustomize.git
make install build-plugins
cd examples/crds/argo-workflow
cat README.md
```
This feature will be much more important as Kubernetes moves forward. It will eventually have an effect on how a `kubectl patch` works on Argo resources, as Kubernetes continues to improve support for CRDs. See [this PR adding CRD validation field in server-side apply](https://github.com/kubernetes/kubernetes/pull/77354) for …
=> Add merge keys to Workflow objects to allow for StrategicMergePatches

cmd/argo/commands/submit.go, cmd/argo/commands/template/create.go, util/file/fileutil_test.go, workflow/util/util.go, workflow/util/util_test.go
This PR tries to reduce code duplication in the ```submit``` and ```template create``` code files.
It does so by factoring out the common code that was to read from a file or a url and adds tests for it.
It also adds a test for the dry-run option of the submit command.
=> Small code cleanup and add tests

Gopkg.lock, cmd/argoexec/commands/root.go, cmd/workflow-controller/main.go, util/cmd/cmd.go
This updates us to use later version of `argoproj/pkg` which has a fix to configure glog to *not* attempt to write to /tmp
=> Prevent controller from crashing due to glog writing to /tmp

golangci.yml
I increased the timeout duration of golangci-lint.
=> Increase timeout of golangci-lint

workflow/util/util.go
I found the state of a retried workflow is not correct and already run nodes are not printed correctly until it is processed. I fixed the CLI so it can print the initial state of a retry correctly.
I tried the following workflow which fails at last always.
<details>
<summary>steps.yaml</summary>
```
kind: Workflow
metadata:
generateName: steps-
spec:
entrypoint: hello-hello-hello
templates:
- name: hello-hello-hello
steps:
- - name: hello1
arguments:
parameters: [{name: message, value: "hello1"}]
- - name: hello2a
arguments:
parameters: [{name: message, value: "hello2a"}]
- name: hello2b
arguments:
parameters: [{name: message, value: "hello2b"}]
- name: fail
template: fail
- name: fail
container: …
```
=> Fix retry workflow state

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/operator.go
I added `StoredTemplateID` which is used to refer a template in `StoredTemplates`. I added this field because it will be easy to change the logic to store templates (e.g. using MD5, just index or something) in the future.
=> Save stored template ID in nodes

Gopkg.lock, Gopkg.toml
When attempting to bump Argo to `2.3.1` in Nixpkgs (ref: https://github.com/NixOS/nixpkgs/pull/69139) I ran into the following build problem: 
```
go/src/github.com/argoproj/argo/workflow/artifacts/hdfs/util.go:21:26: cannot use krbClient (type *"gopkg.in/jcmturner/gokrb5.v5/client".Client) as type *"github.com/colinmarc/hdfs/vendor/gopkg.in/jcmturner/gokrb5.v5/client".Client in assignment
builder for '/nix/store/wfpzhnc91l4mdk4jxz37y743nqqhpbhk-argo-2.3.0.dr
```
The problem is still there on `2.4.0-rc1`.
After noticing that the very next commit in `colinmarc/hdfs` removes vendored deps, I guessed that going to that commit would solve the problem. It did!
So while I don't know why this issue is presenting when Nix is trying to build Argo `2.3.1`, this change at least removes the problem.
=> pin colinmarc/hdfs to the next commit, which no longer has vendored deps

workflow/controller/dag.go, workflow/controller/operator.go
A task group ancestor node doesn't have a template and caused a template unavailable error.
=> Fix DAG output aggregation

demo.md
Mainly ensures that all commands run on the `argo` namespace
=> Bug fixes in getting started

util/file/fileutil.go, util/file/fileutil_test.go, workflow/executor/docker/docker.go
Empty output artifacts are a valid and desired use case. (Think of `grep` or any other filtering program where one of the outputs can be empty.)
Argo failing on empty outputs was a pretty bad surprise for us.
Fixes https://github.com/argoproj/argo/issues/1642
The problem was introduced in https://github.com/argoproj/argo/pulls/1247
=> Stop failing if artifact file exists, but empty

workflow/controller/operator.go, workflow/controller/steps.go, workflow/templateresolution/context.go, workflow/templateresolution/context_test.go, workflow/templateresolution/lazyworkflowtemplate.go
The current workflow template resolution fails if a used template is deleted during template execution. I made a gist to reproduce this issue.
https://gist.github.com/dtaniwaki/c6ccf9e5d9ef04bdd4962c76429cf6db
I made the workflow template resolution lazy so just retrieving stored templates doesn't require workflow template existence.
=> Resolve WorkflowTemplate lazily

workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Fixes: https://github.com/argoproj/argo/issues/1503.
@jessesuen @sarabala1979 Please review
=> Don't provision VM for empty artifacts

cmd/argoexec/commands/wait.go
Fixes: #1674 
I changed the logic of killing sidecars so we can still stop on a failure of the post process.
=> Handle sidecar killing properly

workflow/controller/operator.go
Fixes #1659 
Retry nodes didn't have inputs because they're not registered as executable nodes. I fixed it and confirmed the problematic workflow works.
=> Handle retried node properly

pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/operator.go
Locally referenced templates cannot be executed successfully because the reference is not found in stored templates but found local templates still need to be resolved. Here's an example that reproduces the issue besides `examples/workflow-template/local-ref.yaml`.
```
kind: Workflow
metadata:
generateName: argo-dag-
spec:
entrypoint: dag
templates:
- dag:
tasks:
- name: task1
template: container1-proxy
name: dag
- name: container1-proxy
template: container1
- container:
image: python:alpine3.6
command: [python, -c]
args: ["import sys; sys.exit(0)"]
name: container1
```
=> Store locally referenced templates properly

workflow/validate/validate.go, workflow/validate/validate_test.go
workflow.priority substitution was error-ing during validation
=> Fix issue that workflow.priority substitution didn't pass validation

docs/variables.md, examples/status-reference.yaml, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go, workflow/validate/validate_dag_test.go, workflow/validate/validate_test.go
Closes: https://github.com/argoproj/argo/issues/1663
Makes
```
{{steps.<STEPNAME>.status}}
{{tasks.<TASKNAME>.status}}
```
available as variables
=> Added status of previous steps as variables

cmd/argo/commands/get.go, cmd/argo/commands/template/get.go
Currently, `argo get` just ignores workflows other than the first one while `kubectl describe` can print multiple resources. I think it's reasonable to follow the spec. I also changed the behavior for `WorkflowTemplate` as well.
The output of multiple workflow printing will be like below.
```
$ argo get continue-on-fail-znnhj dag-daemon-task-2txg5
Name:                continue-on-fail-znnhj
Namespace:           default
Status:              Succeeded
Created:             Sun Oct 06 16:07:37 +0900 (20 minutes ago)
Started:             Sun Oct 06 16:07:38 +0900 (20 minutes ago)
Finished:            Sun Oct 06 16:25:01 +0900 (2 minutes ago)
Duration:            17 minutes 23 seconds
STEP                                         PODNAME …
```
=> Print multiple workflows in one command

workflow/controller/operator.go
Fixes #1693
I misunderstood the retry node processing logic and made retrying nodes infinitely running in #1669 . I fixed the logic so it can create new child node on failure successfully.
=> Fix retry node processing

Gopkg.lock, api/openapi-spec/swagger.json, examples/pod-spec-patch-wf-tmpl.yaml, examples/pod-spec-patch.yaml, examples/pod-spec-yaml-patch.yaml, pkg/apis/workflow/v1alpha1/openapi_generated.go, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/operator.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go, workflow/util/util.go, workflow/util/util_test.go
This PR will resolve  #703. This functionality will enable passing parameters all POD spec elements. 
```
kind: Workflow
metadata:
generateName: pod-spec-patch-
spec:
arguments:
parameters:
value: 100m
templates:
podSpecPatch: '{"containers":[{"name":"main", "resources":{"limits":{"cpu": "{{workflow.parameters.message}}"}}}]}'
container:
args: ["hello world"]
```
=> PodSpecPatch functionality 

workflow/common/util.go, workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes: https://github.com/argoproj/argo/issues/1646. Thanks @c-dante
```
...
Name:                pod-name-pjdk9
Status:              Failed
Message:             No more retries left
Created:             Mon Oct 21 11:59:01 -0700 (11 seconds ago)
Started:             Mon Oct 21 11:59:01 -0700 (11 seconds ago)
Finished:            Mon Oct 21 11:59:12 -0700 (now)
Duration:            11 seconds
STEP                               PODNAME                    DURATION  MESSAGE
✖ pod-name-pjdk9 (pod-name)                                            No more retries left
├-✖ pod-name-pjdk9(0) (pod-name)  pod-name-pjdk9-3274678606  5s        failed with exit code 1
└-✖ pod-name-pjdk9(1) (pod-name)  pod-name-pjdk9-2670537227  4s        failed …
```
=> Fixed incorrect `pod.name` in retry pods

demo.md
Fixes: https://github.com/argoproj/argo/issues/1683
=> Fixes bugs in demo

Gopkg.lock, Gopkg.toml
After adding `protobuf` functionality `make codegen` now requires `gonum.org/v1/gonum/graph`. However, it wasn't added to `Gopkg.toml` so running `dep ensure` wouldn't fetch it. Added under `required` per the [dep docs](https://golang.github.io/dep/docs/Gopkg.toml.html#required).
=> Add gonum.org/v1/gonum/graph to Gopkg.toml

pkg/apis/workflow/v1alpha1/workflow_types.go
An `fmt.Println(...)` most likely for debug purposes got merged to master causing debug information to be printed to the user on the CLI:
```
$ argo submit --watch temp.yaml
[{steps1 stepsTempalte {[] []} nil []  nil  nil}]
[{steps2 stepsTempalte {[] []} nil []  nil  nil}]
[{leafA whalesay {[] []} nil []  nil  nil}]
[{leafB whalesay {[] []} nil []  nil  nil}]
[{steps1 stepsTempalte {[] []} nil []  nil  nil}]
[{steps2 stepsTempalte {[] []} nil []  nil  nil}]
[{leafA whalesay {[] []} nil []  nil  nil}]
[{leafB whalesay {[] []} nil []  nil  nil}]
Name:                suspend-template-nsv4n
Status:              Pending
Created:             Wed Nov 06 07:32:12 -0800 (now)
Name:                suspend-template-nsv4n
Namespace: …
```
=> Removed debug `Println`

workflow/controller/operator.go, workflow/controller/operator_test.go
Suspended steps would never time out, regardless of the setting of activeDeadlineSeconds.
This change fixes that.
=> Fail suspended steps after deadline

util/cmd/cmd.go
According to the go golint report, package comment is detached.
So I delete that blank line.
=> fix blank lines

docs/README.md, docs/workflow-executors.md
=> Add documentation for executors

manifests/base/crds/workflow-crd.yaml
Set additionalPrinterColumns in the CRD to make k8s print the status and age of workflows when using kubectl.
This required k8s >= 1.11.
Example of `kubectl get workflows`:
```
NAME                         STATUS      AGE
abc-87-1573741887810-4nhds   Succeeded   43m
abc-88-1573741887810-5t2p6   Running     43m
abc-89-1573741887810-77xq5   Running     43m
abc-90-1573741887810-7nd57   Failed      43m
abc-91-1573741887810-jlzzr   Succeeded   43m
```
=> Make kubectl print status and start/finished time

workflow/controller/steps.go
Fixes #1801 by adding a hint when a `when` expression contains tokens that `govaluate` considers invalid.
Example:
```
Name:                brackets-test-dl284
Status:              Failed
Message:             Invalid 'when' expression '{true} == {true}': Invalid token: '{' (Hint: try wrapping the affected expression in quotes ("))
Created:             Mon Dec 02 09:55:33 -0800 (16 seconds ago)
Started:             Mon Dec 02 09:55:33 -0800 (16 seconds ago)
Finished:            Mon Dec 02 09:55:49 -0800 (now)
Duration:            16 seconds
STEP                                    PODNAME                         DURATION  MESSAGE
✖ brackets-test-dl284 (brackets-test)                                            Invalid 'when' expression …
```
=> Added hint when using certain tokens in when expressions

cmd/argoexec/commands/wait.go
#fixes #1697 When a failure on the pod watch occurred, the error should be returned after all information from the pod (log, artifacts) are collected. I also added an exponential backoff to the pod watch and the adding of pod annotations.
=> Wait container error on pod watch failure and exponential backoff

workflow/config/config.go, workflow/persist/sqldb/sqldb.go
Quick fix to enable SSL connection to Postgres databases for workflow repositories.
**disclaimer**: couldn't get this to work mysql as there didn't seem to be an option to do so using`upper.io/db.v3`...
**disclaimer 2**: I'm a bit of a noob when it comes to Golang so didn't manage to run tests/write new ones locally. I'm totally counting on your CI system to flag my possible mistakes :smile:
=> SSL enabled database connection for workflow repository (#1712)

cmd/argo/commands/common.go, cmd/argo/commands/lint.go, cmd/argo/commands/template/common.go, cmd/argo/commands/template/create.go, cmd/argo/commands/template/lint.go, workflow/controller/operator.go, workflow/templateresolution/context.go, workflow/util/util.go, workflow/validate/lint.go, workflow/validate/validate.go, workflow/validate/validate_test.go
Fixes #1662
I created a concept of `local template resolution context` so lint validation rejects remote template resolutions unless passed a flag.
Here's the lint test result with this fix.
```
$ argo lint examples/workflow-template/steps.yaml
FATA[0000] examples/workflow-template/steps.yaml: templates.hello-hello-hello.steps[0].hello1 failed to get a remote template in local context
$ argo lint --resolve-remote-templates examples/workflow-template/steps.yaml
Workflow manifests validated
$ argo lint --kubeconfig=config examples/workflow-template/steps.yaml
FATA[0000] examples/workflow-template/steps.yaml: templates.hello-hello-hello.steps[0].hello1 failed to get a remote template in local context
$ argo lint --kubeconfig=config --resolve-remote-templates …
```
=> Do not resolve remote templates in lint

workflow/controller/operator.go
Fixes #1761
I fixed the retry failure on workflows with PVCs by marking main nodes error on operation-level error and keeping PVCs of failed/error nodes for future retries.
=> Handle operation level errors

README.md
Wavefront internally uses argo for release automation
=> docs: Adding Wavefront to the users list

README.md
Add Sidecar to the list of organizations that use Argo Workflows.
=> docs: Add Sidecar Technologies to list of who uses Argo

workflow/executor/common/common.go
Found that the k8sapi/kubelet executor that use the `WaitForTermination()`
of the common executor randomly throw the error as below and
also issue has been reported (#1573)
```
=== 8< ===
time="2019-12-05T06:00:16Z" level=info msg="Waiting on main container"
time="2019-12-05T06:00:20Z" level=info msg="main container started with container ID: 980c0415db8e7c404161eb37ada3f5a17fe38f284ff02960e130526b69d3b7a3"
time="2019-12-05T06:00:20Z" level=info msg="Starting annotations monitor"
time="2019-12-05T06:00:20Z" level=info msg="Waiting for container 980c0415db8e7c404161eb37ada3f5a17fe38f284ff02960e130526b69d3b7a3 to complete"
time="2019-12-05T06:00:20Z" level=info msg="Starting deadline monitor"
time="2019-12-05T06:00:20Z" level=info msg="Starting to wait completion of containerID …
```
=> fix: Ensure timer channel is empty after stop

docs/configure-artifact-repository.md, docs/getting-started.md
Helm 3 has been the default version in brew repository, and it has
quite different operations from before. This change is to make the
doc update to date.
=> docs: Update doc based on helm 3.x changes

workflow/persist/sqldb/sqldb.go
update comment to match function name
Checklist:
=> fix(persistence): Update comment in sqldb.go to match function name

docs/CONTRIBUTING.md
The current target looks like an absolute reference but is browser-interpreted as relative. The change makes it explicitly a relative reference and avoids a 404 in GitHub.
Checklist:
=> docs: Fix e2e testing link

workflow/config/config.go, workflow/config/config_test.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
=> feat!(logging): Always archive logs if in config. Closes #1790

workflow/common/placeholder.go, workflow/common/placeholder_test.go, workflow/validate/validate.go, workflow/validate/validate_test.go
Fixes #1842
I changed the validation to use dynamically-generated placeholder strings.
=> fix: Use dynamically generated placeholders

workflow/controller/controller_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
`TemplateScope` should be a based template context from which a template resolution starts.
This fix is necessary to make the workflow detail view work with workflow templates without steps: e.g. `examples/workflow-template/hello-world.yml`
=> fix: Fix template scope

.circleci/config.yml, test/e2e/expectedfailures/pod-termination-failure.yaml, test/e2e/functional_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes: https://github.com/argoproj/argo/issues/1832
When a k8s node where the POD runs has an issue, the POD will go to "terminating" state - which is actually "running" phase but with "DeletionTimestamp", and stuck there. This fix quick fails it when this kind of situation is detected.
=> fix: quick fail after pod termination

Gopkg.lock
=> fix: Update Gopkg.lock with dep ensure -update

Gopkg.lock
=> feat(artifacts): Add support for IAM roles for service accounts in artifact storage. Fixes #1774

.dockerignore
It takes a long time to send `node_modules` to the deamon build context even though it is unnecessary to do so.
=> fix: Decrease docker build time by ignoring node_modules

persist/sqldb/migrate.go
Mysql doesn't support to create an index with `if not exists`.
=> fix: Make sql works for both mysql and postgre

workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate_test.go
=> feat: Provide values of withItems maps as JSON in {{item}}. Fixes #1905

README.md
Link doesn't render if there is a space between `]` and `(`
=> docs: Minor formatting fix

README.md
=> docs: Add CyberAgent to the list of Argo users

.circleci/config.yml, cmd/argo/commands/cron/delete.go, cmd/argo/commands/cron/resume.go, cmd/argo/commands/cron/root.go, cmd/argo/commands/cron/suspend.go, test/e2e/cron/cron_test.go, test/e2e/fixtures/then.go
=> feat: Add suspend and resume to CronWorkflows CLI

cmd/workflow-controller/main.go, manifests/namespace-install.yaml, manifests/namespace-install/kustomization.yaml, manifests/namespace-install/overlays/workflow-controller-configmap.yaml, manifests/namespace-install/overlays/workflow-controller-deployment.yaml
This is the implementation for proposal https://github.com/argoproj/argo/issues/1938, with this change, `workflow-controller` adds 2 optional args`--namespaced` and `--namespace`. 
This deprecates the dependency of `namespace` configuration in the configmap for namespace only mode installation.
=> feat: Enhancement for namespace installation mode configuration

ui/src/app/shared/utils.ts, ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.scss
=> chore: Fix UI TODOs

Makefile, cmd/argo/commands/template/lint.go, cmd/server/workflowarchive/archived_workflow_server_test.go, cmd/server/workflowtemplate/workflow_template_server_test.go, test/e2e/argo_server_test.go, test/e2e/cli_test.go, test/e2e/fixtures/e2e_suite.go, test/e2e/fixtures/given.go, test/e2e/fixtures/then.go, test/e2e/fixtures/when.go, test/e2e/smoke/hello-world-workflow-tmpl.yaml, test/e2e/smoke/workflow-template-whalesay-template.yaml, test/e2e/smoke_test.go, test/e2e/testdata/workflow-template-nested-template.yaml, test/e2e/workflow_template_test.go, util/kubeconfig/kubeconfig_test.go
=> chore: Added WorkflowTemplate test

test/e2e/argo_server_test.go
=> fix: WorkflowTempalteTest fix

Makefile
=> fix(Makefile): Rename staticfiles make target. Fixes #2010

.circleci/config.yml, .dockerignore, Makefile, cmd/server/workflowtemplate/workflow_template_server_test.go, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/base/minio/minio-pod.yaml, manifests/quick-start/mysql/mysql-deployment.yaml, manifests/quick-start/postgres/postgres-deployment.yaml, persist/sqldb/workflow_archive.go, test/e2e/argo_server_test.go, test/e2e/expectedfailures/pod-termination-failure.yaml, test/e2e/fixtures/e2e_suite.go, test/e2e/fixtures/given.go, test/e2e/fixtures/then.go, test/e2e/fixtures/when.go, test/e2e/manifests/mysql.yaml, test/e2e/manifests/postgres.yaml, test/e2e/smoke/basic.yaml, test/e2e/smoke_test.go, test/e2e/workflow_template_test.go
=> fix(archive): upsert archive + ci: Pin images on CI, add readiness probes, clean-up logging and other tweaks

.circleci/config.yml, Makefile, hack/update-manifests.sh, manifests/quick-start-no-db.yaml, manifests/quick-start-none.yaml, manifests/quick-start/no-db/kustomization.yaml, manifests/quick-start/no-db/overlays/workflow-controller-configmap.yaml, test/e2e/argo_server_test.go, test/e2e/cli_test.go, test/e2e/fixtures/persistence.go, test/e2e/manifests/no-db.yaml, test/e2e/manifests/no-db/kustomization.yaml, test/e2e/manifests/no-db/overlays/argo-server-deployment.yaml, test/e2e/manifests/no-db/overlays/workflow-controller-deployment.yaml, workflow/controller/config_controller.go
Checklist:
This PR adds:
1. Fixes the nil deref in the GC.
1. Adds a new `no-db` test suite and set-up options, e.g. `make start DB=no-db`
=> fix: nil pointer in GC

test/e2e/argo_server_test.go
=> fix: Only run archived wf testing when persistence is enabled

Makefile
`-d` is not avaliable in my system:
```
kubectl -n argo get `kubectl -n argo get secret -o name | grep argo-server` -o jsonpath='{.data.token}' | base64 -d
base64: invalid option -- d
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
-h, --help     display this message
-D, --decode   decodes input
-b, --break    break encoded string into num character lines
-i, --input    input file (default: "-" for stdin)
-o, --output   output file (default: "-" for stdout)
```
Seems like it's safer to use `--decode`
=> fix: "base64 -d" not always available, using "base64 --decode"

Makefile
=> build: adds `make env` to make testing easier

workflow/executor/pns/pns.go
=> fix: container ID parser in PNS executor for CRI-O. Fixes #2095

test/e2e/cli_test.go
=> fix: Skip running --token testing if it is not on CI

ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Fixes #2102 
Demo (notice `managedNamespace` redirection still happens): https://cl.ly/4f3a073db983
=>  fix: Namespace redirects no longer error and are snappier

workflow/executor/resource.go
Fix https://github.com/argoproj/argo/issues/2078
Test:
Tested on minikube with the yaml mentioned [here](https://github.com/argoproj/argo/issues/2078#issuecomment-579407628). Manually delete the `Job` resource. Then `kubectl get wf zjl-k8s-jobs -o yaml` and the output is as expected:
```
......
status:
finishedAt: "2020-01-29T04:28:48Z"
message: Resource Job.batch/pi-job-gsvvn in namespace default has been deleted
somehow.
nodes:
zjl-k8s-jobs:
displayName: zjl-k8s-jobs
finishedAt: "2020-01-29T04:28:48Z"
id: zjl-k8s-jobs
message: Resource Job.batch/pi-job-gsvvn in namespace default has been deleted
somehow.
name: zjl-k8s-jobs
phase: Failed
startedAt: "2020-01-29T04:28:36Z"
templateName: pi-tmpl
type: Pod
phase: Failed
startedAt: "2020-01-29T04:28:36Z"
......
```
=> fix: Fix Resource Deletion Bug

ui/src/app/webpack.config.js
Fixes: #2103 
Same problem and fix as https://github.com/argoproj/argo-cd/issues/2114 and https://github.com/argoproj/argo-cd/pull/2162
=> fix: Disable webpack dot rule

cmd/argo/commands/delete.go, pkg/apiclient/classic-workflow-service-client.go, test/e2e/cli_test.go, test/e2e/fixtures/when.go
Checklist:
Depended on by #2116
This PR is primarily aimed at migrating `argo delete` to using the `apiclient`. I present it as a good example of this because:
* I did quite a bit of refactoring of `delete.go` and it behaves slightly different.
* I added support for `--selector` as I thought we should not want out tests to delete workflows not labelled with `argo-e2e'. This is a new feature.
* I wrote 4 new e2e tests.
* I actually delete more production code than I wrote.
@whynowy @simster7 @sarabala1979
=> feat: Add support to delete by using labels. Depended on by #2116

docs/cron-workflows.md
=> docs: Add CronWorkflow usage docs

ui/src/app/app.tsx, ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx, ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/login/components/login.tsx, ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-submit.tsx
Added missing uiUrl calls and fixed browser history initialization.
Checklist:
=> fix(ui): fixed ui navigation issues with basehref. Fixes #2113

ui/src/app/shared/services/requests.ts, ui/src/app/shared/services/workflows-service.ts, ui/src/app/workflows/components/workflow-artifacts.tsx
I've not tested this yet, and I don't /really/ know what I'm doing. But
the onerror handler currently breaks the logs UI as it does not result
in the catch getting triggered.
=> fix: logs UI should fall back to archive

Dockerfile, Dockerfile.dev
=> fix: Add certs to argocli image. Fixes #2129

persist/sqldb/migrate.go
=> feat: Update archived workflow column to be JSON. Closes #2133

server/artifacts/artifact_server.go
Fixes: https://github.com/argoproj/argo/issues/2163 by adding the [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header with the desired file extension.
Thanks @ddseapy for reporting this bug.
=> fix: Specify download .tgz extension

ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/shared/components/resource-submit.tsx, ui/src/app/workflow-templates/components/workflow-template-details/workflow-template-details.tsx, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-submit.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Closes #2165 by improving error handling to display the JSON response message when available, and not allow the submission of malformed yamls while displaying the reason they are malformed.
Also brings this functionality to CronWorkflow and WorkflowTemplate submission, which previously did not have it.
=> chore: Improved error handling and refactor

persist/sqldb/offload_node_status_repo.go, test/e2e/fixtures/e2e_suite.go, workflow/controller/controller.go
=> fix(offloading): Correctly deleted offloaded data. Fixes #2206

README.md
=> docs: Add BasisAI to the company list

ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Closes https://github.com/argoproj/argo/issues/2231.
Checklist:
=> feat: Reduce API calls when changing filters. Closes #2231

docs/workflow-templates.md
I'm guessing "reusable checks of YAML" should read "reusable chunks of YAML."
Checklist:
=> fix(docs): Corrects presumed typo, checks --> chunks

cmd/argo/commands/common.go, cmd/argo/commands/get.go, cmd/argo/commands/get_test.go, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/operator.go, workflow/util/util.go
Here I chose a half-width character `ǁ` (U+01C1) for suspended nodes. I wanted to look for characters where the two bars are separated a bit more but couldn't find any. For its color, I chose cyan since the node is still a running node. Closes #1896.
By the way, could anyone please point me to the test files for commands? I don't see any in the repo.
Screenshot:
Checklist:
=> feat: Add a new symbol for suspended nodes. Closes #1896

ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/shared/services/archived-workflows-service.ts
=> feat(ui): Add filters for archived workflows. Closes #2259

cmd/argo/commands/root.go
CLI had watch command listed twice, fixed by removing duplicate command call.
Checklist:
=> fix: Removed duplicate Watch Command

cmd/argo/commands/resubmit.go, pkg/apiclient/classic-workflow-service-client.go, test/e2e/cli_test.go, test/e2e/testdata/exit-1.yaml
Checklist:
See #2116
Can be merged as soon as approved.
=> chore(cli): Migrate `argo resubmit` to use client API. See #2116

workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix(sequence): broken in 2.5. Fixes #2248

test/e2e/functional/param-aggregation.yaml, test/e2e/functional/parameter-aggregation.yaml, test/e2e/functional_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix(controller): Get correct Step or DAG name. Fixes #2244

Makefile
Checklist:
I have already merge this to release-2.5 and release-2.6. It does fully automate releases yet, but makes the process simpler and more reliable by making sure you are clean, dist is created, and you build before you publish.
Please merge as soon as approved and builds are green.
=> build: Improve reliability of release.

docs/getting-started.md, manifests/README.md
Checklist:
The namespace changes feel strange to me... is there a reason why getting-started namespaces to `argo` by default? If not, I'd as soon drop `-n argo` from all the below commands and just add a link pointing to the namespaced install yaml.
=> chore: update getting-started guide for 2.5.2 and apply other tweaks

workflow/controller/controller_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go, workflow/validate/validate_test.go
=> feat: Allow retry strategy on non-leaf nodes, eg for step groups. Fixes #1891

Dockerfile, Dockerfile.dev, test/e2e/images/cowsay/Dockerfile
Using a --no-install-recommends when apt-get installing packages.
This will result in a smaller image size.
Checklist:
=> fix(Dockerfile): Using `--no-install-recommends` (Optimization)

examples/template-on-exit.yaml, workflow/controller/dag.go
Currently we run onExit handlers from a dependent node. Simplify logic so that `onExit` handlers are run by their own respective nodes. This will simplify implementations of #1839 and #2254
=> fix: Simplify completion detection logic in DAGs

docs/variables.md, workflow/common/common.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go
Closes: https://github.com/argoproj/argo/issues/2242
=> feat: Expose workflow.paramteres with JSON string of all params

workflow/executor/docker/docker.go
This ensure that we properly close both stdout and stderr pipes after
executing docker logs.
Checklist:
=> fix(docker): remove NopCloser from the executor. See #2261

docs/getting-started.md
=> chore: update getting started guide to use 2.6.0

server/workflow/workflow_server.go, test/e2e/cli_test.go, test/e2e/expectedfailures/empty-parameter-dag.yaml, test/e2e/expectedfailures/empty-parameter-steps.yaml, workflow/validate/validate.go
Fixes #2313
The issue was introduced in #1744, where `ResolveTemplate()` in `context.go` does not call `ProcessArgs()` any more.
Checklist:
=> fix: Always validate templates with different input parameters. Fixes #2313

workflow/executor/docker/docker.go
This PR fixes #2261. Multireader concactinates, not combines, the two
streams, this meant that we blocked on stdin if stderr was not
completely buffered.
In addition, this implementation ensures that we call Wait() on the
command, and any error is return by Close(). Godoc for
exec.Cmd.Std(out|err)Pipe, confirms that we do not need to close those
pipes.
This PR also ensures that we do not leak go routines in the even that
cmd.Start() fails.
=> fix(docker): fix streaming of combined stdout/stderr

docs/getting-started.md
We currently have specific version information in Getting Started, forcing us to update it with every release. Make Getting Started agnostic to versions by moving specific download instructions to each release and redirecting users there, as well as showing manifests with the `stable` tag as opposed to the specific version tag.
Checklist:
=> docs: Make Getting Started agnostic to version

ui/src/app/shared/services/workflows-service.ts
Currently Argo UI is displaying just the last 20 logs when opening logs of a step, removing the tailLines=20 logOptions argument fixes this issue.
Checklist:
=> fix(ui): Removed tailLines from EventSource

ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
Fixes #2372. Thanks @foobarbecue!
=> fix: Say no logs were outputted when pod is done

examples/README.md
Running this example as written gives `json: cannot unmarshal number into Go struct field Backoff.workflow.spec.templates.retryStrategy.backoff.duration of type string`
Checklist:
=> fix (docs): change duration to a string

test/e2e/smoke/artifact-passing.yaml, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Description:
Closes #1722.
The controller has a behavior that when a template has an artifact whose path overlaps with any of the volumes to be mounted in this template, it will not load the artifact into the default artifact directory but to the volume to be mounted. It should mount the volume to the init container as well before doing so. However, when we check for volumes that should be mounted to the init container, we miss out volumes defined in script templates, and thus artifacts cannot be loaded properly only for this type of template. To be safe, I also checked other types of templates, and I think we've covered all cases, i.e., container templates and script templates.
Updated E2E to cover this case and tested manually with the following template (basically fetched from the …
=> fix(controller): Mount volumes defined in script templates. Closes #1722

workflow/config/config.go, workflow/controller/controller.go
Bug fix for the last comments here #2331 (review) which were not fixed before master.
Checklist:
=> fix(doc strings): Fix bug related documentation/clean up of default configurations #2331

ui/src/app/shared/services/workflows-service.ts, ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Fixes #2384. This new behavior reflects `argo watch` correctly.
Before:
After:
Behavior if `len(children) > 1` is conserved:
=> fix: Don't display Retry Nodes in UI if len(children) == 1

ui/src/app/shared/components/yaml/yaml.scss, ui/src/app/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.scss
Closes #2378.
Also I updated the min-height of the editor. The default 50px was annoying.
Screenshot:
Checklist:
=> feat(ui): Use a monospace font family for yaml editors. Closes #2378

.dockerignore, Dockerfile
=> fix: Correctly report version. Fixes #2374

docs/CONTRIBUTING.md
The current suggested way to get the auth token for argo when deployed don't seam to work. This PR contains a fix where: 
```bash 
./dist/argo auth token
```
is suggested to replace 
```bash 
./dist/argo token
```
Checklist:
=> docs: Update CONTRIBUTING.md with argo auth token command fix. 

manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/namespace-install/argo-server-rbac/argo-server-role.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-no-db.yaml, manifests/quick-start-postgres.yaml, test/e2e/manifests/mysql.yaml, test/e2e/manifests/no-db.yaml, test/e2e/manifests/postgres.yaml
Checklist:
When I use retry button in the argo-server, it will response:
```
{"error":"pods \"continue-on-fail-s6n6s-2335603486\" is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot delete resource \"pods\" in API group \"\" in the namespace \"argo\"","code":2,"message":"pods \"continue-on-fail-s6n6s-2335603486\" is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot delete resource \"pods\" in API group \"\" in the namespace \"argo\""}
```
I cannot understand why the argo-server will delete the pod. However, this PR will fix this problem.
=> fix(server): Update manifests to figure "Unable to retry workflow".

pkg/apis/workflow/v1alpha1/workflow_types.go, util/util.go
Fixes #2413 
In versions <v2.5.0 we allowed the step.arguments.parameters.value field to be a number as well as a string. In version >=v2.5.0 a custom unmarshaller was implemented that enforced stricter type checking, but we still want to add backwards-compatibility to workflows. Here we manually attempt to convert a number to a string field.
This current solution is hacky, and am open to suggestions in improving it.
=> fix: Allow numbers in steps.args.params.value

workflow/controller/operator_template_scope_test.go
=> test: Skip flakey tests in operator_template_scope_test.go. See #2432

ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/shared/components/namespace-filter.tsx, ui/src/app/shared/utils.ts, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
=> feat(ui): cache namespace selection. Closes #2439

persist/sqldb/workflow_archive.go
=> fix(archive): Fix edge-cast error for archiving. Fixes #2427

workflow/controller/operator.go
Fixes: https://github.com/argoproj/argo/issues/2415
The check introduced in #1762 `woc.wf.Status.Phase != wfv1.NodeSucceeded` was insufficient because at that point in the operation, the workflow itself is not yet marked as succeeded. This lead to PVCs never being deleted. Switched the logic to `woc.wf.Status.Phase == wfv1.NodeError || woc.wf.Status.Phase == wfv1.NodeFailed ` to keep PVCs on Failure/Error explicitly.
Regardless, I believe this behavior should be an opt-in feature flag. Users should be able to use if they want their PVCs deleted regardless of status. @dtaniwaki Do you want to own implementing the feature flag behavior?
=> fix: Delete PVCs unless WF Failed/Errored

test/e2e/functional_test.go, workflow/common/common.go
=> test: Maybe fix TestPendingRetryWorkflowWithRetryStrategy. Fixes #2446

examples/artifact-path-placeholders.yaml
Without this fix, the submission failed with
``` raw
sh: can't create /outputs/actual-lines-count/data: nonexistent directory
tee: /outputs/text/data: No such file or directory
```
=> fix(example) make dir if needed

persist/sqldb/sqldb.go, workflow/config/config.go
=> fix(persistence): set postgres ssl config to string Fixes #1866

examples/README.md, examples/retry-backoff.yaml, examples/suspend-template.yaml
Missed this when I fixed the docs here: 96af36d85d70d4721b1ac3e6e0ef14db65e7aec3
Checklist:
=> fix: Duration must be a string. Make it a string.

go.mod, go.sum, persist/sqldb/mocks/WorkflowArchive.go, persist/sqldb/null_workflow_archive.go, persist/sqldb/workflow_archive.go, server/workflowarchive/archived_workflow_server.go, server/workflowarchive/archived_workflow_server_test.go, test/e2e/argo_server_test.go, ui/package.json, ui/src/app/archived-workflows/components/archived-workflow-filters/archived-workflow-filters.scss, ui/src/app/archived-workflows/components/archived-workflow-filters/archived-workflow-filters.tsx, ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/shared/services/archived-workflows-service.ts, ui/yarn.lock
=> feat: search archived wf by startat. Closes #2436

api/openapi-spec/swagger.json, docs/configure-artifact-repository.md, go.mod, go.sum, pkg/apiclient/cronworkflow/cron-workflow.swagger.json, pkg/apiclient/workflow/workflow.swagger.json, pkg/apiclient/workflowarchive/workflow-archive.swagger.json, pkg/apiclient/workflowtemplate/workflow-template.swagger.json, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/artifacts/artifacts.go, workflow/artifacts/s3/s3.go
This allow you to set s3 configuration useSDKCreds: true to tell the
exec image to pull configuration from IRSA environment variables, or any supported aws sdk credentials following the default priority order
Checklist:
=> feat: Add support for IRSA and aws default provider chain.

api/openapi-spec/swagger.json, pkg/apiclient/_.primary.swagger.json
I failed to double-check the ParallelSteps child type in swagger.json and thus caused this: argoproj-labs/argo-client-gen#5
Tested `make java` in argo-client-gen. Still get a build error, but a different one (I don't think openapi-generator/java knows how to deal with nested lists). I'll open another issue for that one.
Checklist:
=> fix: ParallelSteps child type so replacements happen correctly

Makefile
When building an image from a detached head there is no git tag and the Makefile fails. In that case use the git sha hash.
Checklist:
=> fix: Build image with SHA tag when a git tag is not available

Dockerfile, Dockerfile.dev, Makefile
This reverts commit c724c7c1afca646e09c0cb82acf8b59f8c413780. The commit breaks `workflow-controller` and `argo-server` with error:
```standard_init_linux.go:190: exec user process caused "exec format error"```
Checklist:
=> chore: Revert "feat: Add support for arm64 platform (#2364)"

cmd/argo/commands/list.go, test/e2e/cli_test.go, test/e2e/smoke/basic-generate-name.yaml
This PR ensures that the returned list of workflows has a max length of `chunkSize`. Previously we apply `chunkSize` before all the filtering such that the returned list may have fewer items than expected.
Closes #2420.
Checklist:
=> fix(cli): Rearrange the order of chunk size argument in list command. Closes #2420

docs/workflow-controller-configmap.yaml, docs/workflow-controller-configmap_v2.7+.yaml
=> docs: Add separate ConfigMap doc for 2.7+

workflow/validate/validate.go, workflow/validate/validate_test.go
Fixes: #2057 (Thanks @samath117)
Allows for global workflow parameter names to be resolved at runtime
=> fix: Allow runtime resolution for workflow parameter names

pkg/apiclient/argo-server-client.go
=> fix: Increase client gRPC max size to match server. Fixes #2513

api/openapi-spec/swagger.json, go.mod, go.sum, pkg/apiclient/cronworkflow/cron-workflow.swagger.json, pkg/apiclient/workflow/workflow.swagger.json, pkg/apiclient/workflowarchive/workflow-archive.swagger.json, pkg/apiclient/workflowtemplate/workflow-template.swagger.json, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/artifacts/artifacts.go, workflow/artifacts/gcs/gcs.go
=> chore: minor fix and refactory

docs/workflow-controller-configmap_v2.7+.yaml
=> chore(docs): Update docs for useSDKCreds

test/e2e/cli_test.go, workflow/common/util_test.go
Checklist:
bug fix
`assert.Error` doesn't check error messages while `assert.EqualError` does.
=> fix: fix wrong assertions

server/cronworkflow/cron_workflow_server.go, server/cronworkflow/cron_workflow_server_test.go, server/workflow/workflow_server.go
=> fix: Validate CronWorkflow before creation

USERS.md
=> docs: Add Riskified to the user list

Dockerfile, Dockerfile.dev
This upgrades the executor base image from debian:9.6-slim to
debian:10.3-slim. This fixes a number of CVEs. As of today,
debian:9.6-slim has 10 high, 11 medium, and 60 low CVEs [1], while
debian:10.3-slim has 0 high, 4 medium, and 43 low CVEs [2].
1 - https://snyk.io/test/docker/debian%3A9.6-slim
2 - https://snyk.io/test/docker/debian%3A10.3-slim
Checklist:
=> chore(docker): upgrade base image for executor image

docs/workflow-templates.md
=> chore: fix typos in the workflow template docs

config/config.go, config/controller.go, config/controller_test.go
=> fix: Fixes empty/missing CM. Fixes #2285

ui/src/app/workflows/components/workflow-list-item/workflow-list-item.tsx
A small change to UI to include "DURATION". See the last "DURATION" row in the example image.
=> feat: Show workflow duration in the index UI page

ui/src/app/workflows/components/workflow-list-item/workflow-list-item.tsx, workflow/common/util.go, workflow/common/util_test.go, workflow/controller/operator.go
=> fix: Fix bug in deleting pods. Fixes #2571

workflow/executor/resource.go
It's correct but make people confuse.
Checklist:
=> style: Correct the confused logic in resource executor

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #2560 
When using a retry node, we would add the outputs of the retry node instead of the last child to the scope. Changed to add the outputs of the last child node.
Wonder how this went undetected for so long.
=> fix: Use outputs of last child instead of retry node itslef

workflow/common/serviceaccount.go, workflow/common/util.go, workflow/controller/operator.go, workflow/executor/executor.go
I got an error "%s pvc has already exists with different ownerreference" when trying to deploy my workflow and couldn't find out what PVC was causing the error, so I fixed the formatting of the error message. I also searched for other similar issues in the codebase and changed them too.
I wasn't sure if it would be correct to always return code `errors.CodeNotFound`, so I left them empty ("") for now.
Checklist:
=> fix(error handling): use Errorf instead of New when throwing errors with formatted text

ui/src/app/app.tsx
Before:
After:
Top is WorkflowTemplate, bottom is ClusterWorkflowTemplate
=> fix: Fix WorkflowTemplate icons to be more cohesive

go.mod, go.sum, test/e2e/cli_test.go, test/e2e/fixtures/e2e_suite.go
=> test: Fix teething problems

docs/workflow-archive.md, persist/sqldb/migrate.go
=> fix: Support minimal mysql version 5.7.8. Fixes #2625

persist/sqldb/workflow_archive.go
=> chore: Use error equals instead of strings.Contains

ui/src/app/shared/components/resource-submit.tsx
Checklist:
When uploading a workflow, or submittint a template, it is more likely that one just wants to submit the workflow by simply modifying parameter values. This also makes Workflow / WorkflowTemplate submissisons less scary for users not familiar with the Worklow YAML itself, as they can simply focus on the top part of the screen and ignore the YAML edit box below.
A future improvement could include an option to hide the YAML editor completely from the UI, ie. where one wants to give access to the UI to people who are allowed to manage Workflow execution but not modify Workflows.
I am requesting input on the styling and paddings here, I think it could look a bit better.
This commit was broken out from https://github.com/argoproj/argo/pull/2635
=> feat(UI): Move Workflow parameters to top of submit

workflow/controller/exec_control.go, workflow/controller/operator_test.go, workflow/controller/workflowpod.go
=> fix: onExit step gets stuck if the workflow exceeds activeDeadlineSeconds. Fixes #2603

Makefile, hack/maybe-skip-job.sh
=> build: Fix codegen for releases

docs/running-locally.md
According to the doc which is currently linked in - one is to install protoc via `brew install protobuf`, and not via `brew install protoc`.
Checklist:
=> chore: update running-locally.md - corrects protoc install command

Makefile
Ensure we always pull latest binaries
=> fix: Don't use docker cache when building release images

Dockerfile, Makefile, test/e2e/fixtures/util.go, ui/package.json, ui/src/app/webpack.config.js
=> build(ui): Fix compression of UI package.

manifests/base/workflow-controller/workflow-controller-metrics-service.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-no-db.yaml, manifests/quick-start-postgres.yaml
While adding a name is optional from a Kubernetes standpoint since there
is only one port listed, the named port makes using Prometheus easier.
There's a targetPort option for Prometheus' ServiceMonitor Custom
Resource, but this targetPort doesn't relate to the service's
targetPort, but in fact the containers' targetPort pointed at by the
service [1]. And since the workflow-controller deployment doesn't
actually explicitly list the ports the targetPort configuration on a
ServiceMonitor does nothing. So having the named port on the service's
port makes it much easier to use for Prometheus.
1 - https://github.com/coreos/prometheus-operator/issues/2515
I'm not actually sure how to use this service with Prometheus-operator without this named port. I considered this commit a feature, but might …
=> feat(manifests): add name on workflow-controller-metrics service port

ui/src/app/login/components/login.tsx
=> fix: Improve cookie security. Fixes #2759

workflow/util/util.go
=> feat: Make phase and templateRef available for unsuspend and retry selectors

api/openapi-spec/swagger.json, pkg/apiclient/workflow/workflow.swagger.json, pkg/apis/workflow/v1alpha1/common.go, pkg/apis/workflow/v1alpha1/generated.proto, ui/src/app/shared/template-resolution.ts, ui/src/app/shared/utils.ts, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, ui/src/app/workflows/components/workflow-yaml-viewer/workflow-yaml-viewer.tsx, ui/src/models/workflows.ts
=> fix: Fix template resolution in UI

Makefile, test/e2e/fixtures/e2e_suite.go, test/e2e/manifests/mixins/workflow-controller-deployment.yaml
=> test: Get tests running on release branches

cmd/argo/commands/client/conn.go, docs/tls.md
=> docs: Update tls.md

test/e2e/functional/global-scope.yaml, test/e2e/functional_test.go, workflow/controller/operator_test.go, workflow/controller/steps.go
Fixes: https://github.com/argoproj/argo/issues/2823
=> fix: Add Step node outputs to global scope

docs/configure-artifact-repository.md
Support for _not_ tar.gz'ing output artifacts has been added. Expanded descriptions will hopefully help users discover that new capability.
Checklist:
=> chore: note that tar.gz'ing output artifacts is optional

docs/variables.md, workflow/common/common.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go, workflow/validate/validate_test.go
Reopening #2810
This PR exposes workflow.Spec.ServiceAccountName as global variable "workflow.serviceAccountName" similar to "workflow.namespace".
Issue: #2794 
Checklist:
=> feat: expose workflow.Spec.ServiceAccountName as global variable. See #2794

.github/ISSUE_TEMPLATE/bug_report.md, cmd/argo/commands/root.go, pkg/apiclient/apiclient.go, test/e2e/manifests/mixins/argo-server-deployment.yaml
Checklist:
To help get more diagnostics for errors.
=> feat(CLI): Add -v and --verbose to Argo CLI

cmd/argo/commands/common.go, cmd/argo/commands/get.go
=> chore: Display wf.Status.Conditions in CLI

workflow/cron/operator.go
=> fix: Don't error when deleting already-deleted WFs

docs/getting-started.md
Fixing the `ConfigMap` so that artifact works out of the box as advertised on the label
Checklist:
=> docs: Update getting-started.md

.circleci/config.yml, Makefile, test/e2e/cli_test.go, test/e2e/cli_with_server_test.go, test/e2e/cron_test.go, test/e2e/functional/stop-terminate.yaml, test/e2e/functional_test.go, test/e2e/testdata/sleep-3s.yaml, workflow/executor/docker/docker.go
Fixes: #2623 
Fixes: #2833 
Fixes: #2620
=> test: Fixes various tests

docs/configure-artifact-repository.md, docs/default-workflow-specs.md, docs/getting-started.md, docs/workflow-controller-configmap.md
Fix broken code introduced with https://github.com/argoproj/argo/pull/2872
Also update each ConfigMap examples
Checklist:
=> fix: ConfigMap syntax

USERS.md
We're are very happy with it.
We perform various tasks around it, mostly:
- Automatic flat enrichment (adding furniture to make them look prettier)
- Baking of 3D models of flats (using blender in a container)
- Automatic batch processing of some 3D models of furniture and decorations
Checklist:
=> docs(users): Adding Habx to the users list

server/workflow/workflow_server.go, test/e2e/cli_test.go, test/e2e/cli_with_server_test.go, workflow/controller/operator_test.go, workflow/util/util.go, workflow/util/util_test.go
Checklist:
Fixes https://github.com/argoproj/argo/issues/2621
=> fix(controller): Workflow stop and resume by node didn't properly support offloaded nodes. Fixes #2543

workflow/controller/dag.go, workflow/controller/operator.go, workflow/controller/steps.go
=> feat(controller): Remove the excessive logging of node data

ui/src/app/workflows/components/workflow-details/workflow-details.tsx
This is for the log button (example workflow link) in the top bar:
By default the current window will be redirected to the link. A new tab will be opened if ctrl is pressed when the link is clicked.
Closes #2887.
Checklist:
=> feat(ui): Allow opening workflow logs in a new tab; Closes #2887

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #2923 
Don't update the backoff message with "live" seconds:
```
Retrying in 5 seconds...
Retrying in 4 seconds...
```
These messages cause the entire workflow to be re-operated upon unnecessarily. Instead simply state the back-off duration:
```
Backoff for 8 seconds
```
=> fix: Don't update backoff message to save operations

examples/k8s-orchestration.yaml
This is a bugfix for one of the examples `k8s-orchestration.yaml` where the `print-generated-numbers` pod has the error `Error: unknown flag: --show-all`
Checklist:
=> fix(examples): Error with unknown flag: --show-all

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/controller/exec_control.go, workflow/controller/operator.go
Fixes #2956 
Issue was that a DAG would not be marked as failed until all of its retries got exhausted. However, if a Workflow is Shutdown before this happens, the DAG would be classified as Running indefinitely.
This fix only allows a DAG to be marked as running before all of its retries got exhausted if its nodes would execute under the current (or lack of) ShutdownStrategy.
=> fix: Consider Shutdown when assesing DAG Phase for incomplete Retry node

docs/variables.md, examples/retry-with-steps.yaml, workflow/common/common.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/validate/validate.go
- add `pod.retryAttempt` that reports the retry attempt number starting at 0 for first attempt and increasing by 1 each attempt.
- only executes on nodes with `retryStrategy` defined.
- updated the `examples/retry-with-steps.yaml` to demonstrate usage.
- updated the `docs/variables.md` to describe variable.
See #2808 and #2898 for enhancement request.
Checklist:
=> feat: add local variable pod.retryAttempt (see #2808, #2898)

workflow/controller/exec_control.go, workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes #2901 
MaxDuration now counts from first node start instead of first node finish. It is more reliable and makes more sense given the spec
Also adds a short-circuit feature that would fail a retry if waiting for the current backoff would exceed the max duration, saving the time it would have spent waiting.
=> fix: Begin counting maxDuration from first child start

workflow/executor/pns/pns.go
Bug in PNS executor when sidecars need to be `SIGKILL`'d (likely a missed line).
=> fix(executor/pns): remove sleep before sigkill

workflow/controller/operator.go, workflow/controller/operator_metrics_test.go, workflow/controller/steps.go
There was a slight bug in the inference logic that would not emit metrics for a node that was created and completed all within the same operation. This fixes that.
=> fix: Consider metrics that were created and completed in the same operation

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go, workflow/executor/executor.go
This reverts commit a1ac8bcf548c4f8fcff6b7df25aa61ad9e4c15ed.
Checklist:
See #3043
=> fix(artifacts): Revert allow tar check to be ignored. Reverts #3024

.circleci/config.yml, Makefile, Procfile, manifests/quick-start-mysql.yaml, manifests/quick-start-no-db.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/mysql/kustomization.yaml, manifests/quick-start/no-db/kustomization.yaml, manifests/quick-start/postgres/kustomization.yaml
Fixes: #2965 
Checklist:
`argo-server` and `workflow-controller` and started using `goreman` same as Argo CD, which foreground them and logs which prepend the app name:
We label resources and can prune resources not needed. 
This can be merged as soon as green.
=> build: Use goreman for starting locally.

test/e2e/functional_test.go
=> test: fix TestContinueOnFailDag. Closes #2624

README.md
The support of Alibaba Cloud OSS has been added previously by our team members in https://github.com/argoproj/argo/pull/1919.
Checklist:
=> docs: Add Alibaba Cloud OSS to the list of supported artifacts

USERS.md
=> docs: add AppDirect to the list of users

workflow/common/common.go, workflow/common/common_test.go
Fixes: #3122
It might be possible to receive a valid unstructured workflow that fails a cast. `getWfPriority` already accounts for this:
https://github.com/argoproj/argo/blob/6e5dd2e19a3094f88e6f927f786f866eccc5f500/workflow/controller/controller.go#L525-L528
We do not want to panic if this happens as the controller itself will resolve the Workflow and – failing that – it will output a graceful error.
=> fix: Remove unnecessary panic

test/e2e/ui/ui-workflow-error.yaml, ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx, ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx, ui/src/app/shared/components/phase-icon.tsx, ui/src/app/shared/components/phase.tsx, ui/src/app/workflows/components/index.ts, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx, ui/src/app/workflows/components/workflow-panel/workflow-panel.tsx, ui/src/app/workflows/components/workflow-summary-panel.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
Checklist:
Fixes #3091
* Add a panel that shows the error instead of the loading animation if the DAG cannot be loaded.
* Tidy up the summary panel:
* Colorise phase
* Show relative start and finish time.
=> fix(ui): Display error message instead of DAG when DAG cannot be rendered. Fixes #3091

Makefile
This PR fixes the following two errors while running `make start` which are caused by incorrect paths to these two binaries:
```
staticfiles -o server/static/files.go ui/dist/app
/bin/bash: staticfiles: command not found
make: *** [Makefile:182: server/static/files.go] Error 127
➜  argo git:(master) ✗ go get bou.ke/staticfiles
go: finding bou.ke/staticfiles latest
```
```
grep '127.0.0.1 *mysql' /etc/hosts
127.0.0.1 mysql
env ALWAYS_OFFLOAD_NODE_STATUS=false LOG_LEVEL=debug VERSION=latest AUTH_MODE=hybrid goreman -set-ports=false -logtime=false start
env: goreman: No such file or directory
make: *** [Makefile:374: start] Error 127
```
Checklist:
=> build: Fix path to staticfiles and goreman binaries

workflow/controller/controller.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/cron/controller.go, workflow/cron/operator.go, workflow/cron/operator_test.go, workflow/metrics/metrics.go, workflow/metrics/util.go
Closes: #3034
Currently only supports:
* Operation panics
* CronWorkflow submission errors
This interface should only be used for errors that are impossible to surface with custom metrics
=> feat(metrics): Report controller error counters via metrics. Closes #3034

docs/running-locally.md
=> docs: Add instructions on using Minikube as an alternative to K3D

docs/variables.md, workflow/common/common.go, workflow/controller/operator_test.go, workflow/controller/steps.go, workflow/controller/steps_test.go
Closes https://github.com/argoproj/argo/issues/3110
=> feat(metrics): Add node-level resources duration as Argo variable for metrics. Closes #3110

Makefile
SSO support is added in https://github.com/argoproj/argo/pull/2745 but this check should be optional.
Checklist:
=> build: Only check Dex in hosts file when SSO is enabled

docs/getting-started.md
=> docs: Update Getting Started

pkg/apis/workflow/v1alpha1/workflow_types.go, pkg/apis/workflow/v1alpha1/workflow_types_test.go
=> fix(metrics): Ensure stable desc/hash for metrics. Fixes #3193

USERS.md, docs/workflow-controller-configmap.yaml, go.mod, go.sum, manifests/quick-start-mysql.yaml, manifests/quick-start-no-db.yaml, manifests/quick-start-postgres.yaml, manifests/quick-start/base/argo-server-sso-secret.yaml, manifests/quick-start/base/overlays/workflow-controller-configmap.yaml, server/auth/sso/sso.go, server/auth/sso/sso_test.go
This change adds support for reading the SSO client ID value from a secret, just like the client secret is read already. That will make it easier to provide that the client ID value externally, via facilities like external secrets, which in turn makes rotating secrets much easier.
Besides adding unit tests, tested this by running `make start AUTH_MODE=sso` and verifying the login process with dex and its sample app.
Checklist:
=> feat(sso): Allow reading SSO clientID from a secret.

cmd/argo/commands/watch.go
Currently if we are watching a Workflow on the CLI and there are no new events from it, we don't refresh the screen. Since the screen contains a duration in seconds, we may perhaps be giving the impression that Workflow execution has stalled:
```
Name:                steps-vhd7c
Status:              Running
Created:             Thu Jun 11 11:51:33 -0700 (9 seconds ago)
Started:             Thu Jun 11 11:51:33 -0700 (9 seconds ago)
Duration:            9 seconds
STEP            TEMPLATE           PODNAME                 DURATION  MESSAGE
● steps-vhd7c  hello-hello-hello
└---● hello1   whalesay           steps-vhd7c-3181874478  9s
```
If this screen does not refresh, it could give the impression that execution has stalled since …
=> feat: Tick CLI Workflow watch even if there are no new events

workflow/ttlcontroller/ttlcontroller.go, workflow/ttlcontroller/ttlcontroller_test.go, workflow/validate/validate.go
=> fix: Support the TTLStrategy for WorkflowTemplateRef

cmd/argo/commands/delete.go, cmd/argo/commands/get.go, cmd/argo/commands/logs.go, cmd/argo/commands/resubmit.go, cmd/argo/commands/resume.go, cmd/argo/commands/retry.go, cmd/argo/commands/root.go, cmd/argo/commands/stop.go, cmd/argo/commands/suspend.go, cmd/argo/commands/terminate.go, cmd/argo/commands/wait.go, cmd/argo/commands/watch.go
=> chore(cli): Add examples of @latest alias for relevant commands. Fixes #3225

docs/variables.md
=> chore: Covered steps.<STEPNAME>.outputs.parameters in variables document

USERS.md, workflow/controller/operator.go, workflow/controller/operator_test.go
Summary
----
Fixes #2901
When a node fails due to a pod-deleted error (see code [here](https://github.com/argoproj/argo/blob/a7d8546cf9515ea70d686b8c669bf0a1d9b7538d/workflow/controller/operator.go#L833)), `FinishedAt` is unavailable and retry backoff doesn't work as expected. Backoff is crucial to handle the pod-deleted error since it usually happens when the cluster is under pressure.
This PR sets `FinishedAt` to system time when the pod is deleted. 
Tests
----
Verified with our internal load test:
* 3600 workflows
* 2 workflows created per second
Before: finishedAt is null, and workflow success rate is 66.1%.
```
foo-pipeline-xhwq8-3799176537:
boundaryID: foo-pipeline-xhwq8-2284472225
displayName: echo(2)
finishedAt: null
id: foo-pipeline-xhwq8-3799176537
message: pod deleted
name: …
```
=> fix(controller): set pod finish timestamp when it is deleted

manifests/quick-start-mysql.yaml, manifests/quick-start/mysql/mysql-deployment.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
=> chore: update mysql yaml port

workflow/common/common.go, workflow/util/util.go
Append an additional label so it's easy for user to see the name of the original workflow that has been resubmitted.
Checklist:
=> feat: Append previous workflow name as label to resubmitted workflow

workflow/util/util.go
Currently we are checking this for each iteration which is unnecessary.
Checklist:
=> fix: Avoid unnecessary nil check for annotations of resubmitted workflow

Makefile
I accidentally omitted the `v` when releasing `v2.8.2`, leading the docker images and manifests to use the tag `2.8.2` instead. While there were no issues (since _all_ the tags matched), we should ensure that all release tags contain a `v` for consistency.
I added a target to the `Makefile` to ensure this requirement is met.
```
$ make prepare-release VERSION=2.8.2
It looks like you're trying to use a SemVer version, but have not prepended it with a v (such as v2.8.2). The v is required for our releases. Do you wish to continue anyway? [y/N]n
$ make prepare-release VERSION=v2.8.2
rm -Rf dist/* ui/dist
...
```
=> build: Add warning to ensure 'v' is present on release versions

test/e2e/functional/output-jqfilter-parameters.yaml, workflow/executor/resource.go
When playing with jqFilter, the return value begins with double quotes and ends in double quotes, also followed by a newline: i.e.:
```
"parameter value"\n
```
Related PR : argoproj#1232
This commit ensure we do not insert extra double quotes and trailing new line when using
valueFrom: jqFilter to set the value of an output parameter for
resource templates.
Checklist:
=> fix(jqFilter)!: remove extra quotes around output parameter value

.gitignore, pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/artifacts/git/git.go, workflow/artifacts/git/git_test.go
Checklist:
Fixes #2343 
See #3246
* Write SSH private key to a temp file rather than `~/.ssh/id_rsa` so we don't delete my keys while testing 😡
* Add support for authentication when used with `fetch` or `revision`.
=> fix(git): Fixes Git when using auth or fetch. Fixes #2343

workflow/validate/validate.go, workflow/validate/validate_test.go
We encountered this problem when submitting workflows via the Argo server API. The included test illustrates the issue. It breaks with
```
--- FAIL: TestWorkflowWithWFTRefWithOverrideParam (0.00s)
validate_test.go:2570:
Error Trace:	validate_test.go:2570
Error:      	Received unexpected error:
spec.arguments.some-param.value is required
```
without the code fix.
Checklist:
=> fix(server): Fix validation of overridden ref template parameters.

docs/fields.md, examples/handle-large-output-results.yaml, examples/loops-big-array.yaml
This is admittedly niche, but was very important for my team.
=> docs: add example for looping over big arrays

workflow/controller/operator.go
=> fix(controller): Fix panic logging.

docs/README.md, docs/access-token.md, docs/rest-api.md
Checklist:
This PR documents how to create a token suitable for automation - i.e. an "access token"
=> docs: Document access token creation and usage

cmd/argo/commands/resubmit.go
=> feat: Allow to change priority when resubmitting workflows

ui/src/app/shared/components/checkbox-filter/checkbox-filter.tsx, ui/src/app/shared/components/pagination-panel.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
This PR:
* Saves pagination and label/phase selection preferences in the Workflow List page to local storage
* Adds a warning that Workflows aren't globally sorted when paginating them:
* Removes the count in the phase selection box since these only display the number of Workflows actually sent to the UI instead of the number of Workflows that exist in the cluster. This could cause some confusion
=> feat: Save pagination limit and selected phases/labels to local storage

hack/generate-proto.sh
Avoid error like the following:
```
+ go install k8s.io/code-generator/cmd/go-to-protobuf
+ go-to-protobuf --go-header-file=./hack/custom-boilerplate.go.txt --packages=github.com/argoproj/argo/pkg/apis/workflow/v1alpha1 --apimachinery-packages=+k8s.io/apimachinery/pkg/util/intstr,+k8s.io/apimachinery/pkg/api/resource,k8s.io/apimachinery/pkg/runtime/schema,+k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/api/core/v1,k8s.io/api/policy/v1beta1 --proto-import ./vendor
./hack/generate-proto.sh: line 12: go-to-protobuf: command not found
make: *** [Makefile:281: proto] Error 127
```
Checklist:
=> build: Fix path to go-to-protobuf binary

workflow/util/util.go
Removes the warning `Variable 'labels' collides with imported package name`. The imported package is `"k8s.io/apimachinery/pkg/labels"`.
Checklist:
=> chore: Avoid variable name collision with imported package name

Makefile, test/e2e/argo_server_test.go, test/e2e/cli_test.go, test/e2e/cli_with_server_test.go, test/e2e/cluster_workflow_template_test.go, test/e2e/cron_test.go, test/e2e/functional_test.go, test/e2e/metrics_test.go, test/e2e/smoke_test.go, test/e2e/workflow_template_test.go
=> test: Add e2e tags

USERS.md
We're using it to power pipelines around grants, publications and funding data.
Checklist:
=> docs: Wellcome is using Argo in our Data Labs division

examples/global-outputs.yaml
The global param needs to be passed as an input, not used directly.
Checklist:
=> fix(docs): Fix incorrect example of global parameter usage

workflow/metrics/metrics.go
Fixes: https://github.com/argoproj/argo/issues/3391
=> fix: Fix concurrency issues with metrics

cmd/argo/commands/wait.go
=> fix(cli): panic on wait command if event is null

cmd/argo/commands/watch.go, util/logs/workflow-logger.go
=> fix: No panic on watch. Fixes #3411

workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix: Script steps fail with exceededQuota

workflow/metrics/metrics.go
=> fix: Add struct-wide RWMutex to metrics

docs/argo-server.md
Minor docs update.
After moving from `argo-ui` to the `argo-server` Service, the URL has become outdated.
Checklist:
=> fix(docs): Update kubectl proxy URL

.github/workflows/docker-image.yml
As mentioned in #2747 Docker Hub Automated Build Hooks don't allow to build Windows images. As v2.9.0 comes with Windows support for argoexec and as you migrated CI to GitHub Actions also, it would make sense to use GitHub Actions also for building the Docker images.
I added a workflow file which builds and pushes the images for Linux (workflow-controller, argoexec, argocli) and Windows (argoexec only) whenever a new tag `v*` is pushed. I used the existing Docker Hub Hooks (https://github.com/argoproj/argo/blob/master/hooks/build) as a base for the scripts. The jobs building and pushing the images are appending `-linux` or `-windows` to the tag, a third job is creating a Manifest and pushes it to allow for multiarch. Example:
1. Tag `v2.9.0` is pushed
1. Job `build-linux` is building and …
=> chore: Use GitHub Actions to build Docker Images to allow publishing Windows Images

pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/common/util.go, workflow/controller/dag.go, workflow/controller/dag_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go, workflow/controller/steps.go
Fixes: https://github.com/argoproj/argo/issues/3431
Fixes: https://github.com/argoproj/argo/issues/3432
~**Not ready for review**.~
~Tests are not expected to pass~ Tests should now pass
~Still need to write new tests~ Added tests
=> fix: Ensure task dependencies run after onExit handler is fulfilled

cmd/argo/commands/logs.go, cmd/argo/commands/submit.go
This is useful when we want to see the snapshot of previously terminated container logs.
Checklist:
=> feat(cli): Allow to view previously terminated container logs

workflow/controller/operator_test.go
=> test(controller): Add memoization tests. See #3214 (#3455)

workflow/controller/controller.go, workflow/controller/pod/significant.go, workflow/controller/pod/significant_test.go
Checklist:
Fixes #3097
This is actually not the original problem in #3097, instead introduced by `SignificantPodChange`, but only when `kubectl delete --force pod ...` is used. The informer treats this delete as a update rather than a delete. @jessesuen @alexmt informer weirdness you might want to be aware of.
=> fix(controller): Fail workflow when pod is deleted with --force. Fixes #3097

workflow/controller/operator_test.go
We rely on this label so it's good to include this in the tests.
Checklist:
=> test(controller): Ensure resubmitted workflows have correct labels

workflow/controller/operator.go, workflow/controller/operator_metrics_test.go, workflow/controller/operator_test.go
Fixes: https://github.com/argoproj/argo/issues/3404
=> fix: Metric emission with retryStrategy

docs/metrics.md
Closes https://github.com/argoproj/argo/issues/3057
=> docs: Add controller-level metrics

USERS.md, cmd/argo/commands/server.go, docs/argo-server-auth-mode.md, docs/cli/argo_server.md, ui/src/app/login/components/login.tsx
=> fix: link to server auth mode docs, adds Tulip as official user

README.md
It's easier to see what is failing. Otherwise there are too many branches/builds in the list of GitHub Actions without manual filtering.
Checklist:
=> docs: Add link to GitHub Actions in the badge

cmd/argo/commands/completion.go
Checklist:
I added more bash completions so we can easily use `WorkflowTemplate`, `ClusterWorkflowTemplate`, and `CronWorkflow`.
=> feat: Support Bash Completions for More Resources

hack/docgen.go
Although very rare, if we were to remove or move a command, the old doc would be persisted. This PR removes all cmd docs before they're generated to ensure that only the desired docs remain.
=> build: Clear cmd docs before generating them

examples/hello-world.yaml
Running this without quotes results in the following error:
```
error: unable to decode "https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found f, error found in #10 byte of ...|trategy":false}},"sp|..., bigger context ...|abels":{"workflows.argoproj.io/archive-strategy":false}},"spec":{"entrypoint":"whalesay","templates"|...
```
Checklist:
=> fix: String interpreted as boolean in labels

workflow/controller/operator.go, workflow/controller/operator_test.go
This PR changes the backoff exponent to start from zero. See #3513 for details.
Checklist:
=> fix(controller): Backoff exponent is off by one. Fixes #3513

cmd/argo/commands/watch.go
=> fix: Panic on CLI Watch command

.github/workflows/ci-build.yaml, .github/workflows/gh-pages.yaml, .gitignore, .golangci.yml, Makefile, docs/swagger.md, hack/docgen.go, server/auth/sso/sso.go, test/e2e/fixtures/e2e_suite.go, test/e2e/fixtures/given.go, util/cmd/cmd.go, workflow/controller/exec_control.go, workflow/controller/operator.go, workflow/controller/steps.go, workflow/executor/executor.go, workflow/validate/validate_test.go
Checklist:
* Docker Image CI: 14m 
* CI: 14m
* Test: 5m -> 3m30
* Test E2E: 14m -> 13m
* Test Cron: 8m -> 8m
* Codegen: 8m -> 7m30
* UI: 32s
There are some slow tests, but no single test which is much worse that other tests. So no improvement to be made there today.
Fixes #3515
=> ci: Make builds marginally faster. Fixes #3515

.github/workflows/gh-pages.yaml, Makefile, hack/docgen.go, hack/main.go, hack/null_docgen.go, hack/parse_examples.go
Fixes https://github.com/argoproj/argo/issues/3529
=> fix: Fix links in fields doc

test/e2e/functional_test.go
=> fix: Skip TestStorageQuotaLimit

docs/argo-server.md, mkdocs.yml
=> docs: Document ingress set-up. Closes #3080

server/workflow/workflow_server.go, util/util.go, util/util_test.go
=> fix(controller): Fix bug in util/RecoverWorkflowNameFromSelectorString. Add error handling

docs/releasing.md
I created formulas for Argo CLI and Argo CD in the official homebrew-core repository (https://github.com/Homebrew/homebrew-core/pull/58259). This change changes the documentation to use that repo instead of your own tap.
=> docs: Migrate to homebrew-core (#3567)

docs/workflow-templates.md
The problem can only be seen in the `docs` at https://argoproj.github.io/argo/workflow-templates/
Githubs Markdown flavour does understand codeblocks within bullet points, but the compilation from `Markdown -> html`, seems to have a problem with that.
Checklist:
=> docs: Correct indentation for codeblocks within bullet-points for "workflow-templates"

workflow/common/util.go, workflow/controller/dag.go, workflow/controller/operator.go, workflow/controller/steps.go, workflow/controller/workflowpod.go, workflow/validate/validate.go
Fixes https://github.com/argoproj/argo/issues/3620
`template.New` panics on invalid templates while `template.NewTemplate` returns an error
=> fix: Don't panic on invalid template creation

Makefile, test/e2e/argo_server_test.go, test/e2e/cli_with_server_test.go
=> build: Disable TLS for dev mode. Fixes #3617

workflow/util/util.go, workflow/util/util_test.go
=> fix(controller): Carry-over labels for re-submitted workflows. Fixes #3622

server/workflow/workflow_server.go, util/logs/workflow-logger.go
Checklist:
Fixes #3608
I was incorrect in my solution to #3608. Re-establishing a watch can result in an infinite loop and therefore the server consuming 100% CPU. One instance when this happens is when `listOptions.resourceVersion` has "too old resource version" (e.g. old browser window left open). 
This PR does:
* Essentially reverts the original fix.
* Reports `v1.Status` errors as warnings rather than error in the `workflow-logger.go`.
* Return a `v1.Status` error back to the client for workflow watch.
=> fix(server): Report v1.Status errors. Fixes #3608

workflow/controller/operator.go, workflow/controller/operator_test.go
Fixes: https://github.com/argoproj/argo/issues/3647
=> fix: interface{} values should be expanded with '%v'

pkg/apis/workflow/v1alpha1/item.go, pkg/apis/workflow/v1alpha1/item_test.go, workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix(controller): Fix nested maps. Fixes #3653

ui/src/app/webpack.config.js
Following the changes in https://github.com/argoproj/argo/pull/3618, disable TLS in the dev webpack server
=> build: Disable TLS in dev server

workflow/controller/operator.go
Fixes: #3665
This line was removed in v2.9.0, but issues arose with the controller picking up outdated versions of workflows, operating on them, then attempting to update the resources on the cluster. Since the workflows were outdated, conflicts arose when attempting to update, causing our conflict resolution code to be invoked. The conflict resolution code was not perfect and workflow information was not correctly persisted, causing undefined behavior.
Testing procedure:
1. Make a build without this line.
2. Run multiple workflows
3. See undefined behavior (hanging pending pods, hanging running nodes, etc.); see the following log:
```
Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \""WF_NAME\"": the object has been modified; please apply your changes to …
```
=> fix: Re-introduce 1 second sleep to reconcile informer

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement_proposal.md
Checklist:
The goal of this PR is to more quickly capture useful information. Current, IMHO, we ask for too much we don't need and that no one provides. Instead, it would be better to ask for just 1 or 2 key items.
=> chore: Update issue templates

docs/argo-server.md
=> fix: Ingress docs

workflow/controller/controller.go
rewrite log into a structured form suggested in https://github.com/argoproj/argo/issues/2308
Avoid conflicting other branches or taking a lot of steps, I have firstly changed in the controller. 
Checklist:
=> feat(controller): controller logs to be structured #2308

workflow/executor/executor.go
Create a retryer for MainContainerStart.
Add exponential retry for watch pod that can cause issue when using k8sapi executor.
With help of @jsenon
Change after review of #3204
Fixes #3007
Checklist:
=> fix(executor): Add retry on pods watch to handle timeout.

.golangci.yml, test/e2e/cli_test.go, test/e2e/cli_with_server_test.go
Checklist:
~~* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~~
Closes #3750
=> build: Lint files tagged with `e2e`. Closes #3750

docs/scaling.md
The command line parameter is `--instanceid` not `--instance-id` as mistakenly written in the documentation
Checklist:
* [b ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [b] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.
=> docs: Correct typo in `--instanceid` 

pkg/apis/workflow/register.go, server/apiserver/argoserver.go, server/event/dispatch/operation.go, server/event/dispatch/operation_test.go, server/event/event_server.go, server/event/event_server_test.go, test/e2e/argo_server_test.go, test/e2e/fixtures/then.go, test/e2e/functional_test.go, workflow/controller/controller.go, workflow/controller/controller_test.go, workflow/events/event_recorder_manager.go
=> feat(server): Emit audit events for workflow event binding errors

workflow/controller/workflowpod.go
…cutor.
You also need to alter the argoexec image with setuid to really use rootless containers, but that can be done independently.
Motivation https://github.com/argoproj/argo/issues/3767
@jessesuen
Checklist:
=> feat(executor): Add SYS_CHROOT to ease the setup of non-root deployments with PNS. Closes #3767

workflow/controller/dag.go, workflow/controller/dag_test.go
Fixes https://github.com/argoproj/argo/issues/3739
Fixes https://github.com/argoproj/argo/issues/3780
Bug came to be because:
1. Task A is a TaskGroup (i.e. uses withItems, withParams, etc.)
2. Task A's tasks are empty (i.e. withParams: "")
3. Task B depends on Task A
4. Task B is a target task (i.e. it is a leaf task in the DAG)
Since Task A had no expanded tasks, its children were actually normal tasks (Task B) instead of the expected expanded tasks. Since we previously used a "shortcut" by skipping over the expanded tasks (i.e. queuing only the children of children of TaskGroup nodes), we never considered Task B.
Since we can't tell when a TaskGroup's children are expanded tasks or normal tasks, we remove our use of the "shortcut" and always queue all children of TaskGroups. This is …
=> fix: Consider all children of TaskGroups in DAGs

docs/resource-duration.md
The documentation talks about 100mi as default but 1Gi as denominator. This PR fixes this typo
---
Checklist:
=> docs: memory base amount denominator documentation

.github/workflows/ci-build.yaml, .gitignore, Makefile
This should fix the problems with the `homebrew-core` build as proposed by @alexec in https://github.com/argoproj/argo/issues/3769
Checklist:
=> ci: static files not being built with Homebrew and dirty binary. Fixes #3769

docs/ide-setup.md
Workflow CRD's link is pointing to ClusterWorkflowTemplate CRD
Checklist:
=> docs: Amend link to the Workflow CRD. Fixes #3578

.github/workflows/docker-image.yml
Checklist:
Hopefully finally closes #2080
=> ci: Changed tagging and amend multi-arch manifest

ui/src/app/workflows/components/workflows-list/workflows-list.tsx
=> fix(ui): use absolute URL to redirect from autocomplete list. Closes #3903

util/retry/retry.go, workflow/executor/executor.go
Replace default retry in executor with an increased value retryer.
https://github.com/argoproj/argo/pull/3675 added a pod watch retry to handle timeout.
We need to increase this retry value to several other places. e.g. the wait container could timeout requests to etcd during wait.
We are experimenting the following error with argo-workflow 2.10.0. 
```
time="2020-08-28T16:02:23.208Z" level=info msg="Waiting on main container"
time="2020-08-28T16:02:23.702Z" level=info msg="main container started with container ID: 17ec51e28b2a528c7c5238b5858e3d3a19c8c2f599f6c4950690da0f5a5c641a"
time="2020-08-28T16:02:23.702Z" level=info msg="Starting annotations monitor"
time="2020-08-28T16:02:23.709Z" level=info msg="Waiting for container 17ec51e28b2a528c7c5238b5858e3d3a19c8c2f599f6c4950690da0f5a5c641a …
```
=> fix(executor): Replace default retry in executor with an increased value retryer

ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Fixes: https://github.com/argoproj/argo/issues/3904
Checklist:
=> fix: Fix children is not defined error

api/openapi-spec/swagger.json, api/openapi-spec/swagger_test.go, docs/swagger.md, pkg/apis/workflow/v1alpha1/item.go, test/e2e/argo_server_test.go
=> fix(swagger): Correct item type. Fixes #3926

docs/metrics.md
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
Checklist:
This is is a bug fix.
Fixes: https://github.com/argoproj/argo/issues/3841
=> fix(docs): Correct indentation to display correctly docs in the website

cmd/argo/commands/server.go
fix: typo of argo server cli (#3984)
Checklist:
=> fix: typo of argo server cli (#3984)

manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/namespace-install/workflow-controller-rbac/workflow-controller-role.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
When using PVC with the rendered manifests, we run into this error:
```
User "system:serviceaccount:workflows:argo" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "argo"
```
Checklist:
=> fix: argo-cluster-role pvc get

workflow/controller/controller.go, workflow/controller/operator.go, workflow/metrics/metrics.go, workflow/metrics/metrics_test.go
Fixes: https://github.com/argoproj/argo/issues/3992
Still needs testing
=> fix: Delete realtime metrics of running Workflows that are deleted

workflow/controller/operator.go
I have a very limited understanding of what is going on here. But it seems the synchronization code could use `processedTmpl` with all the interpolations applied instead of raw `resolvedTmpl`.
Also `TryAcquire` piece seems inconsistent as the condition checks `processedTmpl.Synchronization` but then `resolvedTmpl.Synchronization` is passed instead.
Checklist:
=> fix(controller): use interpolated values for mutexes and semaphores. Fixes #3955

docs/windows.md, docs/workflow-executors.md
Triggered by https://github.com/argoproj/argo/issues/4009 and https://github.com/argoproj/argo/issues/3682 I added additional information to the docs on artifacts and limitations when using Windows containers.
Checklist:
=> docs(Windows): Add more information on artifacts and limitations

docs/argo-server-sso.md
Clarify that the user ought to create k8s secrets to hold the OAuth2 config values.
See related [enhancement proposal](https://github.com/argoproj/argo/issues/4069).
Checklist:
=> docs: Update SSO docs to clarify the user must create K8S secrets for holding the OAuth2 values

USERS.md, util/logs/workflow-logger.go
=> fix(server): Optional timestamp inclusion when retrieving workflow logs. Closes #4033

Dockerfile.windows, USERS.md, workflow/common/util.go, workflow/executor/docker/docker.go, workflow/executor/executor.go
This is a preliminary change to fix #4082. 
After this change the following happens:
```
time="2020-09-21T11:59:10.713Z" level=info msg="Saving output artifacts"
time="2020-09-21T11:59:10.714Z" level=info msg="Staging artifact: render-files"
time="2020-09-21T11:59:10.714Z" level=info msg="Copying /render/ from container base image layer to \\tmp\\argo\\outputs\\artifacts\\render-files.tgz"
time="2020-09-21T11:59:10.714Z" level=info msg="Archiving fe5574c11e503bf7d7fe00202990d70f81f7d995867dd02d229623b41909a18b:/render/ to \\tmp\\argo\\outputs\\artifacts\\render-files.tgz"
time="2020-09-21T11:59:10.715Z" level=info msg="cmd /c docker cp -a fe5574c11e503bf7d7fe00202990d70f81f7d995867dd02d229623b41909a18b:/render/ - | gzip -1 > \\tmp\\argo\\outputs\\artifacts\\render-files.tgz" …
```
=> fix(executor): windows output artifacts. Fixes #4082

.github/workflows/docker-image.yml
Like mentioned in https://github.com/argoproj/argo/issues/4062#issuecomment-694635885 I did the following to fix #4062:
- Leverage the buildx GitHub action to simplify setup of buildx
- Using a build matrix for building each target (`workflow-controller`, `argocli`, `argoexec`) on each Linux platform (`linux/amd64`, `linux/arm64`) in parallel.
- Using caching for buildx
This brings down the build time to around 40 min. This is still not super fast but better than 2h. The main bottleneck are the ARM64 images which require emulation for building (a single image takes around 39mins vs. 6mins for AMD64).
Could we get native ARM64 machines through CNCF (https://www.cncf.io/services-for-projects/#continuous-integration)? We could use them as self-hosted GitHub runners.
Test run: …
=> chore(build): Use build matrix and cache. Fixes #4062

manifests/namespace-install.yaml, manifests/namespace-install/argo-server-rbac/argo-server-role.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
Since https://github.com/argoproj/argo/pull/3116 allowed submitting `Cronworkflows` from UI, the `argo-server-role` role has to be updated for namespaced installations to actually allow the operation on kubernetes clusters with more strict RBAC like OpenShift.
Otherwise you'd get similar message to https://github.com/argoproj/argo/issues/922 :
```
time="2020-09-23T14:46:44Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = workflows.argoproj.io \"XYZ\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" grpc.code=PermissionDenied grpc.method=SubmitWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-09-23T14:46:44Z" grpc.time_ms=44.759 …
```
=> fix(server): argo-server-role to allow submitting cronworkflows from UI

docs/running-locally.md
In the latest version of k3d, the command for getting a cluster has been updated.
Checklist:
=> fix(docs): Update k3d command for running argo locally

cmd/argo/commands/delete.go, test/e2e/cli_test.go
run `argo delete` command without arguments and no output, want output helpfunc. 
```
0
```
Checklist:
=> fix(cli): add validate args in delete command

docs/variables.md, mkdocs.yml
Checklist:
~I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~
~My builds are green. Try syncing with master if they are not.~
=> docs: Include minimal reference for templating mechanism

.github/workflows/docker-image.yml
This is pre-pushing a temporary manifest to DockerHub referencing the linux/amd64 images right after those are built so we can release earlier without having to wait for the long-running arm64 image builds. After all images finished building the temporary manifest is overwritten with a new one with references to all images for amd64, arm64 and windows.
Details: 
1. Building and pushing all images for linux/amd64, e.g. `argoproj/argoexec:v2.11-linux-amd64` - this will only take around 6minutes
2. Create and push the manifest and reference only the linux/amd64 images yet, e.g. `argoproj/argoexec:v2.11` referencing only `argoproj/argoexec:v2.11-linux-amd64` for now
3. When all other images for Windows and linux/arm64 finished building after 40mins, we update and push the manifest overwriting …
=> chore(build): Pre-push temporary manifest with linux/amd64. Fixes #4062

ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
Fixes: #3754
From `examples/exit-handlers.yaml`
=> fix(ui): Render children of workflow-level onExit. Fixes #3754

ui/src/app/shared/services/workflows-service.ts, ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
When the API finishes streaming logs from a given container, it's normal for
the server to close the connection which results in an error being emitted in the browser.
When one of those errors is received, we check whether or not the node is still pending or
running which allows us to differentiate between a disconnection that happens due to a network
error, and a disconnect that happens due to the completion of log streaming.
Fixes #4117
Checklist:
=> fix(ui): handle logging disconnects gracefully. Fixes #4117

.github/workflows/docker-image.yml
Like discussed the pull error from #4216 seems to be caused by a rare corner-case where the Docker Hub failed somehow when the image was pushed. I don't think a specific change broke it as pulling the `latest`-images did work even before the revert of #4127.
- I re-added the changes from #4127 which you reverted
- I added a step which tries pulling all linux/amd64 and windows images after publishing to avoid such errors in the future
Example run: https://github.com/lippertmarkus/argo/actions/runs/289933647
You may also want to cherry-pick this to `release-2.11`.
Checklist:
=> chore(build): re-add #4127 and steps to verify image pull

workflow/controller/operator.go
Example: 
Example log:
```
time="2020-10-05T14:02:48-07:00" level=info msg="Pod failed" displayName="retry-container-v2n8p(0)" namespace=argo pod=retry-container-v2n8p-2124340039 templateName=retry-container workflow=retry-container-v2n8p
```
=> chore: Enahnce logging around pod failures

cmd/argo/commands/delete.go, cmd/argo/commands/list_test.go, util/printer/workflow-printer.go, util/printer/workflow-printer_test.go
=> feat(cli): Print 'no resource msg' when `argo list/delete` returns zero workflows

docs/swagger.md
Checklist:
Our doc are not being deployed due to this warning:
```
WARNING -  Documentation file 'rest-api.md' contains a link to 'swagger.md' which is not found in the documentation files. 
```
https://github.com/argoproj/argo/runs/1216143545?check_suite_focus=true
=> docs: Reinstate swagger.md so docs can build.

.github/workflows/ci-build.yaml, Makefile, USERS.md
Checklist:
PR related to: https://github.com/argoproj/argo/issues/4206
Removed the `if` clause completely coz `k3d start` doesn't mean anything there and `make start` seems to be alright, brings up both `argo-server` and `workflow-controller`. As for `github/workflow/ci-build.yaml` I don't think it's needed, coz I don't see any `k3d` commands in there, only `make start` ones which should be fine?
Also, changed context check as k3d prefixes `k3d-` to any cluster which user created and updates kubeconfig automatically.
=> fix(Makefile): removed deprecated k3d cmds. Fixes #4206

manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml, manifests/install.yaml
The aggregate roles in `cluster-install/workflow-controller-rbac` were missing `WorkflowEventBinding` CRD. - This PR should fix that.
Note: I don't know if `workfloweventbinding/finalizers` are even a thing, but I'm including them anyways. 
Checklist:
=> fix: Add WorkflowEventBinding to aggregated roles

cmd/argo/commands/delete.go, docs/cli/argo_delete.md, test/e2e/cli_test.go
Checklist:
Add to support `--field-selector` option for `delete` command.
This PR is separated from argoproj/argo#3962.
=> feat(cli): Add the field selector option for delete command

workflow/controller/dag.go, workflow/controller/operator_concurrency_test.go
=> fix(controller): Synchronization lock didn't release on DAG call flow Fixes #4046

workflow/controller/operator.go, workflow/controller/operator_test.go
=> fix(controller): Fix argo retry with PVCs. Fixes #4275

manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml, manifests/install.yaml
@alexec I'm really sorry, it seems in https://github.com/argoproj/argo/pull/4268 I've introduced a typo making the whole PR a nonsense. Resources listed roles must be in plural form, otherwise it doesn't work... :facepalm: 
Checklist:
=> fix: WorkflowEventBinding typo in aggregated roles

workflow/cron/operator.go, workflow/cron/operator_test.go
Checklist:
The `ResourceVersion` checks made the assumption that the corn operation context is used only once. It is wrong, it is used many times - each time `Run` is invoked. This change instead uses `Patch` to update the cron workflow status. I believe that, unlike for a workflow, this is safe because all the status fields can be patched safely.
=> fix(controller): Patch rather than update cron workflows.

ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/shared/components/resource-editor/resource-editor.tsx, ui/src/app/shared/examples.ts, ui/src/app/workflow-templates/components/workflow-template-list/workflow-template-list.tsx, ui/src/app/workflows/components/workflows-list/workflows-list.tsx
=> feat(ui): Submit resources without namespace to current namespace. Fixes #4293

Makefile
Checklist:
I use the default `GOPATH`, i.e. `${HOME}/go`. The original Makefile required `GOPATH` to be set. However if it is not set you get this error:
```bash
/bin/staticfiles -o server/static/files.go ui/dist/app
make: /bin/staticfiles: No such file or directory
make: *** [server/static/files.go] Error 1
```
If it is not set we can use `go env GOPATH`.
I also got this error trying to build with `make` using Go `1.15.2`:
```bash
go install ./vendor/sigs.k8s.io/controller-tools/cmd/controller-gen
without -mod=vendor, directory /Users/ids/projects/argo/vendor/sigs.k8s.io/controller-tools/cmd/controller-gen has no package path
make: *** [/Users/ids/go/bin/controller-gen] Error 1
```
I fix this by adding `-mod=vendor` to the `go install` command.
Some whitespace fixes (trailing whitespace, …
=> fix(build): Some minor Makefile fixes

SECURITY.md
=> docs: Fix incorrect link to static code analysis document

cmd/argo/commands/template/lint.go, test/e2e/cli_test.go
=> fix(cli): Fix panic on argo template lint without argument

ui/src/app/cron-workflows/components/cron-workflow-details/cron-workflow-details.tsx
#4164
This corrects the only violations of `strictFunctionTypes` found in this project, although we still need to fix those errors in upstream libs like `argo-ui` before we can potentially enable that option here.
=> fix(ui): correct typing errors in cron-workflow-details

examples/README.md
The "resource" keyword should be a child of the template.  Not the "inputs" value.
This incorrect indentation will cause an error during an `argo submit` execution, like the one below.
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "resource"
Checklist:
=> docs: Update pvc example with correct resource indentation. Fixes #4330

workflow/common/util.go, workflow/executor/executor.go
=> fix(executor): Increase pod patch backoff. Fixes #4339

Makefile
/etc/hosts can use tabs to separate records so we should match for it.
Checklist:
* [b] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
=> Use '[[:blank:]]' instead of ' ' to match spaces/tabs

api/openapi-spec/swagger.json, pkg/apis/workflow/v1alpha1/cron_workflow_types.go, pkg/apis/workflow/v1alpha1/generated.proto, pkg/apis/workflow/v1alpha1/openapi_generated.go
PR #4357 introduced a change to some generated documentation, but did not update the associated
comment in code, so CI would continually fail on the codegen step.  This updates the comment to match
what the desired docs are.
=> chore: match code comments to the generated documentation

Makefile
Checklist:
I find that having `vendor` around slows down Intellij appreciably.
=> build: Remove `vendor` at end of `codegen`

workflow/sync/semaphore.go
=> fix(controller): Enqueue the front workflow if semaphore lock is available

Makefile, manifests/base/argo-server/argo-server-deployment.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml, server/artifacts/artifact_server.go
=> fix(server): Download artifacts from UI. Fixes #4338

workflow/controller/operator.go
Fixes: https://github.com/argoproj/argo/issues/4381
Checklist:
=> fix: Use correct template when processing metrics

docs/variables.md, workflow/controller/steps.go, workflow/controller/steps_test.go
Fixes: https://github.com/argoproj/argo/issues/4402
~**Still needs tests**~
Checklist:
=> fix: Ensure resourceDuration variables in metrics are always in seconds

docs/workflow-concepts.md
The old link points to a missing page. This uses a newer spec version but the page does exist.
Checklist:
=> fix(docs): update link to container spec

cmd/argo/commands/cron/get.go, cmd/argo/commands/cron/get_test.go, cmd/argo/commands/cron/list.go, cmd/argo/commands/cron/root.go, cmd/argo/commands/cron/util.go, docs/cron-workflows.md, pkg/apis/workflow/v1alpha1/cron_workflow_types.go, ui/src/app/cron-workflows/components/cron-workflow-summary-panel.tsx
Fixes: https://github.com/argoproj/argo/issues/4325
**WIP**
Checklist:
=> fix: Assume controller is in UTC when calculating NextScheduledRuntime

ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx
Fixes #4264 
Shows the suspended CronWrokflows inside the list. 
Pause icon if suspended, clock icon if not (same icon as previously)
Checklist:
=> feat(ui): Visualisation of the suspended CronWorkflows in the list. Fixes #4264

Dockerfile, hack/nsswitch.conf
Add nsswitch.conf to resolve hosts in /etc/hosts. When cgo is disabled argo server is unable to resolve localhost. Go will fallback to check `/etc/nsswitch.conf`. We set nsswitch.conf to first check /etc/hosts and then dns.
=> fix: localhost not being resolved. Resolves #4460, #3564

ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx
We recently had Argo UI (v2.11.7) crash with the following error when trying to show hidden nodes:
```
Cannot read property 'length' of undefined
Reload this page to try again.
Stack Trace
TypeError: Cannot read property 'length' of undefined
at t.hiddenNode (https://argo.intacct.training.sail.sagedatacloud.com/main.44d1c937d2b2bb2c533b.js:478:443061)
at t.generateEdge (https://argo.intacct.training.sail.sagedatacloud.com/main.44d1c937d2b2bb2c533b.js:478:441687)
at https://argo.intacct.training.sail.sagedatacloud.com/main.44d1c937d2b2bb2c533b.js:478:440362
at Array.forEach (<anonymous>)
at t.layoutGraphPretty (https://argo.intacct.training.sail.sagedatacloud.com/main.44d1c937d2b2bb2c533b.js:478:440321)
at t.layoutGraph (https://argo.intacct.training.sail.sagedatacloud.com/main.44d1c937d2b2 …
```
=> fix(ui): Check node children before counting them.

workflow/controller/operator.go, workflow/controller/workflowpod_test.go
Signed-off-by: ivancili <ivandotilic@gmail.com>
Checklist:
Resolves #4481
=> fix(controller): prepend script path to the script template args. Resolves #4481

cmd/argo/commands/common.go, cmd/workflow-controller/main.go
Adding millisecond-level timestamps in follow-up to #2795 so that we have them everywhere and not just in argoexec. Thanks to @astein-te for implementing the original feature request.
=> feat: adds millisecond-level timestamps to argo and workflow-controller

manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml, manifests/install.yaml, manifests/namespace-install.yaml, manifests/namespace-install/argo-server-rbac/argo-server-role.yaml, manifests/quick-start-minimal.yaml, manifests/quick-start-mysql.yaml, manifests/quick-start-postgres.yaml
In 2.12.0-rc1 when using SSO RBAC - argo fails to create the secret, due to missing permissions in the argo-server-role
https://github.com/argoproj/argo/blob/0931baf5fbe48487278b9a6c2fa206ab02406e5b/server/auth/sso/sso.go#L135-L138
=> fix(server): Add `list sa` and `create secret` to `argo-server` roles. Closes #4526

server/auth/sso/sso.go, server/auth/sso/sso_test.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Checklist:
Fixes #3873
=> feat(controller): make SSO session expiry configurable

ui/src/app/shared/components/error-notice.tsx
=> fix(ui): Do not auto-reload doc.location. Fixes #4530

workflow/controller/operator_wfdefault_test.go
=> fix(test): fix TestWFDefaultWithWFTAndWf flakiness

workflow/metrics/util.go, workflow/validate/validate.go, workflow/validate/validate_test.go
=> fix: Validate metric key names

workflow/executor/pns/pns.go, workflow/executor/pns/pns_test.go
Checklist:
In several environments, where docker is used **and** the kubelet and docker are managed by systemd, the cgroup line has a `docker-` prefix. [Here](https://github.com/cri-o/cri-o/issues/842#issuecomment-327428272) is a table of the possible combinations and the resulting cgroup lines.
This PR fixes the behaviour and removes all possible "\*-" prefixes, like "docker-*" in systemd controlled docker/kubelet environments.
Failing example before the fix:
```
time="2020-11-18T12:10:04.158Z" level=info msg="containerID docker-4bb908294439e857f63daec791892a3dddace0cd02bec10fe3f1c5d91589d31f mapped to pid 39"
time="2020-11-18T12:10:04.158Z" level=warning msg="Failed to get main PID: Failed to determine pid for containerID 4bb908294439e857f63daec791892a3dddace0cd02bec10fe3f1c5d91589d31f: …
```
=> fix: executor/pns containerid prefix fix

manifests/README.md
Updated kubectl apply command in manifests README from kubectl install which was a typo.
=> docs: Updated kubectl apply command in manifests README

util/env/env.go, util/env/env_test.go, workflow/controller/operator.go
Checklist:
This change is to test to see if increasing this improve issues like #4560
=> feat(controller): Make MAX_OPERATION_TIME configurable. Close #4239

pkg/apis/workflow/v1alpha1/workflow_types.go, server/artifacts/artifact_server.go, server/artifacts/artifact_server_test.go, workflow/artifacts/artifacts.go
When artifacts are uploaded to whatever repository is in use, they're stored
under a key that includes both the intended file name as well as the extension
to use based on whether or not compression was used when it was created.
Use that key as the file name when returning artifacts for download rather than
just "filename.tgz", that way we don't incorrectly identify non-compressed artifacts
as compressed tarballs.
Fixes #4252
=> fix(server): use the correct name when downloading artifacts

server/artifacts/artifact_server.go
When serving very large artifacts, first loading them into memory can potentially
cause the pod to go OOM/crash depending on how much memory is available and what
limits have been set.  Rather than loading it into memory, we can serve files
directly from disk.
Fixes #4588
=> fix(server): serve artifacts directly from disk to support large artifacts

workflow/validate/validate.go, workflow/validate/validate_dag_test.go
Fixes https://github.com/argoproj/argo/issues/4570. Related https://github.com/argoproj/argo/issues/4199. It looks like `dependencies` is first converted into `depends` to support backwards compatibility ([related code](https://github.com/argoproj/argo/blob/4531d7936c25174b3251e926288866c69fc2dba3/workflow/common/ancestry.go#L100-L127)) so either 'depends' or 'dependencies' should fail the validation. 
Checklist:
=> fix(controller): Prevent tasks with names starting with digit to use either 'depends' or 'dependencies'

util/fields/fields.go, util/fields/fields_test.go
=> fix: Fix TestCleanFieldsExclude

workflow/executor/executor.go
Currently if we use k8sapi or kubelet executor with output parameters from base image layer, e.g. `/tmp`, we will see the following warning: 
```
Warning  WorkflowNodeError      9s    workflow-controller  Error node couler-test-2[1].heads-114: failed to save outputs: open /mainctrfs/tmp/dummy.txt: no such file or directory
```
This is a bit misleading and not informative to users.
Checklist:
=> feat(executor): More informative log when executors do not support output param from base image layer

workflow/controller/controller.go, workflow/controller/indexes/labels.go, workflow/controller/indexes/labels_test.go
Fixes https://github.com/argoproj/argo/issues/4551
Checklist:
=> fix: Count Workflows with no phase as Pending for metrics

.gitignore, ui/src/app/shared/components/drop-down-button.scss, ui/src/app/shared/components/drop-down-button.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
This bugged me and was easy to fix. I tidied up the link button too.
https://share.getcloudapp.com/E0u4zl29
Checklist:
=> feat(ui): Replace 3 buttons with drop-down

ui/src/app/reports/components/reports.tsx, ui/src/app/shared/components/data-loader-dropdown.tsx, ui/src/app/workflows/components/workflow-filters/workflow-filters.tsx
DataLoaderDropdown fix input type from promise to function that returns promise 
so that promise only gets executed in the child component instead of everywhere..
Sorry about all the trouble
Checklist:
Fixes #4654
=> fix(ui): DataLoaderDropdown use function=> promise instead of promise. Fixes #4654 

cmd/argo/commands/cron/list.go, cmd/argo/commands/delete.go, cmd/argo/commands/list.go, cmd/argo/commands/template/list.go, docs/cli/argo_cron_list.md, docs/cli/argo_delete.md, docs/cli/argo_list.md, docs/cli/argo_template_list.md
Feature: Add shorthanded option -A for --all-namespaces
Signed-off-by: makocchi-git <makocchi@gmail.com>
kubectl's --all-namespaces has an shortened alias -A.
It would be nice if argo has the same alias.
=> feat(cli): Add shorthanded option -A for --all-namespaces

cmd/argo/commands/stop.go, cmd/argo/commands/terminate.go, docs/cli/argo.md, docs/cli/argo_stop.md, docs/cli/argo_terminate.md
Checklist:
Adding more information on Cobra short helper and cli docs.
Ref https://github.com/argoproj/argo/issues/4454
=> docs: Add more information about terminate and stop process

ui/package.json, ui/src/app/cron-workflows/components/cron-workflow-list/cron-workflow-list.tsx, ui/src/app/cron-workflows/components/cron-workflow-summary-panel.tsx, ui/src/app/shared/components/duration-panel.tsx, ui/src/app/shared/cron.tsx, ui/yarn.lock
=> feat(ui): add countdown to cronWorkflowList Closes #4636

ui/src/app/userinfo/components/cli-help.tsx, ui/src/app/userinfo/components/user-info.tsx
Closes https://github.com/argoproj/argo/issues/4630
Checklist:
=> feat(ui): Make it easy to use SSO login with CLI. Resolves #4630

config/config.go, workflow/controller/workflowpod.go, workflow/controller/workflowpod_test.go
Some clusters require explicit resources in all containers. This would allow us to configure the resources for the main container.
Checklist:
=> feat(controller): Allow to configure main container resources

ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-panel/workflow-panel.tsx, ui/src/app/workflows/components/workflow-timeline/workflow-timeline.tsx
=> fix(ui): Fixed reconnection hot-loop. Fixes #4580

workflow/controller/steps.go, workflow/controller/steps_test.go
Fixes https://github.com/argoproj/argo/issues/4647
Checklist:
=> fix: Consider optional artifact arguments

workflow/controller/operator.go, workflow/metrics/pod_missing_metric.go, workflow/metrics/server.go
=> feat(controller): Pod deletion grace period. Fixes #4719

workflow/executor/common/wait/wait.go
Checklist:
Tested manually by adding a couple of lines to reduce the api timeout to ~20 seconds and then running a tweaked hello-world workflow with a sleep 60. Ideally this would be an e2e test, but in your youtube contributor video you mentioned needing all the e2e tests to run in under 10 minutes. I'm not sure how much you could compress the times and still have a reliable test for this, so I haven't added an end to end test. Opinions welcome.
=> fix(executor): Deal with the pod watch API call timing out

server/auth/gatekeeper.go, server/auth/mode.go, server/auth/mode_test.go
Fixes https://github.com/argoproj/argo/issues/4400
Checklist:
=> fix(server): Allow Bearer token in server mode. Fixes #4400

docs/argo-server-sso.md
I am fairly certain this is the correct place for this documentation update but would like to know if there are more places to update as well as this took me quite a while to figure out.
Checklist:
=> docs: Update SSO docs to explain how to use the Argo CD Dex instance with Argo Workflows Server

workflow/controller/workflowpod.go
This is cherry-picked from my colleague's stale PR https://github.com/argoproj/argo/pull/4432 as well as applying a similar change to main container's resource copying logic. cc @simster7 @alexec 
Co-authored-by: merlintang <tangrock@gmail.com>
Checklist:
=> fix(executor): Copy main/executor container resources from controller by value instead of reference

workflow/executor/resource.go
This is cherry-picked from my colleague's stale PR https://github.com/argoproj/argo/pull/4433 as well as address remaining comments from maintainers to move the logic to top of the for loop. cc @simster7 @alexec
Signed-off-by: terrytangyuan terrytangyuan@gmail.com
Co-authored-by: merlintang tangrock@gmail.com
Checklist:
=> fix(executor): Always check if resource has been deleted in checkResourceState()

cmd/workflow-controller/main.go, docs/scaling.md, test/e2e/fixtures/then.go, test/e2e/functional_test.go, workflow/controller/controller.go, workflow/metrics/metrics_test.go, workflow/ttlcontroller/ttlcontroller.go, workflow/ttlcontroller/ttlcontroller_test.go
=> feat(controller): Enhanced TTL controller scalability

pkg/apis/workflow/v1alpha1/workflow_types.go, workflow/controller/steps.go, workflow/sync/mutex_test.go
=> fix(controller): Fixed workflow stuck with mutex lock

workflow/controller/operator.go
=> fix(controller): Requeue when the pod was deleted. Fixes #4719

cmd/argo/commands/wait.go, cmd/argo/commands/watch.go, server/workflow/workflow_server.go, ui/src/app/shared/services/requests.ts, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, util/logs/workflow-logger.go
=> fix(controller): Fixes resource version misuse. Fixes #4714

test/e2e/argo_server_test.go, test/e2e/cli_test.go, test/e2e/fixtures/given.go, test/e2e/fixtures/when.go, test/e2e/functional_test.go, test/e2e/testdata/sleepy-workflow.yaml
=> test: Improved e2e test robustness

config/config.go, config/config_test.go, persist/sqldb/sqldb.go
=> fix(controller): Support default database port. Fixes #4756

Dockerfile, Dockerfile.dev
Checklist:
The self-signed key bundled in the argocli image cannot be used.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: argo-server
spec:
selector:
matchLabels:
app: argo-server
template:
metadata:
labels:
app: argo-server
spec:
serviceAccountName: argo-server
containers:
- name: argo-server
image: argoproj/argocli:v2.11.8
securityContext:
capabilities:
drop:
- ALL
args:
- server
- --configmap
- argo-server-cm
- --auth-mode
- sso
- --secure
ports:
- name: web
containerPort: 2746
readinessProbe:
httpGet:
port: 2746
scheme: HTTP
path: /
initialDelaySeconds: 10
periodSeconds: 20
volumeMounts:
- mountPath: /tmp
name: tmp
volumes:
- name: tmp
emptyDir: { }
securityContext:
runAsUser: 8737 # argo UID
runAsGroup: 8737 # argo UID
nodeSelector:
kubernetes.io/os: linux
```
Here's …
=> fix(server): Update argo-server crt/key owner

workflow/controller/operator.go, workflow/controller/operator_test.go
fixes #2637
Support Unix Time format in `workflow.creationTimestamp` variable.
Checklist:
=> feat(controller): unix timestamp support on creationTimestamp var

server/auth/sso/sso.go
=> fix(server): Do not silently ignore sso secret creation error

examples/example-golang/main.go
The workflow in the current example would only exit the loop when it reaches completion. It's better to exit loop immediately when the workflow has failed. 
Checklist:
=> chore(example): Add watch timeout and print out workflow status message

cmd/argo/main.go, cmd/argoexec/main.go, cmd/workflow-controller/main.go, test/e2e/fixtures/e2e_suite.go
Signed-off-by: kristoffer johansson <johanson.kristoffer@gmail.com>
Fix for loading authentication plugins for k8s client-go. Import all supported plugins instead of specific ones. Closes (#4531)
=> fix: load all supported authentication plugins for k8s client-go

cmd/argo/commands/node.go, docs/cli/argo_node.md
Checklist:
This adds the missing 'phase' command to the node cli command, eg:
```argo node set my-wf --node-field-selector displayName=approve --phase Succeeded```
would set the phase for the suspend node with displayName=approve to Succeeded
=> feat(cli): add phase option to `node set` command

Makefile, go.mod, go.sum
The new version incorporates a couple of important bug fixes and performance optimizations.
Checklist:
=> chore: Bump OSS Go SDK to v2.1.5

util/slice/slice.go
=> fix(controller): Preserve the original slice when removing string

.github/workflows/docker-image.yml
=> feat: Publish images on Quay.io

docs/variables.md, workflow/common/common.go, workflow/controller/steps.go, workflow/controller/steps_test.go
An `exitCode` from each step can be referenced as an output value since https://github.com/argoproj/argo/pull/2111. It would be nice if we can use the same value in the step/task-level metrics.
This PR maps the `node.Outputs.ExitCode` to a `exitCode` variable within the local scope of the metrics. This follow the variable scheme used for steps and task where the exit code is put on the same level as phase status (`steps.<STEPNAME>.exitCode`) and not within the `outputs.*` scope (like `outputs.result` for example).
Checklist:
=> feat: Expose exitCode to step level metrics

.github/workflows/ci-build.yaml, Makefile
=> fix(controller): Add matrix tests for node offload disabled. Resolves #2333

workflow/cron/operator.go
Fixes https://github.com/argoproj/argo/issues/4868
=> fix: Do not error on duplicate workflow creation by cron

USERS.md, workflow/creator/creator.go, workflow/creator/creator_test.go
Fixes https://github.com/argoproj/argo/issues/4880
Checklist:
* [x ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
=> fix(controller): make creator label DNS compliant. Fixes #4880

config/config.go, docs/workflow-controller-configmap.yaml, workflow/controller/config.go
=> feat(controller): optional database migration

ui/src/app/workflow-event-bindings/components/workflow-event-bindings/workflow-event-bindings.tsx
Super minor typo fix.  The URL will still be valid in a browser with `::`, but still good to correct.
=> fix(ui): removing unneeded ':' in protocol for workflow-event-bindings

.github/workflows/ci-build.yaml, Makefile, Procfile, workflow/controller/controller_test.go, workflow/controller/operator_test.go, workflow/controller/workflowpod_test.go
* on a dev machine `make start` will automatically start the UI if you have `yarn` installed
* test refactoring
Checklist:
=> build: on a dev branch automatically start the UI

ui/src/app/workflows/components/workflow-details/workflow-details.tsx
=> fix(ui): Fix workflow refresh bug

ui/src/app/shared/components/object-editor/object-editor.tsx
Fix UI
Issue:
- when switching tabs (other -> manifest) in template/cron wf detail views, the submit button becomes disabled despite no change in manifest
- when toggling yaml<->json in template/cron wf detail view manifest, the submit button becomes disabled despite no change in manifest
Change:
- only updates text when values are modified in monaco-editor
Checklist:
=> fix(ui): objecteditor only runs onChange when values are modified

test/e2e/functional/k8s-patch.yaml, test/e2e/functional_test.go, workflow/controller/operator.go, workflow/executor/resource.go, workflow/validate/validate.go
=> feat(controller): Support K8S JSON patch with resource template. Closes #4883

ui/src/app/shared/components/object-editor/object-editor.tsx
Fixed issue introduced by PR #4911
Sorry, the previous implementation is very buggy,
Issues:
object-editor
- unable to create newline, due to rendering text with stringify removes all empty lines
- duplicate render, text was first rendered by monaco, then the rendered text got rendered again by useEffect hook
Changed:
base on the pre #4911 code, add an additional isModified hook to trigger initial onChange
Checklist:
=> fix(ui): fix object-editor text render issue

.golangci.yml, Makefile, test/e2e/argo_server_test.go, test/e2e/cron_test.go, test/e2e/manifests/mysql/kustomization.yaml, test/e2e/metrics_test.go, test/e2e/smoke_test.go, ui/src/app/webpack.config.js
=> build: Faster `make start`, faster smoke jobs

ui/src/app/workflows/components/workflow-creator.tsx, ui/src/app/workflows/components/workflow-details/workflow-details.tsx, ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx
=> fix(ui): v3 UI tweaks

workflow/controller/controller.go, workflow/controller/operator_concurrency_test.go, workflow/sync/common.go, workflow/sync/mutex.go, workflow/sync/mutex_test.go, workflow/sync/semaphore.go, workflow/sync/sync_manager.go, workflow/sync/sync_manager_test.go
=> feat: Check the workflow is not being deleted for Synchronization workflow

docs/fields.md, examples/map-reduce.yaml, workflow/validate/validate.go, workflow/validate/validate_test.go
=> fix(cli): Update the map-reduce example, fix bug.

docs/node-field-selector.md, workflow/util/util.go, workflow/util/util_test.go
Fixes: https://github.com/argoproj/argo/issues/4910
=> fix(cli): Allow full node name in node-field-selector

test/e2e/cli_test.go, test/e2e/testdata/log-problems.yaml, util/logs/workflow-logger.go
=> fix(server): Fix missing logs bug
